### ISSUE TITLE
Include latitude/longitude on facilities

### ISSUE THREAD

**Issue by mcmanuss8** [peeringdb/peeringdb#1]
a) You can put 'em on a map easily.
b) You can show how close facilities are (or if they're in the same building as described.
c) You can use the lat / long to cluster facilities and fix missing CLII codes.

**Comment by grizz** [comment]
@52-41-4d mentioned he has scripts done for this already at peeringdb/docs/issues/65

**Comment by mcmanuss8** [comment]
@52-41-4d whatchya got? 
I was looking at https://github.com/openvenues/libpostal recently do to normalization of addresses. Unfortunately it doesn't give lat/long out of the box. :(

**Comment by 52-41-4d** [comment]
@mcmanuss8 Google has this awesome API (which I used for one of my projects!) that we can use for this. Please see the example script [here](https://github.com/52-41-4d/Misc/blob/master/Geocoder.java). Let me know if you have any questions.

**Comment by eloos** [comment]
I actually have the code written, it only borks on some Hindi/Japanese references, I'll send it to Matt
