### ISSUE TITLE
add notification e-mail address for IXP

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/peeringdb#10]
Add a notification e-mail address to IXP records. Whenever a networks joins / leaves a notification is sent to this address

**Comment by grizz** [comment]
As long as it's optional, I'm for this, as a single address

**Comment by eloos** [comment]
@grizz do you need more information to quote this? If i understand the request correctlyb @arnoldnipper, we want to generate (if the IXP has so configuered) an email when a network associates or disassociates themselves from an ixlan?

**Comment by arnoldnipper** [comment]
Exactly, @eloos

**Comment by arnoldnipper** [comment]
no longer needed as soon as we have the new conflict resolution process in place
