### ISSUE TITLE
Radius search doesn't work without a street address

### ISSUE THREAD

**Issue by grizz** [peeringdb/peeringdb#1004]
**Describe the bug**
Radius search doesn't work without a street address enteted.

**Expected behavior**
It should probably work with just the city.

**Comment by grizz** [comment]
After further testing, it appears this is limited to China.

**Comment by ynbrthr** [comment]
actually China mainland seems to be working. the issue is for searches on hk

**Comment by leovegoda** [comment]
If this is just related to HK, is this something we can resolve or is the fundamental issue the quality of the data available via public GIS databases?

**Comment by leovegoda** [comment]
I just tested again. It does not report an error when searching for facilities within a 25km radius of the city of Hong Kong in Hong Kong. I did the same thing for Monaco in Monaco and no errors there, either. A search for facilities within 25km of Beijing in China comes back with a list of results. 

I am not sure that there really is a bug here. It's possible that there was a temporary error and no underlying issue with the software.
