### ISSUE TITLE
Improve radius search

### ISSUE THREAD

**Issue by ynbrthr** [peeringdb/peeringdb#1005]
the new (and awesome) radius search requires one country, and one country only, to be selected in the very long country dropdown menu. e.g. with vienna:

<img width="772" alt="image" src="https://user-images.githubusercontent.com/58094221/125711414-b6fc1a94-2e97-4379-a281-e0666e76debb.png">

Simplify the workflow by displaying all records matching a city name, except if one has selected a specific country. If multiple countries are selected, return all the facilities in the cities matching those countries.

**Comment by leovegoda** [comment]
Might it be more helpful to dynamically reduce the list of countries based on the first few letters of the city name? For instance, if I type "Lond" the list of countries might be reduced to under 10, making it easier for me to direct my search?

**Comment by leovegoda** [comment]
@grizz is https://github.com/peeringdb/peeringdb/issues/1204 likely to address this?

**Comment by grizz** [comment]
> @grizz is #1204 likely to address this?

Yes, #1204 will cover this.

**Comment by leovegoda** [comment]
We can close this when we deploy https://github.com/peeringdb/peeringdb/issues/1392 and switch to v2 search

**Comment by leovegoda** [comment]
Closing as v2 search is now the default on the front page of www.peeringdb.com
