### ISSUE TITLE
Advanced Search does not show YRIX when searching for exchanges in Billings

### ISSUE THREAD

**Issue by leovegoda** [peeringdb/peeringdb#1006]
**Describe the bug**
In 2.28.0-beta an Advanced Search for exchanges in Billings, USA returns no results but there is an exchange there and it is listed at: https://beta.peeringdb.com/ix/199

**To Reproduce**
1) search for https://beta.peeringdb.com/advanced_search?city=Billings&country__in=US&reftag=ix or even
2) https://beta.peeringdb.com/advanced_search?city=Billings&country__in=US&reftag=ix 
3) examine results

**Expected behavior**
The YRIX ought to be returned to a search for exchanges in Billings, USA

**Who is affected by the problem?**
Potential peers at this exchange and maybe other exchanges if this issue is not specific to this exchange

**What is the impact?**
The exchange is hard to find if you don't already know it exists

**Are there security concerns?**
No

**Are there privacy concerns?**
No

**What are the proposed actions?**
Investigate why the exchange is not returned in the results

**What is the proposed priority?**
Fix for production release of 2.28

**Provide a rationale for any/all of the above**
Returning this exchange for this search is the intended outcome of the recent changes delivered via #23  

**Additional context**
None

**Comment by ynbrthr** [comment]
it's part of the ongoing work around 777 and derivatives. IXPs have no state field today, and some IXPs put it after the city name, and the search needs to be improved too.

**Comment by leovegoda** [comment]
OK. I'll close it as this one will be resolved through other work.
