### ISSUE TITLE
IPv4/6 prefixes field verification

### ISSUE THREAD

**Issue by robertjakub** [peeringdb/peeringdb#101]
do some kind of field verification on the webpage: the value of "IPv4/IPv6 prefixes" should not exceed the certain value. the net/10184 record has a IPv6 prefixes set to 4000000000 (it's more then unsigned int - the local sync to postgresql fails).

**Comment by robertjakub** [comment]
(since the problem still exist, and is minor) - I made a ugly hack in the django-peeringdb: https://github.com/robertjakub/django-peeringdb/commit/ab2c762397168ab63a5cc01c87347e5a1b9a110c to fix this issue. The real issue is the type of the info_prefixes[4|6] field. the PositiveIntegerField limits: sqlite: no checks, mysql: it's 64 bit value, postgresql: it's 32 bit value. (no sure for the others databases). (and I'm not sure - should it be None or MAXPREFIX if exceeded arbitrary selected value MAXPREFIX)

**Comment by vegu** [comment]
Implemented in `3972470` as a loose server side sanity check with the following limits

info_prefixes4 : 500000
info_prefixes6 : 50000

Limits are controlled by server configuration and can be adjusted as needed
