### ISSUE TITLE
AC is unable to add a new user 

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/peeringdb#1015]
**Describe the bug**
https://peeringdb.com/cp/peeringdb_server/user/add is asking for "Please fill out the anti-spam challenge (captcha) field". However, there is no such field.

**To Reproduce**
1. https://peeringdb.com/cp/peeringdb_server/user/add
2. Fill in information
3. Click on any of the save buttons

**Expected behavior**
Remove the requirement

**Who is affected by the problem?**
AC

**What is the impact?**
AC is not able to add users

**Are there security concerns?**
no

**Are there privacy concerns?**
no

**What are the proposed actions?**

**What is the proposed priority?**
normal

**Comment by peterhelmenstine** [comment]
+1 Remove the requirement for anti-spam challenge for already authenticated AC users makes sense.

**Comment by grizz** [comment]
Clear bug, moving to 3

**Comment by Juimar** [comment]
+1 Remove the requirement for anti-spam challenge

**Comment by vegu** [comment]
This has been fixed as part of #715 and will be going to beta this month, leaving the ticket open until then
