### ISSUE TITLE
DB

### ISSUE THREAD

**Issue by Steve9324** [peeringdb/peeringdb#1018]
#111> `[https://github.com/creativecommons/legaldb/pull/111#issue-705917249](GitHub) **Is` your feature request related to a problem? Please describe.**

**Who is affected by the problem?**

**What is the impact?**

**Are there security concerns?**

**Are there privacy concerns?**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Could this feature request need support from the Admin Committee?**
Consider if an administrator might need to provide assistance at any point.

**What is the proposed priority?**
simply urgent/not

**Provide a rationale for any/all of the above**

**Additional context**

**Comment by martinhannigan** [comment]
What is the context of this post? When I follow the github link I land on
what appears to be a copy and paste of a license agreement.

**Comment by grizz** [comment]
I'm going to go out on a limb and say this is bot spam :)

Please reopen with a more clear description if not.
