### ISSUE TITLE
IX-F Importer: needless saves to deleted netixlans

### ISSUE THREAD

**Issue by vegu** [peeringdb/peeringdb#1019]
**Describe the bug**

Sometimes the IX-F importer seems to re-save already deleted netixlan objects (basically changing their `updated` value and nothing else).

We should investigate why and when this happens and fix it.

**What is the impact?**

While there should be no operational impact from this, it does cause the following issues:

- redundant snapshots of the netixlan object saved to the object history
- the peeringdb-py client will see them as updated objects and pull them in again needlessly

**Comment by ccaputo** [comment]
@peeringdb/pc please expedite this bug.  It excessively grows the database and causes extra work for the peeringdb-py client.  Thanks!

**Comment by mcmanuss8** [comment]
+1  - seems like a straightforward bug
