### ISSUE TITLE
504 Gateway Time-out

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/peeringdb#1021]
**Describe the bug**
When calling https://peeringdb.com/cp/peeringdb_server/networkixlan/67436/history/ I get this error message. I've tried 3x with same result

**To Reproduce**
1. https://peeringdb.com/cp/peeringdb_server/networkixlan/67436/history/
2. See error

**Expected behavior**
The history should be shown

**Who is affected by the problem?**
@peeringdb/ac 

**What is the impact?**
AC is unable to see the history

**Are there security concerns?**
no

**Are there privacy concerns?**
no

**What are the proposed actions?**
fix

**What is the proposed priority?**
high

**Comment by arnoldnipper** [comment]
@peeringdb/ac, please confirm

**Comment by funkestefan** [comment]
Confirmed. Takes forever to load, results in 504 Gateway Time-out

**Comment by vegu** [comment]
Confirmed this to happen for `netixlans`, history for other objects like `net` seems to load correctly. (note: I haven't checked all entity types)

Checking the `netixlan` in question, it has 3 history entries total.

**Comment by vegu** [comment]
Does not happen for all netixlans either, https://peeringdb.com/cp/peeringdb_server/networkixlan/21608/history/ loads for example.

**Comment by arnoldnipper** [comment]
Moved to 3a as clearly identified as a bug by a developer

**Comment by mcmanuss8** [comment]
@arnoldnipper how urgently is this hampering AC work?

**Comment by arnoldnipper** [comment]
Which categories do we have for urgent :)

**Comment by mcmanuss8** [comment]
1) Breaking your ability to do your job
2) Very bothersome, but you have a workaround to still do your job OR it only happens very rarely
3) Annoying/cosmetic/slows you down a bit
