### ISSUE TITLE
Different footer on https://auth.peeringdb.com/account/login/?next=/

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/peeringdb#1025]
**Describe the bug**
Version and stats are missing on https://auth.peeringdb.com/account/login/?next=/

**To Reproduce**
1. Log out and then click on https://peeringdb.com/account/login/?next=/
2. Look at the footer

**Expected behavior**
Same footer as on all other pages

**Who is affected by the problem?**
all users

**What is the impact?**
no version and stats

**Are there security concerns?**
no

**Are there privacy concerns?**
no

**What are the proposed actions?**
fix

**What is the proposed priority?**
cosmetic

**regular footer**
![20210819 PeeringDB 01](https://user-images.githubusercontent.com/16888757/130057307-0568ebc3-f3f5-4833-b019-a7fd817f7b25.png)

**footer on login page**
![20210819 PeeringDB 00](https://user-images.githubusercontent.com/16888757/130057308-fb94e0be-7449-43c0-8fc8-ec15a3003b27.png)

**Comment by arnoldnipper** [comment]
@peeringdb/pc, please +1 as this imo clearly is a bug

**Comment by kaycliff** [comment]
+ 1

**Comment by leovegoda** [comment]
@arnoldnipper I've just logged in checked the footer at each step. It looks like the stats are shown at every stage, so some other change has probably fixed this. Can we close it?

**Comment by arnoldnipper** [comment]
fixed
