### ISSUE TITLE
Fallback captcha solution is broken

### ISSUE THREAD

**Issue by vegu** [peeringdb/peeringdb#1026]
**Describe the bug**

On the account sign up page: The fallback captcha solution that is supposed to provide an alternative captcha challenge for users unable to load the google recaptcha challenge appears to be currently broken.

This error is invisible to users for whom the normal google re-captcha challenge loads. 

On the backend we observe this message: 

`The _imagingft C module is not installed`

**Expected behavior**

If google re-captcha does not load (because your country has blocked it for example) a fallback captcha solution should be presented instead.

**Who is affected by the problem?**

People living in countries where google services are blocked trying to sign up for a peeringdb account, being unable to do so.

**Comment by arnoldnipper** [comment]
+1 ... and what do you propose as a fallback captcha solution, @vegu?

**Comment by vegu** [comment]
@arnoldnipper we already have one in place, its just not working currently, likely because the container is missing a dependency.

To be clear my proposal is to fix the current fallback solution not implement another separate fallback solution.

**Comment by grizz** [comment]
Pushing to 4, bug
