### ISSUE TITLE
Make the search field on cp/peeringdb_server/network/ aware of leading AS/ASN

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/peeringdb#1027]
**Is your feature request related to a problem? Please describe.**
Currently, searches only work if AC enters an ASN. However, often it's easier to c&p ASxxxxx or ASNxxxxx. If the system could strip leading AS/ASN as it does on the main user page that would greatly help @peeringdb/ac 

**Who is affected by the problem?**
AC

**What is the impact?**
Extra work

**Are there security concerns?**
no

**Are there privacy concerns?**
no

**Describe the solution you'd like**
Make the ASN search the same as on the regular user interface. I.e. strip leading AS/ASN

**What is the proposed priority?**
normal

**Additional context**
All ASN search fields should behave the same way. I.e. if there are additional search fields systemwide apply the same fix

**Comment by peterhelmenstine** [comment]
+1 love this idea. Wondering if this search field request could be expanded to be more like a industry search (not to prefer google) but most search algorithms as PeeringDB seems to be more strict than others. If this is out of scope for this request, happy to take this offline and into another request.

**Comment by Juimar** [comment]
+1 It would be useful

**Comment by netravnen** [comment]
+1

**Comment by vegu** [comment]
**summary**

- improve network search in django-admin to understand asn search with leading `AS` and `ASN` prefixes
