### ISSUE TITLE
soft & hard delete give server 500 error on duplicateipnetworkixlan tool

### ISSUE THREAD

**Issue by job** [peeringdb/peeringdb#103]
On the https://peeringdb.com/cp/peeringdb_server/duplicateipnetworkixlan/ tool, if you check one or more duplicate IP entries and click either "soft" or "hard" delete in the lower left, the server gives a `500` error and the records are not deleted.

**Comment by job** [comment]
It would also be nice if **All** entries can be shown on a single page instead of having to deal 8 pages of pagination

**Comment by vegu** [comment]
500 errors fixed in 13bde24

**Comment by vegu** [comment]
pagination removed in ab76e07
