### ISSUE TITLE
RDAP lookup buggy

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/peeringdb#1030]
**Describe the bug**
The tool can't find an entry for ASN 63791, though it exists

**To Reproduce**
See screenshots attached. To reproduce try to find unregistered JP ASN

**Expected behavior**
The tool should work 100% correct for all proper ASN

**Who is affected by the problem?**
Users with e.g. some JP ASN

**What is the impact?**
Users are unable to register the ASN

**Are there security concerns?**
no

**Are there privacy concerns?**
no

**What are the proposed actions?**
fix the tool

**What is the proposed priority?**
high, but not urgent

Attachments
Failed affiliation
![20210822 PeeringDB 00](https://user-images.githubusercontent.com/16888757/130365010-b62eadc2-1b61-420d-9746-5946797aeed9.png)

JP Whois
![Screenshot 2021-08-22 19 30 18](https://user-images.githubusercontent.com/16888757/130365029-c969ebc1-f238-484b-bb7b-f516b92a7203.png)

APNIC RDAP
![Screenshot 2021-08-22 19 39 22](https://user-images.githubusercontent.com/16888757/130365047-1b55e1e8-df16-40f7-bbb4-dc8d47ad124a.png)

**Comment by arnoldnipper** [comment]
@peeringdb/ac, did you also already run into this issue?

**Comment by grizz** [comment]
From the initial glance at this, it looks like something wrong on APNIC's side:

https://jpnic.rdap.apnic.net/autnum/63791

whois reports it as assigned, but it's also in the middle of an unassigned block, which I don't recall seeing before.

**Comment by arnoldnipper** [comment]
> whois reports it as assigned, but it's also in the middle of an unassigned block, which I don't recall seeing before.

Years ago, APNIC decided to subdelegate ASN chunks to NIRs (e.g. JPNIC, CNNIC, INNIC, IDNIC, KRNIC). And information is well documented in Whois. However, RDAP information seems to be broken. I.e. APNIC does not refer to the NIR. @peeringdb/ac has been in touch with APNIC already in 2019 (or even earlier). And they promise to fix it. Obviously, they are not yet there.

Hence, what can we do until then?

**Comment by martinhannigan** [comment]
The list of APNIC based NRIR's:


   - APJII (ID) <https://www.apjii.or.id/> - Indonesia
   - CNNIC (CN) <http://www1.cnnic.cn/index.htm> - China
   - IRINN (IN) <http://www.irinn.in/> - India
   - JPNIC (JP) <http://www.nic.ad.jp/> - Japan
   - KISA (KR) <https://www.kisa.or.kr/eng/main.jsp> - Korea
   - TWNIC (TW) <https://www.twnic.net.tw/> - Taiwan
   - VNNIC (VN) <http://www.vnnic.vn/en?lang=en/> - Vietnam

It shoulds like APNIC isn't very interested in fixing it as a priority.

I'm not certain if other RIR's provide for national RIR's. Would building a
reference resource table and sending the query direct to the NRIR improve
accuracy and reliability? The likelihood that the resources would change
are slim to none so this could be one-time work. The complication is
resource transfer which if my memory services me correctly is not honored
or allowed by the NRIR's. I am happy to dig into the data portion, I know
where to find it if it is interesting.

**Comment by grizz** [comment]
> > whois reports it as assigned, but it's also in the middle of an unassigned block, which I don't recall seeing before.
> 
> Years ago, APNIC decided to subdelegate ASN chunks to NIRs (e.g. JPNIC, CNNIC, INNIC, IDNIC, KRNIC). And information is well documented in Whois. However, RDAP information seems to be broken. I.e. APNIC does not refer to the NIR. @peeringdb/ac has been in touch with APNIC already in 2019 (or even earlier). And they promise to fix it. Obviously, they are not yet there.

Right, what I meant to say was, I don't recall seeing it reported as a delegated assignment that doesn't just resolve to the delegation. My memory could also be failing me. :)

> Hence, what can we do until then?

I'm not sure, give up and go back to whois scraping?

@martinhannigan Those lists exist, we purposefully were trying to use RDAP as intended and not fall back to whois and static mappings.

The problem being that the RIRs continue to provide better and more consistent information from whois queries.

**Comment by arnoldnipper** [comment]
> I'm not sure, give up and go back to whois scraping?

That can't be the solution IMO


> The problem being that the RIRs continue to provide better and more consistent information from whois queries.

+1000 ... and I don't understand why. Wasn't RDAP invented to phase out Whois?

**Comment by arnoldnipper** [comment]
> I'm not certain if other RIR's provide for national RIR's. Would building a reference resource table and sending the query direct to the NRIR improve accuracy and reliability?

Looks like only APNIC and LAC-NIC have [NIR](https://en.wikipedia.org/wiki/National_Internet_registry). Otoh, shouldn't the RIRs refer to the NIR in case they have subdelegated an ASN. I guess the issue is that the NIR in most cases don't have RDAP up and running.

**Comment by martinhannigan** [comment]
On Sun, Aug 29, 2021 at 12:26 PM Arnold Nipper ***@***.***>
wrote:

> I'm not certain if other RIR's provide for national RIR's. Would building
> a reference resource table and sending the query direct to the NRIR improve
> accuracy and reliability?
>
> Looks like only APNIC and LAC-NIC have NIR
> <https://en.wikipedia.org/wiki/National_Internet_registry>. Otoh,
> shouldn't the RIRs refer to the NIR in case they have subdelegated an ASN.
>

Yes. It's also interesting and perhaps a clue RDAP points at Cloudflare.
WHOIS points at LINODE. They appear to be using some geolocating, but
that's consistent when I switch back and forth so may indicate separate
infrastructure.

**Comment by arnoldnipper** [comment]
> Yes. It's also interesting and perhaps a clue RDAP points at Cloudflare. WHOIS points at LINODE.

Not sure what you are talking about. Which RDAP? Which Whois?

**Comment by martinhannigan** [comment]
Looking at resolutions for queries and DNS to see if theres any different
other than the tool:

Whois - resolves to LINODE

whois.apnic.net has address 45.79.94.209
whois.apnic.net has address 45.79.86.211
whois.apnic.net has IPv6 address 2600:3c01::f03c:91ff:fed5:cfca
whois.apnic.net has IPv6 address 2600:3c01::f03c:91ff:fed5:cf54

RDAP - resolves to Cloudflare

jpnic.rdap.apnic.net is an alias for jpnic.rdap.apnic.net.cdn.cloudflare.net
.
jpnic.rdap.apnic.net.cdn.cloudflare.net has address 104.18.236.68
jpnic.rdap.apnic.net.cdn.cloudflare.net has address 104.18.235.68
jpnic.rdap.apnic.net.cdn.cloudflare.net has IPv6 address
2606:4700::6812:ec44
jpnic.rdap.apnic.net.cdn.cloudflare.net has IPv6 address
2606:4700::6812:eb44

**Comment by arnoldnipper** [comment]
> Looking at resolutions for queries and DNS to see if theres any different other than the tool:

Which effect does that have on the content?

**Comment by martinhannigan** [comment]
On Sun, Aug 29, 2021 at 6:37 PM Arnold Nipper ***@***.***>
wrote:

> Looking at resolutions for queries and DNS to see if theres any different
> other than the tool:
>
> Which effect does that have on the content?
>

If you are talking about RDAP as unreliable and whois as more reliable, a
lot? Perhaps they have sync problems? And even more so, that helps make it
clear reverting to the whois scrape is not as bad an idea as perhaps
thought. Considering that, maybe the approach of RDAP and if exit 1, whois
as a fallback since we know its not reliable for APNIC and they apparently
won't commit to fix for whatever reason (fairness to them, who knows?).

**Comment by arnoldnipper** [comment]
> If you are talking about RDAP as unreliable and whois as more reliable, a lot? Perhaps they have sync problems?

Not RDAP is unreliable, but the data in RDAP. And I have no idea how data in RDAP and Whois is related to each other. So, talking of sync problems is wild speculation at best IMO.

**Comment by martinhannigan** [comment]
On Sun, Aug 29, 2021 at 6:49 PM Arnold Nipper ***@***.***>
wrote:

> If you are talking about RDAP as unreliable and whois as more reliable, a
> lot? Perhaps they have sync problems?
>
> Not RDAP is unreliable, but the data in RDAP. And I have no idea how data
> in RDAP and Whois is related to each other. So, talking of sync problems is
> wild speculation at best IMO.
>

Wild speculation has solved many complicated Internet problems. And without
a lot of knowledge of APNIC back end, path of least resistance. We could
always keep asking them for what they think the best work around is if they
cant solve it? At worst, if we won't assume then it's easy to say whois
will be more reliable answer + data and lets fall back.

YMMV,

-M<

**Comment by arnoldnipper** [comment]
> Wild speculation has solved many complicated Internet problems.

Wild speculation, IMO ;-)

> We could always keep asking them for what ...

We are in contact with APNIC about this issue

**Comment by martinhannigan** [comment]
On Sun, Aug 29, 2021 at 7:10 PM Arnold Nipper ***@***.***>
wrote:

> Wild speculation has solved many complicated Internet problems.
>
> Wild speculation, IMO ;-)
>

Actually, not. You have to start somewhere especially when you don;t
control the other side.

We could always keep asking them for what ...
>
> We are in contact with APNIC about this issue
>

Your proposal is "fix the tool". Doesn't that imply actions on the PDB
side? If you only want to do it your way then why bother submitting these?

Thanks!

-M<

**Comment by grizz** [comment]
> Actually, not. You have to start somewhere especially when you don;t control the other side. We could always keep asking them for what ...
>
> > We are in contact with APNIC about this issue
>
> Your proposal is "fix the tool". Doesn't that imply actions on the PDB side? If you only want to do it your way then why bother submitting these? Thanks!

You have to start somewhere... :)

An issue is good so we can verify what the problem is, and work around it on our side if need be.

**Comment by leovegoda** [comment]
@arnoldnipper It looks like APNIC's RDAP now fetches data from JPNIC. Have the AC tools seen misses related to this issue recently? If no, could we close it?

**Comment by arnoldnipper** [comment]
> @arnoldnipper It looks like APNIC's RDAP now fetches data from JPNIC. Have the AC tools seen misses related to this issue recently? If no, could we close it?

RDAP data now is fetched from JPNIC for newly added data. We still see misses and mismatches between Whois and RDAP but @peeringdb/ac knows how to work arrow
