### ISSUE TITLE
Peeringdb_server needs to have its files documented. 

### ISSUE THREAD

**Issue by fakela** [peeringdb/peeringdb#1031]
**Is your feature request related to a problem? Please describe.**

Each file in peeringdb_server should have at least some short explanation/documentation of what is in there. 

**Who is affected by the problem?**

Developers and other people willing to contribute to the codebase E.g QA analysts 

**What is the impact?**

This will enable people to contribute easily  to the codebase

**Could this feature request need support from the Admin Committee?**

Yes

**What is the proposed priority?**

simply urgent

**Comment by leovegoda** [comment]
If we decide to participate in the NANOG 83 Hackathon, having this documentation ready would be valuable for volunteer developers.

**Comment by leovegoda** [comment]
Working with @grizz to get this done for mid-October

**Comment by leovegoda** [comment]
I think this might now be complete. Is that right?

**Comment by leovegoda** [comment]
20C has confirmed that this has been done and the issue can be closed
