### ISSUE TITLE
Clicking "Add" to add a user api-key without providing a name for the key raises Internal Error

### ISSUE THREAD

**Issue by vegu** [peeringdb/peeringdb#1033]
**Describe the bug**

Trying to add a personal api key at https://www.peeringdb.com/profile without specifying a name for it will raise a user-unfriendly 500 Internal error alert.

This should instead alert the user that a name is required for the api key.

**Comment by ccaputo** [comment]
If fix is safe, I recommend for priority fix queue since this results in emails to Ops each time it happens.
