### ISSUE TITLE
CORS Access-Control-Allow-Origin header missing in API responses

### ISSUE THREAD

**Issue by natesales** [peeringdb/peeringdb#1034]
**Describe the bug**
Since PeeringDB 2.29, the server is no longer setting the CORS Access-Control-Allow-Origin header to allow cross site API requests in the browser. (See #78)

**To Reproduce**

```bash
~ ▴ curl -I -H "Origin: https://peeringdb.com" https://peeringdb.com/api/net\?asn\=34553
HTTP/2 200 
date: Wed, 25 Aug 2021 22:42:42 GMT
content-type: application/json; charset=utf-8
content-length: 1139
server: nginx
allow: GET, POST, HEAD, OPTIONS
vary: Authorization, Accept-Language, Cookie, Origin
x-frame-options: DENY
content-language: en
```

**Expected behavior**
The server should respond with a `Access-Control-Allow-Origin: *` header.

**Who is affected by the problem?**
Applications using the PeeringDB API directly from the browser. e.g. https://natesales.net/loa-generator

**What is the impact?**
Affected applications will be unable to query the PeeringDB API, instead receiving a CORS error such as `Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://www.peeringdb.com/api/net?asn=34553. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).`

**Are there security concerns?**
N/A

**Are there privacy concerns?**
N/A

**What are the proposed actions?**
The server should respond with a `Access-Control-Allow-Origin: *` header set for (all?) API GET calls.

**What is the proposed priority?**
simply urgent/not

**Provide a rationale for any/all of the above**
While admittedly PeeringDB API calls could be made from most application's backends, the convenience of simple apps such as https://natesales.net/loa-generator should warrant the inclusion of a modification to CORS policy.

**Additional context**
See #78 for previous discussion about this.

**Comment by axu-trex** [comment]
The CORS headers are working for `https://www.peeringdb.com/api/...` but not for `https://peeringdb.com/api/...` Is the shorter URL for the API illegal, or should the CORS headers be allowed for it as well?

**Comment by netravnen** [comment]
> The CORS headers are working for `https://www.peeringdb.com/api/...` but not for `https://peeringdb.com/api/...` Is the shorter URL for the API illegal, or should the CORS headers be allowed for it as well?

The correct URI to use is `www.peeringdb.com/api` according to the current [API specification documentation](https://docs.peeringdb.com/api_specs/)

**Comment by allanveloso** [comment]
The CORS headers do not work for `POST https://auth.peeringdb.com/oauth2/token/`, so it's not possible to implement a web app without a server using _Proof Key for Code Exchange_.

Is that the intended behaviour?
