### ISSUE TITLE
duplicateipnetworkixlan sorting is strange

### ISSUE THREAD

**Issue by job** [peeringdb/peeringdb#104]
is this ran through sorted() instead of a sorter capable of 'understanding' IP addresses? 

http://instituut.net/~job/screenshots/b83d8f86c5268b99792ba813.png

**Comment by job** [comment]
The sorting seems to fall apart when on the second or any subsequent page, the first page of the tool looks properly sorted.

**Comment by vegu** [comment]
fixed in 52ab7d
