### ISSUE TITLE
Long caching of deleted entries

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/peeringdb#1042]
**Describe the bug**
Entries still show up in the GUI even after 20h 

**To Reproduce**
https://peeringdb.com/search?q=Optify%20Mediaforce

```
{
  "id": 2344,
  "org_id": 2096,
  "name": "Optify Mediaforce",
  "aka": "Optify, Mediaforce, Keysurf, Keytalk, Keycom, Relish Networks, Keycom",
  "name_long": "",
  "website": "http://www.pccwglobal.co.uk",
  "asn": 25178,
  "looking_glass": "",
  "route_server": "",
  "irr_as_set": "AS-KEYCOM",
  "info_type": "Cable/DSL/ISP",
  "info_prefixes4": 25,
  "info_prefixes6": 1,
  "info_traffic": "50-100Gbps",
  "info_ratio": "Mostly Inbound",
  "info_scope": "Regional",
  "info_unicast": true,
  "info_multicast": true,
  "info_ipv6": true,
  "info_never_via_route_servers": false,
  "ix_count": 11,
  "fac_count": 6,
  "notes": "",
  "netixlan_updated": "2021-08-22T00:12:42.077808Z",
  "netfac_updated": "2018-05-02T13:28:24Z",
  "poc_updated": "2020-01-22T04:24:09Z",
  "policy_url": "",
  "policy_general": "Open",
  "policy_locations": "Not Required",
  "policy_ratio": false,
  "policy_contracts": "Not Required",
  "allow_ixp_update": false,
  "created": "2009-05-14T14:23:08Z",
  "updated": "2021-08-26T16:26:36Z",
  "status": "deleted"
}
```

**Expected behavior**
Deleted object shouldn't be visible anymore

**Who is affected by the problem?**
all users

**What is the impact?**
confusion

**Are there security concerns?**
no

**Are there privacy concerns?**
no

**What are the proposed actions?**
bug fix

**What is the proposed priority?**
simply urgent/not

**Provide a rationale for any/all of the above**

**Additional context**

**Comment by arnoldnipper** [comment]
Clearly identified as a bug ... see e.g. https://peeringdb.com/search?q=204571

**Comment by vegu** [comment]
Should also investigate the state of the production search index as part of this
