### ISSUE TITLE
AC Change User Permission broken

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/peeringdb#1043]
**Describe the bug**
The AC Change User Permission interface shows user - group relations which do not exist

**To Reproduce**
- go to https://peeringdb.com/cp/peeringdb_server/userpermission/1590/change/
- user seems to be admin of orgs with id 1187, 22553, 25554, 26904, 28629
- https://www.peeringdb.com/org/22553 does not exist. Same for 25554 and 28629

**Expected behavior**
The interface should exactly shown the correct relations

**Who is affected by the problem?**
AC, maybe others

**What is the impact?**

**Are there security concerns?**
Maybe

**Are there privacy concerns?**
Maybe

**What are the proposed actions?**
fix the bug

**What is the proposed priority?**
urgent as it is unclear what the impact is

**Provide a rationale for any/all of the above**

**Additional context**

**Comment by vegu** [comment]
This seems to happen when an org is soft-deleted. 

Looks like users aren't removed from the org's groups when an org is soft-deleted. This seems like a bug to me as well. Impact should be minimal unless we actually undelete and reassign orgs with any regularity.

**Comment by arnoldnipper** [comment]
> Impact should be minimal unless we actually undelete+reassign orgs with any regularity.

Should we take extra care for merging/unmerging? Currently, it's not well-defined what happens when objects are merged/unmerged. IMO we should at least describe internally - if not even generally - what happens when we merge/unmerge.

**Comment by arnoldnipper** [comment]
Moved to 3a as identified as a bug by a developer

**Comment by mcmanuss8** [comment]
>> What is the proposed priority?
> urgent as it is unclear what the impact is

Do we understand what the impact is yet?

**Comment by arnoldnipper** [comment]
> > > What is the proposed priority?
> > > urgent as it is unclear what the impact is
> 
> Do we understand what the impact is yet?

@vegu wrote: Impact should be minimal unless we actually undelete+reassign orgs with any regularity.

**Comment by vegu** [comment]
> Should we take extra care for merging/unmerging?

@arnoldnipper The organization merge tool should correctly remove the user from the old org.

Its when organizations get deleted otherwise that users are not removed from the groups for the org.

I wan wondering if the proposed fix is to clear org user groups when the org is soft-deleted. This will make it currently impossible to undelete the org again and have user permission restored as well.

**Comment by arnoldnipper** [comment]
> @arnoldnipper The organization merge tool should correctly remove the user from the old org.

And what happens when we unmerge? Will the user be re-added, @vegu?

**Comment by vegu** [comment]
> And what happens when we unmerge? Will the user be re-added, @vegu?

@arnoldnipper if the unmerge is done via `/cp/peeringdb_server/organizationmerge/`  using the `undo` action then yes. If you manually move the entities back to the previous org then no.

**Comment by arnoldnipper** [comment]
> If you manually move the entities back to the previous org then no.

@vegu, I don't get this sentence. Permissions are bound to `org`, not to entities belonging to an `org`.  Aren't they?

**Comment by vegu** [comment]
@arnoldnipper correct - permissions are bound to the org

Users are permissioned to orgs by being in the org's user groups. (member & admin) 

During a merge with the merge org tool users get removed from their old org's groups and added to the other org's groups.

Using the undo merge action ensures users get moved back to their original org as they were before.

If on the other hand you decide to undo a merge manually by undeleting the org and moving the entities back to the org you will also need to manually take care of moving those users back to original org's group as well. 

Does that make more sense?

**Comment by vegu** [comment]
**summary**

- soft deleting an organization should remove the users from it's groups
