### ISSUE TITLE
Strange and undeletable entries in Verification Queue 

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/peeringdb#1045]
**Describe the bug**
There are strange and undeletable entries in the Verification Queue 

**To Reproduce**
1. https://peeringdb.com/cp/peeringdb_server/verificationqueueitem/?o=3&q=
2. Mark first entry
3. Go down and select "DENY and delete selected items" from the dropdown. Then click on "Go"
4. You get an "Server Error (500)"

**Expected behavior**
- all entries should have a string != "-" in the items field
- an entry should be handable by one of the selectable actions from the dropdown
- 
**Who is affected by the problem?**
@peeringdb/ac 

**What is the impact?**
The verification queue can't be kept clean

**Are there security concerns?**
no

**Are there privacy concerns?**
no

**What are the proposed actions?**
- Look into it
- remove the strange entries
- check for proper working
- 
**What is the proposed priority?**
annoying, but can be worked around

**Provide a rationale for any/all of the above**

**Additional context**

![20210902 PeeringDB 00](https://user-images.githubusercontent.com/16888757/131808318-105c901c-ac2a-4dbc-a807-e68ab1c94021.png)

**Comment by peterhelmenstine** [comment]
+1 sounds like a bug

**Comment by arnoldnipper** [comment]
deleting them one by one worked
