### ISSUE TITLE
Add search field to several AC interfaces

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/peeringdb#1049]
**Is your feature request related to a problem? Please describe.**
Newly added interfaces are missing a search field

**Who is affected by the problem?**
@peeringdb/ac 

**What is the impact?**
Only linear search

**Are there security concerns?**
no

**Are there privacy concerns?**
no

**Describe the solution you'd like**

Add a search field to
- https://peeringdb.com/cp/oauth2_provider/accesstoken/ for token and user
- https://peeringdb.com/cp/oauth2_provider/application/ for user
- https://peeringdb.com/cp/oauth2_provider/grant/ for Code and user
- https://peeringdb.com/cp/oauth2_provider/refreshtoken/ for Token and user

- https://peeringdb.com/cp/otp_email/emaildevice/ for email devices

- https://peeringdb.com/cp/otp_static/staticdevice/ for static devices

- https://peeringdb.com/cp/otp_totp/totpdevice/ for User

**Describe alternatives you've considered**
biting the dust

**Could this feature request need support from the Admin Committee?**
It's for AC

**What is the proposed priority?**
Urgent, as linear search is more than cumbersome

**Provide a rationale for any/all of the above**

**Additional context**

**Comment by peterhelmenstine** [comment]
+1

**Comment by Juimar** [comment]
+1

**Comment by martinhannigan** [comment]
How often would this be used? Can you give an example use case? Ive never
been on the AC. It would help me to wrap my head around it priority wise.

You said it’s urgent. How did the AC survive without it so far?

I saw AC +1s so imagine it matters.

Thanks

**Comment by peterhelmenstine** [comment]
+ 1 Yes please and thank you.

**Comment by arnoldnipper** [comment]
covered by #1239
