### ISSUE TITLE
Add 'Route Server' Info type	(a.k.a. "Network Type") for network objects

### ISSUE THREAD

**Issue by job** [peeringdb/peeringdb#105]
In what used to be `INFO_TYPE_CHOICES` an option should be added called `Route Server` so Autonomous Systems can identify themselves as performing a Route Server functionality. This is same data field where for instance 'NSP' and 'Non-Profit' are defined.

**Comment by job** [comment]
This request is a solution to what was discussed here http://lists.peeringdb.com/pipermail/pdb-tech/2016-December/000230.html

**Comment by job** [comment]
Mockup 
<img width="1010" alt="298ec9f53261b2a409e17da3" src="https://cloud.githubusercontent.com/assets/153816/21473028/a4de7d8c-caf6-11e6-9f3d-5f8d2e875a7b.png">

**Comment by job** [comment]
mockup

<img width="959" alt="cc33364a40da10ccb9283fd2" src="https://cloud.githubusercontent.com/assets/153816/21473208/1bdfaf7e-cb00-11e6-8516-3dec25228b85.png">

**Comment by arnoldnipper** [comment]
iirc there was a dicussion on product-comm to get rid off this information or at least to get it straight
