### ISSUE TITLE
IX-F manually triggered import bugs

### ISSUE THREAD

**Issue by vegu** [peeringdb/peeringdb#1054]
**Describe the bug**

With manually triggered IX-F imports now enabled ops has identified some bugs with this new feature that should be addressed.

There are currently three distinct bugs

1. The `-P` parameter is supposed to limit how many of such import requests are handled at a time, this is one of the avenues we have for rate limiting the process. Command seems to ignore this limit.

2. In the case where an ix tries to trigger a manual import without enabling the ix-f import checkbox or providing an ix-f import url we currently end at a situation where the command still picks it up but can't process it due to the missing "ix-f import enabled" flag and/or url.

3. Manual imports affected by [2] (and one instance where the ix-f feed returned a 404 response) currently remain queued - we should double check that import errors for manually triggered imports always resolve (either as a success or as an error) and that whatever the resolution is is communicated accordingly to the IX ui.

**What are the proposed actions?**

[1] seems like a straight forward bug, and passing a number to `-P` should apply a limit to how many import requests are processed

[2] might need some clarification - is the "ix-f import enabled" flag only relevant for automatic imports and should manually triggered imports simply ignore it - or should they require it to be set.

In the case where the ix-f import url is not specified, clicking the the manual import button should notify the user of this instead of triggering the import.

**Comment by arnoldnipper** [comment]
> [2] might need some clarification - is the "ix-f import enabled" flag only relevant for automatic imports and should manually triggered imports simply ignore it - or should they require it to be set.

IMO the "ix-f import enabled" flag is only relevant for automatic imports and should manually triggered imports simply ignore it. The IXP may just want to test the functionality. And for this use case, they had to enable and disable the flag. While it's not a big deal to do this, you might forget to disable it after testing.

**Comment by arnoldnipper** [comment]
@peeringdb/pc, routed through to 3a as this is a bug according to the developers. Please make your mind regarding [2]

**Comment by ccaputo** [comment]
> > [2] might need some clarification - is the "ix-f import enabled" flag only relevant for automatic imports and should manually triggered imports simply ignore it - or should they require it to be set.
> 
> IMO the "ix-f import enabled" flag is only relevant for automatic imports and should manually triggered imports simply ignore it. The IXP may just want to test the functionality. And for this use case, they had to enable and disable the flag. While it's not a big deal to do this, you might forget to disable it after testing.

+1 (from my Ops non-PC perspective)
