### ISSUE TITLE
Blacklist private / unassigned IP addresses

### ISSUE THREAD

**Issue by job** [peeringdb/peeringdb#106]
The following ranges (or ranges within these ranges) can never be an IXP Peering Lan Prefix or an IP address entered by a PDB user, because they have been designated other purposes by the IANA or IETF.

PDB should error when someone tries to enter any of these (an IP address or a prefix which overlaps with part of these prefixes) as an IXP lan or as their public peering IP address.

```
0.0.0.0/8 - IANA - Local Identification
10.0.0.0/8 - RFC 1918 - Private Use
127.0.0.0/8 - IANA - Loopback
169.254.0.0/16 - RFC 3927 - Link Local
172.16.0.0/12 - RFC 1918 - Private Use
192.0.2.0/24 - RFC 5737 - TEST-NET-1
192.168.0.0/16 - RFC 1918 - Private Use
198.18.0.0/15 - RFC 2544 - Network Interconnect Device Benchmark Testing
198.51.100.0/24 - RFC 5737 - TEST-NET-2
203.0.113.0/24 - RFC 5737 - TEST-NET-3
224.0.0.0/3 - RFC 5771 - Multcast (formerly Class D)
100.64.0.0/10 - RFC 6598 - Shared Address Space
0000::/8 - loopback, unspecified, v4-mapped
0064:ff9b::/96 - RFC 6052 - IPv4-IPv6 Translation
0100::/8 - RFC 6666 - reserved for Discard-Only Address Block
0200::/7 - RFC 4048 - Reserved by IETF
0400::/6 - RFC 4291 - Reserved by IETF
0800::/5 - RFC 4291 - Reserved by IETF
1000::/4 - RFC 4291 - Reserved by IETF
2001::/33 - RFC 4380 - Teredo prefix
2001:0:8000::/33 - RFC 4380 - Teredo prefix
2001:0002::/48 - RFC 5180 - Benchmarking
2001:0003::/32 - RFC 7450 - Automatic Multicast Tunneling
2001:10::/28 - RFC 4843 - Deprecated ORCHID
2001:20::/28 - RFC 7343 - ORCHIDv2
2001:db8::/32 - RFC 3849 - NON-ROUTABLE range to be used for documentation purpose
2002::/16 - RFC 3068 - 6to4 prefix
3ffe::/16 - RFC 5156 - used for the 6bone but was returned
4000::/3 - RFC 4291 - Reserved by IETF
5f00::/8 - RFC 5156 - used for the 6bone but was returned
6000::/3 - RFC 4291 - Reserved by IETF
8000::/3 - RFC 4291 - Reserved by IETF
a000::/3 - RFC 4291 - Reserved by IETF
c000::/3 - RFC 4291 - Reserved by IETF
e000::/4 - RFC 4291 - Reserved by IETF
f000::/5 - RFC 4291 - Reserved by IETF
f800::/6 - RFC 4291 - Reserved by IETF
fc00::/7 - RFC 4193 - Unique Local Unicast
fe80::/10 - RFC 4291 - Link Local Unicast
fec0::/10 - RFC 4291 - Reserved by IETF
ff00::/8 - RFC 4291 - Multicast
```

**Comment by grizz** [comment]
very trivial to add with ipaddress::is_private

**Comment by job** [comment]
I've cleaned up the existing wrong data in PDB just now.

**Comment by grizz** [comment]
@job should be `224.0.0.0/4` shouldn't it?

**Comment by job** [comment]
224.0.0.0/4 is multicast. 240.0.0.0/4 is future use. So 224.0.0.0/3 cannot/should not be used.

**Comment by grizz** [comment]
Oh, right, my math was off on that, thanks

**Comment by job** [comment]
I listed it shitty, should've split that /3 into 2 x /4

**Comment by vegu** [comment]
From my understanding this is completed with the exception of 224.0.0.0/3 due to a bug in the `ipaddress` python module. Will either have to write manual fix for it, or wait until it is fixed in `ipaddress` and update.

**Comment by job** [comment]
manual fix for 224.0.0.0/3 is probably best, i guess?

**Comment by grizz** [comment]
@job agree, I was going to do a patch to them first instead of hacking it into PDB

**Comment by job** [comment]
upstream you mean?

Somehow I suspect there may be some ideological thing behind it somehow

**Comment by arnoldnipper** [comment]
Could we please implement this? See https://peeringdb.com/ix/2447

**Comment by vegu** [comment]
The validator is implemented, but it only validates ixlan prefixes. I believe the intention was to have netixlan validation through the implementation of #8.

#8 is scheduled to be fixed in the next batch of backlog fixes

**Comment by arnoldnipper** [comment]
Sure, once we have ixlan prefixes for alle IXes that should do. AC has set a deadline for all IXes to add their ixlan prefixe until 2018-12-31 23:59 UTC. From 2019-01-01 00:00 UTC AC will start to remove IXes which don't have at leasr one ixlan prefix
