### ISSUE TITLE
"HARAKIRI ON WORKER" issues need to be resolved

### ISSUE THREAD

**Issue by ccaputo** [peeringdb/peeringdb#1060]
**Describe the bug**
`grep -C 5 HARAKIRI /var/log/messages` on production and beta instances results in many examples.  These should be chased down and figured out.

A sample:

```
Sep 30 19:50:30 betagw0 pdb_django: Thu Sep 30 19:50:30 2021 - *** HARAKIRI ON WORKER 19 (pid: 530, try: 1) ***
Sep 30 19:50:30 betagw0 pdb_django: Thu Sep 30 19:50:30 2021 - HARAKIRI !!! worker 19 status !!!
Sep 30 19:50:30 betagw0 pdb_django: Thu Sep 30 19:50:30 2021 - HARAKIRI [core 0] 10.x.y.z - GET / since 1633031369
Sep 30 19:50:30 betagw0 pdb_django: Thu Sep 30 19:50:30 2021 - HARAKIRI !!! end of worker 19 status !!!
Sep 30 19:50:31 betagw0 pdb_django: DAMN ! worker 19 (pid: 530) died, killed by signal 9 :( trying respawn ...
Sep 30 19:50:31 betagw0 pdb_django: Respawned uWSGI worker 19 (new pid: 531)
```

Arguably a beta release should not make it to production while these are happening since they represent failures that are not otherwise being detected/reported.  I recommend a check of the beta /var/log/messages instance files be performed after beta deploys and before production deploys to catch problems.

**Comment by arnoldnipper** [comment]
Makes good sense to me ... +1

**Comment by ccaputo** [comment]
These are being caused by failed TCP connections to the backend database. Options are being discussed between ops and devs.
