### ISSUE TITLE
api-cache improvements

### ISSUE THREAD

**Issue by grizz** [peeringdb/peeringdb#1065]
We should evaluate possible api-cache improvements along with #970 and ideally before the DB update next year.

**Comment by leovegoda** [comment]
Does the @peeringdb/oc want to go ahead with this? If so, it could be scheduled over the end of the year

**Comment by ccaputo** [comment]
> Does the @peeringdb/oc want to go ahead with this? If so, it could be scheduled over the end of the year

I think @grizz is planning to review this.

**Comment by grizz** [comment]
This issue is for the reviewing :)

**Comment by grizz** [comment]
**Summary**
api-cache-gen has increased in time and now takes 30+ minutes, we will evaluate if we still need a separate process for it, and see what improvements can be done.

@peeringdb/pc Could we get some votes here please :)

**Comment by arnoldnipper** [comment]
+1

**Comment by martinhannigan** [comment]
+1

**Comment by peterhelmenstine** [comment]
+1

**Comment by leovegoda** [comment]
Decision to be made at the next PC meeting
