### ISSUE TITLE
Users are not able to create facilities for which they are not the owner

### ISSUE THREAD

**Issue by job** [peeringdb/peeringdb#107]
There should be some kind of checkbox, that PeeringDB users can indicate that they are present in a certain facility, but that they are just a tenant of the facility and **not** the owner.

The advantage for PeeringDB is that as the user base grows, more facilities are entered into PeeringDB. Even though the facility management might not actively participate in PeeringDB

The advantage for the AdminCom is that we don't need to discuss with the PeeringDB user whether they understand PeeringDB properly or not.

I'm not exactly sure how it should look from an UI perspective.

**Comment by job** [comment]
@arnoldnipper suggests that the same applies to IXPs

**Comment by job** [comment]
@arnoldnipper said:

> "And we have to do something to make it harder for users to register facilities and IXPS. 95+% are fake registrations. At best users want to associate their network with the facility or the IXP. Maybe the default should be not to show those tabs.
> Somehow  .... enable those tabs if Admins are quite sure that the organisation is also operating facilities and/or IXP"

**Comment by eloos** [comment]
Could we resolve this by educating the users whom are going through a first experience? For instance by showing a pop-up over each field with an explanation on the proper use of the field. This would be shown to all users for an org that has nothing set up in terms of IXP, Facilities or networks and to everyone for whom this session is their first login.

**Comment by grizz** [comment]
I think this will be solved by simply allowing suggestions as version 1 did, yes?

**Comment by arnoldnipper** [comment]
> I think this will be solved by simply allowing suggestions as version 1 did, yes?

What exactly do you mean by this?

**Comment by grizz** [comment]
Version 1 had forms to "suggest" new Facilities which then went to the AC to approve

**Comment by arnoldnipper** [comment]
Wouldn't it simply need an extra button in the "Add Facility/Exchange" template to implement this? If ticked, an extra field pops up, where I can add the organisation where the Facility/Exchange belongs to

**Comment by arnoldnipper** [comment]
@vegu / @grizz ... could you pls make proposal(s)

**Comment by grizz** [comment]
I'd propose:

New 'Suggest' button on each entity, only available for a logged in and verified user. Allows the same as any other request, but doesn't set the org, which would then create an AC ticket in the queue. AC would have to verify the entity is valid, assign the correct org, and approve.

If it's not legit, AC would deny.

Sound reasonable?

**Comment by eloos** [comment]
Vote: in favour of proposal of @grizz

**Comment by arnoldnipper** [comment]
Vote: in favour of @grizz 's proposal

**Comment by mcmanuss8** [comment]
+1 @grizz

**Comment by kay23** [comment]
Agreeing with @grizz's proposal. +1

**Comment by job** [comment]
+1 for what grizz suggested.

**Comment by thatchrisp** [comment]
+1 Grizz

**Comment by karumugham** [comment]
Yes on grizz's "suggest" proposal

**Comment by fhibler** [comment]
+1 on @grizz suggestion.

**Comment by nopedial** [comment]
+1

**Comment by vegu** [comment]
Implemented in 2600ee4
