### ISSUE TITLE
OpenID Connect integration

### ISSUE THREAD

**Issue by caguado** [peeringdb/peeringdb#1070]
**Is your feature request related to a problem? Please describe.**
I would like to use PeeringDB to authenticate users to log in to a web application. The integration described in [the docs](https://docs.peeringdb.com/oauth/) allows to use a vanilla OAuth2 client. However many of the managed services available today use OpenID Connect (OIDC). OIDC is an extension to OAuth2 that is compatible with it but that defines additional scopes, claims (JWT) to implement a federated environment. This request is to propose enabling OIDC with RS256 signing.

Some of the managed services who support OIDC are Facebook, Google SignIn, AWS Cognito/SSO, Azure, Okta, Auth0.

PeeringDB Django setup uses a library which has support for this feature and can be enabled as per the linked documentation.

This issue has been discussed offline and seems a feasible option, for others to benefit from it too.

**Who is affected by the problem?**
Any PeeringDB customer/operator who wants to enable an identity federation with a _managed service_ is currently unable to do so.

**What is the impact?**
OIDC is a precondition to enable federated access with the managed services mentioned above, without it customer portal will have to implement their own or roll out their own identity solutions.

**Are there security concerns?**
I have limited visibility into the service management of PeeringDB but this request will not increase the security exposure of PeeringDB regarding OAuth2. Looking at the code base of this repository, the OIDC integration can be enabled with a few configuration changes in one of the [Django dependencies](https://django-oauth-toolkit.readthedocs.io/en/latest/oidc.html).

I am not aware of the particulars of implementation details of django-oauth-toolkit about OIDC that could compromise PeeringDB's stability, nor why it has not been enabled already. Given that is already used for login by PeeringDB, I do not anticipate issues.

In order to enable OIDC, the PeeringDB webapplication will need to [cryptographically sign](https://django-oauth-toolkit.readthedocs.io/en/latest/oidc.html#creating-rsa-private-key) the tokens for validation by Relying Parties. This requires certain level of security of the crypto material used for such a signature. This however should not be different from the security bar already expected from the existing Django installation where an equivalent key is used to encrypt cookies.

Enabling `RS256` will improve the availability and integration of PeeringDB with consuming applications because those will be able to validate JWT tokens without further involving PeeringDB's signing API.

**Are there privacy concerns?**
OIDC does not increase PeeringDB's customer data more than what is already disclosed [the docs](https://docs.peeringdb.com/oauth/).

**Describe the solution you'd like**
I am proposing to follow the OIDC configuration guide of [django-oauth-toolkit](https://django-oauth-toolkit.readthedocs.io/en/latest/oidc.html) where PeeringDB service owners will need to perform the following 2 actions:
* create and secure an RSA private key (https://django-oauth-toolkit.readthedocs.io/en/latest/oidc.html#creating-rsa-private-key). This is a critical step to enable token verification with `RS256` signing algorithm.
* configure PeeringDB's Django installation to include:
  * enable OIDC feature flag
  * the aforementioned private key
  * expose the `openid` scope

**Describe alternatives you've considered**
This request is a precondition for the use of managed services based on OpenID. Without it, operators will need to implement their own authorization framework increasing the operational bar for those already using those managed services. In my case, I will not be able to integrate with PeeringDB without this feature.

**Could this feature request need support from the Admin Committee?**
I am not aware.

**What is the proposed priority?**
Urgent

**Provide a rationale for any/all of the above**
I am working on releasing a feature early 2022 and it will be a blocker for the current planned integration. Without further visibility into how timelines work for PeeringDB but assuming a no urgent option may not be prioritised in the foreseeable future, I am marking this issue as urgent.

**Additional context**
All the information about this integration is described in the documentation of the [django-oauth-toolkit](https://django-oauth-toolkit.readthedocs.io/en/latest/oidc.html#openid-connect-support).

**Comment by caguado** [comment]
Any progress on the topic?

**Comment by mcmanuss8** [comment]
@caguado apologies for not engaging on this one. 

Can you clarify the use case a bit for me? It sounds like you, as an organization, want to log into PeeringDB using your org's SSO implementation? Using OpenID will make that simpler?

**Comment by caguado** [comment]
Thanks for coming back so quickly.

The opposite flow is what I am looking for. I would like to use PeeringDB as an OpenID _Authorization Server_ so that any PeeringDB user can signin to my organization's website. To that purpose, I am requesting to enable OpenID Connect (OIDC) and improve the JWT signing and verification mechanism in your middleware so that I can use any of the managed services mentioned above (e.g. [AWS Cognito User Pools](https://docs.aws.amazon.com/cognito/latest/developerguide/cognito-scenarios.html)).

As it stands, AWS Cognito is not able to federate with PeeringDB because:
* PeeringDB does not implement OIDC.
* the JWT tokens issued by PeeringDB cannot be cryptographically verified by the relying party.

**Comment by grizz** [comment]
+1 from me, this all makes good sense.

@peeringdb/pc ?

**Comment by martinhannigan** [comment]
+1 = roadmap 2022

**Comment by caguado** [comment]
Any visibility into that 2022 roadmap? If there is any guidance on how the infra/QA is done we will be more than happy to contribute the code changes and unblock our Q1 launch.

**Comment by leovegoda** [comment]
> Any visibility into that 2022 roadmap? If there is any guidance on how the infra/QA is done we will be more than happy to contribute the code changes and unblock our Q1 launch.

We will be introducing FIDO U2F 2FA support in our January release. I'm looking at when we could introduce support for OIDC but we need additional @peeringdb/pc support to advance this work.

The PC is currently deciding on the high level priorities for 2022 and we plan to publish the roadmap in January.

**Comment by mcmanuss8** [comment]
+1

**Comment by leev** [comment]
+1 This would be a great addition.  Our (Cloudflare) peering portal requires a user to signup and we need to verify each user before giving them access.  This will allow us to use peeringdb as any idP removing the signup/verify process.

**Comment by caguado** [comment]
Contributing a PR with the changes required to enable integration.

I tested in a private AWS ECS-Cognito integration and got a successful authorization code flow and its validated JWT id_token.
