### ISSUE TITLE
There are 2 facilities with invalid location

### ISSUE THREAD

**Issue by astramax57** [peeringdb/peeringdb#1089]
**Describe the bug**
There are 2 facilities with invalid location:
https://peeringdb.com/fac/11113 and https://peeringdb.com/fac/11103

The problem is that the lontitude and latitude were mixed up in places

**To Reproduce**
1. Go to 'https://peeringdb.com/fac/11113'
2. Click on location link, https://maps.google.com/?q=117.958202,40.924757
3. See map with no point
4. Swap lontitude and latitude, press Enter
5. See map with right point in China

The same behavior is for second facility too.

**Comment by arnoldnipper** [comment]
Thanks for spotting, @astramax57. Next time you see invalid data, please send an email to the [PeeringDB Support](mailto:support@peeringdb.com)
