### ISSUE TITLE
Check whether upcoming change to ARIN RDAP profile requires changes to PeeringDB

### ISSUE THREAD

**Issue by leovegoda** [peeringdb/peeringdb#1090]
ARIN has announced that it will be changing its RDAP profile on 16 December 2021:

https://lists.arin.net/pipermail/arin-tech-discuss/2021-November/000975.html

We should check whether this change will require code changes in PeeringDB. If we do need to make code changes, we should use this issue to track what they might be and how to authorize and schedule them, if we need to deploy a new release to support the change.

**Comment by grizz** [comment]
The changes look fine and haven't seen any issues.
