### ISSUE TITLE
Adjust "Add Facility" menu to include newly defined fields

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/peeringdb#1091]
**Describe the bug**
https://peeringdb.com/org/nnnnn#add_fac does not contain the newly defined fields (e.g. available_voltage_services)

**To Reproduce**
Pick any org's "Add Facility" tab

**Expected behavior**
The menu should contain **all** fields so that the user can input all data at once.

**Who is affected by the problem?**
All users

**What is the impact?**
Extra work for the users

**Are there security concerns?**
no

**Are there privacy concerns?**
no

**What are the proposed actions?**
Modify the "Add Facility" menu

**What is the proposed priority?**
none. Generally, if new fields are added, menus must be adjusted automatically

**Comment by arnoldnipper** [comment]
@peeringdb/pc, please discuss whether a request GUI should contain **all** fields or not. IMO it should.

**Comment by martinhannigan** [comment]
+1, low priority, enhancement.

**Comment by peterhelmenstine** [comment]
+1 Agreed

**Comment by mcmanuss8** [comment]
+1

**Comment by vegu** [comment]
**summary**

- add fields to `Add Facility` dialog
  - `Property`
  - `Diverse Serving Substations`
  - `Available Voltage Services`

**Comment by martinhannigan** [comment]
Would it make sense to merge Issue #1115?

Thanks

**Comment by arnoldnipper** [comment]
> Would it make sense to merge Issue #1115?

no

**Comment by martinhannigan** [comment]
I’d like to add these two issues to PC agenda monthly to discuss as
learning opportunity.

Id like to learn why poking this facilities code shouldn’t cause us to get
other low hanging fruit accomplished expecting the code may be reasonably
nearby.

Thanks !

**Comment by grizz** [comment]
I think it would make sense as well. We have a handful of issues pertaining to the other objects too, combining issues from each object type together in a single sprint will allow us to holistic choices. It most likely will also reduce the time spent coding / testing.

Agree on adding it to the agenda for next PC meeting -- @mcmanuss8
