### ISSUE TITLE
Peeringdb update error

### ISSUE THREAD

**Issue by Bolortuyae** [peeringdb/peeringdb#1092]
**Describe the bug**

We are Mobicom of Mongolia. AS55805. 

Something error. Bad request

**To Reproduce**
1. Go to '(https://www.peeringdb.com/net/11727)'
2. Click on 'Edit'
![image](https://user-images.githubusercontent.com/95021116/143611325-62b08b5a-0884-4672-b63a-a44e6a94acbc.png)

**Expected behavior**
Want to add new IXP in our AS55805

When we add new IXP whcih HKIX there is error. Could you please fix this issue urgently. 
**Who is affected by the problem?**
AS55805
**What is the impact?**
We could public peer due to can not add new IXP which is HKIX. 

**Are there security concerns?**

**Are there privacy concerns?**

**What are the proposed actions?**

**What is the proposed priority?**

very urgent

**Provide a rationale for any/all of the above**
![image](https://user-images.githubusercontent.com/95021116/143609762-b9d5013b-8fa9-45e5-a1fc-906ffb2e8344.png)

**Additional context**
![image](https://user-images.githubusercontent.com/95021116/143609744-c4abd422-bdb2-4e65-a762-ca576cdb37de.png)

**Comment by arnoldnipper** [comment]
Please send an email to [PeeringDB Support](mailto:support@peeringdb.com). They are able to help you.
