### ISSUE TITLE
Clicking on Facility history in AC GUI throws 500

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/peeringdb#1096]
**Describe the bug**
Clicking on the history button of any facility gives a "Server Error (500)"

**To Reproduce**
e.g. https://peeringdb.com/cp/peeringdb_server/facility/11546/history/

**Expected behavior**
Clicking on the history button of any facility should give the history of changes made

**Who is affected by the problem?**
@peeringdb/ac 

**What is the impact?**
AC is not able to lookup the history

**Are there security concerns?**
no

**Are there privacy concerns?**
no

**What are the proposed actions?**
fix the bug

**What is the proposed priority?**
high

**Provide a rationale for any/all of the above**

**Additional context**

**Comment by peterhelmenstine** [comment]
+1 500 BadGateway is not good

**Comment by mcmanuss8** [comment]
+1 clear bug

**Comment by Juimar** [comment]
+1

**Comment by arnoldnipper** [comment]
May we please have a fix for this with the next release, @grizz  and @mcmanuss8 ? It's impossible for @peeringdb/ac to see who did what.

**Comment by arnoldnipper** [comment]
@grizz and @mcmanuss8 , please prioritize!

**Comment by arnoldnipper** [comment]
This is still broken ... see [this facility history](https://www.peeringdb.com/cp/peeringdb_server/facility/3050/history/)
