### ISSUE TITLE
Ipv6

### ISSUE THREAD

**Issue by THELEMITED** [peeringdb/peeringdb#1097]
**Is your feature request related to a problem? Please describe.**

**Who is affected by the problem?**

**What is the impact?**

**Are there security concerns?**

**Are there privacy concerns?**

**Describe the solution you'd like**

**Do you think this feature will require a formal design?**
yes/no (add why if no)

**Describe alternatives you've considered**

**Could this feature request need support from the Admin Committee?**
Consider if an administrator might need to provide assistance at any point.

**What is the proposed priority?**
simply urgent/not

**Provide a rationale for any/all of the above**

**Additional context**

**Comment by mcmanuss8** [comment]
@THELEMITED doesn't seem like this template got filled out. Closing, please reopen and fill in the template if you have something you want to see changed
