### ISSUE TITLE
Expose authentication methods on outbound federation

### ISSUE THREAD

**Issue by caguado** [peeringdb/peeringdb#1099]
**Is your feature request related to a problem? Please describe.**
In the scenario where PeeringDB is the [authorization server](https://openid.net/specs/openid-connect-basic-1_0.html#Terminology) used by third parties to signin PeeringDB users automatically, it is useful to know the successful authentication processes the user has met upon signin towards establishing a level of assurance of the identity.

The OIDC specification defines the `acr` and `amr` [claims](https://openid.net/specs/openid-connect-basic-1_0.html#IDToken) as two complementing elements to expose the identity assurance level and authentication methods that the user has met respectively upon signing in.

**Who is affected by the problem?**
Any third-party OIDC provider will benefit from this feature and will gain trust in the authentication process and subsequent operations allowed on their tooling.

**What is the impact?**
No operational changes to existing PeeringDB processes.

**Are there security concerns?**
No other security considerations other than those already in considered when implementing Oauth2/OIDC.

**Are there privacy concerns?**
The exposure of additional claims may reveal information about the user (ref [rfc8176#section-4](https://datatracker.ietf.org/doc/html/rfc8176#section-4)), however the changes proposed in this request are generic to not include personal identifiable information.

**Describe the solution you'd like**
There are standards (e.g. [PAPE](https://openid.net/specs/openid-provider-authentication-policy-extension-1_0.html), [RFC8176](https://datatracker.ietf.org/doc/html/rfc8176)) and proposals of standard ([EAP](https://openid.net/specs/openid-connect-eap-acr-values-1_0.html)) for each of them so this feature request is to propose to start with `amr` with values drawn from RFC8176 as a simpler mechanism to start with.

From that starting point, two use case scenarios could be delivered:
* a verified PeeringDB user has **no** FIDO/U2F second factor: the JWT id_token includes `amr: [pwd]`
* a verified PeeringDB user has FIDO/U2F enabled: the JWT id_token includes `amr: [pwd, hwk]`

**Do you think this feature will require a formal design?**
Possibly.

**Describe alternatives you've considered**
There is no known alternative available within the OIDC protocol to step up authentication once completed by PeeringDB.

**Could this feature request need support from the Admin Committee?**
Possibly.

**What is the proposed priority?**
Ideally to be completed together with #692 and/or #760

**Provide a rationale for any/all of the above**
PeeringDB is positioning itself not only as a supporting entity to coordinate peering practices but also as an element of trust within the participating networks. The more we can strengthen the security posture offered to those parties, the better trust and lower the barriers to run smooth operations for the benefit of our common customers.

**Additional context**
None.

**Comment by mcmanuss8** [comment]
+1

**Comment by grizz** [comment]
+1 -- should be a scope for that as well to notify the user.

**Comment by martinhannigan** [comment]
+1

**Comment by grizz** [comment]
**Summary**

- Add amr field to oauth profile, with choices from [Section 2](https://datatracker.ietf.org/doc/html/rfc8176#section-2) of [RFC8176](https://datatracker.ietf.org/doc/html/rfc8176)
- Add docs for developers
- Add scope for auth info? I haven't found anyone else doing a scope for this, but it seems like it can't hurt. Can probably decide at implementation time.

**Comment by barryo** [comment]
+1 for this also. 

Following the recent incident at RIPE, we have had IXP Manager users asking for the ability to enforce 2fa for their organisations. If we were to develop that now, we would have to disable that orgs ability to use PeeringDB OAuth as we cannot ensure 2fa via PeeringDB.

If amr data is provided, then we can honour 'enforce 2fa for organisations' without disabling PeeringDB OAuth.
