### ISSUE TITLE
Model campus datacenter facilities

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/peeringdb#11]
Some datacenters are in campus buildings, named Facility DC1 to Facility DCn. From outside it may look like different DCs, in reality it's just one. See Ticket #8549 in Ubersmith.

Idea is to have _one_ virtual DC and keep the structure. This might also model a DC in a DC perhaps

**Comment by mcmanuss8** [comment]
@peeringdb/pc Close in favor of a more complicated model as described in #287?

**Comment by as44980** [comment]
+1  

It appears that #287 has a broader scope plus the potential to addres the linkage between facilities both in a multi-building campus' and multi-tennant building :)

**Comment by grizz** [comment]
Agreed on closing in favor of #287
