### ISSUE TITLE
Users need to be affiliated to an org to take advantage of some Advanced Search features

### ISSUE THREAD

**Issue by leovegoda** [peeringdb/peeringdb#1102]
**Describe the bug**
Users need to be affiliated with an org to take advantage of some advanced search features including radius search. 

**To Reproduce**
1. Login with an account that is not affiliated with an org
2. Go to Advanced Search
3. Click on Facilities
4. Search for Paris, France

You see a  note that it is not possible to filter the results but is possible to see all results for Paris, France and export them in CSV of JSON format.

**Expected behavior**
Active user accounts should be able to minimize the amount of data they get from search results by applying relevant filters, like a radius limit. 

**Who is affected by the problem?**
PeeringDB users who are not affiliated with an organization.

**What is the impact?**
They cannot use advanced search to its full potential.

**Are there security concerns?**
I don't think so.

**Are there privacy concerns?**
I don't think so. 

**What are the proposed actions?**
This restriction should be removed. 

**What is the proposed priority?**
For discussion by the @peeringdb/pc 

**Provide a rationale for any/all of the above**
PeeringDB has a responsibility to the organizations sharing their data through it. This restriction does not limit the amount of data available to users. Instead, it make more data available so does not protect the organizations sharing data nor help legitimate users who want to find an interconnection facility within a given radius of a specific address.

**Additional context**
Example screenshot attached as a PDF
[advanced_search.pdf](https://github.com/peeringdb/peeringdb/files/7856448/advanced_search.pdf)

**Comment by arnoldnipper** [comment]
If users are not affiliated with an org they are orphaned and will be removed anyway.

**Comment by peterhelmenstine** [comment]
My initial thought: "What's the concern with having non org affiliated users not being able to search? What does being affiliated get you that you wouldn't allow the public? Not sure I understand the security concern here."

But now my current thought: "Sharing data without a source affiliation if they abuse the policy"

+1

**Comment by leovegoda** [comment]
Is it important that some of the search features only be made available to authenticated users with an organizational affiliation? If so, we should document the rationale. If not, could we open up this feature to users who are not logged in?

**Comment by peterhelmenstine** [comment]
Contact info is currently restricted. Would prevent folks from being spammed.

**Comment by leovegoda** [comment]
> Contact info is currently restricted. Would prevent folks from being spammed.

This search is not about contact information. It is about getting a list of interconnection facilities. At the moment we let anyone get the full list for a metro area but stop people from getting a smaller list by applying a radius filter. 

Users need to click through to find out more that links to the `fac`, information about the metro area and the number of networks present.

![Screen Shot 2022-01-13 at 9 36 03 AM](https://user-images.githubusercontent.com/59064677/149380619-7e5b2f36-60ed-4026-92e4-b95ae52d9344.png)

I am not sure what we are protecting by stopping people from reducing the amount of information they get from a search.

**Comment by leovegoda** [comment]
Geosearches are restricted to authenticated users to avoid abuse
