### ISSUE TITLE
Document Security Entrypoint for PeeringDB services

### ISSUE THREAD

**Issue by job** [peeringdb/peeringdb#1104]
We should document how people can reach out to PeeringDB staff for security related issues, create security@ alias, etc.

**Comment by grizz** [comment]
I've brought this up before, still +1 :)

**Comment by job** [comment]
security@peeringdb.com goes to me and Chris Caputo - will add more volunteers later.

**Comment by arnoldnipper** [comment]
+1

**Comment by leovegoda** [comment]
> Action items IMO
> 
> * @leovegoda to draft something

Working on this.
