### ISSUE TITLE
Release version missing on https://peeringdb.com/account/two_factor/

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/peeringdb#1107]
**Describe the bug**
Release version missing on https://peeringdb.com/account/two_factor/

**To Reproduce**
1.  go  https://peeringdb.com/account/two_factor/

**Expected behavior**
every page should show the complete footer

**Who is affected by the problem?**
everyone

**What is the impact?**

**Are there security concerns?**
no

**Are there privacy concerns?**
no

**What are the proposed actions?**
fix it

**What is the proposed priority?**
simply urgent/not

**Provide a rationale for any/all of the above**

**Additional context**

**Comment by jjavierweb** [comment]
Based on a quick review, it seems like the include statement is not rendering the value of the PEERINGDB_VERSION on the two-factor page footer, this could mean we have to either use "with" statement on the include or some other context type of inclusion

**Comment by arnoldnipper** [comment]
Routed through to 3a

**Comment by leovegoda** [comment]
This page now shows the release version in the footer at the bottom so I am closing the issue
