### ISSUE TITLE
Retirement of ARIN Non-Authenticated IRR

### ISSUE THREAD

**Issue by leovegoda** [peeringdb/peeringdb#1109]
**Is your feature request related to a problem? Please describe.**
ARIN is retiring ARIN-NONAUTH (https://lists.arin.net/pipermail/arin-announce/2022-January/002614.html). We might need to make updates to the code to stop new references to ARIN-NONAUTH and we might want or need to alert networks with references to SET objects in ARIN-NONAUTH to update their entries in PeeringDB.

**Who is affected by the problem?**
Networks that used the ARIN-NONAUTH IRR and not moved to another IRR and updated PeeringDB.

**What is the impact?**
Lower quality data

**Are there security concerns?**
Probably not

**Are there privacy concerns?**
No

**Describe the solution you'd like**
* Check if any code or configs need to be changed
* Check if we should notify networks that they need to update their PeeringDB entry

**Do you think this feature will require a formal design?**
We might need to design the notification process.

**Describe alternatives you've considered**

**Could this feature request need support from the Admin Committee?**
Some networks might need support from the AC

**What is the proposed priority?**
Our changes can follow ARIN's implementation

**Provide a rationale for any/all of the above**
We should not accept new references to ARIN-NONAUTH once it has gone and we should help networks that didn't realize their PeeringDB entry still referred to it to update.

**Additional context**

**Comment by arnoldnipper** [comment]
> **Who is affected by the problem?**
> Networks that used the ARIN-NONAUTH IRR and not moved to another IRR and updated PeeringDB.

ATM, no network prefixed their as-set with ARIN-NONAUTH.

**Comment by leovegoda** [comment]
@arnoldnipper If there is still no network using ARIN-NONAUTH then we can close this issue

**Comment by arnoldnipper** [comment]
No network is using ARIN-NONAUTH
