### ISSUE TITLE
Clean up legacy org and net mapping

### ISSUE THREAD

**Issue by grizz** [peeringdb/peeringdb#111]
PDBv1 did not allow for multiple networks per org, so both IX and Private Facility had local_asn fields which could be set to another ASN. PDBv2 introduced a much more flexible model, but kept the local_asn field, after the 2.0 release, it was changed to validate the local_asn was actually valid by making users create a network entity for it. That has caused a bit of confusion, since now the alternate ASNs actually have network entities, but their records could be on the primary ASN via local_asn.

To make matters worse, some views list net.asn while some list lan.local_asn, such as in #110

A way to resolve this would be to move all of the entries with local_asn to their respective networks, creating the network if needed. That would make the UI not show related ASNs, so we could want to add an option to also query by those.

**Comment by arnoldnipper** [comment]
At the same time the "Public Peering Exchange Points" and "Private Peering Facilities" view should also be moved to the org view thus allowing for all ASN of an org to be shown. 

With the "net view" you would only have the view of the network in question but not of all networks belonging to the same org.

**Comment by arnoldnipper** [comment]
I've added records for all ASN which pop up as asn in netixlan records.
[20170805-2add-asn.txt](https://github.com/peeringdb/peeringdb/files/1209592/20170805-2add-asn.txt)

**Comment by arnoldnipper** [comment]
I've added records for all ASN which pop up as asn in netfac records.
[20170810-2add-asn.txt](https://github.com/peeringdb/peeringdb/files/1236256/20170810-2add-asn.txt)

**Comment by eloos** [comment]
@arnoldnipper can you elaborate what the entries in the files you attached represent and what needs to be done in terms of data-cleaning?

**Comment by arnoldnipper** [comment]
> @arnoldnipper can you elaborate what the entries in the files you attached represent and what needs to be done in terms of data-cleaning?

Sorry, didn't reply to that. The entries in the files I attached contained ASN not yet having a `net`record but appereared as valued in `local_asn`

**Comment by arnoldnipper** [comment]
````sh
396029
200966
50607
131744
19733
133229
206235
````
didn't have a net entry. Fixed in `netfac` resp. `netixlan`
