### ISSUE TITLE
Add campus object

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/peeringdb#1110]
**Is your feature request related to a problem? Please describe.**
This feature request relates to #287. We agreed that two additional (pseudo facility) objects are needed via other fields to a `fac` object. Fields `landlord` and `campus`. Additionally, a field `part_of` describes that a facility is part of a `campus`.

**Who is affected by the problem?**
All facility operators who are lessees or run campus DC

**What is the impact?**
We get a clear structure of the complexity of facilities. It will be clear who is the owner. And it will be apparent that there might be multiple facility operators at the same address. Furthermore, facility operators who "joined" their campus DC into one `fac` object may now split this object again into separate facilities while still showing all the networks which are available on the campus.

**Are there security concerns?**
no

**Are there privacy concerns?**
no privacy concerns, but when implementing this feature, we should deal with data ownership of `ixfac` and `netfac` as we already did for `netixlan`

**Describe the solution you'd like**
Taken from #287, more precisely this [post](https://github.com/peeringdb/peeringdb/issues/287#issuecomment-739707546)

- add three fields `landlord`, `campus`, and `part_of` to the `fac` object
 - the field `landlord` should be used iff the Facility A is either a building or a subset of a building operated by a different entity than the parent building. The field's value is the id of the Facility L where Facility A belongs to or is part of. (Note: org_id(A) != org_id(L))
 - a facility with the field `campus` set to `true` can not be referenced in any fac relation (currently `ixfac` and `netfac`)
 - the diameter of a `campus` should not exceed 100km
 - the field `part_of` may be used to model a campus. A facility A having a `part_of` field with value N is part of the (pseudo)facility C with id N and which has set the field `campus` to `true`

**Do you think this feature will require a formal design?**
**yes**

**Additional context**
Having this feature is also a prerequisite for the `carrier` object.

**Comment by peterhelmenstine** [comment]
+1 agreed but may need some simple descriptions. Curious how we came up with 100km? Obviously latency is a concern but I'm just thinking for the *one* facility that'll likely be on the border and complain.

**Comment by martinhannigan** [comment]
A campus is a walkable parcel, not a State.

-1

**Comment by arnoldnipper** [comment]
> A campus is a walkable parcel, not a State.
 
@martinhannigan,  please read #287. It took us hours to get consensus. And define what "walkable" is (man pacific crest trail)

**Comment by martinhannigan** [comment]
Thanks. Re-read. You can see I opposed then.  I remain -1.

**Comment by arnoldnipper** [comment]
> Thanks. Re-read. You can see I opposed then. I remain -1.
>

Come on, @martinhannigan. Please be constructive. What do you propose instead? 100km also is walkable.

**Comment by leovegoda** [comment]
In today's @peeringdb/pc meeting there was an agreement that a campus could be defined by inter-building x-connects being available on the same basis as intra-building x-connects. A `campus` object could be created and an organization could place its own facilities within this campus. 

The `landlord` part of the discussion has been separated out and is now in https://github.com/peeringdb/peeringdb/issues/1235

**Comment by leovegoda** [comment]
Renamed issue to avoid confusion when people read the release notes
