### ISSUE TITLE
Bad API keys need to return 401 just like a bad user/pass. Presently they return 200.

### ISSUE THREAD

**Issue by ccaputo** [peeringdb/peeringdb#1117]
**Describe the bug**
With #266 we gained API keys. At present, a corrupt/expired/bogus API key simply results in an anonymous user session. This means the user has no feedback regarding a broken API key unless they are trying to make a change that requires change permissions. We should return HTTP 401 for a broken API key, and fail the request just like we would for a bad username/password, rather than returning HTTP 200 which is what we do now. Otherwise we have a bad pattern that gives developers the sense their client code is working, when it may actually not be.

I suspect the code below is the issue:

https://github.com/peeringdb/peeringdb/blob/c21130eed9b504c8cf3106f9665a2f7b38ecea92/peeringdb_server/permissions.py#L55-L78

**To Reproduce**
With a real API key, this will return data that includes User-only contact info:

```curl -v -H "Authorization: Api-Key <real API key>" -H "Content-Type: application/json" -X GET https://peeringdb.com/api/net/416```

This will return almost the same data, sans the User-only contact info:

```curl -v -H "Authorization: Api-Key BOGUS" -H "Content-Type: application/json" -X GET https://peeringdb.com/api/net/416```

Only a careful eye will catch the difference. We should not be so opaque.

**Expected behavior**
If an "Authorization:" header is present, fail and return HTTP 401 if its contents to not result in successful authentication.

**Who is affected by the problem?**
Client API users. We are trying to encourage greater API key usage.

**What is the impact?**
Wasted effort.

**Are there security concerns?**
Perhaps. A false sense of success (HTTP 200) can result in unknown consequential bugs.

**Are there privacy concerns?**
I don't think so, but I could be wrong.

**What are the proposed actions?**
See above.

**What is the proposed priority?**
I consider this urgent and hope others will too.

**Provide a rationale for any/all of the above**
API keys are useful when implemented well. At present our implementation seems buggy to me. I hope to reduce the wasted time of other developers, while also helping the Ops crew out by providing the community with the tools for increased use of authenticated sessions.

**Comment by mcmanuss8** [comment]
+1 clear (to me) bug

-Steve

**Comment by ccaputo** [comment]
Also, we should make clear in docs/api_keys.md which is preferred when both a user/pass and an API key is present. Only one should be checked when both are present, but I am not sure which should be favored. Or maybe it should be an outright failure when both are present, to avoid ambiguity?

**Comment by ynbrthr** [comment]
+1

**Comment by arnoldnipper** [comment]
+1 and routed through to 3a

**Comment by vegu** [comment]
Providing a non-existent api key should indeed raise an authentication failure.

> Also, we should make clear in docs/api_keys.md which is preferred when both a user/pass and an API key is present. Only one should be checked when both are present, but I am not sure which should be favored. Or maybe it should be an outright failure when both are present, to avoid ambiguity?

I think failure on providing two authentication methods should be the way to go. There is no way for us to tell which the user intended to use when they provided both in their script.

Ready to move this to `ready to implement` if people are happy with the above assessment.

**Comment by ccaputo** [comment]
> I think failure on providing multiple authentication methods should be the way to go. There is no way for us to tell which the user intended to use when they provided both in their script.

I think this makes good sense. Thx!

**Comment by ccaputo** [comment]
@vegu I've noticed something else:

```curl -v https://testbad:testpass@beta.peeringdb.com/api/net/416```

correctly returns 401 (and no response) while:

```curl -v https://testbad:testpass@beta.peeringdb.com/net/416```

incorrectly returns 200 and a response, albeit incomplete since the user was expecting data that requires authentication.

Authentication failure, whether with /api/ or without, and regardless of Content-Type:, should fail rather than incorrectly indicating successful authentication to the user.

**Comment by ccaputo** [comment]
With this new fix on beta, I have tested a variety of scenarios.

The good news...

- valid {org,user} api-key /api/ query: works
- valid {org,user} api-key non-/api/ query: works
- bogus {org,user} api-key /api/ query: fails as expected with 401
- bogus {org,user} api-key non-/api/ query: fails as expected with 401

- valid auth `https://testbad:testpass@beta.peeringdb.com` query: works
- bogus auth `https://testbad:testpass@beta.peeringdb.com` query: fails as expected with 401

- valid auth `Authorization: Basic` query: works
- bogus auth `Authorization: Basic` query: fails as expected with 401

- testing with both `Authorization: Basic` and `Authorization: Api-Key`: Returns 400 Bad Request, regardless of whether good auth data is present for either or both. I believe this is intended behavior.

The questionable news...

- bad auth with corrupt base64 input `"Authorization: Basic <corrupt base64 encoding>` query: fails with "Server Error (500)", which I didn't expect. Not sure if this should return 401 or whether 500 is an acceptable response. I expected 401.

> > I think failure on providing multiple authentication methods should be the way to go. There is no way for us to tell which the user intended to use when they provided both in their script.
> 
> I think this makes good sense. Thx!

Also questionable...

- testing with both `Authorization: Basic` and `https://testbad:testpass@beta.peeringdb.com`: Appears to favor the Authorization header and ignore the URL auth. Should we instead fail 400 when both are present?

- testing with both `Authorization: Api-Key` and `https://testbad:testpass@beta.peeringdb.com`: Appears to favor the Authorization header and ignore the URL auth. Should we instead fail 400 when both are present?

My concern with these last two is that a user may not understand why a request is failing with 401 when the Basic or Api-Key methods are not authenticating, while staring at what appears to be a correct user/pass. I'm wondering if it would simply be better to fail 400 when multiple auth methods are present, regardless of in the Authorization: header or the URL.

@vegu what do you think?

**Comment by ccaputo** [comment]
I should clarify that if these are low-priority corner/rare cases that we shouldn't worry about, I am happy to see this ticket be closed. @peeringdb/pc

**Comment by martinhannigan** [comment]
+1

**Comment by grizz** [comment]
@ccaputo I think we should probably address those, but in a different issue. :)

**Comment by ccaputo** [comment]
> @ccaputo I think we should probably address those, but in a different issue. :)

Sounds good. Closing this and have created #1133.
