### ISSUE TITLE
Bug in email address matching for ASNAUTO tool

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/peeringdb#1118]
**Describe the bug**
See https://peeringdb.deskpro.com/agent/#app.tickets,inbox:all,t.o:69727,vis:6. The request is coming from info@bdix.net. info@bdix.net is found at the RiR. However, the result is "We retrieved the RiR entry for the specified ASN 140684 but found no match with the requesting user."

**To Reproduce**
1. Go to https://peeringdb.deskpro.com/agent/#app.tickets,inbox:all,t.o:69727,vis:6
2. Or https://peeringdb.deskpro.com/agent/#app.tickets,inbox:all,t:69833,t.o:69832,vis:6
3. Or https://peeringdb.deskpro.com/agent/#app.tickets,inbox:all,t.o:69923,vis:6
4. See the behaviour

**Expected behavior**
Adress matching must work properly

**Who is affected by the problem?**
@peeringdb/ac 

**What is the impact?**
Extra work and confusion

**Are there security concerns?**
no

**Are there privacy concerns?**
no

**What are the proposed actions?**
investigate and fix the bug

**What is the proposed priority?**
simply urgent

**Provide a rationale for any/all of the above**

**Additional context**
![20220220_Deskpro-Agent-Interface](https://user-images.githubusercontent.com/16888757/154856374-58cfe767-4d4f-4dae-917a-2acca2a38fa2.png)

**Comment by peterhelmenstine** [comment]
+1 So the address is there but not matching? Some syntax error or something?

**Comment by Juimar** [comment]
+ 1

**Comment by leovegoda** [comment]
@arnoldnipper was this something that happened just once or is it happening repeatedly? If so, how often?

**Comment by grizz** [comment]
I'm looking through logs, but this looks like an intermittent failure from rdap services being unavailable.

**Comment by arnoldnipper** [comment]
> I'm looking through logs, but this looks like an intermittent failure from rdap services being unavailable.

If the RDAP service is not available I would expect the query to be re-queued!
