### ISSUE TITLE
Some command-line-tool executions are not logged

### ISSUE THREAD

**Issue by vegu** [peeringdb/peeringdb#1119]
**Describe the bug**

AC was trying to undo a facility merge using the `Facility Merge: UNDO` tool at https://www.peeringdb.com/cp/peeringdb_server/commandlinetool/ - the merge in question is missing from the the selection list.

Further investigation shows that the command-line-tool execution of the facility merge was not stored, and thus cannot be found to be undone.

This appears to be a regression bug affecting the following tools 

- `Renumber IP Space`
- `Merge Facility`
- `Merge Facility: UNDO`

**To Reproduce**
1. Do a facility merge through https://www.peeringdb.com/cp/peeringdb_server/commandlinetool/ 
2. Check https://www.peeringdb.com/cp/peeringdb_server/commandlinetool/ and see that the entry for the merge has not been logged.

**Who is affected by the problem?**

Some AC operations need to fall back to 20c support to help (undoing a facility merge)

**Comment by arnoldnipper** [comment]
@peeringdb/pc and @peeringdb/ac, this needs immediate fix IMO

**Comment by martinhannigan** [comment]
How often has the AC had to fall back to 20C to request an undo?

**Comment by peterhelmenstine** [comment]
+1 Seems obvious. Logging is important to know what happens.

**Comment by arnoldnipper** [comment]
> How often has the AC had to fall back to 20C to request an undo?

Bugs must be fixed. Fullstop!

**Comment by martinhannigan** [comment]
Yes. But priorities must be set properly to fix with limited resources.

**Comment by leovegoda** [comment]
Adding to what @martinhannigan has said above, we currently have more than 50 open issues for bugs. About 20 are ready for implementation but just tackling just those bugs would consume all our resources for several months. It's vital that we get a priority order for bugs so we can use our resources to the greatest effect.

**Comment by arnoldnipper** [comment]
IMO, we should request some extra money to do bug fixing. Esp. bug fixing for vital @peeringdb/ac tools has high priority.

**Comment by martinhannigan** [comment]
This would go back to my frequency/impact questions. I agree that logging
is an important function. My question was basically what is the impact to
quality and what is its frequency? That seems like a reasonable question.

I'll leave urgency (spend more money to fix {high,low level} bugs faster to
folks who do this for a living. The counts in terms of bugs should be
prefaced with priorities before we discuss more spending IMHO.

Warm regards,

-M<
