### ISSUE TITLE
Ops: response header X-Auth-ID to augment logging

### ISSUE THREAD

**Issue by ccaputo** [peeringdb/peeringdb#1120]
**Is your feature request related to a problem? Please describe.**

Ops needs to have the PeeringDB django code set an HTTP response header named "`X-Auth-ID:`".

Nginx could then use this response header for logging, and use `proxy_hide_header X-Auth-ID;` to prevent it from going to the client.

For the contents, I propose:

  - user/pass login: X-Auth-ID: <user>
    - example: "X-Auth-ID: altopia"

  - user/pass failed login: X-Auth-ID: <user>
    - example: "X-Auth-ID: altopia", and the 401 error code is sufficient to indicate a failed login

  - Org or User API-key login: X-Auth-ID: apikey_<prefix>
    - example: "X-Auth-ID: apikey_etwNzguc"

  - Org or User API-key failed login: X-Auth-ID: apikey_<prefix>
    - example: "X-Auth-ID: apikey_etwNzguc", and the 401 error code is sufficient to indicate a failed login

  - Anonymous: No X-Auth-ID: response header.

After implementation, in the nginx.conf Ops would then replace $remote_user with $sent_http_x_auth_id.

This will enable us to have visibility into what API key is being used along with maintaining the ability to see what user is being used, when a user/API-key authentication happens.

REQUIRED:

  - Since these come from users, any data put in this response header needs to be sanitized, along with all whitespace being converted to underscores, to prevent logs from being messed up or used as a buffer overrun vector. Also, usernames or apikeys that don't authenticate, should be length limited to 16 bytes in the response header. Valid usernames greater than 16 bytes are allowed.

  - Add additional validation to the User object to block creation of usernames starting with "apikey_".

**Who is affected by the problem?**
Operations (Ops).

**What is the impact?**
Without this feature, Ops is blind to which user/org is using an API-key.

**Are there security concerns?**
Yes. User supplied data needs to be sanitized before stored into the X-Auth-ID: response header.

**Are there privacy concerns?**
No, this is for internal Ops usage. Nginx will be configured to not send this header to the client.

**Do you think this feature will require a formal design?**
No. I have previously discussed this with @vegu and he indicated the effort seems like a good idea and implementation should be reasonably straightforward.

**Could this feature request need support from the Admin Committee?**
No, this is for internal Ops usage.

**What is the proposed priority?**
Urgent.

**Provide a rationale for any/all of the above**
Without this feature, Ops is blind to which user/org is using an API-key. Completing this is part of our efforts to promote increased API-key utilization and gain tools to be able to reach out to developers/users of client software which is inelegant and costly to PeeringDB.

**Comment by ccaputo** [comment]
@peeringdb/pc please support this. Ops needs it ASAP.

**Comment by grizz** [comment]
+1

**Comment by martinhannigan** [comment]
Is this a COGS issue, a security issue or both?

Thanks!

**Comment by ccaputo** [comment]
> Is this a COGS issue, a security issue or both? Thanks!

I'd say both.

**Comment by martinhannigan** [comment]
The COGS argument is strong. I don't totally understand the mechanics of
the security concern.

+1 controlling/reducing expense and financial risk is a priority.

**Comment by peterhelmenstine** [comment]
If Chris needs it that's good enough for me ;)

**Comment by ccaputo** [comment]
Reopening since:
- Non-API-key authentication is not resulting in X-Auth-ID: being set. It needs to.
- X-Auth-ID: is being sent to unrelated clients. Ie., it isn't being cleared between users.

**Comment by ccaputo** [comment]
Aside: The beta and prod servers now log the X-Auth-ID: response header and also prevent it from going to the client.

**Comment by ccaputo** [comment]
> * Non-API-key authentication is not resulting in X-Auth-ID: being set. It needs to.

This now works.

> * X-Auth-ID: is being sent to unrelated clients. Ie., it isn't being cleared between users.

Fix confirmed.

> * We need to limit _valid_ API Keys in X-Auth-ID: to just the prefix (the part prior to the '.'), so as to not reveal the whole API Key in logs (bad if they get shared) while listing enough to identify the user/org based on the key prefix.

Confirmed!
