### ISSUE TITLE
Ops: API throttling needs customizable messages

### ISSUE THREAD

**Issue by ccaputo** [peeringdb/peeringdb#1121]
**Is your feature request related to a problem? Please describe.**
With the advent of #853 Ops needs the ability to have customizable throttle messages returned with HTTP 429 that can be configured via the /cp/ interface. Labels as follows:

```
API: Anonymous user API throttle message

API: Authenticated user API throttle message
```

with corresponding environment variables API_THROTTLE_RATE_ANON_MSG & API_THROTTLE_RATE_USER_MSG or as appropriate.

if present, these would replace the current message. An example of which is:

```
Request was throttled. Expected available in 39 seconds.
```

Once created, Ops would then configure be able to configure template messages like the following:

```
Request was throttled. Expected available in <time>. Authenticate for less restrictions. For more information visit: https://docs.peeringdb.com/Xyz

Request was throttled. Expected available in <time>. For more information visit: https://docs.peeringdb.com/Xyz
```

Coding wise, this may provide insights: https://stackoverflow.com/questions/32932357/custom-throttling-response-in-django-rest-framework/32937123

**Who is affected by the problem?**
Potentially all API users.

**What is the impact?**
Better understanding of throttling when it occurs.

**Are there security concerns?**
No.

**Are there privacy concerns?**
No.

**Describe the solution you'd like**
See above.

**Do you think this feature will require a formal design?**
No, already done above.

**Describe alternatives you've considered**
N/A

**Could this feature request need support from the Admin Committee?**
The Admin Committee will need to be aware of the existence of throttling since the throttling may generate support requests. Networks that need support can be referred to the same web page, once it is active.

**What is the proposed priority?**
Urgent, from my Ops perspective of needing to keep the service functioning well for all, while also managing costs.

@peeringdb/oc @peeringdb/pc @peeringdb/ac please support.

**Comment by grizz** [comment]
I think this is a great idea, I'm not keen on having the messages in an environment variable tho. Any reason not to make it a static change? Alternatively I think a template file for it would be better -- or is there a reason I'm not thinking of to make it so dynamic?

+1 either way from me

**Comment by ccaputo** [comment]
> I think this is a great idea, I'm not keen on having the messages in an environment variable tho. Any reason not to make it a static change? Alternatively I think a template file for it would be better -- or is there a reason I'm not thinking of to make it so dynamic?

I'm not excited about waiting for a new production rollout between message changes if we need to fine tune what message is delivered or which URL we refer people to. I suppose we could simply make the URL be configurable for starters.

> +1 either way from me

Thanks.

**Comment by peterhelmenstine** [comment]
+ 1 feedback error messages are always good

**Comment by martinhannigan** [comment]
If someone actually correlates them (and manages costs). Logs aren't cheap.
Its a lot harder to use them effectively than many think.

Don’t overly invest in post mortems IMHO…..

**Comment by job** [comment]
This would benefit API constituents, +1

**Comment by ccaputo** [comment]
Testing of this on beta is yielding good results! Example messages configured and verified:

API: Anonymous API throttle rate message:

- `Request was throttled. Expected available in {time}. Authenticate for less restrictions. For more information visit: https://docs.peeringdb.com/howto/api_keys/`

API: Authenticated API throttle rate message

- `Request was throttled. Expected available in {time}. Consider better caching of results, such as by using peeringdb-py: https://github.com/peeringdb/peeringdb-py`
