### ISSUE TITLE
Logging for melissa (geo-address normalization) queries

### ISSUE THREAD

**Issue by vegu** [peeringdb/peeringdb#1122]
Ops needs to be able to track and review melissa (geo-address normalization) queries made from peeringdb.

We need to be able to monitor usage of the melissa api through its various integrations in peeringdb to keep tracks of costs associated with its usage.

This can be accomplished by logging such requests - as they happen - to a dedicated table that ops can review and aggregate through a cli.

**Comment by grizz** [comment]
+1

**Comment by arnoldnipper** [comment]
+1

**Comment by mcmanuss8** [comment]
+1 but can we instead log all calls at this level of granularity s.t. we can  do similar analysis?

**Comment by grizz** [comment]
We can, but you'd need to tell us which calls you'd like to include :)

This seems like a good place to use prometheus as well.

**Comment by mcmanuss8** [comment]
> We can, but you'd need to tell us which calls you'd like to include :)

All of them! ;)

But more seriously - ops probably wants to know:

api call name, api key used (or anon), interactive_or_frontend flag, client ip,  api args

And from there we can derive usage by api call, usage by api keys, usage by users using the api directly or using the frontend, usage by ip/asn level 

I think in this case you're thinking of logging the outbound to melissa, which could probably fit into that format
