### ISSUE TITLE
Ops: API throttling of repeated requests

### ISSUE THREAD

**Issue by ccaputo** [peeringdb/peeringdb#1126]
[co-created with @vegu and @grizz, but blame me for mistakes]

### Technical Side

Implement API rate limiting that will take into consideration the response size of a request and throttle repeated requests according to configuration.

We can extend the existing rate-limit functionality that exists in django-rest-framework to implement this.

Requests would be rate-limited if the same source (user/org or ip-address or ip-block (/24 or /64)) requests a qualifying API endpoint (e.g., size requirements met) a configurable amount of times within a configurable duration.

Use user (user/pass or API key) and org (API key) limitations when able/authenticated. If unauthenticated, ip-address & ip-block limits will instead be enforced.

This will augment, not replace existing rate limiting tools.

### Configuration

Controllable through the django-admin controlpanel:

- Size Threshold: minimum size of the response that would trigger rate limiting
- Time Window: Time window for consideration of repeated requests from the same user
- Limit: Maximum number of requests within time-window
- On/Off Toggle: to allow toggling off this rate-limiting entirely

with throttle details per class as follows:

- user: size, time limit, on/off
- org: size, time limit, on/off 
- unauth IP: size, time limit, on/off
- unauth IPv4 /24 & IPv6 /64: size, time limit, on/off

### In summation

As part of this, #1117, #1120, #1121, and https://github.com/peeringdb/peeringdb-py/issues/62 are needed so that we have what is needed for providing the incentives to users to use API keys or user/pass authentication, along with the ability to be able to reduce API overusage which causes problems for other API users. Additionally, this designed to help Ops control costs while being able to reach out and work with API users to more efficiently utilize the shared resource that is PeeringDB.

**Comment by arnoldnipper** [comment]
+1

**Comment by ccaputo** [comment]
@peeringdb/pc please help this move forward with your support. Thx!

**Comment by peterhelmenstine** [comment]
+ 1 We're going to inform folks somehow about this right? Not sure if the API would kick back a response when they are ratelimited

**Comment by ccaputo** [comment]
> * 1 We're going to inform folks somehow about this right? Not sure if the API would kick back a response when they are ratelimited

Yep, this is the idea with #1121. Would replace the current HTTP error code 429 message. An example of which is:

```
Request was throttled. Expected available in 39 seconds.
```

With something Ops would configure like the following:

```
Request was throttled. Expected available in <time>. Authenticate for less restrictions. For more information visit: https://docs.peeringdb.com/Xyz

Request was throttled. Expected available in <time>. For more information visit: https://docs.peeringdb.com/Xyz
```

**Comment by ynbrthr** [comment]
+1

**Comment by peterhelmenstine** [comment]
why are plus ones now show up in e-mails as negative?

**Comment by ccaputo** [comment]
> why are plus ones now show up in e-mails as negative?

I don't think I am seeing that, but in the case of your comment above you left a space between the '+' and the '1' which resulted in a bullet point rather than a "+1". You can edit that if you want to fix it.

**Comment by job** [comment]
Operationally hammering seems to become more and more of an issue. +1 from my side 

thanks @ccaputo for the willingness to assume any blame ;-)

**Comment by ccaputo** [comment]
> thanks @ccaputo for your willingness to assume any blame ;-)

Oh boy!

**Comment by martinhannigan** [comment]
+1 makes sense to me

**Comment by ccaputo** [comment]
Testing on beta...

Testing with "API: Response size throttle enabled for ip blocks" set to True is resulting in `Server Error (500)`.

That said, testing with the following enabled, is working well:

- API: Response size throttle enabled for ip addresses
- API: Response size throttle enabled for authenticated users (both api-key and user:pass methods tested)
- API: Response size throttle enabled for organization api-keys

**Comment by martinhannigan** [comment]
Im sure its obvious. But lost me. What happened?

**Comment by ccaputo** [comment]
> Im sure its obvious. But lost me. What happened?

The code to implement the IP block throttling has a bug which is resulting in HTTP response 500.

**Comment by ccaputo** [comment]
> Testing with "API: Response size throttle enabled for ip blocks" set to True is resulting in `Server Error (500)`.

I confirm this part is fixed.

Separately or related, not sure, I found another way to trigger `Server Error (500)`:

- Set API: Authenticated API throttle rate to 6666/minute
- `curl -s -v -H "Authorization: Api-Key <key>" -H "Content-Type: application/json" -X GET https://beta.peeringdb.com/api/net/416`
- Set API: Authenticated API throttle rate to 1/minute
- `curl -s -v -H "Authorization: Api-Key <key>" -H "Content-Type: application/json" -X GET https://beta.peeringdb.com/api/net/416`
- Observe `Server Error (500)`.

Happens with both user & org API keys and with user:pass@ auth.

Also anonymously:
- Set API: Anonymous API throttle rate to 6666/minute
- `curl -s -v -H "Content-Type: application/json" -X GET https://beta.peeringdb.com/api/net/416`
- Set API: Anonymous API throttle rate to 1/minute
- `curl -s -v -H "Content-Type: application/json" -X GET https://beta.peeringdb.com/api/net/416`
- Observe `Server Error (500)`.

**Comment by ccaputo** [comment]
The fix is good!

**Comment by EgeKaanGurkan** [comment]
Does anyone have a link or relevant information on the official rate limits and periods for authenticated users?
