### ISSUE TITLE
Structure addresses using a standard that supports floors and suite numbers

### ISSUE THREAD

**Issue by leovegoda** [peeringdb/peeringdb#1127]
**Is your feature request related to a problem? Please describe.**
We do not provide a structure for users to format addresses. This leads to users representing the same address in multiple ways. This makes it harder for users performing data analysis as they need to perform their own normalization when identifying interconnection facilities that exist in the same property. 

This is a particular issue for properties with multiple, independently operated interconnection facilities. In those cases, all users need a floor and/or suite number. See #255 for example.

**Who is affected by the problem?**
Facility operators are not guided as to the format that should be used. Searchers either need to manually normalize data or risk an incomplete analysis.

**What is the impact?**
The lack of structure for addresses reduces our ability to serve both facility operators and those searching for those facilities.

**Are there security concerns?**
No

**Are there privacy concerns?**
No

**Describe the solution you'd like**

- We should implement a standard for the representation of addresses developed by an appropriate standards body. Possible options include:
   - UPU S42 (ISO 19160)
   - RFC 5774 (Presence Information Data Format Location Object )
- We should then implement an interactive dialogue to suggest corrections to users when they enter an address on the website.
- We should periodically check addresses in PeeringDB against a known good source of addresses and use this data to identify if we need to do further work.

**Do you think this feature will require a formal design?**
Yes. We will need to update the address field based on the structure. We will need to work out if or how we should automatically update existing addresses. We will need to identify if we need to make changes to search and if so what they should be. We will need to update the address entry dialogue on the website.

**Describe alternatives you've considered**
See above

**Could this feature request need support from the Admin Committee?**
Not sure

**What is the proposed priority?**
Implement in 2022

**Provide a rationale for any/all of the above**

**Additional context**
Helping organizations offering interconnection services share their addresses in a single format makes them easier to find. This makes PeeringDB more useful to both them and the users searching it for interconnection options.

**Comment by martinhannigan** [comment]
-1 mission creep.

I'm responsible for several independently operated interconnection
facilities and I can see no benefit other than a heavy lift to change
what's already in place including billing, LOA's, etc. What's done is done
for almost all. Speaking for myself, I do not want to be guided beyond the
entry of how to find the location, who owns it, who is present and if
there's a MMR. The rest is course of business.

Certainly an interesting idea.

Thanks!

**Comment by arnoldnipper** [comment]
-1 as well. We have floor and suite in the address section. It's up to the users to fill in properly.

**Comment by arnoldnipper** [comment]
Two -1 so far. Hence closed. Please re-open
