### ISSUE TITLE
Return auth error when multiple auth methods are used

### ISSUE THREAD

**Issue by ccaputo** [peeringdb/peeringdb#1133]
Excerpted from #1117:

---

With this new fix on beta, I have tested a variety of scenarios.

The good news...

- valid {org,user} api-key /api/ query: works
- valid {org,user} api-key non-/api/ query: works
- bogus {org,user} api-key /api/ query: fails as expected with 401
- bogus {org,user} api-key non-/api/ query: fails as expected with 401

- valid auth `https://testbad:testpass@beta.peeringdb.com` query: works
- bogus auth `https://testbad:testpass@beta.peeringdb.com` query: fails as expected with 401

- valid auth `Authorization: Basic` query: works
- bogus auth `Authorization: Basic` query: fails as expected with 401

- testing with both `Authorization: Basic` and `Authorization: Api-Key`: Returns 400 Bad Request, regardless of whether good auth data is present for either or both. I believe this is intended behavior.

The questionable news...

- bad auth with corrupt base64 input `"Authorization: Basic <corrupt base64 encoding>` query: fails with "Server Error (500)", which I didn't expect. Not sure if this should return 401 or whether 500 is an acceptable response. I expected 401.

> > I think failure on providing multiple authentication methods should be the way to go. There is no way for us to tell which the user intended to use when they provided both in their script.
> 
> I think this makes good sense. Thx!

Also questionable...

- testing with both `Authorization: Basic` and `https://testbad:testpass@beta.peeringdb.com`: Appears to favor the Authorization header and ignore the URL auth. Should we instead fail 400 when both are present?

- testing with both `Authorization: Api-Key` and `https://testbad:testpass@beta.peeringdb.com`: Appears to favor the Authorization header and ignore the URL auth. Should we instead fail 400 when both are present?

My concern with these last two is that a user may not understand why a request is failing with 401 when the Basic or Api-Key methods are not authenticating, while staring at what appears to be a correct user/pass. I'm wondering if it would simply be better to fail 400 when multiple auth methods are present, regardless of in the Authorization: header or the URL.

---

To which @grizz wrote:

> @ccaputo I think we should probably address those, but in a different issue. :)

**Comment by grizz** [comment]
Agree with 401 and a message saying why for the first one.

For the second 2, I think we should do 400 with a message, even if any or all of them work. Something like that has the potential of making a developer go insane. :)

+1 from me

**Comment by ccaputo** [comment]
> Agree with 401 and a message saying why for the first one.
> 
> For the second 2, I think we should do 400 with a message, even if any or all of them work. Something like that has the potential to make a developer go insane. :)

Sounds good!

**Comment by martinhannigan** [comment]
+1

**Comment by vegu** [comment]
Putting the `user:pass` in the url is just shorthand for setting an `Authorization` header with basic auth.

In this case the client (curl) is deciding which to prioritize and i am guessing since it sees you explicitly specifying an `Authorization` header through -H it will omit adding another `Authorization` header for the user:pass part of the url.

I don't think this is something we can address on our end since the decision is made by the client (curl) and only one authorization header is sent to the server.

Multiple authorization headers already raise a bad request, so we should be covered on that end.

**Comment by ccaputo** [comment]
> Putting the `user:pass` in the url is just shorthand for setting an `Authorization` header with basic auth.
> 
> In this case the client (curl) is deciding which to prioritize and i am guessing since it sees you explicitly specifying an `Authorization` header through -H it will omit adding another `Authorization` header for the user:pass part of the url.
> 
> I don't think this is something we can address on our end since the decision is made by the client (curl) and only one authorization header is sent to the server.
> 
> Multiple authorization headers already raise a bad request, so we should be covered on that end.

In the case, the only issue left is the base64 one:

- bad auth with corrupt base64 input "Authorization: Basic <corrupt base64 encoding> query: fails with "Server Error (500)", which I didn't expect. Not sure if this should return 401 or whether 500 is an acceptable response. I expected 401.

**Comment by netravnen** [comment]
> bad auth with corrupt base64 input "Authorization: Basic  query: fails with "Server Error (500)", which I didn't expect. Not sure if this should return 401 or whether 500 is an acceptable response. I expected 401.

I favour returning *anything other* than 5xx responses. As 5xx responses are for indicating server side errors, afaik. Misleading the user/endpoint to the root cause of the issue.

> [400 Bad Request](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/400)
> The server cannot or will not process the request due to something that is perceived to be a client error (e.g., malformed request syntax, invalid request message framing, or deceptive request routing).
> [401 Unauthorized](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/401)
> Although the HTTP standard specifies "unauthorized", semantically this response means "unauthenticated". That is, the client must authenticate itself to get the requested response.

Either 400 or 401 would, in my opinion, be one of the correct response codes to return.

**Comment by netravnen** [comment]
For indicating a malformed base64 string, I favour 400 over 401.

**Comment by leovegoda** [comment]
**Summary**
1. When `Authorization: Basic` header is used in combination with `https://testbad:testpass@beta.peeringdb.com` return a 401 error
2. When  `Authorization: Api-Key` header is used in combination with `https://testbad:testpass@beta.peeringdb.com` return a 400 error with a message that is helpful to a software developer

**Comment by leovegoda** [comment]
**Updated summary**
When `Authorization: Basic` fails with corrupt base64 input return a [401 code](https://www.w3.org/Protocols/HTTP/HTRESP.html) with a message like "Corrupt base64 input" adjust the precise message text to make it helpful to software developers

**Comment by grizz** [comment]
Updated updated, I think 400 is the correct code to paint our bikeshed :)
