### ISSUE TITLE
Problem with oauth due to www. redirect

### ISSUE THREAD

**Issue by vegu** [peeringdb/peeringdb#1134]
**Describe the bug**

2.35.0 introduced redirecting from https://peeringdb.com to https://www.peeringdb.com for all requests. (#916)

This seems to have broken oauth if your application had its peeringdb oauth url set to `https://peeringdb.com`, resulting in the following error:

```
405 Client Error: Method Not Allowed for url: https://www.peeringdb.com/oauth2/token/
```

The error goes away if the application is instead configured to request from `https://www.peeringdb.com`

**Expected behavior**

For configuration purposes (and backwards compatibility) both `https://www.peeringdb.com` and `https://peeringdb.com` should work for oauth. 

**Who is affected by the problem?**

Applications using peeringdb for oauth that have been configured to send oauth requests to `https://peeringdb.com` instead of `https://www.peeringdb.com`

**Are there security concerns?**

no

**Comment by arnoldnipper** [comment]
Can we please fix this immediately?

**Comment by grizz** [comment]
+1 -- Documentation should be updated to use `auth.peeringdb.com` for OAuth.

**Comment by lamehost** [comment]
I am experiencing problems with Ouath2 that i believe were introduced by 2.35.0 that might be related

Oauth2 public authorization-code flow is failing with `401 - {'meta': {'error': 'Invalid username or password'}}` even though everytthing in the token request looks OK:
```
request url: https://auth.peeringdb.com/oauth2/token/
request body: grant_type=authorization_code&redirect_uri=https%3A%2F%2F0.0.0.0%2Fapi%2Fv1.0%2Fauth%2Fpeeringdb%2Fcallback&code=fdVjtGRGgXqxpi6p7vAlzcP4BDY3xq
request headers: {'Accept': 'application/json', 'Content-Type': 'application/x-www-form-urlencoded;charset=UTF-8'}
```

**Comment by grizz** [comment]
@lamehost I'm not aware of anything rolled out for 2.35 that would affect that -- invalid user/pass is simply an invalid username or password.

This issue is referring to an error in the redirect which wouldn't affect you since you're using `auth.peeringdb.com`.

Please double check your user/pass directly on peeringdb, and if it's still failing, open a new issue please.

**Comment by lamehost** [comment]
@grizz,

You're right. Looks like it is related to #1117. Please disregard
