### ISSUE TITLE
#727 RS Peer Checkbox followup changes

### ISSUE THREAD

**Issue by lukastribus** [peeringdb/peeringdb#1135]
This is a followup related to #727

@lukastribus wrote:

> Had a call with @arnoldnipper, we talked about different proposals and we agreed on the following:
> 
>     * adjust the colors of the icon so that it matches with the existing UI
> 
>     * move the icon to the policy column, as the RS peer is indeed a policy decision of the AS so it makes sense to have it there
> 
> 
> Using a checkbox would require renaming the column ("RS/Policy" or something) and that would mean it no longer matches the data model/API, which is also to be avoided.
> 
> So the 2 changes proposed above is a good compromise we both agreed on.
> 
> Any feedback would be much appreciated.
> 
> Thanks

@arnoldnipper wrote:

> > So the 2 changes proposed above is a good compromise we both agreed on.
> 
> +1

**Comment by arnoldnipper** [comment]
@peeringdb/pc, please make up your mind

**Comment by grizz** [comment]
I agree with changing the color, maybe something like the following:

![image](https://user-images.githubusercontent.com/23176/159497100-26cf0d01-4b65-4c36-9800-982dfe50eed2.png)

Moving it to the Policy column also makes sense, but I don't think we need to change the column name, we should change the tooltip from `RS Peer` to `Routeserver Peer` and I think that would be enough. Here is yet another time it would be nice to have a UX professional. :)

> Using a checkbox would require renaming the column ("RS/Policy" or something) and that would mean it no longer matches the data model/API, which is also to be avoided.

The visual UI doesn't need to follow the API, in fact, in most cases it shouldn't. All that matters is all the information is available via the API, which it is.

**Comment by lukastribus** [comment]
> I agree with changing the color, maybe something like the following

Yes, I like it 👍 


> I don't think we need to change the column name

Indeed the proposal is to not change any names.


> we should change the tooltip from RS Peer to Routeserver Peer and I think that would be enough

Agreed.

**Comment by peterhelmenstine** [comment]
+1. I like Arnold's idea of the left arrow pointing inside too but it might be too fancy for some ;)

**Comment by lukastribus** [comment]
I don't object.

**Comment by martinhannigan** [comment]
+1 I dont care.

**Comment by lukastribus** [comment]
What's missing at this point?

Is additional consensus necessary? Does this need manpower for logo update and code change?

**Comment by vegu** [comment]
**Summary**
- replace icon graphic with https://github.com/peeringdb/peeringdb/issues/1135#issuecomment-1075213716
- move the icon to to the policy column
