### ISSUE TITLE
[beta] new api throttling logic causes bug in api-cache generation

### ISSUE THREAD

**Issue by vegu** [peeringdb/peeringdb#1146]
**Describe the bug**

Implementation of #1126 resulted in a bug that causes api-cache no longer to be built reliably.

**Comment by arnoldnipper** [comment]
+1 and routed through to 3a as clearly identified as a bug by a developer

**Comment by martinhannigan** [comment]
Hi Stefan - thanks. Can you explain a little more with regards to how the
bug manifests itself and what the impact is? I'd like to support this
including commenting on priority.

Thanks!

**Comment by ccaputo** [comment]
> Hi Stefan - thanks. Can you explain a little more with regards to how the bug manifests itself and what the impact is? I'd like to support this including commenting on priority. Thanks!

Hi @martinhannigan, while it is believed this is now fixed on beta, this fix was needed because throttling code was breaking api-cache generation. api-cache generation is a periodic cron task which needs to function properly and unimpeded.
