### ISSUE TITLE
[beta] performance issue when authenticating via api keys

### ISSUE THREAD

**Issue by vegu** [peeringdb/peeringdb#1147]
**Describe the bug**

Requesting the api while authenticating via api-key is significantly slower (2-3 times) in 2.36.0-beta when compared to 2.35.0

Cause has not been determined at this point - recommendation is for it to be fixed before 2.36.0 is rolled out to production.

**Comment by arnoldnipper** [comment]
+1 and routed through to 3a as identified as a big by a developer

**Comment by ccaputo** [comment]
Speedup confirmed.
