### ISSUE TITLE
parse json ixp-member-list

### ISSUE THREAD

**Issue by grizz** [peeringdb/peeringdb#115]
This will need to have a json_member_list field added to each IX Lan, and a cron job that periodically fetches, parses, and coverts to an internal PDB format

**Comment by dorkmatt** [comment]
How is this different then #116? The schema makes a recommended URL location, we shouldn't be parsing the readme markdown file.

**Comment by grizz** [comment]
@dorkmatt added a better description instead of just my notes :)

**Comment by vegu** [comment]
fixed in cf295a0
