### ISSUE TITLE
Tab URLs don't work anymore

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/peeringdb#1152]
**Describe the bug**
All the tab URLs https://www.peeringdb.com/org/nnnnn#{add_net,add_ix,users,...} don't work anymore

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to any org
2. Click on any tab, copy and paste
3. See that you are at the org base URL

**Expected behaviour**
URLs should work as intended

**Who is affected by the problem?**
All users

@peeringdb/ac, please verify and confirm

**Comment by peterhelmenstine** [comment]
+1 imbedded html tables issue?

**Comment by grizz** [comment]
+1

This looks like a Chrome bug as it works in the other browsers I've tried and the HTML is correctly giving it the correct URL. I'm guessing there's a work around for Chrome.

**Comment by arnoldnipper** [comment]
I've tried w/ Edge Version 100.0.1185.50 (Offizielles Build) (64-Bit) and doesn't work either
