### ISSUE TITLE
Exporting Advanced Search broken

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/peeringdb#1153]
**Describe the bug**
Trying to export https://www.peeringdb.com/export/advanced-search/fac/json-pretty?undefined=1187&limit=250&depth=1 results in '{"non_field_errors": ["Internal Error (500)"]}'

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to https://www.peeringdb.com/advanced_search?reftag=fac
2. Click on "Search" and then on "JSON" or on "CSV"
3. See an error

**Expected behaviour**
Export as JSON/CSV file

**Who is affected by the problem?**
All users

@peeringdb/ac and @peeringdb/pc, please confirm

**Comment by leovegoda** [comment]
I see the same error

**Comment by peterhelmenstine** [comment]
+1 Bad error

**Comment by vegu** [comment]
can reproduce bug on dev environment

**Comment by arnoldnipper** [comment]
Routed through to 3a as big is confirmed by a developer
