### ISSUE TITLE
Broken doc URL

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/peeringdb#1154]
**Describe the bug**
https://github.com/peeringdb/docs/blob/master/release_notes/release_notes_2021 throws a 404. Same for https://github.com/peeringdb/docs/blob/master/release_notes/release_notes_2020

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to https://docs.peeringdb.com/release_notes/
2.  Scroll down and click on [2021 Release Notes](https://github.com/peeringdb/docs/blob/master/release_notes/release_notes_2021)

**Expected behaviour**
Links must work

@leovegoda and @peeringdb/pc, please verify

**Comment by leovegoda** [comment]
If I go to https://docs.peeringdb.com/release_notes/ and scroll down and click on the links I get a working page

**Comment by leovegoda** [comment]
> Not sure a website doc defect is a bug. Can we just fix without the overhead?

I agree. But I don't think this is actually a broken link. I expect it was a temporary glitch because I cannot reproduce it.

**Comment by martinhannigan** [comment]
Im getting a 404 via safari ios mobile on his item 2. The rest arent
reproducible by me.

**Comment by leovegoda** [comment]
> Im getting a 404 via safari ios mobile on his item 2. The rest arent
> reproducible by me.

I have tried again from iOS on a different network but cannot reproduce this. The pages are there. There could be a web server problem but the pages themselves are fine.

**Comment by peterhelmenstine** [comment]
It's working for me. Not getting any 404.

**Comment by martinhannigan** [comment]
Logs? Should be a record.
