### ISSUE TITLE
An account with admin status can not have permissions

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/peeringdb#1157]
**Describe the bug**
An account with admin status can not have permissions. I.e. 
 - when upgrading from "member" to "admin", any permissions must be removed
 - when having the status "admin", adding permissions must not be possible
 
**To Reproduce**
Steps to reproduce the behaviour:
1. Go to https://www.peeringdb.com/cp/peeringdb_server/userpermission/81925/change/
2. Otoh, see [Users](https://www.peeringdb.com/org/14444#users), resp. [Permissions](https://www.peeringdb.com/org/14444#manage_perms)

**Expected behaviour**
An admin account is an admin account. Hence, permissions don't make sense

**Who is affected by the problem?**
Some users. And [AC](@peeringdb/ac)

**What is the impact?**
Unexpected behaviour; confusion

**Are there security concerns?**
no

**Are there privacy concerns?**
no

**Additional context**

![20220426 PeeringDB 02](https://user-images.githubusercontent.com/16888757/165397539-5c8c0dff-6824-4a64-a74c-6702103469b6.png)
![20220426 PeeringDB 01](https://user-images.githubusercontent.com/16888757/165397542-4005ee89-954d-470d-a360-acc014d5d3bc.png)

**Comment by peterhelmenstine** [comment]
+1 Yup. confusing and annoying

**Comment by grizz** [comment]
+1 and bug, yes

**Comment by Juimar** [comment]
+1

**Comment by vegu** [comment]
**summary**
- An account with organization admin status should not have manageable granular permissions
- When upgrading from "member" to "admin", any permissions must be removed
- when having the status "admin" in an organization, managing granular permissions to objects within that org must not be possible
