### ISSUE TITLE
Allow updates from IXP member list

### ISSUE THREAD

**Issue by grizz** [peeringdb/peeringdb#116]
https://github.com/euro-ix/json-schemas

Should support push and pull

**Comment by eloos** [comment]
From euro-ix:
At present Euro-IX is the only IXPA interface ready to talk with PeeringDB -  we encourage ALL IXPs to use the Euro-IX website while others are being worked on.
•APIX started work, LAC-IX and AFIX to come..

Do we know how we need to integrate all of these? Or will IX-F provide a consolidated view via the API?

**Comment by arnoldnipper** [comment]
The Euro-IX format was adopted by IX-F. And I expect work from IX-F in the  not so far future

**Comment by grizz** [comment]
The format is completely standalone, which associations also use it is irrelevant (except for choosing to adopt it), it would be IX directly to PDB

**Comment by dorkmatt** [comment]
SFMIX is in support of this, as already publish the JSON file and it would be great that this would be our conduit into publishing data into PeeringDB (pull support initially is fine, no need for push). However, I could see some of our participants may not want to be listed, maybe enhancing the schema with a flag to publish or not?

**Comment by arnoldnipper** [comment]
The idea is to use this data to only *synchronize* data. The decision to be listed at an IXP still is with the network. However if it decides to be listed then the information about the IP addresses will be overwritten by the information provided by the IXP: Especially if the IXP does not list the ASN as being connected the network will not be shown

**Comment by dorkmatt** [comment]
@arnoldnipper Ok, just to be clear - the only JSON sections PeeringDB would sync is "ixp_list" but not "member_list".

**Comment by arnoldnipper** [comment]
@dorkmatt the idea of this feature request is to use "member_list" to synchronize data. Of course, the information from "ixp_list" could also be used to update information. But that seems to be less useful as this information more or less is static while the informatin from "member_list" is very dynamic
