### ISSUE TITLE
better rdap error reporting

### ISSUE THREAD

**Issue by grizz** [peeringdb/peeringdb#1164]
In our ongoing quest for better RDAP error reporting in the automatic network validator, we've found a new error case to handle. If the RIR does a 301 referral that doesn't resolve or work, we should catch that and report as such.

We should also check for any lookup errors resulting from RIR provided information, as this isn't the first time it's happened.

@peeringdb/ac What would you like to see in the created ticket? I was thinking the RDAP request tree, with a full stack trace for any errors. Would that be too much information?

**Expected behavior**
A clear and concise error message of where and why the RDAP lookup is failing.

**Who is affected by the problem?**
New network signups and the AC since it affects

**What is the impact?**

**Are there security concerns?**
no

**Are there privacy concerns?**
no

**Comment by peterhelmenstine** [comment]
+1 like it!

**Comment by arnoldnipper** [comment]
+1

**Comment by arnoldnipper** [comment]
> @peeringdb/ac What would you like to see in the created ticket? I was thinking the RDAP request tree, with a full stack trace for any errors. Would that be too much information?

Probably ... otoh, it doesn't happen so often. It's more important the user gets a meaningful error message and not only "500 Something went wrong"

@peeringdb/ac still can create the entry and also affiliate the user with the organisation via the permissions GUI.

**Comment by netravnen** [comment]
> I was thinking the RDAP request tree, with a full stack trace for any errors. Would that be too much information?

If you include the message as an internal note or an attached text file in the ticket. That _might_ be useful. As @arnoldnipper, it is not often it happens. But the information can be useful, still. :)

> It's more important the user gets a meaningful error message and not only "500 Something went wrong"

Agreed

**Comment by mcmanuss8** [comment]
+1

**Comment by vegu** [comment]
**summary**

- proper error raising on invalid redirects in rdap data
- user friendlier errors on unhandled exceptions when interpreting rdap data
