### ISSUE TITLE
Ops: Throttle strings with "Response size" should be renamed "Repeated request"

### ISSUE THREAD

**Issue by ccaputo** [peeringdb/peeringdb#1168]
At: https://github.com/peeringdb/peeringdb/blob/60c706687056db4ca24b555f2de010a6a91042c6/peeringdb_server/models.py#L5418-L5475 strings with "Response size" should be renamed "Repeated request".

Not sure if a migration is also needed for this change.

Purpose is that the current language will be confusing to future admins. These throttle mechanisms have to do with identical repeated requests, combined with certain size minimums. The current language does not indicate that.

Variable names can remain unchanged.

**Comment by mcmanuss8** [comment]
+1

**Comment by arnoldnipper** [comment]
+1

**Comment by grizz** [comment]
> Variable names can remain unchanged.

I think we might as well rip off the bandage and change them now, or it might be quite confusing down the road as to why the variable names don't match the description. :)

**Comment by martinhannigan** [comment]
+1

**Comment by ccaputo** [comment]
Fix confirmed on beta.
