### ISSUE TITLE
Ops: Exempt superusers (PeeringDB Admin Committee & Operations Committee admins) from throttling

### ISSUE THREAD

**Issue by ccaputo** [peeringdb/peeringdb#1172]
API and Melissa request throttling needs to not apply to superuser (admin) authenticated requests.

**Comment by martinhannigan** [comment]
What circumstances would this typically occur? Are you concerned about
abuse? (circumvention).

Asking re $ inpact since this is partly why we dis this?



Thanks

**Comment by ccaputo** [comment]
> What circumstances would this typically occur? Are you concerned about abuse? (circumvention). Asking re $ inpact since this is partly why we dis this? Thanks

I have clarified the title. This is for Admin Committee and Operations Committee admins, to prevent them from being throttled while they are trying to do their jobs.

I think members of these committees will be careful with respect to accidental abuse.

An example of why I created this today is because an Admin Committee member needed to perform more Melissa address checks than a normal user ever would in a small time frame, and they were throttled.

**Comment by grizz** [comment]
+1

With the original email and Chris and I, we have 3 committee members, so bumping to Reached.

**Comment by martinhannigan** [comment]
All good.

How do we have oversight?

Thanks

**Comment by grizz** [comment]
> How do we have oversight? Thanks

Good point. I was thinking we didn't need any, but an admin user could have an unrelated script that has a bug so it's probably best to just make it a separate limit?

Thoughts @ccaputo ?

**Comment by martinhannigan** [comment]
On Thu, May 26, 2022 at 21:16 Matt Griswold ***@***.***>
wrote:

> How do we have oversight? Thanks
>
> Good point. I was thinking we didn't need any, but an admin user could
> have an unrelated script that has a bug so it's probably best to just make
> it a separate limit?
>
> Thoughts @ccaputo <https://github.com/ccaputo> ?
>


Thanks. That. And cost auditing.

Who was throttled and what were they asking for?

Warm Regards,

-M<

**Comment by ccaputo** [comment]
> > How do we have oversight? Thanks
> 
> Good point. I was thinking we didn't need any, but an admin user could have an unrelated script that has a bug so it's probably best to just make it a separate limit?
> 
> Thoughts @ccaputo ?

If there is a bug in the throttling mechanisms, I think it is more important that a PeeringDB Admin be exempt from the throttling, rather than create a separate category of throttling.

> Who was throttled and what were they asking for?

I am not going to name the name. The person can chime in if they like, but I don't think it is germane. Above I answered with: "an Admin Committee member needed to perform more Melissa address checks than a normal user ever would in a small time frame, and they were throttled".

**Comment by martinhannigan** [comment]
On Thu, May 26, 2022 at 9:55 PM Chris Caputo ***@***.***>
wrote:

> How do we have oversight? Thanks
>
> Good point. I was thinking we didn't need any, but an admin user could
> have an unrelated script that has a bug so it's probably best to just make
> it a separate limit?
>
> Thoughts @ccaputo <https://github.com/ccaputo> ?
>
> If there is a bug in the throttling mechanisms, I think it is more
> important that a PeeringDB Admin be exempt from the throttling, rather than
> create a separate category of throttling.
>
> Who was throttled and what were they asking for?
>
> I am not going to name the name. The person can chime in if they like, but
> I don't think it is germane. Above I answered with: "an Admin Committee
> member needed to perform more Melissa address checks than a normal user
> ever would in a small time frame, and they were throttled".
>

OK. Whats the question that was throttled?

**Comment by ccaputo** [comment]
> OK. Whats the question that was throttled?

It wasn't a query, but rather a POST. Melissa address checks are performed when an address is entered. It is an address normalization feature. See https://github.com/peeringdb/peeringdb/issues?q=melissa+

**Comment by martinhannigan** [comment]
On Thu, May 26, 2022 at 10:07 PM Chris Caputo ***@***.***>
wrote:

> OK. Whats the question that was throttled?
>
> It wasn't a query, but rather a POST. Melissa address checks are performed
> when an address is entered. It is an address normalization feature. See
> https://github.com/peeringdb/peeringdb/issues?q=melissa+
>
> a
>

Fair enough. Rather than grant a wide privilege, perhaps we can create
automation for such an activity? Better than an exception As an
alternative, a public log of post or query AC activity that may violate
norms may be an easy way to oversee so there is no abuse. Without an easy
audit function related to cost I’m skeptical this is a big need.

**Comment by arnoldnipper** [comment]
+1

**Comment by ccaputo** [comment]
> Fair enough. Rather than grant a wide privilege, perhaps we can create automation for such an activity? Better than an exception As an alternative, a public log of post or query AC activity that may violate norms may be an easy way to oversee so there is no abuse. Without an easy audit function related to cost I’m skeptical this is a big need.

This issue is about helping the Admin Committee do their job as it exists today. I believe changing how they do their job, or a public log of their actions, is a separate discussion for a different forum/issue.

I am trying to implement throttling for cost control and resource sharing. Until this issue is resolved, the Melissa throttling rollout is blocked.

**Comment by martinhannigan** [comment]
On Thu, May 26, 2022 at 23:47 Chris Caputo ***@***.***> wrote:

> Fair enough. Rather than grant a wide privilege, perhaps we can create
> automation for such an activity? Better than an exception As an
> alternative, a public log of post or query AC activity that may violate
> norms may be an easy way to oversee so there is no abuse. Without an easy
> audit function related to cost I’m skeptical this is a big need.
>
> This issue is about helping the Admin Committee do their job as it exists
> today. I believe changing how they do their job, or a public log of their
> actions, is a separate discussion for a different forum/issue.
>
> I am trying to implement throttling for cost control and resource sharing.
> Until this issue is resolved, the Melissa throttling rollout is blocked.
>
>

If this is just to complete the rollout I see no problem.

**Comment by vegu** [comment]
**summary**

- implement separately configurable api throttling limits for superusers

**Comment by mcmanuss8** [comment]
+1
