### ISSUE TITLE
Enforce Session Timeouts

### ISSUE THREAD

**Issue by prithvimanikonda** [peeringdb/peeringdb#1180]
**Is your feature request related to a problem? Please describe.**
Currently, PeeringDb portal does not enforce session timeout and Django picks up 2 weeks as the default for session expiry. The general guidance is to have the authenticated sessions be timed out after 1 hour.

**Who is affected by the problem?**
This does not affect the usability of the portal but if sessions do not expire we run into a risk of having unauthorized access to the portal.

**What is the impact?**
The impact is minimal as the physical access to the computer is needed

**Are there security concerns?**
Minimal

**Are there privacy concerns?**
Minimal

**Describe the solution you'd like**
Django offers a mechanism to set cookie timeout of the sessions which can be used to set the timeout. Also, for authenicated users, we can redirect the customers to the login page.

**Do you think this feature will require a formal design?**
No

**Describe alternatives you've considered**
No alternatives were considered but we can also implement a middleware that does this rather than relaying on out of box middleware.

**Could this feature request need support from the Admin Committee?**
Yes, to approve the pull requests and merging it

**What is the proposed priority?**
Mild

**Comment by prithvimanikonda** [comment]
https://github.com/peeringdb/peeringdb/pull/1179

**Comment by ccaputo** [comment]
@prithvimanikonda Please clarify if this would this cause web logins to expire after 2 hours? If yes, a big thumbs down from me. That is a fundamental user experience change for PeeringDB, that should be fully considered by the @peeringdb/pc. Personally, I would be frustrated to have to go through the login and 2FA process multiple times per day.

**Comment by peterhelmenstine** [comment]
Would 2nd Chris (ccaputo)'s concern above. Is the UI the same as the webportal? Assume so in which case 1 hour would be pretty annoying.

**Comment by martinhannigan** [comment]
We need to hear from security experts on best practice for this as a start.
Good idea in concept.

**Comment by grizz** [comment]
> Would 2nd Chris (ccaputo)'s concern above. Is the UI the same as the webportal? Assume so in which case 1 hour would be pretty annoying.

Thirded, the 2 weeks even annoys me :)

Is there a NIST best practice for this?

**Comment by ccaputo** [comment]
> Thirded, the 2 weeks even annoys me :)

Amen.

Perhaps the peeringdb.com web user experience could have one long timeout while OAuth users have a shorter timeout?

Or have a short default but allow users to set a longer timeout if they have knowledge of the security of their own environment, with help text caveating the risks of doing so.

Alternatively or also, OAuth confederate sites could set a recent login requirement if their own portal standards are stricter than what is decided for users for the peeringdb.com web site.

**Comment by prithvimanikonda** [comment]
The following is the proposal to split the session cookie in a way that we can have two different timeouts based on API user vs Web user

[PeeringDB Session Timeout Proposal.pdf](https://github.com/peeringdb/peeringdb/files/9105102/PeeringDB.Session.Timeout.Proposal.pdf)

**Comment by prithvimanikonda** [comment]
Here is the PR based on the proposal that I had put forward: https://github.com/peeringdb/peeringdb/pull/1208

**Comment by mcmanuss8** [comment]
+1 to separating the oauth and www session timeouts. 

Proposal:
We'll keep the www timeout the same and set the oauth timeout to a configurable (by ops) min and max. This will let the application leveraging our oauth make some decisions about how long to honor it within reason. 
In email we had landed on a 30minute minimum and 7day maximum.

@peeringdb/pc  please vote

**Comment by martinhannigan** [comment]
+1

**Comment by grizz** [comment]
+1

**Comment by peterhelmenstine** [comment]
+1

**Comment by kaycliff** [comment]
+1Sent from my iPhoneOn Oct 4, 2022, at 6:46 PM, Peter Helmenstine ***@***.***> wrote:﻿
+1
