### ISSUE TITLE
Manual IX-F import request queue can get stuck

### ISSUE THREAD

**Issue by vegu** [peeringdb/peeringdb#1182]
**Describe the bug**

It is possible for an internet exchange admin to trigger manual IX-F import requests without having their import url set. If enough exchanges do this it will cause the queue to get stuck at which point ops needs to clear it out for manual ix-f imports to get processed again.

**To Reproduce**

Request import without ever setting the IX-F import url (it needs to be `null`, if it is `""` it does not trigger the issue) on 5 or more exchanges.

**Expected behavior**

- It should not be possible to queue for manual import if the exchange has no ix-f import url set
- The IX-F importer should discard manual import requests if the url is null

**Who is affected by the problem?**

Any IX operators wanting to trigger a manual IX-F import for their exchange.

**What is the impact?**

Ops needs to manually fix the queue when it gets stuck like this.

**Comment by arnoldnipper** [comment]
Routed through to 3a as this was identified as a bug by a developer

**Comment by mcmanuss8** [comment]
+1

**Comment by ccaputo** [comment]
@peeringdb/pc this was hit again and wasted time of multiple people to figure out. Please schedule it to get fixed ASAP.

**Comment by leovegoda** [comment]
@ccaputo @arnoldnipper I'd like to get this scheduled for 2.51.0. To do that, we need to agree what the implementation should be. Does this approach make sense?

**Summary**
- The manual import option should always be disabled until an import URL is set
- There should be a tooltip noting that the option can only be enabled when an import URL is set
- When a URL is set, things should run as they do now

**Comment by ccaputo** [comment]
> > Looks good, but additionally: "The IX-F importer should discard manual import requests if the url is null".
> 
> If there is no URL, you can't click on "Request import". Hence, the importer has nothing to discard.

What I mean is that internally, within the IX-F Importer rather than the UX/UI, there should be an internal failsafe which discards manual import requests if the URL is ever null.

**Comment by vegu** [comment]
closed through https://github.com/peeringdb/peeringdb/pull/1440
