### ISSUE TITLE
OAuth logins with 2FA don't complete first time

### ISSUE THREAD

**Issue by benjojo** [peeringdb/peeringdb#1191]
**Describe the bug**

When a user is authenticating to another site via the [peeringdb OAuth](https://docs.peeringdb.com/oauth/) system, and they are not logged in to PeeringDB already, and they have 2FA enabled, the flow dumps them into the main page after 2FA, and not the OAuth flow.

**To Reproduce**
1. Launch private browsing window to ensure clean, logged out session.
1. Go to https://bgp.tools/authed/manage-peering to login to bgp.tools with PeeringDB (with a 2FA account)
1. Note how you are dumped to the front page rather than the expected permissions screen.

**Expected behavior**

For 2FA users to get the permissions screen after 2FA auth, like the non 2FA users do

**Who is affected by the problem?**

bgp.tools users, and probably anyone else using OAuth logins

**What is the impact?**

People get confused during login flows. Making PeeringDB OAuth harder to use.

**Are there security concerns?**

At least one person disabled 2FA because of this

**Comment by leovegoda** [comment]
This looks important in the context of #1180

**Comment by vegu** [comment]
I was **not** able to reproduce this while using OTP for 2FA approach.

I was able to reproduce this while using U2F for 2FA approach.

So it seems like a bug with the latter.

**Comment by vegu** [comment]
@benjojo were you using a U2F device or a one-time-password (google authenticator) as 2FA method?

**Comment by benjojo** [comment]
I actually don't use 2FA on my PeeringDB account, but I can try and ask the
users who hit this

**Comment by benjojo** [comment]
It was a U2F device yes

**Comment by arnoldnipper** [comment]
Routed through to 3a as identified as a bug by a developer

**Comment by mcmanuss8** [comment]
+1
