### ISSUE TITLE
Add automated testing at the browser level

### ISSUE THREAD

**Issue by vegu** [peeringdb/peeringdb#1198]
There currently are no automated tests at the browser level, so changes to the UX require manual review and are time consuming and prone to oversight.

Adding a suite of browser-based tests that we can ideally run against a dev instance or beta after a beta deploy would go a long way towards improving quality control for new releases.

It would also help with the process of accepting outside patches that touch UX parts.

**Comment by peterhelmenstine** [comment]
+1 Makes sense to me.

**Comment by grizz** [comment]
+1

And yes, sooner than later. :)

**Comment by martinhannigan** [comment]
+1

**Comment by prithvimanikonda** [comment]
+1
