### ISSUE TITLE
CSRF Failed: CSRF token missing or incorrect

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/peeringdb#120]
User gets this error message and is unable to edit his records

**Comment by grizz** [comment]
It can happen on poor connections that get lots of time outs. What browser/version/os?

**Comment by grizz** [comment]
closing for lack of info

**Comment by netravnen** [comment]
Also.
Refer to the following ticket https://peeringdb.deskpro.com/agent/#app.tickets,inbox:archive_resolved,t.o:11130,vis:5 which popped up recently regarding the same issue.

**Comment by vegu** [comment]
How often do we still see this occur on average?

**Comment by netravnen** [comment]
@vegu I do not know. First time i have handled a ticket with this error reported.
I suspect something between the user and the server maybe causing this. (Fx ssl/tls proxy in corp environment) But in reality I know nothing.

**Comment by arnoldnipper** [comment]
Every 4-6 weeks
