### ISSUE TITLE
Improve Search Functionality

### ISSUE THREAD

**Issue by martinhannigan** [peeringdb/peeringdb#1204]
**Is your feature request related to a problem? Please describe.**
The search ability of PDB is limited considering the amount of data available. Making it more easily accessible is a goal of this issue. Increasing search utility has been the subject of multiple PC discussions and has been received favorably.

**Who is affected by the problem?**

PeeringDB users.

**What is the impact?**

Inefficient search and slower access to more useful information. One could argue "API" but its not always suitable and for both parties costs CPU cycles.  

**Are there security concerns?**

Not that I'm aware of.

**Are there privacy concerns?**

Not that I'm aware of.

**Describe the solution you'd like**

A free form search feature. Some potential uses case examples:

- Searching for $data within a city including a radius option
- Use of and/or with appropriate boolean operator application
- General free form functionality found in many search engines

For example:

"MassIX" or "Mass-IX" +Boston OR +Springfield OR Worcester -Marlboro +208v

**Do you think this feature will require a formal design?**

Yes. It should also require some level of cost analysis that scales with limited or wide use

**Describe alternatives you've considered**

Doing nothing, which doesn't seem very useful considering we have requests for search functionality in various past issues.

**Could this feature request need support from the Admin Committee?**

Doubtful. Search engine use with boolean operators is common. Should require little to no support if implemented similarly.

**What is the proposed priority?**

Suspect this is urgent since its a major improvement, but perhaps suitable for PDB v3. 

**Provide a rationale for any/all of the above**

Improved search functionality, effective use of resources and a better PDB user and UI experience.

**Additional context**

Worth exploring with developer hours being used to flush out specifics.

**Comment by arnoldnipper** [comment]
+1

**Comment by martinhannigan** [comment]
@peeringdb/pc chime in please and thank you!

**Comment by grizz** [comment]
+1

Let's scope this initially as a major (10 hours) of exploration to modernize the search as much as we can.

**Comment by peterhelmenstine** [comment]
There was a previous discussion to include a commercial version of Google's search which would essentially do what is asked of here rather than re-invent the wheel. I think someone was going to look into the cost and that was the last I remember where that went.

**Comment by grizz** [comment]
Hrm, I don't recall that, I don't think it would work with the radius search, but I could be wrong. Can we find out what happened with that?

It already uses http://haystacksearch.org/ so there's not a lot of wheel inventing, but certainly whichever is the easiest path is the way to go.

**Comment by martinhannigan** [comment]
Then there's UI implementation and tie into other search features being
requested which while I provided examples is not exhaustive by any means.

**Comment by mcmanuss8** [comment]
+1 better search please

**Comment by leovegoda** [comment]
When we implement this it would be helpful to incorporate support for `carrier` (deployed in 2.43.0) and `campus` (scheduled for early 2023) in the Advanced Search. Making it easy to know which facilities have a choice of carriers would be helpful, as would knowing which facilities can provide cross-connects to other facilities.
