### ISSUE TITLE
Ops: Limit Django sessions to pages that need it

### ISSUE THREAD

**Issue by ccaputo** [peeringdb/peeringdb#1205]
Django sessions need to be limited to the following:

- authenticated sessions
- login & registration forms

**Comment by mcmanuss8** [comment]
+1

-Steve

**Comment by peterhelmenstine** [comment]
+1 per internal discussion

**Comment by grizz** [comment]
+1

**Comment by prithvimanikonda** [comment]
@ccaputo Can you elaborate on what this is about?

**Comment by prithvimanikonda** [comment]
+1
