### ISSUE TITLE
HTTP Basic Authentication not working without "www" prefix in URL

### ISSUE THREAD

**Issue by ryeleo** [peeringdb/peeringdb#1206]
**Describe the bug**
When attempting to develop using PeeringDB APIs, rate limiting seems to keep me from making more than one request every few **hours**.

**To Reproduce**
1. Make a few GET requests for url: https://www.peeringdb.com:443/api/net?asn=15169&depth=2
2. Later in the day, make another GET request to the same URL

**Expected behavior**

If it has been more than a few minutes, I should be able to make the request.

**Who is affected by the problem?**

Developers.

**What is the impact?**

Development is blocked.

**Are there security concerns?**

Could cause Denial of Serif rate limiting were less limiting.

**What are the proposed actions?**

Modify rate limiting so that I can make a request every couple/few minutes.

**Comment by ryeleo** [comment]
Aha, you've pointed out that I forgot to clarify the actual rate-limit behavior I observed during development: I am receiving an HTTP 429 response indicating that I am being throttled when I use my peeringdb account.
```
requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url: https://www.peeringdb.com:443/api/net?asn=15169&depth=2
```

Interestingly, testing it today in my browser, I see a more informative message when I am unauthenticated: 
```
{"message": "Request was throttled. Expected available in 59 minutes. Authenticate for less restrictions. For more information: https://docs.peeringdb.com/howto/api_keys/", "meta": {"error": "Too Many Requests"}}
```

**Comment by martinhannigan** [comment]
Thanks! I can not recreate this. After looking at the network path, I suspect my throttling yesterday was related to a middle network who shall remain nameless. I've made tens of successful requests this evening of the same GET and no impact.

**Comment by ryeleo** [comment]
That is very interesting to me that you are seeing no issues. 🤔 I wonder if you are on some special subnet that is unthrottled...?

Some of my teammates are getting the same 429 responses as they do initial testing of the peeringdb integration that I'm developing. 😢

**Comment by ryeleo** [comment]
Some of my teammates noticed that they do not hit this rate limiting when they use an API Token instead of username password. 🤔 I'll test this out myself and report back!

**Comment by martinhannigan** [comment]
Thanks! As another data point, I was using username/pass!

**Comment by ryeleo** [comment]
Just tested my solution with an API Key (associated to user: rleonar7) -- surprisingly I saw the 429 on just my 2nd API request. In prior testing with username/password, I was making 2-3 requests before running into the 429 response -- this time I was only allowed a single request before hitting the HTTP 429 response!

```
2022-07-21 21:08:58 DEBUG     Using PeeringDB account: Api-Key [/home12/rleonar7/routeviews/routeviews-cli/src/routeviews/peeringdb/get.py:15]
... omitted for brevity...
  File "/home12/rleonar7/routeviews/routeviews-cli/src/routeviews/peeringdb/repository.py", line 75, in get_network_info
    response = self.get('/net', params=params)
  File "/home12/rleonar7/routeviews/routeviews-cli/src/routeviews/peeringdb/repository.py", line 56, in get
    response.raise_for_status()
  File "/home12/rleonar7/routeviews/routeviews-cli/venv/lib/python3.8/site-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url: https://www.peeringdb.com:443/api/net?asn=15169&depth=2
```

**Comment by ryeleo** [comment]
I noticed what I think is the issue! There is a colon instead of whitespace to separate username from password when using the `requests` Python package. As a result, the HTTP Authentication header is 'malformed' according to PeeringDB API it seems -- resulting in me effectively having anonymous access it seems. 

I noticed my colleague's test used whitespace and worked well. I am integrating this change now and will report back again :D

ℹ I'm thinking this issue might be best resolved by making it clear how the HTTP Authentication works, and linking to it from the [main PeeringDB API docs](https://www.peeringdb.com/apidocs/).

**Comment by martinhannigan** [comment]
Awesome!

**Comment by killafunkinmofo** [comment]
I was having a similar issue and found this, but with a different solution. I was using https://peeringdb.com. I was doing work with peeringdb support and we found that when I changed to https://www.peeringdb.com authentication was working. Maybe useful if others with similar issue find this post first like I did.

**Comment by leovegoda** [comment]
> Some notes that would be great to publish as part of the PeeringDB documentation:
> 
> 1. Do NOT base64 encode Authentication HTTP Header value.
> 2. Username/Password Must be space-separated (e.g., must not be colon ":" separated).
> 3. Username when using an API token should be "`Api-Key`".
> 4. Ensure "www" is in all API requests!

This is useful feedback. Thanks! I will work on adding a document that mentions all these things.

**Comment by ccaputo** [comment]
> api_key = 'BiBEKR8o.FVtZgE3qtluI1QU9DIR9eyBxiUyuiKnG'

@ryeleo I have revoked this key. Please consider API keys to be like your password and not post them.

**Comment by ccaputo** [comment]
> > I was having a similar issue and found this, but with a different solution. I was using https://peeringdb.com. I was doing work with peeringdb support and we found that when I changed to https://www.peeringdb.com authentication was working. Maybe useful if others with similar issue find this post first like I did.
> 
> @killafunkinmofo, thank you so much for mentioning this! I was still hitting the rate limiting until I just now added the "`www`" to my URL. This was the final piece to enable me to use PeeringDB API with python requests package!

I wonder if there is a bug in the python requests module that causes it to drop the request headers when following a redirect.

I wonder if #1139 should be revisited. I fear the amount of time wasted by devs on this when we could just not enforce canonical for /api/ requests.

**Comment by ccaputo** [comment]
@ryeleo any objection to this issue being closed, given the title change and apparent fault with the python requests module? The 301 redirects are handled by the AWS ALB, and the failure to send request headers after a redirect seems to be beyond something we can fix, short of revisiting #1139. (if someone wants to dig into the python request module aspect, and file a bug as appropriate with python for that, that would be grand)

**Comment by ryeleo** [comment]
> > api_key = 'BiBEKR8o.FVtZgE3qtluI1QU9DIR9eyBxiUyuiKnG'
> 
> @ryeleo I have revoked this key. Please consider API keys to be like your password and not post them.
> 

Hahaha, well I must have forgotten to revoke that one. I felt the example was most clear when I provided an old revoked key. Thank you for catching that! 🙏😅

**Comment by martinhannigan** [comment]
Awesome feedback. Thank you!
