### ISSUE TITLE
RIR Status update misses ASNs

### ISSUE THREAD

**Issue by vegu** [peeringdb/peeringdb#1216]
**Describe the bug**

#473 introduced rir status fields to networks, we're noticing some inconsistencies in that data that manifests as rir status being unset for ASNs that it should be set for.

Additionally the api value for `rir_status_updated` timestamp currently contains msecs when other api timestamps do not and should be brought in line.

**Comment by mcmanuss8** [comment]
+1 bug

**Comment by grizz** [comment]
+1, bug

**Comment by arnoldnipper** [comment]
IMO the algorithm doesn't work properly. Iff `rir_status_updated` is **not** updated when we don't find the ASN marked ok in one of the RIR DB. However

`
jq -r '.asn, .rir_status, .rir_status_updated' 1660522025-net-www-0.json | paste - - - | egrep -c 2022-07-27T05:29:57
24963
`

OTOH

`
jq -r '.asn, .rir_status, .rir_status_updated' 1660522025-net-www-0.json | paste - - - | egrep 2022-07-27T05:29:57 | egrep -c ok
22517
`

**Comment by arnoldnipper** [comment]
IMO we have false positives. I.e. we mark too many networks for deletion

`
jq -r '.asn, .rir_status, .rir_status_updated' 1660522025-net-www-0.json | paste - - - | egrep -c null
2556
`

I only count 295.

Example: AS 702
