### ISSUE TITLE
api/net/#NETID?depth=2 is not equal to matching api/net?asn__in=#ASN&depth=2

### ISSUE THREAD

**Issue by ccaputo** [peeringdb/peeringdb#1217]
[Feel free to improve the Issue title as appropriate.]

A user reported this apparent bug. A diff of the outputs of:

```curl https://www.peeringdb.com/api/net/416?depth=2 | jq```

with corresponding ASN:

```curl https://www.peeringdb.com/api/net?asn__in=6456\&depth=2 | jq```

results in:

```       "id": 416,
       "org_id": 550,
-      "org": {
-        "id": 550,
-        "name": "Altopia Corporation",
-        "aka": "",
-        "name_long": "",
-        "website": "https://www.altopia.com/",
-        "notes": "",
-        "net_set": [
-          416
-        ],
-        "fac_set": [],
-        "ix_set": [],
-        "address1": "1700 7th Ave Ste 116 PMB #300",
-        "address2": "",
-        "city": "Seattle",
-        "country": "US",
-        "state": "WA",
-        "zipcode": "98101-1323",
-        "floor": "",
-        "suite": "",
-        "latitude": null,
-        "longitude": null,
-        "created": "2005-02-01T10:16:50Z",
-        "updated": "2019-10-04T16:33:10Z",
-        "status": "ok"
-      },
       "name": "Altopia Corporation",
       "aka": "alt.net",
       "name_long": "",
```

The lack of the org object in the second query seems like a bug.

**Comment by grizz** [comment]
After discussion and looking into it, we believe it's a caching decision. We will report back after more digging.

**Comment by arnoldnipper** [comment]
Routed through to 3a as flagged "bug" by a developer

**Comment by grizz** [comment]
Let's re-evaluate along with #1219

**Comment by leovegoda** [comment]
> Let's re-evaluate along with #1219

@grizz Did #1219 resolve this?

**Comment by grizz** [comment]
This is just a caching decision, the first one is a network object, the second is a list of network objects. so the first one gets more information.

Right or wrong, at this point we'd have to wait until v3 to change it anyway, so closing and tagging for that.

#625 

Please re-open if you think this needs other attention.

**Comment by martinhannigan** [comment]
+1
