### ISSUE TITLE
PeeringDB Usage Data

### ISSUE THREAD

**Issue by leovegoda** [peeringdb/peeringdb#1218]
**Is your feature request related to a problem? Please describe.**
The PC does not have access to PeeringDB usage data. Without usage data, design choices are based on best guesses.

**Who is affected by the problem?**
Ultimately, this affects all users. Immediately, it impacts the ability of the PC to make design choices.

**What is the impact?**
Design decisions are based on personal experience and anecdotal evidence rather than data. As the PC is a small group they might not be aware of issues that are easily identified with actual data.

**Are there security concerns?**
There should not be

**Are there privacy concerns?**
We don't care about tracking PeeringDB users on other sites. We should only be collecting aggregate data on use of PeeringDB services.

If we use an external service, we might need to update our [Privacy Policy](https://docs.peeringdb.com/gov/misc/2017-04-02-PeeringDB_Privacy_Policy.pdf).

**Describe the solution you'd like**
We should regularly collect data to identify trends. This should include:

1. In which countries are our users based. This will let us know if we have countries with significant Internet usage but low PeeringDB usage.
2. Do our users use the website or API?
3. What proportion of usage is by authenticated users?
4. What kinds of devices do web users use?
5. What screen sizes do web users use?

A web page that automatically shows trends and charts would be helpful.

The ability to export data in structured formats, like CSV, to compare with external data sources, like ASN assignments from the [RIRs’ daily stats files](https://ftp.arin.net/pub/stats/) would be helpful.

No preference for the technology to use. It could be a tool like [Google Analytics](https://analytics.google.com/analytics/web/provision/#/provision) or [Matamo](https://matomo.org/) if that is the simplest approach.

**Do you think this feature will require a formal design?**
Yes

**Describe alternatives you've considered**
Periodic manual collection of statistics. This is time consuming and makes trend analysis more difficult.

**Could this feature request need support from the Admin Committee?**
It should not

**What is the proposed priority?**
Would be good to have this in place by mid-2023

**Provide a rationale for any/all of the above**
Informed decision making

**Comment by mcmanuss8** [comment]
+1

**Comment by grizz** [comment]
+1

**Comment by martinhannigan** [comment]
Yes +1

**Comment by leovegoda** [comment]
I'm closing this as the work will be done in #1308
