### ISSUE TITLE
Optimize Cacheing

### ISSUE THREAD

**Issue by leovegoda** [peeringdb/peeringdb#1219]
**Is your feature request related to a problem? Please describe.**
PeeringDB's dataset is relatively small but repeated inefficient queries for records is expensive. We should aim to make it even easier for users to have a local copy of PeeringDB. This should be more cost effective for PeeringDB and improve user experience.

**Who is affected by the problem?**
Any PeeringDB user affected by query limits, and PeeringDB as an organization

**What is the impact?**
Improve user experience and manage costs effectively

**Are there security concerns?**
No

**Are there privacy concerns?**
No

**Describe the solution you'd like**
- Make it easier for users to obtain and make use of PeeringDB's data on their own equipment.
- Make it easier for third parties to cache and distribute PeeringDB data

Also see: https://github.com/peeringdb/peeringdb-py/issues/65

**Do you think this feature will require a formal design?**
Yes

**Describe alternatives you've considered**
The @peeringdb/oc has worked with software developers and large users to help them cache PeeringDB locally. This was enabled by improvements to logging and the query limits, which encouraged some users to contact PeeringDB. Working with users and third-party software developers should continue.

**Could this feature request need support from the Admin Committee?**
This should reduce demands on the AC by reducing support queries about refused connections

**What is the proposed priority?**
Urgent

**Provide a rationale for any/all of the above**
Improve user experience and manage costs effectively

**Comment by grizz** [comment]
+1

**Comment by martinhannigan** [comment]
+1 plus static and other stuff we can cache

**Comment by leovegoda** [comment]
Also see: https://github.com/peeringdb/peeringdb/issues/1065
