### ISSUE TITLE
IXPs removing left members from exchange

### ISSUE THREAD

**Issue by kieber** [peeringdb/peeringdb#122]
IXPs need a way to disassociate from members who have left, especially when reusing that members IP.  Having to write mail to support@ before the new member can enter their IP doesn't appear to be a sustainable solution to me.

**Comment by arnoldnipper** [comment]
Related to resp covered by #116 imho

**Comment by arnoldnipper** [comment]
We will implement cross-check with IX-F JSON list (http://ml.ix-f.net/directory) soon. So make sure you provide a JSON list

**Comment by vegu** [comment]
fixed in cf295a0
