### ISSUE TITLE
Set Secure Headers in PeeringDB Web Application

### ISSUE THREAD

**Issue by prithvimanikonda** [peeringdb/peeringdb#1221]
**Is your feature request related to a problem? Please describe.**
PeeringDB should enable as many security HTTP headers as possible. Many security headers either eliminate entire classes of web application vulnerabilities and/or greatly reduce the impact that a particular vulnerability may have on your service. The following instances of this finding were identified:

Endpoint: https://www.peeringdb.com/
Strict-Transport-Security (Missing header).
Content-Security-Policy (Missing header).
X-Content-Type-Options (Missing header).
X-XSS-Protection (Missing header).

**Who is affected by the problem?**
The usability of PeeringDB is not impacted but there is a potential class of web application vulnerabilities

**What is the impact?**
***Strict-Transport-Security***

Strict-Transport-Security is a feature to enforce that the browser uses HTTPS only and never makes HTTP requests to this domain. 

***Content-Security-Policy***
This allows web developers to control the resources which a particular page can fetch or execute.
https://django-csp.readthedocs.io/en/latest/configuration.html

***X-Content-Type-Options***
Prevents browsers from incorrectly identifying content types when no Content-Type header is supplied by the server. 

***X-XSS-Protection***
Sets the configuration for the cross-site scripting filter built into most browsers.

**Are there security concerns?**
Yes

**Are there privacy concerns?**
No

**Describe the solution you'd like**
Django offers middleware to set these headers on all the responses from the web application with configurable knobs. I propose to use well supported middlewares to close the security gaps identified.

**Do you think this feature will require a formal design?**
No, these headers are pretty standard practice for any HTTPS web application.

**Describe alternatives you've considered**
N/A

**Could this feature request need support from the Admin Committee?**
Need support in merging the code and deploying it to beta and prod env.

**What is the proposed priority?**
moderate

**Comment by prithvimanikonda** [comment]
Here is the proposed solution for this issue: https://github.com/prithvimanikonda/peeringdb/pull/3 on my local fork,

**Comment by mcmanuss8** [comment]
+1

**Comment by grizz** [comment]
+1

**Comment by martinhannigan** [comment]
+1
