### ISSUE TITLE
Invalid data (in choice fields) found via API

### ISSUE THREAD

**Issue by gmazoyer** [peeringdb/peeringdb#1223]
**Describe the bug**
Some objects have fields in which content is chosen from a valid list of choices. However some records contain choices that are not in the actual list.

Lists of available choices can be found in [this file](https://github.com/peeringdb/django-peeringdb/blob/main/src/django_peeringdb/const.py).

**To Reproduce**

Perform the below request and we get `"region_continent": "MIddle East"` which is not a valid choice.

```
curl 'https://www.peeringdb.com/api/fac?id=838' | jq
{
  "data": [
    {
      "id": 838,
      "org_id": 2649,
      "org_name": "CityNet Telecom",
      "name": "CityNet Host",
      "aka": "",
      "name_long": "",
      "website": "http://www.citynethost.com",
      "clli": "",
      "rencode": "",
      "npanxx": "",
      "notes": "",
      "net_count": 1,
      "ix_count": 0,
      "sales_email": "",
      "sales_phone": "",
      "tech_email": "",
      "tech_phone": "",
      "available_voltage_services": [],
      "diverse_serving_substations": null,
      "property": null,
      "region_continent": "MIddle East",
      "status_dashboard": null,
      "created": "2010-08-15T00:00:00Z",
      "updated": "2017-09-06T04:34:31Z",
      "status": "ok",
      "address1": "Ahlam Buildings",
      "address2": "Suite 21",
      "city": "Tenth of Ramadan",
      "country": "EG",
      "state": "",
      "zipcode": "44653",
      "floor": "",
      "suite": "",
      "latitude": 30.091435,
      "longitude": 31.25435
    }
  ],
  "meta": {}
}
```

**Expected behavior**

Get the data without invalid choices.

**Who is affected by the problem?**

Everyone

**What is the impact?**

Tools that synchronise content locally can fail if they perform input checks.

**Are there security concerns?**

I don't believe so.

**Are there privacy concerns?**

I don't believe so.

**What are the proposed actions?**

Fix invalid data by updating affected records.

**What is the proposed priority?**

Not urgent

**Provide a rationale for any/all of the above**

**Additional context**

List of affected records:

```
error validating id: 838 for model: facility
{'region_continent': ["Value 'MIddle East' is not a valid choice."]}
error validating id: 1042 for model: facility
{'region_continent': ["Value 'America' is not a valid choice."]}
error validating id: 1509 for model: facility
{'region_continent': ["Value 'MIddle East' is not a valid choice."]}
error validating id: 1768 for model: facility
{'region_continent': ["Value 'MIddle East' is not a valid choice."]}
error validating id: 2146 for model: facility
{'region_continent': ["Value 'America' is not a valid choice."]}
error validating id: 2152 for model: facility
{'region_continent': ["Value 'America' is not a valid choice."]}
error validating id: 3873 for model: facility
{'region_continent': ["Value 'MIddle East' is not a valid choice."]}
error validating id: 5702 for model: facility
{'region_continent': ["Value 'America' is not a valid choice."]}
error validating id: 6107 for model: facility
{'region_continent': ["Value 'America' is not a valid choice."]}
error validating id: 7158 for model: facility
{'region_continent': ["Value 'America' is not a valid choice."]}
error validating id: 7291 for model: facility
{'region_continent': ["Value 'America' is not a valid choice."]}
error validating id: 7641 for model: facility
{'region_continent': ["Value 'America' is not a valid choice."]}
error validating id: 8871 for model: facility
{'region_continent': ["Value 'MIddle East' is not a valid choice."]}
error validating id: 9616 for model: facility
{'region_continent': ["Value 'MIddle East' is not a valid choice."]}
error validating id: 11254 for model: facility
{'region_continent': ["Value 'America' is not a valid choice."]}
error validating id: 12512 for model: facility
{'region_continent': ["Value 'America' is not a valid choice."]}
```

**Comment by arnoldnipper** [comment]
I've tried to fix this. However,

- modifying via the API again returns "MIddle East"
- on the GUI level this field is not editable
- on the [AC](@peeringdb/ac) GUI level when modifying the value jumps back to "-------"

**Comment by gmazoyer** [comment]
> Additionally, we find this bug in `838 MIddle East 1509 MIddle East 1768 MIddle East 3873 MIddle East 8871 MIddle East 9616 MIddle East`

You're right, I listed all the incoherences I found in the additional context of this issue's first message.

**Comment by vegu** [comment]
These come from address normalization and errors in the country-code -> continent mappings in django-peeringdb https://github.com/peeringdb/django-peeringdb/blob/main/src/django_peeringdb/const.py#L941 and https://github.com/peeringdb/django-peeringdb/blob/main/src/django_peeringdb/const.py#L341 - which will need to be fixed and deployed before the data can be cleaned up.

**Comment by martinhannigan** [comment]
+1 what matt said

**Comment by arnoldnipper** [comment]
It's still not fixed ...

`
curl -s https://www.peeringdb.com/api/fac/838 | jq -r '.data[].region_continent'
MIddle East
`

**Comment by arnoldnipper** [comment]
Fixed ...

`
curl -s https://www.peeringdb.com/api/fac/838 | jq -r '.data[].region_continent'
Middle East
`

**Comment by leovegoda** [comment]
@arnoldnipper and @gmazoyer Can we close this now?
