### ISSUE TITLE
Evaluate ways to reduce operational costs

### ISSUE THREAD

**Issue by leovegoda** [peeringdb/peeringdb#1225]
**Is your feature request related to a problem? Please describe.**
PeeringDB hosting costs have been on an upward trend over the last year. We should investigate ways to reduce operational costs without sacrificing service quality.

**Who is affected by the problem?**
Higher costs could require additional sponsorship or reduce service quality if not addressed by lowering operational costs.

**What is the impact?**
Improved financial efficiency

**Are there security concerns?**
No

**Are there privacy concerns?**
No

**Describe the solution you'd like**
An analysis that can be evaluated by PeeringDB Stewards

**Do you think this feature will require a formal design?**
Yes

**Describe alternatives you've considered**
More sponsorship

**Could this feature request need support from the Admin Committee?**
No

**What is the proposed priority?**
High

**Provide a rationale for any/all of the above**
We ought to sustain or improve value to sponsors while retaining or improving service levels

**Comment by arnoldnipper** [comment]
+1 

IMO that must a joint task of [OPS](@peeringdb/oc) and the [developers](@peeringdb/20c)

**Comment by grizz** [comment]
Agreed, +1

**Comment by martinhannigan** [comment]
Is the auth scope too wide?

**Comment by mcmanuss8** [comment]
+1

**Comment by leovegoda** [comment]
In implementing this issue, we'll look at deploying directly onto the cloud infrastructure, instead of deploying to a VM that runs on that infrastructure. It is hoped that this will help with efficient service scaling.
