### ISSUE TITLE
Add a "Delete Affiliation" button/option to the profile

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/peeringdb#1226]
**Is your feature request related to a problem? Please describe.**

A user should be able to remove an affiliation. Currently, they only can close their account. If they want to remove an affiliation they have either to contact their admin or [AC](@peeringdb/ac)

**Comment by martinhannigan** [comment]
+1

**Comment by DarwinCosta** [comment]
+1

**Comment by peterhelmenstine** [comment]
+1 agree on the new feature

**Comment by netravnen** [comment]
+1

**Comment by arnoldnipper** [comment]
**Summary**

- Add a "Remove" button next to the user's affiliations on their [profile](https://www.peeringdb.com/profile)
- Let the user confirm the removal (I guess we have a standard text)
- In case the user is the last affiliated with the `org`, let the user confirm again. This time with the hint that the removal will leave the `org` abandoned

**Comment by leovegoda** [comment]
@tbotnz has agreed to develop this

**Comment by elgaeloHub** [comment]
This is definitely a useful feature

**Comment by vegu** [comment]
closed through https://github.com/peeringdb/peeringdb/pull/1440
