### ISSUE TITLE
Change ix-f to IX-F

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/peeringdb#1231]
**Describe the bug**

For consistency, it should read IX-F, not ix-f

**Comment by leovegoda** [comment]
@arnoldnipper Where is this?

**Comment by arnoldnipper** [comment]
> @arnoldnipper Where is this?

I don't remember. OTOH, it should be easy to find

**Comment by grizz** [comment]
In a few template files.

**Comment by vegu** [comment]
merged in #1588
