### ISSUE TITLE
Transition from lgtm.com before the service ends

### ISSUE THREAD

**Issue by leovegoda** [peeringdb/peeringdb#1234]
**Is your feature request related to a problem? Please describe.**
We use lgtm.com for continuous security analysis. lgtm.com will close at the end of 2022. We need to transition to GitHub code scanning or an alternative equivalent service before the lgtm.com service ends. See blog post at:

https://github.blog/2022-08-15-the-next-step-for-lgtm-com-github-code-scanning/

**Who is affected by the problem?**
As above

**What is the impact?**
As above

**Are there security concerns?**
Only if we do not transition to a new equivalent service in time 

**Are there privacy concerns?**
No

**Describe the solution you'd like**
Evaluate GitHub code scanning as an alternative. Transition to it if it is suitable.Otherwise, look for equivalent services.

**Do you think this feature will require a formal design?**
Not sure

**Describe alternatives you've considered**
None

**Could this feature request need support from the Admin Committee?**
No

**What is the proposed priority?**
Complete before the end of 2022

**Provide a rationale for any/all of the above**
As above

**Additional context**
None

**Comment by mcmanuss8** [comment]
+1

**Comment by martinhannigan** [comment]
+1 because steve and matt did and they know.
