### ISSUE TITLE
Add data about whether a facility operator owns the building or has an agreement with the owner

### ISSUE THREAD

**Issue by leovegoda** [peeringdb/peeringdb#1235]
**Is your feature request related to a problem? Please describe.**
This is a new issue to take the `landlord` part of the discussion from https://github.com/peeringdb/peeringdb/issues/1110

This issue is intended to discuss whether and how to show that a facility operator either owns the building or has an agreement with the owner of the building.

**Who is affected by the problem?**
One use case described was that a network operators might prefer to make an agreement directly with the building operator rather than purchase from an existing facility operator in the building.

**What is the impact?**
More information is available to market participants

**Are there security concerns?**
Probably not

**Are there privacy concerns?**
No

**Describe the solution you'd like**
An attribute in the facility object that allows the facility operator to declare whether they own the building or not. In the @peeringdb/pc meeting people noted that legal terms like lessee and lessor can be confusing, so a simple language word would be an advantage.

**Do you think this feature will require a formal design?**
Not sure

**Describe alternatives you've considered**
None

**Could this feature request need support from the Admin Committee?**
Probably

**What is the proposed priority?**
Not sure

**Provide a rationale for any/all of the above**
This gives networks more information and so greater choice

**Additional context**
None

**Comment by martinhannigan** [comment]
-1 we already have a field for owner or lessee. Not certain what the objective of this is. Clarification needed.

**Comment by martinhannigan** [comment]
If you are trying to sinolify lessee I agree. I would suggest owner or renter. Or owner and nothing which implies strongly you're an"renter". 

Hope that helps.
