### ISSUE TITLE
Put an Icon next to user name on https://www.peeringdb.com/org/nnnn#users if the user is using U2F

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/peeringdb#1238]
**Is your feature request related to a problem? Please describe.**
When introducing 2FA we put an icon next to the username. We should do the same when a user uses U2F. This helps the admins of an `org` as well as [AC](@peeringdb/ac)

**Comment by grizz** [comment]
+1

**Comment by mcmanuss8** [comment]
+1

**Comment by martinhannigan** [comment]
+1

**Comment by vegu** [comment]
**summary**

- add a U2F badge next to user name in organization user listing if the user has set up U2F 2FA
