### ISSUE TITLE
Add a search field to all AC views

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/peeringdb#1239]
**Is your feature request related to a problem? Please describe.**
Not all [AC](@peeringdb/ac) pages have search fields, e.g

- [Webauthn](https://www.peeringdb.com/cp/django_security_keys/securitykey/)
- [Grants](https://www.peeringdb.com/cp/oauth2_provider/grant/)
- [Email devices](https://www.peeringdb.com/cp/otp_email/emaildevice/)
- [Static devices](https://www.peeringdb.com/cp/otp_static/staticdevice/)
- ...

**Who is affected by the problem?**
[AC](@peeringdb/ac) who has to lookup items

**Comment by mcmanuss8** [comment]
+1

**Comment by martinhannigan** [comment]
+1

**Comment by grizz** [comment]
3a pending complete list

**Comment by arnoldnipper** [comment]
Here is the **complete** list for now. And whenever a tab is added, search **must** be added

- https://www.peeringdb.com/cp/oauth2_provider/grant/
- https://www.peeringdb.com/cp/django_security_keys/securitykey/
- https://www.peeringdb.com/cp/otp_email/emaildevice/
- https://www.peeringdb.com/cp/otp_static/staticdevice/
- https://www.peeringdb.com/cp/otp_totp/totpdevice/
- https://www.peeringdb.com/cp/peeringdb_server/commandlinetool/
- https://www.peeringdb.com/cp/peeringdb_server/datachangeemail/
- https://www.peeringdb.com/cp/peeringdb_server/datachangenotificationqueue/
- https://www.peeringdb.com/cp/peeringdb_server/datachangewatchedobject/
- https://www.peeringdb.com/cp/peeringdb_server/geocoordinatecache/
- https://www.peeringdb.com/cp/peeringdb_server/oauthapplication/
- https://www.peeringdb.com/cp/peeringdb_server/partnership/
- https://www.peeringdb.com/cp/peeringdb_server/sponsorship/
- https://www.peeringdb.com/cp/socialaccount/socialtoken/
- https://www.peeringdb.com/cp/socialaccount/socialapp/

**Comment by martinhannigan** [comment]
Im good and already +1.  I’m only -1 on “must”. We need flexibility where we need if.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by arnoldnipper** [comment]
Search field is a **must** .

**Comment by martinhannigan** [comment]
-1 with must for me.

**Comment by arnoldnipper** [comment]
> -1 with must for me.

Did you already forget that you mentioned that ... it's an AC only issue ... time to introduce an AC dev queue again

**Comment by martinhannigan** [comment]
Its also a cost issue on many fronts. If we can simply drop must its probably the same exact thing youre asking for in the issue.  We should try to be flexible in all we do so when something is bad we can address it easily and without “must”. That will come back to bite us.



Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by martinhannigan** [comment]
I'm interpreting this issue as you want a free form search option on every
page. That feels wasteful. Implementation wise, perhaps a search ability
for a specific field would limit the potential for random and useless
searches (cost) and instead use a regex in the field itself. Not
necessarily my area of expertise, but something similar to when you might
choose a country on a webform and as you start typing matches begin to
appear. If something like this is what you're actually asking for or could
work it may be a good compromise.

Question for 20c: does this change the search and prevent burnt CPU cycles
or does it not impact it differently at all? I recall that we could cache
one where the other could not be.

HTH

Thanks,

-M<
