### ISSUE TITLE
Don't allow the first and last addresses being assigned

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/peeringdb#1241]
**Describe the bug**
Currently, it's possible to e.g. assign .0 and .255 on a /24.  This **must** be forbidden

**Comment by martinhannigan** [comment]
I don't disagree. But I also see this as a corner case and a low priority

+1

**Comment by mcmanuss8** [comment]
+1

**Comment by netravnen** [comment]
+1

**Comment by grizz** [comment]
**Summary**

Add validation check to fail on network and broadcast addresses.
