### ISSUE TITLE
Help text covers non-compliant email addresses

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/peeringdb#1257]
**Describe the bug**

According to #737, for non-compliant emails, the tool "... should highlight these users in the user listing, probably through special color highlight for the email address and a help text on mouse over."

However, the help text covers the email address. Admins are not able to contact the users.

**Comment by grizz** [comment]
@arnoldnipper could we get a screenshot? I'm not sure what you mean exactly.

Thanks

**Comment by arnoldnipper** [comment]
> @arnoldnipper could we get a screenshot? I'm not sure what you mean exactly.
> 

![20221012_PeeringDB_01](https://user-images.githubusercontent.com/16888757/195389733-753df9f0-476f-4503-a3a7-aa0f2bea6dd1.png)
