### ISSUE TITLE
Add Selenium Grid to CI testing

### ISSUE THREAD

**Issue by grizz** [peeringdb/peeringdb#1260]
**Is your feature request related to a problem? Please describe.**

The current browser testing uses chrome only, ideally, the CI testing would fire up a Selenium Grid with major browsers and test as part of the Pull Request testing.

**Comment by arnoldnipper** [comment]
+1

**Comment by mcmanuss8** [comment]
+1

**Comment by leovegoda** [comment]
@grizz Would this be a minor, if we get consensus?

**Comment by martinhannigan** [comment]
How did this one slip past the cracks of the PDB PC meeting?

+1

**Comment by grizz** [comment]
+1

> @grizz Would this be a minor, if we get consensus?

Probably, it might end up closer to a Major.

**Comment by leovegoda** [comment]
Discussed this with @grizz and we will schedule this for 2.51.0 at the start of the work to update the webUI. It is possible that we'll select [playwright](https://github.com/microsoft/playwright) instead of Selenium.

**Comment by leovegoda** [comment]
This is being worked on but will follow deployment of 2.51.0
