### ISSUE TITLE
mysql8 tests

### ISSUE THREAD

**Issue by ccaputo** [peeringdb/peeringdb#1261]
@grizz asked me to post this to track any mysql8 testing & needed changes. mysql8 is currently running on beta.

**Comment by grizz** [comment]
To clarify, it's a semi forced change to AWS Aurora RDS after the EOLing of what we are currently running.

Ops will be looking for a time after 2.41 release to test and migrate the database.

**Comment by arnoldnipper** [comment]
My understanding is that no code change is needed

**Comment by mcmanuss8** [comment]
+1
