### ISSUE TITLE
[beta] OAuth not functional

### ISSUE THREAD

**Issue by vegu** [peeringdb/peeringdb#1263]
**Describe the bug**

Using beta.peeringdb.com as an OAuth provider seems to no longer be working as of `2.41.0-beta`.

It never prompts for the authorization and goes straight to the landing page (or /login first if the user is not logged in)

**Comment by prithvimanikonda** [comment]
Pull request for the fix: https://github.com/peeringdb/peeringdb/pull/1264

**Comment by vegu** [comment]
was fixed in 2.41.0-beta1
