### ISSUE TITLE
Post interaction feedback

### ISSUE THREAD

**Issue by leovegoda** [peeringdb/peeringdb#1268]
**Is your feature request related to a problem? Please describe.**
The annual user survey has given PeeringDB information on the aspects of the service that are most valuable to users and the areas where improvement is most important. But this survey reaches a small proportion of PeeringDB’s 43,000 users. It also requires the users who respond to remember their experiences and commit some time to responding. We should make it easier to indicate a positive or negative experience and provide feedback.

Each interaction, such as a search or update, should include an option to deliver feedback. The visual design should ensure that the feedback element is not intrusive - it might be something to place in the CSS footer. It should give the user the opportunity to let us know if their experience was positive or negative, and provide an optional comment. It would be nice if we could also allow users to send a screenshot if they want, noting that they should not share any confidential information.

Because this approach would be limited to user sentiment on specifics, we should probably still run an annual scoring exercise where we ask users what is most important to them.

This might be a feature that cannot usefully be implemented in the API.

**Who is affected by the problem?**
Ultimately, all PeeringDB users. Immediately, this would help the @peeringdb/pc and other committees.

**What is the impact?**
A clearer indication of which improvements the users would like us to focus resources.

**Are there security concerns?**
No, as long as we advise users on what data we collect and what they should not share. e.g. credentials.

**Are there privacy concerns?**
There could be if there was a link to login information, or the specific of the search or action taken. It would be good to know if the feedback comes from authenticated users and the kind of action immediately before it but specifics, like usernames or search parameters, should not be recorded.

**Describe the solution you’d like**
As above

**Do you think this feature will require a formal design?**
Yes

**Describe alternatives you’ve considered**
This is an alternative to the current process

**Could this feature request need support from the Admin Committee?**
It should not

**What is the proposed priority?**
Implement before September 2023

**Provide a rationale for any/all of the above**
More data points would give a more accurate view of user sentiment

**Additional context**
None

**Comment by martinhannigan** [comment]
On Thu, Oct 13, 2022 at 5:04 PM Leo Vegoda ***@***.***> wrote:

> *Is your feature request related to a problem? Please describe.*
> The annual user survey has given PeeringDB information on the aspects of
> the service that are most valuable to users and the areas where improvement
> is most important. But this survey reaches a small proportion of
> PeeringDB’s 43,000 users. It also requires the users who respond to
> remember their experiences and commit some time to responding. We should
> make it easier to indicate a positive or negative experience and provide
> feedback.
>
> Each interaction, such as a search or update, should include an option to
> deliver feedback. The visual design should ensure that the feedback element
> is not intrusive - it might be something to place in the CSS footer. It
> should give the user the opportunity to let us know if their experience was
> positive or negative, and provide an optional comment. It would be nice if
> we could also allow users to send a screenshot if they want, noting that
> they should not share any confidential information.
>

More information on a pseudo design would be welcome. However, intrusive is
likely to receive a backlash. On the one hand, feedback is good. It helps
us to be better. On the other hand, distracting users and using vital
screen real estate for potentially ineffective purposes should be a real
concern. We need to treat each pixel as platinum and for request demanding
UI real estate hold it to a very high standard. Im not certain this meets
that.

*Provide a rationale for any/all of the above*
> More data points would give a more accurate view of user sentiment
>
> Agree.

Will defer a vote for more information.


Warm regards,

Martin



>

**Comment by leovegoda** [comment]
Closing as we'll address this in the website update

**Comment by peterhelmenstine** [comment]
Was going to say do it like Wiki does it. Annual 'hey this is a free service if you like it please provide feedback' on the website.
