### ISSUE TITLE
Filter doesn't seem to work for IP addresses

### ISSUE THREAD

**Issue by martzuk** [peeringdb/peeringdb#127]
For example, on https://www.peeringdb.com/net/4224 there is the IP 43.243.21.2 listed for AKL-IX, but the filter does not work on it. Screenshots attached
![screenshot 2017-02-14 17 28 56](https://cloud.githubusercontent.com/assets/1249518/22940834/21c55e0e-f2db-11e6-98de-68a2adf0d9ac.png)
![screenshot 2017-02-14 17 29 05](https://cloud.githubusercontent.com/assets/1249518/22940833/21bc56b0-f2db-11e6-8915-6614e1294770.png)

**Comment by vegu** [comment]
fixed in a9dcf4f

**Comment by martzuk** [comment]
Tested this on the beta version 2.1.0, I noticed it works ok on /net/ but not on /ix/

**Comment by vegu** [comment]
Thanks for the report, similar issue, different UI elements, so i split it into its own ticket at #146, hope to resolve soon
