### ISSUE TITLE
Enable Google Analytics for beta.peeringdb.com

### ISSUE THREAD

**Issue by leovegoda** [peeringdb/peeringdb#1270]
**Is your feature request related to a problem? Please describe.**
To advance #1218 the @peeringdb/pc [agreed to test](https://docs.peeringdb.com/committee/product/notes/2022-10-17_Product_Committee_Notes.pdf) Google Analytics on beta.peeringdb.com. This issue is for that deployment.

**Who is affected by the problem?**
See #1218 

**What is the impact?**
See #1218 

**Are there security concerns?**
See #1218 

**Are there privacy concerns?**
See #1218 

**Describe the solution you'd like**
This is a test deployment on beta.peeringdb.com

**Do you think this feature will require a formal design?**
No. We will be using an out of the box product

**Describe alternatives you've considered**
See PC meeting notes for previous discussion

**Could this feature request need support from the Admin Committee?**
Unlikely

**What is the proposed priority?**
Next deploy

**Provide a rationale for any/all of the above**
See above

**Additional context**

**Comment by arnoldnipper** [comment]
Q: are there any costs involved. If, how much?

**Comment by mcmanuss8** [comment]
+1

**Comment by grizz** [comment]
+1
