### ISSUE TITLE
Implement auto-removal of stale networks according to DOTF recommendations

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/peeringdb#1271]
**Is your feature request related to a problem? Please describe.**
Currently, networks and IXP only are notified about `netixlan` mismatches resulting from IX-F JSON imports. However, if the networks went south or doesn't respond for other reasons, the stale information is not removed.

**Who is affected by the problem?**

- IXP who want to keep their assignments clean
- networks who get re-assigned IPs
- @peeringdb/ac having additional work

**Describe the solution you'd like**

After having notified the network  x times, wait another y days and then remove the `netixlan` entry.

**Do you think this feature will require a formal design?**
yes, @peeringdb/ac already has drafted a version

**Could this feature request need support from the Admin Committee?**
It's an AC issue

**What is the proposed priority?**
long overdue

**Comment by martinhannigan** [comment]
On Fri, Oct 21, 2022 at 8:00 AM Arnold Nipper ***@***.***>
wrote:

> *Is your feature request related to a problem? Please describe.*
> Currently, networks and IXP only are notified about netixlan mismatches
> resulting from IX-F JSON imports. However, if the networks went south or
> doesn't respond for other reasons, the stale information is not removed.
>
*Who is affected by the problem?*
>
>    - IXP who want to keep their assignments clean
>    - networks who get re-assigned IPs
>    - @peeringdb/ac <https://github.com/orgs/peeringdb/teams/ac> having
>    additional work
>
> *Describe the solution you'd like*
>
> After having notified the network x times, wait another y days and then
> remove the netixlan entry.
>
> *Do you think this feature will require a formal design?*
> yes, @peeringdb/ac <https://github.com/orgs/peeringdb/teams/ac> already
> has drafted a version
>

Where can we all see that? I looked on the drive, but couldn’t find
anything that resembled the issue.

*Could this feature request need support from the Admin Committee?*
> It's an AC issue
>

Its a product(quality) issue related to quality which the benefit to the AC
is that thee’s no more scruff to deal with related to state/mismatches.


*What is the proposed priority?*
> long overdue
>

Falls into the data quality bucket so getting it on the list sooner than
later is probably reasonable.

+1

**Comment by DarwinCosta** [comment]
Makes sense. +1.

**Comment by mcmanuss8** [comment]
+1

**Comment by grizz** [comment]
+1

**Comment by peterhelmenstine** [comment]
+1

**Comment by DarwinCosta** [comment]
+1.

**Comment by vegu** [comment]
> > **Describe the solution you'd like**
> > After having notified the network x times, wait another y days and then remove the `netixlan` entry.
> > **Do you think this feature will require a formal design?** yes, @peeringdb/ac already has drafted a version
> 
> I notice the implementation defaults to this just happening after 90 days, but I don't see any code regarding the required number of notifications to the network. Was that dropped as part of the solution?

Was missed - will add as part of #1355
