### ISSUE TITLE
Add a button for IXes to flag a netixlan entry as bad

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/peeringdb#1272]
**Is your feature request related to a problem? Please describe.**
Currently, only ~19%  of all IXes provide IX-F JSON data. Especially, the older and smaller ones not running IXP Manager may lack resources to implement IX-F JSON.

However, they are also eager to keep the `netixlan` entries clean. ATM, they have to email [AC](@peeringdb/ac) for help.

**Who is affected by the problem?**
81% of all IXes, not having IX-F JSON at hand/enabled

**Describe the solution you'd like**
Add a button/mechanism for IXes to flag a `netixlan` entry as bad. If an entry is flagged as bad, run the normal dispute procedure.

**Do you think this feature will require a formal design?**
no

**Comment by arnoldnipper** [comment]
Complements #983

**Comment by job** [comment]
perhaps such a button should be called “report issue”?

**Comment by peterhelmenstine** [comment]
+ yup agreed

**Comment by mcmanuss8** [comment]
Dupe of #170 ?

**Comment by leovegoda** [comment]
This appears to be a duplicate of #170, which is scheduled for release in January 2024. I'm closing this issue.
