### ISSUE TITLE
Add a procedure for testing against production tagged code

### ISSUE THREAD

**Issue by grizz** [peeringdb/peeringdb#1273]
**Is your feature request related to a problem? Please describe.**

When discussing PDB auth at NANOG 86, it was brought up that developers would like to be able to integrate PDB to their end to end testing, especially for auth, against the production code. We at PeeringDB would prefer to not have test or fake data in production, so we want to provide a way to automate testing from a local code base.

**Who is affected by the problem?**

Developers, integrators.

**What is the impact?**

**Are there security concerns?**

No.

**Are there privacy concerns?**

No.

**Describe the solution you'd like**

Building a container with tagged code should work well. We'll probably need to allow users to add fixtures and sync data from a local mirror which would require docs and possibly some support code.

**Do you think this feature will require a formal design?**

No, the functionality should already be there.

**Describe alternatives you've considered**

Above, adding test data to production.

**Could this feature request need support from the Admin Committee?**

No.

**Comment by mcmanuss8** [comment]
+1

**Comment by grizz** [comment]
Closing with #1274 and lack of third party testing. We now have a container to test against and can tweak and change as needed with new tickets.

This is being used as part of #1225's container testing as well.
