### ISSUE TITLE
Missing allowed sources for scrpts

### ISSUE THREAD

**Issue by grizz** [peeringdb/peeringdb#1275]
After deploying security improvements #1221 / #1242 we've noticed we're missing a some sources that should be allowed for functionality.

Currently have found /apidocs and captcha for registration, we're doing a full search to see if there's anything else.

**Comment by mcmanuss8** [comment]
Clear bug, let's fix this ASAP

**Comment by arnoldnipper** [comment]
+1 ... and we **need** captcha for registration
