### ISSUE TITLE
Excluded ASNs - Cyclic confirmation of status on RIR Whois

### ISSUE THREAD

**Issue by fischerdouglas** [peeringdb/peeringdb#1277]
**Is your feature request related to a problem? Please describe.**
The small ISP market is experiencing strong consolidation.
Almost every day an ISP is purchased or merged with another ISP, and with that, ASNs cease to exist.
In many cases the ASN numeric resource is returned or these resources are retrieved by the RIR/NIR/LIR.

I've come across ASNs a few times that no longer exist in the Whois/RDAP databases but are still present in the PeeringDB database.

I know that enabling PeeringDB registration is quite effective.
But in my view, the presence of these still active ASNs in PeeringDB indicates a failure in a cyclical commit process.
**Who is affected by the problem?**
Every one that trust PeeringDB only to establish peering relationship with other networks.

**What is the impact?**
Garbage information present in the PeeringDB base.

**Are there security concerns?**
Yes! If the ASN does not exist anymore, and PeeringDB keeps that ASN on his base, it could be used for 

**Are there privacy concerns?**
I do not think so.
All related data is natively public.

**Describe the solution you'd like**

**Do you think this feature will require a formal design?**
Yes

**Describe alternatives you've considered**
I believe an automated engine running 2-4 times a day checking via RDAP/Whois against the respective RIRs can solve this.
Maybe consider that instead of deleting the ASN, add some way to mark that ASN as "inactive" or "removed_from_RIR".

**Could this feature request need support from the Admin Committee?**
I don't know how to express an opinion on this.

**What is the proposed priority?**
Regular

**Provide a rationale for any/all of the above**
Manter a base do PeeringDB limpa e confiável.

**Additional context**

At 10:15 (GMT-3) on 2022-10-27 the network https://peeringdb.com/asn/265343 existed as "LOPES TELECOM EIRELI - ME".
And on the Registro.BR whois site, the ASN appeared with "Recurso Inexistent" https://registro.br/tecnologia/ferramentas/whois/?search=AS265343

This is a file of numerical resources retrieved by Registro.BR - LIR from LACNIC.
https://ftp.registro.br/pub/numeracao/recuperados-latest

**Comment by arnoldnipper** [comment]
Once `rir_status` is successfully implemented, we will auto-remove stale networks after 90 days. Iow, the [issue](https://github.com/peeringdb/peeringdb/issues/473) is addressed since 3+ years already. Hey, we are superfast

**Comment by grizz** [comment]
@arnoldnipper Where is the issue that deals with removing after being stale for 90 days?

**Comment by grizz** [comment]
Found it, @fischerdouglas I believe #1271 accomplishes what you're asking for.
