### ISSUE TITLE
Commandline tool "Run command" button gone

### ISSUE THREAD

**Issue by vegu** [peeringdb/peeringdb#1278]
**Describe the bug**

The "Run command" button for the commandline-tool admin tool has been replaced by a generic "Add commandlinetool" button.

This appears to be a UX templating issue between the new data export tool and the command line tool.

Run command is still available by manually navigating to `/cp/peeringdb_server/commandlinetool/prepare`

**Who is affected by the problem?**

admincom

**Comment by arnoldnipper** [comment]
Identified as a bug by a developer
