### ISSUE TITLE
RIR status gets deleted when changes are made to the network

### ISSUE THREAD

**Issue by vegu** [peeringdb/peeringdb#1279]
**Describe the bug**

Updating a network's data through the interface at `/net/{id}` will reset its `rir_status` value to `null`.

The `rir_status` value will remain `null` until the rir status update job runs again. (currently runs once per day)

**To Reproduce**
1. Go to a network at `/net/{id}` that currently has "RIR Status" "ok"
2. Click edit, change any field, click save
3. Reload page - RIR status is now null

**Comment by arnoldnipper** [comment]
Routed through to 3a as identified as a bug by a developer

**Comment by arnoldnipper** [comment]
**when updating `rir_status` or `rir_status_updated`, don't update `updated`**
