### ISSUE TITLE
Improve RIR Update Procedure

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/peeringdb#1280]
**Is your feature request related to a problem? Please describe.**

[Since 3,5 years](#473) we work on adding the RIR status of an ASN to get rid of stale networks. Though in place since 2.39.0 it still [doesn't work properly](#1279). The `rir_status` must not only looked at regularly (once per day atm), but also whenever the `status` changes.

`rir_status` is already populated. As this is unreliable atm, reset the status completely, once.
- if the ASN is flagged OK by a RIR, set rir_status="ok" and set rir_status_updated=now()
- f the ASN is not flagged OK by a RIR, set rir_status="notok" and set rir_status_updated=now()
- **when updating `rir_status` or `rir_status_updated`, don't update `updated`**

Anytime:
-  if an ASN is added, set rir_status="ok" and set `=created
-  if an ASN is deleted (manually), set rir_status="notok" and set rir_status_updated=updated
-  if an ASN is re-added, set rir_status="ok" and set rir_status_updated=updated

 Regularly (00:00 UTC atm)
-  if old_rir_status=="ok" and new_rir_status=="ok": noop
-  if old_rir_status=="ok" and new_rir_status=="notok": set rir_status="notok" and set rir_status_updated=now()
-  if old_rir_status=="notok" and now()-oldset rir_status_updated >= 90*86400: delete object
-  if old_rir_status=="notok" and new_rir_status=="ok": notify AC to look into it

**Comment by arnoldnipper** [comment]
Dear [AC](@peeringdb/ac) and [PC](@peeringdb/pc), please comment. This RIR thingie is hanging around for a while. Having it implemented will help improving data quality

**Comment by netravnen** [comment]
IMO, it reads a very sensible proposal in the outline above.
+1

**Comment by peterhelmenstine** [comment]
+1

**Comment by martinhannigan** [comment]
I can't see how looking at it more than monthly matters. Keeping cloud
costs down balanced against this benefit makes me believe it is worth
waiting. RIR data is notoriously inaccurate and policy varies region to
region including how legacy holders are treated. Setting flags for almost
anything  RIR related could be low priority if that's all we are doing. I'd
probably not be in favor of trying to increase the importance of RIR data
any further than what we use it for as it stands.

Not for or against yet.

Thanks

-M<

**Comment by arnoldnipper** [comment]
> RIR data is notoriously inaccurate

We are taking information from the RIRs when we populate the `net` record with information. According to your allegation we shouldn't do that. But where should we then take the information from?

**Comment by martinhannigan** [comment]
On Thu, Dec 15, 2022 at 3:24 AM Arnold Nipper ***@***.***>
wrote:

> RIR data is notoriously inaccurate
>
> We are taking information from the RIRs when we populate the net record
> with information. According to your allegation we shouldn't do that. But
> where should we then take the information from?
>

RIR data being inaccurate is not an allegation, it's a fact. I never chimed
in on if we should or shouldn't do it. This seems like a reasonable
improvement - that doesn't require spending much money. Probably doesn't
cost a lot to implement or change anyhow. But resources are precious so I
suggest limited exposure for this particular feature.

When we use RIR data to make a true or false decision I suggest we should
have a second or third input to increase the accuracy. To improve our
accuracy.

YMMV, $0.02

Warm regards and happy holidays!

Martin

**Comment by mcmanuss8** [comment]
+1

**Comment by arnoldnipper** [comment]
@leovegoda, it's ready for implementation and a minor, but it would massively help to remove stale ASN data.
