### ISSUE TITLE
Ops: Emails to OPERATIONS_EMAIL need to be rate-limited

### ISSUE THREAD

**Issue by ccaputo** [peeringdb/peeringdb#1282]
With yesterday's database upgrades we discovered that errors sent to OPERATIONS_EMAIL can result in a denial of service for the mail processor. Thus we should limit the rate at which emails from each instance can dispatch to OPERATIONS_EMAIL.

Tunable in ".env" as "OPERATIONS_EMAIL_RATELIMIT", with a default, if not defined, of 2/minute.

NOTE: The database must _not_ be used for the rate limiting. Design TBD, but it needs to be something with very minimal dependencies, since this is part of error reporting. I recommend django shared memory, if able, or something like a temp file worst case (since EBS could be throttled).

**Comment by mcmanuss8** [comment]
Are we worried about rate limiting across hosts/containers? Or is an imperfect solution where each host has its own rate limit good enough to solve this?

**Comment by ccaputo** [comment]
> Are we worried about rate limiting across hosts/containers? Or is an imperfect solution where each host has its own rate limit good enough to solve this?

Imperfect is perfectly sufficient for this.
