### ISSUE TITLE
Footer "Global System Statistics" should be cached within django instance, not updated with every page load

### ISSUE THREAD

**Issue by ccaputo** [peeringdb/peeringdb#1283]
From my Operations perspective, it appears that each page load includes "Global System Statistics" in the footer of a page that has realtime statistics queried from the database. That is 8x different "SELECT COUNT(*)" SQL commands, per footer, significantly slowing response time since the HTML is not dispatched until these are rendered. There is no need for these to be perfectly realtime and in fact it creates unneeded load on the database. These statistics change very slowly.

These should be cached in django memory, per instance. I think a 5 (or 15?) minute in-memory cache for this data is sufficient. If cache is older than 5 (or 15?) minutes, the querier can update it. If in an in-memory solution is not feasible, a temporary local file can work. Or maybe some other lightweight design.

I think this work is important to do because it costs PeeringDB money to support higher database queries. Reducing this kind of extra load will reduce costs while improving performance for all of the users.

**Comment by mcmanuss8** [comment]
+1 cache this in whatever caching layer we already support

**Comment by martinhannigan** [comment]
I'd argue it needs to be generated once a week vs. a day or hour. It's an
advertisement. Certainly something to be proud of, but not something that
should cost us more than a few cents a week to maintain.

YMMV

-M<

**Comment by ccaputo** [comment]
I believe https://github.com/peeringdb/peeringdb/blob/e81ce506b563672c3fe1357338e403cbf8344161/peeringdb_server/stats.py#L36 also needs a `status="ok"` filter.

**Comment by grizz** [comment]
@ccaputo We missed this comment
