### ISSUE TITLE
Ops: django needs lightweight healthcheck route that confirms database connectivity

### ISSUE THREAD

**Issue by ccaputo** [peeringdb/peeringdb#1284]
At present the HTTP load balancers are checking the health of instances, to determine which are alive to receive end-user requests, by querying for "/robots.txt". This is a temporary solution to reduce database load. We were previously pulling "/" which involved several SQL SELECT queries.

We should return to including database wellness as part of healthchecks, but in a lightweight way that does not adversely impact users or raise costs.

Thus Operations needs the following:

- a "/healthcheck" route implemented in django.

- this route will perform a "SELECT version()" against the configured database. If the SELECT succeeds, the HTTP GET should return 200. If it fails, HTTP get should return HTTP 500 (or other appropriate error code).

- after this route becomes available on the beta & production instances, the AWS ALB "target group" health checker configurations should be adjusted accordingly, replacing the current "/robots.txt" query.

**Comment by ccaputo** [comment]
@vegu In reviewing the code, I don't see how view_healthcheck() will ever return anything other than HTTP 200. Can you advise what happens if `cursor.execute("SELECT version()")` fails?

**Comment by vegu** [comment]
@ccaputo The default django internal server error will be raised.

So a HTTP status 500 response with content "Internal Server Error"

**Comment by ccaputo** [comment]
> @ccaputo The default django internal server error will be raised.
> 
> So a HTTP status 500 response with content "Internal Server Error"

Perfect. And now tested on beta with respect to a working database and a bad database configuration. Thanks!

Will role this to production after the next production deploy.

**Comment by ccaputo** [comment]
Prod and tutorial target groups are now using "/healthcheck".
