### ISSUE TITLE
Ops: Expose CSP_CONNECT_SRC to .env

### ISSUE THREAD

**Issue by ccaputo** [peeringdb/peeringdb#1288]
Per @vegu: "We currently do not define or expose a CSP_CONNECT_SRC variable, but this should probably be added in the future, so we can be more specific with these policies."

Once this is in place, I think we can remove `CSP_DEFAULT_SRC=*.google-analytics.com,'self'` from .env and replace it with `CSP_CONNECT_SRC=*.google-analytics.com,'self'` either in .env or as a default in `__init__.py`. CSP_DEFAULT_SRC would then default to `'self'` per https://github.com/peeringdb/peeringdb/blob/e81ce506b563672c3fe1357338e403cbf8344161/mainsite/settings/__init__.py#L681-L686.

**Comment by grizz** [comment]
**Summary**

Add configuration options for ease of operations.

**Comment by ccaputo** [comment]
I commented out `CSP_DEFAULT_SRC=*.google-analytics.com,'self'` in .env on beta and restarted django on those instances, and confirm the changes made for this issue enable Google Analytics reporting to continue to work.
