### ISSUE TITLE
Add permission 'manage peering sessions'

### ISSUE THREAD

**Issue by BarbarossaTM** [peeringdb/peeringdb#1290]
**Is your feature request related to a problem? Please describe.**

PeeringDB offers the possibility to use it as an OAuth provider which is great, thanks for that!
If one uses this feature, for example to grant (potential) peers access to a peering portal for the own network, one question is which users should be allowed to manage peering sessions within this portal. Options range from only allowing access for PeeringDB users with `admin` rights to everyone who has a PeeringDB account and is associated with a given ASN. This might not be what the administrators of an organisation/network in PeeringDB want though.

**Who is affected by the problem?**

Users of the OAuth feature.

**What is the impact?**

Potentially too narrow or to wide access in applications consuming the OAuth feature.

**Are there security concerns?**

None.

**Are there privacy concerns?**

None.

**Describe the solution you'd like**

While working on a Peering Portal which consumes the PDB OAuth API I started wondering if it were possible to add another permission into the mix within PeeringDB to denote that a user should be able to manage peering sessions for this organisation/ASN. This would obviously not have any influence inside PeeringDB itself but would be helpful for consumers of the OAuth API do manage access within Peering Portals etc.

This could look like this:

![pdb](https://user-images.githubusercontent.com/10324868/203766917-a090f8c6-1432-4ecb-8974-f0afbb296a31.jpg)

The permission would not make much sense for facilities (but would not be of harm I guess), but rather for networks and maybe even IXPs. If this right were to be incorporated into the rights presented via the API, consumers can easily act on it.

**Do you think this feature will require a formal design?**

I don't know the code/architecture but would assume it should be fairly straight forward to add another permission into the mix, so this should not require a formal design :-)

**Describe alternatives you've considered**

None.

**Could this feature request need support from the Admin Committee?**

I don't know, but I guess not :-)

**What is the proposed priority?**

It would be very nifty to have but is not urgent.

**Provide a rationale for any/all of the above**

Layd out above :-)

**Comment by grizz** [comment]
@BarbarossaTM Thanks for issue!

I think that makes a lot of sense and will discuss further with the PC.

From a technical side, it should be as simple as adding another permission bit.

@peeringdb/pc Thoughts?

**Comment by martinhannigan** [comment]
Like. +1

**Comment by mcmanuss8** [comment]
+1

**Comment by grizz** [comment]
+1

**Comment by peterhelmenstine** [comment]
+1

**Comment by martinhannigan** [comment]
-+1
