### ISSUE TITLE
Show all e-mail addresses associated with a username

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/peeringdb#1291]
**Describe the bug**
Currently, only the so-called "primary" e-mail address is shown in the `org` "Users" tab. And in case it violates the restriction the one from the non-primaries with the lowest ID is shown.

Both for [AC](@peeringdb/ac) and the PeeringDB admins of the `org` it would help to show **all** addresses

**To Reproduce**
1. Go to https://www.peeringdb.com/org/29027#users
2. Search the AC GUI for the username

**Expected behavior**
Show **all** email addresses associated with a username

**Are there security concerns?**
no

**Are there privacy concerns?**
no

**Comment by peterhelmenstine** [comment]
+1

**Comment by mcmanuss8** [comment]
+1

**Comment by grizz** [comment]
+1

**Comment by martinhannigan** [comment]
+2

**Comment by peterhelmenstine** [comment]
+1

**Comment by martinhannigan** [comment]
+1

From: Peter Helmenstine ***@***.***>
Date: Thursday, April 6, 2023 at 11:31 AM
To: peeringdb/peeringdb ***@***.***>
Cc: Martin Hannigan ***@***.***>, Comment ***@***.***>
Subject: Re: [peeringdb/peeringdb] Show all e-mail addresses associated with a username (Issue #1291)

+1
