### ISSUE TITLE
user approval emails go to non www URL

### ISSUE THREAD

**Issue by grizz** [peeringdb/peeringdb#1292]
**Describe the bug**

For example, a user org approval emails has:

```
As the organization's administrator you may view your organization's user list here:

https://peeringdb.com//org/XXXX#users
```

The above is a production config change, but while looking around for that, I've found a few places that still reference `https://peeringdb.com/` that should be cleaned up.

Creating this issue to track changes.

@peeringdb/pc pushing as a bug to Next release.

**Comment by grizz** [comment]
Also fixed BASE_URL in production config management

**Comment by peterhelmenstine** [comment]
+1 cleaner and more professional
