### ISSUE TITLE
Allow anonymous users to change languages

### ISSUE THREAD

**Issue by dvanallen** [peeringdb/peeringdb#1295]
Currently a user must create / log in to an account before they can set a language preference for PeeringDB by updating their user profile.  We should allow anonymous users to change the language on any page without having to get through the account login process.

I think it would be best to implement this as a language select box in the header or footer of the site, which will set a language cookie for the user and then reload the page to the selected language.

This is a project I've been discussing with @leovegoda for a while now, but I don't think we have an open Issue for it yet.  I have some code to contribute for this which needs feedback, which I'll include here shortly as a PR with some screenshots.

**Comment by arnoldnipper** [comment]
+1

**Comment by martinhannigan** [comment]
This is an interesting idea and comment. I'd like to suggest we put it on
the agenda for the next peeringDB product committee meeting @Stephen McManus
***@***.***>

Thanks!

**Comment by mcmanuss8** [comment]
+1

**Comment by grizz** [comment]
+1

**Comment by martinhannigan** [comment]
+1




Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by leovegoda** [comment]
> @leovegoda Should this be pulled in for the 2.45 release?

Yes, please!
