### ISSUE TITLE
CSRF cookie not set error from email confirmation view

### ISSUE THREAD

**Issue by dvanallen** [peeringdb/peeringdb#1296]
Users without an existing session cookie who press the button to confirm their email will receive an error response:

`{"non_field_errors": ["CSRF cookie not set."]}`

The trigger for this issue seems to be the combination of https://github.com/peeringdb/peeringdb/issues/1205 and https://github.com/peeringdb/peeringdb/pull/1183.  Because we use CSRF middleware with `CSRF_USE_SESSIONS`, we need to have a session for all paths that may take a POST request from an anonymous user.  We need to update the custom session middleware to allowlist all new paths where an anonymous user may make a POST request.

Why this doesn't happen every time: the email confirmation page does not set a session cookie, but it can use one that already exists from the user having visited one of the login pages allowlisted in our custom Session Middleware: https://github.com/peeringdb/peeringdb/blob/355fff42924a62b1920bd1f263d83e696e96b74b/peeringdb_server/middleware.py#L52-L58.  Note that this does not convey any additional security - the user could simply visit the `/login` page to receive a new session cookie, without actually needing to login.

I suggest that we invert the logic in the session middleware to instead add the API endpoints to a denylist, and then allow session creation for all other paths.  This will make it simpler to add new paths with CSRF protection in the future.

For example, I would like to add a language selection option for anonymous users on all non-API pages in https://github.com/peeringdb/peeringdb/issues/1295.

**To Reproduce**
1. Create a new user profile.
1. Delete your session cookie.
1. Open the confirmation email link.
1. Click the confirm button.
1. Failure.

**Comment by arnoldnipper** [comment]
+1

**Comment by grizz** [comment]
**Summary**

Fix a bug with CSRF cookies not being set.

**Comment by grizz** [comment]
@dvanallen Huge thank you for figuring this out and making changes available for us to pull in! :1st_place_medal:
