### ISSUE TITLE
Increase IPv4/6 prefix limits

### ISSUE THREAD

**Issue by grizz** [peeringdb/peeringdb#1298]
Moved from https://github.com/peeringdb/peeringdb/issues/671#issuecomment-1366988272

> as of 28-12-2022 2247 I see on [Potaroo](https://bgp.potaroo.net/v6/v6rpt.html)
>
> IPv4: 941718
> IPv6: 171984
>
> Given that we are already at 1M for IPv4 and 100k for IPv6, I suggest to raise the values of info_prefixes4 resp 
> info_prefixes6 to
>
> IPv4: 1.2M
> IPv6: 180k

+1

**Comment by martinhannigan** [comment]
+1

**Comment by leovegoda** [comment]
@grizz Can we close this?
