### ISSUE TITLE
Exact match and then alphabetical results for simple search

### ISSUE THREAD

**Issue by leovegoda** [peeringdb/peeringdb#1299]
**Is your feature request related to a problem? Please describe.**
Search results from simple searches on https://www.peeringdb.com do not have their results presented in alphabetical order. This makes it more challenging to find the result you want when there are many results. Ordering the results alphabetically would be good. Example search: https://www.peeringdb.com/search?q=sky

**Who is affected by the problem?**
Anyone using simple search on the web interface and searching for a phrase in many company names

**What is the impact?**
This will help users find their results faster

**Are there security concerns?**
No

**Are there privacy concerns?**
No

**Describe the solution you'd like**
Implement standard alphabetical sorting

**Do you think this feature will require a formal design?**
No

**Describe alternatives you've considered**
Leaving it as it is

**Could this feature request need support from the Admin Committee?**
Unlikely

**What is the proposed priority?**
Not urgent

**Provide a rationale for any/all of the above**
Improve the experience for web users, particularly on mobile devices

**Additional context**
None

**Comment by martinhannigan** [comment]
Interesting, and I support the work here.

I have a suggestion for two alternatives. One I like, one I just want to
see what others think about as an add on.

The first is sorting based on the latest entry updated. Freshest first, to
incentivize accuracy. May be worth spending time and money on.

Second is sorting by sponsors first, to incentivize sponsoring. I like this
less, however, I don't know what people think of it overall. Not certain
this is worth spending time and money on.

Then the obvious question. What's the penalty for doing nothing? Is someone
asking for us to sort alphabetically?

Thanks!

-M<

**Comment by martinhannigan** [comment]
Thanks, helpful. This sounds more suitable to the overall search issue vs.
a separate issue. Would it be useful to include it in that discussion?

**Comment by leovegoda** [comment]
> Thanks, helpful. This sounds more suitable to the overall search issue vs. a separate issue. Would it be useful to include it in that discussion?

It is definitely a small issue. Including it with other related issues makes sense. Because it is related to the display of data, rather than what is returned, it might fit better in a cycle focused on improving the website user interface.

**Comment by leovegoda** [comment]
In today's @peeringdb/pc meeting we agreed that the best option would be to put exact match search results at the top and then alphabetize partial matches below that

**Comment by grizz** [comment]
Include with #1204

**Comment by peterhelmenstine** [comment]
+1

**Comment by martinhannigan** [comment]
+1
