### ISSUE TITLE
Unlike stated string filtering operations are not case-insensitive

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/peeringdb#130]
curl -s -k -X GET https://peeringdb.com/api/ix\?name__startswith="npix" | jq '.data[]' | wc -l
0

curl -s -k -X GET https://peeringdb.com/api/ix\?name__startswith="npIX" | jq '.data[]' | wc -l
46

**Comment by vegu** [comment]
fixed in 2fcba9c
