### ISSUE TITLE
Deploy Google Analytics on www and docs

### ISSUE THREAD

**Issue by leovegoda** [peeringdb/peeringdb#1308]
**Is your feature request related to a problem? Please describe.**
We deployed Google Analytics on beta.peeringdb.com in 2.42.0 (November 2022) as a first step towards achieving the objectives set out in https://github.com/peeringdb/peeringdb/issues/1218

2.43.0 (January 2023) was the first opportunity to collect data from users testing against beta. One takeaway is that we probably need to encourage more organizations to test against beta.

The rationale behind #1218 remains, so we should move towards deploying Google Analytics on www and docs. That way we'll be better informed about who our users are and be in a better position to make good decisions.

Before deploying on www and docs we should deploy https://github.com/peeringdb/peeringdb/issues/1281 so we know which pages users are using.

There is a guide to deploying Google Analytics on MkDocs (docs) here: https://squidfunk.github.io/mkdocs-material/setup/setting-up-site-analytics/

**Who is affected by the problem?**
@peeringdb/pc 

**What is the impact?**
All users should benefit from better product decisions

**Are there security concerns?**
No

**Are there privacy concerns?**
Not really. Users who object will have installed a browser plugin that ignores the Google Analytics URL

**Describe the solution you'd like**
1. Deploy #1281 
2. Deploy Google Analytics on www and docs

These can happen in the same deployment.

**Do you think this feature will require a formal design?**
No

**Describe alternatives you've considered**
We looked at a range of web analytics tools and Google Analytics seemed like the best fit for us

**Could this feature request need support from the Admin Committee?**
No

**What is the proposed priority?**
Target of 2.45.0

**Provide a rationale for any/all of the above**
As above

**Comment by peterhelmenstine** [comment]
+1

**Comment by grizz** [comment]
+1

**Comment by mcmanuss8** [comment]
+1

**Comment by grizz** [comment]
Added to prod deploy environment for 2.45.0
