### ISSUE TITLE
[beta] django-two-factor-auth 1.15.0 compatibility issues

### ISSUE THREAD

**Issue by vegu** [peeringdb/peeringdb#1309]
`2.43.0-beta` installs version `1.15.0` of `django-two-factor-auth`, during testing we have noticed that this introduces the following issues

- it breaks OTP email recovery
- it introduces issues with the migration state 

django-two-factor-auth should be pinned to 1.14 for the 2.43.0 release and then the issues above should be fixed during the next dependency upgrade cycle.

**Comment by grizz** [comment]
We'll revisit during #1311

**Comment by ccaputo** [comment]
@grizz Re-opening because I want to make sure the pull request (https://github.com/peeringdb/peeringdb/pull/1310) gets included in the code base prior to the next deploy.
