### ISSUE TITLE
Update Dependencies

### ISSUE THREAD

**Issue by grizz** [peeringdb/peeringdb#1311]
Update all dependencies to new major releases.

This year includes Django 4.2 LTS

**Comment by leovegoda** [comment]
@peeringdb/pc I'd like to schedule this essential work. Is there approval to go ahead?

**Comment by mcmanuss8** [comment]
+1

**Comment by arnoldnipper** [comment]
+1

**Comment by martinhannigan** [comment]
+1

**Comment by peterhelmenstine** [comment]
+1
