### ISSUE TITLE
"Please Confirm Your E-mail Address" required once a week

### ISSUE THREAD

**Issue by martzuk** [peeringdb/peeringdb#1312]
My organisation has enabled email verification. It seems to ask me to verify my email once per week (looking back in my mailbox). This seems to be triggered by me logging in. Surely we shouldn't have to verify this frequently?

**Comment by leovegoda** [comment]
> My organisation has enabled email verification. It seems to ask me to verify my email once per week (looking back in my mailbox). This seems to be triggered by me logging in. Surely we shouldn't have to verify this frequently?

Your organization's administrator can change the frequency. The current set of frequencies offered is:

- 1 week
- 2 weeks
- 1 month
- 6 months
- 1 year

**Comment by martzuk** [comment]
Was hidden in a corner, thanks :)
