### ISSUE TITLE
Improve email confirmation control - add 3 month option & maybe set new default value

### ISSUE THREAD

**Issue by leovegoda** [peeringdb/peeringdb#1313]
**Is your feature request related to a problem? Please describe.**
#1312 indicates that some admins might not realize that they can set different values for the periodic reconfirm control in the Users tab of the organization management control page.

It would be good if we could add a tooltip, an additional period, and possible change the default from one week to something else.

<img width="1187" alt="Screenshot 2023-01-25 at 13 16 54" src="https://user-images.githubusercontent.com/59064677/214694041-37fcc6bf-83c3-40c3-a178-2a024c2ae997.png">

**Who is affected by the problem?**
Admins and users whose admins enable this option.

**What is the impact?**
Help admins make an informed choice and give them more options.

**Are there security concerns?**
No

**Are there privacy concerns?**
No

**Describe the solution you'd like**
1. A tooltip letting admins know that a range of options is available
2. An option for 3 months 
3. Possibly changing the default from 1 week to something else - @peeringdb/pc if so what should the default be?

**Do you think this feature will require a formal design?**
No

**Describe alternatives you've considered**
Do nothing

**Could this feature request need support from the Admin Committee?**
These changes should reduce demand on the AC

**What is the proposed priority?**
Relatively soon

**Provide a rationale for any/all of the above**
This should help improve the balance between security and usability for both users and admins

**Comment by martinhannigan** [comment]
Thanks Leo. Do you recall the issue that was raised to implement this in
the first place?

**Comment by mcmanuss8** [comment]
+1

**Comment by leovegoda** [comment]
> Thanks Leo. Do you recall the issue that was raised to implement this in the first place?

The feature was developed based on https://github.com/peeringdb/peeringdb/issues/737

**Comment by peterhelmenstine** [comment]
+1

**Comment by martinhannigan** [comment]
+1
