### ISSUE TITLE
issues when accepting / denying carrier presence requests

### ISSUE THREAD

**Issue by vegu** [peeringdb/peeringdb#1315]
**Describe the bug**

Currently only organization administrators are able to accept / deny carrier presence requests at their facilties.

Users that have been given permissions to manage only facilities currently have nothing happen when they click either accept or deny.

The browser console shows that their request was denied, and the error notification to the UX is lost in a separate error.

**Expected behavior**

Organization members that have been granted permission to manage facilities should be able to accept / deny carrier presence request at their permissioned facility.

**Who is affected by the problem?**

Facility administrators

**Comment by arnoldnipper** [comment]
> Currently only organization administrators are able to accept / deny carrier presence requests at their facilties.

Not even `org` admins are able to accept / deny carrier presence requests at their facilties. Only superusers can.

**Feature Request**
Auto-approve if `carrier.org_id` == `fac.org_id`

**Comment by arnoldnipper** [comment]
Identified as a bug by a developer. Tbd whether the feature request can be handled with the bug fixing.

**Comment by vegu** [comment]
**Summary**

- fix permission issues when accepting or rejecting carrier facility presence requests
- automatically approve carrier-facility presence if both carrier and facility share the same organization
