### ISSUE TITLE
Carriers is missing from Advanced Search

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/peeringdb#1318]
**Describe the bug**
You can't search for Carriers at [Advanced Search](https://www.peeringdb.com/advanced_search)

**To Reproduce**
1 Go to https://www.peeringdb.com/advanced_search
2 There is no Carrier to search for

**Expected behavior**
You can search for Carriers

**Comment by leovegoda** [comment]
I've asked for this to be included in https://github.com/peeringdb/peeringdb/issues/1204#issuecomment-1406780280

**Comment by martinhannigan** [comment]
+1

**Comment by leovegoda** [comment]
Could we implement this by adding a "Carrier Presence" search above the "Network Presence" search?

<img width="1387" alt="Screenshot 2023-11-03 at 14 15 19" src="https://github.com/peeringdb/peeringdb/assets/59064677/52ae2fd1-3908-4f82-b2a1-206c53455676">

**Comment by leovegoda** [comment]
Support for carrier search is now implemented in v2 search (the default basic search) and works nicely. Is this issue still needed?
<img width="1330" alt="Screenshot 2023-11-15 at 10 11 25" src="https://github.com/peeringdb/peeringdb/assets/59064677/ddb5da74-2503-4bb2-afab-737fae2a2374">

**Comment by jackcarrozzo** [comment]
If advanced search isn't sunsetted, this is worth doing

**Comment by grizz** [comment]
+1

**Comment by mcmanuss8** [comment]
+1

**Comment by jbartig** [comment]
+1
