### ISSUE TITLE
Bug in API

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/peeringdb#132]
User reportes:

As far as i can see there's a problem in the API methods.
Please look at the following:

mmarzetti@arno:~$ curl https://www.peeringdb.com/api/ix?name__in="Equinix Sydney"
{"meta": {}, "data": [{"id": 94, "org_id": 2, "name": "Equinix Sydney", "name_long": "Equinix Sydney Exchange", "city": "Sydney", "country": "AU", "region_continent": "Australia", "media": "Ethernet", "notes": "", "proto_unicast": true, "proto_multicast": false, "proto_ipv6": true, "website": "https://ix.equinix.com", "url_stats": "", "tech_email": "ap-noc@ap.equinix.com", "tech_phone": "+65-67238833", "policy_email": "peering@ap.equinix.com", "policy_phone": "+612.8337.2000", "created": "2010-07-29T00:00:00Z", "updated": "2016-06-08T15:55:17Z", "status": 

mmarzetti@arno:~$ curl https://www.peeringdb.com/api/ix?name__in="Foo Bar Foo"
{"meta": {}, "data": []}

mmarzetti@arno:~$ curl https://www.peeringdb.com/api/ix?name__in="Equinix Hong Kong"
<html>
<head><title>400 Bad Request</title></head>
<body bgcolor="white">
<center><h1>400 Bad Request</h1></center>
<hr><center>nginx</center>
</body>
</html>

Please note that Equinix Hong Kong is an existing exchange.
URL: https://www.peeringdb.com/ix/125

**Comment by vegu** [comment]
Hmm, at first inspection this appears to a be a weird inconsistency within nginx. Does not look like curl is properly encoding that url, as to why nginx lets it through in some cases and in some others fails with bad request i can't say at this point.

> GET /api/ix?name__in=Equinix Hong Kong HTTP/1.1
> Bad request syntax ('GET /api/ix?name__in=Equinix Hong Kong HTTP/1.1').

The problem goes away entirely if we do proper url encoding:

curl -G http://dev2.20c.com:7024/api/ix --data-urlencode "name__in=Equinix Hong Kong"

or

curl http://dev2.20c.com:7024/api/ix?name__in=Equinix%20Hong%20Kong

**Comment by lukastribus** [comment]
The uppercase H after the space triggers a codepath that expects "HTTP/1.1" (notice that this does not trigger when looking for "Equinix hong Kong" with a lowercase h):

```
$ curl "https://www.peeringdb.com/api/ix?name__in=Equinix hong Kong"
{"meta": {}, "data": [{"id": 125, "org_id": 2, "name": "Equinix Hong Kong", "name_long": "Equinix Hong Kong", "city": "Hong Kong", "country": "HK", "region_continent": "Asia Pacific", "media": "Ethernet", "notes": "", "proto_unicast": true, "proto_multicast": false, "proto_ipv6": true, "website": "https://ix.equinix.com", "url_stats": "", "tech_email": "ap-noc@ap.equinix.com", "tech_phone": "+65-67238833", "policy_email": "peering@ap.equinix.com", "policy_phone": "+852.2970.7788", "created": "2010-07-29T00:00:00Z", "updated": "2017-03-07T18:57:53Z", "status": "ok"}]}
$
```

Also see:
https://trac.nginx.org/nginx/ticket/196

> As per RFC it uses space as a delimiter, but backtracks to uri parsing (to please broken clients) if it doesn't see 'H' after space.

and:
> I tend to think that proper fix in nginx would be to disallow spaces in uri by default, this should make such problems much easier to find.


Maybe we can get this improved upstream:
http://mailman.nginx.org/pipermail/nginx/2017-April/053449.html

**Comment by eloos** [comment]
In my view this issue is not related to peeringdb and therefore should not be tracked as an issue here. This is explainable behaviour of our webserver based on malformed input.
