### ISSUE TITLE
Organization Network Type - Access technology agnostic

### ISSUE THREAD

**Issue by RossIreland** [peeringdb/peeringdb#1321]
The closest Network Type I see in the dropdown list is "Cable/DSL/ISP".

This doesn't cover FTTx type access or Mobile access.
We don't use Cable. We use DSL/FTTx/Mobile.

Can the field value be updated to include FTTx?
 
alternatively

Can a new technology agnostic option be added to the list?

e.g.

ACCESS/ISP

Thanks

**Comment by martinhannigan** [comment]
How about ISP/NSP without the specifics so that changes are seamless?

**Comment by RossIreland** [comment]
ISP/NSP is preferable to me than Cable/DSL/ISP.

That though perhaps loses some information about the main activity of the network. 
In our case that is connecting eyeballs to look at content.
I note "Content" is a Network Type in the list.
However the Traffic Ratios field covers whether a network is mainly Eyeballs, Content or in between.

Up to you. 

My main purpose with this request is to remove "Cable" from the Network Type that is most appropriate for us to use.

**Comment by grizz** [comment]
This was discussed on 2023-02-02, I think the PC will be following up with a plan after another round of discussion.

**Comment by RossIreland** [comment]
Sounds good.

I suggest keeping NSP and ISP as separate categories. They are sufficiently different.
My perception is that an NSP typically aims to have balanced traffic flows at least with other NSPs. 
An ISP will usually be satisfied with very asymmetric inward traffic flows and won't care much about outward traffic flow rates.

**Comment by leovegoda** [comment]
The PC [met in July](https://docs.peeringdb.com/committee/product/notes/2023-07-06_Product_Committee_Notes.pdf) and agreed that PeeringDB will retain the Network Type field. We will not change the types of networks but will implement the ability to select multiple types. This will be implemented in the website and v2 API now deployed. We will plan a more radical update of the field for a future v3 API.

**Comment by leovegoda** [comment]
The work described above will be tracked in https://github.com/peeringdb/peeringdb/issues/1357 so I'll close this issue as a duplicate
