### ISSUE TITLE
Give API writes high priority and limits

### ISSUE THREAD

**Issue by leovegoda** [peeringdb/peeringdb#1322]
**Is your feature request related to a problem? Please describe.**
We want to ensure that users sending large but reasonable numbers of API writes are not rate limited. The goal is that legitimate users sending a reasonable number of API writes should not need to re-try. 

The service should be protected against abuse with a high limit.

**Who is affected by the problem?**
We see a low level of API writes at the moment. This issue is anticipates the development of tools that push updates to PeeringDB automatically and choose to use the API.

**What is the impact?**
The goal is to avoid any impact.

**Are there security concerns?**
No

**Are there privacy concerns?**
No

**Describe the solution you'd like**
A limit on API writes that will protect service availability but not impact users making a large number of updates in an automation fashion.

**Do you think this feature will require a formal design?**
@peeringdb/oc should review the proposed limit

**Describe alternatives you've considered**
Do nothing

**Could this feature request need support from the Admin Committee?**
No

**What is the proposed priority?**
Not urgent

**Provide a rationale for any/all of the above**
We'd like to maximize data quality and one way to do this is to rely on networks and IXPs comparing their internal configurations against PeeringDB and automating updates. If we are successful in encouraging automated comparison of data and get more updates, we should ensure that users are not accidentally rate limited, especially on their first run.

**Additional context**
Discussed in today's @peeringdb/pc meeting.

**Comment by ccaputo** [comment]
A bulk updater will tend to supply data as quickly as it can, sending additional updates as soon as confirmation of the previous POST happens. Thus to regulate the flow in a way that does not monopolize, the PeeringDB server may need to delay the acknowledgement of a POST for reasonable pacing and sharing of resources with others. Possibly just a sub-second delay after multiple POSTs, or possibly a delay based on current general loading of an instance.

**Comment by martinhannigan** [comment]
Good DOS or resource control limitation.

+1

**Comment by peterhelmenstine** [comment]
+1 What limit would help protect but not limit legit users. Current peak from the data provided show about 687 POST as an average to say a 10k max limit just to protect from an attack or something broken?

**Comment by grizz** [comment]
+1

**Comment by martinhannigan** [comment]
We ask “set to what” a lot.

Do we have data to see what is “normal”?

**Comment by leovegoda** [comment]
> We ask “set to what” a lot. Do we have data to see what is “normal”?

The sampled data @arnoldnipper shared indicated that API writes were well under 1% of API reads.

**Comment by martinhannigan** [comment]
Cool. Ill have to find it. Thanks!

**Comment by peterhelmenstine** [comment]
see slack channel

**Comment by peterhelmenstine** [comment]
See my comment above or the slack #productcom

**Comment by grizz** [comment]
> See my comment above or the slack #productcom

Could you paste anything decided on here? The slack reference is going to be useless in 90 days :)

**Comment by peterhelmenstine** [comment]
Leo Vegoda
  [8:58 AM](https://peeringdb.slack.com/archives/C58U4TJDS/p1675357117758369)
These are the API data Arnold produced:
grep -v /api -h /efs/logs/nginx/*/access.log | grep -v GET | cut -d ” ” -f 6 | sort  | sed ‘s/^.//’ | uniq -c
      1 DELETE
    578 HEAD
    687 POST
[7:34 AM] grep /api -h /efs/logs/nginx/*/access.log | grep -v GET | cut -d ” ” -f 6 | sort  | sed ‘s/^.//’ | uniq -c
     21 DELETE
      2 HEAD
     12 OPTIONS
    172 POST
    141 PUT
[7:35 AM] The full picture
[7:35 AM] grep -v /api -h /efs/logs/nginx/*/access.log |  cut -d ” ” -f 6 | sort  | sed ‘s/^.//’ | uniq -c
      1 DELETE
 525547 GET
    578 HEAD
    693 POST
[7:36 AM] grep /api -h /efs/logs/nginx/*/access.log | cut -d ” ” -f 6 | sort  | sed ‘s/^.//’ | uniq -c
     21 DELETE
 143677 GET
      2 HEAD
     12 OPTIONS
    172 POST
    141 PUT

**Comment by martinhannigan** [comment]
This is good stuff. Admittedly, I'm a little lost here. Limiting API
writes  generically sounds like it's not really what we're after if we're
looking to set a limit that protects us in a multi-faceted way. I thought
we'd be looking at something lower level to evaluate a limit such as vmstat
data. Do we/is it worth digging that deep?

**Comment by ccaputo** [comment]
In case useful, these are the January 2023 API numbers:

```
    105 HEAD
    157 OPTIONS
    837 DELETE
   4507 POST
   5101 PUT
6866423 GET
```
