### ISSUE TITLE
Facility unable to accept carrier

### ISSUE THREAD

**Issue by jayhanke** [peeringdb/peeringdb#1323]
Clicking on the green Accept button doesn't authorize a new carrier in a facility

**To Reproduce**
1. Go to Facility page (logged in as facility owner)
2. Click on Accept for the Carrier that has requested a listing

**Expected behavior**
Accepting the carrier

**Who is affected by the problem?**
https://www.peeringdb.com/fac/10411
https://www.peeringdb.com/carrier/6

**Comment by netravnen** [comment]
@jayhanke looks like a dup of https://github.com/peeringdb/peeringdb/issues/1315 ?

**Comment by jayhanke** [comment]
Yes, looks like the same issue.

**Comment by leovegoda** [comment]
@jayhanke [2.43.1](https://docs.peeringdb.com/release_notes/#release-2431) should have resolved this problem, so I'm closing this  issue.
