### ISSUE TITLE
add favicon to all PeeringDB websites

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/peeringdb#133]
low hanging fruit

**Comment by grizz** [comment]
docs, www, can anyone think of any others?

**Comment by arnoldnipper** [comment]
Just add them to all sites running webservices :)

**Comment by ghankins** [comment]
https://status.peeringdb.com/
https://beta.peeringdb.com/

**Comment by grizz** [comment]
Closing, only the mailman one is left and is blocking on new mailman version
