### ISSUE TITLE
BFD support field in Global and IX specific views

### ISSUE THREAD

**Issue by jdhandap** [peeringdb/peeringdb#1331]
Running BFD across IXPs can provide faster convergence (1-3 sec) as opposed to 30-90sec today during failures within the IX environment (or) the remote end. 

Can we have BFD support field in the Global and IX specific views in peeringDB that IX participants can update? This could help facilitate wider BFD adoption across IXPs.. 
    a) This will help peers identify the peers that support BFD and thereby reducing effort and resources involved in setting up BFD with other peers across the IX
    b) It can also help with the automation workflow of enabling BFD

Thoughts?

**Comment by job** [comment]
If the goal is to automate it, wouldn’t it be better to let BGP opportunistically use BFD; instead of relying on an external source like PDB?

**Comment by job** [comment]
https://datatracker.ietf.org/doc/html/draft-ietf-idr-rs-bfd

**Comment by jdhandap** [comment]
@job : Its true that one could opportunistically enable BFD for all peers on the IX easily.. 

However, 

1)  Deterministic validation: 

The field in PeeringDB could be used as the  source of truth to validate that the BFD session is expected to be up or not. 

without some source of truth, doing validations on the BFD state is not effective. 


2) The field in peeringdb could be used to better determine the scalability requirements of BFD on router vendors..Do we need to certify BFD operations for 100/1000 peers in an IX market. 

3) In cases where some vendor platforms runs BFD in centralized mode (using route processor), the scalability could be limited and in those cases one would want to enable BFD on select peers based on their traffic profile / SLAs.. In these cases opportunistic approach may not be very effective.

**Comment by arnoldnipper** [comment]
+1

**Comment by grizz** [comment]
I think I like this, probably per port on the netixlan?

Next to RS Peer?
![image](https://user-images.githubusercontent.com/23176/220504818-da8b8682-51f5-48ab-98b4-18a85d46ae47.png)

**Comment by jdhandap** [comment]
Yeah, that would be the most granular point of application.

**Comment by martinhannigan** [comment]
I like it in principle. but I don't think we should call it a source of
truth. If the community wants a source of truth someone should start a
dedicated registry. It feels out of scope for PDB from that view. However,
we can certainly agree that a "best effort" field is warranted and I
support that sans source of truth labels.

**Comment by grizz** [comment]
+1

**Comment by grizz** [comment]
**Summary**

Use a bitfield, display an icon with a mouse over for both RS and BFD to keep the UI from getting cluttered.

**Comment by grizz** [comment]
@jdhandap @job single bool for BFD? Or should we split it up more?

**Comment by jdhandap** [comment]
@grizz : I believe it will be nice to have two bools, but may be #b is a necessity and #a would be a nice to have. 

a)  a global bool (to convey that a partner does support BFD towards IX connections). 
b) a bool per IX ( to convey that a partner supports BFD on the Network element attached to the IX). This may be more authoritative way to determine whether to activate BFD to this ASN on the IX.

**Comment by grizz** [comment]
> @grizz : I believe it will be nice to have two bools, but may be #b is a necessity and #a would be a nice to have.
> 
> a) a global bool (to convey that a partner does support BFD towards IX connections).

I don't think we're ready to add it there yet.. and I think it would make more sense as a read only aggregate of any ixlan's BFD flag. It should be noted for v3 however, #625 -- thanks!

> b) a bool per IP address per IX ( to convey that a partner supports BFD on the Network element attached to the IX). This may be more authoritative way to determine whether to activate BFD to this ASN on the IX.

Agreed

**Comment by leovegoda** [comment]
**Summary**
1. Add a boolean value for BFD support per IP address
2. Add a mouseover icon showing BFD support when the value is true
