### ISSUE TITLE
Available voltages are USA-centric

### ISSUE THREAD

**Issue by rfc1036** [peeringdb/peeringdb#1332]
**Describe the bug**

The list of available voltages for data centers does not reflect the common European electric power distribution practices.

The European standard for power distribution is **400 V three phase** (phase to phase) wye service with **230 V single phase** (phase to neutral).

While 240 V is close enough to 230 V (the accepted tolerance is +/- 10%, to support both the existing 220 V and 240 V networks), no option is provided to represent the commonly available 400 V three phase service.

**Expected behavior**

The list of available voltages should contain at least the most common options available in data centers.

**Who is affected by the problem?**

All European data centers.

**What is the impact?**

It is not currently possible to represent the voltages available in most European data center.

**Are there security concerns?**

No.

**Are there privacy concerns?**

No.

**What are the proposed actions?**

**Add 400 VAC** to the list of available voltages.

**What is the proposed priority?**

Not urgent.

**Comment by martinhannigan** [comment]
Excellent issue.

Frequency Hz is also typically different.  We need to make a few
adjustments to this field overall.

Ill grab for PC.

Thanks!

-M<

**Comment by rfc1036** [comment]
True, but with the notable exception of Japan the frequency of the national grid of a country is always known: so I suspect that adding a field for it would just add noise.

**Comment by martinhannigan** [comment]
I think we just need to add standard voltages globally to the checkboxes
then and let the users self select since they would know better?

**Comment by rfc1036** [comment]
Yes. I am not familiar with the US market, but I think that just adding an entry for 400 VAC would be good enough for Europeans.

**Comment by martinhannigan** [comment]
'

The 400V change makes sense. I have a few other unrelated changes since
we're opening the power options up for change and will submit a separate
issue.

+1

**Comment by arnoldnipper** [comment]
> The 400V change makes sense. I have a few other unrelated changes since we're opening the power options up for change and will submit a separate issue.

Why not fold the other power options here? Should be an easy one, @martinhannigan, by slightly changing the subject

**Comment by arnoldnipper** [comment]
+1

**Comment by arnoldnipper** [comment]
> True, but with the notable exception of Japan the frequency of the national grid of a country is always known: so I suspect that adding a field for it would just add noise.

+1, frequency does not make sense

**Comment by grizz** [comment]
+1

Separate power changes should be in a separate issue, otherwise they can slow this down and confuse things. We can still do them at the same time if the other ones get consensus :)

**Comment by martinhannigan** [comment]
Agree. Lets go with the 400v update mow.

+1

**Comment by martinhannigan** [comment]
Let's add the 240V question to the agenda tomorrow in our PC meeting. Its mostly a no op and not relevant to data centers so if we're adding 400V we can easily remove 240V.

**Comment by arnoldnipper** [comment]
> Let's add the 240V question to the agenda tomorrow in our PC meeting. Its mostly a no op and not relevant to data centers so if we're adding 400V we can easily remove 240V. Had some time to rethink. Its easy to do it now without impact.

You are right. It must read 230VAC. **And it's relevant**

**Comment by mcmanuss8** [comment]
+1

**Comment by martinhannigan** [comment]
On Thu, Mar 2, 2023 at 06:30 Arnold Nipper ***@***.***> wrote:

> Let's add the 240V question to the agenda tomorrow in our PC meeting. Its
> mostly a no op and not relevant to data centers so if we're adding 400V we
> can easily remove 240V. Had some time to rethink. Its easy to do it now
> without impact.
>
> You are right. It must read 230VAC. *And it's relevant*
>

Please explain how 230v is relevant to PDB?

**Comment by martinhannigan** [comment]
+1

**Comment by rfc1036** [comment]
230V is the only single phase power distribution available in European data centers, and is what is usually provided in racks with no more than 7 kW of power (which would be most of them).

**Comment by martinhannigan** [comment]
On Thu, Mar 2, 2023 at 15:48 rfc1036 ***@***.***> wrote:

> 230V is the only single phase power distribution available in European
> data centers, and is what is usually provided in racks with no more than 7
> kW of power (which would be most of them).
>
In the US households are provided with 220-240v. My oven runs 240. I’ll dig
into this with some DC folks and see if its truly relevant and how PDB
should address  Listing all common (or uncommon) voltages was not the point
of listing this. Admittedly it started US centric. The point was to make
site selection easier and indicating, say, 480v, was relevant to efficiency
of a suite and stepping down to (random). voltage in a building of DC’s. In
PDB parlance “an address”. It was never about common rack selection.

**Comment by arnoldnipper** [comment]
> Please explain how 230v is relevant to PDB?

https://en.wikipedia.org/wiki/Mains_electricity#Voltage_levels and what @rfc1036 said.

**Comment by martinhannigan** [comment]
The disconnect here is simple. Adding 400v from a European perspective in
addition to 480v from a NA view is good. From each you can step down to
whatever voltage you want in a variety of ways. If we want to add rack
voltages its going to get ugly e.g. single phase, 3PH, 4 wire, etc. We
could add distribution voltage, but DC’s already have that covered. That’s
not really the point.

The purpose of the field was to demonstrate the metered voltage for an
address. I think from a bell curve perspective we can believe that most
DC’s are consistent locally. So if you have a 480v service in a facility
and you hand off 480v to a tenant, you meter facing the tenant. They can
then step down to whatever they want below 480v, or 400v./

In the beginning, many of today’s networks went directly to building owners
and rented closets for PoP’s, especially in carrier hotels. Today, _you can
still do that_ This information is mainly intended to indicate that even if
GIANT1, 2 and 3 DC operators are in a building and with their own services
or not - you can still go and rent/lease from a landlord and use excess
building power. That’s a bit simplistic, but high level which is what I
intended when I proposed we note voltage. 240v was an error (too granular
and off beat in the big picture) in retrospect. So would 230v be IMHO.

If we want to get more granular this is going to be out of scope for PDB
IMHO.

Hope that helps.

I propose we go forward with 480v, 400v, delete 240v and continue to
improve competitiveness of addresses using non interconnection data from a
high level such as the above.

Thanks and hope that helps.

**Comment by rfc1036** [comment]
In the market I am most familiar with (Italy), in most data centers customers can only have 230V single phase delivered to racks, not 400V three phase: this is why 230V is relevant. Even cages usually do not have a dedicated switchboard. Not all customers buy colocation space by the suite.

**Comment by martinhannigan** [comment]
Agree. That’s not the point we tried to address with the field. I think you
make a good point though. What we are addressing is what’s upstream.

**Comment by arnoldnipper** [comment]
> Agree. That’s not the point we tried to address with the field. I think you
make a good point though. What we are addressing is what’s upstream.

Definitely not. We are addressing what's downstream. Hence, we should have

- 48VDC
- 120VAC (US/CA)
- 230VAC (almost worldwide)
- 400VAC (???)
- 480VAC

**Comment by martinhannigan** [comment]
What has been approved for this issue and should go forward is adding 400v and removing 240v. If someone wants to add 220, 120, 230v, 50hz, or any other indicator of available voltage another issue would be welcome.

Thanks!

-M>


On Fri, Mar 3, 2023 at 3:58 AM Arnold Nipper ***@***.******@***.***>> wrote:

Agree. That’s not the point we tried to address with the field. I think you
make a good point though. What we are addressing is what’s upstream.

Definitely not. We are addressing what's downstream. Hence, we should have

  *   48VDC
  *   120VAC (US/CA)
  *   230VAC (almost worldwide)
  *   400VAC (???)
  *   480VAC

**Comment by grizz** [comment]
Solved with #1341

**Comment by rfc1036** [comment]
I do not understand how removing 220V/230V/240V (which are functionally the same and are generally represented as just "230V") makes any sense: I know plenty of data centers which only provide 230V (i.e. single phase distribution) to single racks but not 400V (i.e. three phase distribution).

**Comment by arnoldnipper** [comment]
@rfc1036, we only left the *unusual* voltages. Does that make sense?

**Comment by rfc1036** [comment]
I do not think that it makes much sense, but I am no UX expert so...
