### ISSUE TITLE
Calling /api/carrier with parameters is broken

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/peeringdb#1333]
**Describe the bug**
212.86.201.219 - u1590 [17/Feb/2023:12:34:29 +0000] "GET /api/carrier?org_id=25554&fields=id%2Cname HTTP/1.1" 500 145 "-" "curl/7.52.1" 0.968
212.86.201.219 - u1590 [17/Feb/2023:12:35:32 +0000] "GET /api/carrier?org_id=25554 HTTP/1.1" 200 313 "-" "curl/7.52.1" 1.067

**To Reproduce**
see above

**Expected behavior**
API calls must also work with parameters

**Comment by arnoldnipper** [comment]
@peeringdb/20c, please confirm

**Comment by vegu** [comment]
Was able to reproduce bug and identify cause in https://github.com/peeringdb/peeringdb/blob/master/peeringdb_server/serializers.py#L1854
