### ISSUE TITLE
Clearly show when a facility is part of a campus

### ISSUE THREAD

**Issue by leovegoda** [peeringdb/peeringdb#1336]
**Is your feature request related to a problem? Please describe.**
The @peeringdb/pc agreed at its [second February meeting](https://docs.peeringdb.com/committee/product/notes/2023-02-14_Product_Committee_Notes.pdf) that we should make it easy for `facility` operators to show when a `facility` is a part of a `campus`. We agreed that it would be good to do this with a small icon.

**Who is affected by the problem?**
- `facility` operators can clearly show that a `campus` exists
- PeeringDB users searching for a `facility` can clearly see when it is part of a `campus` 

**What is the impact?**
Improve the user experience for everyone

**Are there security concerns?**
No

**Are there privacy concerns?**
No

**Describe the solution you'd like**
Add a small icon alongside each `facility` in a campus

**Do you think this feature will require a formal design?**
No

**Describe alternatives you've considered**
Do nothing, or add text

**Could this feature request need support from the Admin Committee?**
No

**What is the proposed priority?**
Soon

**Provide a rationale for any/all of the above**
We have added the `campus` object, so we should make it work effectively for all users

**Comment by mustangthz** [comment]
+1

**Comment by mcmanuss8** [comment]
+1

**Comment by grizz** [comment]
+1

**Comment by grizz** [comment]
> +1, but also add the `faccampus` object (which indirectly already is implemented via this badge)

`faccampus` needs to be a separate issue, there's no reason for it once we expose `fac.campus_id`, which is just waiting for us to decide to keep campus since it's an existing API change.

**Comment by arnoldnipper** [comment]
> `faccampus` needs to be a separate issue, there's no reason for it once we expose `fac.campus_id`, which is just waiting for us to decide to keep campus since it's an existing API change.

`fac.campus_id` means that a facility can be a member of at most one campus. If we all agree that's the case, then we don't need `faccampus`

**Comment by martinhannigan** [comment]
+1 for icon. -1 on rest.

**Comment by mustangthz** [comment]
Agreed.

**Comment by arnoldnipper** [comment]
> +1 for icon. -1 on rest.

Come on, @martinhannigan and @mustangthz. We agreed to have feature parity between GUI and API. I.e. there must be a way to easily detect that a facility is part of a camous.

**Comment by grizz** [comment]
@arnoldnipper this is an approved issue for adding an icon, please create a new issue for this discussion.

**Comment by arnoldnipper** [comment]
> @arnoldnipper this is an approved issue for adding an icon, please create a new issue for this discussion.

For adding an icon you must add an extra field to the `fac` object. So why not expose this to the API? Happy to create a new issue. IMO a bit bureaucratic, though

**Comment by martinhannigan** [comment]
Arnold you raised a multi campus issue as well. Needs more discussion to scope IMHO.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by grizz** [comment]
> > @arnoldnipper this is an approved issue for adding an icon, please create a new issue for this discussion.
> 
> For adding an icon you must add an extra field to the `fac` object.

That's not true. 

> So why not expose this to the API? Happy to create a new issue.

Exposing via API is already planned once we have vetted this object.

> IMO a bit bureaucratic, though

It's highly distracting to discuss this on an approved trivial issue, this is akin to thread hijacking.

**Comment by arnoldnipper** [comment]
> It's highly distracting to discuss this on an approved trivial issue, this is akin to thread hijacking.

Let's move on in #1340

**Comment by grizz** [comment]
**Summary**
Show an icon when a facility is part of a campus.
