### ISSUE TITLE
add favicon to mailman site

### ISSUE THREAD

**Issue by grizz** [peeringdb/peeringdb#134]

**Comment by grizz** [comment]
Going to wait for mailman 3.1 migration

**Comment by grizz** [comment]
Waiting on #198

**Comment by job** [comment]
i don't think we need to put time in this

**Comment by grizz** [comment]
@job I agree, was just giving it to you since you had the mailman 3.1 ticket. :)

**Comment by job** [comment]
I find myself not really caring about mailman favicons, I propose we close this
