### ISSUE TITLE
Inconsistent return results when querying facilities by state (Datafill)

### ISSUE THREAD

**Issue by jayhanke** [peeringdb/peeringdb#1343]
fac = pdb.tags.fac
fac_list = fac.all().filter(state='Iowa')

Returns:
https://peeringdb.com/fac/9845, Connect Des Moines, 12
https://peeringdb.com/fac/10411, Bluebird Quad Cities Data Center, 8
https://peeringdb.com/fac/13101, Aureon Downtown, 1

VS
fac_list = fac.all().filter(state='IA')

Returns:
https://peeringdb.com/fac/339, OneNeck Cedar Falls, 3
https://peeringdb.com/fac/3011, Long Lines Secure Data Center, 1
https://peeringdb.com/fac/3127, Enseva Cedar Rapids, 2
https://peeringdb.com/fac/4546, LightEdge Des Moines 1 (DSM1), 8
https://peeringdb.com/fac/4547, LightEdge Des Moines 2 (DSM2), 7
https://peeringdb.com/fac/5804, IP Pathways DSM1, 2
https://peeringdb.com/fac/6480, SFN IA-Emery, 6
https://peeringdb.com/fac/7332, SFN IA-IowaFalls, 3
https://peeringdb.com/fac/7705, SFN IA-Davenport, 16
https://peeringdb.com/fac/7706, SFN IA-Waterloo, 7
https://peeringdb.com/fac/8338, Involta Cedar Rapids,IA, 3
https://peeringdb.com/fac/10791, DartPoints North Liberty, IA, 2
https://peeringdb.com/fac/12304, OneNeck Des Moines, 2
https://peeringdb.com/fac/13256, SFN IA-Urbana, 1

**Comment by martinhannigan** [comment]
On Fri, Mar 10, 2023 at 12:02 PM Matt Griswold ***@***.***>
wrote:

> I am opening a can of worms here, but I thought we had fixed this.
> @ynbrthr <https://github.com/ynbrthr> I'm ready for your response. :)
>
> Let's make this narrow and easy to get it pushed through and fixed.
>
> *Summary*
> Normalize US State names to 2 letter abbreviation.
>
> Big +1 from me.
>
>
+1 and a yan

**Comment by mcmanuss8** [comment]
+1

**Comment by martinhannigan** [comment]
+1

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by grizz** [comment]
**Summary**
We need to enforce state naming on validation and then normalize data.

**Comment by grizz** [comment]
From initial looks, it looks to be a bug/change in melissa, will look at it with #1370

**Comment by vegu** [comment]
While testing locally and an production through the melissa normalization through the user facing UX seems to be working accordingly. States get normalized automatically and the user is prompted to accept further normalization changes if they exist.

However a failure in melissa earlier or down the line could still let unnormalized data through.

Then we identified an additional entry vector for unnormalized State values through django-admin as creating / editing facilties there does not apply any of the normalization logic.

For US, CA, GB and AU we should be able to normalize those to 2 letter codes from static data. This could be done in a command that runs regularly and re-normalizes as needed, with the added benefit of not using any additional melissa credits just on state normalization.

**proposal**

- create a command that normalizes states for US, CA, GB and AU to 2 letter codes from static data without requiring any external APIs

**Comment by leovegoda** [comment]
> **proposal**
> 
> * create a command that normalizes states for US, CA, GB and AU to 2 letter codes from static data without requiring any external APIs

GB addresses do not need a state. While there are both administrative and ceremonial counties they are not [required in addresses](https://personal.help.royalmail.com/app/answers/detail/a_id/81/~/how-to-address-your-mail-%28clear-addressing%29). Using the town name and a postcode makes the address unambiguous. Many large buildings will have their own postcode.

**Comment by martinhannigan** [comment]
That makes sense. It is indeed similiar in the US, “Boston+02109” is unique and some buildings even companies have their own zip e.g. 02109-4444 It is customary in the US to use State abbreviations.



From: Leo Vegoda ***@***.***>
Date: Friday, April 21, 2023 at 11:52 AM
To: peeringdb/peeringdb ***@***.***>
Cc: Martin Hannigan ***@***.***>, Comment ***@***.***>
Subject: Re: [peeringdb/peeringdb] Inconsistent return results when querying facilities by state (Datafill) (Issue #1343)

proposal
·         create a command that normalizes states for US, CA, GB and AU to 2 letter codes from static data without requiring any external APIs

GB addresses do not need a state. While there are both administrative and ceremonial counties they are not required in addresses<https://personal.help.royalmail.com/app/answers/detail/a_id/81/~/how-to-address-your-mail-%28clear-addressing%29>. Using the town name and a postcode makes the address unambiguous. Many large buildings will have their own postcode.

**Comment by grizz** [comment]
> GB addresses do not need a state.

My fault, take GB out of the list then -- or maybe it's just US, CA :)

**Comment by leovegoda** [comment]
> > GB addresses do not need a state.
> 
> My fault, take GB out of the list then -- or maybe it's just US, CA :)

[Australia Post says](https://auspost.com.au/sending/check-sending-guidelines/addressing-guidelines) we need states for Australia, too.

**Comment by arnoldnipper** [comment]
**Summary**

create a command that normalizes states for US, CA, and AU to 2 letter codes from static data without requiring any external APIs

**Comment by ynbrthr** [comment]
what's missing to close that one? also, i believe we should include brazil

**Comment by leovegoda** [comment]
Scheduling this for 2.59.0. I noticed there's a project that could be helpful: https://pypi.org/project/iso3166-2/
