### ISSUE TITLE
add favicon to main site

### ISSUE THREAD

**Issue by grizz** [peeringdb/peeringdb#135]

**Comment by vegu** [comment]
i added the old favicon we had to the main site in commit bfb2f22 - however as that was made from the old logo i figure we might want to replace it with something more recent, so leaving this open for now.

**Comment by mcmanuss8** [comment]
https://beta.peeringdb.com/favicon.ico == 404?

**Comment by grizz** [comment]
It's at https://beta.peeringdb.com/s/favicon.ico - should work in your browser

**Comment by arnoldnipper** [comment]
But it's the wrong logo, isn't it? ... the right one would be this
![12687932_948880115203711_5478681281853501322_n](https://cloud.githubusercontent.com/assets/16888757/24018055/ad3a5c40-0a92-11e7-96a8-abdc1a0826b8.png)
