### ISSUE TITLE
Include carrier and campus objects in the API

### ISSUE THREAD

**Issue by leovegoda** [peeringdb/peeringdb#1352]
**Is your feature request related to a problem? Please describe.**
We should add both the `carrier` and `campus` objects to the main API now that we know there is demand for them.

We were not sure that there would be genuine user demand for these objects, so did not include them in the main API when they were introduced. We now have demonstrated demand and should make these new objects fully equal with older object types.

**Who is affected by the problem?**
API users

**What is the impact?**
API users can properly integrate these new objects into tools.

**Are there security concerns?**
No

**Are there privacy concerns?**
No

**Describe the solution you'd like**
Normalize the new objects in the API

**Do you think this feature will require a formal design?**
Maybe. @grizz ?

**Describe alternatives you've considered**
None

**Could this feature request need support from the Admin Committee?**
No

**What is the proposed priority?**
ASAP

**Provide a rationale for any/all of the above**
As above

**Comment by martinhannigan** [comment]
+1, but not certain about priority which is for later.



From: Leo Vegoda ***@***.***>
Date: Wednesday, March 15, 2023 at 11:16 AM
To: peeringdb/peeringdb ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [peeringdb/peeringdb] Include carrier and campus objects in the API (Issue #1352)

Is your feature request related to a problem? Please describe.
We should add both the carrier and campus objects to the main API now that we know there is demand for them.

We were not sure that there would be genuine user demand for these objects, so did not include them in the main API when they were introduced. We now have demonstrated demand and should make these new objects fully equal with older object types.

Who is affected by the problem?
API users

What is the impact?
API users can properly integrate these new objects into tools.

Are there security concerns?
No

Are there privacy concerns?
No

Describe the solution you'd like
Normalize the new objects in the API

Do you think this feature will require a formal design?
Maybe. @grizz<https://github.com/grizz> ?

Describe alternatives you've considered
None

Could this feature request need support from the Admin Committee?
No

What is the proposed priority?
ASAP

Provide a rationale for any/all of the above
As above

**Comment by mcmanuss8** [comment]
+1 we should do this, they are getting the uptick we hoped they would

**Comment by grizz** [comment]
+1

No formal design required, we can expose from the API in the standard places.

**Comment by arnoldnipper** [comment]
> We should add both the carrier and campus objects to the main API now that we know there is demand for them.

+1 and also the related objects, like `carrierfac`
