### ISSUE TITLE
Updating voltage services options

### ISSUE THREAD

**Issue by martinhannigan** [peeringdb/peeringdb#1353]
**Is your feature request related to a problem? Please describe.**

While not a problem, it's related to a refinement of uncommon service offerings related to three phase voltages in primarily buildings, and data centers.

**Who is affected by the problem?**

If data quality where a person they would be the affected party.

**What is the impact?**

Will continue to improve data relevancy of information contained within PDB.

**Are there security concerns?**

No

**Are there privacy concerns?**

No

**Describe the solution you'd like**

Add 415v and 380v to the voltage service options list.

Remove 120 and 208v from the voltage services options list.

Final list should contain five voltages of 48VDC, 480VAC, 415VAC, 400VAC, and 380VAC. 

**Do you think this feature will require a formal design?**

No

**Describe alternatives you've considered**

Doing nothing, but that would not be a path to data utility improvements.

**Could this feature request need support from the Admin Committee?**

No.

**What is the proposed priority?**

When we can get around to it.

**Provide a rationale for any/all of the above**

Using a higher voltage (like 480VAC) can be more cost-effective option for landlords and tenants when they can take advantage of three phase high voltage offering. This allows for smaller conductors to transmit electricity over longer distances from the utility or building transformer and distribution switchboard, as well as smaller distribution equipment owned by the landlord or tenant e.g. step down. As a result, less indoor space is needed for electrical rooms, creating more flexible options for truck dock loading and tenant door locations. 

The 120/208/230VAC etc are common voltages that meet or exceed 95th % available in data centers globally. There's little need for PDB to highlight the obvious.

**Additional context**

We should consider the take rate on this field and see if its worth continuing with any/high value improvements in the future.

**Comment by arnoldnipper** [comment]
> Final list should contain five voltages of 48VDC, 480v, 415v, 400v, and 380v.

+ 380VDC

**Comment by martinhannigan** [comment]
@peeringdb/pc please ack (I updated voltages to be clear on type voltage alternating current (VAC) vs. volts direct current (VDC).

**Comment by arnoldnipper** [comment]
-1 as still US centric

**Comment by peterhelmenstine** [comment]
Not sure what power has to do with peering.

**Comment by arnoldnipper** [comment]
> Not sure what power has to do with peering.

Power is a feature of a facility. And facilities are keen for interconnection. Adding self-characterization helps networks to chose the facility which suits their needs best. And I agree with you that is questionable in what detail we should allow ix/fac to go. For power, IMO the offering of DC would be enough as every facility is offering AC. And the voltage is basically defined by the country where the facility is in.

**Comment by martinhannigan** [comment]
On Fri, Mar 24, 2023 at 8:09 AM Arnold Nipper ***@***.***>
wrote:

> Not sure what power has to do with peering.
>
> Power is a feature of a facility. And facilities are keen for
> interconnection. Adding self-characterization helps networks to chose the
> facility which suits their needs best. And I agree with you that is
> questionable in what detail we should allow ix/fac to go. For power, IMO
> the offering of DC would be enough as every facility is offering AC. And
> the voltage is basically defined by the country where the facility is in.
>

The voltage listings are about addresses. Facilities can opt to ignore, or
take an advantage and compete. The history of voltage here and agreeing to
include it is about site selection, not standard 208/120 rack availability
which needs no advertising. 480/400/380VAC fall into the -1 portion of a
bell curve which can be interesting. For example, and one I think I’ve used
before, you want 100^2 m or SF in the same building as a major eyeball
which also may have an independent MMR so you can interconnect with the
eyeball and others who are present. The address advertises 480V service
which could mean cheaper service delivery to an independent space which
might then opt to step it down on their own. It allows for site selection
that is independent of a typical retail space while still providing
expanded interconnection opportunities.

As far as -2 curve voltages like 380VDC and adding more? I’m not an expert
in voltage delivered in the middle east or africa. There are some
variations. Rather than try and solve problems that don’t exist, I’d
suggest we wait for someone to come and ask for a country specific voltage
and we can then determine if it’s run of the mill (curve) or -1 or 2. And
engage with a local, knowledgeable, party.

That makes 48VDC an in-curve offering since anyone on the planet can simply
add a rectifier to their rack. I’ve never found a building anywhere that
offers 48VDC to tenants. I have found data center operators who do.

Feels like once v3 is settled and the volume of questions on address
hiearchy is solved, this will become more clear.

Warm regards,

-M<

**Comment by ehohermuth** [comment]
If we extend the peeringDB with more information about the facility we should provide the possibility to select the diffrent world standards which are well documented on wikipedia https://en.wikipedia.org/wiki/Mains_electricity_by_country
At least the eruopean most used standards are currently missing: 1 phase 230V 50Hz, 3 phase 400V 50Hz

**Comment by ehohermuth** [comment]
Hi,I like to summarize - we all agree that the field doesn‘t reflect all countries and of limited use. The solution is indeed trickier:Solution A: We extend the Values to all Variants. + The Community can choose - The Variants and need more workSolution B: We listen only the Exceptions -   + less variants, easy to handle- Confusion ( Community has to check what is common in every country) - Exception within one country could be common in another ?Solution C:We eliminate the field+ no confusion and limitied value- less possibilities for the facilities to diffrentiate and give the community a way to search about their requirementsSolution D:Change the Field to the exact Values a datacenter offers for power:European Example:1 phase 230V 16A 50Hz3 Phase 400V 32A 50Hz48V DC 125A….+ The community can search and filter for theire requirements and the facility can diffrentiate- change of an existing field add complexityOn a greenfield approach I would go for solution D but now I opt for A and add the diffrent voltages on request. Some notes about 230V (220V) and 400V(380V) they are tight together ( diffrence between two phases vs phase and ground). However power supplies usualy have no issues but you gain 5% more power.drehstromBild · 3 KBRegards ErichVon UnterwegsAm 26.06.2023 um 22:31 schrieb Arnold Nipper ***@***.***>:﻿

1 phase 230V 50Hz is common. No need to mention it
3 phase 400V 50Hz is not common at the rack level

**Comment by martinhannigan** [comment]
>1 phase 230V 16A 50Hz3 Phase 400V 32A 50Hz48V DC 125A….+

If these are easy to find common product offerings in a data center economy
this doesn't make sense. I'm also not certain why single phase is relevant
to the discussion for discerning value. One might argue this is a negative.

This started out as a simple way to show a building can offer a high
voltage service directly not requiring to be a customer of a data center
and expanding options. Somehow, this has pivoted to data centers wanting to
show how common they really are. I don't think it adding every single
commonality or (sub par nuances) helps to improve interconnection much.

-1

**Comment by martinhannigan** [comment]
The PC met and decided that we have enough here to proceed. We're going to leave the list as is with previous voltages for now.  We're open to all seeking additional voltage listing, especially those with in-country or region electrical expertise.

**Comment by grizz** [comment]
Closing until we have voltages to add.
