### ISSUE TITLE
IX-F Importer: IX-F Member Data not being nullified after IX stops/changes import

### ISSUE THREAD

**Issue by ccaputo** [peeringdb/peeringdb#1360]
I am seeing a case where an IX has removed their config for an IX-F Import, yet the new code for #1271 is emailing participants and the IX about issues from when an import was previously configured.

@peeringdb/20c, I will email you details about the specific IX.

I think this is a high priority to fix and I have configured "IXF_REMOVE_STALE_NETIXLAN=False" on prod0 in the meantime, so that PeeringDB does not remove valid data.

I think the removal code needs to include safeguards that involve confirmation from a recent IX-F Import, so that a stale prior import is not ever acted upon.

**Comment by ccaputo** [comment]
As part of this fix, I recommend changing the default at https://github.com/peeringdb/peeringdb/blob/baa4f0134fdcbdeb4e4e4c624f4eff53521de773/mainsite/settings/__init__.py#L1056 to False so that only an affirmative .env config enables it.

**Comment by vegu** [comment]
The IX changing the url should naturally cause a cleanup of previous IX-F information on the next importer run. The issue is really when the IX turns the importer off. 

If we remove all IX-F information when the IX turns off the importer we lose track of who was notified about what and all notifications will be sent again once the IX turns it back on again. 

To the original ticket's point - i think the following safeguards make sense:

- check if ix-f import for the ix is currently turned on, skip if it is turned off
- check the date of when the ix-f information that suggests the netixlan removal was last seen in the ix-f data. ignore any that were not seen in the last import run - this is to catch edge cases where the ix has had i turned off for a while, turned it back on and now needs to process current vs old data.

**Comment by arnoldnipper** [comment]
> To the original ticket's point - i think the following safeguards make sense:

Wouldn't it make sense to remove all IX-F information, when the IXP changes the URL (including removing the URL at all)?

**Comment by ccaputo** [comment]
> +1 ... but is this env variable needed anymore? Shouldn't we remove any IX-F import information, if $IXP changes the URL? (To a different one or remove it at all)?

The env variable is needed to be able to disable the importer from taking destructive actions, when bugs like this are discovered. Had we lacked it this round, the code for production would have needed an immediate change.

> check if ix-f import for the ix is currently turned on, skip if it is turned off

This check needs to include both a check of whether import is enabled and whether an import URL is configured.

> check the date of when the ix-f information that suggests the netixlan removal was last seen in the ix-f data. ignore any that were not seen the last time the importer ran - this is to catch edge cases where the ix has had i turned off for a while, turned it back on and now needs to process current vs old data.

Thumbs up to this.

> Wouldn't it make sense to remove all IX-F information, when the IXP changes the URL (including removing the URL at all)?

This is an interesting point and is a bit of a @peeringdb/pc decision. If this were to happen, we could empower an IXP to cause all notifications to be re-sent out, and presumably all hints regarding the IXP to be reset, if the IXP goes approximately a full day with their import disabled (the Importer runs at about 0000 UTC). I could see an argument for empowering an IXP with that ability, but I could also see an argument for that becoming subject to abuse with repeated disablings/enablings causing repeated emails and re-emergence of dismissed hints from PeeringDB. Ie. overloading the disable/enable with this "feature" could enable abuse. Thus I think the greater risk would be that. Thus @vegu's suggestion above reads as safest to me.

@peeringdb/pc (and anyone else reading :-) please advise how this should work, keeping in mind all of the above.

**Comment by arnoldnipper** [comment]
> If this were to happen, we could empower an IXP to cause all notifications to be re-sent out, and presumably all hints regarding the IXP to be reset, if the IXP goes approximately a full day with their import disabled (the Importer runs at about 0000 UTC).

Iff the removal would also cause a cascade of emails. If an IXP removes or changes the URL, information sent so far are useless, IMO.

**Comment by arnoldnipper** [comment]
**Summary**
- check if ix-f import for the ix is currently turned on, skip if it is turned off
- check the date of when the ix-f information that suggests the netixlan removal was last seen in the ix-f data. ignore any that were not seen the last time the importer ran - this is to catch edge cases where the ix has had i turned off for a while, turned it back on and now needs to process current vs old data.

**Comment by peterhelmenstine** [comment]
+1

**Comment by grizz** [comment]
+1

**Comment by Yo-Robinson** [comment]
+1

**Comment by ccaputo** [comment]
On beta with:

```
IXF_REMOVE_STALE_NETIXLAN_NOTIFY_COUNT=3
IXF_REMOVE_STALE_NETIXLAN_NOTIFY_PERIOD=20
IXF_REMOVE_STALE_NETIXLAN_PERIOD=30
IXF_REMOVE_STALE_NETIXLAN=True
```

defined as:

- IXF_REMOVE_STALE_NETIXLAN_NOTIFY_COUNT - number of notifications before countdown to automatic deletion of stale record starts, can be set to 0 to turn off re-notification.

- IXF_REMOVE_STALE_NETIXLAN_NOTIFY_PERIOD - number of days to wait in between repeat notifications
- IXF_REMOVE_STALE_NETIXLAN_PERIOD - days to wait after final notification before automatically removing the stale netixlan
- IXF_REMOVE_STALE_NETIXLAN - global on/off switch for the whole process of stale netixlan notification / removal

I have performed a test run.

From what I can tell, no entries were deleted, which makes sense, since no networks have have multiple notifications yet.

Keeping in mind that beta means emails aren't actually sent out, based on debug output, I estimate that when this first runs on production, about 278 emails will be dispatched to networks that have been previously reminded about stale entries.

I intend to enable this on production after the next production roll-out.

**Comment by ccaputo** [comment]
With:

```
IXF_REMOVE_STALE_NETIXLAN_NOTIFY_COUNT=3
IXF_REMOVE_STALE_NETIXLAN_NOTIFY_PERIOD=20
IXF_REMOVE_STALE_NETIXLAN_PERIOD=30
IXF_REMOVE_STALE_NETIXLAN=True
```

I enabled this on Production today and performed a run. As a result, ~288 emails were dispatched.

~285 with Subject:

  - [prod] [IX-F] PeeringDB: Action May Be Needed: IX-F Importer data mismatch between ASxxxxx and one or more IXPs

~3 with Subject:

  - [prod] [IX-F] PeeringDB: Action May Be Needed: IX-F Importer data mismatch between FooIX and one or more networks

I am performing another run to make sure emails are not duplicated. Will report back if things don't go well.
