### ISSUE TITLE
Add Campus and Carrier Tooltips

### ISSUE THREAD

**Issue by leovegoda** [peeringdb/peeringdb#1361]
**Is your feature request related to a problem? Please describe.**
We have added new `campus` and `carrier` objects. They are prominently visible on the front page and the advanced search page but our definitions are not.
<img width="781" alt="Screenshot 2023-03-27 at 12 51 28" src="https://user-images.githubusercontent.com/59064677/228051578-40c1ad6d-7ee7-42f2-bdc6-95e31ea7b9f5.png">
<img width="516" alt="Screenshot 2023-03-27 at 12 52 28" src="https://user-images.githubusercontent.com/59064677/228051589-b606923e-2279-4978-80c1-34eec6349255.png">

**Who is affected by the problem?**
User who have not memorized our documentation

**What is the impact?**
User will misunderstand what the objects are intended to represent

**Are there security concerns?**
No

**Are there privacy concerns?**
No

**Describe the solution you'd like**
- Add a tooltip noting that a carrier provides L1 and L2 connectivity into a facility.
- Add a tooltip noting that a campus is a group of facilities where inter-building cross-connects are available with the same ease as intra-building cross-connects.

**Do you think this feature will require a formal design?**
No

**Describe alternatives you've considered**
Do nothing

**Could this feature request need support from the Admin Committee?**
No

**What is the proposed priority?**
Soon

**Provide a rationale for any/all of the above**
It helps users

**Comment by martinhannigan** [comment]
Does it make sense use type 1 or type 2 nomenclature?  More focused facility relationship and offering better choices for consumers.

“I am at 123 Main” vs “I can serve at 123 Main” is clearer.



Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: Leo Vegoda ***@***.***>
Sent: Monday, March 27, 2023 3:58:49 PM
To: peeringdb/peeringdb ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [peeringdb/peeringdb] Add Campus and Carrier Tooltips (Issue #1361)


Is your feature request related to a problem? Please describe.
We have added new campus and carrier objects. They are prominently visible on the front page and the advanced search page but our definitions are not.
[Screenshot 2023-03-27 at 12 51 28]<https://user-images.githubusercontent.com/59064677/228051578-40c1ad6d-7ee7-42f2-bdc6-95e31ea7b9f5.png>
[Screenshot 2023-03-27 at 12 52 28]<https://user-images.githubusercontent.com/59064677/228051589-b606923e-2279-4978-80c1-34eec6349255.png>

Who is affected by the problem?
User who have not memorized our documentation

What is the impact?
User will misunderstand what the objects are intended to represent

Are there security concerns?
No

Are there privacy concerns?
No

Describe the solution you'd like

  *   Add a tooltip noting that a carrier provides L1 and L2 connectivity into a facility.
  *   Add a tooltip noting that a campus is a group of facilities where inter-building cross-connects are available with the same ease as intra-building cross-connects.

Do you think this feature will require a formal design?
No

Describe alternatives you've considered
Do nothing

Could this feature request need support from the Admin Committee?
No

What is the proposed priority?
Soon

Provide a rationale for any/all of the above
It helps users

**Comment by grizz** [comment]
+1

**Comment by leovegoda** [comment]
**Summary**
Add tooltips with this text:
- For carrier "Provider of L1 or L2 connectivity into a facility"
- For campus "A set of facilities under one management, with inter-building cross-connects"
