### ISSUE TITLE
Google Analytics for docs.peeringdb.com

### ISSUE THREAD

**Issue by leovegoda** [peeringdb/peeringdb#1363]
**Is your feature request related to a problem? Please describe.**
We missed docs.peeringdb.com when completing https://github.com/peeringdb/peeringdb/issues/1308

We should deploy Google Analytics on docs.peeringdb.com.

**Who is affected by the problem?**
PeeringDB team members

**What is the impact?**
See #1308

**Are there security concerns?**
No

**Are there privacy concerns?**
No

**Describe the solution you'd like**
As above

**Do you think this feature will require a formal design?**
No

**Could this feature request need support from the Admin Committee?**
No

**What is the proposed priority?**
Soon

**Comment by arnoldnipper** [comment]
+1

**Comment by grizz** [comment]
Fixed in https://github.com/peeringdb/docs/pull/275
