### ISSUE TITLE
IX Object Creation Per Policy

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/peeringdb#1364]
**Is your feature request related to a problem? Please describe.**

The AC has too much work. Less DeskPro tickets means more time to spend with family. Or on other DeskPro tickets.

**Who is affected by the problem?**

Users and Admin Committee volunteers.

**What is the impact?**

A faster turn around on IX object creation. Less work for the AC. Immediate use by the community.

**Are there security concerns?**

no

**Are there privacy concerns?**

no

**Describe the solution you'd like**

The IX object creation process is here: https://tinyurl.com/ys6mju3y

**Do you think this feature will require a formal design?**

It's already there

**Describe alternatives you've considered**

**Could this feature request need support from the Admin Committee?**
Consider if an administrator might need to provide assistance at any point.

**What is the proposed priority?**

normal

**Additional context**

![ix-object-approval-process](https://user-images.githubusercontent.com/16888757/228671114-4a3af9e7-2a43-4f71-92e8-19548de472cc.png)

**Comment by martinhannigan** [comment]
-1

This policy creates work and is difficult to automate. It should incorporate a trust component if we really want to reduce work for the AC.

Let’s work on these processes with a goal of using the AC only to address a complaint vs. decide if something is “valid”.



From: Arnold Nipper ***@***.***>
Date: Wednesday, March 29, 2023 at 5:26 PM
To: peeringdb/peeringdb ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [peeringdb/peeringdb] IX Object Creation Per Policy (Issue #1364)

Is your feature request related to a problem? Please describe.

The AC has too much work. Less DeskPro tickets means more time to spend with family. Or on other DeskPro tickets.

Who is affected by the problem?

Users and Admin Committee volunteers.

What is the impact?

A faster turn around on IX object creation. Less work for the AC. Immediate use by the community.

Are there security concerns?

no

Are there privacy concerns?

no

Describe the solution you'd like

The IX object creation process is here: https://tinyurl.com/ys6mju3y

Do you think this feature will require a formal design?

It's already there

Describe alternatives you've considered
A clear and concise description of any alternative solutions or features you've considered.

Could this feature request need support from the Admin Committee?
Consider if an administrator might need to provide assistance at any point.

What is the proposed priority?

normal

Additional context

[ix-object-approval-process]<https://user-images.githubusercontent.com/16888757/228671114-4a3af9e7-2a43-4f71-92e8-19548de472cc.png>

**Comment by arnoldnipper** [comment]
> This policy creates work and is difficult to automate. It should incorporate a trust component if we really want to reduce work for the AC.

This policy is easy to implement. Way easier than that for [facilities](#1185). We already trust the RIR for `net` objects. Now, we would extend this trust LAN prefixes

**Comment by martinhannigan** [comment]
Can you describe a true or false psudeo-code regarding how code would work determining how a user demonstrates a relationship with resources?





From: Arnold Nipper ***@***.***>
Date: Wednesday, March 29, 2023 at 5:26 PM
To: peeringdb/peeringdb ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [peeringdb/peeringdb] IX Object Creation Per Policy (Issue #1364)

Is your feature request related to a problem? Please describe.

The AC has too much work. Less DeskPro tickets means more time to spend with family. Or on other DeskPro tickets.

Who is affected by the problem?

Users and Admin Committee volunteers.

What is the impact?

A faster turn around on IX object creation. Less work for the AC. Immediate use by the community.

Are there security concerns?

no

Are there privacy concerns?

no

Describe the solution you'd like

The IX object creation process is here: https://tinyurl.com/ys6mju3y

Do you think this feature will require a formal design?

It's already there

Describe alternatives you've considered
A clear and concise description of any alternative solutions or features you've considered.

Could this feature request need support from the Admin Committee?
Consider if an administrator might need to provide assistance at any point.

What is the proposed priority?

normal

Additional context

[ix-object-approval-process]<https://user-images.githubusercontent.com/16888757/228671114-4a3af9e7-2a43-4f71-92e8-19548de472cc.png>

**Comment by martinhannigan** [comment]
The policy says “demonstrating” a relationship.

Yet it makes hard requirements:


   - IPv4 prefixes must not be longer than a /27 or shorter than /19
   - IPv6 prefixes must not be shorter than /64 but may be longer i.e. a
   /120 is allowed but a /63 is not


They’re technical requirements. That has nothing to do with demonstrating a
relationship. What’s the psudeo code to confirm the above?

We should take a deep look at all approval policies when they come up for
automation and give them a sanity check so we can have confidence that
we’re truly bumping out real issues.

Thanks Arnold,

-M<

**Comment by peterhelmenstine** [comment]
Seems this all could easily be automated.

**Comment by martinhannigan** [comment]
How many tickets a month does it make go away?



Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by peterhelmenstine** [comment]
Without looking we get at least a couple handfulls per month. Automating this would certainly help.

**Comment by martinhannigan** [comment]
+1

**Comment by vegu** [comment]
closed through https://github.com/peeringdb/peeringdb/pull/1440
