### ISSUE TITLE
White label IXP Feature

### ISSUE THREAD

**Issue by martinhannigan** [peeringdb/peeringdb#1365]
**Is your feature request related to a problem? Please describe.**

When creating an IXP object, ensuring uniqueness is vital. However, mandating the same name in every location is unnecessary. Communities may want to brand the IXP differently in various locations (cities, buildings, data centers) but still share the same fabric and resources. In such cases, we can support "white-labeling", a common technique in many industries. A single IXP fabric space can be marketing by many uniquely, increasing its success and expanding its user base, community, and trust. By offering this capability, we empower communities to tailor the IXP to their unique needs, fostering greater engagement and adoption while conserving technical resources such as IP numbers and support.

**Who is affected by the problem?**

IXP communities and users.

**What is the impact?**

Marketing and success. Not technically impacting on its face.

**Are there security concerns?**

No.

**Are there privacy concerns?**

No.

**Describe the solution you'd like**

To be able to use the same IXP resource records to support a unique object on a per address or facility basis.

**Do you think this feature will require a formal design?**

Yes, it will for certain.

**Describe alternatives you've considered**

Using website or DNS CNAME to point at ixp objects. Feasible, but could create confusion. May also impose security risks. One of the benefits of being able to white label is a reputable approval process within PDB.

Both seem to dilute the value of PDB. Some may feel strongly about white labeling and independence and set up competitive directories. Not particularly useful to anyone.

Doing nothing. No additional value creation for the resources PDB provides.

**Could this feature request need support from the Admin Committee?**

No. The approval process should follow (documented) ~fac; if we have a trusted user submitting the request it should auto-approve. 

Psudeo code:

if trusted_user:
   NOT_require_manual_intervention()
else:
   issue_public_notice()
   start_timer()
   wait_for_response_or_timeout()
   if no_response_or_intervention():
      approve_request()
   else:
      require_manual_intervention()

if is_master_IXP:
   grant_ultimate_approval()

**What is the proposed priority?**

v3

**Provide a rationale for any/all of the above**

A personalized IXP experience for local communities
Improving ability to compete with national, international and commercial IXPs

Example:

100% hypothetical, using local to me placeholders:

Vermont-IX is situated in Burlington, VT.
Montperlier,VT broaband community wants montpelier-ix
Both agree to cooperate and share resources, but provide unique name space
Montpelier gets a local experience
Both gain access to users and shared resources improving efficiencies and potential increasing traffic
Community building relationships and traffic  benefits

Result:  (modified, clearly numbering plans are up to participates and intended to mean umbrella prefix)
Burlington-IX.com located in Burlington, VT and a child of "vermont-ix"
Vermont-IX.com  located in Burlington, VT and the master for resources
Montpelier-IX.com  located in Montpelier, CT and a child of "vermont-ix"
Consolidated-LEC-IX.com  located at the CO in White River Junction, VT and a child of "vermont-ix"

**Additional context**

If we don't do this nothing bad will happen. However, if we want to continue to grow IXP's and provide some level of independence, pride and competition enabling, this could be very useful and help PDB add value.

**Comment by arnoldnipper** [comment]
-1

**Comment by mustangthz** [comment]
I'm not sure this is going to work..... -1

**Comment by martinhannigan** [comment]
Details?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by mcmanuss8** [comment]
> Result:
> Burlington-IX.com (192.0.2.0/24) located in Burlington, VT and a child of "vermont-ix"
> Vermont-IX.com (192.0.2.0/24) located in Burlington, VT and the master for resources
> Montpelier-IX.com (192.0.2.0/24) located in Montpelier, CT and a child of "vermont-ix"
> Consolidated-LEC-IX.com (192.0.2.0/24) located at the CO in White River Junction, VT and a child of "vermont-ix"


To clarify in this example - we'd display to the user 4 different IXes with different names, but there'd by one underlying IX object and 3 children? They'd have the same set of networks and facilities? So if I added my network to one of the children, it would show up in the other 3 too automatically?

**Comment by martinhannigan** [comment]
Netmasks may be a shiny object distraction so adjusted. Example wise perhaps more illustrative. IP addressing would clearly be up to the participants and subject to interoperability.

Vermont-IX 192.0.2.0/24 (Community Umbrella)

  *   Montpelier-IX 192.0.2.0/26
  *   Consolidated-LEC -IX 192.0.2.0/26
  *   Burlington-IX 192.0.2.0/26

If you then wanted to add Jay-IX to the group

Vermont-IX 192.0.2.0/24 (Community Umbrella)

  *   Montpelier-IX 192.0.2.0/26
  *   Consolidated-LEC -IX 192.0.2.0/26
  *   Burlington-IX 192.0.2.0/26
  *   Jay-IX 192.0.2.0/26


The difference between this an extended metro fabric is the label (name). Each one would be able to be it’s own community but share resources and fabric to maximize utilization including POCs, addresses and benefits of autonomy. In the case of my LEC example, Im not saying Consolidated would do anything, but I am saying we might get benefits of a large region ASN (LEC or incument) to participate by allowing them to run their own IX but tie into rest fabric wise. In most smaller states, the LEC has all the fiber and major long haul ASN so will be natural for interconnection benefits. One of the blockers to an IXP running in a CO is regulatory and this may help remove that roadblock.

There are going to be new instances of much smaller IXP communities due to the current mass influx of broadband moneys flowing (see Connected Nation) where utilization will be small, but extremely valuable due to transport and other costs to get to the world and limits of content deployment. So while Leo labeled this marketing in the agenda for meeting, I’d argue it’s not only marketing.

And admittedly, could use more flushing out so firing the -1 gun may be premature.





From: mcmanuss8 ***@***.***>
Date: Wednesday, April 5, 2023 at 4:22 PM
To: peeringdb/peeringdb ***@***.***>
Cc: Martin Hannigan ***@***.***>, Assign ***@***.***>
Subject: Re: [peeringdb/peeringdb] White label IXP Feature (Issue #1365)

Result:
Burlington-IX.com (192.0.2.0/24) located in Burlington, VT and a child of "vermont-ix"
Vermont-IX.com (192.0.2.0/24) located in Burlington, VT and the master for resources
Montpelier-IX.com (192.0.2.0/24) located in Montpelier, CT and a child of "vermont-ix"
Consolidated-LEC-IX.com (192.0.2.0/24) located at the CO in White River Junction, VT and a child of "vermont-ix"

To clarify in this example - we'd display to the user 4 different IXes with different names, but there'd by one underlying IX object and 3 children? They'd have the same set of networks and facilities? So if I added my network to one of the children, it would show up in the other 3 too automatically?

**Comment by mcmanuss8** [comment]
I'm not -1 yet, I generally understand the use case, but I'm still struggling to understand how this would work in practice, especially w.r.t. how it would work for a network joining one of the child IXes. Maybe you could sketch out a diagram of how this would work both from the network perspective and the peeringdb perspective? Like: 

* If I join a child IX, do I show up as a member of all of the IXes? 
* If, as a network, I only want to show up as being in some subset of the IXes, how does that work? 
* Similarly - wow would the ix <-> facility association work? Would adding a facility to one of the ixes apply to the others? 

FYI, I'm going to drop this from the agenda for tomorrow until we have some more details on how this proposal would work, as I worry we'll rathole on it a bit too much. Can talk about it next month since it doesn't seem like this is urgent, either way

**Comment by martinhannigan** [comment]
It is not urgent and agree, punt for a month.

From: mcmanuss8 ***@***.***>
Date: Wednesday, April 5, 2023 at 4:47 PM
To: peeringdb/peeringdb ***@***.***>
Cc: Martin Hannigan ***@***.***>, Assign ***@***.***>
Subject: Re: [peeringdb/peeringdb] White label IXP Feature (Issue #1365)

I'm not -1 yet, I generally understand the use case, but I'm still struggling to understand how this would work in practice, especially w.r.t. how it would work for a network joining one of the child IXes. Maybe you could sketch out a diagram of how this would work both from the network perspective and the peeringdb perspective? Like:
·         If I join a child IX, do I show up as a member of all of the IXes?
·         If, as a network, I only want to show up as being in some subset of the IXes, how does that work?
·         Similarly - wow would the ix <-> facility association work? Would adding a facility to one of the ixes apply to the others?

FYI, I'm going to drop this from the agenda for tomorrow until we have some more details on how this proposal would work, as I worry we'll rathole on it a bit too much. Can talk about it next month since it doesn't seem like this is urgent, either way

**Comment by arnoldnipper** [comment]
For me it sounds as a counterpart to what we have with campus and facilities. That said, what you call children IXes would be real IXes and each of them would have their own prefix. But I guess, that's not hat you had in mind.

**Comment by martinhannigan** [comment]
It isn't really PDB's job to approve of what we are doing. PDB's job should be to help us to figure out how to make the database work for everyone and allow us to complete most effectively.  Yes, we know $country asks for too many fake things. We can't let the people working hard to make the Internet better get drowned by total and complete rigidness. 

**ARIN is more flexible than PDB.**

[](url)
![Screenshot 2023-06-19 at 6 14 21 PM](https://github.com/peeringdb/peeringdb/assets/21081154/5f59d25b-ca85-4fa8-a3ae-de40aee35272)
![Screenshot 2023-06-19 at 6 14 28 PM](https://github.com/peeringdb/peeringdb/assets/21081154/02230b75-8322-4881-904d-435a851b0a12)

**Comment by martinhannigan** [comment]
@peeringdb/pc let's get this one off our agenda either way "paper cuts" at our upcoming meeting. Thanks.

**Comment by peterhelmenstine** [comment]
Couldn't this be accomplished with an Org and IXes under them? If the issue is the need for an ASN for an IX Organization that shouldn't be an issue.

**Comment by martinhannigan** [comment]
I didn’t know an ASN was required for an IXP or an ORG that was associated.



From: Peter Helmenstine ***@***.***>
Date: Tuesday, June 20, 2023 at 12:30 PM
To: peeringdb/peeringdb ***@***.***>
Cc: Martin Hannigan ***@***.***>, Assign ***@***.***>
Subject: Re: [peeringdb/peeringdb] White label IXP Feature (Issue #1365)

Couldn't this be accomplished with an Org and IXes under them? If the issue is the need for an ASN for an IX Organization that shouldn't be an issue.

**Comment by job** [comment]
An IP address block is required for IXPs - not an ASN.

For ISPs an ASNs is required - not an IP address block.

**Comment by peterhelmenstine** [comment]
“Who is affected by the problem?

IXP communities and users.“

Can you clarify this point?

Is there an active case where this is being requested in a way the current system does not support the request? I’m still failing to see why an Org with underlying IXes can’t support such a request.

**Comment by martinhannigan** [comment]
You're in a better position than me to know this. I also think that question is as disengaging as "do you have an ASN?".

**Comment by martinhannigan** [comment]
After a good discussion with the @peeringdb/pc we agreed this was already achievable with current iteration of PDB. That means that the ORG policy part will be referred to the @board and we'll close this. Thanks!

**Comment by martinhannigan** [comment]
Consensus reached by PC to close. Thanks!
