### ISSUE TITLE
Facility data export into Google Earth KMZ

### ISSUE THREAD

**Issue by peterhelmenstine** [peeringdb/peeringdb#1368]
**Is your feature request related to a problem? Please describe.**
A request has been made on Slack's NA-IX PeeringDB facility data visual mapping. One user created a Google Earth KMZ file based on an export of all the facilities with data indicating the IXes, networks and other related data for the facility.

**Who is affected by the problem?**
Peers looking for new places to peer.

**What is the impact?**
Another popular way to access the PeeringDB database in a more visual manor

**Are there security concerns?**
This is already public data. Just a different way of representing the same thing

**Are there privacy concerns?**
This is already public data. Just a different way of representing the same thing

**Describe the solution you'd like**
An export of the PeeringDB facility data into a Google Earth KMZ file that includes the details of the facility fields and it's content (eg: IXes, Networks and carrier objects). Have this KMZ file placed on the website and updated periodically (TBD - daily, hourly?) depending on usage (downloads).

**Do you think this feature will require a formal design?**
I don't believe so.

**Describe alternatives you've considered**
There has been discussion on mapping data based in the search feature on the website. This still needs to be implemented.

**Could this feature request need support from the Admin Committee?**
I don't believe so.

**What is the proposed priority?**
Not urgent but has been requested by a few industry folks. I believe it will be a very popular tool for the industry as people use Google Earth more often.

**Provide a rationale for any/all of the above**
Google Earth is commonly used by a number of Sales Engineers and network buyers for their planning purposes. This would give them an easier method to import this data into a visual tool they commonly use for work.

**Additional context**
This has already been implemented by users in the industry (https://na-ix.slack.com/files/UULPMEWTF/F04LJ8LHJMV/peeringdb-20230127.kml) . It would simply be something we maintain as a periodic export and have on the website.

![image](https://user-images.githubusercontent.com/29210211/230463151-3b7d8f82-8157-49ee-a49f-fdf90aa0e077.png)

**Comment by martinhannigan** [comment]
+1





Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: Peter Helmenstine ***@***.***>
Sent: Thursday, April 6, 2023 12:51:18 PM
To: peeringdb/peeringdb ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [peeringdb/peeringdb] Facility data export into Google Earth KMZ (Issue #1368)


Is your feature request related to a problem? Please describe.
A request has been made for mapping. One user created a Google Earth KMZ file based on an export of all the facilities with data indicating the IXes, networks and other related data for the facility.

Who is affected by the problem?
Peers looking for new places to peer.

What is the impact?
Another popular way to access the PeeringDB database in a more visual manor

Are there security concerns?
This is already public data. Just a different way of representing the same thing

Are there privacy concerns?
This is already public data. Just a different way of representing the same thing

Describe the solution you'd like
An export of the PeeringDB facility data into a Google Earth KMZ file that includes the details of the facility fields and it's content (eg: IXes, Networks and carrier objects). Have this KMZ file placed on the website and updated periodically (TBD - daily, hourly?) depending on usage (downloads).

Do you think this feature will require a formal design?
I don't believe so.

Describe alternatives you've considered
There has been discussion on mapping data based in the search feature on the website. This still needs to be implemented.

Could this feature request need support from the Admin Committee?
I don't believe so.

What is the proposed priority?
Not urgent but has been requested by a few industry folks. I believe it will be a very popular tool for the industry as people use Google Earth more often.

Provide a rationale for any/all of the above
Google Earth is commonly used by a number of Sales Engineers and network buyers for their planning purposes. This would give them an easier method to import this data into a visual tool they commonly use for work.

Additional context
This has already been implemented by users in the industry (https://na-ix.slack.com/files/UULPMEWTF/F04LJ8LHJMV/peeringdb-20230127.kml) . It would simply be something we maintain as a periodic export and have on the website.

**Comment by mcmanuss8** [comment]
+1 on a map view with an export to kmz kind of option. I could see this being on: 

* main page (peeringdb.com/ ) 
* network page (peeringdb.com/net/x )
* search results page (peeringdb.com/search/x )

**Comment by arnoldnipper** [comment]
+1 as well and additionally what @mcmanuss8 suggested

- ix page: where are the networks located
- fac page: where are the carrier/ix/net located

**Comment by grizz** [comment]
@mcmanuss8 We need to refine the scope a bit: map view from google maps or something embedded in the page as well as the kmz export? If so, those should probably be separate issues, and at the very least former will require some UX.

Whole database KMZs should be generated every n interval for caching  (and #1225 happiness).

+1

**Comment by grizz** [comment]
**Summary**
Original feature request:
> An export of the PeeringDB facility data into a Google Earth KMZ file that includes the details of the facility fields and it's content (eg: IXes, Networks and carrier objects). Have this KMZ file placed on the website and updated periodically (TBD - daily, hourly?) depending on usage (downloads).

Exported at least daily, we can probably just fit it in with the new api-cache gen.

---

@mcmanuss8 @arnoldnipper I think its best to make a new issue, this is a very quick to implement standalone request as is, adding things changes the scope drastically
