### ISSUE TITLE
IX participant details to include route-server participation

### ISSUE THREAD

**Issue by peterhelmenstine** [peeringdb/peeringdb#1369]
**Is your feature request related to a problem? Please describe.**

![image](https://user-images.githubusercontent.com/29210211/230450883-6b717c7a-c8dd-4001-a72a-bbc52184d7c4.png)

When looking at IX participants the features of those participants should include route-server participation. This is a common feature on most IX websites. This would help members easily determine if they can reach a peer via a route server or have to reach out directly to peer when reviewing potential peers.

**Who is affected by the problem?**
All networks looking to peer.

**What is the impact?**
This would help facility better peering interactions.

**Are there security concerns?**
None.

**Are there privacy concerns?**
Not that I'm aware of.

**Describe the solution you'd like**
Would like to implement a field where it's a check box saying they are peering with the route-server and have that reflect on the "Peers at this Exchange Point" field similar to speed or policy.

**Do you think this feature will require a formal design?**
Possibly. Not sure how a new field is implemented and reflected on other pages like the participant page.

**Describe alternatives you've considered**
Alternative would be to leave it for the IX operators to list this feature on their own website as some do today.

**Could this feature request need support from the Admin Committee?**
Possibly if there are questions when adding a network to an exchange.

**What is the proposed priority?**
Not urgent.

**Provide a rationale for any/all of the above**
Some IX operators add this feature and field today in their public descriptions. This would help consolidate this information into a single database.

**Additional context**
AMS-IX Bay Area for example:
![image](https://user-images.githubusercontent.com/29210211/230462531-e4c0d0d8-43c2-4d01-a92c-30d7b2830267.png)

**Comment by arnoldnipper** [comment]
@peterhelmenstine, there is this nice icon 
![rs_peer](https://user-images.githubusercontent.com/16888757/233871235-82db37d3-28e3-4ebd-a3c1-ad9d4094603e.png)
 left to the policy.
 
 
![DE-CIX-Frankfurt-PeeringDB](https://user-images.githubusercontent.com/16888757/233871303-f572b343-c247-44b2-b0be-ef29124bf7cf.png)

**Comment by peterhelmenstine** [comment]
Ahh. Great. I'll close this as it's already been implemented.
