### ISSUE TITLE
Add search field to Verification queue

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/peeringdb#137]

**Comment by grizz** [comment]
Due to the way the admin search would need to traverse foreign keys, this will take quite a bit of time

**Comment by arnoldnipper** [comment]
To implement this? Or searching time?

**Comment by grizz** [comment]
to implement it

**Comment by eloos** [comment]
@arnoldnipper is this for the AC?

**Comment by arnoldnipper** [comment]
Yes, @eloos ... as indicated by the label ;-)

**Comment by eloos** [comment]
@arnoldnipper right, so this means that this is not a decision that PC must take. If you believe the impact of this is significant, then let us quote the project and AC decides whether it makes sense

**Comment by arnoldnipper** [comment]
perfect, @eloos ... let's do it this way

**Comment by vegu** [comment]
fixed in 7fe8049
