### ISSUE TITLE
Facility history still broken

### ISSUE THREAD

**Issue by grizz** [peeringdb/peeringdb#1372]
_Originally posted by @arnoldnipper in https://github.com/peeringdb/peeringdb/issues/1096#issuecomment-1500811625_

              This is still broken ... see [this facility history](https://www.peeringdb.com/cp/peeringdb_server/facility/3050/history/)

**Comment by grizz** [comment]
From looking at logs, this is a new error, we're investigating.

**Comment by arnoldnipper** [comment]
Routed through to 3a as identified as a bug by a developer
