### ISSUE TITLE
Search to include new objects: Campus & Carrier

### ISSUE THREAD

**Issue by peterhelmenstine** [peeringdb/peeringdb#1374]
**Is your feature request related to a problem? Please describe.**
When using the basic search the results do not include the new objects campus and carrier. Add them to the results in the basic search

**Who is affected by the problem?**
Users search for campuses and carriers by name

**What is the impact?**
Missing search results

**Are there security concerns?**
no

**Are there privacy concerns?**
no

**Describe the solution you'd like**
Add in new campus and carrier objects into the basic search

**Do you think this feature will require a formal design?**
yes/no (add why if no)
No. Should be similar to the other three pillars: Networks, Exchanges, Facilities, organizations

**Describe alternatives you've considered**
You would have to find them by going to the organization and seeing them listed there.

**Could this feature request need support from the Admin Committee?**
Consider if an administrator might need to provide assistance at any point.
Not that I can see.

**What is the proposed priority?**
simply urgent/not
urgent as it's part of the new feature rollout

**Provide a rationale for any/all of the above**
Why not include all objects to search by name rather than a subset?

**Additional context**
Current search results only include the following:
![image](https://user-images.githubusercontent.com/29210211/231679098-2bc5b4e9-fb34-4872-ab46-b9f07082dfbe.png)

**Comment by martinhannigan** [comment]
+1 of course, but wouldn't this just be part of 1204?

https://github.com/peeringdb/peeringdb/issues/1204

**Comment by mustangthz** [comment]
+1

**Comment by peterhelmenstine** [comment]
@martinhannigan after reading #1204 I believe you're correct.

**Comment by mcmanuss8** [comment]
+1

**Comment by grizz** [comment]
+1

**Comment by martinhannigan** [comment]
Ob. +1

From: mcmanuss8 ***@***.***>
Date: Thursday, May 4, 2023 at 12:25 PM
To: peeringdb/peeringdb ***@***.***>
Cc: Martin Hannigan ***@***.***>, Mention ***@***.***>
Subject: Re: [peeringdb/peeringdb] Search to include new objects: Campus & Carrier (Issue #1374)

+1

**Comment by leovegoda** [comment]
**Summary**
1. Build this new search capability in v2 search
2. Switch the current position of v2 search and the older simple search. This means the search box on the front page will use the v2 search and there will be a link to the older simple search
3. Place a note on the front page with this text "You are using our new search interface. [Click here](https://www.peeringdb.com/search?q=) to use to the old interface. [Click here](https://forms.gle/TYJgvrCGvyTCiaCY8) to provide feedback."
4. Place a note below the older simple search box on its new page with this text "You are using our old simple search interface. [Click here](https://www.peeringdb.com/search/v2?q=) to return to the new interface."
