### ISSUE TITLE
Social Media hyperlinks disappear after edits (cosmetic issue)

### ISSUE THREAD

**Issue by peterhelmenstine** [peeringdb/peeringdb#1375]
**Describe the bug**

After editing and saving new social media entries the hyperlinks links disappear. Reloading the page brings them back.

**To Reproduce**
1. Go to a page that has a social media link to edit
2. Click the edit button
3. Click the save button
4. See missing hyperlinks (only text remains)
5. reload page
6. See hyperlinks return

**Expected behavior**
After saving the hyperlinks should stay

**Who is affected by the problem?**
Users editing the new social media links

**What is the impact?**
Confusion for the user when trying to add their social media links

**Are there security concerns?**
No

**Are there privacy concerns?**
No

**What are the proposed actions?**
Must be a cosmetic bug. Unsure how to fix. Maybe force a reload of the page?

**What is the proposed priority?**
simply urgent/not
Urgent as it relates to a new feature to be released.

**Provide a rationale for any/all of the above**
Folks editing would get confused, frustrated and my simply give up.

**Additional context**
Here's an example of after saving the edits. Text remains but no hyperlink:
![image](https://user-images.githubusercontent.com/29210211/231680743-336e67a5-6e5c-4283-b036-3eb5834c75ec.png)
until after you reload the page:
![image](https://user-images.githubusercontent.com/29210211/231681374-098a4169-3d79-4255-b70e-e2bc363f8704.png)

**Comment by arnoldnipper** [comment]
URL, @peterhelmenstine?

**Comment by peterhelmenstine** [comment]
@arnoldnipper 

Is this what you're referring to? https://beta.peeringdb.com/org/25554

See the social media links, try to edit and then save. Links are gone.

**Comment by arnoldnipper** [comment]
> Is this what you're referring to? https://beta.peeringdb.com/org/25554

As this is still in testing, sending a reply on the mailing list might be more appropriate?

**Comment by grizz** [comment]
We've already been notified and are on it, we didn't realize there was an issue until recently.

Thanks everyone!
