### ISSUE TITLE
Add a "Suggest Carrier" button

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/peeringdb#1376]
**Is your feature request related to a problem? Please describe.**
Add a "Suggest Carrier" button the same way as we have for facilities

**Describe the solution you'd like**
Users are using carriers and would like to add them.

**Do you think this feature will require a formal design?**
no

**Comment by grizz** [comment]
I'm hesitant to add an unmaintained object type to PeeringDB, and don't see a huge reason to add carrier.

How often is this happening? It might be worth discussing with a user or two requesting this to understand their needs more.

**Comment by martinhannigan** [comment]
I can’t line up behind this one. It falls along the lines of why we want to be able to dislodge some. We’re going to load facilities up with resellers which are effectively “fake” carriers.



From: Matt Griswold ***@***.***>
Date: Thursday, May 4, 2023 at 12:49 PM
To: peeringdb/peeringdb ***@***.***>
Cc: Subscribed ***@***.***>
Subject: Re: [peeringdb/peeringdb] Add a "Suggest Carrier" button (Issue #1376)

I'm hesitant to add an unmaintained object type to PeeringDB, and don't see a huge reason to add carrier.

How often is this happening? It might be worth discussing with a user or two requesting this to understand their needs more.

**Comment by arnoldnipper** [comment]
> I'm hesitant to add an unmaintained object type to PeeringDB, and don't see a huge reason to add carrier.

Me, too ... the best way would be to automate the creation of this object as well. From what I remember today on discussing the automated creation of the `fac` object, anyone will be able to kick the creation off.
