### ISSUE TITLE
Reset 'Social Media' to '[]' if field has no value

### ISSUE THREAD

**Issue by netravnen** [peeringdb/peeringdb#1380]
**Describe the bug**

a social media field being `null` causes the page to not be able to be rendered by the frontend

**To Reproduce**
1. Go to any random network in the backend `/cp`
2. Update the social media field, remove any contents from the field (causes the field value to be set to `null`)
3. Save the page
4. access the network in the frontend
5. See error

**Expected behavior**

A HTTP 200 page instead of HTTP 500 internal server error

**Who is affected by the problem?**

users, if the PDB Admin has updated the network information (think new user trying to register a new asn which has been previously assigned, state deleted -> ok, where we typically null all information before reassigning to new ORG)

**What is the impact?**

a `null` causes the page to not be able to be rendered by the frontend

**Are there security concerns?**

none

**Are there privacy concerns?**

none

**What are the proposed actions?**

default the field to `{}` instead of `null` if the field is empty when saving the network information in the backend.

![image](https://user-images.githubusercontent.com/1938389/234230808-8f5daeec-a4e9-4fe7-8b1a-cf418d156c0d.png)

**What is the proposed priority?**

low

**Provide a rationale for any/all of the above**

none

**Additional context**

none

**Comment by netravnen** [comment]
`[]` (list) is incorrect, IMO. `{}` (dictionary) is the correct one.

**Comment by arnoldnipper** [comment]
```json
 "social_media": [
    {
      "service": "twitter",
      "identifier": "DECIX"
    },
    {
      "service": "facebook",
      "identifier": "DECIX.Internet.Exchange"
    },
    {
      "service": "instagram",
      "identifier": "decix.connect"
    },
    {
      "service": "website",
      "identifier": "https://www.de-cix.net"
    }
  ]
```
Hence, if there are no social media, it should read

```json
 "social_media": [
  ]
```
But, IANAP
