### ISSUE TITLE
Add hover tip to describe meaning of routeserver icon

### ISSUE THREAD

**Issue by leovegoda** [peeringdb/peeringdb#1381]
**Is your feature request related to a problem? Please describe.**
[#1369](https://github.com/peeringdb/peeringdb/issues/1369) suggests the meaning of the routeserver icon in the Policy column in the Peers at this Exchange Point table is not obvious. We should add a tooltip to explain the meaning of the icon and other values.

![230450883-6b717c7a-c8dd-4001-a72a-bbc52184d7c4](https://user-images.githubusercontent.com/59064677/234302749-5f26a591-ce34-4624-b304-0e75009641a9.png)

**Who is affected by the problem?**
PDB web users and networks who peer with the routeserver

**What is the impact?**
Neither the networks who peer with the routeserver nor our web users get the full value of the data published if it is not well understood

**Are there security concerns?**
No

**Are there privacy concerns?**
No

**Describe the solution you'd like**
A tooltip explaining the column values when you mouse over the "Policy" header

**Do you think this feature will require a formal design?**
No

**Describe alternatives you've considered**
Publish a support article. But many users won't know to look for it, making that option less effective.

**Could this feature request need support from the Admin Committee?**
No

**What is the proposed priority?**
Medium

**Provide a rationale for any/all of the above**
Features like the routeserver icon have less value when users don't understand them.

**Comment by martinhannigan** [comment]
Leo, appears general UI standards would place tips on the right vs left. Can we make that adjustment to move this ahead?

Thanks —



Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: Leo Vegoda ***@***.***>
Sent: Tuesday, April 25, 2023 10:20:46 AM
To: peeringdb/peeringdb ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [peeringdb/peeringdb] Add hover tip to describe meaning of routeserver icon (Issue #1381)


Is your feature request related to a problem? Please describe.
#1369<https://github.com/peeringdb/peeringdb/issues/1369> suggests the meaning of the routeserver icon in the Policy column in the Peers at this Exchange Point table is not obvious. We should add a tooltip to explain the meaning of the icon and other values.

[230450883-6b717c7a-c8dd-4001-a72a-bbc52184d7c4]<https://user-images.githubusercontent.com/59064677/234302749-5f26a591-ce34-4624-b304-0e75009641a9.png>

Who is affected by the problem?
PDB web users and networks who peer with the routeserver

What is the impact?
Neither the networks who peer with the routeserver nor our web users get the full value of the data published if it is not well understood

Are there security concerns?
No

Are there privacy concerns?
No

Describe the solution you'd like
A tooltip explaining the column values when you mouse over the "Policy" header

Do you think this feature will require a formal design?
No

Describe alternatives you've considered
Publish a support article. But many users won't know to look for it, making that option less effective.

Could this feature request need support from the Admin Committee?
No

What is the proposed priority?
Medium

Provide a rationale for any/all of the above
Features like the routeserver icon have less value when users don't understand them.

**Comment by mcmanuss8** [comment]
+1

**Comment by grizz** [comment]
+1

**Comment by leovegoda** [comment]
**Summary**
Add a tooltip next to the Policy title "Peering with the routeserver is shown with an icon"
