### ISSUE TITLE
Keep the list of IRR up to date

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/peeringdb#1385]
**Is your feature request related to a problem? Please describe.**
IRRs come and go. Keeping them up to date is crucial

**Who is affected by the problem?**
Valid IRR are not accepted (e.g. IDNIC)

**Describe the solution you'd like**
Keep the list of IRR up to date along https://www.irr.net/docs/list.html

**Do you think this feature will require a formal design?**
no

**Describe alternatives you've considered**

**Comment by mcmanuss8** [comment]
+1

**Comment by grizz** [comment]
+1 to bringing the list up to date with currently operational IRRs, not to excluding IRRs based on their policies.

Quick fix to the list at https://github.com/peeringdb/peeringdb/blob/ef187b7cef7a2e5256fe06ec587892f5c1fd682d/peeringdb_server/inet.py#L20

**Comment by stkonst** [comment]
Hi @arnoldnipper 

Regarding the List of supported IRR databases in peeringDB, please keep in mind that there is an upcoming RIPE policy that aims to restrict the usage of IRR databases for IXP operators who configure Prefix filters on Route Servers. You can find the presentation of the Connect WG in the following URL:
https://ripe86.ripe.net/wp-content/uploads/presentations/109-Proposal_Connect_WG_V1.pdf

Thus, it might make sense to keep the list of supported IRRs frozen for a while in Peering DB until this document finalizes and comes alive.

**Comment by martinhannigan** [comment]
I can't attest to data validity, but they're all answering.

FYi,

-M<

**Comment by leovegoda** [comment]
> Hi @arnoldnipper
> 
> Regarding the List of supported IRR databases in peeringDB, please keep in mind that there is an upcoming RIPE policy that aims to restrict the usage of IRR databases for IXP operators who configure Prefix filters on Route Servers. You can find the presentation of the Connect WG in the following URL: https://ripe86.ripe.net/wp-content/uploads/presentations/109-Proposal_Connect_WG_V1.pdf
> 
> Thus, it might make sense to keep the list of supported IRRs frozen for a while in Peering DB until this document finalizes and comes alive.

This was considered in [yesterday's PC meeting](https://docs.peeringdb.com/committee/product/notes/2023-06-01_Product_Committee_Notes.pdf). The agreement was that PeeringDB should not regulate which IRRs a network may use.
