### ISSUE TITLE
Search is inconsistent

### ISSUE THREAD

**Issue by ccaputo** [peeringdb/peeringdb#1391]
I just observed:

<img width="1091" alt="Screen Shot 2023-06-01 at 12 16 59 PM" src="https://github.com/peeringdb/peeringdb/assets/1417833/b78c5298-310f-424e-a43c-8a94442948fc">

And then a refresh resulting in:

<img width="1084" alt="Screen Shot 2023-06-01 at 12 17 13 PM" src="https://github.com/peeringdb/peeringdb/assets/1417833/0d3f0535-e9e4-44f3-a0f2-13aecfe58b77">

This seems to be a search consistency bug related to #1204.

**Comment by ccaputo** [comment]
Looks like this is with v1 search and not v2 search. @grizz suggests this might be due to the indexer running when it happened. Still a bug. :-)

**Comment by ccaputo** [comment]
> A bug that can be fixed by moving over to the v2 search! :)

Love it. BTW, just noticed the v2 search is much faster.

**Comment by grizz** [comment]
Will be fixed with going to v2 (#1392)

**Comment by martinhannigan** [comment]
+1

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
