### ISSUE TITLE
v2 search failing to find some names

### ISSUE THREAD

**Issue by leovegoda** [peeringdb/peeringdb#1394]
Creating a new issue from Arnold's report in #1392. It could be a problem handling searches that include a hyphen character. Searches for names with hyphens seem to fail but searches for those without hyphens seem to work.

![20230603 PeeringDB 01](https://github.com/peeringdb/peeringdb/assets/16888757/ab6c4ae5-80af-4c3e-a722-eef6c4adb498)

![20230603 PeeringDB 03-1](https://github.com/peeringdb/peeringdb/assets/16888757/32b57075-9609-4498-a9d0-1393e6eba60b)
![20230603 PeeringDB 03-0](https://github.com/peeringdb/peeringdb/assets/16888757/17bdc70b-d408-48ec-91f4-e9a77d5c7d16)
![20230603 PeeringDB 02](https://github.com/peeringdb/peeringdb/assets/16888757/23bd4bd8-e103-4ce9-8c5b-393cf66f4e9d)

_Originally posted by @arnoldnipper in https://github.com/peeringdb/peeringdb/issues/1392#issuecomment-1575205543_

**Comment by arnoldnipper** [comment]
Please note that searches with hyphens do not **generally** fail (Search for "AMS-IX" reveals their networks, at least)

**Comment by leovegoda** [comment]
> Please note that searches with hyphens do not **generally** fail (Search for "AMS-IX" reveals their networks, at least)

Searches for "AMS-IX" work but "ams-ix" do not.

**Comment by arnoldnipper** [comment]
> > Please note that searches with hyphens do not **generally** fail (Search for "AMS-IX" reveals their networks, at least)
> 
> Searches for "AMS-IX" work but "ams-ix" do not.
>

Searches for "AMS-IX" work partially. They only reveal their `net`|works. The `ix` objects and the `org` object are missing

**Comment by martinhannigan** [comment]
I tried this on mobile and desktop and each time I received complete results. I can’t recreate it. MacOS Monterey, Safari.

[ from:


;; ANSWER SECTION:

whoami.akamai.com.   300    IN     CNAME  whoami.akamai.net.

whoami.akamai.net.   61     IN     A      24.24.43.169


at Tue Jun  6 07:30:48 EDT 2023 ]



I also tried it from my mobile iPhone 13 safari. Expected results. Using “v2 Search (Beta)” ]



HTH,



-M<


From: Arnold Nipper ***@***.***>
Date: Tuesday, June 6, 2023 at 2:45 AM
To: peeringdb/peeringdb ***@***.***>
Cc: Subscribed ***@***.***>
Subject: Re: [peeringdb/peeringdb] v2 search failing to find some names (Issue #1394)

Please note that searches with hyphens do not generally fail (Search for "AMS-IX" reveals their networks, at least)

Searches for "AMS-IX" work but "ams-ix" do not.

Searches for "AMS-IX" work partially. They only reveal their net|works. The ix objects and the org object are missing

**Comment by martinhannigan** [comment]
Tried again Tue Jun  6 11:05:23 EDT 2023 from


;; ANSWER SECTION:

whoami.akamai.com.   300    IN     CNAME  whoami.akamai.net.

whoami.akamai.net.   116    IN     A      24.24.43.171

All objects returned as expected in both upper and lower cases. I don’t doubt what you’re seeing. It’s intermittent and probably not browser based.

HTH,

-M<



From: Arnold Nipper ***@***.***>
Date: Tuesday, June 6, 2023 at 2:45 AM
To: peeringdb/peeringdb ***@***.***>
Cc: Subscribed ***@***.***>
Subject: Re: [peeringdb/peeringdb] v2 search failing to find some names (Issue #1394)

Please note that searches with hyphens do not generally fail (Search for "AMS-IX" reveals their networks, at least)

Searches for "AMS-IX" work but "ams-ix" do not.

Searches for "AMS-IX" work partially. They only reveal their net|works. The ix objects and the org object are missing

**Comment by arnoldnipper** [comment]
> All objects returned as expected in both upper and lower cases. I don’t doubt what you’re seeing. It’s intermittent and probably not browser based.

Screen shots?

**Comment by netravnen** [comment]
From what I see. The issue stems from names containing hyphens and case-sensitivity.

- France-IX will return results.
- france-ix will not. <~ Does not match the spelled case by France-IX.

Examples,

https://www.peeringdb.com/search/v2?q=DE-CIX vs https://www.peeringdb.com/search/v2?q=de-cix

https://www.peeringdb.com/search/v2?q=AMS-IX vs https://www.peeringdb.com/search/v2?q=ams-ix

https://www.peeringdb.com/search/v2?q=France-IX vs https://www.peeringdb.com/search/v2?q=france-ix

Screenshots for France-IX vs france-ix

![image](https://github.com/peeringdb/peeringdb/assets/1938389/20d6af10-71a1-4dcf-8667-6006940b5147)

![image](https://github.com/peeringdb/peeringdb/assets/1938389/cb699d38-399d-4e8f-8e8b-16429c030b35)

Screenshots for ams-ix vs AMS-IX

![image](https://github.com/peeringdb/peeringdb/assets/1938389/ae440abe-f7c6-4dae-acbe-9f83a2b30ac7)

![image](https://github.com/peeringdb/peeringdb/assets/1938389/e4dc698f-505f-4f40-865f-02b3be4bd017)

Screenshots for de-cix vs DE-CIX

![image](https://github.com/peeringdb/peeringdb/assets/1938389/eb40876f-51f0-480e-90c3-4034500847da)

![image](https://github.com/peeringdb/peeringdb/assets/1938389/3e5f58dc-61ed-47cb-a3e6-5406dfc435bd)

**Comment by netravnen** [comment]
> Are these findings different from what has been reported on #1392?

Not really. Only adding to the data points.

**Comment by leovegoda** [comment]
**Summary:** the backend database treats a hyphen as a minus. We need to treat that behavior as a bug and develop code that works around this default behavior.
