### ISSUE TITLE
v2 search does not find exchanges

### ISSUE THREAD

**Issue by leovegoda** [peeringdb/peeringdb#1397]
**Describe the bug**
This search: https://www.peeringdb.com/search/v2?q=ix+in+manchester correctly identifies that I want results for Manchester in the UK. But it gives no results despite IXPs run by Equinix and LINX in the city.

**To Reproduce**
1. Go to https://www.peeringdb.com/search/v2?q=ix+in+manchester
2. See the lack of results:
<img width="1557" alt="Screenshot 2023-06-13 at 08 17 10" src="https://github.com/peeringdb/peeringdb/assets/59064677/042f4c6b-3ea7-4e9a-9301-48a48e5bf9bf">

3. Go to https://www.peeringdb.com/search/v2?q=fac+in+machester
4. Click on the links for [Equinix](https://www.peeringdb.com/fac/78) and [Teledata](https://www.peeringdb.com/fac/601) to see that they host [Equinix Manchester](https://www.peeringdb.com/ix/1927) and [LINX Manchester](https://www.peeringdb.com/ix/583).

**Expected behavior**
The search should list both [Equinix Manchester](https://www.peeringdb.com/ix/1927) and [LINX Manchester](https://www.peeringdb.com/ix/583) in the Exchanges column.

**Who is affected by the problem?**
Anyone using v2 search who misses results.

**What is the impact?**
Lower data quality.

**Are there security concerns?**
No

**Are there privacy concerns?**
No

**What are the proposed actions?**

- Ensure that searches for named metro areas check all facilities in the area for exchanges.
- Ensure that searches for named metro areas report all exchanges hosted in facilities in those areas. 

**What is the proposed priority?**
ASAP

**Provide a rationale for any/all of the above**
Users have repeatedly told us that search and data quality are their two highest priorities. While v2 search is currently labelled as a beta service we want to deploy it to production as the main search (see: #1392) as it is both more user friendly and faster. But we can only do this if it provides reliable results.

**Additional context**

**Comment by leovegoda** [comment]
Addendum: @martinhannigan noticed that the spelling of Manchester was wrong in one of the searches. Interestingly, the new search engine understood what I meant rather than what I typed. This is probably a good thing. It also means the search miss is not related to my typo.

**Comment by arnoldnipper** [comment]
Shouldn't we summarize the v2 bug fixing, @leovegoda?

**Comment by martinhannigan** [comment]
+1 on summarizing, there are quite a few repetitive issues.

**Comment by leovegoda** [comment]
Closing as this is fixed as of https://docs.peeringdb.com/release_notes/#release-2520
