### ISSUE TITLE
Replication of Facility Record

### ISSUE THREAD

**Issue by amartins** [peeringdb/peeringdb#1407]
What steps can be implemented to ensure the prevention of duplicate facility records effectively? For instance, let's consider a specific scenario where EdgeUno mistakenly creates a duplicate facility record (fac/13773) that erroneously matches the address of the Equinix SP4 facility (fac/165).

**Who is affected by the problem?**
All PeeringDB users. 

**What is the impact?**
Inaccurate data: Duplicate records can lead to conflicting information, resulting in inaccurate data. This can cause confusion and errors in decision-making processes.

**Are there security concerns?**
Duplicate records can introduce inconsistencies and discrepancies in data.

**Comment by martinhannigan** [comment]
Alessandro, 

Does Equinix entirely own and control the building at Av. Ceci, 1900 - Res. Tambore? It doesn't look like it. However, it does look like EdgeUno is your customer. Is that correct?

Thanks!

**Comment by amartins** [comment]
Hi @martinhannigan, 

Equinix is the rightful owner of the building situated at Av. Ceci, 1900 - Residencial Tamboré. This information is corroborated by [Equinix's Q1 2023 Investor Presentation](https://d1io3yog0oux5.cloudfront.net/_212922e5f1eaebefa245593a2875473a/equinix/db/2160/20762/pdf/Intro+to+Equinix_IR_Presentation+Q1+23+05.08.2023+DIST.pdf) on page number 33, which confirms their ownership of the Equinix SP4 building.

Indeed, EdgeUno is merely a customer, and the facility belongs to Equinix. If all of Equinix's customers were to create new facility records independently, it could potentially result in conflicting information, as I previously mentioned.

The Data Ownership Task Force team should consider this as an excellent topic for a broader discussion. ;-)

**Comment by arnoldnipper** [comment]
> **Are there security concerns?**
> Duplicate records can introduce inconsistencies and discrepancies in data.

I don't agree that this is a security concern.

> What steps can be implemented to ensure the prevention of duplicate facility records effectively?

@peeringdb/ac usually checks for duplicates. However, a match on address is necessary but not sufficient. If you are in doubt, send an email to support@peeringdb.com

For the moment, I don't see a realistic way to check this systematically.

**Comment by martinhannigan** [comment]
Thanks Alessandro. We've had some debates about addresses and your
information is useful. I would imagine now this is clearly an easy support
ticket to the "admin committee".

Warm regards,

-M<

**Comment by arnoldnipper** [comment]
> The Data Ownership Task Force team should consider this as an excellent topic for a broader discussion.

Before discussing this at DOTF, there needs to be a more sound definition what would be considered a facility. We are about of implementing "[Admin Committee Guidelines and Criteria for Approving Networks, IXPs, and Facilities]"(https://docs.peeringdb.com/committee/admin/approval-guidelines). Please check this document to see if the procedure would prevent creation of duplicates. If it doesn't, we should the issue there, first.

**Comment by amartins** [comment]
> Thanks Alessandro. We've had some debates about addresses and your information is useful. I would imagine now this is clearly an easy support ticket to the "admin committee". Warm regards,
> […](#)

Thank you, @martinhannigan. I'll raise a ticket to the AC team.

**Comment by amartins** [comment]
> > The Data Ownership Task Force team should consider this as an excellent topic for a broader discussion.
> 
> Before discussing this at DOTF, there needs to be a more sound definition what would be considered a facility. We are about of implementing ["Admin Committee Guidelines and Criteria for Approving Networks, IXPs, and Facilities"](https://docs.peeringdb.com/committee/admin/approval-guidelines). Please check this document to see if the procedure would prevent creation of duplicates. If it doesn't, we should the issue there, first.

Hey @arnoldnipper, I believe there is an essential validation mechanism missing in the document that you outlined. This mechanism involves referencing valid official records and legal documentation, such as Title Deeds, Land Registry documents, Property Tax Records, and any relevant public records, which I shared previously. Make sense? ;-) 

By the way, could you please let me know when PeeringDB intend to implement the new guidelines?

**Comment by peterhelmenstine** [comment]
We have debated what a 'facility' is for the past few years and most are in favor of a less limiting definition. Something more vague such as a place where 2-3 networks can come together and peer and that could live within a facility within a facility within a facility (eg: Building, Suite, colo company, customer cabinet, etc. So in the case EdgeUno could have the same address if they are offering colo services to the public.

**Comment by martinhannigan** [comment]
It should definitely be less restrictive. It’s a balance. Until we solve address subordination it’s hard to be able to true of false a new FAC in my opinion until then. Like 60 Hudson appearing to have a direct relationship with DE-CIX. The EU < > Equinix question appears to be straight colo. Perhaps as PDB matures more a POP object would help to continue to make it clear to consumers what a presence actually means?

This is going to require more work in order to be right – and fully automatable. And to avoid liabilities.





From: Peter Helmenstine ***@***.***>
Date: Monday, July 3, 2023 at 6:00 PM
To: peeringdb/peeringdb ***@***.***>
Cc: Martin Hannigan ***@***.***>, Mention ***@***.***>
Subject: Re: [peeringdb/peeringdb] Replication of Facility Record (Issue #1407)

We have debated what a 'facility' is for the past few years and most are in favor of a less limiting definition. Something more vague such as a place where 2-3 networks can come together and peer and that could live within a facility within a facility within a facility (eg: Building, Suite, colo company, customer cabinet, etc. So in the case EdgeUno could have the same address if they are offering colo services to the public.

**Comment by martinhannigan** [comment]
OTOH, we’ve also allowed much:

https://www.peeringdb.com/search?q=EdgeUno

I think in a perfect world we’d do nothing but clearly identify that a rightful owner is in control of the address and is the only one who can approve of a direct relationship.

Honestly, after seeing this? I’m not certain what to think. Seems like our fault nomenclature wise.




From: Peter Helmenstine ***@***.***>
Date: Monday, July 3, 2023 at 6:00 PM
To: peeringdb/peeringdb ***@***.***>
Cc: Martin Hannigan ***@***.***>, Mention ***@***.***>
Subject: Re: [peeringdb/peeringdb] Replication of Facility Record (Issue #1407)

We have debated what a 'facility' is for the past few years and most are in favor of a less limiting definition. Something more vague such as a place where 2-3 networks can come together and peer and that could live within a facility within a facility within a facility (eg: Building, Suite, colo company, customer cabinet, etc. So in the case EdgeUno could have the same address if they are offering colo services to the public.

**Comment by peterhelmenstine** [comment]
A counter argument would be your 60 Hudson example. The owners of the building address don't care what goes on in their building in regards to peering 'facilities' or they would have shown up by now. Getting them to approve a direct relationship is even more more limiting. Isn't that what we're trying to prevent?

If there's space where 2-3 networks can interconnect then that's a facility and an address can have unlimited facilities imo.

**Comment by amartins** [comment]
Both of you have made excellent points, and I completely agree with you, @peterhelmenstine. However, I believe that the suggestion made by @martinhannigan  regarding the POP record will effectively address the gap we are facing. 

Going back to my initial point, happy to discuss how we can guarantee the accuracy of PeeringDB data and effectively eliminate any form of duplicates. ;-)

**Comment by martinhannigan** [comment]
Inline

From: Peter Helmenstine ***@***.******@***.***>
Date: Monday, July 3, 2023 at 6:48 PM
To: peeringdb/peeringdb ***@***.******@***.***>
Cc: Martin Hannigan ***@***.******@***.***>, Mention ***@***.******@***.***>
Subject: Re: [peeringdb/peeringdb] Replication of Facility Record (Issue #1407)

A counter argument would be your 60 Hudson example. The owners of the building address don't care what goes on in their building in regards to peering 'facilities' or they would have shown up by now. Getting them to approve a direct relationship is even more more limiting. Isn't that what we're trying to prevent?



Shouldn’t  peeringdb be a good steward for building owners as well as networks who it impacts?

If there's space where 2-3 networks can interconnect then that's a facility and an address can have unlimited facilities imo.

Let’s not get distracted.

One solution could be Equinix creating a fac object for their address and then nest their data center fac object under it. That might accomplish a clear recognition of ownership.

Warm regards,

-M<

**Comment by arnoldnipper** [comment]
> I believe that the suggestion made by @martinhannigan regarding the POP record will effectively address the gap we are facing.

KISS ... another object doesn't resolve anything. We already have the field `property` where you can indicate what the relationship is.

**Comment by amartins** [comment]
> KISS ... another object doesn't resolve anything. We already have the field `property` where you can indicate what the relationship is.

I understand your perspective, but it seems that the inclusion of the `property` field does not effectively address or eliminate the issue of duplicates. :-)

**Comment by arnoldnipper** [comment]
> understand your perspective, but it seems that the inclusion of the `property` field does not effectively address or eliminate the issue of duplicates. :-)

Nor would a new object ;-)

**Comment by peterhelmenstine** [comment]
I think a simple e-mail to support@peeringdb.com should suffice for data clean up for potential duplicates. In this case with EdgeUno being a customer of Equinix that would not apply as a duplicate as it meets the facility definition.

**Comment by martinhannigan** [comment]
Agree, but the current approach keeps it complicated and ignores how the business works. It should align.

I look forward to working to help improve object clarity and neutrality.



Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by amartins** [comment]
> I think a simple e-mail to [support@peeringdb.com](mailto:support@peeringdb.com) should suffice for data clean up for potential duplicates. In this case with EdgeUno being a customer of Equinix that would not apply as a duplicate as it meets the facility definition.

In the [AC Guidelines document](https://docs.peeringdb.com/committee/admin/approval-guidelines/), a `facility` is defined as a physical location where two or more IP Networks or Internet Exchange Points (IXPs) interconnect with each other. This definition focuses on the interconnection aspect of facilities. The key criterion for approving Facility objects is to verify their existence through confirmation from multiple existing PeeringDB users.

Additionally, as stated in the [DO Policy](https://docs.peeringdb.com/gov/misc/2020-04-06_PeeringDB_Data_Ownership_Policy_Document_v1.0.pdf), PeeringDB uses the term `facility` to record data centers that serve as public centralized locations where computing and networking equipment of tenants are situated. These facilities may include one or more meet-me-rooms. A Facility in PeeringDB's context can refer to either a data center or a public meet-me-room used for interconnection. Within PeeringDB, Facilities can accommodate IXs and Networks, allowing these entities to establish interconnections.

Based on the information above, could you please indicate the category under which the facility record fac/13773 falls?

**Comment by martinhannigan** [comment]
From: Alessandro Martins ***@***.***>
Date: Wednesday, July 5, 2023 at 7:15 AM
To: peeringdb/peeringdb ***@***.***>
Cc: Martin Hannigan ***@***.***>, Mention ***@***.***>
Subject: Re: [peeringdb/peeringdb] Replication of Facility Record (Issue #1407)

I think a simple e-mail to ***@***.******@***.***> should suffice for data clean up for potential duplicates. In this case with EdgeUno being a customer of Equinix that would not apply as a duplicate as it meets the facility definition.

In the AC Guidelines document<https://docs.peeringdb.com/committee/admin/approval-guidelines/>, a facility is defined as a physical location where two or more IP Networks or Internet Exchange Points (IXPs) interconnect with each other. This definition focuses on the interconnection aspect of facilities. The key criterion for approving Facility objects is to verify their existence through confirmation from multiple existing PeeringDB users.

Additionally, as stated in the DO Policy<https://docs.peeringdb.com/gov/misc/2020-04-06_PeeringDB_Data_Ownership_Policy_Document_v1.0.pdf>, PeeringDB uses the term facility to record data centers that serve as public centralized locations where computing and networking equipment of tenants are situated. These facilities may include one or more meet-me-rooms. A Facility in PeeringDB's context can refer to either a data center or a public meet-me-room used for interconnection. Within PeeringDB, Facilities can accommodate IXs and Networks, allowing these entities to establish interconnections.

Based on the information above, could you please indicate the category under which the facility record fac/13773 falls?



https://docs.peeringdb.com/committee/admin/approval-guidelines/

“A facility without networks or IXPs is considered potential “junk”.

**Comment by peterhelmenstine** [comment]
Probably the second one.

Agree we do t want junk but the facility entry was only created 22 days ago and will likely populate with networks. There is a bit of ‘chicken & egg’ that needs to happen first. Aren’t we trying to be less restrictive here? 

Maybe we can put a time limit from the creation of the facility with no networks.

**Comment by arnoldnipper** [comment]
> Maybe we can put a time limit from the creation of the facility with no networks.

fyi: 22.6% of the 5193 facilities neither have a network or ix

**Comment by martinhannigan** [comment]
It's interesting that the FAC object has more than one definition.

**Comment by peterhelmenstine** [comment]
Hmm... 22.6% is much higher than I expected. Unsure how I feel about that. Wouldn't want to remove an empty facility a day before someone wants to add their network.

Agree the AC Guidline and DO policies should be synced.

**Comment by arnoldnipper** [comment]
> Hmm... 22.6% is much higher than I expected. Unsure how I feel about that. Wouldn't want to remove an empty facility a day before someone wants to add their network.

Is there any reason we want to remove empty facilities/ixes? IMO, it makes our life much more complicated.

**Comment by peterhelmenstine** [comment]
Looks like some would call it 'junk' while others would find them to be potential peering opportunities. If it's not hurting anyone...

**Comment by arnoldnipper** [comment]
> Looks like some would call it 'junk' while others would find them to be potential peering opportunities. If it's not hurting anyone...

I don't see an easy way to detect whether an `ix` or `fac` is abandoned or even never existed. Hence, my recommendation is to leave it as it is. When @peeringdb/ac gets notified about a non-existing `ix` or `fac`, they will look into it.

**Comment by peterhelmenstine** [comment]
Agreed the solution for now would be to simply e-mail support.

**Comment by grizz** [comment]
This is resolved by emailing support.

For the policy updates, this will be best accomplished with the address object changes for v3 (#625)
