### ISSUE TITLE
Adjust IPv4/6 prefix limits automatically

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/peeringdb#1410]
**Is your feature request related to a problem? Please describe.**
IPv4/6 prefix limits are used to protect bgp sessions. However, as the Internet is growing prefix-wise, this is not a fix number

**Who is affected by the problem?**
every network

**What is the impact?**
For now,  IPv4/6 prefix limits have to be adjusted manually. Currently, the request is to set IPv6 prefix limit to 200k

**Are there security concerns?**
no

**Are there privacy concerns?**
no

**Describe the solution you'd like**
Reguarly check the size of the IPv4/IPv6 table and adjust  the IPv4/6 prefix limits accordingly

**Do you think this feature will require a formal design?**
No, as the size of the IPv4/6 tables can be retrieved from trusted sources and the IPv4/6 prefix limits can be calculated accordingly

**What is the proposed priority?**
normal

**Comment by leovegoda** [comment]
Christian Teuschel and I recently discussed using RIPEStat's API to help us inform users about the difference between what the network has set in PeeringDB as a maximum prefix limit and what is seen from RIPE NCC's observation points. This could either help someone communicate a more accurate maximum prefix limit in PeeringDB or fix a routing problem.

**Comment by arnoldnipper** [comment]
> Christian Teuschel and I recently discussed using RIPEStat's API to help us inform users about the difference between what the network has set in PeeringDB as a maximum prefix limit and what is seen from RIPE NCC's observation points. This could either help someone communicate a more accurate maximum prefix limit in PeeringDB or fix a routing problem.

IMO, this is a service RIPEStat could offer. I don't see that we incorporate this in PeeringDB, as we then would need do the same for all the others.

**Comment by job** [comment]
The IPv6 CIDR Report suggests that the current IPv6 table is 190,000 https://www.cidr-report.org/v6/as2.0/

On my personal router (which takes a feed from the NLNOG RING LG) is at 231,226 ... so it seems somewhat unlikely to me that someone is sending 200,000 on a *peering* link.

I think the limit should be a double digit percentage (20-25%?) below the 'full' routing table to help avoid people making maximum prefix limits somewhat useless. I imagine its easy to type in a 0 too many when entering information in this field, so a safe guard of sorts seems beneficial

**Comment by arnoldnipper** [comment]
> so it seems somewhat unlikely to me that someone is sending 200,000 on a _peering_ link.

What about Route Servers? Does the same logic apply to them?

**Comment by job** [comment]
> > so it seems somewhat unlikely to me that someone is sending 200,000 on a _peering_ link.
> 
> What about Route Servers? Does the same logic apply to them?

I believe so, yes. Route Servers don’t distribute full routing tables.

**Comment by grizz** [comment]
Automating this at the time of deploy from RIPEStat or cidr report seems like a good idea, I thought we had an issue for that once upon a time?

I agree with Job that it should be a percentage of the current table size, I'd say 25% or even a little more but it sounds like we can agree on 25%

**Comment by arnoldnipper** [comment]
> I agree with Job that it should be a percentage of the current table size, I'd say 25% or even a little more but it sounds like we can agree on 25%

My understanding of Job's proposal was that it should be **75%** of the current table size, not **25%**

**Comment by arnoldnipper** [comment]
> I believe so, yes. Route Servers don’t distribute full routing tables.

Route Servers may have a lot of partly disjunctive RS peers, so that the total amounts to full size, almost. At least, that's what my memory serves me.

**Comment by grizz** [comment]
> My understanding of Job's proposal was that it should be **75%** of the current table size, not **25%**

Corrected.

**Comment by mcmanuss8** [comment]
+1

**Comment by grizz** [comment]
+1

**Comment by martinhannigan** [comment]
+1

**Comment by grizz** [comment]
**Summary**

Script to update the ansible variables from a source, probably RIPEstat, to be 25% of global DFZ.

**Comment by job** [comment]
> **Summary**
> 
> Script to update the ansible variables from a source, probably RIPEstat, to be 25% of global DFZ.

This should be 75% … as per https://github.com/peeringdb/peeringdb/issues/1410#issuecomment-1627394674 right?

**Comment by grizz** [comment]
@job haha, it would be nice if I was thinking about in terms of total instead of below. Yes, it's set to 75% of global DFZ, currently is at:

```
DATA_QUALITY_MAX_PREFIX_V4_LIMIT=707273
DATA_QUALITY_MAX_PREFIX_V6_LIMIT=152296
```
