### ISSUE TITLE
Manual IX-F import request queue can get stuck

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/peeringdb#1413]
**Describe the bug**
It is possible for an internet exchange admin to trigger manual IX-F import requests without having their import url set. If enough exchanges do this it will cause the queue to get stuck at which point ops needs to clear it out for manual ix-f imports to get processed again.

For details see #1182 

@ccaputo requested urgent bug fix

**Comment by ccaputo** [comment]
Is this not a dup?
