### ISSUE TITLE
Tooltip with Full IX Name on Mouse-Over IX-Abbreviation

### ISSUE THREAD

**Issue by klaus-nicat** [peeringdb/peeringdb#1414]
**Is your feature request related to a problem? Please describe.**
I love and use peeringdb. But I stll do not know all the abbreviations of IXs by heart. For example I just looked up https://www.peeringdb.com/asn/7195 and in the section "Public Peering Exchange Points" I see "GTIX". I wonder where GTIX is. Now I have to click on the Link to see where that IX is. But I would like to stay on the current page.

**Who is affected by the problem?**
Maybe other users too.

**What is the impact?**
Less clicking around

**Are there security concerns?**
No

**Are there privacy concerns?**
No

**Describe the solution you'd like**
Hence, a mouse-over tooltip would be nice if the mouse moves over "GTIX", for example showing the IX "Long Name", ie "Guatemala Internet Traffic Exchange Point".

**Do you think this feature will require a formal design?**
I do not know

**Describe alternatives you've considered**
None

**Could this feature request need support from the Admin Committee?**
I do not know

**What is the proposed priority?**
low, but easy to implement I guess

**Provide a rationale for any/all of the above**
I do not know

**Additional context**
![grafik](https://github.com/peeringdb/peeringdb/assets/67467112/80a326dd-0253-4416-bdb1-a326ce1bf216)

**Comment by martinhannigan** [comment]
It may be worth considering if “long name” can be used for this as the db reference for the TT.





Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: klaus-nicat ***@***.***>
Sent: Friday, July 21, 2023 4:31:44 PM
To: peeringdb/peeringdb ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [peeringdb/peeringdb] Tooltip with Full IX Name on Mouse-Over IX-Abbreviation (Issue #1414)


Is your feature request related to a problem? Please describe.
I love and use peeringdb. But I stll do not know all the abbreviations of IXs by heart. For example I just looked up https://www.peeringdb.com/asn/7195 and in the section "Public Peering Exchange Points" I see "GTIX". I wonder where GTIX is. Now I have to click on the Link to see where that IX is. But I would like to stay on the current page.

Who is affected by the problem?
Maybe other users too.

What is the impact?
Less clicking around

Are there security concerns?
No

Are there privacy concerns?
No

Describe the solution you'd like
Hence, a mouse-over tooltip would be nice if the mouse moves over "GTIX", for example showing the IX "Long Name", ie "Guatemala Internet Traffic Exchange Point".

Do you think this feature will require a formal design?
I do not know

Describe alternatives you've considered
None

Could this feature request need support from the Admin Committee?
I do not know

What is the proposed priority?
low, but easy to implement I guess

Provide a rationale for any/all of the above
I do not know

Additional context
[grafik]<https://user-images.githubusercontent.com/67467112/255278529-80a326dd-0253-4416-bdb1-a326ce1bf216.png>

**Comment by leovegoda** [comment]
Our UX designer will be developing approaches to address this use case in to the new website design

**Comment by grizz** [comment]
+1

**Comment by mcmanuss8** [comment]
+1

**Comment by martinhannigan** [comment]
+1

**Comment by grizz** [comment]
@leovegoda I think this will just get done with the new UX, correct?

**Comment by leovegoda** [comment]
> @leovegoda I think this will just get done with the new UX, correct?

This is in the design for the new web UX. It might be more efficient to do a whole bunch of UX work in one go.

**Comment by martinhannigan** [comment]
Sweet. Maps to long name. I can see many alternative uses for it when an object or its record support is lacking!
