### ISSUE TITLE
Auto-CleanUp old pending "User to Organization Affiliation Request"

### ISSUE THREAD

**Issue by netravnen** [peeringdb/peeringdb#1415]
**Is your feature request related to a problem? Please describe.**

From a recent mail thread concerning DeskPro ticket #89987. It became clear that it would be beneficial to auto-cleanup old pending affiliation requests.

**Who is affected by the problem?**

None in particular.

**What is the impact?**

Do not store old stale data.

**Are there security concerns?**

None

**Are there privacy concerns?**

None

**Describe the solution you'd like**

@ccaputo suggested this.

Clearing out non-approved old pending affiliation requests. 2 months was suggested. I am in favour of 3 months. But either period can work, IMO.

_When_ the stale affiliation requests are automatically deleted. Generate an E-mail to both the organization Admin(s) and the user, informing them the affiliation request was automatically deleted. Due to not having been approved within [insert timeframe].

**Do you think this feature will require a formal design?**

Yes

**Describe alternatives you've considered**

None

**Could this feature request need support from the Admin Committee?**

IMO, no.

**What is the proposed priority?**

Low?

**Provide a rationale for any/all of the above**

None

**Additional context**

None

**Comment by grizz** [comment]
+1 makes sense to me

**Comment by martinhannigan** [comment]
We don’t know what Deskpro ticket #89987 is. Why does it need to be cleaned up?

Thanks!

-M<



From: ch ***@***.***>
Date: Monday, July 24, 2023 at 2:01 PM
To: peeringdb/peeringdb ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [peeringdb/peeringdb] Auto-CleanUp old pending "User to Organization Affiliation Request" (Issue #1415)

Is your feature request related to a problem? Please describe.

From a recent mail thread concerning DeskPro ticket #89987. It became clear that it would be beneficial to auto-cleanup old pending affiliation requests.

Who is affected by the problem?

None in particular.

What is the impact?

Do not store old stale data.

Are there security concerns?

None

Are there privacy concerns?

Describe the solution you'd like
A clear and concise description of what you want to happen.

Do you think this feature will require a formal design?
yes/no (add why if no)

Describe alternatives you've considered
A clear and concise description of any alternative solutions or features you've considered.

Could this feature request need support from the Admin Committee?
Consider if an administrator might need to provide assistance at any point.

What is the proposed priority?
simply urgent/not

Provide a rationale for any/all of the above

Additional context
Add any other context or screenshots about the feature request here.

**Comment by ccaputo** [comment]
> We don’t know what Deskpro ticket #89987 is. Why does it need to be cleaned up? Thanks!

The  Deskpro ticket had to do with a user's confusion about a PeeringDB Admin cleaning up an old affiliation request. One ticket resulting from that confusion is #1416 to make clear when it is a PeeringDB Admin who performs an intervention pertaining to an affiliation request, while this issue #1415 has to do with simply auto-purging old unhandled requests since at some point it is arguably good security hygiene, so there is less risk of an accidental affiliation approval.

**Comment by elgaeloHub** [comment]
I think this is a sensible feature to implement.

**Comment by arnoldnipper** [comment]
+1

**Comment by Juimar** [comment]
+ 1

**Comment by martinhannigan** [comment]
Is there a policy process that this is part of?

-1 for now.

**Comment by arnoldnipper** [comment]
> Is there a policy process that this is part of?

This would be along the lines of what we already do with pending requests for registrations. They are automatically removed after 90 days. To keep the system clean, we should do the same with pending requests for affiliation.

**Comment by grizz** [comment]
+1

**Comment by mcmanuss8** [comment]
+1, but notify the user when we clean it up versus doing it silently

**Comment by martinhannigan** [comment]
+1

**Comment by vegu** [comment]
**Summary**

- Implement django management command that deletes old affiliation requests, to be run on a schedule via cron
- default time to 3 months but allow overriding via settings variable and command flag
- upon deletion send emails to organization admins and the affiliating user and inform them the affiliation request was automatically deleted due to not having been approved within in the specified time frame

**Comment by Juimar** [comment]
+1
