### ISSUE TITLE
Add (PeeringDB Support) after superuser name in public notifications

### ISSUE THREAD

**Issue by netravnen** [peeringdb/peeringdb#1416]
**Is your feature request related to a problem? Please describe.**

Make it more clear to PeeringDB users. Whenever a PeeringDB superuser makes a change that generates a public notification to PeeringDB users.

**Who is affected by the problem?**

@peeringdb/ac (PeeringDB users raise tickets)

PeeringDB users, who are confused about what is happening. If the name in the public notification is not from within their own organization.

**What is the impact?**

Increased clarity

**Are there security concerns?**

None

**Are there privacy concerns?**

Only as far as which information about the superuser is included in the public notification.

This will not change. If it is only the name that is included, as is the situation today.

**Describe the solution you'd like**

When a superuser (e.g. @peeringdb/ac) makes a change that generate a public notification to PeeringDB users that _also_ includes the superuser's name. Include "[insert superuser name] (PeeringDB Support)"

**Do you think this feature will require a formal design?**

No.

Only make it clearer it is PeeringDB staff making the change by tagging on `(PeeringDB Support)` after the superuser name.

**Describe alternatives you've considered**

None

**Could this feature request need support from the Admin Committee?**

Unsure

**What is the proposed priority?**

Low

**Provide a rationale for any/all of the above**

None

**Additional context**

<img width="1072" alt="image" src="https://github.com/peeringdb/peeringdb/assets/1938389/5c990125-7141-4894-9ef0-8063bb93e91a">

**Comment by peterhelmenstine** [comment]
To clarify this isn't necessarily a public notification but an e-mail to a user requesting an affiliation? Am I understanding that right?

If this is simply to put a name of the AC member to an existing process then I don't see a problem with that.

+1

**Comment by martinhannigan** [comment]
+1 generic name is good enough.



Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by netravnen** [comment]
grizz,

> It seems like PeeringDB support should be fine, we have internal records of who did what in the case of any complaints, etc.

Question: The /cp does NOT show which user_id denied an affiliation
request. [0] Is this information stored in the database. And "just"
not shown in the backend view?

[0]: https://www.peeringdb.com/cp/peeringdb_server/userorgaffiliationrequest/
-> Open any (recent) "denied" affiliate request to see what I
describe.

**Comment by netravnen** [comment]
The **summary** is then instead of showing the superuser name. We replace superuser name with generic "PeeringDB Support" :thinking:

**Comment by grizz** [comment]
> Question: The /cp does NOT show which user_id denied an affiliation request. [0] Is this information stored in the database. And "just" not shown in the backend view?

I believe so, let's add that to the issue and we'll update that if needed as well (which may bump this to a minor).
