### ISSUE TITLE
replace missing Glyphicons

### ISSUE THREAD

**Issue by leovegoda** [peeringdb/peeringdb#1419]
**Describe the bug**
The Glyphicons Halflings font was free to use as a part of Bootstrap 3 but was dropped as a part of Bootstrap 4. 

Without this license, icons like the alphabetical sort indicator do not display correctly. It looks like this:

<img width="279" alt="Screenshot 2023-07-27 at 11 42 02" src="https://github.com/peeringdb/peeringdb/assets/59064677/dc4f21a5-aa51-4ec4-a520-3e10f154d01c">

But should have a glyph like this:

![image](https://github.com/peeringdb/peeringdb/assets/59064677/3f69365c-d2cb-4da9-8589-4e844a50e8f6)

**To Reproduce**
The problem is not immediately visible to anyone with the font installed on their local machine. Otherwise, look at any table that supports sorting.

**Expected behavior**
1. Buy the license (this has been approved) 
2. Install the license code

**Who is affected by the problem?**
Web users

**What is the impact?**
It is not clear that the icon can be clicked to sort the table

**Are there security concerns?**
No

**Are there privacy concerns?**
No

**What are the proposed actions?**
Buy the license and configure it

**What is the proposed priority?**
This is a quick fix to a developer confirmed problem, so I'll schedule it for 2.51.0

**Comment by leovegoda** [comment]
Moved straight to Ready for Implementation as this does not require development and the spending has been approved

**Comment by leovegoda** [comment]
@vegu pointed out that we could use "Sort by Alpha" from Google Fonts, instead: https://fonts.google.com/icons?selected=Material+Icons+Outlined:filter_list:&icon.query=sort&icon.set=Material+Icons

**Comment by arnoldnipper** [comment]
+1 and please implement what's best for us.

**Comment by ljarbinet** [comment]
> @vegu pointed out that we could use "Sort by Alpha" from Google Fonts, instead: https://fonts.google.com/icons?selected=Material+Icons+Outlined:filter_list:&icon.query=sort&icon.set=Material+Icons

Google fonts' "Sort by Alpha" can be found in lots of websites and seems to be well assimilated by users

**Comment by martinhannigan** [comment]
They also seem to be more aesthetically pleasing and common.



From: Laurent Jarbinet ***@***.***>
Date: Wednesday, August 2, 2023 at 5:26 AM
To: peeringdb/peeringdb ***@***.***>
Cc: Subscribed ***@***.***>
Subject: Re: [peeringdb/peeringdb] Obtain and install license for Glyphicons Halflings font (Issue #1419)

@vegu<https://github.com/vegu> pointed out that we could use "Sort by Alpha" from Google Fonts, instead: https://fonts.google.com/icons?selected=Material+Icons+Outlined:filter_list:&icon.query=sort&icon.set=Material+Icons

Google fonts' "Sort by Alpha" can be found in lots of websites and seems to be well assimilated by users

**Comment by leovegoda** [comment]
**Summary:** replace the current glyph with "Sort by Alpha" from Google Fonts

**Comment by grizz** [comment]
and any other missing icons

Also updating title.

**Comment by vegu** [comment]
closed through https://github.com/peeringdb/peeringdb/pull/1440
