### ISSUE TITLE
Expanding IX LAN checks for overlap, preventing expansion if old and new block overlaps

### ISSUE THREAD

**Issue by netravnen** [peeringdb/peeringdb#1424]
**Describe the bug**

Expanding IX LAN https://www.peeringdb.com/ix/4011 **from** 103.138.70.96/27 **to** 103.138.70.64/26

**To Reproduce**

1. go to https://www.peeringdb.com/ix/4011
2. hit edit
3. Change the v4 peering lan **from** 103.138.70.96/27 **to** 103.138.70.64/26
4. See error (_Prefix overlaps with CENTRO-IX's prefix: 103.138.70.96/27_)

**Expected behavior**

Since it is the exact same IX LAN v4 prefix that is being tried expanded. I.e. the prior block falls into the new block. It was expected to succeed.

**Who is affected by the problem?**

IXP's who have been assigned a larger v4 block that included their prior v4 block.

**What is the impact?**

Unable to renumber the v4 peering lan prefix without some scripting hurdles.

(Remove all existing v4 peerings, store them somewhere, remove old v4 peering lan prefix, create new v4 peering lan prefix, recreate all v4 peering addresses)

**Are there security concerns?**

none

**Are there privacy concerns?**

none

**What are the proposed actions?**

allow peeringdb user and support to renumber peering lans, where the "old" v4 block falls into the "new" v4 block.

**What is the proposed priority?**

unsure (have outstanding [ticket](https://peeringdb.deskpro.com/agent/#app.tickets,filter:36,t.o:90511,vis:5))

**Provide a rationale for any/all of the above**

Unable to proceed with [ticket 90511](https://peeringdb.deskpro.com/agent/#app.tickets,filter:36,t.o:90511,vis:5)

**Additional context**

none

**Comment by arnoldnipper** [comment]
IIRC, we already have an issue for that @netravnen. Unlike removing an `ixlan`, removing an `ixpfx` does not remove all `netixlan` objects as there is no connection. Hence, changing an `ixpfx` is safe. I.e. removing the /27 and then adding the overlapping /26.

**Comment by arnoldnipper** [comment]
@netravnen, should have been fixed in #924

**Comment by arnoldnipper** [comment]
Fixed in #924

**Comment by netravnen** [comment]
@arnoldnipper I do not _fully_ agree with you. Example

I am trying to renumber CENTRO-IX. (The user has tried as well from the [frontpage](https://www.peeringdb.com/ix/4011))

- https://www.peeringdb.com/ix/4011
- https://www.peeringdb.com/cp/peeringdb_server/ixlanprefix/3537/change

<img width="344" alt="image" src="https://github.com/peeringdb/peeringdb/assets/1938389/7a122b31-2dfe-472c-a75d-cedde5ad3a6c">

<img width="356" alt="image" src="https://github.com/peeringdb/peeringdb/assets/1938389/b0a00d86-9237-4d97-9a58-19510dd93421">

1. from 103.138.70.96/27
2. to 103.138.70.64/26

Then the /cp refuses the change request with error `Prefix overlaps with CENTRO-IX's prefix: 103.138.70.96/27`

To reproduce,
1. Either from the [frontpage](https://www.peeringdb.com/ix/4011), the [/cp ](https://www.peeringdb.com/cp/peeringdb_server/ixlanprefix/3537/change/), or using the [Renumber IP Space Command line tool](https://www.peeringdb.com/cp/peeringdb_server/commandlinetool/prepare/)
2. replace current ixpfx subnet 103.138.70.96/27, with
3. new ixpfx subnet 103.138.70.64/26
4. receive error message "Prefix overlaps with CENTRO-IX's prefix: 103.138.70.96/27"

**Comment by netravnen** [comment]
Any and all responses, ideas, suggestions on how I can proceed is warmly welcomed. :-)

**Comment by netravnen** [comment]
> IIRC, we already have an issue for that @netravnen. Unlike removing an `ixlan`, removing an `ixpfx` does not remove all `netixlan` objects as there is no connection. Hence, changing an `ixpfx` is safe. I.e. removing the /27 and then adding the overlapping /26.

@arnoldnipper Overlooked this options. As I was under the assumption the removal of the ixpfx would remove all related netixlan objects as well. (Or be prevented due to the ixpfx not being empty)

IMO. Maybe add this possibility to the PDB Command-Line-Tool in the /cp so it can be done using regular /cp GUI in the future? 🤔

**Comment by netravnen** [comment]
> We need to solve your problem regardless of other issues. Customer service. Can 20c chine in here re: a potential fix?

@martinhannigan with AN's input. I can continue. Thou the suggestion is not very obvious. And still leaves room for adding AN's suggestion to the /cp GUI in one form or another.

**Comment by netravnen** [comment]
@arnoldnipper thx for the provided steps. Did help me resolve the users ticket. IMO. I would still like the steps you described to be converted to e.g. a command line tool in the /cp.

**Comment by arnoldnipper** [comment]
> @arnoldnipper thx for the provided steps. Did help me resolve the users ticket. IMO. I would still like the steps you described to be converted to e.g. a command line tool in the /cp.

IMO, that's overkill. Command line tools are for complex operations. Removing and adding an `ixpfx` isn't complex and best done via the general UI.
