### ISSUE TITLE
Update social media icons in footer

### ISSUE THREAD

**Issue by leovegoda** [peeringdb/peeringdb#1425]
**Is your feature request related to a problem? Please describe.**
The social media icons for YouTube and X (previously Twitter) have changed. We should update them in the footer.

**Who is affected by the problem?**
Web users who look for a social media icon

**What is the impact?**
Using the current set of icons helps users navigate

**Are there security concerns?**
No

**Are there privacy concerns?**
No

**Describe the solution you'd like**
https://docs.peeringdb.com/ has already been updated. Use the symbols found there.

**Do you think this feature will require a formal design?**
No

**Describe alternatives you've considered**
Do nothing

**Could this feature request need support from the Admin Committee?**
No

**What is the proposed priority?**
Low

**Comment by leovegoda** [comment]
Outreach Committee is happy for this to proceed @20c - can you please do a time estimation

**Comment by ghankins** [comment]
There's also a broken link at the bottom of the page that needs to be fixed.  The link in the PeeringDB logo goes to https://docs.peeringdb.com/news, but that page never existed.  Please remove the logo and link entirely.  We already have the logo at the top of each page.
