### ISSUE TITLE
[Beta] campus with only 1 facility in it breaks peeringdb-py client sync

### ISSUE THREAD

**Issue by vegu** [peeringdb/peeringdb#1427]
**Describe the bug**
On beta we are now exposing `campus_id` on the `fac` api end point to be able to sync facility -> campus relationships to the peeringdb-py client.

There currently exists an issue where a campus that has exactly 1 facility in it will break sync. This happens because campuses, by design, are pending until they have at least 2 facilities in them. If a campus has exactly 1 facility in it, that facility will reference the pending campus.

Currently the api does not include any `pending` objects, so the client is unable to fetch the referenced pending campus during sync, breaking the sync process.

**To Reproduce**
Run peeringdb-py client sync against current beta instance.

**Proposed Fix**
We could allow `pending` campus objects to be fetched by the client, the same we allow soft-deleted objects to be fetched (via the `since` incremental update parameter)

Or we could also not reference the campus on the facility object until it is no longer pending.

**Comment by arnoldnipper** [comment]
+1 ... also for the proposed fix
