### ISSUE TITLE
Changing ASN field on "Add Network" to be numbers only

### ISSUE THREAD

**Issue by rapdodge** [peeringdb/peeringdb#1430]
**Is your feature request related to a problem? Please describe.**
Yes, because if ASN field are not number only, it got 500 Error

**Who is affected by the problem?**
Me (and maybe others)

**What is the impact?**
Error 500 when you wanted to adding ASN

**Are there security concerns?**
No

**Are there privacy concerns?**
No

**Describe the solution you'd like**
Changing the ASN field on "Add Network" from text to number

**Do you think this feature will require a formal design?**
No, because it's just changing the input type from text to number

**Describe alternatives you've considered**
No alternative

**Could this feature request need support from the Admin Committee?**
No

**What is the proposed priority?**
Low, but it's nice if will be changed to next release

**Provide a rationale for any/all of the above**
-

**Additional context**
![image](https://github.com/peeringdb/peeringdb/assets/33513626/c5ae52e6-58c1-4617-9848-ef2893f8a409)

Field that outlined input type should be changed from text to number. Since if people don't know that field should be number only, it will got error 500

**Comment by martinhannigan** [comment]
+1

Friendly suggestion to pop an error that says something like text detected,
try without using the letters "AS" or something similar.

**Comment by arnoldnipper** [comment]
+1 ... my suggestion is to strip "AS" and "ASN" if they should occur. That's in line what we do on the user/AC interfaces.

**Comment by martinhannigan** [comment]
that works too. Sounds like this is cleaner.

**Comment by mcmanuss8** [comment]
+1

**Comment by grizz** [comment]
+1

**Comment by grizz** [comment]
**Summary**

Make this a number only field, and/or strip out AS|ASN so it doesn't fail validation.

**Comment by martinhannigan** [comment]
+1
