### ISSUE TITLE
Make dates ISO 8601 compliant everywhere in PeeringDB

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/peeringdb#1432]
**Is your feature request related to a problem? Please describe.**

Done for user GUI, but missing in @peeringdb/ac  See #296

**Comment by martinhannigan** [comment]
+1

**Comment by peterhelmenstine** [comment]
+1

**Comment by grizz** [comment]
**Summary**
Make dates displayed in the admin control panel ISO8601 compiant.
