### ISSUE TITLE
Timestamps should be consistent

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/peeringdb#1433]
**Describe the bug**

  "rir_status_updated": "2022-07-27T05:29:57.260109Z",
  "created": "2004-07-28T00:00:00Z",
  "updated": "2022-07-27T05:33:22Z",

**Comment by mcmanuss8** [comment]
+1

**Comment by grizz** [comment]
+1

**Comment by grizz** [comment]
**Summary**

Drop microseconds from timestamps

**Comment by martinhannigan** [comment]
+1
