### ISSUE TITLE
API list net documentation says "org" is a string, but it actually contains a dictionary

### ISSUE THREAD

**Issue by mpounsett** [peeringdb/peeringdb#1438]
**Describe the bug**
The API documentation for the [list net](https://www.peeringdb.com/apidocs/#tag/api/operation/list%20net) call defines `org` as `string`, but the data structure returned is an `org` object, as returned by `list org`.

**To Reproduce**

``` console
curl "https://www.peeringdb.com/api/net/10664" | jq ".data[].org"
```

**Expected behavior**
Documentation should indicate the actual data type returned.

**Who is affected by the problem?**

Anyone using the API documentation.

**What is the impact?**

Confusion. :)

**Are there security concerns?**

Unknown.

**Are there privacy concerns?**

Unlikely.

**What are the proposed actions?**

Update the documentation.

**What is the proposed priority?**

not urgent

**Comment by arnoldnipper** [comment]
+1 ... Same goes for "ix", "fac", and "carrier"

**Comment by mcmanuss8** [comment]
+1

**Comment by grizz** [comment]
+1

**Comment by grizz** [comment]
The docs are all generated, so so this will require some poking and possibly code changes. It will not require a release to fix.
