### ISSUE TITLE
Facility Update section

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/peeringdb#144]
It would be great to have a subsection on the home page for facility Updates. When a new facility comes online or an existing facility adds a new location it would be great to have a feed of that information available or just hyperlinked to their PDB entry.

(copy of #143 just for facilties)

**Comment by eloos** [comment]
shouldn't this be part of a larger "ticker feed" which could include many more items like new networks, networks joinging exchanges etc.. I believe this should be part of a communication strategy. Maybe even a link to a twitter feed might be more appropriate and could even be a third party plugin? All the data is in the API and can be fetched based on a delta thanks to the modification date.

**Comment by grizz** [comment]
@eloos I think that's a good idea, but should be created as a separate ticket for more discussion, this is quick and easy to do, so might as well just add to the home page

**Comment by vegu** [comment]
fixed in 0941c05
