### ISSUE TITLE
v2 search - support for ISO 3166 alpha-2 country codes

### ISSUE THREAD

**Issue by leovegoda** [peeringdb/peeringdb#1447]
**Describe the bug**
ISO 3166 alpha-2 codes are widely used because they are unambiguous and don't require users to know the correct spelling for country names. 

v2 searches that use ISO 3166 alpha-2 codes often return additional results. Searches that use the country name return more accurate results.

Searches that use ISO 3166 alpha-2 codes that have been [assigned or exceptionally reserved](https://www.iso.org/glossary-for-iso-3166.html) should give the same results as the English short name used in ISO 3166.

**To Reproduce**
1. Search for ix in ke (https://www.peeringdb.com/search/v2?q=ix+in+ke)
2. See that the returned results include exchanges in facilities that are not located in Kenya

<img width="409" alt="Screenshot 2023-09-26 at 07 35 49" src="https://github.com/peeringdb/peeringdb/assets/59064677/fa2ec115-0f63-4dff-b4da-e06c92d6842f">

3. Search for ix in kenya (https://www.peeringdb.com/search/v2?q=ix+in+kenya)
4. See that the returned results are all based in facilities located in Kenya

<img width="556" alt="Screenshot 2023-09-26 at 07 35 31" src="https://github.com/peeringdb/peeringdb/assets/59064677/fd36b83e-4344-4dea-9039-7228f3fb4dab">

**Expected behavior**
Both searches should return the same results

**Who is affected by the problem?**
Users of v2 search, which should become the core search feature

**What is the impact?**
Users are slowed down and possibly confused

**Are there security concerns?**
No

**Are there privacy concerns?**
No

**What are the proposed actions?**
Ensure that searches using ISO 3166 alpha-2 codes return the same results as searches using the English short name used in ISO 3166.

**What is the proposed priority?**
Soon

**Provide a rationale for any/all of the above**
Search quality and data quality are the most valued user features. We should fix bugs that could slow or confused users using search.

**Additional context**
Discovered when researching https://github.com/peeringdb/peeringdb/issues/1446

**Comment by grizz** [comment]
+1

**Comment by ynbrthr** [comment]
+1

**Comment by martinhannigan** [comment]
+1
