### ISSUE TITLE
Improve long IPv6 address visualization

### ISSUE THREAD

**Issue by lukastribus** [peeringdb/peeringdb#145]
Some networks have long IPv6 addresses, for instance Microsoft at MIX-IT:
https://www.peeringdb.com/net/694

PDB does not show the trailing "2" of either IPv6 addresses at MIX-IT. One can blindly select the entire address with a double-click and copy&paste it out of it, but that doesn't seem very intuitive.

Not sure what the best solution for this.

(of course, y'all use the API and fill your peering automation software with it, but not all shops do it this way).

**Comment by arnoldnipper** [comment]
Lukas, not sure what you exactly mean (see .png attached). Otoh you will probably always have issues on e.g. mobile phones or small displays (see other snapshot)
![20170403 peeringdb 00](https://cloud.githubusercontent.com/assets/16888757/24621255/3079fa4a-18a1-11e7-9b37-7b285a0b32b3.png)
![2017-04-03 17 09 20](https://cloud.githubusercontent.com/assets/16888757/24621362/787dfeae-18a1-11e7-965c-9f8e78b98c41.png)

**Comment by lukastribus** [comment]
Well, this is a 27" display with 2560x1440 resolution, and both Firefox and Chrome (zoom: 100%) show this:

![pdb-ms-mixit-issue](https://cloud.githubusercontent.com/assets/15380567/24621730/c6ccf0b4-18a2-11e7-920f-f62a6bab55ad.png)


Lower resolutions (on a 23" screen) show *exactly* the same issue. The behavior with different desktop resolutions is the same for me, trimming trailing "2" from the IPv6 address.

Can you confirm you tried a desktop resolution with Chrome or Firefox, with Zoom: 100% and no other fancy setting like non-default DPI o Display scaling?


Thanks

**Comment by arnoldnipper** [comment]
Lukas,

these are my settings

14" Lenovo X1, Display resolution 2560x1440
Browser is Chrome Version 57.0.2987.133, Zoom 100%

Afaik there are no fancy settings.

**Comment by arnoldnipper** [comment]
This is how it looks like on Edge resp. FF
![20170403205026_peeringdb_ff_snip](https://cloud.githubusercontent.com/assets/16888757/24625483/6b6d0d78-18af-11e7-94e5-db9b3125237e.png)
![20170403204618_peeringdb_edge_snip](https://cloud.githubusercontent.com/assets/16888757/24625489/713e77b4-18af-11e7-9fd4-306fb7c8f9f2.png)

**Comment by lukastribus** [comment]
Hello Arnold,

thanks for checking.

Well, the fact is I have this issue on 2 different desktop PC's in two different, but standard resolutions:
27" --> 2560x1440
22" --> 1680x1050 (its not 23")

I find it hard to believe that you are using 2560x1440 on a 14" laptop without any DPI scaling. You must be using a microscope to read the text on the display then :)

I assume you can reproduce this issue when you zoom back to something lower than 100% (in Chrome).


Be that as it may, clearly the visualization is indeterministic and based on DPI/zoom/browser vendor on high-resolution desktop PC's and that kind of indeterministic behavior is confusing and time consuming.

I don't care about smartphones, but I would like to PDB to not trim parts of the address in standard desktop resolutions, without me knowing.


I just talked to my CSS guy, and other than artificially making the column longer (which just moves the problem around), we can force a line break by adding "word-break: break-all;" to the CSS style for this:

![pdb-break-all](https://cloud.githubusercontent.com/assets/15380567/24647323/bd3f1018-191f-11e7-92d5-57a3156fb0e8.png)


It will only break the line when it doesn't fit, and it seems like a very good solution to this problem.

**Comment by arnoldnipper** [comment]
breaking the line seems a perfect solutions

**Comment by lukastribus** [comment]
Same thing for email addresses:
https://www.peeringdb.com/asn/6830

**Comment by vegu** [comment]
fixed in ee3940ca
