### ISSUE TITLE
Cosmetic issue with affiliation emails and double-slash in URL

### ISSUE THREAD

**Issue by ccaputo** [peeringdb/peeringdb#1451]
Like #1334 there is a double-slash happening in affiliation emails _after_ the domain name, ala:

```
From: support@peeringdb.com
To: a@b.c
Subject: User Xyz wishes to be affiliated to your Organization



User Xyz (x@y.z) wishes to be affiliated to Example Organization.

As the organization's administrator you may approve or deny this request here:

https://www.peeringdb.com//org/9999999999#users
```

In addition to fixing this, I recommend a search for other superfluous double-slashes be performed to catch other cases.

**Comment by mcmanuss8** [comment]
+1

**Comment by martinhannigan** [comment]
+1

**Comment by netravnen** [comment]
Mails sent to deskpro usually contains `//` (`https://www.peeringdb.com//cp/peeringdb_server/<organization>/<ID>/change/`)

Including the `href` value of the links with texts
- "Review Affiliation/Ownership Request", and
- "Approve Ownership Request and Notify User"

![image](https://github.com/peeringdb/peeringdb/assets/1938389/f1336d1f-667a-45c3-a5ef-987766e6287a)
