### ISSUE TITLE
Normalizing the presentation of place names

### ISSUE THREAD

**Issue by leovegoda** [peeringdb/peeringdb#1452]
**Is your feature request related to a problem? Please describe.**
Our users describe city and country names in a variety of inconsistent ways. Users have consistently told us that data quality and search results are their highest priorities. We should continue to allow users to submit data using local spellings and keep that in a set of user supplied data fields. The data should be normalized for presentation using Melissa, so search results export with consistent naming.

**Who is affected by the problem?**
Users investigating cities or countries with multiple names in common usage.

**What is the impact?**
User entered data is maintained but all results use consistent naming.

**Are there security concerns?**
No.

**Are there privacy concerns?**
No.

**Describe the solution you'd like**
As above.

**Do you think this feature will require a formal design?**
Yes.

**Describe alternatives you've considered**
Rely on the radius search and v2 search (Elastic search) to help users find the resources they are interested in. Users would have to manually normalize data themselves if they need normalized data.

**Could this feature request need support from the Admin Committee?**
Possibly. Guidance from the @peeringdb/ac would be useful.

**What is the proposed priority?**
Important but not urgent.

**Provide a rationale for any/all of the above**

- Avoid surprising users of search with multiple names for the same location.
- Avoid surprising users entering data by changing it without their knowledge.

**Additional context**
The radius search and v2 search have been improvements but the results presented still require normalization for some analyses. Automating this would be user friendly.

**Comment by mcmanuss8** [comment]
+1 - we should have a normalized name that's "authoritative" and then alternative spellings (including what the user provided) so we can search on those too.

**Comment by peterhelmenstine** [comment]
+1

**Comment by ynbrthr** [comment]
+1

**Comment by leovegoda** [comment]
That looks like a good summary to me

**Comment by martinhannigan** [comment]
Im unclear about the benefits.

Do all other websites do this? Is this a priority over UI? How many users
asked for this?

Thanks

**Comment by leovegoda** [comment]
The consensus at today's @peeringdb/pc meeting was to both normalize city names and enable alternative names searching in a single step to help users get the best experience. Changed status as a result.

**Comment by grizz** [comment]
Also as discussed on the call, we believe the v2 search will handle alternative name searching, but will do some internal (PC) testing before it goes to beta.

**Comment by jackcarrozzo** [comment]
+1
