### ISSUE TITLE
Add a metro area field with normalized presentation of naming

### ISSUE THREAD

**Issue by leovegoda** [peeringdb/peeringdb#1454]
**Is your feature request related to a problem? Please describe.**
Users searching for facilities often want to look in a broad metro area. Often, the metro area covers more than one jurisdiction. For example, [bitNap Datacenter](https://www.peeringdb.com/fac/2890) is in L'Hospitalet de Llobregat but most people would search for Barcelona as it is only 6km from the center of Barcelona. 

Facility operators and the users searching for facilities could benefit from an optional, user supplied metro area field that uses normalized naming. e.g. a facility operator in Chandler, AZ might choose to list Phoenix, AZ as the metro area. 

**Who is affected by the problem?**
All users interested in a broad metro area rather than specific jurisdictional boundaries.

**What is the impact?**
A complete list of facilities serving a metro area can be found without guessing a radius to search within. This should make search a little bit easier for some users and make some facilities more discoverable.

**Are there security concerns?**
No

**Are there privacy concerns?**
No

**Describe the solution you'd like**

- An optional field for the metro area served 
- Name normalization using Melissa
- The ability to specifically search by metro area instead of street address

**Do you think this feature will require a formal design?**
Yes

**Describe alternatives you've considered**

- We could leave things as they are
- We could automatically populate a metro area field for all facilities where we know of a nearby metro area
- We could automatically populate a metro area field but require the facility owner to approve publication

**Could this feature request need support from the Admin Committee?**
Unlikely

**What is the proposed priority?**
TBD

**Provide a rationale for any/all of the above**
Users consistently report data quality and search as tehir two top priorities. This could improve both.

**Additional context**
This is orthogonal to https://github.com/peeringdb/peeringdb/issues/1452 but should use the same naming normalization.

**Comment by ynbrthr** [comment]
+1

**Comment by martinhannigan** [comment]
In the US, a metro area isn't a jurisdiction; it's typically population
density related to the downtown core and frequently bordered (facing the
inside) by a major highway system. For example RT 128 in MA or I495 The
Capitol Beltway in DC (which the DC metro area is sometimes thought to
touch three states). I don't think this is optimal competitively either. It
feels like it could suffocate the independent operators of both IXP's and
data centers. They already have a hard enough time competing with nationals.

-1

Search radius seems like it's already a good solution to find options
nearby or far.

**Comment by arnoldnipper** [comment]
"metro area" is not always well-defined. Where it is, it would add additional help. E.g. in Germany, there are 11 well-defined metropolitan areas. Hence, +1

**Comment by grizz** [comment]
-1 based on discussion about how to define MSAs, and the pain that comes with it shouldn't be something PeeringDB does.

**Comment by mcmanuss8** [comment]
-1

**Comment by leovegoda** [comment]
Closing as v2 search already does a large part of this and going down this road could be expensive

**Comment by martinhannigan** [comment]
-1
