### ISSUE TITLE
Org name RIPE-NCC-END-MNT for new networks

### ISSUE THREAD

**Issue by leovegoda** [peeringdb/peeringdb#1455]
**Describe the bug**
A user reported that their new org got the name RIPE-NCC-END-MNT. AC members reported seeing this several times for other org creations. 20C investigated and found that the code cycles through all contacts and uses whatever the last one is for the name of the org. 

RIPE-NCC-END-MNT should not be used as it is not a good description of any org.

**To Reproduce**
Omitted as 20C has already investigated this.

**Expected behavior**
If no entity name is given, call the org AS$ASN. e.g. AS64496's organization would be called AS64496. The org admin could then rename their organization as necessary.

**Who is affected by the problem?**
End user organizations with an ASN assigned by the RIPE NCC

**What is the impact?**
User confusion

**Are there security concerns?**
No. This was investigated and the issue does not grant affected organizations any permissions they should not have.

**Are there privacy concerns?**
No

**What are the proposed actions?**
If no entity name is given, call the org AS$ASN. e.g. AS64496's organization would be called AS64496. The org admin could then rename their organization as necessary.

**What is the proposed priority?**
Urgent

**Provide a rationale for any/all of the above**
This could cause user confusion and eats up AC time

**Comment by peterhelmenstine** [comment]
+1

**Comment by martinhannigan** [comment]
+1

**Comment by grizz** [comment]
+1

> The description of the expected behavior needs to be corrected. There is an entity object. However, the algo picks the last one. It also could pick the first and then already exit.

Not all entities have org names, so it uses contacts now -- the fix will be to use the org name if it's there, or name it for the ASN and let the user update it as needed. I see no reason to need to notify the AC any differently than usual.

**Comment by arnoldnipper** [comment]
> Not all entities have org names, so it uses contacts now -- the fix will be to use the org name if it's there, or name it for the ASN and let the user update it as needed. I

Look at https://www.peeringdb.com/net/34362. The rdap object has an org field. However, the tool still picked "RIPE-NCC-END-MNT" as org name. 

Something changed. Either at how RIPE exports their DB information. Or something at our side.

**Comment by grizz** [comment]
Right, that's exactly what I said.

RIPE changed and started adding that, this will fix that as stated above.

**Comment by arnoldnipper** [comment]
> Not all entities have org names, so it uses contacts now

Then, it needed to be clarified. The above-mentioned object has an org field. Let's discuss what an org object should look like. See e.g. https://www.peeringdb.com/org/36327. In the past, I've updated such object with proper org information derived from whois.

**Comment by leovegoda** [comment]
https://www.peeringdb.com/org/36327 is currently mostly empty after being created three weeks ago. It's possible that the user doesn't know why they should fill out the data, or how. We could prompt users to update their entries by automatically sending them to the [relevant HOWTO](https://docs.peeringdb.com/howtos/) if they remain essentially empty after an agreed period - maybe two weeks.

**Comment by arnoldnipper** [comment]
Depends on what we think, who should do what. The ASNAUTO-Tool helps to prepopulate entries for net and org. I always understood that @peeringdb/ac has to look after each entry and ensure that both are proper. In this case, an AC member should have changed the org name to "Mathias Neerup" (ORG-MN189-RIPE).

**Comment by grizz** [comment]
> > Not all entities have org names, so it uses contacts now
> 
> Then, it needed to be clarified. The above-mentioned object has an org field. Let's discuss what an org object should look like. See e.g. https://www.peeringdb.com/org/36327. In the past, I've updated such object with proper org information derived from whois.

This issue is simply to change ASNAUTO to use `If it has an org name, use that, if not use AS$ASN` instead of `last listed contact` -- let's keep it simple and separate so we can fix the current behavior.

The user can always change the org name to whatever they would like, the AC doesn't need to do anything with it -- but any AC interaction should be a separate issue.

**Comment by arnoldnipper** [comment]
> The user can always change the org name to whatever they would like, the AC doesn't need to do anything with it

That isn't true. The user can't change it to names already taken (ok and deleted). Hence, it isn't perpendicular to any AC action

**Comment by netravnen** [comment]
Looking forward to see if this is resolved.

Dealing with the tickets... :face_exhaling:

**Comment by netravnen** [comment]
Does the fix for this issue looks for if an organization already exists with a name found in the WHOIS records _before_ creating a new organization?

I continue to see networks being affiliated with "RIPE-NCC-END-MNT" https://www.peeringdb.com/org/37006

![image](https://github.com/peeringdb/peeringdb/assets/1938389/b63f4ca7-608c-4b3a-8305-27eea1bdd6cc)

Footnote: No tickets containing "RIPE-NCC-END-MNT" has been created in Deskpro since Jan 26. (Deskpro #98016 was the last one) -- Which I suppose was an intended change as part of the fix for 1455.

**Comment by netravnen** [comment]
Did a full move this evening,

| ORG | NET
| --- | ---
| https://www.peeringdb.com/org/37288 | https://www.peeringdb.com/asn/58350  
| https://www.peeringdb.com/org/37289 | https://www.peeringdb.com/asn/215614 
| https://www.peeringdb.com/org/37290 | https://www.peeringdb.com/asn/205343 
| https://www.peeringdb.com/org/37291 | https://www.peeringdb.com/asn/44299  
| https://www.peeringdb.com/org/37292 | https://www.peeringdb.com/asn/62273  
| https://www.peeringdb.com/org/37293 | https://www.peeringdb.com/asn/210625 
| https://www.peeringdb.com/org/37294 | https://www.peeringdb.com/asn/215628

**Comment by netravnen** [comment]
DeskPro 97943 was affected by the same issue. Thou for a ORGname collision in the LACNIC WHOIS DB.

**Comment by netravnen** [comment]
Does the fix for this issue shipped with the latest release assume the organization does not exist?

Still seeing networks being affiliated to the "DUMMY" organization (I was hoping would be unnecessary with the shipment of v2.55.0... 😖) 

![image](https://github.com/peeringdb/peeringdb/assets/1938389/0dc4ca59-5292-4008-86a7-59848847e99d)

![image](https://github.com/peeringdb/peeringdb/assets/1938389/507b1168-12c9-4e2b-b1d4-0676cd4d29dc)

**Comment by netravnen** [comment]
The tickets are also arriving to Deskpro.

![image](https://github.com/peeringdb/peeringdb/assets/1938389/6bd3874f-8ef3-4091-863a-a7aa22ca3019)

**Comment by netravnen** [comment]
@leovegoda Can this be reopened? I disagree this has been resolved. As the tickets are still coming in.

If this has indeed been resolved. I would like to know _how_ it has been resolved.

E.g. does the solution implemented looks for if ORG `RIPE-NCC-END-MNT` exists and only creates a new ORG if `RIPE-NCC-END-MNT` does _not_ exist?

If ORG `RIPE-NCC-END-MNT` exists, it assigns the new network to ORG `RIPE-NCC-END-MNT`?

**Comment by grizz** [comment]
@netravnen could you email me the deskpro ticket and which network it was so we can take a look?
