### ISSUE TITLE
Update website to take advantage of wider screen and improve mobile device support

### ISSUE THREAD

**Issue by leovegoda** [peeringdb/peeringdb#1463]
**Is your feature request related to a problem? Please describe.**
We now know that about 80% of web users are on a desktop or laptop with a screen resolution of 1920x1080 or larger. About 20% of users are on mobile devices. We should update the web design to take better advantage of wide screens while gracefully adapting for mobile devices.

**Who is affected by the problem?**
Web users

**What is the impact?**
Improve user experience by adjusting table sizes across the whole site and introducing new UI elements for `campus` view

**Are there security concerns?**
No

**Are there privacy concerns?**
No

**Describe the solution you'd like**
Implement the design changes

**Do you think this feature will require a formal design?**
Already designed

**Describe alternatives you've considered**
Do nothing

**Could this feature request need support from the Admin Committee?**
No

**What is the proposed priority?**
Release in January 2024

**Provide a rationale for any/all of the above**
This is one step in a design update to the website. The plan is to implement the changes in stages, so we avoid surprising and confusing users. This first step does two things: 

1. adjusts table size, spacing, and location 
2. introduces tabs for `campus` views, showing number counts for each table category 

**Additional context**
Future design improvements include new table design, a new data export control, changes to the front page, org admin pages, and personalization

**Comment by grizz** [comment]
+1

**Comment by mcmanuss8** [comment]
+1

**Comment by martinhannigan** [comment]
+1

**Comment by leovegoda** [comment]
@20c-ed I believe that implementing this issue will also resolve https://github.com/peeringdb/peeringdb/issues/1337 - is that correct?

**Comment by grizz** [comment]
Good catch, yes it would!
