### ISSUE TITLE
Analysis: Investigate use of ECS/Fargate

### ISSUE THREAD

**Issue by leovegoda** [peeringdb/peeringdb#1466]
**Is your feature request related to a problem? Please describe.**
Followup from #1225

Switch beta.peeringdb.com to ECS/Fargate and evaluate impact on both cost and operational complexity.

**Who is affected by the problem?**
Operations Committee

**What is the impact?**
This is analysis

**Are there security concerns?**
No

**Are there privacy concerns?**
No

**Describe the solution you'd like**
An evaluation of whether using ECS/Fargate would make sense for www.peeringdb.com

**Do you think this feature will require a formal design?**
No

**Describe alternatives you've considered**
Do nothing

**Could this feature request need support from the Admin Committee?**
No

**What is the proposed priority?**
December 2023

**Provide a rationale for any/all of the above**
We need to make sure we make the most efficient use of resources possible. Investigating the possibility of saving both volunteer time and sponsor donations is the right thing to do.

**Comment by grizz** [comment]
+1

@peeringdb/pc please vote so we can get this into the queue for the Operations Committee

**Comment by martinhannigan** [comment]
+1

**Comment by arnoldnipper** [comment]
+1
