### ISSUE TITLE
v2 search - not able to find IX participant based on IP

### ISSUE THREAD

**Issue by netravnen** [peeringdb/peeringdb#1469]
**Describe the bug**

**To Reproduce**
1. Go to frontpage
2. Use the v2 search
3. Enter random assigned IX IP
4. No results are returned

**Expected behavior**
The same as in the v1 search. Return IX network who uses the UP and IX who has the network

**Who is affected by the problem?**
AC and regular user who are looking for network based on IP assigned on Internet Exchange PFX LAN

**What is the impact?**
Not able to locate which network are using the IP

**Are there security concerns?**
N/A

**Are there privacy concerns?**
N/A

**What are the proposed actions?**
Should behave the same (or very similar) to the v1 search

**What is the proposed priority?**
with 1-2 releases released 9 Nov 2023

**Provide a rationale for any/all of the above**
avoid causing confusion

**Additional context**
pictures

**v1 search**
<img width="1542" alt="20231109205945002647" src="https://github.com/peeringdb/peeringdb/assets/1938389/c08de56c-5f32-449b-a7c8-416603c3d13d">

**v2 search**
<img width="1557" alt="20231109205930002646" src="https://github.com/peeringdb/peeringdb/assets/1938389/606ce4a6-f17a-411c-800c-6b70e9d2db4d">

**Comment by arnoldnipper** [comment]
Clear bug

**Comment by martinhannigan** [comment]
+1
