### ISSUE TITLE
[INFO REQ] Possible to change PeeringDB Username ?

### ISSUE THREAD

**Issue by Jeni4** [peeringdb/peeringdb#147]
**Is it in any way possible to change the Username of one's Peering DB profile ?**

**Comment by arnoldnipper** [comment]
yes, just do it yourself ;-) ... or send an e-mail to support@peeringdb.com

**Comment by arnoldnipper** [comment]
@Jeni4 ... a regular user has to send an email to support@peeringdb.com. If you are a PDB admin use the Admin GUI to change the username ;-)
