### ISSUE TITLE
Searching for specific facilities (so far Equinix) returns incorrect results

### ISSUE THREAD

**Issue by martzuk** [peeringdb/peeringdb#1473]
**Describe the bug**
Searching for certain sites specifically by name doesn't return the correct result. so far seen it with various Equinix facilities

**To Reproduce**
Use the new search, and type "Equinix FR5"

**Expected behavior**
Equinix FR5 result returned

**Who is affected by the problem?**
All users

**What is the impact?**
v2 search doesn't work

**Are there security concerns?**
No

**Are there privacy concerns?**
No

**What are the proposed actions?**
Fix it

**What is the proposed priority?**
Not

**Provide a rationale for any/all of the above**
It should work properly

**Additional context**
<img width="1822" alt="Screenshot 2023-11-27 at 15 08 44" src="https://github.com/peeringdb/peeringdb/assets/1249518/7a6591f8-8099-4e1c-b3eb-27b799650f67">
<img width="1822" alt="Screenshot 2023-11-27 at 15 08 45" src="https://github.com/peeringdb/peeringdb/assets/1249518/c724eea6-30f6-4c40-ac95-0c4f8ac59f12">

**Comment by martinhannigan** [comment]
I can recreate it in the v2 free form search.
It works for me in the legacy free form search.
It works for me in the advanced search via Facilities optional screen and
using the name field.

+1 bug.

**Comment by jackcarrozzo** [comment]
+1

**Comment by arnoldnipper** [comment]
+1

**Comment by arnoldnipper** [comment]
I can't recreate it in v2. And interestingly, https://www.peeringdb.com/search/v2?q=FR5 gives exactly what you are looking for

**Comment by netravnen** [comment]
| Searches for | URL
| --- | ---
| "FR5" | https://www.peeringdb.com/search/v2?q=FR5
| "Equinix" _and_ "FR5" | https://www.peeringdb.com/search/v2?q=Equinix+FR5
| "Equinix" | https://www.peeringdb.com/search/v2?q=Equinix

Seems to me like spaces in the V2 search gets treated as a query separator. Causing the search results to be the combined results of all space separated strings.

**Comment by netravnen** [comment]
| Searches for | URL
| --- | ---
| "Equinix" _and_ "Globalconnect" | https://www.peeringdb.com/search/v2?q=Equinix+globalconnect

**Comment by arnoldnipper** [comment]
https://www.peeringdb.com/search/v2?q=Equinix+FR5 searches for "Equinix" **or** "FR5", not "Equinix" **and** "FR5"

**Comment by tcsweetser** [comment]
Well ...

"+" here becomes a simple space after the web server has parsed it, no?

Testing it like https://www.peeringdb.com/search/v2?q=Equinix%2BFR5 is *not
*producing a result.

Regards
<https://about.me/terry.sweetser?promo=email_sig&utm_source=product&utm_medium=email_sig&utm_campaign=gmail_api&utm_content=thumb>
Terry Sweetser
about.me/terry.sweetser
<https://about.me/terry.sweetser?promo=email_sig&utm_source=product&utm_medium=email_sig&utm_campaign=gmail_api&utm_content=thumb>
