### ISSUE TITLE
KML Placemark/Point Meta Data Not Displaying Correctly

### ISSUE THREAD

**Issue by martinhannigan** [peeringdb/peeringdb#1475]
**Describe the bug**
When clicking on pin for KML meta data?  Some display, and some have truncated data.

**To Reproduce**

1. Go to  KML data  <Placemark id="65609">  <Point id="65608"> which reflects https://www.peeringdb.com/fac/3484 Crown Castle Boston
2. Click the yellow pin for Crown Castle
3. Metadata is truncated after Comment
4. Click the pin for Databank which is next to it
5. Meta data completes accurately

To easily fly to the bad pin, use the GE app to go to 1 Summer, Boston, MA

This is happening to more than a few placemarks. Or points. I thought I saw some inconsistency in the KML but the file was too big to easily diff the bad vs. good. HTH.

**Expected behavior**

Meta data display entirely when requested

**Who is affected by the problem?**

Users of the KMZ file

**What is the impact?**

Incomplete data

**Are there security concerns?**

No.

**Are there privacy concerns?**

No.

**What are the proposed actions?**

Evaluate, repair.

**What is the proposed priority?**

Not urgent

**Provide a rationale for any/all of the above**

Accuracy, consistency.

**Additional context**

Considered adding to enhancements list, but this bug has a different class so I didn't.

**Comment by martinhannigan** [comment]
Additional debugging.

After more probing it appears conclusive that something is breaking in the markup related to comment.

Crown marked "all" there records with the comment "Previously Lightower" and none work
Equinix

NTT FRA 2 has comments, truncated meta data
Digital Realty CHI (2299 Busse Road) has comments, truncated meta data
Databank facilities have no comments, all show meta data correctly

Seems like a pattern.

**Comment by leovegoda** [comment]
I see this. Also, when I look at https://www.peeringdb.com/fac/3152 I just see the comment but not the rest of the entry.
<img width="470" alt="Screenshot 2023-12-04 at 07 50 37" src="https://github.com/peeringdb/peeringdb/assets/59064677/d3d15adf-7cb2-404c-be6e-5b074a63da99">

**Comment by grizz** [comment]
+1 this should be checked out.

**Comment by AjSteller** [comment]
Thanks Martin for linking, I had missed this one when checking issues for duplicate before submitting, my apologies.

As noted in #1501, I was able to confirm that the notes being added as the "Description" are hiding the rest of the meta data. Verified this by manually deleting the notes text from the Description in Google Earth and the meta data shows up properly. Can do the same in reverse and go to properties of a placemark and add any text in the Description, once you do that you can't see any of the other meta data, only the text in the description.

Seems that the solution is likely to just not export the Notes field in to the Description since the Notes are also in the regular meta data table and shows up there.

Thanks all!

**Comment by martinhannigan** [comment]
Anthony, yep. Confirmed. I couldn't figure out why removing the notes had
an impact, but I think 20c did.

The notes are valuable IMHO. Not critical of peeringDB, but they've enabled
work-around to deficiencies. They're also good to monitor to see where PDB
can make improvements (such as
https://github.com/peeringdb/peeringdb/issues/1131) since if you have to
put it in notes to get attention and more than a few are doing it perhaps
there's an enhancement to be made. Even if Lumen did tag you in PDB, that
doesn't tell the real story of Lumen (Qwest, Level(3), Centurylink,
$acquisition). A lot of people still think in terms of footprint. And
because of how messy long haul provisioning is the extra information can be
useful to guide provisioning while they try and find everything.

Example attached. The other great thing about notes is it supports markdown
language so you can make it "look" nice in the record.

Hope it's not too difficult of a fix!

**Comment by grizz** [comment]
Will be fixed with #1489
