### ISSUE TITLE
v2 search not able to find organization and network - Marconi Solutions Srls

### ISSUE THREAD

**Issue by netravnen** [peeringdb/peeringdb#1476]
**Describe the bug**
Using the legacy search, only one net and one org result is return for "Marconi Solutions Srls".

Using the v2 search. A multitude of results are returned. Just not the correct ones.

**To Reproduce**
1. Go to PDB frontpage
2. Search for "Marconi Solutions Srls" using the v2 search, also affected are
   - "OPEN DC SDN BHD"
3. Switch to legacy search
4. See error (i.e. the different returned results)

**Expected behavior**
The v2 search result should at least include the expected org and net

**Who is affected by the problem?**
any user using the frontend v2 search

**What is the impact?**
user confusion when not able to search for one org and net

**Are there security concerns?**
none

**Are there privacy concerns?**
none

**What are the proposed actions?**
the v2 search should at least return the expected ("Correct") results amongst the returned search results.

**What is the proposed priority?**
urgent (bug?)

**Provide a rationale for any/all of the above**
using the v2 search feels 'less than stellar' compared to the legacy search. When the expected results are not returned.

**Additional context**

legacy search

![image](https://github.com/peeringdb/peeringdb/assets/1938389/1be8c155-d431-49f3-91f5-44a3dac47b81)

v2 search - "Marconi Solutions Srls" is not amongst the returned search results.

![image](https://github.com/peeringdb/peeringdb/assets/1938389/bbbedece-9c53-4bda-b688-dfc3722ffe00)

**Comment by martinhannigan** [comment]
Recreated. +1 bug

**Comment by vegu** [comment]
Some observations: 

Searching for `Marconi` or `Srls` works. 

Without having looked at the implementation, this seems like a bug with the scoring of the results, where the matches on the term `Solutions` (not just in the name but also inside the object notes etc.) are contributing to the score causing them to score higher than the actual match on the exact phrase and pushing it out of the results.

**Comment by leovegoda** [comment]
> Should we pile search issues into this issue or create new ones? I'm seeing some oddity as well. HTH Warm regards,

It would be good to have a separate Github issue for each search issue to be resolved.

**Comment by netravnen** [comment]
Encountered the same issue while searching for org "OPEN DC SDN BHD" using the v2 search.

**Comment by leovegoda** [comment]
Pete has reported a similar issue for Digital Realty. The correct results (or at least better. results) (in all cases) seem to be provided when putting quote marks around the search term.

**Comment by leovegoda** [comment]
Moved to Ready for Implementation as this bug has been independently reproduced by several users
