### ISSUE TITLE
MMR Object

### ISSUE THREAD

**Issue by martinhannigan** [peeringdb/peeringdb#1477]
**Is your feature request related to a problem? Please describe.**

Create a meet-me-room object that is usable by buildings that have independent meet-me-room facilities but rent or lease space to FAC's or allow an IXP to be centralized in neutral MMR.

**Who is affected by the problem?**

All IXP users

**What is the impact?**

Visibility, competitiveness and clarity "where is everyone" in the building and what's the best way to get to them if I'm not in the same FAC for interconnection purposes.

**Are there security concerns?**

No.

**Are there privacy concerns?**

No.

**Describe the solution you'd like**

A design and deployment of an MMR object.

**Do you think this feature will require a formal design?**

Yes. How it fits in the schema. Rules for creation.

**Describe alternatives you've considered**

Doing nothing. Continues to leave large questions about who is in a building  and how to get to them effectively.

**Could this feature request need support from the Admin Committee?**

Limited. Likely to be requests that don't fit rules. But chicken and egg at this stage.

**What is the proposed priority?**

Not urgent, probably v3.

**Provide a rationale for any/all of the above**

Infrastructure visbility.

**Additional context**

Many buildings have meet-me-rooms and they're absent from PDB. Knowing about the entrance MMR helps networks to figure out when they can avoid coss such as dark fiber lengths or the type 2 services to gain access to a building then a FAC.

Retail data centers already have their own MMR's. May not apply to them. Design details and input consensus driven.

**Comment by arnoldnipper** [comment]
-1, as MMR are nicely covered by the `fac` object. See

```
3737    SCL-IX MMR      Santiago        CL
3755    SCL-IX MMR Extension 1  Santiago        CL
3756    SCL-IX MMR Extension 2  Santiago        CL
8242    AWS Bahrain DC53 MMR    Askar   BH
8243    AWS Bahrain DC52 MMR    Hamala  BH
```

**Comment by martinhannigan** [comment]
How many more examples do you have for research purposes?

Thanks

**Comment by martinhannigan** [comment]
Thanks Arnold. I’ll do what I can to explain how the infrastructure here
works, but facility is a box not a fuzzy border.

**Comment by martinhannigan** [comment]
+1

Part of the reason to support this is clarity of the infrastructure. While only a few have included MMR in their name, a clue that there is some need, most don't understand how the meet-me-room works or realize there can be many in a building and many different hierarchies of MMR. For example, if a building has a core MMR and an IXP chooses to take residence there they are likely in a completely neutral position to serve the building and its sub-facs (or addr/fac). Knowing that the MMR exists also levels the playing field for IXPs and allows for greater competition. Including in tier 1 markets.

Core building MMR - usually requires landlord authorization in the form of an access agreement, easement or lease. Appurtenances are also usually governed by the MMR authority.

FAC within an address - A fac in a building which has a MMR is usually bound to the MMR for long haul and proxy networks. Knowing this ahead of interconnection has value.

FAC MMR - most data centers have their own MMR's for internal cross connect. 

MMR - Telx operated MMR's on behalf of some buildings. This practice continues today. Clearly understanding who controls what MMR provides value to interconnection decisions.

Clarifying how to get around a building physically and which IXPs can be chosen is also a benefit. Some IXP's appear to be whole building reachable however that usually means theirs an interconnection extension fee on top of a port and normal interconnection charge. 

From an object perspective, this is the last piece of the puzzle to begin to potentially allow PDB to automate LOA. While we may not get all the way down to RR position and port, getting as close as the last patch between two authorities has automation value.

**Comment by jackcarrozzo** [comment]
PC call: is MMR needed separately? What is MMR vs fac

**Comment by arnoldnipper** [comment]
From [Admin Committee Guidelines and Criteria for Approving Networks, IXPs, and Facilities](https://docs.peeringdb.com/committee/admin/approval-guidelines): A “facility” is a physical location where two or more IP Networks or IXPs interconnect with each other.

By this definition, an MMR is a facility. Hence no need for an `mmr` object

**Comment by martinhannigan** [comment]
Incorrect. An MMR is a function of a facility. It’s also a required
breakpoint to connect to IXPs in the majority of cases.

**Comment by jackcarrozzo** [comment]
PC call: We should do a schema powwow

**Comment by jackcarrozzo** [comment]
We will circle back to this with a group
