### ISSUE TITLE
Facility data incorrectly exported to KMZ

### ISSUE THREAD

**Issue by elgaeloHub** [peeringdb/peeringdb#1479]
**Describe the bug**
Facility data does not get exported correctly to KMZ

**To Reproduce**
1. Open the following facility page https://www.peeringdb.com/fac/1816
2. Click on [Google Earth KMZ](https://public.peeringdb.com/peeringdb.kmz) to export today's KMZ export
3. Open [Google Earth](https://earth.google.com/) and import the KMZ file
4. Go to New York and look for a pin titled "325 Hudson". See differences between the KMZ data and the facility page

**Expected behavior**
Data on the KMZ export should be the same as in the web page

**Who is affected by the problem?**
Everyone potentially

**What is the impact?**
Data is incorrect

**Are there security concerns?**
No

**Are there privacy concerns?**
No

**What are the proposed actions?**
Analyse the code and figure out why this happens

**What is the proposed priority?**
Important but not urgent

**Provide a rationale for any/all of the above**
PeeringDB users want to have correct information.

**Comment by elgaeloHub** [comment]
After reviewing the issues, it seems this is a sub-issue of https://github.com/peeringdb/peeringdb/issues/1472

**Comment by grizz** [comment]
@elgaeloHub Thanks for the report, we appreciate any information that helps us split up #1472 and address the issues!

I'm not seeing the issue with 325 Hudson tho? I've compared the KMZ with the facility page / Google Maps, and they all look the same to me. Attached screenshots for better discussion.


Pics against 60 Hudson for perspective.

![image](https://github.com/peeringdb/peeringdb/assets/23176/137ad135-6da7-4975-a450-b36d83f5a787)

![image](https://github.com/peeringdb/peeringdb/assets/23176/b3d3dc34-43a1-48b0-8f0b-32a5e5529153)

From Facilities page link:

![image](https://github.com/peeringdb/peeringdb/assets/23176/33974191-4620-42ab-b8b6-d7ba0cb11b62)

Data:

![image](https://github.com/peeringdb/peeringdb/assets/23176/bf83e6f8-3776-476f-9a18-a5ab4495b73a)

**Comment by elgaeloHub** [comment]
Hi Matt,

Precisely, look at the difference on the content on your last screenshot with the current fac object id 1816 on the website https://www.peeringdb.com/fac/1816 (screenshot attached for convenience)

At least the fields "Name", "Aka" and "Website" are incorrect on the Google Maps.

<img width="731" alt="Screenshot 2023-12-08 at 15 53 13" src="https://github.com/peeringdb/peeringdb/assets/67879397/9eb7c2a6-ab7e-4eae-9f11-4378bd3c94bb">

**Comment by netravnen** [comment]
https://github.com/peeringdb/peeringdb/blob/fc5e073909a581c3f5ea6c99486806792478aa32/peeringdb_server/export_kmz.py

I might be asking a stupid dumb question. From the code I read _"It reads the facility data from a JSON file, creates a KML object, and adds points to a folder in the KML."_ ... How often is the the cached `fac-0.json` file updated?

For this particular case concerning https://www.peeringdb.com/fac/1816 - Now 'H5 Data Centers New York' - Previously '325 Hudson' - Name last updated 20 Nov 2023 - It is very confusing why the name change is not (yet) visible in the KMZ file. When it is over 2 weeks ago the name was changed by the user.

![image](https://github.com/peeringdb/peeringdb/assets/1938389/e9800345-86b9-457d-a872-73e763fa9463)

![image](https://github.com/peeringdb/peeringdb/assets/1938389/f49ee895-9037-44d9-b244-49f8185e24bf)

(Screenshot from GpsPrune, reading the KMZ file as of 2023-12-10 20:55 +00:00)

**Comment by mcmanuss8** [comment]
+1 this is confusing for users

**Comment by grizz** [comment]
@netravnen it was an issue with the cached file, you're right.

@elgaeloHub I think it's correct now, right?

This is an issue with the kmz generation caching is all.

**Comment by elgaeloHub** [comment]
Looks good now! 
<img width="641" alt="Screenshot 2023-12-20 at 10 06 48" src="https://github.com/peeringdb/peeringdb/assets/67879397/6da58ffc-5247-40a8-9a76-0d5bcf7c4bfa">
Thanks @grizz

**Comment by grizz** [comment]
Closing as resolved

**Comment by jackcarrozzo** [comment]
From PC call- sticking with current behavior of serving cached facilities KMZ; would like to improve messaging to users of KMZ dump so they are aware data is up to 24hrs old.
