### ISSUE TITLE
No type checking is done when entering LAN prefixes

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/peeringdb#148]
"ixlan_id": 1089,
  "protocol": "IPv4",
  "prefix": "2001:7f8:98::/64",
  "created": "2017-04-10T00:18:05Z",
  "updated": "2017-04-10T00:18:05Z",

**Comment by job** [comment]
@grizz no estimate yet

**Comment by grizz** [comment]
proto doesn't match version, should auto-detect

**Comment by vegu** [comment]
fixed in ce7773f
