### ISSUE TITLE
Network Registration fail results in AC action and retry failure

### ISSUE THREAD

**Issue by martinhannigan** [peeringdb/peeringdb#1481]
**Describe the bug**

While registering a net object, the email address for the WHOIS entry in an RIR was different than the email address of the person submitting. While the email address used vs. used at ARIN were different, they are the same company. However, the email address is not the issue since the "rejection" was accurate based on the tool tip. Once the automation to validate against the RIR whois took place (that took a long time) the request was noted it needed admin intervention. 

Here is the AC response: 
![Screenshot 2023-12-08 at 12 37 49 PM](https://github.com/peeringdb/peeringdb/assets/21081154/92edb297-048d-400e-b024-78706bcec306)

**To Reproduce**
Go to ORG
Click EDIT
Click ADD NETWORK
Enter ASN for network
Provide mismatched email address
Wait for status to change to intervention required
Wait for N hours telling a user their request failed and won't be proceed <--- wasted step
Re-try entry
Error message occurs: 
![Screenshot 2023-12-08 at 12 46 25 PM](https://github.com/peeringdb/peeringdb/assets/21081154/98c4954e-1ab8-437a-ac32-432b1593a56e)

**Expected behavior**

Failure should be as fast as the network RIR WHOIS information fails to pass the programmed test and user should be able to try again.

**Who is affected by the problem?**

Users adding new networks in PDB
The AC getting tickets

**What is the impact?**

User friendliness
Less AC workload
Better customer service

**Are there security concerns?**

No

**Are there privacy concerns?**

No

**What are the proposed actions?**

Automate the ADD network function that if an entry fails an automated test it expands the automation from start to finish by notifying the user of the failure and cleaning up any records that would prevent the user from trying again.

**What is the proposed priority?**

Medium

**Provide a rationale for any/all of the above**

More automation and less tickets
Faster network creation (speed of business vs. speed of volunteer)
Improved service delivery

**Comment by mcmanuss8** [comment]
+1

**Comment by peterhelmenstine** [comment]
+1 but not sure how to do this. open to suggestions

**Comment by grizz** [comment]
**Summary**

If there is a mismatch, notify the user and give them a chance to update the RIR record or their PDB email address. If that doesn't work, they should be directed to manually open a ticket with support.

+1

**Comment by martinhannigan** [comment]
+1

**Comment by martinhannigan** [comment]
Adding an additional thought on block vs. allow. Success would be higher if the domain was matched vs. the user. The purpose for admin user in PDB is to control the account and who accesses it. Presumably, any user from an ORG is able to create an object based on inherited permissions.

**Comment by grizz** [comment]
> Adding an additional thought on block vs. allow. Success would be higher if the domain was matched vs. the user. The purpose for admin user in PDB is to control the account and who accesses it. Presumably, any user from an ORG is able to create an object based on inherited permissions.

I would not assume that, it needs an exact match (based on the initial approval of this issue). That would also cause issues if there are anything other than official org domains listed, how we know which domain is official, etc etc.
