### ISSUE TITLE
Address Change UI

### ISSUE THREAD

**Issue by martinhannigan** [peeringdb/peeringdb#1483]
**Describe the bug**

When entering an address for an org an address suggestion appears. An option to reject does not appear. 

**To Reproduce**

Change address
Save
A “suggested” address option may appear
If it is not accurate or preferred, its not obvious you can reject and keep existing accurate entry

**Expected behavior**

An option to keep the address entered since the users knows if an address works or not or there is a minor nuance ( Sq. vs. Square) that is acceptable.

**Who is affected by the problem?**

Users of PDB

**What is the impact?**

Confusing UI

**Are there security concerns?**

No

**Are there privacy concerns?**

No

**What are the proposed actions?**

Allow a “Keep entered address” or “accept suggestion”  option

**What is the proposed priority?**

Low priority

**Provide a rationale for any/all of the above**

Confusing if inaccurate and data accuracy. Probably a UI issue.

**Comment by peterhelmenstine** [comment]
+1

**Comment by martinhannigan** [comment]
+1
