### ISSUE TITLE
Update ORG Social Media Option "Twitter" to "X"

### ISSUE THREAD

**Issue by martinhannigan** [peeringdb/peeringdb#1484]
**Is your feature request related to a problem? Please describe.**
Twitter has renamed itself X. The UI still references Twitter.

**Who is affected by the problem?**

Users of PDB

**What is the impact?**

Accuracy and UI only.

**Are there security concerns?**

No.

**Are there privacy concerns?**

Not here. X? Probably.

**Describe the solution you'd like**

Change "Twitter" to "X"

**Do you think this feature will require a formal design?**

No.

**Describe alternatives you've considered**

Doing nothing. Leaves an inaccuracy intact. Better do correct it.

**Could this feature request need support from the Admin Committee?**

No.

**What is the proposed priority?**

Low priority.

**Comment by peterhelmenstine** [comment]
+1

**Comment by mcmanuss8** [comment]
+1

**Comment by jackcarrozzo** [comment]
+1

**Comment by grizz** [comment]
+1

**Comment by martinhannigan** [comment]
+1
