### ISSUE TITLE
Invalid_client error on oauth

### ISSUE THREAD

**Issue by toddjcrane** [peeringdb/peeringdb#1485]
**Describe the bug**
Tried implementing OAuth per https://aaronparecki.com/oauth-2-simplified/, but received an "invalid_client" error on code exchange for access token

**To Reproduce**
```
client_secret = "<-- Redacted -->"
client_id = "<-- Redacted -->"
redirect_uri = "<-- Redacted -->"

PDB_ENDPOINT = "https://auth.peeringdb.com/"

PDB_OAUTH_ACCESS_TOKEN_URL = "{}oauth2/token/".format(PDB_ENDPOINT)
PDB_OAUTH_AUTHORIZE_URL = "{}oauth2/authorize/".format(PDB_ENDPOINT)
PDB_OAUTH_PROFILE_URL = "{}profile/v1".format(PDB_ENDPOINT)


url = "%(endpoint)s?response_type=code&client_id=%(client_id)s&redirect_uri=%(redirect_uri)s&scope=openid+email+profile+networks" % {
    "endpoint": PDB_OAUTH_AUTHORIZE_URL,
    "client_id": client_id,
    "redirect_uri": redirect_uri,
}

################################################################################################
# URL is pasted in browser, code argument is copied into terminal assigned to code variable 
################################################################################################

code = "<-- Redacted -->"

import requests

r1 = requests.post(
    PDB_OAUTH_ACCESS_TOKEN_URL,
    data={
        "grant_type": "authorization_code",
        "code": code,
        "redirect_uri": redirect_uri,
        "client_id": client_id,
        "client_secret": client_secret,
    },
)


# >>> r1
# <Response [401]>
# >>> r1.text
# '{"error": "invalid_client"}'
```
**Expected behavior**
Oauth API should give access token

**Who is affected by the problem?**
More than just us. We found a gist calling out this at https://gist.github.com/natesales/97156caf3a1276eee60c7e0fc9ca937a

**What is the impact?**
Inability to use Oauth, which prevents building a peering portal

**Are there security concerns?**
not in the way you're asking about

**Are there privacy concerns?**
no

**What are the proposed actions?**
troubleshooting on PDB's side

**What is the proposed priority?**
not urgent

**Provide a rationale for any/all of the above**
We are attempting to build a peering portal for us and a few of our clients allowing networks to view traffic and request peering

**Comment by grizz** [comment]
@toddjcrane Thanks for the report!

What is your OIDC algo set at? It should be set (`RSA with SHA-2 256` works fine) as noted at https://docs.peeringdb.com/oauth/ There is an issue, #1143, from the gist you linked that may be helpful as well.

If that doesn't fix it, could you show a full dump of that request please? (similar to https://github.com/peeringdb/peeringdb/issues/1143#issuecomment-1368375100)

**Comment by Alkanov** [comment]
I am getting the same `{'error': 'invalid_client'}` with "RSA with SHA-2 256" selected

**Comment by tszxxx** [comment]
same here, if we follow `https://support.panopto.com/s/article/How-to-Get-OAuth2-Access-Tokens-for-Users#hTargetInstance0`, we will get this error
```
{
    "meta": {
        "error": "Invalid username or password"
    }
}
```

**Comment by tszxxx** [comment]
```
curl --location 'https://auth.peeringdb.com/oauth2/token/' \
--header 'Content-Type: application/x-www-form-urlencoded' \
--data-urlencode 'grant_type=authorization_code' \
--data-urlencode 'code=?’ \
--data-urlencode 'client_id=?==' \
--data-urlencode 'client_secret=?' \
--data-urlencode 'redirect_uri=?’
```
will return invalid client

**Comment by tszxxx** [comment]
any idea on how to solve this?

**Comment by tszxxx** [comment]
@grizz do you have a way to fix it?

**Comment by Alkanov** [comment]
@grizz the original issue is still relevant. What @tszxxx reported is a different problem than the "invalid_client" we are getting. Steps to reproduce it on the first post are still valid too

**Comment by grizz** [comment]
If you have the OIDC algo set to `RSA with SHA-2 256` then `invalid_client` means you're entering in the client ID or secret incorrectly.

**Comment by tszxxx** [comment]
> If you have the OIDC algo set to `RSA with SHA-2 256` then `invalid_client` means you're entering in the client ID or secret incorrectly.

should I encrypt both clientID and clientSecret in the post request to get the access token? Or simply use it as plain text

**Comment by jackcarrozzo** [comment]
Sorry, we lack the resources to help debug client oauth impls
