### ISSUE TITLE
URL Referrer Behavior

### ISSUE THREAD

**Issue by martinhannigan** [peeringdb/peeringdb#1487]
**Is your feature request related to a problem? Please describe.**

When clicking on a URL it changes focus within the current session/tab/browser and leaves it behind instead of opening a new tab or browser session.

**Who is affected by the problem?**

Users of PDB

**What is the impact?**

Loss of focus, change of view, distracting result from click.

**Are there security concerns?**

No

**Are there privacy concerns?**

No

**Describe the solution you'd like**

When a user clicks a non peeringdb.com URL that refers them out of their current window it should open a new tab or browser.

**Do you think this feature will require a formal design?**

Uncertain

**Describe alternatives you've considered**

Doing nothing. However, that doesn't seem consistent. The behavior is distracting and one can assume when reviewing a PDB window the user is working so the distraction can be disruptive.

**Could this feature request need support from the Admin Committee?**

No

**What is the proposed priority?**

Low priority.

**Provide a rationale for any/all of the above**

Common UI behavior.

**Comment by jackcarrozzo** [comment]
+1

**Comment by mcmanuss8** [comment]
+1

**Comment by jbartig** [comment]
+1

**Comment by martinhannigan** [comment]
Doesn't appear to work in Beta.
Open PeeringDB. Click on anything. Switches page in focus.

**Comment by leovegoda** [comment]
Definitely works in release. I am closing and moving this issue to the 2.58.0 release milestone

**Comment by martinhannigan** [comment]
Doesn't work as the issue describes. See attached.  URL is a PeeringDB URL or an external URL. There's no differentiation. I believe when discussed this was also understood "changing focus".  Browser is Firefox. I believe all settings are correct to support this feature.

https://github.com/peeringdb/peeringdb/assets/21081154/2ed18500-a239-4f89-a682-e6e01fbf7766

**Comment by martinhannigan** [comment]
reopening to flag.

**Comment by martinhannigan** [comment]
Actually, in re-reading it does specify a non Peering-db URL. Should I submit a new issue to request "any"? Thanks.
