### ISSUE TITLE
Remove unneeded fields from the KMZ

### ISSUE THREAD

**Issue by grizz** [peeringdb/peeringdb#1489]
Will help to keep clutter down and the file size smaller. Currently the file is too big for google maps to use.

From #1472 

ID
Org_ID
Status
LAT/LONG (already embedded in placemark)
CLLI
NPA-NXX
Networks
Net_Count (mask to Network Count)
Ix_Count (Mask/rewrite to IX Count)
Org_Name (Mask/rewrite to Org or Organization)
Zipcode (Mask/rewrite to Zip Code or globalize..Postal Code?)
Name (Already displayed at top of box)

**Comment by martinhannigan** [comment]
+1

**Comment by mcmanuss8** [comment]
+1 trim it down is good

**Comment by grizz** [comment]
+1

**Comment by peterhelmenstine** [comment]
+1

**Comment by martinhannigan** [comment]
Comparing this and comparing what we got it seems different. Small point of information. Google Maps measures the size by the uncompressed value of the file so when facilities.kmz is currently expanded to KML it's 17.5 MB which is 12.5 MB too big. With the ability to slim down on search I would suggest we don't care about the entire file being able to be loaded into maps, but the chunks for localization. I would expect most people are using it local/regional anyhow.

**Comment by peterhelmenstine** [comment]
+1

**Comment by grizz** [comment]
I think we can drop all of the fields except a link back to the site.

This is a closed issue this, a new one should be created.

**Comment by martinhannigan** [comment]
Done.

There are useful fields to quick view. Mostly agree.

**Comment by martinhannigan** [comment]
I’m less excited about major investment in KML vs csv and json TBH.
