### ISSUE TITLE
Add LinkedIn and GitHub links to the page footer

### ISSUE THREAD

**Issue by ghankins** [peeringdb/peeringdb#149]
We missed adding LinkedIn in #136 

Need to add it too.

LinkedIn URL is: https://www.linkedin.com/company/peeringdb
GitHub URL is: https://github.com/peeringdb/peeringdb/issues

Remove the line that says: "Follow us on Social Media", so that the icons are under the version number.

**Comment by ghankins** [comment]
URL is: https://www.linkedin.com/company/peeringdb

**Comment by job** [comment]
fixed in 2f4b3978f316a8cf7352b1b8ebdf31f8374cd22e

**Comment by ghankins** [comment]
It needs to be fixed on www too.

**Comment by vegu** [comment]
fixed in ccbd5b4

**Comment by ghankins** [comment]
Thanks for adding the logos.  The LinkedIn logo looks odd because it's round and the text is black.

Can you please use one of the square logos and make the text clear so it matches the look of the Facebook logo.
https://content.linkedin.com/content/dam/brand/site/brand-assets/linkedin-in-for-screen.zip

The GitHub logo looks inverted too.  It should be like the favicon in white.
https://github-media-downloads.s3.amazonaws.com/GitHub-Mark.zip

**Comment by vegu** [comment]
fixed in 0c87c87
