### ISSUE TITLE
Add multiple KMZ files with different chunks of data

### ISSUE THREAD

**Issue by grizz** [peeringdb/peeringdb#1492]
Allow for dissection or nightly exports by $chunk

Optional all-in-1 file
Optional 7 continent file
Optional United States file

Smaller files would load into google maps, and be more performant

Broken out from #1472 - @peeringdb/pc ingdb/pc please vote.

**Comment by martinhannigan** [comment]
+1

**Comment by peterhelmenstine** [comment]
+1

**Comment by mcmanuss8** [comment]
Can we clarify what the outcome would be - would we have one for every country? Where would you get these? Is there going to be a zip with all the files?

**Comment by leovegoda** [comment]
> Can we clarify what the outcome would be - would we have one for every country? Where would you get these? Is there going to be a zip with all the files?

If we add the .KMZ export feature (https://github.com/peeringdb/peeringdb/issues/1495) in then we don't need per country files because people can run a search (which they'll be able to save, soon) for their preferred set of results.

**Comment by mcmanuss8** [comment]
Great, let's bundle these together then - I'd rather just do #1495 honestly

**Comment by grizz** [comment]
I like the idea of doing this with #1495 instead.

So -1 here, +1 #1495

**Comment by martinhannigan** [comment]
-1

**Comment by grizz** [comment]
Closing by consensus on PC call.
