### ISSUE TITLE
Enable .KMZ export for Advanced Search results

### ISSUE THREAD

**Issue by leovegoda** [peeringdb/peeringdb#1495]
**Is your feature request related to a problem? Please describe.**
The Advanced Search provides geographic results for Campuses, Exchanges, Facilities and Organizations. These can be exported as JSON or CSV. We should add .KMZ as an export option now we share all facility data in .KMZ format.

**Who is affected by the problem?**
Anyone who wants to look at data on a map.

**What is the impact?**
Improved service offering.

**Are there security concerns?**
No. This is the same data in a new format.

**Are there privacy concerns?**
No.

**Describe the solution you'd like**
Add a .KMZ export option.

**Do you think this feature will require a formal design?**
Possibly.

**Describe alternatives you've considered**
Do nothing.

**Could this feature request need support from the Admin Committee?**
It should not.

**What is the proposed priority?**
Implement in a .KMZ focused release early in 2024

**Comment by mcmanuss8** [comment]
+1

**Comment by martinhannigan** [comment]
How much resource is this going to use?

I would suggest we at least put this function behind a login account. I
could see this being used widely and by many with no direct affiliations to
PDB. Since it's only fasciitis data the parsing regionally is slick if
approved.

**Comment by leovegoda** [comment]
> How much resource is this going to use? 

Probably very similar to what we use now.

> I would suggest we at least put this function behind a login account. 

All the geographic use of Advanced Search already requires users to be logged in. This is just a new way to package the same results they are already getting.

**Comment by martinhannigan** [comment]
Resource wise I was asking about how much CPU do we burn with each output
to KML if any and we should consider moving the KML itself "inside" the
login. The data is valuable and the least we can require is for a user to
be a bonafide PDB user. We ought to think more about how we can use this
feature.

**Comment by martinhannigan** [comment]
So moving the kmz from the main page/www without auth to a page that
requires auth is a policy change?

**Comment by grizz** [comment]
+1

**Comment by leovegoda** [comment]
> So moving the kmz from the main page/www without auth to a page that requires auth is a policy change?

Requiring a login for data that does not require a login now sounds like a policy change to me. What is the advantage we get from making them login?

**Comment by martinhannigan** [comment]
I don’t recall any suggestions that it should’ve been in the public space
anyhow. Was there? I’ll send some policy suggestions to the PC. Then we can
communicate that to the board.

thanks leo!

**Comment by leovegoda** [comment]
I think the decision to put it in the footer was taken by me and 20C. We chose that because it just repackaged existing content that was already available anonymously.

**Comment by martinhannigan** [comment]
I didn't know anyone else had a KMZ. Doable vs API - buy then why would we
if someone else did it? (hint: authoritative +enterprise value)

**Comment by martinhannigan** [comment]
This isn't a bad idea overall. I'd suggest we do a cost analysis. I'm also
skeptical that outputting advanced search results into a KML will be worth
the cost to produce it e.g. "all facilities in Boston, MA". While the cost
may be small, it's not negligible or zero.

**Comment by grizz** [comment]
outputting to KML is going to be very similar to CSV. KMZ is compressed, so it would be a bit more.

**Comment by martinhannigan** [comment]
-1

**Comment by martinhannigan** [comment]
+1

**Comment by jackcarrozzo** [comment]
+1
