### ISSUE TITLE
pdb_stats needs to be updated to include Campuses, Carriers, etc. & possible bug with user counts

### ISSUE THREAD

**Issue by ccaputo** [peeringdb/peeringdb#1500]
pdb_stats needs to be updated to match the "Global System Statistics" reports on the footer of the site.

The footer currently reports:

```
Global System Statistics
1152 Exchanges
29161 Networks
5282 Facilities
40 Campuses
136 Carriers
52359 Connections to Exchanges
47611 Connections to Facilities
6632 Automated Networks
52157 Registered Users
27185 Organizations
```

while pdb_stats currently outputs:

```
2024-01-03
-------------
fac: 5282
ix: 1152
net: 29161
org: 27185
users: 41998
```

Notably missing are the numbers for new objects and new calculations: Campuses, Carriers, Connections to Exchanges, Connections to Facilities, Automated Networks.

pdb_stats is used to inform the annual infographic, so it would be good to enable the option of including this additional data going forward.

NOTE: There is also an apparent bug with the user counts, with the Global System Statistics showing a much higher number than reported by pdb_stats. Which is correct and how can the other be brought into correctness?

**Comment by ccaputo** [comment]
> NOTE: There is also an apparent bug with the user counts, with the Global System Statistics showing a much higher number than reported by pdb_stats. Which is correct and how can the other be brought into correctness?

The web page footer appears to be including Users with status "pending" in its count, while the output pdb_stats is reporting the more correct count of verified users.

https://github.com/peeringdb/peeringdb/blob/fc5e073909a581c3f5ea6c99486806792478aa32/peeringdb_server/stats.py#L51

versus:

https://github.com/peeringdb/peeringdb/blob/fc5e073909a581c3f5ea6c99486806792478aa32/peeringdb_server/management/commands/pdb_stats.py#L68-L70

**Comment by mcmanuss8** [comment]
+1 they should be consistent and include all objects

**Comment by grizz** [comment]
+1

**Comment by jackcarrozzo** [comment]
PC call: valid req, but only user of pdb_stats is seemingly ccaputo. Worth fixing pdb_stats to make same as web view.

**Comment by martinhannigan** [comment]
+1

**Comment by ccaputo** [comment]
> PC call: valid req, but only user of pdb_stats is seemingly ccaputo. Worth fixing pdb_stats to make same as web view.

I don't use the data, rather it the pdb_stats inform the yearly infographic used for fundraising. We should not be publishing inaccurate data on the web site footer.

**Comment by jackcarrozzo** [comment]
Badly summarized by me, thx @ccaputo

**Comment by arnoldnipper** [comment]
+1
