### ISSUE TITLE
Create preview.peeringdb.com with updated web UI

### ISSUE THREAD

**Issue by leovegoda** [peeringdb/peeringdb#1502]
**Is your feature request related to a problem? Please describe.**
We have an updated design for www.peeringdb.com's web UI. The updated design does not change functionality. We should present the new design to users at a new hostname so those interested can test it and provide feedback.

We'll communicate the new design in a blog post, mailing list announcements, and on social media.

**Who is affected by the problem?**
Users of www.peeringdb.com.

**What is the impact?**
Improve user experience.

**Are there security concerns?**
No.

**Are there privacy concerns?**
No.

**Describe the solution you'd like**
Share the updated design with web users on a new hostname so they can test it and provide feedback. We can then make adjustments, if needed, before deploying the new design on www.peeringdb.com.

This builds on the screen size adaptive changes in 2.54.0 (https://github.com/peeringdb/peeringdb/issues/1463)

It does not include the front page changes. They will be scheduled in a future update.

Specific changes:

1. Update background color
2. New header and footer design
3. Update table design with downwards arrow for expanding large tables
4. New export button (with export interstitial to select tables and format)
5. New tabbed design for campuses
6. Icon updates

**Do you think this feature will require a formal design?**
Yes, we have one.

**Describe alternatives you've considered**
Do nothing.

**Could this feature request need support from the Admin Committee?**
Consider if an administrator might need to provide assistance at any point.

**What is the proposed priority?**
2.55.0

**Provide a rationale for any/all of the above**
Improved the web design and avoid negative surprises to users

**Additional context**
This plan has already been accepted by the @peeringdb/pc, so I'm moving it straight to Ready for Implementation

**Comment by peterhelmenstine** [comment]
+1

**Comment by martinhannigan** [comment]
It would be great to discuss this on our upcoming PC call. We have beta and
we have this and I'm interested to learn if it might make sense to merge it
all to beta since it sounds like we would need to spend more money to
segregate them and do them in parallel.

**Comment by grizz** [comment]
Completed.
