### ISSUE TITLE
Is it possible to create an affiliation request even when the ASN (~Net) has been deleted? (But the ORG still exist)

### ISSUE THREAD

**Issue by netravnen** [peeringdb/peeringdb#1503]
**Describe the bug**
I had a weird ticket ([97124](https://peeringdb.deskpro.com/agent/#app.tickets,inbox:all,t.o:97124,vis:5)) coming in. The user was able to request affiliation with an ASN that had `status = deleted`.

The ASN (~Net) had previously been _deleted_. And was reassigned to the user in ticket 97124. (/net/21545) ([history](https://www.peeringdb.com/cp/peeringdb_server/network/21545/history/))

The organization _had not_ been deleted and still existing in PeeringDB. (/org/24323)

Does the validation that happens when a user requests affiliation with an ASN not validate against the case where `ORG_STATUS = OK && NET_STATUS = DELETED`? <-- Should IMO throw either an error to the user - That they will need to contact support@. 

**To Reproduce**
1. Go to <random_net>
2. delete <random_net>
3. log out and in with another account
4. request affiliation with the now deleted <random_net>
5. if the users experience is correct, their should now be a "stuck" affiliation request
   a. Where the current ORG admins should have been notified,
   b. and no ticket will ever have been sent to support@ due to matching the deleted net record with an existing ORG record.

**Expected behavior**
Throw an error to user about the network having been deleted. And they will need to contact support@.

**Who is affected by the problem?**
users and AC.

**What is the impact?**
user and support (AC) confusion

**Are there security concerns?**
None

**Are there privacy concerns?**
None

**What are the proposed actions?**
Throw an error when trying to request affiliation with an deleted net record.

**What is the proposed priority?**
Unable to decide.

**Provide a rationale for any/all of the above**
Looks to be a bug (~corner case) in the affiliation process validation. IMO.

**Additional context**
~~Add any other context about the problem here.~~

/cc @peeringdb/ac

**Comment by vegu** [comment]
Looks like issue is https://github.com/peeringdb/peeringdb/blob/master/peeringdb_server/signals.py#L386 not checking for `deleted` status
