### ISSUE TITLE
Addition of a security policy `SECURITY.md` to github.com/peeringdb/peeringdb

### ISSUE THREAD

**Issue by netravnen** [peeringdb/peeringdb#1504]
Do we want to enable GitHubs functionality to privately report potential code security issues via GitHub?

When reading the [docs](https://docs.peeringdb.com) I am not able to accurately identify any clear publicly available description for how to report potential code security issues to PeeringDB.

Links:

- https://github.com/peering-manager/peering-manager/security
- https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository
- https://docs.github.com/en/code-security/security-advisories/guidance-on-reporting-and-writing-information-about-vulnerabilities/privately-reporting-a-security-vulnerability
- https://github.com/microsoft/.github/blob/main/SECURITY.md

Edit: If we already have a clear channel of communication for the above mentioned suggestion. Please disregard this issue.

**Comment by leovegoda** [comment]
We have this: https://docs.peeringdb.com/howto/make-a-security-report/

We should create a SECURITY.md and point it there, I suppose.

**Comment by netravnen** [comment]
Summary suggestion:

1. Create a `SECURITY.md` file in the root of the codebase
2. Create `/.well-known/security.txt` on www.PeeringDB.com

----

Minimal `/.well-known/security.txt`

```
# Our security policy
Policy: https://docs.peeringdb.com/howto/make-a-security-report/
```

**Comment by mcmanuss8** [comment]
+1

**Comment by jackcarrozzo** [comment]
Pc call: we have the policy so we might as well put it there

+1

**Comment by jbartig** [comment]
+1

**Comment by grizz** [comment]
This still needs ops work to add the `.well-known/security.txt` file

**Comment by leovegoda** [comment]
Completed via https://github.com/peeringdb/peeringdb/pull/1567
