### ISSUE TITLE
Validation of IRR Records

### ISSUE THREAD

**Issue by dotwaffle** [peeringdb/peeringdb#151]
Many of the IRR Record fields in networks records can not be used because they are being used as free-text. It would be good to add validation to this field, perhaps just making sure the record is valid at well-trused sources on RADB or similar.

Likewise, would it make sense to have that as a once-daily updated prefix list, or is that implementor specific for their automation with bgpq3 etc?

**Comment by grizz** [comment]
Agreed, and adding a prefix list is an awesome idea.

**Comment by grizz** [comment]
Let's actually discuss this more, will at least need a schema change to list multiple as-sets

Prefix list is already handled by irrexplorer, so probably doesn't need to be duplicated here

**Comment by arnoldnipper** [comment]
and make format s.th. like AS-SET@IRR

**Comment by job** [comment]
This continues to be an issue for me, look at the insane coding that is required to try and parse the information in this datafield that is done in @pierky's arouteserver https://github.com/pierky/arouteserver/blob/eb6adaa8be512e987482b5fb8f663986c6fb9331/pierky/arouteserver/peering_db.py#L109-L176

@arnoldnipper mentioned that the source should be able to specified. I propose we allow industry conventions to co-exist: `AS-SET@SOURCE` and `SOURCE::AS-SET` - both are in use and do not conflict with each other.

Multiple AS-SETs can be comma separated.

An AS-SET should confirm to the IETF RFC naming schemes.

Valid names:
```
AS-15562
AS-SNIJDERS
AS15562:AS-SNIJDERS
AS15562
RS-SNIJDERS
AS15562:RS-SNIJDERS
AS-15562:AS-SNIJDERS
```

invalid:
```
AS 15562
AS+SNIJDERS
RIPE AS15562
V6 AS-SNIJDERS
```

**Comment by job** [comment]
@nopedial can you list an overview of all invalid ones that you found in your recent scan? We can use those as input to the unittesting

**Comment by job** [comment]
@nopedial can you list an overview of all invalid ones that you found in your recent scan? We can use those as input to the unittesting

**Comment by grizz** [comment]
Both formats is fine, but let's make it an actual set and validate on input? We could use the current field as input and add a parsed output field for now.

**Comment by stillwaxin** [comment]
@job your example list does not include these types: RIPE::AS-FOO or AS-FOO@RIPE but your text seems to identify them as potentially being valid. Should this be clarified?

**Comment by job** [comment]
good point, my overview was meant for just the "AS-SET" name parsing, but
in the full testing suite those variations should indeed be included as
well.

invalid: `RIPE::AS-SNIJDERS@ARIN`

**Comment by pierky** [comment]
I'd add the `AS1:AS-FOO:AS-BAR` form to the list of valid names. AFAIK there's not a limit to the number of names that can be concatenated in the hierarchy: I've encountered names made up by 3 parts, but I don't remember anything longer than that.

**Comment by job** [comment]
excellent

**Comment by as44980** [comment]
If the AS-SET (or route-set) is being parsed for validation could it be worth taking it a step further to calculate the number of prefixes with valid route objects contained within the specified AS-SET and displaying this alongside the user submited IPv4/IPv4 Prefixes values?

**Comment by as44980** [comment]
Arnold,

While I agree with 2), I am particularly interested in the results of 1) as this may highlight that there are  networks who populate the ipv/ipv6 prefixes field with values that are several orders of magnitude higher than what they actually announce, or even the number if valid route object in their expanded as-set, thus devualing the data for peers who seek to use this to configure appropriate max-prefix values :(

**Comment by arnoldnipper** [comment]
Paul, iirc these were my findings from years ago when I also thought this might be a good approach to calculate max-pref. Also anyone is absolutely free to include anything in his AS-SET. It literally does not really mean anything. Best PDB can do is to check whether the IRR record is syntactically correct and exists. But, just my .02€

**Comment by devicenull** [comment]
We've run into this as well, we're trying to automation generation of prefix lists, but the data in this field is.. interesting.  I see URLs, random strings, and my favorite, the string "NONE"

Even RIPE seemed to mess this up: https://www.peeringdb.com/net/3859

**Comment by arnoldnipper** [comment]
> Even RIPE seemed to mess this up: https://www.peeringdb.com/net/3859

Hmmm ... as ASN are using different policies at different peerings what really is the meaning of IRR Record then? If we already are cleaning up this entry then we should make it really **useful** imho

**Comment by devicenull** [comment]
They've sneakily changed it since I posted ;)

It used to be 'RS-AUTHDNS*'.

IMHO even enforcing that this is a valid AS-SET would be a significant step up from what's there now.  Sure, you could have different AS-SETs per peer, but that's presumably something you would communicate to people on a per-peer basis.

**Comment by arnoldnipper** [comment]
Would it make sense to allow to add @/net/xxxxx or @/ix/yyyyy, where xxxxx and yyyyy are net_id resp. IX_id? In the given example that's exactly what the different AS-SETs are for. Or is this to complicated?

**Comment by as44980** [comment]
Given that the field appears to be called "IRR Record" rather than "IRR Record**s**", personally I would to see the input for this validated to ensure that it contains only a single string...

And if this could be further validated to only permit a string which could conceivably match any of the set names defined in [RFC2280](https://tools.ietf.org/html/rfc2280#section-5) that would be even more useful ;)

**Comment by job** [comment]
This field should not be free text, and there are existing definitions of what valid IRR names are.

**Comment by as44980** [comment]
> "Valid" meaning "exists in at least one IRR database"

Should we consider "Syntaxically valid" as a more practical than attempting to confirm that user provided string coresponds to a record contained in one of the many IIR databases, and thus avoiding the decision about which of these databases should be consulted? ;)

**Comment by devicenull** [comment]
That sounds like a perfectly reasonable choice.  Even making sure they're just syntactically valid is a huge step forward

**Comment by arnoldnipper** [comment]
I'm still missing an answer to my question: what is the purpose of this field? Do people want to generate ACLs from it? If so then syntactically  is not enough. And as we have seen networks are using multiple and different AS-SETs. Hence I would see a need to add further information to the AS-SET

**Comment by job** [comment]
On Wed, May 9, 2018 at 6:32 PM, Arnold Nipper <notifications@github.com>
wrote:

> I'm still missing an answer to my question: what is the purpose of this
> field? Do people want to generate ACLs from it?
>

Yes, organisations and automation use this field as a starting point to
generate ACLs.


> If so then syntactically is not enough.
>

But it is a starting point.


> And as we have seen networks are using multiple and different AS-SETs.
> Hence I would see a need to add further information to the AS-SET
>

I agree that there are unresolved issues here, but just fixing syntax (and
perhaps allowing multiple IRR records per network record) is such low
hanging fruit that we should be doing _something_ here. It does not yet
need to be perfect, the problem space is complex - but free form text
certainly is not the answer here.

**Comment by arnoldnipper** [comment]
+1 .. let's start with just checking syntactical correctness. AC will be happy to take the task

**Comment by stillwaxin** [comment]
If multiple records are allowed what will be the delimiter to indicate such? I agree that stretch goal can be to actually look up the record and validate its existence.  Operations around generating suggested prefix-limits, as-path filters, and prefix-lists sound very useful but is there real demand for this from this platform or would other tools outside of PDB better be used for that function?

**Comment by as44980** [comment]
`I agree that stretch goal can be to actually look up the record and validate its existence.`

Although IMHO this would be nice to have, its probably worth having clear idea of scope as the assurance of syntactically valid data in the short term seems to be an easy win.

Also its clear that some networks may wish to use multiple AS-SETs, perhaps relating to geography or v4/v6, but in the context of automation it doesn't seem very useful for a field which is described as "IRR Record" (singular) to be permitted to contain multiple records... which to use?  ;)

It strikes me as having similarities to the use of a single PDB record to reflect peering with multiple ASN's, in which case is it worth considering if there is demand for the ability for a network to specify which IIR record a peer should use on a per-IX basis?

**Comment by job** [comment]
Let’s handle stretch goals in separate GitHub issues. I want us to get a
MVP here.

**Comment by arnoldnipper** [comment]
> It strikes me as having similarities to the use of a single PDB record to reflect peering with multiple 
> ASN's, in which case is it worth considering if there is demand for the ability for a network to specify
> which IIR record a peer should use on a per-IX basis?

I already brought this up, @as44980  ... s.th. like @/net/xxxxx or @/ix/yyyyy could be a solution

**Comment by dotwaffle** [comment]
I would have thought it would make more sense to encourage networks to set their "member-of:" field in their IRR aut-num record, rather than encouraging data duplication in PeeringDB. Would that not make better sense?

From the RIPE [page](https://www.ripe.net/manage-ips-and-asns/db/support/documentation/ripe-database-documentation/rpsl-object-types/4-2-descriptions-of-primary-objects/4-2-1-description-of-the-aut-num-object):

> "member-of:" - references a set object that this AS wants to be a member of. This membership claim must be acknowledged by a respective "mbrs-by-ref:" attribute in the referenced set object.

From RPSL RFC2622 [as-set](https://tools.ietf.org/html/rfc2622#section-5.1) and [aut-num](https://tools.ietf.org/html/rfc2622#section-6):

> The mbrs-by-ref attribute is a list of maintainer names or the keyword ANY.  If this attribute is used, the AS set also includes ASes whose aut-num objects are registered by one of these maintainers and whose member-of attribute refers to the name of this AS set.

**Comment by job** [comment]
Let's not change the semantics or the way operations are done these days.
Please take it from me how the field is used today. Let's not invent new
things in this ticket.

**Comment by job** [comment]
Most networks have one AS-SET for everything, for ease of operations.
PeeringDB in spirit always accommodated just one record, that people shoved
in multiple sets separated by commas or whitespaces was not intended.
PeeringDB so far has never had a 'per region per ix or per session'
granularity, if we want this it needs to go in a new ticket.

**Comment by as44980** [comment]
> That would be a NEW feature. Feel free to open a NEW github issue.
>
> This ticket should focus on the minimum viable enhancement of making the data syntactically correct.

In that case, presumably changing the currently single "IRR Record" value per network to support multiple records in any form would also be a separate issue?  ;)

**Comment by arnoldnipper** [comment]
Do we all agree, that we want to

 * get the `irr_as_set` field checked for syntactical correctness

 * get rid of data which is not syntactical correct and can not easily be corrected

I've attached a list of imho syntactical incorrect entries
[1526989363-irr-pdb.txt](https://github.com/peeringdb/peeringdb/files/2026411/1526989363-irr-pdb.txt)

**Comment by job** [comment]
Arnold - looks good.

One more question: should we allow multiple IRR records? So that
existing networks that list multiple AS-SETs can keep doing that?

**Comment by arnoldnipper** [comment]
@job imho we should allow multiple records. There are not so many atm. And AC will make sure that these records are separated by white space (i.e. blank I guess) only. We already have updated records where users used "/" as a seperator

**Comment by as44980** [comment]
IMHO failing to take the oppertunity to make this field something which can be reliably parsed with automation would be a shame..

It seems there is consensous that allowing networks to indicate which AS-SET is announced at any given location is out of scope of this issue, would it be possible to get a count of how many networks have populated the "IRR Record" field with more than a single syntaxically valid AS-SET?

ie how much of a corner case is this, and is it worth limititing the usefulness of this data for the majority in order to allow a minority to display some information that arguably would be better placed in the notes section?

**Comment by as44980** [comment]
Yes that may well be the least cornery of the multiple AS-SET cases, in which case would it be worth considering adding a second field for "IPv6 IIR Record" leaving the exsting field for a single, syntaxically valid, IIR record that can either represent dual stack or IPv4 only?

I have no idea if (m)any networks would find it useful to indicate that they expect to advertise prefixes represented by a different as-set or route-set on a per location, per IX or per IX port basis... 

And only really considered it on the basis that if networks feel the need to use more than one AS-SET then I would really like to be able to reliably establish which of these I should be using should I opt to filter the prefixes they send to me based on their published IIR data :)

**Comment by arnoldnipper** [comment]
@as44980 

> It seems there is consensous that allowing networks to indicate which AS-SET is announced at any 
> given location is out of scope of this issue, would it be possible to get a count of how many networks 
> have populated the "IRR Record" field with more than a single syntaxically valid AS-SET?

   4248 1
        92 2
          2 3
          1 5
I.e. 4248 have just 1 AS-SET, 92 2 AS-SETs, 2 3 AS-SETs and 1 has 5 AS-SETs

And remember scope of this issue simply is to make sure that any value is a syntactically correct AS-SET. Or multiples of it. Or RS-SETs.

We also can identify 670 incorrect entries.

**Comment by grizz** [comment]
@arnoldnipper is a command line tool to make a list of invalid entries an acceptable solution for the AC?

**Comment by as44980** [comment]
@arnoldnipper 

Ahh interesting numbers, thanks for sharing..

From that do we think its reasonable to assume that 3+ valid AS-SET's make up a sufficiently low proprtion of the data they can safely be considered corner cases?

And of the 92 networks with 2 valid AS-SET's, does it look like the majority are using this to reflect different AS-SET's for IPv4/6?

If so should we consider a second optional field for those networks who do wish to indicate a different AS-SET to represent their IPv6 announcements?

Regards :)

**Comment by arnoldnipper** [comment]
@grizz 

> @arnoldnipper is a command line tool to make a list of invalid entries an acceptable solution for
> the AC?

I've already cleaned up the IRR records. Those records that are still syntactically incorrect should be removed imho. I guess it should be easy to remove these when I provide the net_ids. Right?

**Comment by arnoldnipper** [comment]
@as44980 

> And of the 92 networks with 2 valid AS-SET's, does it look like the majority are using this to reflect 
> different AS-SET's for IPv4/6?

see file attached.
[1527197511-net-with-two-as-sets.txt](https://github.com/peeringdb/peeringdb/files/2037180/1527197511-net-with-two-as-sets.txt)

**Comment by grizz** [comment]
@arnoldnipper awesome, thanks! I think it will be best to implement the syntax checking, and then we'll do a quick CLI that shows records that don't pass

**Comment by as44980** [comment]
thanks @arnoldnipper

```
# FILE="1527197511-net-with-two-as-sets.txt" ; STRINGS=". v6 6" ; for STRING in $STRINGS ; do echo -en "$STRING:\t" ;  cat $FILE | gawk -F "," '{print $2}' | egrep -ic "$STRING" ; done
.:	90
v6:	47
6:	78
```

Seems like the majority of these networks with a second, syntactically valid, record are indicating they may be announcing a different set of downstream ASN's in IPv6..

Leaving a dozen or so which do not contain the number 6 in their iir_as_set field:

```
# cat $FILE | gawk -F "," '{print $2}' | egrep -iv 6 
irr_as_set
RADB::AS-PACNET RADB::AS-ANC
AS5413:AS-CUSTOMER AS5413:RS-CUSTOMER
AS-NEXELLENT AS-NEXELLENT-CUST
AS-GARR AS-GARRTOGEANT
RIPE::AS-QUBE ARIN::AS-QUBE-US
RIPE::AS-DATAPHONE RIPE::AS-DATAPHONESE
APNIC::AS23947:AS-MORATEL APNIC::AS23947
RIPE::AS-W-IX RIPE::AS-W-IX-IPVSIX
RIPE::AS-CYTANET RIPE::AS-CYTAHELLAS
NTTCOM::AS-5713 NTTCOM::AS-5713-ZA
AS-INTERNETCZ AS-INTCZ-NIX

```

So should we consider a second optional field for those networks who do wish to indicate a different AS-SET to represent their IPv6 announcements? (as a separate issue)

**Comment by job** [comment]
On the flip side you can argue that peeringdb never had an AFI field, so
why start now? If we offer the users a list of syntactically correct
AS-SETs it is already an improvement over the situation today, and easy
to understand.

**Comment by as44980** [comment]
I agree syntax validation will be a useful addition, but by no means the only thing which can add value.. so have raised #314 to continue this strand of discussion..

And while PeeringDB may not have specific AFI fields, the ability to specify ASN on a per session, and thus per AFI, provides a  means to do so and probably reflects the real world that some networks may for whatever reasons do things differently between address families :)

**Comment by arnoldnipper** [comment]
> So should we consider a second optional field for those networks who do wish to indicate a
>  different AS-SET to represent their IPv6 announcements? (as a separate issue)

This is not part of this issue , @as44980

**Comment by as44980** [comment]
@arnold I figured the "(as a separate issue)" part made it clear I was not suggesting this to be "part of this issue", but rather trying to establish if there was any value in opening a separate issue ticket..

but if even discussing the fact that something is off-topic is off-topic then I will raise new issues for anything which might risk falling afoul of this, hence have opened #315

**Comment by job** [comment]
how can we move this forward?

**Comment by grizz** [comment]
@job have PC make a decision? :)

**Comment by durkovic** [comment]
I think it would make sense to unify the procedures used in PeeringDB and json exports.
In json we have:

```
      "connection_list": [
        {
          "vlan_list": [
            {
              "ipv4": {
                "address": "x.x.x.x"
                "as_macro": "as-set",
                "max_prefix": 10000,
                "routeserver": true,
              },
              "ipv6": {
                "address": "x:x:x::x"
                "as_macro": "as-set-v6",
                "max_prefix": 3000,
                "routeserver": true,
              }
```
In PeeringDB, there's already separate info about IPv4 prefixes and IPv6 prefixes, but only one IRR record. So proceeding with this ticket, together with #314 and #315 will provide the unification.

**Comment by grizz** [comment]
@durkovic I like that idea, it should be a separate issue however.

**Comment by devicenull** [comment]
Maybe setting a placeholder attribute for this field of 'AS-EXAMPLE' would be a good start (that's super quick to implement)?

**Comment by job** [comment]
Adding a validator is just a few lines of code (which we can copy from IRRd4) I’m inclined to write an implementation and seek consensus from the PC to merge it as written

**Comment by mcmanuss8** [comment]
Sounds like we have consensus that we should have a validator in general, but not necessarily alignment on what format it should be validating. @job do you want to propose a format and contribute the code or just propose the format?

**Comment by arnoldnipper** [comment]
An issue to solve still is whether we allow more than one IRR record. The format itself seem to be clear afair. IRR::AS-SET.

**Comment by arnoldnipper** [comment]
To move this issue a bit forward. To summarize

 * This issue only deals with the syntax and validation

 * Suggestion is to have a per AFI (IPv4, IPv6) IRR as-set/route-set field

 * Format is IRR::{AS-SET,ROUTE-SET}

 * Valid IRR may be found at http://www.irr.net/docs/list.html

@peeringdb/pc  please make up your mind

**Comment by grizz** [comment]
I'd really like to see the validation get implemented, but I'm not sure I agree with adding a per AFI field. Why bother? What would we do with the existing one? Make it a union of both?

**Comment by job** [comment]
I’m also of two minds about whether two fields operationally is useful or
not. We’ve survived this long without it, and most companies strive for
parity between ipv6 and ipv4, meaning the same as-sets are used. For most
users this is an extra field to copy+paste data into that already existed
elsewhere.

The validation rules can be copied from the irrd4 source code :-)

**Comment by grizz** [comment]
> The validation rules can be copied from the irrd4 source code :-)

+1, that'll work fine for the validation part

**Comment by arnoldnipper** [comment]
> I'd really like to see the validation get implemented, but I'm not sure I agree with adding a per AFI field. Why bother? What would we do with the existing one? Make it a union of both?

Maybe you changed your mind. On Dec 7, 2018 you supported the idea of making the distinction between IPv4 and IPv6. While in general I'm with you and @job that people shouldn't distinguish between v4 and v6 we still have rules which clearly apply to v6 only. Distinguishing would also give more value to the field. The IRR as-set/route-set may only have a single value.

Cleaning up can be done semi-automatically. For the rest I'm happy to talk to each customer with my AC hat on.

**Comment by grizz** [comment]
I still think it's a good idea, and I like @durkovic's idea of putting it on the IX record, but to push this ticket through, let's just start with validation on the existing field, and then make another issue to decide what / if we want to change the field.

Implementation wise, validation would be completely separate, @arnoldnipper is there a reason you're thinking of to do both at the same time?

**Comment by arnoldnipper** [comment]
> Implementation wise, validation would be completely separate, @arnoldnipper is there a reason you're thinking of to do both at the same time?

@grizz the reason is because of the format. If we don't split, the format would be IRR::(as-set|route-set){0,2}. If we allow for an extra IPv6 field IRR::(as-set|route-set){0,1}

**Comment by arnoldnipper** [comment]
Summarize: to be able to validate an IRR as-set/rs-set, following rules apply

 * the as-set/rs-set name has to conform to RFC 2622 (5.1 and 5.2)
 * the source may be specified by `AS-SET@SOURCE` or `SOURCE::AS-SET` (preferred)
 * valid sources can be found [here](http://www.irr.net/docs/list.html)
 * multiple values must be separated by either `,`, ` `, or `, ` (i.e. comma, space or comma followed by space)

@peeringdb/pc, please vote

**Comment by arnoldnipper** [comment]
+1

**Comment by shane-kerr** [comment]
+1

Personally I would prefer a single way of representing the data, since it means that every automated system reading the data now has to implement the full set of options. But I don't feel very strongly about it.

**Comment by job** [comment]
> Summarize: to be able to validate an IRR as-set/rs-set, following rules apply
> 
> * the as-set/rs-set name has to conform to RFC 2622 (5.1 and 5.2)
> * the source may be specified by `AS-SET@SOURCE` or `SOURCE::AS-SET` (preferred)
> * valid sources can be found [here](http://www.irr.net/docs/list.html)
> * multiple values must be separated by either `,`, ` `, or `, ` (i.e. comma, space or comma followed by space)
> 
> @peeringdb/pc, please vote

+1

**Comment by mcmanuss8** [comment]
+1 Let's move this forward

**Comment by arnoldnipper** [comment]
**Release Notes**

To make the IRR as-set/route-set field of more operational value, strict rules apply

 * the as-set/rs-set name has to conform to RFC 2622 (5.1 and 5.2)
 * the source may be specified by `AS-SET@SOURCE` or `SOURCE::AS-SET` (preferred)
 * valid sources are taken from the [list](http://www.irr.net/docs/list.html) of known IRRs
 * multiple values must be separated by either `,`, ` `, or `, ` (i.e. comma, space or comma followed by space)
