### ISSUE TITLE
Mobile interface front page has lots of misaligned sections

### ISSUE THREAD

**Issue by benjojo** [peeringdb/peeringdb#1513]
**Describe the bug**
When loading the PeeringDB interface from a mobile phone,  it appears that many of the website elements are misaligned in a way that seems very broken,  or at best a very suboptimal use of valuable mobile screen space 

**To Reproduce**
1. Load peeringdb.com on a Google Pixel 7 (or similar screen size)

5. ![WhatsApp Image 2024-01-24 at 12 46 45](https://github.com/peeringdb/peeringdb/assets/1504626/fe48940b-ee08-49b0-8249-1b0743ae7c98)

**Expected behavior**
When loading PeeringDB on a mobile phone,  to be provided with a more compact and “straight to the point” user interface

**Who is affected by the problem?**
Mobile users who have not been provided with a link to PeeringDB

**What are the proposed actions?**

An example of a more human friendly interface would be the following ( some small modifications that I made with chrome developer tools using the same screen size as a Google Pixel 7)

![image](https://github.com/peeringdb/peeringdb/assets/1504626/d56888b7-929a-4c6a-89cc-6a4a581b19f6)

Here I made the HTML headings one step larger to make it clear to mobile users (and potentially users with less than optimal eyesight/vision) the difference between the H3 and H4. 

I also exposed to the search box straight away (Since mobile users have fat fingers and would potentially miss the magnifying glass adding to further frustration with the website) and hid away the language selector which would not be used for most users at most times ( you could move that to the bottom if necessary ),  I also move the “hamburger” menu away because I don't believe there's an easy way of placing that ( at least not in the 30 seconds I spent in the Chrome developer tools)

**Comment by job** [comment]
Looks misaligned on iPhone too

![IMG_0598](https://github.com/peeringdb/peeringdb/assets/153816/0c755111-c829-4139-bb54-5a8e8a39620c)
