### ISSUE TITLE
Add PeeringDB beta logo to beta.peeringdb.com

### ISSUE THREAD

**Issue by ghankins** [peeringdb/peeringdb#152]
![pdb-beta-logo-2-0](https://cloud.githubusercontent.com/assets/8171907/25252859/9a0caf90-25ec-11e7-98d4-7e23aa2fea3e.png)

This image is the same size and can be dropped in to
https://beta.peeringdb.com/s//logo-2-0.png

**Comment by grizz** [comment]
@ghankins done now as a temporary fix, will add to the beta deploy for the next release

**Comment by grizz** [comment]
Fixed in 2289fc
