### ISSUE TITLE
Collection of atrocious website changes

### ISSUE THREAD

**Issue by eb0815** [peeringdb/peeringdb#1521]
This is to address all the awful decisions plus the bugs that have arisen from the latest website changes.
Please add to this thread, I'm certain I don't see all the parts of pdb each day and will miss a lot.

I have been super disappointed and annoyed at the latest changes (around 23 January 2024) on the peeringdb.com webpages.
Somebody seems to have decided NOT to ask people who use the site, but instead call a design team to make things "more trendy and add lots of whitespace". IMHO, peeringdb is not a design competition, it is a tool that people, esp. techies, use every day, and it should reflect that. In the past, up until this last change, this has held mostly, and the site was usable. This last redesign is unfortunately detrimental to usability and should be reverted immediately. A discussion with the users at large must be engaged with before trying another attempt at making it "modern and stylish" (essentially crufted and inefficient).

Here's what I stumbled across in the first two minutes. I would like a response from the team to EACH ONE of the issues.

1. Start page, and basically every page: Search
  The search input field is hidden and the magnifying glass needs to be clicked to reveal it. Once it has been revealed, input is not focused on the input field, so it needs to be clicked again before you can enter your search string.
 TODO: Revert to the old version with a search input field and skip the icon shit.

2. Start page, and basically every page: Language selector
  It's nice to have a dropdown for language selection. Albeit, this does not indicate that it's a dropdown.
  TODO: Use proper UI elements and skip design-focused customisation, so people can easily see this is a dropdown.

3. Pages with lists of ASNs, IPs, etc. - e.g., IXP pages
  The table to the right that lists ASNs, IPs, etc. is formatted wrongly and produces linebreaks unnecessarily that make content (a) harder to read and (b) fits less on the screen.
  TODO: Fix algorithms.

4. Entity pages - discovered on the "NET" page for an ASN
  Somebody introduces another search field in the main part of the page. This is not only unnecessarily taking up A LOT of space (because of the odd choice of sizes, fonts, and whitespace), but is also confusing; there is a search present in the page header.
  TODO: Just remove this kind of unnecessary cruft.

**Comment by mustangthz** [comment]
Can you please check https://dev6.20c.com:8037 and see if all of your concerns are addressed?

**Comment by eb0815** [comment]
Hi mustangthz,

thank you! This looks SO much better,

...except for the tables. Let me attach just a screenshot from the DE-CIX Frankfurt page, so you know what happens (on a stock MAC, current Firefox; different browsers look slightly different). I believe there's too much padding.
<img width="576" alt="Screenshot 2024-01-26 at 16 20 19" src="https://github.com/peeringdb/peeringdb/assets/38104234/09d36239-10a5-4853-814c-8da1aaa42b04">

**Comment by eb0815** [comment]
(Oh, and maybe somebody reserved an entire column for the "filter" field instead of doing a colspan.

**Comment by mustangthz** [comment]
Thanks for the feedback!

**Comment by leovegoda** [comment]
Addressed through https://github.com/peeringdb/peeringdb/pull/1529
