### ISSUE TITLE
Search error and not returning data

### ISSUE THREAD

**Issue by martinhannigan** [peeringdb/peeringdb#1525]
**Describe the bug**

Search throws django error, search returns no data

**To Reproduce**

Enter any term
Press enter to search
no data returns or django error

**Expected behavior**

Data returns or notice that no data exists for query

**Who is affected by the problem?**

Everyone

**What is the impact?**

No search

**What are the proposed actions?**

Diagnose, repair.

**What is the proposed priority?**

Probably urgent

<img width="686" alt="Screen Shot 2024-01-26 at 11 25 10 PM" src="https://github.com/peeringdb/peeringdb/assets/21081154/33d50908-c381-490f-8493-0135ee551ad2">

**Comment by leovegoda** [comment]
Addressed through https://github.com/peeringdb/peeringdb/pull/1529
