### ISSUE TITLE
Search doesn't transition from an object

### ISSUE THREAD

**Issue by martinhannigan** [peeringdb/peeringdb#1526]
**Describe the bug**
Search stops working while on an object

**To Reproduce**
Go to www.peeringdb.com
Hit the [magnifying glass](https://github.com/peeringdb/peeringdb/issues/1523)
Enter Equinix [ press enter ]
Click on first entry returned, the Amsterdam ix object
Enter Digital in the search box. Press enter or hit the [magnifying glass](https://github.com/peeringdb/peeringdb/issues/1523)

**Expected behavior**
Results containing Digital appear. 

**Who is affected by the problem?**

Everyone

**What is the impact?**

Search not working as expected or designed

**Are there security concerns?**

No

**Are there privacy concerns?**

No

**What are the proposed actions?**

Diagnose, repair.

**What is the proposed priority?**

Urgent

**Comment by leovegoda** [comment]
Addressed through https://github.com/peeringdb/peeringdb/pull/1529
