### ISSUE TITLE
pdb_rir_status task errors on deskpro ticket creation

### ISSUE THREAD

**Issue by vegu** [peeringdb/peeringdb#1528]
**Describe the bug**
the `pdb_rir_status` command has certain conditions under which it will attempt to create a deskpro ticket.

Currently this call to the deskpro api is broken since it needs to either specify a user or an email for the ticket creation, which the `pdb_rir_status` command currently does not.

Fix should be to set an email address on the ticket it creates.

**Who is affected by the problem?**

We cannot run the `pdb_rir_status` command until fixed, since the faulty ticket it creates will block the deskpro ticket submission queue.

Thus the `pdb_rir_status` job has been turned off on production until this issue is resolved.

While the job is turned off network's rir_status values will not be updated.

**Comment by arnoldnipper** [comment]
This was already addressed in #302 and #309

**Comment by vegu** [comment]
The ticket created by pdb_rir_status is not tied to any user. DeskPRO requires a customer relationship either through user object or an email address.
