### ISSUE TITLE
Add Version Number to Beta code for Beta.Peeringdb.com

### ISSUE THREAD

**Issue by martinhannigan** [peeringdb/peeringdb#1535]
**Is your feature request related to a problem? Please describe.**

Just saw a github notice about a new Beta live oad. Went to the version and wondered what version it was? No indicator.

**Who is affected by the problem?**

Beta users.

**What is the impact?**

Ineffective troubleshooting that could confuse issues.

**Are there security concerns?**

Doubtful

**Are there privacy concerns?**

Doubtful

**Describe the solution you'd like**

Add a version number at the top of the page making it clear what version of code we're testing.

**Do you think this feature will require a formal design?**

No. At least I hope not.

**Describe alternatives you've considered**
Doing nothing. Maintains status quo.

**Could this feature request need support from the Admin Committee?**

No. Could only help.

**What is the proposed priority?**

Should decide

**Comment by jackcarrozzo** [comment]
+1

**Comment by martinhannigan** [comment]
There is a version number. See attached. I'd suggest for beta we push it up and make it more prominent. Thanks!

![Screenshot 2024-01-30 at 7 14 50 PM](https://github.com/peeringdb/peeringdb/assets/21081154/3e1b3a10-0181-40c0-86da-0ecdfd8ac6c1)

**Comment by jackcarrozzo** [comment]
PC call: doesn't seem as though this info adds any value

**Comment by martinhannigan** [comment]
its already there
