### ISSUE TITLE
v2 search: 500 error when last character is a colon

### ISSUE THREAD

**Issue by leovegoda** [peeringdb/peeringdb#1546]
**Describe the bug**
v2 search returns a 500 error when the last character in the search query is a colon.

This appears to happen when the colon is next to another character and not when it appears after a space.

**To Reproduce**
1. Go to https://www.peeringdb.com/
2. Search for `test search:`
3. Seer 500 error

<img width="533" alt="Screenshot 2024-02-08 at 07 50 00" src="https://github.com/peeringdb/peeringdb/assets/59064677/311c85d7-b8ec-46da-a1fc-e58aed43422d">

4. Go to https://www.peeringdb.com/
5. Search for `test search :`
6. Get results

<img width="981" alt="Screenshot 2024-02-08 at 07 51 13" src="https://github.com/peeringdb/peeringdb/assets/59064677/e2268572-be85-4788-9f58-397c33465919">

**Expected behavior**
A small typo should not result in a 500 error

**Who is affected by the problem?**
Web search users

**What is the impact?**
Bad user experience, confusion

**Are there security concerns?**
Probably not

**Are there privacy concerns?**
No

**What are the proposed actions?**
Fix the bug

**What is the proposed priority?**
High, so we can decommission legacy search

**Provide a rationale for any/all of the above**
We want to decommission legacy search and must fix bugs in v2 search so it can be our main search offer

**Comment by arnoldnipper** [comment]
+1

**Comment by mcmanuss8** [comment]
We don’t need to vote on clear bugs. Let’s fix asap though please -SteveOn Feb 9, 2024, at 7:32 PM, Arnold Nipper ***@***.***> wrote:﻿
@peeringdb/pc, please +1 as this clearly is a bug

**Comment by arnoldnipper** [comment]
> We don’t need to vote on clear bugs. Let’s fix asap though please -

I was always waiting for a developer to assert ... but yes, I fully agree.

**Comment by jackcarrozzo** [comment]
+1 nonetheless 😎
