### ISSUE TITLE
Remove "Media Type" field for Internet Exchange object

### ISSUE THREAD

**Issue by martinhannigan** [peeringdb/peeringdb#1555]
**Is your feature request related to a problem? Please describe.**

<img width="496" alt="Screen Shot 2024-02-22 at 12 49 23 AM" src="https://github.com/peeringdb/peeringdb/assets/21081154/55526066-4359-4942-bb36-8a4297c57681">

The choices are Ethernet, ATM, or Multiple. Logically, multiple means Ethernet+ATM. One could get distracted by the label "Media Type" and we will rathole quickly. 

"Media type" may have been inadvertently used, but since ATM and Ethernet are both layer 2 data link protocols, its crystal clear what the intent was. Typically, media type would be more akin to copper or fiber types vs. protocols

Anyone using ATM please raise your hand.

**Who is affected by the problem?**

I would suggest these are entry config errors caused by the confusing options.

https://www.peeringdb.com/advanced_search?media__in=Multiple&reftag=ix

**What is the impact?**

Recovered screen real estate for other useful things.  Removing an unclear option "media type". Less bad configuration. Less transmission of useless data to screens.

**Are there security concerns?**

Not at all.

**Are there privacy concerns?**

No

**Describe the solution you'd like**

Check records. Draw conclusions. Affirm issue. Remove data. Remove the media type entirely from PeeringDB. 

**Do you think this feature will require a formal design?**

No.

**Could this feature request need support from the Admin Committee?**

No

**What is the proposed priority?**

Low, but if we need the screen real estate for something else sooner than later, perhaps consider this as low hanging fruit after the data study.

**Comment by arnoldnipper** [comment]
There are still some L3 IXes around. However, this field didn't even make sense when we launced PDB v2. We should get rid of it in v3. +1

**Comment by martinhannigan** [comment]
On Sun, Feb 25, 2024 at 12:28 Arnold Nipper ***@***.***>
wrote:

> There are still some L3 IXes around. However, this field didn't even make
> sense when we launced PDB v2. We should get rid of it in v3. +1
>
>
Who are these L3 IX in PDB?

**Comment by arnoldnipper** [comment]
e.g. https://www.peeringdb.com/ix/393

**Comment by martinhannigan** [comment]
I cant find any standard (OIX, other) which defines a router as an IX.

**Comment by grizz** [comment]
+1

**Comment by mcmanuss8** [comment]
+1

**Comment by arnoldnipper** [comment]
> Remove permanently for v3 #625

+1

**Comment by martinhannigan** [comment]
+1
