### ISSUE TITLE
Add trust flag to accounts in PDB Deskpro tool to improve automation

### ISSUE THREAD

**Issue by martinhannigan** [peeringdb/peeringdb#1560]
**Is your feature request related to a problem? Please describe.**

Add a trust flag in deskpro so we can use it to automate inbound object creations.

**Who is affected by the problem?**

PDB Admins

**What is the impact?**

Lower workload, improve efficiency

**Are there security concerns?**

No, to the contrary. Likely to improve security

**Are there privacy concerns?**

No, user account data is private.

**Describe the solution you'd like**

Create a field in deskpro where a user can be assigned a trust flag if warranted. Such as successfully created a fac object previously AND has continued to maintain trust in the peeringdb community with good data.

**Do you think this feature will require a formal design?**

Yes. Not certain if this is a 20C opportunity or something separate with DeskPro

**Describe alternatives you've considered**

StatusQuo. Seems terrible.

**Could this feature request need support from the Admin Committee?**

Yes

**What is the proposed priority?**

Urgent

**Provide a rationale for any/all of the above**

A trust flag is likely to automated more process to successful closure and sort out the bad for human intervention. Hopefully results in reduction of AC ticket load. There's also an opex benefit reducing workload across the AC and especially when size or efficiency slides up and down for various understandable reasons.

**Comment by arnoldnipper** [comment]
-1 ... let's implement #1185

**Comment by martinhannigan** [comment]
They’re dependencies. I should’ve  noted it and will update.

**Comment by jackcarrozzo** [comment]
PC call: this should be done through website?

**Comment by martinhannigan** [comment]
Whatever is fastest(cheap), most widely accessible and reliable. Sounds like a lookup from our own DB may make more sense.

**Comment by arnoldnipper** [comment]
We are going down the wrong road, IMO. We already put in trust in [Admin Committee Guidelines and Criteria for Approving Networks, IXPs, and Facilities](https://docs.peeringdb.com/committee/admin/approval-guidelines)

**Comment by martinhannigan** [comment]
No flag means no automation. I’m certain thats not the state we want going
forward. If we have clear requirements like “created facility before” we
need to enable automation, not subjectivity. This also has nothing to do
with AC. Its better product.

Seems like the right road to me.

**Comment by arnoldnipper** [comment]
Again, this has nothing to do with DeskPRO. We have all information in our DB. Mission completed

**Comment by martinhannigan** [comment]
We’ll agree to dis-agree.

Thanks Arnold!

-M<

**Comment by jackcarrozzo** [comment]
Closing, will circle back at some point
