### ISSUE TITLE
CSV and JSON exports truncate at 250 records

### ISSUE THREAD

**Issue by martinhannigan** [peeringdb/peeringdb#1563]
**Describe the bug**
JSON and CSV are truncated at 250 records

**To Reproduce**

1. Go to search
2. Select facilities
3. Select a scope of region=north america
4. Search
5. Press either export function
6. Inspect the output file

**Expected behavior**
All relevant records export as expected

**Who is affected by the problem?**

Users of PDB

**What is the impact?**

Poor data quality

**Are there security concerns?**

No

**Are there privacy concerns?**

No

**What are the proposed actions?**

Fix it.

**What is the proposed priority?**

Medium, impacts user ability to perform PDB related functions quickly and easily in and out of secure and insecure environments (the API  is not relevant)

**Comment by arnoldnipper** [comment]
That's a feature, not a bug, try a search, e.g. https://www.peeringdb.com/advanced_search?info_scope__in=North%20America&reftag=net, then scroll down to the end and you read

**...More than 250 entries matched your query, refine your request...**

**Comment by martinhannigan** [comment]
I saw that. I wasn't certain if that was an error in itself since why would
anyone accept less than what they searched for considering it's an export?

**Comment by arnoldnipper** [comment]
Minimise the load and prevent from abuse/dos

**Comment by martinhannigan** [comment]
Wouldn't it be more secure/smarter/better to prevent abuse to instead
require a login to use such functions?

**Comment by arnoldnipper** [comment]
If you really **search** for something, you don't need 250+ results, IMO. YMMV

**Comment by leovegoda** [comment]
The least we could do is update that message to let people know that they can get all `fac` objects in one go from the .KMZ download

**Comment by martinhannigan** [comment]
CSV, JSON vs. KMZ isn't really close in terms of utility so I'm not sure
what we would gain by adding any sort of banner.

**Comment by martinhannigan** [comment]
+1

**Comment by martinhannigan** [comment]
> If you really **search** for something, you don't need 250+ results, IMO. YMMV

Sorry Arnold, but can you explain what you mean?

Tks!

**Comment by jackcarrozzo** [comment]
PC call: same api limits apply to JSON and CSV; 250 limit is for performance reasons

**Comment by jackcarrozzo** [comment]
Periodic CSV dumps of various types might sense

**Comment by jackcarrozzo** [comment]
API limits can be a little more intelligent too

**Comment by jackcarrozzo** [comment]
PC call: we would like to do Something to improve this- pagination + performance improvements to api is good, but need to improve json + csv export too

**Comment by leovegoda** [comment]
Changed status: I'll schedule some work on how we could implement this in a safe way

**Comment by leovegoda** [comment]
Also, see: https://github.com/peeringdb/peeringdb/issues/1604

**Comment by martinhannigan** [comment]
In reviewing an additional thought. In experimenting with CSV/JSON on objects without an address to point to, (address, lat/long, geocode, etc.) there seems to be no value to normalizing this across objects unless we also normalize a way to bind with a location.
