### ISSUE TITLE
Add export function in Network page

### ISSUE THREAD

**Issue by bengelly** [peeringdb/peeringdb#1573]
**Is your feature request related to a problem? Please describe.**
Via a network page, I can't export to a file (.csv, .xls, .txt, .pdf) information for the following sections :
- Contact information
- Public Peering Exchange Points
- Interconnection Facilities
It is highly frustrating to have to copy/paste this and then toy with it.

**Who is affected by the problem?**
Me, as a peering manager working for a major Tier-1. Pretty sure it affects other people.

**What is the impact?**
Loss of time, efficiency and lot of frustration.

**Are there security concerns?**
No.

**Are there privacy concerns?**
No.

**Describe the solution you'd like**
A simple Export button that would propose a file format to choose from.

**Do you think this feature will require a formal design?**
no, seems rather trivial

**Describe alternatives you've considered**
None that comes to mind.

**Could this feature request need support from the Admin Committee?**
Consider if an administrator might need to provide assistance at any point.

**What is the proposed priority?**
not urgent

**Provide a rationale for any/all of the above**
already did.

**Additional context**
N/A.

**Comment by arnoldnipper** [comment]
You can easily do via the [API](https://www.peeringdb.com/apidocs/).

I would propose a more general approach enhancing PeeringDB by a query tool as it is impossible to hardcode any query.

**Comment by bengelly** [comment]
Hi @arnoldnipper ,

I do not have coding skills, and believe this feature would benefit the general public hence my request.

To the how, I'll leave that with to decide what is best :-)

Thanks !

**Comment by martinhannigan** [comment]
API+CSV+JSON is well received as am object standard IMHO.


+1

**Comment by bengelly** [comment]
Hi @martinhannigan !

In an ideal world, sure ! I'd totally agree with that !

However, as mentioned above, I do not have coding skills (like many) and believe this feature would benefit the general public hence my request.

Thanks !

**Comment by leovegoda** [comment]
This was completed via https://github.com/peeringdb/peeringdb/issues/1189
