### ISSUE TITLE
Ability to visualise datacenter localization via a map

### ISSUE THREAD

**Issue by bengelly** [peeringdb/peeringdb#1575]
**Is your feature request related to a problem? Please describe.**
I would to be able able to navigate datacenter locations via a map, and then click on present dots to see a summary of major location informations (name, number of networks present, etc.)

**Who is affected by the problem?**
Me, as a peering manager working for a major Tier-1. Pretty sure it affects other people.

**What is the impact?**
Loss of time, efficiency and lot of frustration.

**Are there security concerns?**
No.

**Are there privacy concerns?**
No.

**Describe the solution you'd like**
Integration of a map solution.

**Do you think this feature will require a formal design?**
no, seems rather trivial.

**Describe alternatives you've considered**
None that comes to mind.

**Could this feature request need support from the Admin Committee?**
Consider if an administrator might need to provide assistance at any point.

**What is the proposed priority?**
not urgent

**Provide a rationale for any/all of the above**
already did.

**Additional context**
N/A.

**Comment by arnoldnipper** [comment]
Did you try or [KMZ export](https://public.peeringdb.com/peeringdb.kmz)?

**Comment by martinhannigan** [comment]
Try out the KMZ export. You mentioned dots. ArcGIS user?

KMZ will not tell you networks by address but networks by vendor location
im majority of cases.

HTH

-M<

**Comment by bengelly** [comment]
Hi @martinhannigan,

Something basic like displaying this with Openstreet / Google maps integration ? 

For example : https://www.datacentermap.com

HTH.

**Comment by martinhannigan** [comment]
On out main landing  page we provide a facilities  based mapping in KMZ
format updated daily. It can be used in any tool supporting kml.

https://public.peeringdb.com/peeringdb.kmz

HTH

**Comment by bengelly** [comment]
Hi,

Didn't know about this. Really great that you can propose it, KMZs rock :-)

However, still think direct visualisation on the website would be a useful addition... It's less hassle than to have to DL the latest version of the KMZ each time and open it using a client.

I'll leave it to you to make the best call here.

HTH.

**Comment by martinhannigan** [comment]
I get what you’re saying. When this issue comes up at our next PC meeting
we will discuss it in detail. Thanks for the submission!

**Comment by bengelly** [comment]
Thanks for considering :-)

**Comment by arnoldnipper** [comment]
> It's less hassle than to have to DL the latest version of the KMZ each time and open it using a client.

At least in Google Earth, you can reference the URL directly. No DL needed.

**Comment by martinhannigan** [comment]
On Tue, Mar 19, 2024 at 10:55 AM Arnold Nipper ***@***.***>
wrote:

> It's less hassle than to have to DL the latest version of the KMZ each
> time and open it using a client.
>
> At least in Google Earth, you can reference the URL directly. No DL needed.
>
>

Looking at this more closely. It's far simpler to open it in Google Earth
Pro (Free desktop) or earth.google.com and save it for reference. A live
link can be used in the desktop version. KML is not importable to OSM and
this doesn't seem like data that would be useful in OSM for the most part
(aside from OSM extensive TOS/AUP/Licenses).

It does not important into ArcGIS, but ESRI can handle KML. It's finicky
about the formatting and frequently chokes on large imports. ArcGIS is not
a free tool so I'm leaning on them for a fix vs. PDB.

Our (next release?) future version also compresses space uses to we can
keep it small, but informative, enough so it can also be referenced in
maps.google.com

Not really sure after all that what we all might get out of a web version.
I don't know a lot about map coding but it'll be interesting to hear about
for certain.

HTH,

-M<

**Comment by martinhannigan** [comment]
-1 we already have this in our kml. You can also easily import csv with other data to GIS tools as well. Happy to show folks how in a faq.

**Comment by jackcarrozzo** [comment]
Sticking with KMZ for now, closing
