### ISSUE TITLE
Remove more clutter from KMZ Metadata

### ISSUE THREAD

**Issue by martinhannigan** [peeringdb/peeringdb#1577]
We recently made changes to the compressed KML output we provide (KMZ). A bunch of good modifications came from recent issues. Further sharpening the value of the output is needed. 

We're currently publishing:

Org_Id | XXXXX
Org_Name | Some Name
Name | Some Name Again, usually the same as Org_Name
Website | http://example.com
Net_Count | 2
Ix_Count | 0
Region_Continent | North America
Created | 2013-05-03T00:00:00Z
Updated | 2017-09-06T04:48:43Z
Status | ok
Address1 | Address
City | City
Country | US
State | State
Zipcode | Zip 
Latitude | 39.00000
Longitude | -75.000000
Networks | List of networks by name

With:

Org_Id	[ Delete - adds no discernible value to visual interpretation ]
Org_Name [ Keep, mask with Name]
Name	[ Delete, is this long name, org name copy or also know as name?  ]
Website	[ Keep ]
Net_Count	2 [ Mask as Networks ]
Ix_Count	0 [ Mask as Exchanges ]
Region_Continent	[ Delete, I can't understsand the value to have this in the meta data of a mapping application]
Created	 [ Delete ]
Updated	 [ Delete, collapsing the above and replace with a link back to the Meta data's source PDB record ]
Status	ok [ Delete, what does this mean (I know, not everyone will clue in and not certain how it adds visual information value ]
Address1	[ Keep ]
City	[ Keep ]
Country	[ Keep ] [ Much better than United States of America 👍 ]
State	[ Keep ]
Zipcode	[ Keep ]
Latitude	[ Keep ]
Longitude	[ Keep ]
Networks	[ Keep ]

**Comment by martinhannigan** [comment]
And what it looks like "clean"


Name: Sample Networks
PeeringDB: https://peeringdb.com/object/12345
Website: https://www.sample.org
Networks: 2 
Exchanges: 0 
Address:  123 Main St.
City: Boston
Country: US
State: MA
Zipcode: 02109
Latitude 72.00000000
Longitude 42.00000000
Networks: Main, Test, Alpha, Blah

**Comment by grizz** [comment]
+1

**Comment by jackcarrozzo** [comment]
+1

IAW @grizz re networks list

**Comment by martinhannigan** [comment]
+1

**Comment by arnoldnipper** [comment]
+1

**Comment by martinhannigan** [comment]
@grizz How about displaying a count of networks verses the list of networks? I'd also suggest, and I missed it above, keeping the comments meta data. It's being widely used to work around what people perceive as insufficient and I can see it having value for facilities. Looking at what everyone is using comments for may be a useful exercise for one of us to see if there are anything useful there we can create an issue from e.g. support for a PDB oriented peering policy bookmark.

**Comment by martinhannigan** [comment]
Data looks tight (Just getting around to run through the list of issues pre-beta - sorry. :) Suggestion, we should have a style guide. Is it PeeringDB peeringdb or Peeringdb. Nothing to do here.
![Screenshot 2024-05-29 at 7 24 51 PM](https://github.com/peeringdb/peeringdb/assets/21081154/f10472b9-443d-4ed9-a414-4ae9a41a7ec5)
