### ISSUE TITLE
python client overhaul

### ISSUE THREAD

**Issue by grizz** [peeringdb/peeringdb#158]

**Comment by bglinkerman** [comment]
Any idea when the client rewrite may take place. As of now we have to blow away the database everyday because we run into the "404" errors so frequently. Trying to decide if we want to just wait for the new client or write some rudimentary client of our own.

**Comment by bglinkerman** [comment]
@grizz Thanks for the update. That's great news...and good timing. I'll just wait for the new client to be released!
