### ISSUE TITLE
Wrong ORG?

### ISSUE THREAD

**Issue by itrack** [peeringdb/peeringdb#1582]
Some AS are put under **RIPE-NCC-END-MNT**

PeeringDB:
![Screenshot 2024-03-26 at 21 12 24](https://github.com/peeringdb/peeringdb/assets/2368391/cc3f186e-b73e-4675-8cca-7412cf3bef3d)

Whois:
![Screenshot 2024-03-26 at 21 12 16](https://github.com/peeringdb/peeringdb/assets/2368391/afc5b7d6-f59c-42bd-a4ee-dfed7cbcd76a)

I added and deleted the AS from my account, now I get this error:
![Screenshot 2024-03-26 at 21 16 35](https://github.com/peeringdb/peeringdb/assets/2368391/79c1e21e-8afb-4988-802d-88053c0cfa94)

**Comment by arnoldnipper** [comment]
Please reach out to support@peeringdb.com

**Comment by arnoldnipper** [comment]
Known bug and issue at hand can be reolved by @peeringdb/ac

**Comment by itrack** [comment]
I already wrote, thank you

**Comment by netravnen** [comment]
Directly related to #1455. Shouldn have been resolved with the latest PDB 2.56.1 hotfix deployment.
