### ISSUE TITLE
Passkey support for login

### ISSUE THREAD

**Issue by Diosbejgli** [peeringdb/peeringdb#1584]
**Is your feature request related to a problem? Please describe.**
Please add Passkey support for login purposes. This would allow users to replace their passwords with passkeys that are based on asymmetric cryptography instead of a static string.

I'm aware that 2FA is already supported but passkeys are not replacing 2FA, they are replacing passwords. I'm also aware that you can technically create a passkey on the website under "Security keys" and enable password-less login, but native passkey support would be more straightforward and improve adoption.

Based on FIDO standards, passkeys are a replacement for passwords that provide faster, easier, and more secure sign-ins to websites and apps across a user’s devices. Unlike passwords, passkeys are always strong and phishing-resistant.
Passkeys simplify account registration for apps and websites, are easy to use, work across most of a user’s devices, and even work on other devices within physical proximity.

**Who is affected by the problem?**
Everyone

**What is the impact?**
Currently users have to rely on a static password to login, with passkeys they could use a cryptographic key with biometric protection to sign-in.

**Are there security concerns?**
Passkeys are more secure than the currently implemented password-based logins.

**Are there privacy concerns?**
Password stuffing could potentially lead to unwanted information exposure.

**Describe the solution you'd like**
The PeeringDB website to support logins using Passkeys. The login form should offer the user to use a Passkey for logging in or automatically detect the presence of it and offer to use it. Github does this already.

**Do you think this feature will require a formal design?**
N/A

**Describe alternatives you've considered**
N/A

**Could this feature request need support from the Admin Committee?**
N/A

**What is the proposed priority?**
Medium priority as there's no immediate impact, however it's a low-hanging fruit to improve UX and security.

**Provide a rationale for any/all of the above**
This would make it easier and more secure to login to the PeeringDB website.

**Additional context**
https://passkeys.dev/
https://fidoalliance.org/passkeys/

**Comment by grizz** [comment]
+1

**Comment by jackcarrozzo** [comment]
+1

**Comment by martinhannigan** [comment]
+1

**Comment by leovegoda** [comment]
I've returned this to 3a because we'll get a spec written (with 2.61.0 in August 2024). The @peeringdb/pc can discuss the spec and we'll schedule implementation based on the outcome of that discussion.
