### ISSUE TITLE
Accessibility issue: constrast problems

### ISSUE THREAD

**Issue by jzp-github** [peeringdb/peeringdb#159]
The main contrast ratio used across the site is beneath the generally-accepted accessibility guidelines. Please adjust the default CSS accordingly. 

Using a standard baseline, as implemented by http://khan.github.io/tota11y/ and then ported to chrome ( https://chrome.google.com/webstore/detail/tota11y-plugin-from-khan/oedofneiplgibimfkccchnimiadcmhpe ), you can see the incorrect range and recommended changes. See attached screenshots.

<img width="1301" alt="insufficeint-contrast-overview" src="https://cloud.githubusercontent.com/assets/4713248/25579340/14620a00-2e45-11e7-93f9-c438fcaf9bb4.png">
<img width="1299" alt="contrast-problems-detail" src="https://cloud.githubusercontent.com/assets/4713248/25579346/1a164bf0-2e45-11e7-94b5-8a9ef14aa731.png">

**Comment by job** [comment]
perhaps we should hire or find a color specialist?

**Comment by arnoldnipper** [comment]
Or more generally a GUI specialist?

**Comment by job** [comment]
yes

**Comment by eloos** [comment]
this should be part of the UI domain track.

**Comment by brianmalcolm** [comment]
In reviewing the colors suggested by the Chrome plugin, I suggest the following shift in colors:
1. Dark Grey `#5A6B6E` becomes `#4A5F62`
1. Bright Blue `#66C1CF` becomes `#008390`
1. Medium Blue `#447881` becomes `#2B6E78`
1. Header Grey `#CDD4D6` remains the same
1. Light Grey `#DEE3E3` remains the same

Attached is a diagram showing the shift.

I would also suggest changing the bright blue found in the login button and footer to light grey `#DEE3E3`.

![peeringdb-color-diagram](https://user-images.githubusercontent.com/30697613/28930820-bf3e0c92-7839-11e7-9d95-64516b30f69d.png)

**Comment by grizz** [comment]
Works for me, thank you sir.

**Comment by vegu** [comment]
fixed in a79cd802
