### ISSUE TITLE
Organization API key table formatting broken

### ISSUE THREAD

**Issue by vegu** [peeringdb/peeringdb#1603]
**Describe the bug**
The current table that displays org api keys at `https://www.peeringdb.com/org/{org_id}#manage_keys` is formatted incorrectly, shoving everything into a condensed space to left (once there are keys in the table)

**To Reproduce**
1. Go to `https://www.peeringdb.com/org/{org_id}#manage_keys` (replace org_id)
2. Add api key if there aren't any
3. Reload
4. Observe

**Expected behavior**
Normal formatting in the table, according to the table header widths

**Who is affected by the problem?**
Org Admins

**What is the impact?**
Visual only

**Are there security concerns?**
No

**Are there privacy concerns?**
No

**Comment by grizz** [comment]
Pushing to 4, clear bug
