### ISSUE TITLE
rir_status update handler: intermittent bug that may attempt to delete a network too early

### ISSUE THREAD

**Issue by vegu** [peeringdb/peeringdb#1606]
**Describe the bug**
We noticed an attempt to delete a network based on rir status being bad, even though the grace period of 90 days had not been over yet. The issue was not immediately reproducible with dev data.

No networks were deleted and we have disabled the command again. Cause needs to be found and fixed, plus more tests added. 

Edit: There appears to be also a problem with the deletion call itself resulting in `HandleRefModel.delete() got an unexpected keyword argument 'force'` error.

**Comment by leovegoda** [comment]
Set to Ready for Implementation as it's a developer identified bug
