### ISSUE TITLE
Make URLs in Admin GUI clickable

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/peeringdb#161]

**Comment by vegu** [comment]
Which urls?

**Comment by vegu** [comment]
Moved back to review so we can clarify this a bit more.

**Comment by arnoldnipper** [comment]
Especially this one 
![20170706 peeringdb 00](https://user-images.githubusercontent.com/16888757/27927638-ba49798c-628c-11e7-9a03-36b405985916.png)

**Comment by vegu** [comment]
Understood - As it's a text field, probably most reasonable approach would be to add a button next to the field label for URL fields (website in this case).
