### ISSUE TITLE
possible for ixpfx object with empty prefix to exist in a soft-deleted state

### ISSUE THREAD

**Issue by vegu** [peeringdb/peeringdb#1610]
**Describe the bug**

ixpfx 3257 somehow ended up with a null prefix in the database.

Its status is `deleted`, so not visible to users, but it having a null prefix still caused a validation issue during the peeringdb-py client sync process.

the sync issue has been fixed for this particular instance, but the cause should still be investigated.

- why did it end up as blank / null prefix
- why is the client side validation seemingly different than the server side one, given they use the same model schema from django-peeringdb (client error was `django.core.exceptions.ValidationError: {'prefix': ['This field cannot be null.']}`)

**Comment by leovegoda** [comment]
Closing this as it could not be reproduced when developing a fix
