### ISSUE TITLE
Oauth2: Keep getting `invalid_client` error while trying to get the access token

### ISSUE THREAD

**Issue by tszxxx** [peeringdb/peeringdb#1611]
**Describe the bug**
1. We're able to get the code as the first step of the Oauth2 process.
2. When we try to use the code to get the access token, we will get the `invalid_client` as response.

**To Reproduce**
1. navigate to https://auth.peeringdb.com/oauth2/authorize?client_id=OUR_CLIENT_ID_FROM_WEBSITE&redirect_uri=OUR_REDIRECT_URL&scope=profile&response_type=code
2. get the `code` from the redirect url
3. try to use the `code` to get the access token
```
curl --location 'https://auth.peeringdb.com/oauth2/token/' \
--header 'Content-Type: application/x-www-form-urlencoded' \
--data-urlencode 'grant_type=authorization_code' \
--data-urlencode 'code=CODE_FROM_STEP_2' \
--data-urlencode 'client_id=COPY_FROM_OAUTH_APPLICATION_PAGE' \
--data-urlencode 'client_secret=COPY_FROM_OAUTH_APPLICATION_PAGE' \
--data-urlencode 'redirect_uri=OUR_REDIRECT_URL'
```
```
{"error": "invalid_client"}
```

**Expected behavior**
Get the access token after the step #3

**Who is affected by the problem?**

**What is the impact?**

**Are there security concerns?**

**Are there privacy concerns?**

**What are the proposed actions?**
Either tell us how to use the Oauth2 or fix the bug
**What is the proposed priority?**
simply urgent

**Provide a rationale for any/all of the above**

**Additional context**

**Comment by jackcarrozzo** [comment]
Sorry, we lack the resources to help debug client oauth impls. Try using a standard oauth library against pdb, then compare the calls and payloads your code makes vs those made by the library.

**Comment by tszxxx** [comment]
Hi there @jackcarrozzo I tried the standard python library `https://pypi.org/project/requests-oauthlib/` but still get the same error

**Comment by garyshaver** [comment]
Try using the client secret from the initial addition on the oauth entry form (before you save it). Once saved, it pre-hashes and no longer works as expected.  If your client secret starts with 'pbkdf2_sha256$600000$' is pre-hashed.
