### ISSUE TITLE
Snag list for preview.beta.peeringdb.com

### ISSUE THREAD

**Issue by leovegoda** [peeringdb/peeringdb#1617]
**Is your feature request related to a problem? Please describe.**
Make updates based on designer snag list for preview.beta.peeringdb.com

preview.beta.peeringdb.com is a publicly accessible preview of an updated design for www.peeringdb.com. Users can access it, look at how pages they care about look, and provide feedback.

**Who is affected by the problem?**
Users.

**What is the impact?**
Better web design. 

**Are there security concerns?**
No.

**Are there privacy concerns?**
No.

**Describe the solution you'd like**
Update preview.beta.peeringdb.com based on the designer's snag list.

**Do you think this feature will require a formal design?**
No more than the snag list document provided to 20C.

**Describe alternatives you've considered**
None.

**Could this feature request need support from the Admin Committee?**
No.

**What is the proposed priority?**
Soon.

**Provide a rationale for any/all of the above**
We can improve the overall experience of web users by updating the design of www.peeringdb.com so it's more responsive to screen size etc...

**Comment by martinhannigan** [comment]
+1

**Comment by leovegoda** [comment]
Snag list details provided by designer are attached here
[PeeringDB UI Audit -1.pdf](https://github.com/peeringdb/peeringdb/files/15472562/PeeringDB.UI.Audit.-1.pdf)
[PeeringDB UI Audit 1.docx](https://github.com/peeringdb/peeringdb/files/15472563/PeeringDB.UI.Audit.1.docx)

**Comment by grizz** [comment]
+1

**Comment by leovegoda** [comment]
@20c-ed confirmed this has been done so closing and moving to the relevant Milestone
