### ISSUE TITLE
CSV, JSON exports for search views: "download this search"

### ISSUE THREAD

**Issue by job** [peeringdb/peeringdb#162]
If one goes to https://peeringdb.com/advanced_search and for instance clicks "educational/research" and hits "search", it would be cool if the resulting table overview could be downloaded as JSON and/or CSV file with a single click.

"Download this search" or something

**Comment by mcmanuss8** [comment]
Attached is some inspiration of how this could look. As I mentioned on the call, we have a similar feature on an internal tool my $day_job team maintains. 

Basically there's an icon you hover over and you get menu options as shown.
![screen shot 2017-07-08 at 12 17 15 am](https://user-images.githubusercontent.com/5892502/27982576-0023b12a-6373-11e7-87cf-43d1f3eb468b.png)

 I thought the JSON option here could just open up an appropriate api call in a new tab.  For example https://www.peeringdb.com/net/2 "Public Peering Exchange Points" would have an export button next to Filter and clicking it would bring up https://www.peeringdb.com/api/netfac?net=2
It'd be super cool if something like https://www.peeringdb.com/api/netfac?net=2&format=csv would be the way the CSV download worked :)

**Comment by grizz** [comment]
CSV won't fit most of the data, a json download button would work fine, any need for another format?

**Comment by mcmanuss8** [comment]
Why wouldn't CSV fit? I can see needs for JSON, CSV, Excel and HTML. The latter being just a popup of the existing data without all the header/footer, rendered the same as it looks on the peeringdb.com page. Use case there would be if I wanted to iframe something like the Public Peering Exchange Points box on https://www.peeringdb.com/net/2 on www.akamai.com/peering I could do so lazily but clicking the HTML export, and copy/pasting the URL onto my page. Might be useful *shrug*

**Comment by grizz** [comment]
because CSV/Excel are column/row, and all of the data is key/value

**Comment by vegu** [comment]
advanced search `csv` and `json` export implemented in 6ab82eb1

api links for relationship lists such as "Public Peering Exchange Points" should be covered in a separate ticket imo - i seem to recall there already being one, however i cannot find it now.
