### ISSUE TITLE
OpenID Connect discovery configuration document

### ISSUE THREAD

**Issue by icb-** [peeringdb/peeringdb#1625]
**Describe the bug**
I would like to use PeeringDB as an OIDC Provider to authenticate exchange point members using the [Shibboleth IdP OIDC Relying Party plugin](https://shibboleth.atlassian.net/wiki/spaces/IDPPLUGINS/pages/3013804089/OIDCRelyingPartyAuthnConfiguration). This needs the `.well-known/openid-configuration` document, which appears to be missing from the work that was done for #1070. Would it be possible for you to add this?

**To Reproduce**
1. Add OIDC RP integration
2. Attempt to configure on RP
3. Receive error from RP about missing configuration document.

**Expected behavior**
OpenID Connect configuration document should describe the keys and endpoints for the OIDC Provider

**Who is affected by the problem?**
Anyone setting up OIDC integrations

**What is the impact?**
OIDC integrations are more difficult (or impossible) to set up

**Are there security concerns?**
This document describes existing endpoints.

**Are there privacy concerns?**
No

**What are the proposed actions?**
Add 

**What is the proposed priority?**
Not currently urgent, but I need to implement an authentication solution, whether using PeeringDB or a different provider, in the next couple of months.

**Comment by dorkmatt** [comment]
This may be a duplicate of #1585

**Comment by icb-** [comment]
Slightly different, but similar. It does look like it was resolved in #1632 too.
