### ISSUE TITLE
Make search results easily linkable

### ISSUE THREAD

**Issue by job** [peeringdb/peeringdb#163]
Right now when I search, the URL bar isn't updated with the search parameters, this means that I can't easily copy+paste a specific search result, by copy+pasting the URL and pasting that to someone.

The procedure where you have to explain to someone "go to https://peeringdb.com/advanced_search and then click facilities and then type XYZ in field A and then type DEF in field B and etc etc" is far too cumbersome. 

Google allows direct linking to search results! https://www.google.nl/webhp?q=peeringdb#safe=off&q=peeringdb - peeringdb should allow that too

**Comment by vegu** [comment]
fixed in b39fa3cf
