### ISSUE TITLE
ops: add read-only server side switch

### ISSUE THREAD

**Issue by grizz** [peeringdb/peeringdb#1635]
It would be beneficial for ops to have a configuration switch to flip that makes all of PeeringDB read only while still allowing users to login.

It should also add a second flag that allows user login without writing `last_login` to the database so it could be used against a read only database if needed

There was similar available before as maintenance mode, so we may be able to leverage some of that.

**Comment by jackcarrozzo** [comment]
+1

**Comment by mcmanuss8** [comment]
Can you clarify - per user or for that server instance?

**Comment by grizz** [comment]
@mcmanuss8 edited above, thanks for pointing out my ambiguity, is that better?

**Comment by mcmanuss8** [comment]
Make sense. To clarify the use case: We're worried about a mass hack of users or similar and want to prevent data changing until we can resolve? If so, big +1

**Comment by grizz** [comment]
Yes, that would be an example of an extreme situation.

It could be anytime we'd like to limit an attack vector or any sort of write without taking down PDB for normal, read only uses.

**Comment by arnoldnipper** [comment]
+1
