### ISSUE TITLE
Set API Priority And Use LImits Based On Sponsor Tier

### ISSUE THREAD

**Issue by martinhannigan** [peeringdb/peeringdb#1643]
**Is your feature request related to a problem? Please describe.**

Using the API incurs costs for PeeringDB. The API is one of our most valuable resources, second only to our data. We already provide free access to our data—the most valuable asset we possess—via KMZ files and unauthenticated access. However, many sites, including major players like Google and "free" geospatial platforms such as OpenMap, expect and demand support for high performance API access as well. It is not unusual for non profits nor unexpected. It is possibly overdue for PeeringDB.

**Who is affected by the problem?**

PeeringDB interconnection and site selection users.

**What is the impact?**

Reduced costs. Potentially improved sponsorship.

**Are there security concerns?**

Yes. We don't know who is using the data and APi for what purpose. At least justifying through a rate limit gives us a view and to know our customers and what they do with the data - or if we approve of that use from a security perspective.

**Are there privacy concerns?**

Yes. Once the data leaves PDB, especially unauthenticated, our TOS/AUP/policies no longer apply and the data is in the wild. However, not certain that is relevant other than an asterisk for API improvements.

**Describe the solution you'd like**

Develop rate limiting benefits by sponsorship tier. Reduce depth and decrease  priority and/or frequency limits for non sponsor API use.

**Do you think this feature will require a formal design?**

Yes.

**What is the proposed priority?**

High priority.

**Comment by job** [comment]
This sounds like a monetisation scheme that’s unwarranted

**Comment by job** [comment]
Board decides on revenue streams and sponsorship perks, not productcom. If you have proposals please bring them to the stewards list for consideration.

**Comment by martinhannigan** [comment]
The bills have to be paid somehow. However, it's a request for a feature.
If it requires some other approvals then whatever the PeeringDB policy is
(is there?) then this should find its way there easily.

Thanks for the input!

**Comment by mustangthz** [comment]
Marty,

The board will discuss this at the next board meeting.   Thanks.  You can close this issue for now.

**Comment by martinhannigan** [comment]
Thanks!
