### ISSUE TITLE
beta peeringDB site cannot be reached.

### ISSUE THREAD

**Issue by jramseyer** [peeringdb/peeringdb#1648]
**Describe the bug**
https://beta.peeringdb.com/ cannot be reached.

Yesterday, I noticed 502 errors when hitting certain API endpoints (example: https://www.beta.peeringdb.com/api/netfac), but other endpoints worked.  

Today, I see 503 errors on all API endpoints (https://www.beta.peeringdb.com/api)

**To Reproduce**
Load https://beta.peeringdb.com/ in web browser.  Site fails to load.

I also tried https://www.beta.peeringdb.com/api/ix/239 (as an example) and it fails to load.  Prod: https://www.peeringdb.com/api/ix/239 loads data as expected.

I cannot reach the beta site via programmatic access, either.

**Expected behavior**
API data should load

**Who is affected by the problem?**
I am affected, and confirmed with a friend that they are also unable to load.  Tooling cannot reach site either.

**What is the impact?**
Cannot load beta peeringDB data.  

**Are there security concerns?**
No
**Are there privacy concerns?**
No
**What are the proposed actions?**
Please return API functionality to beta site.
**What is the proposed priority?**
Not urgent now, but will be urgent if deployed to prod site.
**Provide a rationale for any/all of the above**
Prod still works now.
**Additional context**
I only see it on the Beta site.  Might it be related to #1561 ?

**Comment by jackcarrozzo** [comment]
Hey, there was a deploy earlier today that went sideways, ops people are working on it. No ETA to my knowledge but likely back “soon”?

**Comment by leovegoda** [comment]
The original deployment of 2.60.0 on beta.peerinbdb.com encountered a problem. A fresh deployment took place and was announced yesterday.
