### ISSUE TITLE
Carrier list page links to non-existing org

### ISSUE THREAD

**Issue by leovegoda** [peeringdb/peeringdb#1651]
**Describe the bug**
The page for https://www.peeringdb.com/carrier/44 links to https://www.peeringdb.com/org/2201 in the Organization field. But https://www.peeringdb.com/org/2201 gives a 404 error.

**To Reproduce**
1. Go to ['...'](https://www.peeringdb.com/carrier/44)
2. Click on [Globalways GmbH](https://www.peeringdb.com/org/2201)
3. See 404 error

<img width="1194" alt="Screenshot 2024-07-22 at 12 43 37" src="https://github.com/user-attachments/assets/168d077a-9259-43dc-afef-9010a1b9cd3f">
<img width="900" alt="Screenshot 2024-07-22 at 12 43 48" src="https://github.com/user-attachments/assets/4b469266-9b1f-4f72-a87f-f863f2003bd8">

**Expected behavior**
The Organization link should go to an active organization.

**Who is affected by the problem?**
The Organization running the Carrier and PeeringDB users.

**What is the impact?**
Bad data.

**Are there security concerns?**
No.

**Are there privacy concerns?**
No.

**What are the proposed actions?**
Work out why the org link doesn't work and fix it if it is a software problem.

**What is the proposed priority?**
Work out what happened and why. Then decide what to do.

**Provide a rationale for any/all of the above**
As above.

**Comment by martinhannigan** [comment]
Interesting.

https://www.peeringdb.com/net/2538

So the network in question is owned by Zayo?

Looks clear that Zayo acquired them. Perhaps the org was deleted due to a
change?

I would suggest we be careful with this org issue since it could impact the
objects below it. For example, see
https://github.com/peeringdb/peeringdb/issues/1616 for example.

Agree this doesn't reflect results as expected, but -1 to bug until further
research. Seems more like an AC issue for now.

Thanks

Martin

**Comment by arnoldnipper** [comment]
This is clearly a bug. A `org` object only can be removed iff no children are hanging off. On the other hand, when `org`|s are merged, all children objects org_ids have to be updated. Looks like that has not been done.

**Comment by arnoldnipper** [comment]
@peeringdb/ac, please look into the history and let us know how this happened

**Comment by martinhannigan** [comment]
Thanks. I’m saying this is a security problem first: ORG has been
obliterated and we need to fully and completely restore, understand and
assure ORG is perfected or we nay have liability.

**Comment by peterhelmenstine** [comment]
+1 looks like a bug

**Comment by cappaxyz** [comment]
Checked history - AC user merged with other org upon admin user request, but the carrier object wasn't included by the merge tool in merge 1694 for some reason - only the network, fac and user objects were.  Does the merge tool have a script for carrier objects?

I can assign the carrier object to the org it was meant to be merged in now if no objection.

**Comment by grizz** [comment]
Looks like a bug to me.

@leovegoda let's make a PC note to add new object types to the merge tool as well, or possibly we can redo the merge tool to include all object types. 20C can check when this is fixed.

**Comment by leovegoda** [comment]
> Looks like a bug to me.
> 
> @leovegoda let's make a PC note to add new object types to the merge tool as well, or possibly we can redo the merge tool to include all object types. 20C can check when this is fixed.

The @peeringdb/ac can fix this specific issue with their admin priveleges. And there is a new issue for the actual tool: https://github.com/peeringdb/peeringdb/issues/1710

**Comment by leovegoda** [comment]
Closed in favor of #1710
