### ISSUE TITLE
Update dependencies and modernise

### ISSUE THREAD

**Issue by leovegoda** [peeringdb/peeringdb#1653]
**Is your feature request related to a problem? Please describe.**
Annual review of dependencies etc...

**Who is affected by the problem?**
Ultimately, everyone

**What is the impact?**
Keep us using stable, well supported code

**Are there security concerns?**
No

**Are there privacy concerns?**
No

**Describe the solution you'd like**
An update like https://github.com/peeringdb/peeringdb/issues/1311 from last year

**Do you think this feature will require a formal design?**
No

**Describe alternatives you've considered**
Do nothing.

**Could this feature request need support from the Admin Committee?**
No.

**What is the proposed priority?**
October 2024.

**Provide a rationale for any/all of the above**
As above.

**Additional context**
See also: https://github.com/peeringdb/peeringdb-py/issues/94 and https://github.com/peeringdb/django-peeringdb/issues/103

**Comment by jackcarrozzo** [comment]
+1

**Comment by mcmanuss8** [comment]
+1

**Comment by arnoldnipper** [comment]
+1 ... do we need to vote on this?

**Comment by grizz** [comment]
Fixed with #1681 and #1683
