### ISSUE TITLE
Direct query access to Elasticsearch to aid search improvements

### ISSUE THREAD

**Issue by jackcarrozzo** [peeringdb/peeringdb#1654]
**Is your feature request related to a problem? Please describe.**

Many users have identified marginal or downright bad search behavior; it is hard for us to accurately characterize the problem and suggest specific improvements.

**Who is affected by the problem?**

Everyone who uses search

**What is the impact?**

It would be ideal if at least (but perhaps not limited to) the PDB PC members could make direct queries to Elasticsearch, such that we might document exact, workable changes to our ES interaction (instead of just saying 'xyz doesn't work, pls make better').

**Are there security concerns?**

To my knowledge there is no secret data in Elasticsearch- allowing read-only access (ie GET reqs only) seems fine to me, since this data is all already available through the site and api. We can restrict it to PDB PC members if need-be, but I'm inclined to suggest we allow its use just like the API- that way any user can use it and discover better usage patterns for our "real"/wrapped search.

**Are there privacy concerns?**

As above- not to my knowledge but worth confirming.

**Describe the solution you'd like**

Sticking a URI route somewhere like `_search` that just passes through the query string and req body to ES is probably easiest? Open to other ideas. 

```
curl -X GET "somehost.peeringdb.com/es/_search?pretty" -H 'Content-Type: application/json' -d \
'{
  "query": {
    "simple_query_string" : {
        "query": "\"fried eggs\" +(eggplant | potato) -frittata",
        "fields": ["xxx", "yyy", "zzz"],
        "default_operator": "and"
    }
  }
}'
```

Extra credit- it would be helpful if one could (optionally?) receive the json blob of the ES query used alongside results from a search query submitted through web or API when applicable (as a `<!-- comment -->` for web, or an `_info` json property for api, etc) for purposes of debugging.

**Do you think this feature will require a formal design?**

Probably not? Seems simple.

**Describe alternatives you've considered**

The alternate is to keep iterating with 'search is broken' GitHub issues, unclear directions to devs, and long timelines for improvement.

**Could this feature request need support from the Admin Committee?**

Negative

**What is the proposed priority?**

Urgent-ish, only because search issues are being discovered at a fairly high rate vis-a-vis everything else.

**Provide a rationale for any/all of the above**

There have been search issues discussed during the last several PC calls; it is not immediately clear how we can work these problems into direct asks to the developers. Allowing us to iterate on the ES queries themselves and pass THOSE to the devs will hasten improvement.

**Additional context**

https://www.elastic.co/guide/en/elasticsearch/reference/current/search-your-data.html
https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-query-string-query.html
https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-simple-query-string-query.html

**Comment by jackcarrozzo** [comment]
PC call: fall back to ssh jump box for auth if need-be

**Comment by grizz** [comment]
+1

**Comment by arnoldnipper** [comment]
+1
