### ISSUE TITLE
IX-F importer: Consider notifications for address protocol inconsistencies

### ISSUE THREAD

**Issue by GD1200** [peeringdb/peeringdb#1656]
**Is your feature request related to a problem? Please describe.**
While troubleshooting why a specific IPv6 address was ignored by the PeeringDB's IX-F importer ([peeringdb_server/ixf.py](https://github.com/peeringdb/peeringdb/blob/2.60.0/peeringdb_server/ixf.py#L1032)), it got obvious that the problem was related to the fact that the network owner had the IPv6 support flag disabled for their network (network.ipv6_support). Considering that it is an inconsistency that should be either resolved by the IX operator by removing the address that the network cannot use, or by the network operator by toggling the protocol support flag, it might be beneficial not to leave such inconsistency facts unnoticed.

**Who is affected by the problem?**
Exchange and network operators

**What is the impact?**
It can lead to situations when a valid address is not added (or not suggested to be added) to the exchange object, and such facts remain unnoticed.

**Are there security concerns?**
No

**Are there privacy concerns?**
No

**Describe the solution you'd like**
I believe this inconsistency should be treated similarly to how general address inconsistencies are handled. For example, the network operator could be suggested to consider toggling the protocol support flag due to the possible active protocol address on a given exchange. Similarly, the IX operator could be notified about the fact the network operator does not support protocol while the protocol address was assigned to them, suggesting to verify if the assigned address is actually usable/active.

**Do you think this feature will require a formal design?**
No (as far as I can see, the check is already in place and the existing notification routines may be involved there)

**Describe alternatives you've considered**
I guess it can also be logged in the IX-F import preview, for the affected network entry. Although I believe it might be tricky to implement, but showing a suggestion to consider switching a protocol on in the network operator's portal when a discrepancy is detected might be another alternative solution.

**Could this feature request need support from the Admin Committee?**
Yes

**What is the proposed priority?**
Low

**Provide a rationale for any/all of the above**
Considering that it is an inconsistency that should be either resolved by the exchange operator, by removing the address that the network cannot use, or by the network operator, by toggling the protocol support flag, it might be beneficial not to leave such inconsistency facts unnoticed.

**Additional context**
[PEERINGDB-202406MREPJ1]

**Comment by arnoldnipper** [comment]
IMO, we should get rid of fields `info_unicast`, `info_multicast`, and `info_ipv6` in v3 as not needed anymore

**Comment by jackcarrozzo** [comment]
PC call: the IX operator controls the source of truth- not a good idea for PDB to be modifying data exported from the IX.
