### ISSUE TITLE
Add name, city, country to ixfac (GET operation)

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/peeringdb#166]
Currently we have

InternetExchangeFacilitySerializer {
id (integer),
ix_id (integer),
ix (serializer),
fac_id (integer),
fac (serializer),
created (string),
updated (string),
status (string)
}

and

NetworkFacilitySerializer {
id (integer),
name (serializer),
city (serializer),
country (serializer),
net_id (integer),
net (serializer),
fac_id (integer),
fac (serializer),
local_asn (integer),
created (string),
updated (string),
status (string)
}

**Comment by eloos** [comment]
@grizz : was there a specific reason for this difference?

**Comment by grizz** [comment]
Off the top of my head, it's left over cruft from the version 1 migration, although it should just be removed from `ixfac`, not added to netfac, which would require version 3.

**Comment by arnoldnipper** [comment]
The GET operation returns gratuitous information about `name`, `city`, and `country` for the `netfac` object. However, this information is missing for `ixfac`. Adding this information would come in handy.

I would even propose to add `longitude` and `latitude` to save on additional API calls.

@peeringdb/pc what do you think? +1 from me :)

**Comment by shane-kerr** [comment]
So the proposal is just to add the information to the return on API calls, presumably pulled from other objects?

**Comment by arnoldnipper** [comment]
> So the proposal is just to add the information to the return on API calls, presumably pulled from other objects?

Exactly ... just do sort of 1.5 depth lookup to `fac` and return this information as well. GET already does a 1.3 depth lookup. Adding one more field for `netfac` and return the same information for `ixfac` as for `netfac` should not be that hard.

**Comment by shane-kerr** [comment]
+1 

Okay, I don't see much harm in adding potentially useful information like this.

**Comment by mcmanuss8** [comment]
+1

**Comment by grizz** [comment]
@peeringdb/pc Since both `ix` and `fac` have these fields, where should we take them from? I'd imagine `fac` would make the most sense.

**Comment by arnoldnipper** [comment]
Hmmm ... `ixfac` means the `fac`  where `ix` presents its services. So, for me, there is no doubt where to take these fields from. Makes sense?

**Comment by mcmanuss8** [comment]
Yes, should pull from the fac.

**Comment by arnoldnipper** [comment]
**Summary**

Add read-only fields `name`, `city` and `country` to object `ixfac`.  The values for these fields are `fac.name`, `fac.city` and `fac.country` from the facility `fac` with `id` == `fac_id`

Example:

```
{
  "id": 412,
  "ix_id": 2,
  "fac_id": 968,
  "created": "2011-01-09T00:00:00Z",
  "updated": "2016-03-14T21:44:19Z",
  "status": "ok"
}
```
would become 
```
{
  "id": 412,
  "ix_id": 2,
  "fac_id": 968,
  "name": "Equinix CH3 - Elk Grove",
  "city": "Elk Grove Village",
  "country": "US",
  "created": "2011-01-09T00:00:00Z",
  "updated": "2016-03-14T21:44:19Z",
  "status": "ok"
}
```
