### ISSUE TITLE
Schedule reset of tutorial server database

### ISSUE THREAD

**Issue by leovegoda** [peeringdb/peeringdb#1666]
**Is your feature request related to a problem? Please describe.**
Anyone can create objects on the tutorial.peeringdb.com server. These objects will date and are not operationally valid. We have received requests to delete old objects containing PII. We should reset the database on a schedule, so outdated objects are removed.

**Who is affected by the problem?**
Anyone named in an object, or anyone who mistakes tutorial server objects as 'operational' data.

**What is the impact?**
A nice clean database for people to learn in.

**Are there security concerns?**
No.

**Are there privacy concerns?**
No. Probably some benefits.

**Describe the solution you'd like**
1. Reset the tutorial server database each time its software is updated.
2. Publish the (estimated) next date on which the server's database will be reset on the front page

**Do you think this feature will require a formal design?**
No. It's a simple change to restart the service with an empty database. The only significant effort is to publish an estimated date and time on which the database will be reset.

**Describe alternatives you've considered**
Do nothing.

**Could this feature request need support from the Admin Committee?**
Should not.

**What is the proposed priority?**
Low priority.

**Provide a rationale for any/all of the above**
We had a request to remove PII from the tutorial server and complied. The data would not have been there if the database had been reset each time the software is updated.

**Comment by jackcarrozzo** [comment]
+1

**Comment by jbartig** [comment]
+1

**Comment by grizz** [comment]
+1

**Comment by martinhannigan** [comment]
+1
