### ISSUE TITLE
net_count is not searchable  

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/peeringdb#167]
curl -s -G https://peeringdb.com/api/fac\?net_count__gte=100 | jq '.data[].id' | wc -l
2436

curl -s -G https://peeringdb.com/api/fac\?net_count__gte=10 | jq '.data[].id' | wc -l
2436

curl -s -G https://peeringdb.com/api/fac\?net_count__gte=0 | jq '.data[].id' | wc -l
2436

**Comment by vegu** [comment]
fixed in 0c52f6b
