### ISSUE TITLE
Inconsistent netixlan ASN data can result in inability for deleted netixlan to be claimed by new user

### ISSUE THREAD

**Issue by ccaputo** [peeringdb/peeringdb#1671]
There are some netixlan records that have an ASN which is different than their network owner's ASN. For example:

<img width="460" alt="Screenshot 2024-09-11 at 9 25 05 AM" src="https://github.com/user-attachments/assets/39668f60-a549-492b-b866-ad174e72f3da">

Although that netixlan has status "deleted", an attempt to re-use the IP address like this:

<img width="546" alt="Screenshot 2024-09-11 at 9 20 58 AM" src="https://github.com/user-attachments/assets/cb3e8e9e-2981-49df-867f-d8fbad8c63de">

results in:

<img width="553" alt="Screenshot 2024-09-11 at 9 20 38 AM" src="https://github.com/user-attachments/assets/fdd1035f-c2a5-4e74-a941-02b36d8f0456">

Rather than providing the user with an opaque error, and to avoid an internal PeeringDB Admin needing to manually go into the control panel and correct the ASN on the deleted record, this invalid data case should be handled.

NOTE: The above data examples are now out of date, but others exist in the database. One possible solution if new data verification code would prevent this from being stored in this manner, is to go through the database and correct all instances of it happening.

**Comment by jackcarrozzo** [comment]
+1

**Comment by grizz** [comment]
+1 to fixing the error message

For the local_asn field, it's going away with v3 (#625) so we probably should null it and make it a read only view of `$network.asn`

**Comment by arnoldnipper** [comment]
Ceterum censeo, `netixlan`, `netfac`, `carrierfac`, and `ixfac` should be completely removed from the DB, once marked deleted. They are good for nothing. 

We didn't clean up data very well, when migrating data into version 2. Especially, we didn't take care that with version 2 there is nothing like **primary ASN**. With version 1, the value in the asn field of `netixlan` didn't have to match the primary asn. Same holds for the value of local_asn in the `netfac` object.

If we don't delete the objects, we at least should run a DB script to rectify the asn values.

**Comment by martinhannigan** [comment]
+1

**Comment by Juimar** [comment]
+1

**Comment by leovegoda** [comment]
**Summary**
Ignore the ASN in the `netixlan` object when it differs from the `net`.

**Comment by arnoldnipper** [comment]
@leovegoda, my understanding - which I also support - is to "... One possible solution if new data verification code would prevent this from being stored in this manner, is to go through the database and correct all instances of it happening." 

In total, we have 20k objects (netixlan and netfac) where we have a mismatch between the net_id and the asn/local_asn. 

Fixing the DB is way better than fixing the code.

**Comment by ccaputo** [comment]
> @leovegoda, my understanding - which I also support - is to "... One possible solution if new data verification code would prevent this from being stored in this manner, is to go through the database and correct all instances of it happening."
> 
> In total, we have 20k objects (netixlan and netfac) where we have a mismatch between the net_id and the asn/local_asn.
> 
> Fixing the DB is way better than fixing the code.

Good point. If current code prevents reoccurrence, and the db can be simply cleaned, that does sound better.

**Comment by arnoldnipper** [comment]
> > @leovegoda, my understanding - which I also support - is to "... One possible solution if new data verification code would prevent this from being stored in this manner, is to go through the database and correct all instances of it happening."
> > In total, we have 20k objects (netixlan and netfac) where we have a mismatch between the net_id and the asn/local_asn.
> > Fixing the DB is way better than fixing the code.
> 
> Good point. If current code prevents reoccurrence, and the db can be simply cleaned, that does sound better.

Afais, the inconsistency comes from the primary/secondary ASN which we had in v1. This concept was used as we didn't have organisations. Since v2, primary/secondary does not make sense anymore. This should be fixed. And the fix is straight forward, IMO

**Comment by leovegoda** [comment]
@arnoldnipper @ccaputo Please confirm which records should be cleansed from the database.

**Comment by ccaputo** [comment]
> @arnoldnipper @ccaputo Please confirm which records should be cleansed from the database.

I think it would be objects with an ASN in the record which disagrees with the related "net" object ASN. @grizz comment makes sense:

> For the local_asn field, it's going away with v3 (https://github.com/peeringdb/peeringdb/issues/625) so we probably should null it and make it a read only view of $network.asn

**Comment by leovegoda** [comment]
**Summary**
Purge the database of objects with an ASN in the record which disagrees with the related "net" object ASN as per https://github.com/peeringdb/peeringdb/issues/1671#issuecomment-2344397781 above

**Comment by ccaputo** [comment]
> **Summary** Purge the database of objects with an ASN in the record which disagrees with the related "net" object ASN as per [#1671 (comment)](https://github.com/peeringdb/peeringdb/issues/1671#issuecomment-2344397781) above

That is absolutely not what we mean. That would be destructive. By "null" it, @grizz means to "null" a single field (local_asn) in an object, not delete the object.

**Comment by ccaputo** [comment]
Here's an attempt:

**Summary**
Nullify the local `asn` field of `netixlan` objects and make it a read only view of $network.asn.

@grizz and @funkestefan: does that seem logical?

**Comment by grizz** [comment]
@ccaputo looks good, thanks.

**Comment by arnoldnipper** [comment]
Attached a list of objects (netfac and netixlan) that have mismatching net_id/asn information.
[20240911-broken.csv](https://github.com/user-attachments/files/17002056/20240911-broken.csv)

**Comment by ccaputo** [comment]
> Attached a list of objects (netfac and netixlan) that have mismatching net_id/asn information. [20240911-broken.csv](https://github.com/user-attachments/files/17002056/20240911-broken.csv)

Fascinating! All in the `deleted` state. (FWIW, I think we should keep them but nullify their `asn` field, so their history is not lost.)

**Comment by arnoldnipper** [comment]
> FWIW, I think we should keep them but nullify their `asn` field, so their history is not lost.
>

I've never found out how I can get access to the history of an object. Is this information kept separately, @ccaputo?

**Comment by arnoldnipper** [comment]
> Fascinating! All in the `deleted` state.
>

Of course! All objects in the `ok` state have consistant information as this is checked.

**Comment by ccaputo** [comment]
> > FWIW, I think we should keep them but nullify their `asn` field, so their history is not lost.
> 
> I've never found out how I can get access to the history of an object. Is this information kept separately, @ccaputo?

It is available in the admin-only django control panel object view.
