### ISSUE TITLE
Reset password malfunction

### ISSUE THREAD

**Issue by adayton01** [peeringdb/peeringdb#1676]
A while ago, After I had entered (added) my ARIN registered email to my peeringDB account, I fell asleep so I did not be aware that I had to respond to your email of confirming my address addition to account. Therefor the confirmation mechenism evicently failed and has now locked my account on log in attempts on that email address ( adayton@adayton.com. 
    I also have attempted a reset per your support ticket but I do not receive the RESET email from your reset system.

Regfards,

Alfred Dayton
631-928-2424

**Comment by leovegoda** [comment]
Closed per https://github.com/peeringdb/peeringdb/issues/1677
