### ISSUE TITLE
New net_side and ix_side fields on netixlan breaks sync once django-peeringdb is released

### ISSUE THREAD

**Issue by vegu** [peeringdb/peeringdb#1690]
**Describe the bug**
We have a pending release for django-peeringdb that is currently blocked by the new net_side and ix_side fields added to netixlan objects in 2.62 breaking the sync process.

The issue here is that, unlike other relationship id fields these aren't defined with the `_id` suffix, causing a type error with the django-peeringdb backend in peeringdb-py.

This can either be fixed by renaming the fields in the api to `net_side_id` and `ix_side_id` respectively or by adding a custom handler in django-peeringdb that handles this case.

Our current recommendation is to fix it in the api, so it is in line with all the other relationship id fields. (org_id, net_id etc.).

This would be a breaking api change, albeit to a field that has only existed for a week, so any software that was written to access the net_side and ix_side fields would need to be adjusted.

**Comment by grizz** [comment]
+1 to API fix, should be targeted for Next release.

**Comment by tcsweetser** [comment]
+1 for the recommendation :)

**Comment by arnoldnipper** [comment]
+1

**Comment by martinhannigan** [comment]
+1API fix
