### ISSUE TITLE
Finnish translation request

### ISSUE THREAD

**Issue by arhippa11** [peeringdb/peeringdb#1694]
Hello,
I'm following the guide to provide a contribution with the Finnish translation of PeeringDB. Could you please generate the necessary files for the fi_FI locale and add them to the repository?

**Comment by jackcarrozzo** [comment]
@arhippa11 sorry for delay, we are working on this!

**Comment by grizz** [comment]
@arhippa11 Apologies for the delay, this turned out to be a bit more work than we expected, but it's all ready now.

You can start translating at: https://translate.peeringdb.com/projects/peeringdb/-/fi/

Thanks for your patience!
