### ISSUE TITLE
Whois: an error occurred

### ISSUE THREAD

**Issue by grizz** [peeringdb/peeringdb#17]
Reported by Peter Hessler on BSD client, but the same error happens on Linux too:

whois -h whois.peeringdb.com as20940

blah blah

Interxion Madrid (MAD1, MAD2) 20940 Madrid ES
Interxion Frankfurt 2 20940 Frankfurt DE
KDDI Otemachi (Telehouse Tokyo Otemachi) 20940 Tokyo JP
Interxion Copenhagen 20940 Copenhagen DK
an error occurred

Moved from peeringdb/docs#104

**Comment by job** [comment]
What's the plan here? :)

**Comment by grizz** [comment]
This had a lot of internal / deployment deps, but is now: fixed 927f6e1
