### ISSUE TITLE
IX-Port Location not shown on IX pages

### ISSUE THREAD

**Issue by kevin-nlix** [peeringdb/peeringdb#1700]
**Describe the bug**
The port location is now shown on network pages, but it's not yet reflected on IX pages. A label has been added for "Port location" on the IX page though, so I would expect the location to be included there as well. See the screenshots below.

**To Reproduce**
Visit any IX page and scroll through the network list.

**Expected behavior**
The port location should be shown on the network overview on the IX page as it is on network pages.

**Who is affected by the problem?**
Anyone wishing to see where a network connects on the IX.

**What is the impact?**
To see where a network connects from the IX page you now have to visit every network's page individually, which is very time consuming.

**Are there security concerns?**
No.

**Are there privacy concerns?**
No.

**What are the proposed actions?**

**What is the proposed priority?**
Not super urgent given that this is a new feature and there's not much data available yet. However, if we want to make this feature successful it should be easy to use, otherwise adoption rate will stall after the initial bump.

**Provide a rationale for any/all of the above**

**Additional context**
Example of IX page
![Screenshot 2024-11-08 at 11 14 01](https://github.com/user-attachments/assets/4fb7c38d-95d1-4b7e-ad18-52f86e88e85d)

Example of network page
![Screenshot 2024-11-08 at 11 14 12](https://github.com/user-attachments/assets/3b53affd-1ef4-4e6b-b98e-cef5edea63b1)

**Comment by arnoldnipper** [comment]
@kevin-nlix, I guess the logic is that the port location for the net side is shown on the network page and the port location for the ix side is shown on the ix page. For ASN 20562 the ix_side is null.

```
curl -snG https://www.peeringdb.com/api/netixlan --data-urlencode asn=20562 | jq -r '.data[] | .net_id, .ix_id, .net_side, .ix_side' | paste - - - - | sort -k1,1n -k2,2n -k3,3n
821     18      34      null
821     26      18      null
821     26      62      null
821     31      58      null
821     48      177     null
821     53      34      null
821     64      18      null
821     64      34      null
821     64      53      null
821     64      58      null
821     64      62      null
821     64      148     null
821     64      177     null
821     73      58      null
821     74      58      null
821     87      58      null
821     91      58      null
821     193     148     null
821     209     58      null
821     248     58      null
821     291     58      null
821     359     53      null
821     387     177     null
821     676     58      null
821     713     58      null
821     1214    58      null
821     2569    18      null
821     2569    62      null
821     2868    148     null
821     4175    58      null
```
Hence, it's a feature, not a bug

**Comment by kevin-nlix** [comment]
@arnoldnipper, ah of course, it makes sense that both sides are recorded. How can a network edit the IX side, or is that reserved for IX only? From the editing tools available it looks like the latter.

I will consider creating a new ticket in the form of a feature request to make both sides visible somehow. If this feature is to be used to get an indication of the network's location, it should be easy to find.

**Comment by kevin-nlix** [comment]
Yeah it makes sense how it has been implemented for now and it's clear that it's not a bug. I will create a feature request to see both. How that is to be implement is indeed a challenge because that table is already cluttered.

I will close this issue at least because it's no longer relevant with your explanation.
