### ISSUE TITLE
block codepath where users can request affiliation with non-existent ASNs

### ISSUE THREAD

**Issue by job** [peeringdb/peeringdb#172]
Recently had a bunch of spam, part of them was affiliation attempts for non-existent ASNs:

```
User adrain hibbert (peeringemail@mailinator.com) wishes to be affiliated to ASN 1080478291
User adrain hibbert (peeringemail@mailinator.com) wishes to be affiliated to ASN 1009939676216382148
User adrain hibbert (peeringemail@mailinator.com) wishes to be affiliated to ASN 1001139053648774877
```

The system should not send out affiliation requests for ASNs which don't exist anywhere in the PeeringDB

**Comment by vegu** [comment]
This is fixed by #140, ASNs for which no RiR entry can be obtained will no longer be allowed to trigger affiliation requests.

**Comment by job** [comment]
I didn't check the code, but this bug wasn't about whether people can
request affiliation with ASNs that doesn't exist at the RIR level, but the
fact that they can/could? request affiliation with ASNs that don't exist in
Peeringdb.

**Comment by vegu** [comment]
If an ASN does not exist in PeeringDB, a RiR check will be done, if no RiR data is found affiliation request will be canceled. This will prevent the kind of spam of we see above were a user just tries to affiliate with non-sensical ASNs.

As per the current design defined in #142 people should be able to attempt affiliation with ASNs that don't exist in PDB yet as long as a valid RiR record can be found, in which case a network will be automatically created and the user will be validated against the contact information found in the RiR entry to determine whether affiliation should be granted.

If there is still concern of spam abuse with the user trying to affiliate to a bunch of valid ASNs, perhaps the better approach to solve this would probably be to just limit how many affiliations a user can have active at the same time.

Thoughts?
