### ISSUE TITLE
system emails "spoof" from address, which conflicts with DMARC

### ISSUE THREAD

**Issue by job** [peeringdb/peeringdb#174]
Emails like these fail to arrive in deskpro. Google's mail servers honor the DMARC settings for b
ooking.com - and booking.com didn't authorise the peeringdb main server to send email.

```
From: XX.XX@booking.com
To: support@peeringdb.com
Cc: 
Bcc: 
Date: Thu, 22 Jun 2017 08:43:53 -0000
Subject: [prod] network - Booking.com IT Services

A new 'network' has been created and requires your approval.
Name: Booking.com IT Services
Requested by user: XX XX (XX.XX@booking.com)

You can go to https://peeringdb.com/cp/peeringdb_server/network/13804/ to view and approve or deny this entry
```

I think the headers should be constructed as following:

```
From: support@peeringdb.com
Reply-To: XX.XX@booking.com
To: support@peeringdb.com
Cc: 
Bcc: 
Date: Thu, 22 Jun 2017 08:43:53 -0000
Subject: [prod] network - Booking.com IT Services
```

Thoughts?

**Comment by arnoldnipper** [comment]
Makes sense .... merge with #100

**Comment by vegu** [comment]
Just to make sure we are not breaking the workflow you guys have established with deskpro with this change:

This change will change the "From" value for all emails sent to deskpro via the the server to "support@peeringdb.com" - if you currently use the value of this field in deskpro to categorize or group tickets (by user for example) this will no longer work after this change, and you will need to see if deskpro can substitute the Reply-To value in it's stead. I don't have deskpro access, so i cannot test this myself.

**Comment by arnoldnipper** [comment]
@vegu, @grizz does have a DeskPRO account. Is it possible to share this account? And I'm pretty sure this will break everything :)

**Comment by job** [comment]
Why would it break anything?

**Comment by arnoldnipper** [comment]
Gutt feeling, @job

**Comment by job** [comment]
We can simply roll back if there is an issue.

I think this change will improve our services

**Comment by grizz** [comment]
@arnoldnipper shared, now @vegu can do work in my name tho ;)

**Comment by vegu** [comment]
@arnoldnipper How does Deskpro currently assign real names to the tickets, as we are currently not including a real name in the From header, is this done manually?

**Comment by arnoldnipper** [comment]
@vegu We don't add anything manually. But maybe I don't get your question.

**Comment by job** [comment]
I'm open to other DMARC solutions too

**Comment by vegu** [comment]
@job - your initial proposal is the correct way to send those emails, we should not be spoofing the from address - i will be sending some test emails early next week to see how deskpro behaves with the change, and then we can take it from there.

**Comment by vegu** [comment]
@arnoldnipper @job 

Ok so i've sent some test emails - currently there are 2 tickets in DeskPRO 10461 and 10462 - They can also be found easily by searching for DMARC in the **Subject** field.

Here's some things to note:

1. Emails sent from 'support@peeringdb.com' did not show up in DeskPRO at all - maillog on the production box shows they are sent and received without issue - probably a configuration issue somewhere in DeskPRO ?
2. 2 emails sent from 'emailtest@peeringdb.com' showed up in DeskPRO, however emails were sent with different Reply-To headers and different name information in the From header and DeskPRO assigned them to the same user contact - from what i can tell currently DeskPRO relates the 'emailtest@peeringdb.com' address to the '20C' name. Maybe DeskPRO can be told to associate Reply-To addresses instead.
3. When replying to the ticket i've received no emails from DeskPRO to at the addresses specified i n the Reply-To headers, maybe this is something that needs to be configured in DeskPRO as well - although it could be simple mail delay, i've waited ~5 minutes at this point.

Thoughts?

**Comment by vegu** [comment]
Upon further inspection:

DeskPRO right now seems to completely ignore the Reply-To header - and both emails were indeed assigned to the same account which DeskPRO stored as `'20C' - <emailtest@peeringdb.com> `

 Responses to the tickets were dispatched to emailtest@peeringdb.com in both cases and NOT the reply-to addresses.

**Comment by vegu** [comment]
Reverting and stashing the work done on this so far so it does not block the rollout of next release. Moving back to backlog for further discussion.

**Comment by arnoldnipper** [comment]
Not longer relevant as we are using the DeskPRO API
