### ISSUE TITLE
Long addresses obscured in list

### ISSUE THREAD

**Issue by notnyt** [peeringdb/peeringdb#175]
The route server icon is covering up part of the address

![1](https://user-images.githubusercontent.com/1365428/27492957-13e3309a-5816-11e7-8e48-3dbe01330a40.png)

![2](https://user-images.githubusercontent.com/1365428/27493013-3bf30a56-5816-11e7-8c11-905e2233a972.png)

**Comment by lukastribus** [comment]
Duplicate, see:
https://github.com/peeringdb/peeringdb/issues/145

**Comment by arnoldnipper** [comment]
#145
