### ISSUE TITLE
Adding e-mail notification for automagically created records

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/peeringdb#179]
# of "positive" ASN where both ASN and Org do not exist

 # of "positive" ASN where Org exists

 # of "positive" claims for an ownership of an organization that has at least one network in it

e-mail support@peeringd.com in case of "positives" as well but *flag* it so that we easily can process those tickets automatically.

**Comment by arnoldnipper** [comment]
relates to #140, #141 and #142

**Comment by vegu** [comment]
fixed in 1a6eb62
