### ISSUE TITLE
Autocreation tool picks wrong organisation

### ISSUE THREAD

**Issue by grizz** [peeringdb/peeringdb#186]
@arnoldnipper commented on [Thu Jul 06 2017](https://github.com/peeringdb/admincom/issues/37)

DeskPRO https://peeringdb.deskpro.com/agent/#app.tickets,inbox:archive_resolved,t.o:7141,vis:6

ASN 205697
Org according spec: Informatica y Comunicacion Salamanca S.L.U <-- org-name
org picked: ALOJALIA-AS <-- as-name

---

@arnoldnipper commented on [Fri Jul 14 2017](https://github.com/peeringdb/admincom/issues/37#issuecomment-315234904)

https://peeringdb.deskpro.com/agent/#app.tickets,inbox:agent,p:4783,t.o:7349,vis:6

ASN 206050
Org according spec: FreeNetwork s.r.o. <-- org-name
Org picked: AS206050 <-- aut-num ???

---

@arnoldnipper commented on [Fri Jul 14 2017](https://github.com/peeringdb/admincom/issues/37#issuecomment-315235494)

https://peeringdb.deskpro.com/agent/#app.tickets,inbox:archive_resolved,t.o:7240,vis:6

ASN 61399
Org according spec: KG-IX LLC <- org-name
Org picked: AS61399 <-- aut-num ???

---

@arnoldnipper commented on [Fri Jul 14 2017](https://github.com/peeringdb/admincom/issues/37#issuecomment-315235943)

https://peeringdb.deskpro.com/agent/#app.tickets,inbox:archive_resolved,t.o:7211,vis:6

ASN 49037
Org according spec: Megalink Ltd <-- org-name
Org picked: AS49037 <-- aut-num ???

**Comment by grizz** [comment]
It falls back to AS when it can't find the org name, will look into it

**Comment by arnoldnipper** [comment]
Obviously rdap and whois information differs sometimes :(
