### ISSUE TITLE
improve approval notifications

### ISSUE THREAD

**Issue by grizz** [peeringdb/peeringdb#19]
All the admin level users within an organisation get the User XX YY wishes to be affiliated to your Organization emails, but it would be useful if there is a follow-up email to the same group of email addresses that says Admin ZZ approved or denied User XX YY to be affiliated with organisation AA. This way people know that the request has been handled and who handled it.

Moved from peeringdb/docs/issues/103

**Comment by vegu** [comment]
fixed in e5c2892
