### ISSUE TITLE
autoasn doesn't check for reserved blocks

### ISSUE THREAD

**Issue by grizz** [peeringdb/peeringdb#191]
For example https://rdap.apnic.net/autnum/135234

From AC ticket https://github.com/peeringdb/admincom/issues/40

**Comment by grizz** [comment]
@arnoldnipper that AS is assigned now, it looks like that whole block is -- do you have another one handy to test against?

**Comment by arnoldnipper** [comment]
@grizz  https://www.iana.org/assignments/as-numbers/as-numbers.xhtml, e.g. 139578-196607
