### ISSUE TITLE
Change default visibility to "Users"

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/peeringdb#192]
When adding contact information the current default is "Private". This is easily overlooked by customers and esp. creates issues when requesting automated peering setups.

**Comment by netravnen** [comment]
You mean to change the default to 'public', I guess ?

**Comment by arnoldnipper** [comment]
No, I mean "Users"

**Comment by grizz** [comment]
Users seems reasonable to me, any objections?

**Comment by ghankins** [comment]
Users makes sense as a default.

**Comment by netravnen** [comment]
Users compared to Public/Private would definitely be the one preferred
default setting going forward.
-- 
Kind Regards
Christoffer

**Comment by vegu** [comment]
fixed in c1e43de4
