### ISSUE TITLE
add search for organisations

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/peeringdb#193]
Current search - even the advanced - only allows for search for networks, exchanges and facilities
![20170807 peeringdb 00](https://user-images.githubusercontent.com/16888757/29019760-e4259812-7b5f-11e7-9af3-887b3619c85e.png)

However sometimes names from those types of records differ from the name of the organisation

**Comment by grizz** [comment]
What fields would you like to include in the search?

**Comment by arnoldnipper** [comment]
Name, City, Country and Continental Region (the latter both with option ctrl/cmd click to select multiple)

**Comment by eloos** [comment]
Once we start touching this screen, does it make sense to also implement #265 ?
I support at the very least @arnoldnipper suggestions but I am also for really taking a leap on functionality so we have something to show for by doing #265

**Comment by grizz** [comment]
@peeringdb/pc no votes on this, +1 from me

**Comment by mcmanuss8** [comment]
+1 makes sense to add, but I don't think #265 is a blocker

**Comment by eloos** [comment]
@arnoldnipper picking this up again, you want to add a tab to search for organisations by the same criteria as we currently do exchanges?
I would guess that you would like organisations to show up when they have either a presence in a facility for that city/country or are present at an exchange in the city country? 
All this in addition to also the name tag?
Alternatively, should we add looking for the organisation to the "networks" tab and add the city/country information? I believe the geographical scope is today set by the user

**Comment by arnoldnipper** [comment]
> I would guess that you would like organisations to show up when they have either a presence in a facility for that city/country or are present at an exchange in the city country?

No, the intention was to show all records owned by that organisation criteria. Network, IX and facility may widely differ from an organisation name, hence being able to search by organisation makes sense IMHO

**Comment by mcmanuss8** [comment]
+1 let's add search by organization.

**Comment by arnoldnipper** [comment]
+1 let's add search by organisation.

**Comment by grrrrreg** [comment]
+1 makes sense to me
would it also make sense to display the returned results for Organizations grouped by IX, Network and Facilities? (maybe I'm missing something)

**Comment by eloos** [comment]
@arnoldnipper coming back to the original request, since the network record has an entry to the org, if you look for a network in the network tab by typing in the org name it works. For instance, on beta.peeringdb.com at the moment I have removed "Belgacom International Carrier Services" from the "also known as" field on BICS, and still if you look up "belgacom" it will show you the BICS record, only when in the org I change belgacom to belgacam for instance, BICS stops showing up. This proves that the current behavior already will show networks if you look them up by org name. Can you confirm that this is the behavior you want or what else would you want?

**Comment by arnoldnipper** [comment]
@eloos sometimes the org name is completely different from the network name. If you only know the org name that doesn't help you as you will not find anything

**Comment by mcmanuss8** [comment]
@eloos Yeah that's what I was thinking, especially since we already have them grouped by net, ix and fac. Just add another column for org results

**Comment by koalafil** [comment]
As I understand the consensus is to have both 1 and 2 below:
 
1. results show a column as "Organizations" next to the existing columns (Exchanges, Networks and Facilities) when one uses a keyword in search. See mockup below with example of "Asteroid" as keyword. 

AND

2. A separate column is made available as "Organizations"  in the Advanced Search (next to the existing Exchanges, Networks and Facilities). On the Organizations view, we should have search criteria with Name, City and ASN imo. 

I am attaching mockup views for both 1 and 2 below: 

For 1, possible look with example searched for Asteroid as keyword in simple search:

![image](https://user-images.githubusercontent.com/49520571/67235470-738d3480-f447-11e9-9ca8-2a73a251e3ea.png)


For 2,  possible look for an Advanced search tab :

![image](https://user-images.githubusercontent.com/49520571/67235540-90296c80-f447-11e9-8cec-90ed342a5252.png)



@mcmanuss8 @eloos @grizz can you pls comment and confirm what I have specified above?  20C is asking for clarification before they can Quote this one.  Thx!

**Comment by mcmanuss8** [comment]
Yes, this is exactly what I'd like to see

**Comment by vegu** [comment]
For the quick search implementation the extra column for organizations will reduce individual column width and push sponsorship badges to the next row more frequently than before. Please see attached screenshot. 

Sponsorship badges being pushed to the next row on longer entity names was already a small concern with the current implementation if i remember correctly.

Not sure what the best way to address this, or if it even needs to be addressed in the scope of this issue, but wanted to give a heads up.

![Screenshot 2019-12-12 at 16 26 33](https://user-images.githubusercontent.com/143124/70736987-36904080-1d1a-11ea-962a-1ba898601f17.png)

cc: @ccaputo

**Comment by ccaputo** [comment]
Not ideal, but I don't see an easy work-around.  Off the cuff idea is to change from a 4x1 grid to a 2x2 grid, with Exchanges & Networks on top row/section (since generally most important?), and Facilities & Organizations on a second row/section.  Ie.

Exchanges (1) | Networks (2)
...
Facilities (0) | Organizations (1)
...

I defer to @peeringdb/pc re this.

**Comment by arnoldnipper** [comment]
Half of the page is unused, even on my laptop. So 2x2 should work

**Comment by grizz** [comment]
With 2x2, searches with a lot of results would put the second row below the fold. We could decrease the padding between columns, but it still can get ridiculously wide.

If we let results define the width with a fluid grid, it would probably show up as 2x2 most of the time, which would work if we added summary first line under the header with the total results, click to scroll type thing. So for that example, first line spanning both columns would be something like:

`Results: Exchanges (1) | Networks (2) | Facilities (0) | Organizations (1)`
