### ISSUE TITLE
Add partners page

### ISSUE THREAD

**Issue by ghankins** [peeringdb/peeringdb#194]
We need to add a partners page that is similar to the sponsors page, but simpler.

**Admin Page**

1. Add a "Partners" administration page to the "PeeringDB administration" page.

2. The "Partners" administration page is similar to the "Sponsorships" administration page, but we don't need as many controls.
* Org box and + control
* No start or stop date, logo should be listed at all times until the partner is deleted
* Level dropdown: currently only need "Data Validation Partner" and "RIR Partner", but may need to expand categories in the future
* URL box
* Logo box and upload controls
* Status box (read-only)

**PDB Page**

1. Add a "Partners" link to the PDB footer under the "Sponsors" link that goes to the partners page.

2. Each partner category should have it's own page size, they can all just all be the same size as Platinum sponsor logos for now until if/when we need to set different sizes in the future.

3. Each partner category should display logos in random order, just like the sponsors page does now.

**Comment by vegu** [comment]
implemented in 3c4a157

**Comment by arnoldnipper** [comment]
Why not leave in start and stop? Doesn't add much work and if partnership is terminated it's easy to resume.

**Comment by vegu** [comment]
This has been moved to beta in the current implementation, if there is agreement to implement start and stop after all can reopen or make a new ticket at a later point.
