### ISSUE TITLE
Add "one click" option to automation tool

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/peeringdb#195]
Currently full automation is only done, if the requestor's email address is found in the RIR RDAP lookup. If there is a mismatch an email ist sent to support@peeringdb.com with much the same information as in the old tool chain.

A simple "Approve" URL, kicking of

 * moving reuqest from "pending" to "approved"

 * sending an email to the requestor

would off-load additional work from Admins

**Comment by vegu** [comment]
fixed in fb898001
