### ISSUE TITLE
Autocreation tool has to do recursive/additional lookups

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/peeringdb#197]
RDAP and RIPE DB do return different results, but you can find the other addresses by executing some additional queries. 

In your case, the address abuse@vusam.com is the abuse contact for AS205726 (https://rdap.db.ripe.net/autnum/205726). 
The address support@vusam.com can be found in https://rdap.db.ripe.net/entity/ORG-DJVG1-RIPE
And daan.vangorkum@vusam.com by executing https://rdap.db.ripe.net/entity/DJVG

**Comment by arnoldnipper** [comment]
Split of from #188 which originally deals with another problem

**Comment by arnoldnipper** [comment]
Same hold for organisation.

E.g. ASN 203433. Tool currently returns AS203433 whereas with recursive lookup it would return "Association Auvernet"

**Comment by arnoldnipper** [comment]
@grizz / @vegu  ... any **estimate** on this. Currently roughly 60%-70% of all ASNAUTO are created with crappy net- and orgnames

**Comment by grizz** [comment]
@arnold Are you asking when it will be done? It's in the current Epic we're working on.

**Comment by arnoldnipper** [comment]
Forgive me that " It's in the current Epic we're working on" does not say me when it will be ready. Is there an estimate?

**Comment by grizz** [comment]
Sorry, it will be deployed to beta by Jan 8th, as decided on the PC call.

**Comment by grizz** [comment]
@arnoldnipper Where are you getting https://rdap.db.ripe.net/entity/ORG-DJVG1-RIPE from?

**Comment by grizz** [comment]
@peeringdb/pc Are there any entity types that should be skipped?

**Comment by arnoldnipper** [comment]
@grizz 

curl -sG https://rdap.db.ripe.net/autnum/205726 | jq '.entities[0]'
{
  "handle": "DJVG",
  "roles": [
    "administrative",
    "technical"
  ],
  "objectClassName": "entity"

**Comment by arnoldnipper** [comment]
@grizz there are no entity types to be skipped, but ideally leave out registrant data from RIR, regional LIR. Maybe we should only evaluate 

 "roles" : [ "administrative", "technical" ],

**Comment by grizz** [comment]
@arnoldnipper 
> "handle": "DJVG",

I see that one, was asking about `ORG-DJVG1-RIPE`

> "roles" : [ "administrative", "technical" ],

Sounds good, we'll make it configurable.

**Comment by arnoldnipper** [comment]
>>"handle": "DJVG",
>
> I see that one, was asking about ORG-DJVG1-RIPE

Looks I was picking that information from whois, @grizz
