### ISSUE TITLE
Contact fields removed extra spaces, new line chars, and html formating

### ISSUE THREAD

**Issue by esundberg** [peeringdb/peeringdb#2]
Minor spacing issue in HTML code for all contact fields. This is causing issues when copying and pasting email address from peeringdb.  You  end up copying the spaces and newline chars along with the email  address. I am using chrome. This happens on all peeringdb records not just this one entry.

The html code for contact names, phone, and email has the following. Below is an example which is an email address. From: view-source:https://www.peeringdb.com/net/917  line 891. There are extra spaces and new lines.

                 <div class="email"
                      
                      data-edit-value="pkaushal@lsnetworks.net"
                      data-edit-name="email">
                    pkaushal@lsnetworks.net
                 </div>

When it should be this so copying an pasting doesn't pickup the new line chars and spaces.

                 <div class="email" data-edit-value="pkaushal@lsnetworks.net" data-edit-name="email">pkaushal@lsnetworks.net</div>

**Comment by vegu** [comment]
fixed 720a275 (2.0.11)
