### ISSUE TITLE
AS-SET schema

### ISSUE THREAD

**Issue by grizz** [peeringdb/peeringdb#202]
All current entries should be converted to a dict of $source: $as_set

Original field can be left until version 3

**Comment by respawner** [comment]
What about networks that use several AS-SET?
I've seen networks using different AS-SET for IPv6 and IPv4 for example.
It is a pain to deal with this, programmatically speaking :(
Maybe a delimiter should be defined (could be a simple space) but I guess that at least we should normalize the way of specifying multiple AS-SET for one network.

**Comment by eloos** [comment]
@respawner this is covered in issue #26.
