### ISSUE TITLE
Don't allow duplicate email addresses for user accounts

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/peeringdb#205]
If a email address is already used disallow registration. There is no added value in having multiple accounts with the same email address, esp. as password recovery only is working with unique email addresses

**Comment by vegu** [comment]
This is already the case, in v2 users are not able to register by using email addresses that already exist in the system. There might still be duplicate addresses from v1 in the system, but new registrations using duplicates will be blocked.

**Comment by arnoldnipper** [comment]
That's simply not true

**Comment by vegu** [comment]
That is a bug then, need to investigate how this happened, but when i try to sign up with my existing email address it is blocking correctly.

Labeling as bug.

**Comment by vegu** [comment]
Looks like an unwanted side effect related to the initial v1 user import. 

Signing up with an email attached to a user account imported from v1 will fall through the validation check. As soon as a v2 user exists with the email address it will block correctly.

**Comment by vegu** [comment]
fixed in 7ec096b

**Comment by vegu** [comment]
Note: this only fixes the bug where some email addresses were allowed to be re used during registration. Clean up of existing dupes needs a separate ticket (and probably some discussion)
