### ISSUE TITLE
Drop IX Lans

### ISSUE THREAD

**Issue by grizz** [peeringdb/peeringdb#21]
see http://lists.peeringdb.com/pipermail/pdb-tech/2016-April/000104.html for discussion

**Comment by job** [comment]
How much work is changing this? Wouldn't everyone need to update their software?

**Comment by job** [comment]
Maybe the issue isn't that the complication lays with PeeringDB, but with the IXPs that have complex setups that need to be expressed in PDB. I'm looking at you netnod.

**Comment by grizz** [comment]
My plan is to simply set each ixlan_id to the ix_id, the structure would remain the same, but could be ignored since the ids would be guaranteed to match -- it could then safely be dropped for version 3. The only change that would need to be made would be to change netnod's LANs to each be it's own IX (and it's not their fault, the schema was from Euro-IX, they just used it).

**Comment by job** [comment]
it is Netnod’s own choice to make a gazillion vlans with slightly different
attributes.

And having multiple IXPs that are actually one and the same might make even
less sense to me.

I’d just leave it for now.

**Comment by grizz** [comment]
It's a poor design that makes it overly complicated in favor of having the data expressed exactly how it is IRL -- their LANs are essentially separate IXes, they just happen to be on the hardware at the same location. If a network is on one LAN and not another, it does no one any good to know that there are in fact multiple LANs so there's no reason for that data to be expressed.

It also hurts PDB in that netnod is the only one using the LAN "feature" -- other IXPs (ie, INEX, LINX) that have multiple LANs express them as separate IXPs, so there's no consistency. By dropping this we would ensure that all IXPs with multiple LANs are shown in the same way.

**Comment by job** [comment]
If Netnod really is the only one the change is easier than I expected and
I’d perhaps be less reluctant to let go of the ixlan concept.

**Comment by grizz** [comment]
So it's a bit more than 1:
```
+------+-------------------+-----+
| id   | name              | cnt |
+------+-------------------+-----+
|   18 | LINX LON1         |   2 |
|   31 | DE-CIX Frankfurt  |   2 |
|   42 | HKIX              |   2 |
|   53 | LONAP             |   2 |
|   64 | NL-ix             |   2 |
|   70 | Netnod Stockholm  |   4 |
|   72 | GigaPIX           |   2 |
|   98 | FICIX Helsinki    |   2 |
|  129 | JINX              |   2 |
|  192 | Netnod Gothenburg |   2 |
|  193 | Netnod Copenhagen |   4 |
|  194 | Netnod Sundsvall  |   2 |
|  257 | Netnod Lulea      |   2 |
|  311 | VSIX              |   2 |
|  344 | CINX              |   2 |
|  492 | FICIX Oulu        |   2 |
|  655 | GigaNET           |   5 |
|  662 | Phoenix IX        |   2 |
|  694 | GIXA              |   2 |
| 1171 | KIVIX             |   2 |
| 1302 | IX Liverpool      |   3 |
| 1332 | FICIX Espoo       |   2 |
| 1420 | TRDIX  Trondheim  |   2 |
| 1488 | Vegas-IX          |   2 |
| 1489 | Aloha-IX          |   2 |
| 1490 | Richmond-IX       |   2 |
| 1776 | GABIX             |   2 |
| 1794 | IX Palmas         |   2 |
+------+-------------------+-----+g
```

Just from spot checking, I found https://peeringdb.com/ix/655 -- clearly those should be separate IXPs, it will take clean up, but this makes me even more in favor of dropping IX Lans.

**Comment by eloos** [comment]
@grizz interesting find, although I would argue that the setup you desribe for 655 is exactly the use case where I think it makes sense to understand the various options I have on the same dot1q port, which I would have a far harder time understanding if they were listed as multiple exchanges

**Comment by grizz** [comment]
@eloos I don't know how their topology is, I only see a few networks that are on more than 1 of those, and I see a lot which have IPs on the wrong IX Lan. Either way, there's still no way to know if the peer network is connected to all of them on the same physical port, or has a dedicated port.

And you gain no added information about anything between using the IX Lan and having them as separate IXes. If that's what you want to solve, that is a use case for adding physical layer (referenced in #15).

**Comment by eloos** [comment]
@grizz and of course the multiple IXP's are still bundled together under the IXP Org object... ok, shall we then move to drop the ix_lan object and have a vote on it?

**Comment by martzuk** [comment]
I think the duplication added by having separate IXPs (e.g. SIX Seattle, ESPANIX et al.) is unnecessary, however having more than one for a physical IX makes viewing the data on peeringdb.com more cumbersome. In either case, to get better data quality I think we need to take one of these actions, and then enable verification (https://github.com/peeringdb/peeringdb/issues/8). In my opinion @job's suggestion is the better one, as it allows me to map a physical port on a router to an IX and then treat the LANs as subinterface units.

**Comment by as44980** [comment]
IMHO "Peering LAN" = Broadcast domain and I expect to be able to find peers who I have the potential to establish sessions with based on having an ip(v4/6) address in that "LAN"...

I am less convinced by the use case of figuring out what other services and/or peering lans are available on the same physical port :)

**Comment by grizz** [comment]
@peeringdb/pc thoughts / votes?

**Comment by arnoldnipper** [comment]
Let's drop it ... make life easier .... and meanwhile a lot of IXes did already change their setup.

**Comment by fhibler** [comment]
+1 drop it

**Comment by grizz** [comment]
@peeringdb/pc 

Just to be clear, this will result in ixlan IDs changing, so there should probably be a community announcement ASAP. It will not affect the current API otherwise, but will pave the way for us to be able to easily remove ixlans from the version 3 API, whenever that happens.

**Comment by arnoldnipper** [comment]
@peeringdb/pc 

What about several steps

  * decision to drop `ixlan`

 * announcement  to the community that we renumber `ixlan` with e.g. the first release in 2020 

 * AC to work with each IX having multiple `ixlan` to remodel their IX

 * on day d-1 auto-remodel leftover IXes

 * enforcing that number of `ixlan` per `ix` <=1

 * on day d, renumber `ixlan` to make ixlan_id == ix_id

**Comment by mcmanuss8** [comment]
+1 on the rollout plan

**Comment by grizz** [comment]
+1 rollout plan

**Comment by arnoldnipper** [comment]
@grizz and @vegu, implementation details needed?

**Comment by grizz** [comment]
@arnoldnipper for the beta deploy today,we'll just auto model the IXes and enforce the ixlans are <= 1

Is that ok?

**Comment by arnoldnipper** [comment]
> @arnoldnipper for the beta deploy today,we'll just auto model the IXes and enforce the ixlans are <= 1
> 
> Is that ok?

First of all, there should only be `ix` with # `ixlan` >= 1 atm. And what happens with `ix` with # `ixlan`>1? Do you auto-migrate them to new `ix`?

**Comment by grizz** [comment]
@arnoldnipper We followed the rollout plan, can discuss on the call if the AC is ready yet.

Closing this so it shows up in the beta changes -- maybe make a new ticket to discuss that?

**Comment by arnoldnipper** [comment]
Please also copy contact information to the newly created ixes

**Comment by grizz** [comment]
@arnoldnipper I'm not sure what you mean? This is already done and deployed, it should be a new ticket.

**Comment by arnoldnipper** [comment]
I hoped it would be easy to add the contact information and could be done immediately. If I open a new issue that will be implemented in a month earliest :( 

Iow when dropping ixlans the new ixes should have inhibited **all** information from the original ix including contact information. Does that make sense?
