### ISSUE TITLE
When looking up ASN information fetch admin-c and tech-c emails

### ISSUE THREAD

**Issue by netravnen** [peeringdb/peeringdb#216]
When looking up ASN information/emails.

Would it not be a valid choice to auto approve a request if either a match is found within the admin-c og tech-c records ?

Currently emails is only found if directly connected to the ASN object. (E.g. abuse, notify etc.)

_NB: I'm talking about RIPE DB in this case. Haven't explored the other RIR databases(!)_

**Comment by eloos** [comment]
Wouldn't this imply that anyone inside a roll account could become the administrator of the PDB record of a company? What is the level of staleness present in org-c and admin-c? I have no idea. Preferably the person inside an organisation that has the administration authority on a RIR should be the one with the authority to create a PDB entry. Possibly are efforts are better geared towards getting all the RIR's on board with this? APNIC seemed to be in favour already.

**Comment by boggits** [comment]
The staleness in those objects is quite high (I've been listed in some objects many years after leaving an organisation in the past) so while the idea is good the current data isn't clean enough to support this

**Comment by grizz** [comment]
This needs PC decision, it's essentially already done via RDAP, explained at https://github.com/peeringdb/peeringdb/issues/197#issuecomment-354506288

It would also require a new whois implementation, I vote no on it.

**Comment by netravnen** [comment]
Stands to reason to reject this idea when I now reflect on it.
