### ISSUE TITLE
Chat room for cooperative working between IX and BGP engineers

### ISSUE THREAD

**Issue by mwtr** [peeringdb/peeringdb#218]
I'm Masataka Mawatari from JPIX.
I presented in APNIC 44 lightning talk, and proposed chat function as an additional function in PeeringDB.
https://www.slideshare.net/apnic/chat-and-operation-with-operators-in-foreign-countryregion
As you can see the slides on the above URL, if PeeringDB would have chat function, it could be more useful for IX and BGP engineers.
IX engineer will create a chat room on PeeringDB, and send an invitation to BGP engineer of IX participant as a guest.
I think that the chat room needs to be retained for them after cooperative work, it's available for only working time between them on activation of new IX port or turn-up new BGP session on router or route server.

**Comment by job** [comment]
Dear Masataka, would there be any reason to limit this to just IXP<>Operator interaction?

**Comment by mwtr** [comment]
Thank you for your comment, Job-san. I have special reasons for it.
Originally this focused on IXP engineers and BGP operators interacting for only activating or upgrading IX port (That reason is if they always could use chat for any inquiries, IX engineers might become very busy :)), because I have only the point of view as an IXP engineer now.

**Comment by grizz** [comment]
Closing this as I think chat is currently outside of PDB's scope, please reopen if you would like further discussion.

Also, this has been solved by IRC for quite some while, #ix for example. :)

**Comment by mwtr** [comment]
Okay. I will think alternative idea. I hope that cooperative work between ISP engineers and IXP engineers will become easier and smoother. If it's on peeringdb, it makes engineers happy, I believe. :)
