### ISSUE TITLE
Support for gshut

### ISSUE THREAD

**Issue by boggits** [peeringdb/peeringdb#219]
Add a tick box or other mechanism to show that the ASN supports the gshut well know community on peering sessions

**Comment by lukastribus** [comment]
Can you elaborate why this would be useful? What do you do different if the remote ASN supports GSHUT?

**Comment by boggits** [comment]
Its means that I can then signal that the link is going away as part of a maint and they can re-route away from the link - ask @job for details :)

**Comment by job** [comment]
I dont think a flag on peeringdb will impact your operations, whether the flag exists or not you wouldn't do anything different, it would at best exist to promote the use of GSHUT. I am not sure about this feature request.. :)

**Comment by benmaddison** [comment]
Yeah, agree with @job on this. Sane thing to do is send gshut anyway, hope it drains, shutdown the session. If your peer has not implemented it, then you'll presumably have to shutdown the session anyways. It's not clear to me how advance knowledge of the peer's behaviour makes any difference, given that sending the community to a peer who is not listening does no harm.

**Comment by lukastribus** [comment]
I meant why a GSHUT flag would be useful **in peeringdb**. Very aware of what GSHUT is, but I disagree that this would be useful as a flag in peeringdb.

Unnecessarily introducing flags that very likely only a small percentage of operaters keep updated anyway with a questionable operational benefit, all while having to change API's and db schemes - what for? What's the reason you cannot send GSHUT to all networks?

What's next, flags for RFC8092 and RFC8203?


Lets not overload peeringdb with unnecessary flags and options, please!

**Comment by grizz** [comment]
Agree this doesn't belong as a flag in PDB, please reply and reopen if anyone would like to further discuss.
