### ISSUE TITLE
Notes: Newlines in Javascript Markdown renderer should behave same as in the python renderer

### ISSUE THREAD

**Issue by lukastribus** [peeringdb/peeringdb#221]
Please consider the newlines in the notes section, currently, newlines are scrambled:
https://www.peeringdb.com/asn/20811

Replace:
`\n`
with:
`<br />\n`

while preparing the content for the browser (in the code path where html is escaped).

**Comment by vegu** [comment]
Notes is a markdown enabled field, as per markdown specs (https://daringfireball.net/projects/markdown/syntax#p) to force a line break a line needs to end with two or more spaces

**Comment by lukastribus** [comment]
@vegu Alright, that works.

But I still see a severe usability issue here. The JS/AJAX update after hitting "Save" makes the text look very different than the actual page impression.

The JS interpretation of the field seems to use a extremely relaxed markdown parser, while the "PHP" markdown parser is strict.

Put the following text in the notes section and compare what the browser shows after hitting Save, and what an actual page impression would look like:

```
Here's a list:
- Item number one
- Item number two
- Item number three
```

The JS generates a nice list, actual page impression does not; because proper markdown requires a empty line before the list (at least in my experience). Same thing with newlines: JS will replace newlines with `<br >`, which is invalid as per the markdown specs you posted.


The point is: we can't have a relaxed parser for the page update after hitting "Save" and then a strict markdown parser when actual page impression takes place.

**Comment by vegu** [comment]
You are right, this is definitely a bug and needs to be addressed, they should behave the same. Can leave this ticket open to track the issue.

**Comment by vegu** [comment]
I updated the issue title to reflect the findings in this discussion - I am wondering if there needs to be discussion in which way to go

1. strict newlines syntax like it is implemented in the python renderer (after page reload)
2. lax newlines syntax like it is implemented in the javascript renderer (after hittin save)

**Comment by lukastribus** [comment]
Ok, but do we *really* need the javascript renderer at all? Can't we just reload the page after a Save?

The javascript renderer just seems like unnecessary complexity to me; complexity that may generate bugs beyond this specific newline issue.

**Comment by vegu** [comment]
That would change the way forms behave across the entire site and while it can certainly be argued for or against, is not within the scope of this ticket.

There might be a middle ground where we either

- drop the javascript renderer and update the field after save from a value generated by the backend - this has some other implications, as the form is tied directly to the `REST` api, so that output would needed to be added there as well.
- drop the backend renderer and offload to javascript during page-load as well

**Comment by lukastribus** [comment]
Seems like the simplest fix would be to drop the backend renderer and do everything in JS then, which is also fine, in my opinion.

I'm just objecting to manually replicating the behavior of one renderer to the other, because both are in use.

**Comment by vegu** [comment]
> Seems like the simplest fix would be to drop the backend renderer and do everything in JS then

Agreed
