### ISSUE TITLE
Add Last Updated for fac and ix objects on web

### ISSUE THREAD

**Issue by yang-dev** [peeringdb/peeringdb#223]
Currently only net object has `Last Updated` field. It would be nice to have the same for ix and fac objects. `updated` field is already available from API.

**Comment by eloos** [comment]
@yang-dev can you clarify what you expect to see? For instance, would you like to see the Last Updated date of an /ix/ object reflect when a new member has joined?

**Comment by mahtin** [comment]
@eloos - Presently ``Last Updated`` on a ``/net/`` or ``/asn/`` web display (and API) is the date of last change for the core data for that network and not for an additional peering or locations items having been added, changed or deleted.

Hence add ``Last Updated`` on a ``/ix/`` or ``/fac/`` web display and make it be the same functionality - just show a change to the core data for that object.

The same field should be added for ``/org`` on the web display as the backend data is there. However, as the ``org`` record is somewhat newer, there's a good hunk of data that could have a somewhat strange ``update`` dates that relate to the migration times vs. user input. For example:

```
$ curl -sS 'https://peeringdb.com/api/org?depth=0' | jq . | egrep updated | sed -e 's/..:..:..Z//' | sort | uniq -c | head
   1       "updated": "2011-02-22T",
   1       "updated": "2015-11-11T",
   1       "updated": "2016-02-24T",
 202       "updated": "2016-03-11T",
5000       "updated": "2016-03-14T",
 108       "updated": "2016-03-15T",
  27       "updated": "2016-03-16T",
  16       "updated": "2016-03-17T",
   4       "updated": "2016-03-18T",
   2       "updated": "2016-03-19T",
$
```
I'll leave that for another issue.
