### ISSUE TITLE
BFD support flag

### ISSUE THREAD

**Issue by richardhkirkando** [peeringdb/peeringdb#224]
We've begun using BFD sessions with a number of our peers. The MICE website's participants page has added a column with this, and that has encouraged a few networks to offer it.  It could also be an option for IX route servers.

IMO it would be useful to have a BFD support flag in peeringdb for organizations using this, so consider it a feature request if y'all agree!

**Comment by lukastribus** [comment]
Similar to #219, I disagree.

What's the operational benefit?

You still have to clarify with your peer whether to use BFD or not, just like MD5 or TTL-security, even if that flag is on. So documenting it has no actual operational benefit in my opinion.

**Comment by job** [comment]
Indeed, similar to #219 

This needs to be fixed in some other way, where your device or management system can actually negotiate with the peer’s router or peer’s management system on what the setting should be.

Putting this in peeringdb as just a flag is too coarse and doesn’t benefit automation

**Comment by grizz** [comment]
Going to close this as out of scope, please reopen if you would like further discussion.
