### ISSUE TITLE
Public Peering Exchange Points sort secondary key

### ISSUE THREAD

**Issue by jkldgoefgkljefogeg** [peeringdb/peeringdb#225]
For Public Peering Exchange Points, when sorting by speed, use Exchange as secondary key.

For example [Facebook ](https://www.peeringdb.com/net/979), 4 x 200G AMS-IX ports not adjacent to each other in sort by speed results.

Same issue also exists in **Peers at this Exchange Point**
Example [AMS-IX](https://www.peeringdb.com/ix/26), when sort by speed, Google's 2x200GE ports are not adjacent to each other.

**Comment by grizz** [comment]
+1 from me, @peeringdb/pc vote please

**Comment by arnoldnipper** [comment]
+1

**Comment by mcmanuss8** [comment]
+1 in theory but I think this is already fixed? I'm unable to reproduce on /net/ and /ix/. 

Side note: The arrow seems to be pointing in the wrong direction when sorting by speed (points up when sorting descending, points down when sorting ascending)

**Comment by grizz** [comment]
@mcmanuss8 you're right that it works now, sorry for not checking it.

I think the arrows are backwards, but it might turn into a religious debate. :) Created #596
