### ISSUE TITLE
'ADW Telecom' not able to add asn266523 to PDB

### ISSUE THREAD

**Issue by netravnen** [peeringdb/peeringdb#226]
Do @grizz or @job or any other PDB developer any idea about what is happening here ? (screenshots)

![2017-10-17 21_47_09-problemas-peer](https://user-images.githubusercontent.com/1938389/31686925-15302228-b388-11e7-82f6-6994e012b398.png)

![2017-10-17 21_47_14-peering](https://user-images.githubusercontent.com/1938389/31686924-1516760c-b388-11e7-8e8d-b8bedfbfde0e.png)

The network does obviously not exists. And I was unable to find any reference to the network in the /cp/ verification queue and soft deleted networks section.

Refer to the following tickets for info from the end user:
https://peeringdb.deskpro.com/agent/#app.tickets,inbox:agent,t.o:11108,vis:5
https://peeringdb.deskpro.com/agent/#app.tickets,inbox:agent,t.o:11118,vis:5

**Comment by vegu** [comment]
asn is probably in the system as deleted, make sure you set the status filter to "all" or "deleted" when searching for it.

**Comment by vegu** [comment]
oh i see you already searched soft-deleted networks, taking a loo

**Comment by vegu** [comment]
I find it when searching for it with status deleted, how were you searching soft-deleted networks in the cp ?

**Comment by vegu** [comment]
for reference: its network id 14405

**Comment by netravnen** [comment]
👌🏼Thx for info. Must have forgotten to change the default search filter when I searched soft deleted networks. (Usually only create stuff in the database😅)

**Comment by netravnen** [comment]
Found I clicked the button 'recover deleted networks ' instead of changing the filter. 🤥 Explains why I was unable to located the soft deleted object/network earlier.

**Comment by vegu** [comment]
understood, thanks for clarifying!
