### ISSUE TITLE
Please sanity check the database and contact the AS with incorrect information

### ISSUE THREAD

**Issue by vias79** [peeringdb/peeringdb#227]
I've written code which hooks into your API for selected IX nodes. During this process I've found several documentation errors which makes automatic peering impossible.

Could you please sanity check the database and perhaps email the contacts and ask them to correct their information. It's in the best interest of everyone :)

Example:
  Netnod Copenhagen - MTU1500, IX ID = 193, IX LAN ID = 193, IX IPv4: 195.69.117.0/24, IX IPv6: 
  2001:7F8:D:200::/64
   
  Any AS connected to this specific IX needs to have their IPv4 and IPv6 within these ranges. If not email 
  and ask them to correct it.
 
  If my AS has IX IPv4: 195.69.118.250 and IPv6: 2001:7F8:D:200::236 I would get an email.

PHP code example:
if(!net_match($ix_ipv4,$as_ix_ipv4) OR !net6_match($ix_ipv6,$as_ix_ipv6)) {
  email_the_as(...);
 }
function net_match($network, $ip) {
        $ipArray = preg_split("/[\/]+/", $ip); //fix if IP contains cidr
        $ip = trim($ipArray[0]);
        $ip_arr = explode('/', $network);
        $network_long = ip2long($ip_arr[0]);
        $x = ip2long($ip_arr[1]);
        $mask =  long2ip($x) == $ip_arr[1] ? $x : 0xffffffff << (32 - $ip_arr[1]);
        $ip_long = ip2long($ip);
        return ($ip_long & $mask) == ($network_long & $mask);
}
function net6_match($network, $address) {
        $exists = 0;
        $address = inet_pton($address);
        $address = gmp_init(bin2hex($address), 16);
        if (false !== $pos=strpos($network, '/')) {
            $prefix = substr($network, 0, $pos);
            $bitlength = substr($network, $pos+1);
            $network = inet_pton($prefix);
            $network = gmp_init(bin2hex($network), 16);
            $mask = str_repeat('1', $bitlength).str_repeat('0', 128-$bitlength);
            $mask = gmp_init($mask, 2);
        }
        else {
            $network = inet_pton($prefix);
            $network = gmp_init(bin2hex($network), 16);
            $mask = str_repeat('1', 128);
            $mask = gmp_init($mask, 2);
        }
        $masked_address = gmp_and($address, $mask);
        $masked_network = gmp_and($network, $mask);
        if(gmp_cmp($masked_address, $masked_network) === 0)
            $exists = 1;
        return $exists;
}

Also it would be nice if these functions was used when an AS enters their information to eliminate future errors.

**Comment by arnoldnipper** [comment]
We are cleaning up the IX structure to get rid of the ixlan structure. We currently already check that new entries are within the IP range of the IX. After restructuring we will also remove any `netixlan` entry not compliant with the `ixpfx`.

Would you like us to keep this issue open, @vias79? If not, please close it.

**Comment by vias79** [comment]
Ok, thanks for info. Good luck with the datacleaning :)
