### ISSUE TITLE
Add mouseover tooltips to various pdb record fields to explain what they are

### ISSUE THREAD

**Issue by job** [peeringdb/peeringdb#228]
I think we can make the website slightly easier to use if we add mouse over tooltips on various fields to further elaborate on what they are.

"IRR Record" -> "Reference to an AS-SET or ROUTE-SET in Internet Routing Registry (IRR)"
"IPv4 Prefixes" -> "Recommended IPv4 maximum-prefix limit to be configured on peering sessions for this ASN"
"IPv6 Prefixes" -> "Recommended IPv6 maximum-prefix limit to be configured on peering sessions for this ASN"

**Comment by job** [comment]
bump

**Comment by mcmanuss8** [comment]
+1 Let's do this

**Comment by mcmanuss8** [comment]
@peeringdb/pc could we get another vote here please?

**Comment by arnoldnipper** [comment]
+1 ... agreed by @job, @mcmanuss8  and @arnoldnipper

**Comment by grizz** [comment]
+1

**Comment by mcmanuss8** [comment]
To be explicit, let's add tooltips for the 3 @job mentioned and then we can open more issues for more fields w/ tooltips in additional issues
