### ISSUE TITLE
When editing an IX LAN and saving, re-toggling edit mode will have the form fields to revert back to the original values.

### ISSUE THREAD

**Issue by vegu** [peeringdb/peeringdb#229]
Data is saved to the server correctly, seems to be an issue of updating the values locally in the form fields afterwards - other sections of the editor do not have this problem as far as i can tell.

Issue observed in Chrome Version 61.0.3163.100

**Comment by grizz** [comment]
+1
Another small bug we can knock out, votes please @peeringdb/pc

**Comment by arnoldnipper** [comment]
+1

**Comment by mcmanuss8** [comment]
+1 fix it please

**Comment by shane-kerr** [comment]
+1

**Comment by grizz** [comment]
Fixed in #21
