### ISSUE TITLE
Would it be possible to batch update the peering lan prefix for /ix/474 ?

### ISSUE THREAD

**Issue by netravnen** [peeringdb/peeringdb#231]
https://peeringdb.com/ix/474 have changed their peering lan prefix from 91.212.9.0/24 to 89.46.144.0/21

They have mapped over all the old ip's in the three leftmost octets. (i.e. the rightmost octet have not changed).

Ticket is https://peeringdb.deskpro.com/agent/#t.o:11716

They request if it is possible for PDB to do the batch update.

**Comment by arnoldnipper** [comment]
See https://github.com/peeringdb/admincom/issues/59
