### ISSUE TITLE
Current IXF member list import rules

### ISSUE THREAD

**Issue by grizz** [peeringdb/peeringdb#237]
## Import rules

Default setting just decides if networks have to opt in or opt out.

`allow_ixp_update`: no

- If a network has an IX entry with both invalid IP addresses, the network IX entry is removed
- If a network has an IX entry with any other invalid information (route server peer and speed), nothing is done
- If a network does not have an entry for the IX, nothing is done

`allow_ixp_update`: yes

- If a network has an IX entry with any invalid information, the entry is updated
- If a network does not have an entry for the IX, one is added
- If a network does not have an entry in the IX member list, the network IX entry is removed

*only IP addresses within the IX prefix sets are added*

## AC Tools

All changes made by the importer are logged to the control panel, available to the AC, and able to be rolled back with a single click.

*full documentation was provided to the AC 2017-11-01*

**Comment by arnoldnipper** [comment]
What is the default setting for allow_ixp_update?

**Comment by ccaputo** [comment]
Is "state = active" in the JSON connection_list being required?  I'm pondering how participants that are on hiatus are handled.

Is it expected that they will lose their PeeringDB listing in the IXP list when on hiatus, if marked "state = inactive".  And then when they return to active state, they will either need allow_ix_update set to yes for an automatic update, or they will need to do a manual update?

**Comment by vegu** [comment]
> Is it expected that they will lose their PeeringDB listing in the IXP list when on hiatus, if marked "state = inactive". And then when they return to active state, they will either need allow_ix_update set to yes for an automatic update, or they will need to do a manual update?

Correct.

Note: If a state is not set at all, it will be seen as active by default. **If state is set** the importer accepts either "active" or "connected" to qualify the entry for import.

**Comment by arnoldnipper** [comment]
allow_ixp_update: no && If a network has an IX entry with both invalid IP addresses, the network IX entry is removed

Q: @vegu  Do **both** IP addresses have to be invalid for the network entry to be removed?

**Comment by bijals** [comment]
Will the network be notified that their incorrect entry has been removed?

**Comment by vegu** [comment]
> Q: @vegu Do both IP addresses have to be invalid for the network entry to be removed?

@arnoldnipper yes

> Will the network be notified that their incorrect entry has been removed?

@bijals no

**Comment by bijals** [comment]
I think it would be good for the network to be notified if their data is changed/removed.  If I was a network and my data in the database was being changed, i would want to know. 
What do others think?

**Comment by arnoldnipper** [comment]
> I think it would be good for the network to be notified if their data is changed/removed. If I was a
> network and my data in the database was being changed, i would want to know.
> What do others think?

From what I see almost 100% of incorrect entries came from networks who went out of business. Mailing them would not be very useful

**Comment by arnoldnipper** [comment]
>> Q: @vegu Do both IP addresses have to be invalid for the network entry to be removed?
>
> @arnoldnipper yes

@vegu What is the reason behind it? My understanding is, that any false information should be removed. So I would already remove the entry if either address is wrong.

**Comment by vegu** [comment]
@arnoldnipper since the ip addresses are what is being used to identify netixlans from ixf data, if one is found the other one can usually be corrected to the correct value, which seemed the reasonable approach to this during implementation, but maybe just dropping it makes more sense?

**Comment by arnoldnipper** [comment]
@vegu for me a logical AND would make more sense: i.e. the entry is valid iff IPv4 address is valid AND IPv6 address is valid

**Comment by arnoldnipper** [comment]
New rules in #474

**Comment by arnoldnipper** [comment]
There will be a new importer soon
