### ISSUE TITLE
It's possible to enter the same IP address twice (duplicate IP addresses)

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/peeringdb#241]
It's still possible to enter the same IP address twice (duplicate IP addresses)
![20171115 peeringdb 00](https://user-images.githubusercontent.com/16888757/32837264-24374d32-ca0d-11e7-84c0-518bcb974689.png)

**Comment by vegu** [comment]
interesting i wonder how that slipped through, i will investigate shortly, the /api and public facing user forms should all validate against that, might be that the /cp does not.

Also #90 has not been implemented yet, but is scheduled for 2.7.0.

**Comment by mcmanuss8** [comment]
#90 is resolved - is this still reproducible?

**Comment by vegu** [comment]
@mcmanuss8 #90 was closed as the issue is now tracked in #268 in a more general ticket about unique db constraints - not resolved yet

**Comment by arnoldnipper** [comment]
handled in #268
