### ISSUE TITLE
Login from logout page results in immediate logout

### ISSUE THREAD

**Issue by ccaputo** [peeringdb/peeringdb#242]
If you logout you are taken to:

  https://www.peeringdb.com/logout

If you click Login on that page and do so, you are logged out again since the URL is:

  https://www.peeringdb.com/login?next=/logout

Thus clicking Login from the logout page should probably redirect to the home page, ie:

  https://www.peeringdb.com/login?next=/

**Comment by vegu** [comment]
fixed in 15126f9
