### ISSUE TITLE
IXF should be IX-F

### ISSUE THREAD

**Issue by ccaputo** [peeringdb/peeringdb#246]
At http://www.ix-f.net/ the acronym has a dash: "IX-F"

**Comment by ccaputo** [comment]
This is visible in the edit tip for where you enter the JSON URL.  Maybe elsewhere.

**Comment by mcmanuss8** [comment]
+1 
@peeringdb/pc let's decide if this should happen

**Comment by arnoldnipper** [comment]
I consider this a bug --> 3a

**Comment by vegu** [comment]
**summary**

- find any remaining occurances of "IXF" in labels / descriptions / texts and change to "IX-F"

**Comment by arnoldnipper** [comment]
**Release Notes**
fix spelling
