### ISSUE TITLE
Add operation to API to look for covering prefixes given an IP

### ISSUE THREAD

**Issue by grizz** [peeringdb/peeringdb#25]
While testing the REST API to lookup if a given IP address belongs to an IX in the PeeringDB database, I came up with the less than ideal solution:

For address 206.223.118.117 search as

https://beta.peeringdb.com/api/ixpfx?prefix__startswith=206.223.118

Will return a prefix and a ixlan_id that can be used to query up to the organization.

But if the prefix is not aligned with the octet (v4) or nibble (v6), the solution doesn't work. 
Have you considered an special lookup for find matching network? The
simplest option is "find a prefix that covers this address", although
the generic option is "find a prefix that covers this prefix", and then addresses can be search as 'x.x.x.x/32' or 'dead::beef/128'

If the backend code is available somewhere, I'll be happy to provide a patch.

Moved from peeringdb/docs/issues/61

**Comment by arnoldnipper** [comment]
+1 and I like this idea. @peeringdb/pc what do you think?

**Comment by shane-kerr** [comment]
Maybe we should just return an error in this case? I worry that trying to come up with a correct match is likely to hide bugs from people using the API.

**Comment by arnoldnipper** [comment]
> Maybe we should just return an error in this case? I worry that trying to come up with a correct match is likely to hide bugs from people using the API.

@shane-kerr I don't understand your comment.  My understanding is that @grizz is looking for something like

 https://peeringdb.com/api/ixpfx?whereis=206.223.118.117

This would return the covering ixpfx in case there is one. And nothing otherwise.

**Comment by shane-kerr** [comment]
Oh I see, that seems reasonable.

Is there any chance of overlapping prefixes, or anycast prefixes? That is, can you return more than one ixpfx reference?

**Comment by arnoldnipper** [comment]
> Is there any chance of overlapping prefixes, or anycast prefixes? That is, can you return more than one ixpfx reference?

No and no. And even if. Would that do harm?

**Comment by shane-kerr** [comment]
No harm, just impacts the possible return values from the call.

**Comment by shane-kerr** [comment]
+1

**Comment by grizz** [comment]
Prefix validation checks for overlapping prefixes, so that should never be possible.

Still +1 from me, years later :)

**Comment by mcmanuss8** [comment]
+1
Let's make sure this is clearly documented in the API though. Similar to #608 I want to make sure cool features like this are more easily found.

**Comment by grizz** [comment]
@peeringdb/pc Just wanted to double check quick, does using @arnoldnipper's suggested endpoint of `/api/ixpfx?whereis=206.223.118.117` work for everyone?

**Comment by mcmanuss8** [comment]
This works for me, provided we make it discoverable as I highlighted above

**Comment by grizz** [comment]
Sure, we might have to do #626 first, not worth spending a lot of time on the docs since they need to get replaced.
