### ISSUE TITLE
Limit number of concurrent affiliation requests per user

### ISSUE THREAD

**Issue by vegu** [peeringdb/peeringdb#251]
To counteract spam of affiliation requests. Need to discuss what would be a good limit though.

**Comment by eloos** [comment]
pending affiliation requests should then time out, is that the case?

**Comment by vegu** [comment]
Could either time them out or provide the user with an interface to cancel them.

Either way the current display would need to be changed to show all the pending requests, currently only the most recently created pending request is shown to the user.

**Comment by arnoldnipper** [comment]
Limiting to 10 seems a rasonable number imho. And let the user actively manage his pending requests. It would also help to give an immediate feedback to who the request is sent. From experience I often see that users are waiting for weeks only to find out that the admin has left

**Comment by eloos** [comment]
@vegu how does this relate to #67? Where did you get the trigger for this activation spam from? On #67 the amount of complaints was relatively low, 2-3

**Comment by vegu** [comment]
Not related to #67 at all, this concerns the admincom having to deal with a user submitting 100+ bogus affiliation requests to unowned / non-existant organizations. 

As far as i am aware this has only happened once at this point, but it slowed down the user's admin page significantly, and should be dealt with in some way or another.

Limiting the amount of affiliation requests a user can have actively pending seemed to be a reasonable way to go about it.

**Comment by grizz** [comment]
@peeringdb/pc This seems like a good idea to do, but probably lower on the priority list than a lot of other things. Thoughts?

**Comment by arnoldnipper** [comment]
Has not happened recently. So +1 for lower priority

**Comment by job** [comment]
> Limiting the amount of affiliation requests a user can have actively pending seemed to be a reasonable way to go about it.

I like this idea. +1

**Comment by grizz** [comment]
In case it wasn't clear, +1 from me

Going to say 5 as a good start.

**Comment by vegu** [comment]
@arnoldnipper @peeringdb/ac 

> And let the user actively manage his pending requests.

To confirm, as part of this we will allow users to cancel their pending affiliation requests.

![Screenshot 2020-04-01 at 16 23 47](https://user-images.githubusercontent.com/143124/78143672-40f45880-7437-11ea-844f-cc3b6c599db4.png)


At this point we have disabled this `cancel` function for affiliation requests that are pending admincom review/processing (eg. ownership requests) as that comes with some implications not covered in this ticket such as how this would disrupt the ac workflow for these requests and how to sync such status changes to deskpro.

@ccaputo @ghankins any input on the colors for those notification messages?

**Comment by ccaputo** [comment]
> @ccaputo @ghankins any input on the colors for those notification messages?

No idea.  :-)

**Comment by ghankins** [comment]
> @ccaputo @ghankins any input on the colors for those notification messages?

Red seems fine.

**Comment by grizz** [comment]
**Release Summary**

In order to reduce organization affiliation request spamming, the number of pending organization requests has been limited to 5.
