### ISSUE TITLE
Add harakiri option to uwsgi config

### ISSUE THREAD

**Issue by vegu** [peeringdb/peeringdb#252]
This is so that if a request hangs one of the uwsgi processes for whatever reason it will restart itself after x seconds. I think 25 seconds would be reasonable.

**Comment by vegu** [comment]
fixed in e2381d56

**Comment by ccaputo** [comment]
This has been increased from 25 to 60 seconds based on user experience with the query: https://peeringdb.com/api/net?ix=18&depth=2
