### ISSUE TITLE
When user is clicking "Request Ownership" add URL

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/peeringdb#253]
* add logged in user URL, like https://peeringdb.com/cp/peeringdb_server/user/1590

* add triggering URL

That would help admins to identify what kind of request it is

**Comment by mcmanuss8** [comment]
I'm not familiar with this flow. Is this an email that gets triggered to AC when a user clicks "Request Ownership"? If so, +1 that would be great to add to help AC out

**Comment by arnoldnipper** [comment]
Woow ... that's a really old issue. Meanwhile, handling of requests has improved. I'll check with @peeringdb/ac but I guess we can safely close this issue

**Comment by arnoldnipper** [comment]
Not longer relevant
