### ISSUE TITLE
Create a small test database

### ISSUE THREAD

**Issue by grizz** [peeringdb/peeringdb#256]
Should have a record or two for every combination of data type.

Would be very useful for testing client sync features (full sync tests typically take around [20m](https://travis-ci.org/peeringdb/django-peeringdb)), things inside PDB, as well as any third party applications using PDB.

Could even pull a full instance of PDB up at `test.peeringdb.com` or something.

**Comment by eloos** [comment]
@grizz how about factoryboy? http://factoryboy.readthedocs.io/en/latest/

**Comment by grizz** [comment]
@eloos From glancing at that, I'm not sure what benefit it would add, but either way we need to create the test data. Marking this as my PC Candidate, I've wished we've had it many times.

**Comment by vegu** [comment]
Command to generate test data has been added in cb67cd8

It seemed the most sensible way to do this as schema changes will require us to regenerate data in the future.

So if we do end up running a separate instance of peeringdb at test.peeringdb.com can run the command there directly to populate with test data.

Alternatively could also run the command on a fresh dev instance and then export the database.
