### ISSUE TITLE
GDPR review for PeeringDB

### ISSUE THREAD

**Issue by mahtin** [peeringdb/peeringdb#257]
Don't shoot the messenger; however, I'm going to add "GDPR review" to the PeeringDB issues list. While I could reference many many EU documents; I'll just use this [article](https://medium.com/speech-privacy/should-my-company-worry-about-gdpr-b8ef778f7515).

> If your company is or soon will be processing personal information of EU citizens — no matter where your company is in the world — then the short answer is YES. You will be required to comply with the General Data Protection Regulation.

**Comment by eloos** [comment]
@mahtin this needs to be evaluated and I have asked the PeeringDB stewards for guidance.

**Comment by eloos** [comment]
Bijal & Chris are evaluating the compliance of PeeringDB with GDPR

**Comment by grizz** [comment]
@bijals @ccaputo any update on this?

**Comment by ccaputo** [comment]
I'm not on this.

**Comment by bijals** [comment]
Documentation sent to Aaron during the APRICOT meeting, I'll follow-up.

**Comment by arnoldnipper** [comment]
@eloos ... may be closed now. Or?

**Comment by grizz** [comment]
@arnoldnipper I haven't been paying close attention, but I don't believe we have received any updates for it, let's leave it open until changes are deployed.

**Comment by grizz** [comment]
Looks like everything is deployed, @peeringdb/pc please reopen if I'm mistaken.
