### ISSUE TITLE
Support for multiple IRR records, identify source

### ISSUE THREAD

**Issue by grizz** [peeringdb/peeringdb#26]
The current database only has one field for a single IRR record, and many networks have multiple, for example separate for IPv4 and IPv6, or different IRR record for customers/peers/regions etc.

The source of the IRR record is not identified - is it in RIPE, RADB, ALTDB etc?

Is there any intention to allow multiple? What seems to happen now is that the field can contain multiple IRR records in a variety of interesting ways, and parsing this is of course a pain.

Moved from peeringdb/docs/issues/56

**Comment by robertjakub** [comment]
some networks make a IRR::ASMacro entry (e.g.: RIPE::AS-Something) for the identifying the right IRR to resolve/expand the record. maybe we need an another field "IRR source" (and make it an table/array of the records with the source:macro:descriptions field)?

**Comment by grizz** [comment]
I think we should turn this into a set, and validate that a source is set in the string. The existing field can remain the same, and be populated from the set as a space delimited list.

**Comment by pierky** [comment]
Maybe it could be worth to link this issue to #151 too.

**Comment by eloos** [comment]
@grizz can you elaborate on what we still need to decide on? I think all the initiaties regarding the IRR record have been referenced now and seem to be coherent (i.e. multiple entries, comma/white space delimited, both formats SOURCE::AS-SET/AS-SET@SOURCE and allowing multiple hiearchies in AS-SET with a colon?) what more is needed to quote and link these issues in an EPIC?

**Comment by grizz** [comment]
@eloos it already is an Epic, #201 

I think in order to proceed, we need to define the following:

- All valid AS-SET values #151 
- If we want to make this an actual set in the backend, or just have it whitespace delimited

I haven't completely gone over all the tickets yet, so I might be missing a few things

**Comment by robertjakub** [comment]
@grizz I think we also add one thing to the discussion: 
the possiblity to specify the version of IP protocol related to the AS-SET; operators often create different AS-SET for the IPv6 filters (like Hurricane, AS-HURRICANE and AS-HURRICANEv6).

**Comment by as44980** [comment]
Should we consider if there are any network who may wish to indicate a unique as-set per IX?

**Comment by arnoldnipper** [comment]
According to discussions in #151 we have not only take into account multiple values, but also

 * address familiy

 * where to apply the policy (net, ix)

**Comment by grizz** [comment]
From the discussion on #151, I think is solved pending #151 getting completed.

**Comment by devicenull** [comment]
I think this is slightly different then #151.  We just hit a case recently where for https://www.peeringdb.com/net/2496 you get radically different results if you use RADB there vs RIPE (due to AS-CN having different definitions).  Would a field listing what IRR databases to use make sense?

**Comment by job** [comment]
I dont believe we need a separate field for the SOURCE, we can adhere to the industry standard as per https://github.com/peeringdb/peeringdb/issues/151#issuecomment-387839904

**Comment by devicenull** [comment]
How would you support multiple sources?  In this case, they've told me they use the RIPE and APNIC databases.  Only using RIPE results in an incomplete prefix list:

```
irr_databases RIPE,APNIC
Aggregated 423 IPv4 prefixes down to 192
Aggregated 87 IPv6 prefixes down to 65

irr_databases RIPE
Aggregated 402 IPv4 prefixes down to 179
Aggregated 81 IPv6 prefixes down to 60
```

**Comment by job** [comment]
ah, the source in this context is merely the source of the `AS-SET` object itself, we don't have support to specify what other databases should be considered when expanding an AS-SET. There is no industry standard for such syntax. RPSL is an incomplete solution, I don't think peeringdb is able to resolve /that/ specific issue
