### ISSUE TITLE
IRR Record on website vs. irr_as_set

### ISSUE THREAD

**Issue by mahtin** [peeringdb/peeringdb#260]
When looking at a network on PeeringDB a networks ``as-set`` is listed on the website as **IRR Record** however it's in the API it's values is called **irr_as_set**. For example:

```
IRR Record         AS-MUMBLE
```

```
"irr_as_set": "AS-MUMBLE",
```
This is inconsistent and the website should change it's label text to **IRR as-set name** for example.

**Comment by andydavidson** [comment]
Agree!

**Comment by job** [comment]
Actually a route-set is also valid here, or an autnum .. so "IRR as-set name" is not entirely correct

**Comment by arnoldnipper** [comment]
What would be a good name, @job ?

**Comment by job** [comment]
Rename `irr_as_set` to `irr_record` .. or leave it be :)

**Comment by grizz** [comment]
Renaming a field would require bumping to version 3, so I'd vote to leave as is for now, but this requires a PC decision

**Comment by mahtin** [comment]
I never said rename the field in the API. I said: change the website’s label text. I don’t want to see the API change!

**Comment by grizz** [comment]
Oh, I have to read the whole ticket? :)

I'm good with changing the label text.

**Comment by job** [comment]
Change it to what? "IRR AS-SET" would be incorrect, as you can also put
a route-set there, or an autnum.

**Comment by mahtin** [comment]
Cool. Let’s say all of that!

**Comment by job** [comment]
On Tue, Jan 09, 2018 at 06:48:29PM +0000, Martin J. Levy wrote:
> Cool. Let’s say all of that! 

"IRR Record" covered all of them, but maybe is vague to some folks.

Would "IRR As-set/Route-set/Autnum" be better? I'm not sure whether that
fits well in te current web layout.

**Comment by mahtin** [comment]
> Would "IRR As-set/Route-set/Autnum" be better? I'm not sure whether that
> fits well in te current web layout.

1. If the text doesn't fit; then why can't we use some form of popup/info button. That could be useful for many items around the PDB world.
2. If the text fits; then we are done.
3. Why is "Autnum" being discussed or proposed. There's an ASN field (which for the purposes of as-set/route-set would be included by default (and if it's not - then huh?).

**Comment by job** [comment]
Indeed, autnum can be dropped. So we arrive at the following: "IRR
as-set/route-set"

ok?

**Comment by eloos** [comment]
@job +1

**Comment by mahtin** [comment]
@job +1

**Comment by arnoldnipper** [comment]
@job +1
