### ISSUE TITLE
put URL to privacy policy on https://peeringdb.com 's footer

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/peeringdb#261]
@ccaputo said in Message-ID: <alpine.LNX.2.21.9.1712191726300.6121@nacho.alt.net>
: I am concerned that while the AUP is easy to find from any peeringdb.com 
page, the Privacy Policy is pretty buried: peeringdb.com -> Documentation 
-> Governance tab -> Policies

**Comment by vegu** [comment]
added link in 2465a58

we put it under "Resources" - another possible spot i could think of would be next to the version

please advise if you have a specific spot in the footer in mind for this to be added

**Comment by arnoldnipper** [comment]
Next to the version does make more sense to me

**Comment by vegu** [comment]
moved next to version in b4cc2a8
