### ISSUE TITLE
Move whois service to whois.peeringdb.com

### ISSUE THREAD

**Issue by job** [peeringdb/peeringdb#263]
We currently operate a WHOIS RFC3912-ish service on port 43 on peeringdb.{com/org/net} and *.peeringdb.{com/org/net}. By having the whois service on the same domain names as the HTTPS services, we hinder improvements on the HTTPS service.

I propose that the WHOIS service is moved to `whois.peeringdb.com` which shall be the canonical name for the whois service. 

The old whois service on *.peeringdb.com and peeringdb.com should be updated and show as preamble & postamble to the whois output something like:

> % Per X/Y/2018 the whois service will only be available at whois.peeringdb.com

Then, after 4 to 6 weeks, the whois service on *.peeringdb.com and peeringdb.com can be turned off.

**Comment by eloos** [comment]
@job have we checked whether typical whois clients support the DNS SRV record? Would that be an option?

**Comment by job** [comment]
we can set a dns srv record _in addition_ to migrating the service, but I
wouldn’t count on wide support in whois clients.

**Comment by job** [comment]
I consulted dns experts, and Whois dns srv records are not a thing. I
checked some open source Whois clients and didn’t see support for srv
records. So, dns srv doesn’t seem to offer any advantage here

**Comment by eloos** [comment]
@job so from a functionality point of view nothing changes? This is about hosting the existing code under a different domain, correct?

**Comment by job** [comment]
indeed

**Comment by job** [comment]
To make it easier for PeeringDB to distribute itself across a CDN or multi-country architecture, we need to move`whois` to its own FQDN.

Let's do a vote, pick 1 or 2.

1) make it so that `whois` is only available at `whois.peeringdb.com`
2) leave things as they are (`whois` works against `*.peeringdb.com` and `peeringdb.com`)

**Comment by job** [comment]
i vote 1

**Comment by job** [comment]
small note: PDB OPS will execute this work.

**Comment by nopedial** [comment]
I vote option 1 as well

**Comment by ccaputo** [comment]
Per http://lists.peeringdb.com/pipermail/pdb-announce/2018-November/000113.html the whois service is now only accessible via "whois.peeringdb.com".  Example:

  whois -h whois.peeringdb.com as1
