### ISSUE TITLE
remove users with same email address

### ISSUE THREAD

**Issue by grizz** [peeringdb/peeringdb#267]
Split from #42 -- depends on #266 for API keys

Timeline from @daydr3am3r's comment

1. Implement API keys with distinct permissions functionality. The API keys could be generated by the users, similarly to what other websites offer.
2. Set and announce a flag day to all PDB users, as to configure API keys under their "primary" accounts and delete users used for API-like functionality. 
3. Provide ample reminders until materialization of the flag day.
4. On flag day, proceed to disable all accounts not having completed step 2, telling them to contact PDB support@ as to proceed with 2. before having their account re-activated.
5. For any accounts having done 2., also consolidate usernames with email addresses as @arnoldnipper suggests. Explain this change as part of 2.
6. After a period of time (say, a year after the flag day) remove all usernames/accounts not having done 

my comment from #42 about merging:

> Migration process is spot on, give them plenty of time to merge. I'd probably be in favor of automatically merging at the end, but I can see the benefits of just disabling them.

**Comment by arnoldnipper** [comment]
@peeringdb/pc please +1 if you agree with what @grizz proposes

**Comment by arnoldnipper** [comment]
+1

**Comment by shane-kerr** [comment]
+1

Makes sense, as it avoids confusion on our side about who the real user@domain.net. :joy:

**Comment by mcmanuss8** [comment]
+1

**Comment by grizz** [comment]
Moving to Implementation discussion, since it currently relies on #266

**Comment by leovegoda** [comment]
As we get ready for #266 to be deployed, what timeline do we want to work with on this?

**Comment by arnoldnipper** [comment]
> As we get ready for #266 to be deployed, what timeline do we want to work with on this?

We will have to notify the users and remind them at least once. Hence, the earliest date would be 2021-04-16 COB IMO when we start **now**

**Comment by martinhannigan** [comment]
Mea cupla. For some reason I thought we did have Peering. ACK on the tool
tip.
