### ISSUE TITLE
Database: unique constraints

### ISSUE THREAD

**Issue by vegu** [peeringdb/peeringdb#268]
While looking into #90 it became evident that doing any such changes to the database breaks peeringdb-py client sync, and as such need to wait for client refactor to be completed. 

In the meantime unique constraints are handled by data validation, but once these requirements are satisfied they should be added as constraints at the database level as well.

- NetworkIXLan.ipaddr4
- NetworkIXLan.ipaddr6

_List may be added to in the future_

While some of this issue is already tracked in #90, we thought it would also make sense to make a a more general ticket for this, in case we find other fields that need to be made unique on a database level.

**Comment by grizz** [comment]
+1

This was already approved as part of the backlog, but for the new approval process, we need 2 more votes please @peeringdb/pc

**Comment by arnoldnipper** [comment]
+1

**Comment by mcmanuss8** [comment]
+1

**Comment by shane-kerr** [comment]
+1

**Comment by arnoldnipper** [comment]
@peeringdb/pc please +1 this is really crucial for a DB

**Comment by vegu** [comment]
Some notes on implementation as i estimate this:

Currently there are a bunch of deleted netixlans lying around with duplicate ips and we will need a migration to clean those up as part of this.

The new client should be ready to handle this change now as well, but will likely need it's own similar migration in django-peeringdb.

**Comment by arnoldnipper** [comment]
@vegu: I noticed this when using /cp. Is there anything to do for @peeringdb/ac?

**Comment by vegu** [comment]
@arnoldnipper for the deleted ones i think we will just null their ipaddress fields during the migrations.

There are however currently 12 or so with status `ok` [0] that need to be cleaned up as well, i haven't checked whether it's feasible to fix those during a migration, but since its not that many, maybe that's something the @peeringdb/ac can look into. 

0: https://www.peeringdb.com/cp/peeringdb_server/duplicateipnetworkixlan/

**Comment by arnoldnipper** [comment]
I'll take care of it, @vegu 

- [ ] @arnoldnipper to clean up [duplicate IPs](https://www.peeringdb.com/cp/peeringdb_server/duplicateipnetworkixlan/)

**Comment by koalafil** [comment]
@arnoldnipper Release Notes pls

**Comment by arnoldnipper** [comment]
**Release Notes**
This issue fixes internal DB behaviour.
