### ISSUE TITLE
Sanitize IX Peering Lan Prefix length

### ISSUE THREAD

**Issue by job** [peeringdb/peeringdb#269]
Slightly related to the `/3` bug in `ipaddress` - IXP Peering LAN prefixes in practise will never have a length shorter than `/18` for IPv4 and `/64` for IPv6.

If a peering lan prefix is entered where the prefix length is /17 (ipv4) or /63 (ipv6) the PDB sofware should throw an error.

**Comment by mahtin** [comment]
Sadly this isn’t 100% correct. Technically there’s difference between v4 & v6 with this issue.

In v4 world, there’s a practical/financial limit but there’s nothing technically stopping a /16 LAN for example. It’s insane, but not technically incorrect. PeeringDB should stick to technical issues. 

In v6 world we all know /64 is it. Period. Except early HKIX days proved otherwise. I’m glad those days are past us. However we see plenty of new IXs input foo/48 (their RIR allocation). I’d be happier with some form of notice towards the user that common practice is /64.

**Comment by job** [comment]
@mahtin if an IXP comes along with an IPv4 /16 peering lan; we'd just raise the limit. This isn't meant to impose anything religious, but just to protect against common typos. We have something similar for maximum prefix limits.

New IXPs should not input their IPv6 RIR allocation as peering lan prefix. That is a misconfiguration and bad data leads to bad automation. So again if an error is generated if the inputted prefix is shorter than /64 that is beneficial to the users.

**Comment by arnoldnipper** [comment]
Throwing an error means a hard limit. Why not simply popping up a notice as @mahtin suggests, @job . Both for IPv4 and IPv6. And if they still enter the value shoot an email to support as well

**Comment by job** [comment]
Yes, a hard limit. A simple email to support@peeringdb.com to resolve
it.

Who benefits if an IXP configures an IPv4 `/2` peering lan prefix?

There is absolutely no issue to having hard limits that can be modified
by contacting PeeringDB - in fact, the most likely future is that when
we see large IXPs grow to the point of `/16s` we as PDB volunteers
notice this industry development and up the limit proactively.

Show me an IXP that is anywhere close to the proposed limits to justify
not implementing hard limits.

I'll repeat myself: we have a similar mechanism for maximum prefix
values, why is the same user data entry protection mechanism not an
issue there?

**Comment by grizz** [comment]
+1 on hard limits, they're easy to override by AC if need be.

I honestly think we should go a step further and say any IX LAN prefix needs AC verification -- new IXes and prefix changes happen so infrequently, it's little workload so let's make sure they make sense. If a new IX owns a /14 or /48 and wants to use it, let's explain why it's a bad idea before caving in and approving it.

**Comment by arnoldnipper** [comment]
Ok with me

**Comment by grizz** [comment]
@peeringdb/pc This looks like it passes (even tho it only has a few votes). I think we should go ahead with /17 and /63.

**Comment by job** [comment]
/64 makes more sense for v6

/17 for ipv4 is good enough

**Comment by arnoldnipper** [comment]
/64 and /17|/18 is fine for me

**Comment by job** [comment]
where are we on this one?

**Comment by arnoldnipper** [comment]
> where are we on this one?

We still have to reach consensus. As soon as we are there, AC is happy to sanitize, i.e. talk to IXes with non-standard masks.

IPv4 pretty much looks ok. The 4 /32 are insane of course

curl -sG https://peeringdb.com/api/ixpfx --data-urlencode protocol=IPv4 --data-urlencode fields=prefix | jq -c '.data[].prefix' | sed 's?.*/??;s?.$??' | sort -n | uniq -c | sort -k2n
      2 20
      8 21
     24 22
     74 23
    530 24
     33 25
     29 26
     11 27
      1 28
      4 32

With IPv6 there is more to do

curl -sG https://peeringdb.com/api/ixpfx --data-urlencode protocol=IPv6 --data-urlencode fields=prefix | jq -c '.data[].prefix' | sed 's?.*/??;s?.$??' | sort -n | uniq -c | sort -k2n
      6 32
     65 48
      3 50
      1 52
    486 64
      2 96
      1 111
      2 112
      2 116

**Comment by mahtin** [comment]
@arnoldnipper - those are some damn ugly numbers!

**Comment by grizz** [comment]
I'm going to put this in the queue for one of the April minor issues then, so speak now if anyone disagrees. :)

We can have config specified values for min and max prefix lengths, and if anyone edits a record it will force them to fix it.

After that, the AC can work to clean up records at will.

**Comment by arnoldnipper** [comment]
> I'm going to put this in the queue for one of the April minor issues then, so speak now if anyone disagrees. :)

@grizz would you mind to specify min/max length for ipv4/6?

IPv4 longs pretty ok now: 20 <= length <= 28; proposal: 18 <= length <= 28

IPv6 still looks weird: 32 <= length <= 116; propsal: 64 <= length <= 116(???)
