### ISSUE TITLE
add better max prefix support

### ISSUE THREAD

**Issue by grizz** [peeringdb/peeringdb#27]
See discussion at peeringdb/docs/issues/38

**Comment by job** [comment]
we should ask the community what their interpretation of max_prefix values is: is it what you actually announce (in general) or what you recommend others to set as max_prefix?

**Comment by grizz** [comment]
Most people I've talked to interpret it as recommended setting, I think this can be closed

**Comment by lukastribus** [comment]
Ok, but is it actually properly documented so that people who do not want to go through closed github issues understand that fact?

**Comment by grizz** [comment]
@lukastribus You're absolutely correct, created #204
