### ISSUE TITLE
Isolate beta / production cookies

### ISSUE THREAD

**Issue by job** [peeringdb/peeringdb#270]
An inherited artifact from PDB 1 is that cookies applied to `*.peeringdb.com` to keep things working if people were using `http://asXXX.peeringdb.com/` - nowadays the `asXXX.` subdomains are a simple 302 redirect to `/asn/XXX` and don't require cookie access.

By isolating the beta / production cookies people won't be logged out when they log in to beta.peeringdb.com and vice versa.

**Comment by mcmanuss8** [comment]
+1 Let's do this as job described

**Comment by arnoldnipper** [comment]
+1 and should long have been done. Wonder why it never made it to the sprint, @eloos

**Comment by grizz** [comment]
+1

**Comment by ShawnaBong** [comment]
Done
