### ISSUE TITLE
Merge tool for Facilities

### ISSUE THREAD

**Issue by grizz** [peeringdb/peeringdb#271]
There is already a merge tool for organisations. Every now and then there is also a request for merging facilities like

https://www.peeringdb.com/fac/2 (original Digital Realty)
https://www.peeringdb.com/fac/447 (original Telx)

An AC usable GUI in addition to the command line tool would be useful

**Comment by eloos** [comment]
@grizz what needs to be reviewed?

**Comment by vegu** [comment]
@eloos I am not sure there is much to review - the CLI for this already exists, this ticket describes the implementation of a UI that wraps around said CLI so AdminCom can do the process themselves.

Requests for facility merges seem to have increased in the recent months, (used to be 1 or 2 a month, now it's 5+) so AC would benefit from being able to do it themselves. I went ahead and estimated the ticket.

**Comment by arnoldnipper** [comment]
@vegu I don't see an estimate ...

**Comment by grizz** [comment]
@arnoldnipper the "major" tag is the estimate, assuming you want it to work the same as the other merge tools, if not, please spec it out.

**Comment by arnoldnipper** [comment]
@grizz , I guess we will need a quote for that as this work is not covered by the maintenance contract and is also orthogonal to any other work (i.e. there are no synergies with other work to be done). Could you hence please send a quote. Merci :)

**Comment by arnoldnipper** [comment]
Of course it will have the possibility to undo the merge. The same way as we already have for merging organisations or renumbering IXes

@grizz  ... quote is still missing :)

**Comment by grizz** [comment]
The "Major" tag is the quote :)

**Comment by arnoldnipper** [comment]
Come one, @grizz ... please provide a real quote to me, please. TIA

**Comment by vegu** [comment]
implemented in a2ad7e4c
