### ISSUE TITLE
modify updated field for some org objects

### ISSUE THREAD

**Issue by mahtin** [peeringdb/peeringdb#273]
A lot of the new ```org`` objects were created in March/2016 as part of the data migration process. This can be seen here:
```
$ curl -sS 'https://peeringdb.com/api/org?depth=0' | jq . | egrep updated | sed -e 's/T..:..:..Z//' | sort | uniq -c | head
   1       "updated": "2011-02-22",
   1       "updated": "2015-11-11",
   1       "updated": "2016-02-24",
 202       "updated": "2016-03-11",
5000       "updated": "2016-03-14",
 108       "updated": "2016-03-15",
  27       "updated": "2016-03-16",
  16       "updated": "2016-03-17",
   4       "updated": "2016-03-18",
   2       "updated": "2016-03-19",
$
```
It is my proposal that these ``updated`` dates be modified to match their ``created`` dates. A quick check of the data shows that for any ``org`` record that's got an ``updated`` value of ``2016-03-14`` or earlier, the ``created`` value should be copied into ``updated``.  Someone should double-check that.

I believe this will improve the value of ``org`` data.

**Comment by arnoldnipper** [comment]
I can't see how this makes it better as it does not add any information

**Comment by mahtin** [comment]
@arnoldnipper - it corrects data that was created somewhat abstractly (and not by the holder of the record).

If nothing else, PeeringDB is all about holding accurate data for the use of it's end-users. If we are going to have ``created`` and ``updated`` columns in these tables; then lets strive to keep them correct.

**Comment by arnoldnipper** [comment]
Setting the 'updated' date to the 'created' date does in no way increase accuracy. Otoh data for org were changed when we migrated to PDB2.0. Hence the update date correctly reflects this

**Comment by arnoldnipper** [comment]
I'm inclined to close the ticket, @mahtin

**Comment by mahtin** [comment]
@arnoldnipper - I'm not as inclined as you are. I understand your point; however there's a very important issue here. The ``updated`` time does not reflect what the end-user did. It reflects an internal PDB database event (1.0 -> 2.0). That (in my mind) makes the present ``update`` value useless. My proposal will fix that error for those ~5,000 entries.

**Comment by arnoldnipper** [comment]
@mahtin, setting the `updated` to `created` doesn't fix anythink as this date is arbitrary as well. And what if users did the change? And who says that the `updated` field only reflects changes made by the user? When we introduced coordinates lot of facility data also was updated. 

Again: your proposal changes ~5,000 entries, but doesn't fix anything.

**Comment by grizz** [comment]
I believe some of those were entries with null dates or old records imported from Caida -- I'm fine with updating the dates if we know what happened, but to @arnoldnipper's point, it seems like a huge time sink to go through everything without getting much if any other data (and that field isn't allowed to be null IIRC).

@mahtin Also keep in mind, we did a *lot* of auto updating entries to conform to the new validation, so technically, a large amount were actually updated during the conversion.

**Comment by arnoldnipper** [comment]
@mahtin , please feel free to escalate
