### ISSUE TITLE
Cookie details for GDPR requirements

### ISSUE THREAD

**Issue by bijals** [peeringdb/peeringdb#275]
Hi, I need information on what cookies are used on the website, for each one, the name (e.g. stat-session), the purpose (e.g. These are standard cookies for user identification and session persistence) and term (e.g. Expires after two weeks). Where's the best place to get this information? Thanks!

**Comment by grizz** [comment]
1. __utma
    - google analytics / stats
    - 6 months
2. csrftoken
    - prevent CSRF
    - 1 year
3. sessionid
    - user id / session
    - 2 weeks
