### ISSUE TITLE
Access details for GDPR Requirements

### ISSUE THREAD

**Issue by bijals** [peeringdb/peeringdb#276]
hello again, additionally to the cookie detail I also need to confirm what accesses are available on PeeringDB, I assume:
- Non-registered users 
- Registered users
- Database administrators
Are there any others, if so what and what is the access? (e.g. restricted views) Thanks.

**Comment by grizz** [comment]
This is just for the website, right?

**Comment by bijals** [comment]
yes, for access to the database..

**Comment by grizz** [comment]
Then yes, that's correct
