### ISSUE TITLE
Enforce at least 1 ix_lan, 1 ix_lan_prefix and 1 email address for each new IXP

### ISSUE THREAD

**Issue by martzuk** [peeringdb/peeringdb#277]
In order to turn on IP validation we need to ensure an IXP has a LAN and prefix listed, to prevent new IXPs being created without this information we should enforce at least 1 of each to be added for the IXP to be created.

**Comment by as44980** [comment]
Seems reasonable, would this mean an overhaul for the process to add a new IX whereby it must first be approved before any peering LANs can be added?

**Comment by arnoldnipper** [comment]
@as44980 ... no! It should be required for any new IX that Peering LAN information also is provided in the request. Currently first an IX has to be approved before a Peering LAN can be added.

**Comment by vegu** [comment]
implemented in b35ddd
