### ISSUE TITLE
Users are unable to create new organisations / networks

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/peeringdb#278]
When trying to affiliate to a network / org there is a "500 Internal Server Error"![20180122 PeeringDB 01.png](https://images.zenhubusercontent.com/57929671e40e5714b16c6b73/8fd5cab0-edfb-4dbe-a474-12387b9a9bbc)

**Comment by vegu** [comment]
Looking at this, able to reproduce, will update once i know more.

**Comment by vegu** [comment]
This appears to be an error during the RDAP lookup, it does not happen for all ASNs.

```
    raise RuntimeError("status for {} was {}".format(url, res.status_code))
RuntimeError: status for https://rdap.db.ripe.net/entity/COLO was 500
```

Looks like it's actually a 500 error propagated from `https://rdap.db.ripe.net/entity/COLO`

@grizz, any idea?

**Comment by grizz** [comment]
Yep, it's definitely propagating from RIPE, will report to them and we can correctly wrap that call to create a manual AC ticket in the case of RIR error.

**Comment by grizz** [comment]
Known RIPE bug, referenced in https://github.com/RIPE-NCC/whois/blob/master/README.RDAP.md

**Comment by arnoldnipper** [comment]
Is there any workaround or hotfix available, @vegu / @grizz ?

**Comment by grizz** [comment]
@arnoldnipper not sure exactly what you mean? It's specific to that entity and is a RIPE bug, so the only thing we can do is not 500 to the user and instead create an AC ticket, either way, it needs to be manually added

**Comment by arnoldnipper** [comment]
@grizz not sure I understand what you say. The hotfix you will provide is to not 500 to the user and instead create an AC ticket. From here AC does it the "old way". Right?

**Comment by grizz** [comment]
@arnoldnipper Correct, so for this one, just add the new org for the user, does that work for you?

**Comment by arnoldnipper** [comment]
Adding network and org worked. However when affiliating user to the newly created org I get a 500. See #279

**Comment by grizz** [comment]
@arnoldnipper that was unexpected, thanks, we'll check it out

**Comment by vegu** [comment]
It's because it's just making an affiliation request same as the user-facing form. It's still going to try to get RDAP information for all the networks under the org because the org is (was) unowned.

Manually adding the user to the org admingroup worked as expected.

I took care of this particular instance, and posted a workaround for admincom in #279

**Comment by arnoldnipper** [comment]
It looks like Japanese networks are also affected. See e.g. https://peeringdb.deskpro.com/agent/#app.tickets,inbox:archive_resolved,t.o:14949,vis:6.

@vegu could you pls try to reproduce.

**Comment by arnoldnipper** [comment]
@vegu In case this is happening, please notify AC with ASN and requestor's email as data

**Comment by vegu** [comment]
Similar error spotted in #307 - but not necessarily caused by the same RIPE bug

**Comment by vegu** [comment]
> @vegu In case this is happening, please notify AC with ASN and requestor's email as data

@arnoldnipper we will have it create an AC ticket on most RDAP lookup errors with the **exception** of `400 Bad Request` and `404 Not Found` - as those those are user input errors and i assume AC is not interested in being notified of those, can you confirm?

Thanks

**Comment by arnoldnipper** [comment]
@vegu  ... confirmed
