### ISSUE TITLE
When affiliating a user to an organisation manually I get a 500

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/peeringdb#279]
https://peeringdb.com/cp/peeringdb_server/user/57921/change/

User has to be affiliated to Org "Coloplast A/S"

**Comment by vegu** [comment]
It's the same issue with a 500 Error from RIPE, not entirely sure yet why it would also trigger of the existing org, looking into it.

**Comment by vegu** [comment]
Alright, so i manually added the user to the admin user group of that org. That should take care of this instance.

As to what happened

RDAP information is collected for all networks under the org during an affiliation request. Hence it triggered the error tracked in #278 here as well.

**Work arounds

- affiliate the user to the org before adding the network

or

- add the user to the org's admin group manually (via edit permissions in the user editor)

I think this ticket can be closed, as the proposed fix in #278 will fix this as well.

**Comment by vegu** [comment]
The fix proposed in #278 will fix the ugly 500 error here as well, but maybe we should make it so that if an affiliation request created through the /cp with status "approved" will not trigger any RDAP lookups ?

**Comment by eloos** [comment]
@arnoldnipper can you confirm that the workaround works for AC?

**Comment by arnoldnipper** [comment]
@eloos : confirmed

**Comment by vegu** [comment]
One member of the admincom confirmed that 

> but maybe we should make it so that if an affiliation request created through the /cp with status "approved" will not trigger any RDAP lookups ?

would be a good addition when handling this kind of issue, so lets make it the focus point of this ticket as the other stuff is already covered by #278.
