### ISSUE TITLE
Get by ASN only searches primary ASN

### ISSUE THREAD

**Issue by grizz** [peeringdb/peeringdb#28]
A network that has multiple ASNs isn't returned when requesting non-primary ASN.

For example, APNIC (id=3103) has the primary ASN 4608, but different ASNs at different IXs (for example ASN 18369 at Equinix-Ashburn (fac=1))

`https://beta.peeringdb.com/api/asn/4608` returns APNIC's record, but `https://beta.peeringdb.com/api/asn/18369` does not.

Searching on the web interface yields the same results (specifically, searchers for 18369 returns no results).

Shouldn't a get or search work for all ASNs for a given org?

Moved from peeringdb/docs/issues/35

**Comment by mcmanuss8** [comment]
Not sure this is a problem - it seems to work, provided the organization has separate net entries for each ASN.

Consider:
https://www.peeringdb.com/api/net?asn=7922
https://www.peeringdb.com/api/net?asn=33654
https://www.peeringdb.com/api/net?asn=7725
etc.
