### ISSUE TITLE
Facility submissions getting lost?

### ISSUE THREAD

**Issue by peterhelmenstine** [peeringdb/peeringdb#280]
I submitted a facility "Digital Realty Hong Kong" which is still pending but haven't seen it pop up in Deskpro. E-ail acknowledging and a ticket number should have been sent to phelmenstine@digitalrealty.com but nothing received or in my spam box.

Also noticed there are a few facilities that a in a state of "pending" that I don't see in Deskpro

I see 9 facilities in a pending state since Jan. 19, 2018, 8:08 a.m that I don't see have related Deskpro tickets. Assume e-mails haven't been sent out to those folks acknowledging their request.

Per Job: 
Probably because of SPF
Leave them to me I’ll investigate later today
Maybe the mails got rerouted
Maybe something else is going on

-pete

**Comment by arnoldnipper** [comment]
My impression is that ohtre requests also got lost. However I was to lazy to dig into it.

**Comment by arnoldnipper** [comment]
See DeskPRO 14271, no affiliation ticket can be found

**Comment by eloos** [comment]
@job @arnoldnipper @vegu @grizz whom is the correct person to investigate this?

**Comment by job** [comment]
The problem was identified via email communication. Pdb ops is working on a permanent solution.

**Comment by arnoldnipper** [comment]
@job What was the outcome? And got tickets lost / were not generated?

**Comment by job** [comment]
A hand full of emails was lost due to anti-spoofing measures applied at
the domain names of the peeringdb users. Pete is following up with the
lost emails manually.

**Comment by arnoldnipper** [comment]
Pls bounce the list of dropped emails to AC, @job

**Comment by job** [comment]
I can't do that in this case. The emails weren't misrouted but silently
blackholed

Peter (pete@) has a list of facilities that remained in pending state
without a corresponding deskpro ticket.

**Comment by arnoldnipper** [comment]
There were not only facilities involved, @job

**Comment by job** [comment]
I don't know how to make a list of what is lost arnold. mail logs say the
emails were successfully sent, but AC tells me things didnt show up in
deskpro.

As you saw I've opened a thread to initiate discussion to resolve this type
of problem.

**Comment by arnoldnipper** [comment]
Thanks. Got it, @job. Maybe it's a good idea to go through the ~4k items in https://peeringdb.com/cp/peeringdb_server/verificationqueueitem/ and clean them up ...

**Comment by peterhelmenstine** [comment]
It's happening again. Just submitted a new facility (Digital Realty Atlanta) that's pending and got no response or deskpro ticket. Unsure if it's just me...

**Comment by job** [comment]
On Wed, Feb 14, 2018 at 12:44:36AM -0800, Peter Helmenstine wrote:
> It's happening again. Just submitted a new facility (Digital Realty
> Atlanta) that's pending and got no response or deskpro ticket. Unsure
> if it's just me...

Strange, seems the mail is delivered:

[root@mailer log]# grep -A 2 digitalreal maillog
Feb 14 08:28:14 mailer postfix/qmgr[31074]: 31FEB5C0318: from=<phelmenstine@digitalrealty.com>, size=1828, nrcpt=1 (queue active)
Feb 14 08:28:14 mailer postfix/qmgr[31074]: 31FEB5C0318: from=<phelmenstine@digitalrealty.com>, size=1828, nrcpt=1 (queue active)
Feb 14 08:28:15 mailer postfix/smtp[19826]: 31FEB5C0318: to=<support@peeringdb.com>, relay=aspmx.l.google.com[173.194.175.27]:25, delay=1.1, delays=0.12/0.01/0.66/0.31, dsn=2.0.0, status=sent (250 2.0.0 OK 1518596895 e5si3583789qtd.12 - gsmtp)
Feb 14 08:28:15 mailer postfix/smtp[19826]: 31FEB5C0318: to=<support@peeringdb.com>, relay=aspmx.l.google.com[173.194.175.27]:25, delay=1.1, delays=0.12/0.01/0.66/0.31, dsn=2.0.0, status=sent (250 2.0.0 OK 1518596895 e5si3583789qtd.12 - gsmtp)

**Comment by peterhelmenstine** [comment]
never saw a DeskPro ticket

**Comment by job** [comment]
sorry the only real solution is to insert deskpro tickets via the API
rather than via email. email simply is not reliable

On Wed, Feb 14, 2018 at 5:10 PM, Peter Helmenstine <notifications@github.com

**Comment by arnoldnipper** [comment]
Sorry, email is very reliable. Google is a ... ymmv

**Comment by grizz** [comment]
> Sorry, email is very reliable. Google is a ... ymmv

+1

Agree with @job tho, API is the way to go

**Comment by peterhelmenstine** [comment]
In this case I submitted the facility through the peeringdb website portal "Manage: Add Facility" tab

**Comment by arnoldnipper** [comment]
>> Sorry, email is very reliable. Google is a ... ymmv
>
> +1
>
> Agree with @job tho, API is the way to go

+1 ... pls send a quote to PC asap :)

**Comment by arnoldnipper** [comment]
> In this case I submitted the facility through the peeringdb website portal "Manage: Add Facility" tab
>

I've picked up the request from Verification queue items and approve the site

**Comment by peterhelmenstine** [comment]
Saw that. Thank you. Was going to leave that there until a fix was done as I have a bunch more to submit.

Did you manually create the deskpro ticket?

**Comment by arnoldnipper** [comment]
> Did you manually create the deskpro ticket?

yes, just for documentation
