### ISSUE TITLE
Investigate using DeskPRO's API to create tickets

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/peeringdb#281]
Currently the interface between PDB and the AC ticketing system DeskPPRO (https://peeringdb.deskpro.com/agent) is email. Though reliable dealing with emailk addresses has caused a lot of problems (spoofing, reply-to, spf, ...).

The idea is to use DeskPRO's API (http://api.deskpro.com/) instead. In the first step 20C should investigate whether it's possible to use the API instead of email.

**Comment by vegu** [comment]
I have glanced over their API documentation, we could definitely switch to that. 

It's a RESTful API so in theory it should it be fairly straightforward - assuming their schema documentation holds up.

**Comment by arnoldnipper** [comment]
What else do you need to send PC a quote for the work to be done, @vegu ?

**Comment by vegu** [comment]
@arnoldnipper We have enough information to estimate / quote

**Comment by job** [comment]
By using the deskpro API we can also give immediate feedback to users whether the work has been handed over to the AC properly or not. I'd appreciate if this work can be rolled into the next release

**Comment by vegu** [comment]
@job As the deskpro api isnt hosted locally by us i would advise that we have the ticket creation in a process external to the actual web server process as such requests have the potential to stall. As such immediate feedback wouldn't easily be available (only that ticket creation has been added to the queue). 

However ticket creation failures here would simply retry again, as such a user could expect their ticket to be created eventually regardless of any issues.

Furthermore immediate feedback about ticket creation success or errors to the user introduce further complexity that would need to be addressed, such as what to do if the api actually errors for whatever reason, what is the user expected to do in such cases?

**Comment by job** [comment]
I was thinking in quite simple terms: if the ticket to deskpro can't be submitted: log an error and ask the user to try again later. If there is no ticket in deskpro the process falls apart anyway

**Comment by job** [comment]
Queueing up requests that need to be passed on to deskpro is perhaps not a bad idea, and letting a worker process go over that queue is not a bad idea either. I leave it in your capable hands :-) If we get rid of SMTP I'm a happy man!

**Comment by vegu** [comment]
fixed in a02e90f and rolled to production in version 2.8.1
