### ISSUE TITLE
Fix URL in generated DespPRO ticket

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/peeringdb#283]
![DeskPRO Agent Interface (1).png](https://images.zenhubusercontent.com/57929671e40e5714b16c6b73/69be8121-5cef-44f6-b8a2-0d89d08d6c78)

Should stop at last "/".

**Comment by mcmanuss8** [comment]
+1 do this

**Comment by job** [comment]
Looking at the code, it seems that the `</a>` is placed correctly

```
{% trans "You can go to" %} <a href="{{ edit_url }}">{{ edit_url }}</a> {% trans "to view and approve or deny this entry" %}{% endlanguage %}
```

Could it be that deskpro is trying to be smart with URLs and is sort of autogenerating a HREF while there already is a HREF?

**Comment by arnoldnipper** [comment]
Looks like the issue was fixed w/o closing it.

**Comment by job** [comment]
cool!
