### ISSUE TITLE
create documentation site

### ISSUE THREAD

**Issue by grizz** [peeringdb/peeringdb#285]
Should include things like a user guide, and document all policy and inner workings for PDB.

- How to use PDB
- IXF-IXP import rules
- Oauth help

**Comment by arnoldnipper** [comment]
There is https://docs.peeringdb.com/

**Comment by andrewbaskett** [comment]
Under docs.peeringDB.com , suggestion is to take one of the Portuguese or Spanish quick start PDFs and translate it into English ( https://docs.peeringdb.com/guide/guia_PeeringDB.pdf )

**Comment by arnoldnipper** [comment]
There are plenty of slides in the full blown presentation set. Should be easy to compile a quick start PDF from that
