### ISSUE TITLE
Ability for IX Operators to modify participants via web interface

### ISSUE THREAD

**Issue by mustangthz** [peeringdb/peeringdb#286]
Please add the ability for IX Operators to remove participants from IX's and reclaim IP's from the web interface.

**Comment by as44980** [comment]
Rather than going against the user-submitted data model would it be worth considering process where an IX operator can flag that a network is no longer a participant of their IX, thus allowing it to be removed following a review by an admin to prevent misuse... accidental or otherwise?

**Comment by arnoldnipper** [comment]
automation, automation, automation ... why not use the import in IX-F JSON format???

**Comment by mustangthz** [comment]
Because not everyone has the ability to automate everything.

**Comment by as44980** [comment]
Or may perhaps even be contractually inhibited from revealing that a particular network is connected, but crucially not prevented from confirming that a network is not connected or at least is not presently allocated the IP which is listed in their PeeringDB record?

**Comment by grizz** [comment]
@peeringdb/pc no votes on this

This might be better done as a separate tool that creates the IX-F schema.

**Comment by mustangthz** [comment]
So you’re saying you have a JSON way for IX’s to mod their space, but you can’t spend a few cycles for IX’s that are not that automated to have a web interface to mod their space?

I think that’s a horrible disservice to small IX’s that do not have devops groups to deal with that.

I really urge the PDB team to reconsider.

-Chris

**Comment by grizz** [comment]
@mustangthz I'm not saying that at all, no. I'm bringing this issue to the attention of the PC, as well as offering possible implementation ideas. The separate tool could easily be done in PDB.

**Comment by bijals** [comment]
FYI Euro-IX is already developing a tool for IXPs to do this and it will be available in a few weeks.

**Comment by mustangthz** [comment]
Rejecting a pdb feature request based on an IXF add is disingenuous.

**Comment by bijals** [comment]
I'm not rejecting the idea for PDB to do it, just stating for the record that there is another association/community working on the same piece of work. 

And while we're talking about the JSON, version 0.8 is being worked on and will be released shortly.

**Comment by arnoldnipper** [comment]
I would like to see proposal from 20C on how much it would cost to implement this feature. So far IXes email AC and the IP gets removed within hours typically

**Comment by grizz** [comment]
@arnoldnipper we will check it out.

**Comment by mustangthz** [comment]
Thank you both!

**Comment by mustangthz** [comment]
Thank you Matt for knocking it out of the park!!!

**Comment by arnoldnipper** [comment]
awesome, @grizz  ... personally I also would keep it separate from PDB. Maybe something like https://tools.peeringdb.com could work

**Comment by mcmanuss8** [comment]
@peeringdb/pc seems like something that should be part of peeringdb or at least hosted on our domain (tools.peeringdb.com is a good idea Arnold). 
Anyone want to shepherd this one?

**Comment by arnoldnipper** [comment]
> @peeringdb/pc seems like something that should be part of peeringdb or at least hosted on our domain (tools.peeringdb.com is a good idea Arnold).
> Anyone want to shepherd this one?

In the light of DOTF what about that an `ix` is also able to populate the _exchange table_ manually. Usually this table would be fed by the IX-F JSON import.

@vegu / @pc comments?

**Comment by arnoldnipper** [comment]
@pc, please have a closer look at it. It would definitely help those 675/822 exchanges (82.11%) which are not yet able to provide an IX-F JSON import.

**Comment by shane-kerr** [comment]
> In the light of DOTF what about that an `ix` is also able to populate the _exchange table_ manually. Usually this table would be fed by the IX-F JSON import.

@arnoldnipper I'm not exactly sure what you are proposing. Can you please clarify?

**Comment by arnoldnipper** [comment]
@shane-kerr, I'm proposing that exchanges are allowed to add/change/delete  `netixlan` records as well. However, instead of committing the change directly, it goes to the same table where IX-F JSON import changes go and we follow the same procedure as if this change came from an IX-F JSON import.

Does that explain what I'm proposing?

**Comment by ynbrthr** [comment]
+1

**Comment by arnoldnipper** [comment]
**Summary**

Provide a tool to allow exchanges to add/change/delete `netixlan` records. However, instead of committing the change directly, it goes to the same table where IX-F JSON import changes go and we follow the same procedure as if this change came from an IX-F JSON import.

Probably an existing [tool](https://fullctl.com/app/ixctl/) could be used as a basis.

**Comment by egfrank** [comment]
#### Proposal

It sounds like the core problem here is that if IX's don't have resources to maintain their own IX-F feed, they don't have a way to propose changes to the `netixlan` records. 

We suggest creating an endpoint `/export/ixlan/{id}/proposal` that outputs an IX-F feed with both current and proposed `netixlan` records. If the ix-f import isnt set up with an external URL, the importer will use this endpoint for these manual proposals.

IX admins propose changes through the now editable panel of Netixlans on the IX view; the UI to edit / add / change netixlans will be similar to the one on the network view. When an IX admin changes a Netixlan in this way, that change is registered as a proposal, displayed on the IX page, and reflected in the `/export/ixlan/{id}/proposal` endpoint.

On the backend, proposals to add / edit / delete `netixlans` will still POST / PUT / DELETE to `/api/netixlan`, but Peeringdb will check for permissions on the reques. If the user is **not** a Network Admin but **is** a IX admin, then those changes will registered as proposals.

**Comment by egfrank** [comment]
@peeringdb/pc  here^ is a proposed summary for the issue for you to review! Moving to 3a as we discuss implementation

**Comment by arnoldnipper** [comment]
> If the user is **not** a Network Admin but **is** a IX admin, then those changes will registered as proposals.

A user may be **both**. So, being an IX admin for the IX in question should be sufficient.

**Comment by grizz** [comment]
Err, I didn't read this issue when moving from Reached to Finalized,  I don't see any other +1s so I'm not sure why it got pushed to reached. At any rate -1 from me, and moving back to decide.

**Comment by arnoldnipper** [comment]
@grizz, I see +1's from @mcmanuss8. @ynbrthr, @shane-kerr and me. Which makes >=3. What's your reasoning to push this back?

**Comment by leovegoda** [comment]
The Product Committee has decided to close this issue. There was no agreement on the concept and the issue has not been discussed for six months or longer.
