### ISSUE TITLE
Definition of "facility" needed (esp. size / span)

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/peeringdb#287]
Citing Peter Helmenstine: Normally I'm ok with a campus simply being represented as a facility and don't want to open up a can of worms but with campuses now extending tens of miles apart there are issues of latency, what's a cross connect, costs for campus fiber, multi-tenant facilities, etc., I'm afraid this can of worms is already open and PeeringDB is allowing ambiguity. If Inflect is building an API to help identify facilities, with addresses creating separate facilities then there going to be a conflict. Basically I'd like to request the Product Comittee come up with that definition, especially if it's one of the 3 pillars of what we're approving.

**Comment by as44980** [comment]
oops I dropped the can and the worms are loose..

First thought is anything remotely related to size/capacity could be comercially sensitive for some and/or hard to resist 'rounding up'.. plus feature creep of questionable benefit for finding peers.

I suspect it may be hard to enforce operators to represent facilities consistently with a variety of potential combinations of multiple facilities, perhaps even run by different operators, in a multi-tennant building to those who consider multiple physically separate buildings to be the same facility... 

Is there any value in having some kind of guidance on best practice on how to represent facilities, for example should anywhere with a unique (delivery) address be considered an independent facility?

And for multi-tennant would it be worth capturing the floor, and if so do we need to consider both multi-floor facilities and mutiple facility operators on the same floor?

Finally for a 'campus' this doesnt seem to benefit from a universally accepted defitiion but could it be worth creating some sort of relationship between sites which are considered to be part of a 'campus', and perhaps what type of connectivity the operator offers between the sites to make them a campus?

If so should there be any conisderation on geographical proximity, or would it be acceptable for an operator to suggest all of their facilites across the globe were a 'campus' linked by wet string and rfc2549 backup paths?

:)

**Comment by mcmanuss8** [comment]
My personal feeling on this is to model is like:

Facility is either a building or a subset of a building operated by a different entity than the parent building. Facilities can be related to each other with metadata:

parent, child, association 

So if you have a multi-tenant building Foo you might have:

Facility A: Foo (owned by Foo Corp)
Facility B: Big Colo 
Facility C: Small Colo

A, B, tenant
A, C, tenant

And if you have Equinix Ashburn you might have:

Facility A: Equnix DC1
Facility B: Equnix DC2
Facility C: Equnix DC4
Facility D: Equnix DC5
Facility E: Equnix DC6

You might make an "Equinix Ashburn Campus" virtual facility (as @arnoldnipper suggested in #11), calling it Z:

Z, A, campus
Z, B, campus
Z, C, campus
Z, D, campus
Z, E, campus

The implication here is that facilities only get associated if the ease/cost of crossconnects is simpler than between two random buildings.

**Comment by mcmanuss8** [comment]
@peeringdb/pc thoughts here welcome

**Comment by ynbrthr** [comment]
> My personal feeling on this is to model is like:
> 
> Facility is either a building or a subset of a building operated by a different entity than the parent building. Facilities can be related to each other with metadata:
> 
> parent, child, association
> 
> So if you have a multi-tenant building Foo you might have:
> 
> Facility A: Foo (owned by Foo Corp)
> Facility B: Big Colo
> Facility C: Small Colo
> 
> A, B, tenant
> A, C, tenant
> 
> And if you have Equinix Ashburn you might have:
> 
> Facility A: Equnix DC1
> Facility B: Equnix DC2
> Facility C: Equnix DC4
> Facility D: Equnix DC5
> Facility E: Equnix DC6
> 
> You might make an "Equinix Ashburn Campus" virtual facility (as @arnoldnipper suggested in #11), calling it Z:
> 
> Z, A, campus
> Z, B, campus
> Z, C, campus
> Z, D, campus
> Z, E, campus
> 
> The implication here is that facilities only get associated if the ease/cost of crossconnects is simpler than between two random buildings.

makes sense. +1

**Comment by arnoldnipper** [comment]
> Facility is either a building or a subset of a building operated by a different entity than the parent building.

By that definition I would also be a facility operator if I have rented a rack from whoever and sublease. Right?

**Comment by mcmanuss8** [comment]
> > Facility is either a building or a subset of a building operated by a different entity than the parent building.
> 
> By that definition I would also be a facility operator if I have rented a rack from whoever and sublease. Right?

Good question. It could be the case, but I'd rather treat "how big do you need to be to operate a 'facility'" as a separate question outside the scope of this issue. :) In my personal opinion, a rack is too small to be interesting for a facility, but maybe a cage? Certainly a suite or a floor within a building could be.

**Comment by arnoldnipper** [comment]
IMO https://github.com/peeringdb/peeringdb/issues/287#issuecomment-391481402 is worth be reread

**Comment by as44980** [comment]
> Facility is either a building or a subset of a building operated by a different entity than the parent building. Facilities can be related to each other with metadata:

So while many facilities occupy the entire building, or perhaps even span multiple buildings, there are plenty of buildings which contain multiple facilities operated by different orgs.. 

Hence is there any value in considering "buildings" as a separate data type, which could either be marked as multi-tenanted and thus allow the creation of multiple facilities within (ie a child of) this building object..

While if a building is created as single tenanted then only one facility would be allowed to be created here, potentially with admin review for any subsequent requests to create a facility in such a building.

This could potentially allow a fairly simple and non-contentious definition of a building, and if multiple facilities are permitted in a multi-tenanted building then perhaps the use cases for the potentially more contentious "facility within facility" are relatively rare?

Finally as the "campus" model is used by a number of facility operators use, this certainly seems worth considering to be somehow reflected in PeeringDB but perhaps in its own thread..

However with regards to the idea of a separate building record, if there was a means to reflect a campus style relationship between two facilities that may provide a solution to any corner cases where what is commonly considered to be a single "facility" actually spans multiple buildings :)

**Comment by arnoldnipper** [comment]
To move this forward here is a **proposal** based on Steve's [idea](https://github.com/peeringdb/peeringdb/issues/287#issuecomment-433989857)

- add three fields `landlord`, `campus`, and `part_of` to the `fac` object
 - the field `landlord` should be used iff the Facility A is either a building or a subset of a building operated by a different entity than the parent building. The value of the field is the id of the Facility L where Facility A belongs to or is part of. (Note: org_id(A) != org_id(L))
 - a facility with the field `campus` set to `true` can not be referenced in any fac relation (currently `ixfac` and `netfac`)
 - the field `part_of` may be used to model a campus. A facility A having a `part_of` field with value N is part of the (pseudo)facility C with id N and which has set the field `campus` to `true`

@peeringdb/pc, please discuss!

**Comment by as44980** [comment]
> To move this forward here is a **proposal** based on Steve's [idea](https://github.com/peeringdb/peeringdb/issues/287#issuecomment-433989857)
> 
>     * add three fields `landlord`, `campus`, and `part_of` to the `fac` object
> 
>     * the field `landlord` should be used iff the Facility A is either a building or a subset of a building operated by a different entity than the parent building. The value of the field is the id of the Facility L where Facility A belongs to or is part of. (Note: org_id(A) != org_id(L))
> 
>     * a facility with the field `campus` set to `true` can not be referenced in any fac relation (currently `ixfac` and `netfac`)
> 
>     * the field `part_of` may be used to model a campus. A facility A having a `part_of` field with value N is part of the (pseudo)facility C with id N and which has set the field `campus` to `true`

I support this as a pragmatic means to deal with a complex issue, but wanted to confirm that with this model the `landlord` would be given the means to approve or reject another entity declaring their facility to be located within the landlords facility?

If so then I suspect consideration needs to be given to unresponsive "landlords" and facilities where the owner may not even be aware of the existence of PeeringDB, perhaps a limit of 90 days for the facility operator to approve/reject before the AC could be asked to consider the request?

Additionally for the campus concept, are we to assume that its left to the objects creator to decide what qualifies the member facilities to be 'part_of' this campus object, rather than attempting to find consensus on a definition based on geographical proximity and/or connectivity options?  :)

**Comment by arnoldnipper** [comment]
> I support this as a pragmatic means to deal with a complex issue, but wanted to confirm that with this model the `landlord` would be given the means to approve or reject another entity declaring their facility to be located within the landlords facility?
> 
> If so then I suspect consideration needs to be given to unresponsive "landlords" and facilities where the owner may not even be aware of the existence of PeeringDB, perhaps a limit of 90 days for the `landlord` facility operator to approve/reject before the AC could be asked to consider the request?

This should be discussed in a separate issue. Already today we have the situation that an IX or net can create an `ixfac` resp. `netfac` w/o consent of the facility owner.  Most likely this is a topic for the DOTF again.



> Additionally for the campus concept, are we to assume that its left to the objects creator to decide what qualifies the member facilities to be `part_of` this `campus` object, rather than attempting to find consensus on a definition based on geographical proximity and/or connectivity options?

Sure, this is left to the object creator. However, IMHO it make sense to define a maximum diameter (either circle or square). Today the [largest DC](https://www.analyticsvidhya.com/blog/2020/09/8-largest-data-centers-world-2020/) covers an area of 0.67km^2 (diameter 0.92km if covered by a circle resp. 0.82km if covered by a square). So anything more than 1km apart should not be considered as a campus.

**Comment by as44980** [comment]
> > I support this as a pragmatic means to deal with a complex issue, but wanted to confirm that with this model the `landlord` would be given the means to approve or reject another entity declaring their facility to be located within the landlords facility?
> > If so then I suspect consideration needs to be given to unresponsive "landlords" and facilities where the owner may not even be aware of the existence of PeeringDB, perhaps a limit of 90 days for the `landlord` facility operator to approve/reject before the AC could be asked to consider the request?
> 
> This should be discussed in a separate issue. Already today we have the situation that an IX or net can create an `ixfac` resp. `netfac` w/o consent of the facility owner. Most likely this is a topic for the DOTF again.

While I think this is a key area that would need to be addressed _before_ any such landlord/tenant relationship is added to the database, I am happy to leave this to be raised as a separate issue _if_ there is consensus to move forward with this :)

**Comment by as44980** [comment]
> Sure, this is left to the object creator. However, IMHO it makes sense to define a maximum diameter (either circle or square). Today the [largest DC](https://www.analyticsvidhya.com/blog/2020/09/8-largest-data-centers-world-2020/) covers an area of 0.67km^2 (diameter 0.92km if covered by a circle resp. 0.82km if covered by a square). So anything more than 1km apart should not be considered as a campus.

I support the model of leaving this to the creator to decide the criteria for inclusion in 'their' campus, but also with some loose boundaries to prevent all of an entities `fac` records being grouped simply because its possible to get some sort of connectivity between them..

However I am not convinced that sizing this based on the dimensions of a sinlge "DC" is wise since the campus concept is typically used to represent multiple building which are either adjacent, on the same plot of land or otherwise "nearby"..

There are operators who market their facilities as a "campus" based on sites where they offer sub 10km dark fiber interconnection options, so if we are to bound the sites which can be `part_of` a `campus` then I would propose a value no less than 10km diameter circle :)

**Comment by arnoldnipper** [comment]
> However I am not convinced that sizing this based on the dimensions of a sinlge "DC" is wise since the campus concept is typically used to represent multiple building which are either adjacent, on the same plot of land or otherwise "nearby"..

The DC mentioned **is a campus**

**Comment by as44980** [comment]
> > However I am not convinced that sizing this based on the dimensions of a single "DC" is wise since the campus concept is typically used to represent multiple building which are either adjacent, on the same plot of land or otherwise "nearby"..
> 
> The DC mentioned **is a campus**

My bad, I assumed that DC was short for the singular Datacenter/Datacentre rather than plural Datacenters/Datacenters ;)

I see that the largest "DC" on that list also asserts that is "largest data center campus in the world" without any definition of campus or it even being mentioned in any of the other entries, is there any more authoritative or consensus driven definitions of this term or is it largely considered to be 'marketing speak'?

As to the relevant that this "DC" "covers an area of 0.67km^2 " I note that the figures quotes are surface area of a number of buildings which appear to have more than a single story, and in this context can reasonably be assumed to refer to the 'floor space' across all floors, which I suspect makes any relation between thees figures and the maximum distance between two facilities which can "be considered as a campus" questionable.

If the definition of the `campus` is to be left to the creator then I don't think its safe to assume that all operators who market a grouping of what are currently independent `fac` records would envisage the proposed `campus` being used exclusively to refer to multiple facilities on a single plot of land, as all of the examples in the linked article appear to be, or for the ability to group these facilities being limited to a maximum separation of 1km.

Based on how I see this term being applied I would propose that, if we seek to put a limit on the distance which a `fac` record can be from any other `fac ` in the `campus` which a user seeks to make it `part_of`, then a suitable value could be the 10km distance which is supported by what I expect is the most commonly used Ethernet PHY for interconnection within these facilities :)

**Comment by arnoldnipper** [comment]
> and in this context can reasonably be assumed to refer to the 'floor space' across all floors

No ... it says "... It is located in Tahoe Reno, Nevada, and covers an area of a boasting 7.2 million square feet." 



> then a suitable value could be the 10km distance

This is way too much.  That would e.g. cover all DC in Frankfurt. IMHO a maximum distance of 1km is reasonable.

**Comment by as44980** [comment]
> > and in this context can reasonably be assumed to refer to the 'floor space' across all floors
> 
> No ... it says "... It is located in Tahoe Reno, Nevada, and covers an area of a boasting 7.2 million square feet."

https://www.prnewswire.com/news-releases/switch-tahoe-reno-now-open-largest-most-advanced-data-center-campus-in-the-world-300407648.html

"the largest, most advanced data center campus in the world .. is designed for up to 7.2 million square feet of data center space"

And "The 2,000 acre campus, located in the Tahoe Reno Industrial Center next to the Tesla Gigafactory, is powered by 100-percent renewable energy"

https://www.calculateme.com/area/acres/to-square-meters/2000

2,000 Acres =
8,093,712.8 Square Meters
(rounded to 8 digits)

> > then a suitable value could be the 10km distance
> 
> This is way too much. That would e.g. cover all DC in Frankfurt. IMHO a maximum distance of 1km is reasonable.

This would appear to be the danger that PeeringDB seeks to define a `campus` to be much smaller than how I understand this term to be used in the industry, so on that basis IMHO limiting this to anything _under_ 10km is unreasonable..  hence we may have to agree to disagree ;)

Does anyone else have any opinions on this, or any sort of definitive definition of a campus which can be referenced?

**Comment by arnoldnipper** [comment]
> This would appear to be the danger that PeeringDB seeks to define a `campus` to be much smaller than how I understand this term to be used in the industry,

Do you have a reliable source for your assertion?

**Comment by mustangthz** [comment]
I think my concern with all of this is that you're trying to establish hard fast rules that can be, and are, used to deny people.  There are tons of examples of interconnection, Yan's examples are great.  Here's another example.  An office building in Cedar Rapids, Iowa, USA (fictional location) that has a closet in the basement where 8 carriers interconnect.  The local WISPs and FISPS also connect there.  Clearly it doesn't meet the current draconian, non-transparent version of a facility.  However, it is an interconnection facility.  The entire conversation needs to be reset as "Suggestions for Facilities."  PeeringDB has Zero business defining what a facility is. Hell, a FISP could have a shack on the size of the road where 3 ISP's meet up to peer, that's a facility.

**Comment by arnoldnipper** [comment]
@peeringdb/pc do we want to go ahead with the [proposal](https://github.com/peeringdb/peeringdb/issues/287#issuecomment-739707546)? Please make up your mind.

**Comment by martinhannigan** [comment]
> > This would appear to be the danger that PeeringDB seeks to define a `campus` to be much smaller than how I understand this term to be used in the industry,
> 
> Do you have a reliable source for your assertion?

I have been there. Switch bought a large patch of land in Sparks, NV (in the Tahoe area). They also have a high count dark fiber network circling the US. Interconnection takes place within their facility between their customers and off-net using typical and extended interconnection methods. Switch Tahoe also has access to the Tahoe IX. 

Munich is 29,405.540 acres vs. 2000 acres and ~67% larger than the Switch Campus in Sparks. Not sure I understand why this matters. See #5 : https://www.dictionary.com/browse/campus?s=t 


+1 @mustangthz +1 @as44980  and FWIW -1 to @arnoldnipper question on proceeding.

**Comment by arnoldnipper** [comment]
@mustangthz, @as44980, @martinhannigan what about limiting the diameter to 100km? This would e.g. cover all of NYC.

**Comment by mustangthz** [comment]
If we have to have an arbitrary distance for a campus, 100km is likely fine.

**Comment by mcmanuss8** [comment]
Why set a distance limit at all, as long as the facilities in question can provide a cross connect between facilities in a similar cost and turnaround time as one within a building? I feel like that's what's really driving a campus model, not the actual physical distance.

In other words, if I have to procure my own fiber to connect two buildings for a reasonably small amount of connectivity, they're not a campus. I agree this doesn't lend itself well to a hard and fast rule though. :)

**Comment by job** [comment]
I imagine anyone using PDB is really just investigating to understand what barriers might exist between them and others they want to interconnect with.

If non-OEO / unlit fiber is available, the geographical distance is somewhat relevant given the commonly understood limitations of COTS optics: Long-Haul, Short-Haul, etc.

Often times the term 'campus' is meant to mean "you can optically connect assets within the campus", but of course other parties saw the value of the term 'campus' and started applying the term "campus" to sets of buildings which are at such distance from each other that the distance cannot reasonably be overcome with un-amplified optical.

I see some value to anchor what we're trying to establish here in physics:

- < 10 KM (via COTS optics in linecards of the IX or Net)
- < 100 KM (via IX/Net owned COTS amplifiers)

Any group of buildings which requires intermediate carriers to connect one asset to another, the term 'campus' no longer applies in my opinion.

**Comment by arnoldnipper** [comment]
Of course, that's the idea of a campus. But as @mustangthz said: Not reliable at all. It’s like looking at sticker prices for cars

**Comment by as44980** [comment]
> If we have to have an arbitrary distance for a campus, 100km is likely fine.

+1

**Comment by as44980** [comment]
> Often times the term 'campus' is meant to mean "you can optically connect assets within the campus", but of course other parties saw the value of the term 'campus' and started applying the term "campus" to sets of buildings which are at such distance from each other that the distance cannot reasonably be overcome with un-amplified optical.

I agree that, even just based on this thread, there are a variety of interpretations as to the definition of a "datacenter campus" and how far apart the facilities which make us this campus can be..

> Any group of buildings which requires intermediate carriers to connect one asset to another, the term 'campus' no longer applies in my opinion.

However I would be inclined to take the more inclusive definition which does not depend on the availability of fiber or what commercial models this may be offered on, IMHO its largely academic if the facility operator can offer this as there are cases where its widely considered more cost effective to use third party/external fibres to connect between two facilities located on a contiguous plot of land.

 
> I see some value to anchor what we're trying to establish here in physics:

I would also agree with this as without limits somebody is likely to try to create a "global campus" of facilities, and if we are going to have limits then it would make sense to anchor it in the physical world and directly related to the COTS technologies used to light such fibers :)

**Comment by arnoldnipper** [comment]
Looks like we reached a consensus so far. Hence, is everyone happy if I split this issue into two
- tenant pseudo facility object (i.e. multiple facilities in one building / at the same address)
- campus pseudo facility object (i.e. multiple facilities _close_ to each other and belonging to the same operator)

If no one butts in within a week from now, I will separate the issue.

**Comment by DarwinCosta** [comment]
> Looks like we reached a consensus so far. Hence, is everyone happy if I split this issue into two
> 
> - tenant pseudo facility object (i.e. multiple facilities in one building / at the same address)
> 
> - campus pseudo facility object (i.e. multiple facilities _close_ to each other and belonging to the same operator)
> 
> 
> 
> If no one butts in within a week from now, I will separate the issue.

@arnoldnipper Im ok with the splitting suggestion.

**Comment by leovegoda** [comment]
@peeringdb/pc With the release of the `campus` object, should we close this issue and create new ones for any remaining work?

**Comment by arnoldnipper** [comment]
> @peeringdb/pc With the release of the `campus` object, should we close this issue and create new ones for any remaining work?

This issue was already split. Hence, it can be closed

**Comment by arnoldnipper** [comment]
https://github.com/orgs/peeringdb/teams/pc With the release of the campus object, should we close this issue and create new ones for any remaining work?

This issue was already split. Hence, it can be closed
