### ISSUE TITLE
Better error message when user tries to add a record (basically network) with status "deleted"

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/peeringdb#288]
PDB does not really delete network records but simply flags them as deleted. If a user tries to add such a network s/he gets the error message

 "network with this asn already exists"

Please change this to

 "network has been deleted. Please contact support@peeringdb.com"

![20180220 peeringdb 01](https://user-images.githubusercontent.com/16888757/36456511-9bc573ee-16a5-11e8-97ff-a7661e3d3394.png)

**Comment by eloos** [comment]
Why is it that networks are not forgotten? is this unique to net objects? How does this relate to #121? There we say we will allow an admin user to delete the org?

**Comment by arnoldnipper** [comment]
Org is the "root". Records "net", "fac" and "ix" are haning off org logically and any admin is able to delete one of this records but not able to re-add.

What about having a deleted record still visible to the owner, but not to the public.

**Comment by mcmanuss8** [comment]
+1 to changing the error message to:
"network has been deleted. Please contact support@peeringdb.com"
when the object has been deleted/archived

**Comment by arnoldnipper** [comment]
+1

**Comment by job** [comment]
+1

**Comment by shane-kerr** [comment]
+1 

It's a hack, but better than the confusing message now!

**Comment by arnoldnipper** [comment]
It's still the old error message
![Screenshot 2019-11-18 12 58 34](https://user-images.githubusercontent.com/16888757/69050969-5d04d980-0a03-11ea-800f-5986d878f942.png)

**Comment by vegu** [comment]
@arnoldnipper 133725 isnt a deleted asn, it currently has the status `ok` on beta - trying with 137001 which is currently set to `deleted` gives the expected message

![gh_288_screenshot](https://user-images.githubusercontent.com/143124/69054180-bd037c00-0a13-11ea-8d2b-6462906ef060.PNG)

**Comment by arnoldnipper** [comment]
Sorry, should have looked in https://beta.peeringdb.com/cp as well :)
