### ISSUE TITLE
Offer 2FA

### ISSUE THREAD

**Issue by job** [peeringdb/peeringdb#290]
Might be cool if we offer 2FA with TOTP 

If users want to enable 2FA they should be presented with a QR code and a hexadecimal representation to import the TOTP in their password manager.

**Comment by job** [comment]
https://django-otp-official.readthedocs.io/en/latest/

**Comment by netravnen** [comment]
Is there any short-term plan for implementing this feature in PDB v2.7 or v2.8 release ?

**Comment by grizz** [comment]
@peeringdb/pc no votes on this, +1 from me

**Comment by arnoldnipper** [comment]
+1

**Comment by mcmanuss8** [comment]
+1 2FA would be very good especially if people start using pdb oauth more

**Comment by job** [comment]
@shane-kerr @mcmanuss8 - what are your thoughts on this one?

**Comment by shane-kerr** [comment]
+1 

Makes sense to me.

**Comment by job** [comment]
Also, now that PeeringDB is an OAuth Identity Provider, it makes even
more sense to improve account login security

**Comment by arnoldnipper** [comment]
@vegu and @grizz, is this straightforward to implement? Or do you need a spec?

**Comment by mcmanuss8** [comment]
I think we should offer 2FA but not *require* 2FA.

**Comment by shane-kerr** [comment]
I agree that we shouldn't require 2FA, although we may want to consider allowing an IX or ISP to require it for users that update their information somehow.

For example, my company uses GitHub which has optional 2FA support. However our company policy requires 2FA for employees who work on our code base there.

**Comment by job** [comment]
Yes, should be optional!

**Comment by grizz** [comment]
@arnoldnipper should be straight forward

@peeringdb/pc This will need an SMS provider for backup to be done correctly, https://www.twilio.com/pricing seems reasonable, yes?

**Comment by lukastribus** [comment]
Why SMS? I don't get it.

**Comment by grizz** [comment]
I guess could just use email, is that what you mean @lukastribus? I'm happy for anyone to define the spec :)

**Comment by grizz** [comment]
> I agree that we shouldn't require 2FA, although we may want to consider allowing an IX or ISP to require it for users that update their information somehow.
> 
> For example, my company uses GitHub which has optional 2FA support. However our company policy requires 2FA for employees who work on our code base there.
> 
> EDIT: This may be out of scope for this ticket, possibly we should a separate ticket for that work.

Probably out of scope for this, but definitely a good idea. For now, we should add a flag in the org user list that shows if the user has 2FA enabled to org admins.

**Comment by job** [comment]
No SMS, No Email.

This feature request is about 2FA using TOPT (
https://tools.ietf.org/html/rfc6238)

**Comment by lukastribus** [comment]
@grizz tbh I didn't understand what we were talking about in the first place. I realize now this is about account recovery when the second factor is lost.

Now peeringdb in general is as secure as the email account referred to the resource in the RIR database, because that is used for account validation for new users.

A manual request towards peeringdb support would probably lead to a re-validation based on that, so it's not gonna get more secure than that (RIR database + email account referred therein).

So like @job say's, don't provide account recovery at all with 2FA and have the users reach out to PDB support in case 2FA are lost (and there is no other users in the org to handle it)?

Both SMS and email are compromising 2FA security, if used as account recovery method.

**Comment by grizz** [comment]
Yes, I was talking about recovery, I disagree with not having a recovery method, not quite strongly enough to -1 this, but very close.

Not having recovery is just going to make workload go up for @peeringdb/ac and how exactly are they going to verify the person is who they say they are? @job please write the proceedure you'd like them to follow for recovery.

Also, it seems silly going from no 2FA to ridiculous overkill.

My 2c, I'll digress.

**Comment by job** [comment]
Ohhhh i think i got confused in the conversation. 

I thought you suggested that the second factor would be SMS or email, and I hope it would just be TOTP.

For recovery... yeah, let's just use the existing mechanism (email)? No need to change that now

**Comment by mcmanuss8** [comment]
So to clarify the ask:

1) PeeringDB should offer 2FA via TOPT, but not require it
2) If TOPT is inaccessible for the user, we should offer a recovery mechanism for them via email


If so, +1 although I think SMS is a nice alternative recovery mechanism in case someone's email has been compromised. There could be some downsides however if the person's organization doesn't want them to login anymore without access to their corporate email.

**Comment by lukastribus** [comment]
SMS recovery won't add any benefit, if an attacker can write to PDB support from a compromised email account, listed in the RIR database (the assumption being that PDB support is gonna reset 2FA for that account in that case).

SMS just add's additional attack surface to 2FA.

Either we just allow recovery via email and be done with it. Or we need to think about proper threat models including human interaction with PDB support from a compromised email account. I suggest we do the former.

**Comment by grizz** [comment]
> SMS recovery won't add any benefit, if an attacker can write to PDB support from a compromised email account, listed in the RIR database (the assumption being that PDB support is gonna reset 2FA for that account in that case).

Being listed in an RIR isn't required for having a PeeringDB user account, FWIW.

**Comment by funkestefan** [comment]
+1 for TOTP and e-mail as a recovery option.

**Comment by netravnen** [comment]
> +1 for TOTP and e-mail as a recovery option.

Allow using more than one MFA device?

=> Each account would be allowed to have up to e.g. 2-3 MFA sources affiliated.

**Comment by funkestefan** [comment]
> Allow using more than one MFA device? => Each account would be allowed to have up to e.g. 2-3 MFA sources affiliated.

Just reveal/show the TOPT URI and you can add it on as many devices as you want. (including your favourite password manager)

**Comment by netravnen** [comment]
> +1 for TOTP and e-mail as a recovery option.

Generate a secret key/token the user is asked to store securely for recovery purpose of their account. In case MFA device is lost. Google calls it **backup-codes**. GitHub calls it [**recovery token**](help.github.com/en/github/authenticating-to-github/recovering-your-account-if-you-lose-your-2fa-credentials#authenticating-with-an-account-recovery-token).

**Comment by grizz** [comment]
To summarize since this got off track a bit:

- Offer optional 2FA using TOTP
- Add necessary GUI in the user profile to enable and set it up
- Add email recovery using the verified user email address
- Add an icon in the org admin section to denote to org admins only if users have 2FA enabled

Assuming that's correct, this will be a Major.

**Comment by Gunni** [comment]
May I add a request for FIDO2 to be supported as 2fa?

Specifically, FIDO U2F using security keys.

**Comment by mcmanuss8** [comment]
@Gunni FIDO is a good request, but we might need to fork that to another issue as it's out of the scope we had already agreed on. I created #692 to track that

**Comment by koalafil** [comment]
Can we pls have the Release Notes? Thx.

**Comment by arnoldnipper** [comment]
2FA is offered now. The implementation includes

 * optional 2FA using TOTP is offered
 * there is a knob in the user profile to enable and set it up
 * email recovery is added using the verified user email address
 * an icon is added in the org admin section to denote to org admins only if users have 2FA enabled

**Comment by job** [comment]
Can we link the TOTP word:

```
<a href="https://tools.ietf.org/html/rfc6238">TOTP</a>
```

**Comment by funkestefan** [comment]
> Can we link the TOTP word:
> 
> ```
> <a href="https://tools.ietf.org/html/rfc6238">TOTP</a>
> ```

Oh yes, please.
