### ISSUE TITLE
Make LAN information, Website and technical email mandatory for adding an IXP

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/peeringdb#291]
Currently only the name and the city is mandatory. For new IXes LAN information, Website as well as technical email **must** be mandatory.
![20180226 peeringdb 00](https://user-images.githubusercontent.com/16888757/36671846-85e898d8-1afd-11e8-88b7-53b7b9e3e28f.png)

**Comment by as44980** [comment]
Out of interest, would you propose to simply require that these fields have some kind of string or would it be worth also considering at least syntaxical validation such as the Technical Email field containing "@" and the Website starting with http(s):// ?  :)

**Comment by arnoldnipper** [comment]
@as44980 afaik that is how it is already handled today. I.e. fields containing emaill addresses must be email addresses. Fields containing a webaddress must start with http:// resp. https://

**Comment by arnoldnipper** [comment]
@grizz and @vegu, any implementation details needed?
