### ISSUE TITLE
Desk pro tickets -> DeskPRO tickets

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/peeringdb#295]
https://peeringdb.com/cp/peeringdb_server/ ... I was scratching my head what "Desk pro tickets" means

**Comment by arnoldnipper** [comment]
It's just a  spelling issue, but still needs quorum. So please add +1s, @peeringdb/pc

**Comment by shane-kerr** [comment]
Assuming that we mean this:

https://www.deskpro.com/

Then it's actually "Deskpro" not "DeskPRO".

**Comment by arnoldnipper** [comment]
I didn't count how often they use DeskPRO and Deskpro. Maybe they even switch between both spellings. 
![Deskpro Admin Interface](https://user-images.githubusercontent.com/16888757/71097268-092b1300-21b0-11ea-886c-d874bfbf28c8.png)

**Comment by shane-kerr** [comment]
+1 

Okay, I'm happy with anything that is not "Desk pro". :cry:

**Comment by grizz** [comment]
+1 -- It comes from django autonaming, so it's literally just adding 2 lines to the models file, not even a minor

**Comment by mcmanuss8** [comment]
+1

**Comment by grizz** [comment]
@job PR this!

**Comment by job** [comment]
> @job PR this!

I am not sure how or where this word comes from. I don't see the (case insensitive) string 'desk pro' in our source code

**Comment by arnoldnipper** [comment]
@job, here: https://peeringdb.com/cp/peeringdb_server/
![20200211 PeeringDB 00](https://user-images.githubusercontent.com/16888757/74259096-a1003580-4cf7-11ea-89bf-a066dd908dda.png)

**Comment by job** [comment]
I was looking for a link to the source code that governs this aspect, not
the webUI itself :-)

**Comment by arnoldnipper** [comment]
**Release Note**
This is a bug fix and only affects the Admin UI
