### ISSUE TITLE
Make dates ISO 8601 compliant everywhere in PeeringDB

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/peeringdb#296]
Title says it all

**Comment by grizz** [comment]
+1

**Comment by mcmanuss8** [comment]
+1

**Comment by grizz** [comment]
@peeringdb/pc no votes, I can't imagine anyone disagreeing though, so pushing to backlog

**Comment by mcmanuss8** [comment]
+1

**Comment by mcmanuss8** [comment]
Looks like we show a compliant date on /network/ 's "Last Updated" field. 
Only other time I see is dates being used is on "Most Recent Updates" on the main page, which use relative times. I think that's ok. 

Seems like we should add "Last Updated" to /fac/ /ix/ and /org/ - filed #526 for that.

I think this can be closed, please reopen if I missed anything (maybe AC tools that need this?)

**Comment by arnoldnipper** [comment]
@mcmanuss8, dates are not ISO 8601 in the @peeringdb/ac  GUI

**Comment by mcmanuss8** [comment]
@arnoldnipper  this issue is 4 years old, please open a new one and reference this if there are missing spots.
