### ISSUE TITLE
Make it clear that some contact addresses are available by logging in

### ISSUE THREAD

**Issue by zorun** [peeringdb/peeringdb#3]
When the visibility of a contact is set to "Users", it is only displayed to logged-in users.

But when a visitor is not logged in, there is no indication at all that a contact address might be available by logging in.  I frequently use peeringdb without being logged in, and I simply assumed that people did not provide a contact.  Only recently did I discover that there are in fact contact addresses, but you need to be logged in to see them.

A solution to this would be to display the contact while hiding the actual email address / phone number.  There would then be a tooltip (or whatever) explaining that you need to be logged in to actually see the address of the contact.

**Comment by vegu** [comment]
fixed in 9cdad1b - there will now be a notification message in the contact information section if contacts are hidden from you due to not being logged in or because you are viewing with an unverified user account.
