### ISSUE TITLE
add long/lat script to populate data from address

### ISSUE THREAD

**Issue by grizz** [peeringdb/peeringdb#30]

**Comment by vegu** [comment]
fixed in e8fef15

**Comment by vegu** [comment]
found an issue where some business premises could not be geocoded accurately, fixed in 0a2bab4, will be part of 2.5.2 and go out to beta at some point this week.

**Comment by arnoldnipper** [comment]
2.5.2? Aren't we release 2.3.0 in a couple of days only?

**Comment by grizz** [comment]
@arnoldnipper why was this reopened?
