### ISSUE TITLE
Number of peers at an IX

### ISSUE THREAD

**Issue by ericandrei** [peeringdb/peeringdb#300]
Hello,

As I discussed with Arnold last month at APRICOT after his PeeringDB Presentation, I think it would be useful for the IXs pages to show the total number of peers on the right side next to „Peers at this exchange point”.

Right now, to see this number you need to choose a facility where an IX is present.

Please consider this.

**Comment by mcmanuss8** [comment]
Unique ASNs or total # of interfaces?

For example: https://www.peeringdb.com/ix/1
Facebook / AS 32934 has 2 interfaces. Should that count as 2 or 1?

**Comment by ericandrei** [comment]
I mean the number of networks: https://www.peeringdb.com/fac/1. If you look under Local Exchanges you will see this number: 292.

So you can see the number of peers of an IX on a Facility page where it is present, but not on his own page.

**Comment by arnoldnipper** [comment]
@mcmanuss8  ... as much useful information as possible imho

**Comment by tkacprzynski** [comment]
I agree on the total number of connected ASNs per IXP. It would also be useful to see the total port capacity for all peers. For example all of the peers based on their entries show that IXP Y has for example 3.43Tbps of total capacity.

**Comment by mcmanuss8** [comment]
@tkacprzynski  @arnoldnipper  it looks like #18 overlaps with this. I took a stab at a mockup there. Agreed this is a dupe?

**Comment by arnoldnipper** [comment]
@mcmanuss8 ... yep, that's a dupe
