### ISSUE TITLE
Possibility for IXPs to add/update/override information for member information relating to its own IXP

### ISSUE THREAD

**Issue by rasssta** [peeringdb/peeringdb#301]
I would like the possibility to push information to PeeringDB for each of the members of the IXP I operate in PDB. Such as:
* IPv4 addresses
* IPv6 addresses
* If there's an active or configured route server session for the specific IPs
* Interface speed

As a side note: If this was also implemented in IXP Manager the information in PDB would automatically become a more updated source of information.

**Comment by arnoldnipper** [comment]
Please look at #237 ... this already is implemented

**Comment by rasssta** [comment]
It’s only possible via the web site as far as I know and not via the API, right? If it is possible, please supply a link to the API doc for this feature.

**Comment by arnoldnipper** [comment]
It's even easier! Just provide an URL in IX-F JSON format and your entries will be updated reguarly (currently every 24h).

As IX, simply edit your `/ix`
![20180315 peeringdb 00](https://user-images.githubusercontent.com/16888757/37480607-f2b8ab6c-287f-11e8-877b-5dff8cfc9c2e.png)
record and add the URL

See https://ml.ix-f.net/ for the format

**Comment by rasssta** [comment]
Oh, that's awesome! :-)

Thanks!
