### ISSUE TITLE
DeskPRO Ticket creation  for users that have no first and last name

### ISSUE THREAD

**Issue by vegu** [peeringdb/peeringdb#302]
We recently ran into an issue where a ticket  was not being published to DeskPRO because the attached user had no first and last name specified on their peeringdb user account, so we were unable to create a person account on the DeskPro side.

This account was imported during the v1 import back in march 2016.

DeskPRO requires you to create a person account for each email address, so some value needs to be given for `name`. In the case of missing first and last name (or even just last name), we need to substitute something else. username is the only thing that comes to mind.

Particularly interested in how the AC thinks these instances should be handled. How did DeskPRO handle this when we were still using email for ticket creation?

**Comment by arnoldnipper** [comment]
My proposal: bounce  back to user with error message that fname and lname is required

**Comment by arnoldnipper** [comment]
@vegu would that be possible?

**Comment by arnoldnipper** [comment]
See #309

**Comment by grizz** [comment]
@arnoldnipper this is safe to close, since #309 fix it, correct?
