### ISSUE TITLE
Add feature to renumber IPv6 ranges to Renumber IP Space tool

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/peeringdb#303]
![20180321 PeeringDB 001.png](https://images.zenhubusercontent.com/57929671e40e5714b16c6b73/31480eec-14a0-4f7d-b5d5-8228278e7c9c)

**Comment by grizz** [comment]
How should this handle going from bigger or smaller prefixes?

Same prefix length is pretty straight forward.

**Comment by mcmanuss8** [comment]
I imagine for going to larger prefix you would keep the same distance from the network address. For going to smaller, I think you only proceed if the highest IP is less than the new prefix's broadcast. Otherwise you refuse
