### ISSUE TITLE
Add mask to Renumber IP Space tool

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/peeringdb#304]
The tool currently assumes that a /24 is renumbered. It would make more sense to include the mask

**Comment by grizz** [comment]
@arnoldnipper should this include ipv6 support as well? or just ipv4 with other than a /24?

**Comment by grizz** [comment]
How should this work, say, going from a /23 to a /22? Just change the last octets in relation to adding on?

I assume nothing manual from going to a smaller prefix length?

**Comment by arnoldnipper** [comment]
@grizz currently the tool only supports /24. If the LAN is a /22 you have to use the tool 4 times. A generalistaion hence would be to specify $old_mask and $new mask with $old_mask >= $new_mask

And yes, support for IPv6 would also be good, however not so much sought for I guess
