### ISSUE TITLE
Every account should be able to update first name and last name values 

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/peeringdb#309]
And both values have to be != ""

**Comment by as44980** [comment]
Could it be worth considering if the account admin(s) of any organisations the user is affiliated with should have the option to require their approval to ensure they can reliably audit who has access?

**Comment by arnoldnipper** [comment]
@as44980 that is already how it is handled today :)

**Comment by grizz** [comment]
This will need a UI, etc for both users and AC to use.

**Comment by arnoldnipper** [comment]
AC already has via https://peeringdb.com/cp/peeringdb_server/user/$UID/change/, no?

For users https://peeringdb.com/profile would be the natural place imho

**Comment by eloos** [comment]
+1 while there are cases where there is no first/last name, just a single name. Not common though since major websites or travelbooking websites don't allow it either. (personal experience with a friends mother)

**Comment by mcmanuss8** [comment]
So how about First Name/Last Name fields and at least one of them has to be filled in? Warning - but not stopping the user: Ex: "Are you sure you want to only fill in $name_field_they_filled_in?" - if they only fill in one of the name fields?

**Comment by leovegoda** [comment]
The Product Committee has decided to close this issue. There was no agreement on the concept and the issue has not been discussed for six months or longer.
