### ISSUE TITLE
implement rate limiting

### ISSUE THREAD

**Issue by grizz** [peeringdb/peeringdb#311]
Should throttle requests per second to the API by session

This feature is available in Django Rest Framework, so should be quick to implement, but the limits will need to be decided on.

**Comment by arnoldnipper** [comment]
From your experience, what is your recommendation @grizz ?

**Comment by grizz** [comment]
@arnoldnipper we will do some profiling and see what we think a good number will be

**Comment by grizz** [comment]
I think 5/s will be a good place to start, any objections?

**Comment by arnoldnipper** [comment]
> I think 5/s will be a good place to start, any objections?
>

Afais one request may spawn up to 25 follow up requests (according to nginx log). Is the request counted as one? Or as $number_of_follow_up_requests+1?

**Comment by grizz** [comment]
@arnoldnipper good point, we'll make it a config variable
