### ISSUE TITLE
reduce backlog Q2'18

### ISSUE THREAD

**Issue by eloos** [peeringdb/peeringdb#313]
Issue created to bundle several issues into an epic for development

High level summary of issues address in this backlog reduction effort
* data quality
  * #201 AS-SET improvement, verification of data rather than free text field (epic)
  * #74 ASN info legacy fix on ixlan
  * #92 netixlan info sanitation fixes (epic)
  * #107 suggest facility option for users not owning the facility
  * #215 improve information provided to users trying to add facility to reduce erroneous data from being submitted to PDB
  * #121 allow users to delete all the information related to a network
  * #205 do not allow duplicate email accounts for users
  * #241 disallow duplicate IP address entry
  * #268 introduce unique constraints in the database, enforce integrity also on DB level
  * #277 enforce minimal information requirement for new IXP entries

* usability (search, visualisation & other)
  * #23 smarter search (epic)
  * #59 search for network at IX/FAC level
  * #38 recaptcha in China for Chinese networks
  * #98 name equivalence for searching (sanitize input to have better chance at finding a match)
  * #145 long IPv6 visualisation improvement
  * #259 fix typo
  * #261 URL to privacy policy in footer
  * #265 add capability for widgets (fetch data only when widget is expanded)
  * #270 isolate cookies for production/beta: easier testing by users

Facilitate development of tools by users:
* python client overhaul #158 (epic)

Stability & operations:
* #252 restart process when it is stuck
* #256 create a small test database to improve regression and release testing, also useful once PDB source is released for developers to test their changes against.
* #263 move whois service to whois.peeringdb.com
* #272 separate DB read/write connections in code to allow read-only operation and future clustering

Admin committee requirements:
* #137 search field for verification queue
* #262 adjust URL in facility creation email
* #303, #304, #305 IP tooling for admin committee

**Comment by arnoldnipper** [comment]
Is this still relevant?

**Comment by koalafil** [comment]
#66 is part of it too (nested in #23), which is pending ProductCom's decision. Once #66 is completed, we will be able to close this as all other issues are reported to be resolved and delivered within #313.

**Comment by arnoldnipper** [comment]
@mcmanuss8 and @koalafil please check if this issue is still relevant

**Comment by mcmanuss8** [comment]
consider this closed
