### ISSUE TITLE
PDB Self-hosted web-based Gettext editor

### ISSUE THREAD

**Issue by netravnen** [peeringdb/peeringdb#319]
Hi PeeringDB,

Would you mind looking into the options of using a 1) self-hosted 2) web-based Gettext editor for language translations done by the community and users of PDB **?** As an alternative to the current process of a) create PDB GH issue, b) wait for empty lang files to be added to repo, c) clone offline, d) edit lang files, e) commit and upload lang files, f) create GH PR, g) wait for PDB devs to merge PR.

I suggest screening the following options:
- http://pootle.translatehouse.org (Django, Python)
- https://weblate.org/ (Python, JS) (VCS integration supported)
- Others:
  - https://alternativeto.net/software/poedit/?license=opensource

**Comment by grizz** [comment]
Thanks! This has amazing potential, we'll have to look into it more and probably make it an epic.

Specifically, there are currently two po files, so we'll have to script set intersection, which should also make it a lot easier for translators. For efficiency, the JS files are done differently, so might have to play around with overriding how that's done.

I'm marking this as my June PC Candidate. :)

**Comment by arnoldnipper** [comment]
we are using weblate now via translate.peeringdb.com

**Comment by netravnen** [comment]
Already startet translating da_DK.

**Comment by arnoldnipper** [comment]
Will you be ready for DKNOG 9 :)
