### ISSUE TITLE
atomic sync

### ISSUE THREAD

**Issue by vegu** [peeringdb/peeringdb#32]
Currently there are still instances where sync can malfunction due to way updates are sent out via the since endpoint on the API.  While this is rare and avoidable by being vigilant about the data, having sync be atomic should fix this.

**Comment by vegu** [comment]
Issue #24 was caused by this problem

**Comment by mcmanuss8** [comment]
This is for the peeringdb sync to a db right? So a way to approach this would be to make temp tables that look like the prod ones, load the data into the temp tables, and then "rename table to table_old; rename table_temp to table; drop table table_old"
