### ISSUE TITLE
Typos in locale

### ISSUE THREAD

**Issue by ale84ms** [peeringdb/peeringdb#321]
Found some typos in django.po:

1) %(user_name)s's **afilliation** request has been approved
2) %(user_name)s's **afilliation** request has been denied
3) **Sepcifies** whether an ixp is allowed to add a netixlan entry for this network via their ixp_member data
4) Object of type '%(type)s' cannot be created because **it's** parent entity '%(parent_tag)s/%(parent_id)s' has not yet been approved
5) Object of type '%(type)s' cannot be created because **it's** parent entity '%(parent_tag)s/%(parent_id)s' has been marked as deleted
6) Has this object's latitude and longitude been syncronized to **it's** address fields
7) The email confirmation process for this email address has been terminated, please **re-initate**
8) User '%(u_name)s' created Network %(n_name)s AS%(n_asn)s (%(n_id)s) under **organzation** %(o_name)s (%(o_id)s).
9) As the user's email address was **succesfully** matched against RiR entry data this network has skipped the verification queue.
10) There was no entry in our database that matches that ASN, so it is likely that a network and **organzation** for it will need to be created.
11) These are the website addresses were able to derive from the **organzation** and **it's** entities
12) Your affiliation request to the Organization '%(o_name)s' and **it's** entities has been approved.
13) This was the result of a manual review of your affiliation request to the organization or one of **it's** entities.
14) All merges are processed manually by peeringdb support staff. If you think this action has been executed in error please **dont** hesitate to contact peeringdb support at

1, 2) "afilliation" should be "affiliation"
3) "Sepcifies" should be "Specifies"
4, 5, 6, 11, 12, 13) "it's" should be "its"
7) "re-initate" should be "re-initiate"
8, 10, 11) "organzation" should be "organization"
9) "succesfully" should be "successfully"
14) "dont"should be "don't"

**Comment by arnoldnipper** [comment]
but found no match with the requesting user. Here are the email addresses we **gatehered**

**Comment by vegu** [comment]
Merging From #333 

> Shouldn't "User %(u_name)s (%(u_email)s) wishes to be affiliated to ASN %(inst)s" read "User %(u_name)s (%(u_email)s) wishes to be affiliated to ASN %(asn)s"?

Also there was a case made that "affiliated to" should be "affiliated with":

> msgid "User is looking to be affiliated to these Organizations"
> msgid "User %(u_name)s wishes to be affiliated to your Organization"
> msgid "User %(u_name)s (%(u_email)s) wishes to be affiliated to %(o_name)s."
> msgid "User %(u_name)s (%(u_email)s) wishes to be affiliated to ASN %(inst)s"
> msgid "user %(user_name)s (%(u_email)s) wishes to be affiliated to Organization '%(o_name)s'"

**Comment by arnoldnipper** [comment]
@vegu, have these typos been sorted out meanwhile? If so, please close. If not, please fix and then close.

**Comment by tbaschak** [comment]
I was just about to make a PR to fix the "Sepcifies" typos and then found this issue... I'll try to find some time to fix some of these and make a PR to fix them all instead of just 1.

**Comment by arnoldnipper** [comment]
**Release note**

fixing a couple of typos

**Comment by grizz** [comment]
Fixed in #842
