### ISSUE TITLE
Typo in "Network Type" drop down

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/peeringdb#322]
For whatever reason "Not disclosed" now is "test Not Disclosed"

**Comment by vegu** [comment]
Error in the english locale, only affects the UI, fixed in 0c878b3.

**Comment by arnoldnipper** [comment]
In other fields as well
![20180602 peeringdb 00](https://user-images.githubusercontent.com/16888757/40880043-7ec7fc8a-66aa-11e8-949b-770aff89ba35.png)

**Comment by vegu** [comment]
This would affect any "Not Disclosed" value
