### ISSUE TITLE
Greek translation

### ISSUE THREAD

**Issue by daydr3am3r** [peeringdb/peeringdb#332]
Greetings,

I'd be happy to help out on translating peeringDB into Greek. Let me know what needs to be done to get this started :-)

**Comment by arnoldnipper** [comment]
@daydr3am3r  ... start here: https://docs.peeringdb.com/translation/

**Comment by daydr3am3r** [comment]
Forked and cloned. Should I just copy say the `pt` into a `gr` directory and start editing?

**Comment by arnoldnipper** [comment]
@daydr3am3r , @vegu will copy needed files

**Comment by vegu** [comment]
el_GR added
