### ISSUE TITLE
Typo?

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/peeringdb#333]
Shouldn't "User %(u_name)s (%(u_email)s) wishes to be affiliated to ASN %(inst)s" read "User %(u_name)s (%(u_email)s) wishes to be affiliated to ASN %(asn)s"?

**Comment by ghankins** [comment]
s/affiliated to ASN/affiliated with ASN/

**Comment by arnoldnipper** [comment]
Same here then probably 'msgid "This was the result of a manual review of your affiliation request to ASN"'

**Comment by arnoldnipper** [comment]
msgid "User is looking to be affiliated to these Organizations"
msgid "User %(u_name)s wishes to be affiliated to your Organization"
msgid "User %(u_name)s (%(u_email)s) wishes to be affiliated to %(o_name)s."
msgid "User %(u_name)s (%(u_email)s) wishes to be affiliated to ASN %(inst)s"
msgid "user %(user_name)s (%(u_email)s) wishes to be affiliated to Organization '%(o_name)s'"

**Comment by vegu** [comment]
Wonder if we should maintain a ticket with all grammatical errors and typos - currently there is this one and #321 - thoughts?

**Comment by arnoldnipper** [comment]
Makes sense imho ... so pls merge with #321

**Comment by vegu** [comment]
Merged to #333
