### ISSUE TITLE
Context for words in po file

### ISSUE THREAD

**Issue by mwtr** [peeringdb/peeringdb#334]
Japanese volunteer team is working on translating .po files to Japanese now.
But we don't know if some translations are suitable because we have no context information for them.
Can we have a place for testing our making .po file or something we can understand context?
Thank you.

**Comment by grizz** [comment]
We have a ticket that would allow for live translations, other than that, we have to push the changes to beta right now.

**Comment by mwtr** [comment]
Thank you for your responding. Let me translate whole to Japanese on po files firstly. After that I will request you apply po files on beta site.

**Comment by mwtr** [comment]
Translation to Japanese of django.po file is almost done on https://github.com/mwtr/peeringdb . I will create a pull request of it to peeringdb/peeringdb shortly after checking by Japanese volunteer members. I'd like you to apply it on beta site. If my understanding is wrong, please correct me. Thank you.

**Comment by grizz** [comment]
That's exactly right, thanks for all the effort!

**Comment by mwtr** [comment]
I have created a pull request to peeringdb/peeringdb. https://github.com/peeringdb/peeringdb/pull/345
Please apply them on beta site. I'd like to check words if they are suitable on context for them. Thank you.

**Comment by mwtr** [comment]
If you have any updates about schedule for applying po files on beta site, please let me know.

**Comment by netravnen** [comment]
@grizz Any updates on this one? The volunteers write to support@ they would like the translation to roll out on the beta site.

- https://github.com/peeringdb/peeringdb/pull/345
- https://peeringdb.deskpro.com/agent/#app.tickets,inbox:unassigned,t.o:19650,vis:5

**Comment by grizz** [comment]
This looks like it's all done, closing. Please reopen if it's not.
