### ISSUE TITLE
Prevent network names containing _only_ "ASN[0-9]+"

### ISSUE THREAD

**Issue by netravnen** [peeringdb/peeringdb#337]
Hi PeeringDB,

Would it makes sense to prevent network names containing ONLY "ASN[0-9]+" in the name**?** Both upon 1) initial network creation (from /profile page) and 2) when editing the network names under fx. /net/*

We agree on it not being a valid name for a network and should be prevented to be entered. Telling the user in an error message to fx. use the same name for both the network and org name.

**Comment by arnoldnipper** [comment]
@netravnen  ... these names come from the RIRs and are inserted by the ASNAUTO tool while automatcially creating the record.

The alternative is for AC to enter the network by **hand**
