### ISSUE TITLE
Improve IX-F JSON import to support import from protected sources

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/peeringdb#344]
Currently the importer is only able to import IX-F JSON schema from publicly accessible sources. However there is the situation that IX members don't want to be made publicly visible by the IX, but on the other hand list themselves as connected to that very IX.

Importing information from protected sources would solve this issue

**Comment by grizz** [comment]
@arnoldnipper is there a proposal on how to do this? I sent you some ideas in an email last week.

Moving to review for discussion.

**Comment by arnoldnipper** [comment]
@grizz , you are right. We have to come up with a new proposal how to handle the IX-F thingie. Does it make sense to have a new issue collecting all issues dealing with the IX-F importer?

**Comment by arnoldnipper** [comment]
@ccaputo maybe we have to take this into account for the DTF.

**Comment by ccaputo** [comment]
> @ccaputo maybe we have to take this into account for the DTF.

How so?

**Comment by arnoldnipper** [comment]
> How so?

That what the `net` tells and what the `ix` exports via the IX-F JSON will mismatch forever?

**Comment by ccaputo** [comment]
> > How so?
> 
> That what the `net` tells and what the `ix` exports via the IX-F JSON will mismatch forever until we have implemented an import from secured sources which do reveal complete information

I don't see how this would change things.

If it is already published, it can stay published.  Possible review by the Admin Committee to confirm if legitimate.

If it is new data, and doesn't match a public IX-F export, either a secure IX-F export mechanism will be needed, or Admin Committee intervention to make it public.

But to put into a document an idea that doesn't actually yet exist, doesn't make sense to me.  The DOTF policy document will hopefully provide guidance, but not handcuffs.

**Comment by arnoldnipper** [comment]
Not longer an issue as ixes are able to not disclose the IX-F JSON import URL
