### ISSUE TITLE
For IX-F import to accept all values listed in https://github.com/euro-ix/json-schemas/wiki/Schema-Field-Entries-Members

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/peeringdb#351]
Currently the script only accepts values `connected / active` as status of an IX member. All other values imply that the network is **removed** from the IX.

The schema definition however suggests following states to be used by an IX

* `connected` - connected and operating normally
* `notconnected` - physically not connected to the IXP due to some issue on the part of the IXP participant
* `disabled` - disabled by the IXP
* `quarantine` - connected to the IXP but in a quarantine state and not linked to the peering VLAN
awaiting-xconnect - both IXP and IXP participant ready for a connection, but waiting for a cross-connect from the colocation provider

In any case all states always imply that the network is a participant of the IX and may be listed in PeeringDB

**Comment by arnoldnipper** [comment]
There is no field in PeeringDB which corresponds to member_list.[].connection_list.[].state. Whatever the state is, the network is a member of the IX in question. Iow: this field is meaningless for PeeringDB.

In contrary what may happen is that netorks are removed from PeeringDB if the IX does not set state to active|connected.

In short: simply ignore `member_list.[].connection_list.[].state`

**Comment by arnoldnipper** [comment]
@vegu what was the reason to only accept `connected / active` ? As laid out, the value of `state` is completely irrelevant for PeeringDB as any network listed there is a legit IX participant.

**Comment by arnoldnipper** [comment]
As mentioned, regardless of the value of `state` **all** networks listed are legit members of the IX. Checking  `state` to match certain values does imho not make sense at all. Simply ignore this field.

**Comment by grizz** [comment]
@arnoldnipper So a reasonable solution would be to accept all entries except for `notconnected`, `disabled`, `quarantine`?

**Comment by arnoldnipper** [comment]
@matt, let's see what the proposal is we are working on

**Comment by arnoldnipper** [comment]
The current status of this discussion may be best described by

------------------------------- snip ------------------------------- 
A quick analysis gives

     25 "active"
      1 "active","inactive"
      1 "connected"
     31 null
      7 "operational"

I.e. most of the IXes providing information in IX-F JSON format don't
even set `state`. And there is only one IX which differentiates.

From this I would propose to either completely drop this field or make
it binary / enumeration (["active","inactive"]).
------------------------------- snap ------------------------------- 
From the discussion on tech-discuss@lists.ix-f.net

I would hence propose that the importer considers [ "active", null, "connected", "operational"] and [ "inactive"] to be equivalence classes. The first equivalence class means that the ASN is on the IX peering lan. The second one means that is not (yet|any longer) on the IX peering lan.

**Comment by grizz** [comment]
@arnoldnipper Thanks for finding this :)

I would propose taking it a step farther and having a set of words that remove it and everything else keep it added. So currently it would be `('inactive',)` means not on the IX, anything else means it is.

**Comment by grizz** [comment]
@peeringdb/pc please chime in quickly and we can get this changed this month

**Comment by mcmanuss8** [comment]
> @arnoldnipper Thanks for finding this :)
> 
> I would propose taking it a step farther and having a set of words that remove it and everything else keep it added. So currently it would be `('inactive',)` means not on the IX, anything else means it is.

Sounds good to me, let's move forward

**Comment by arnoldnipper** [comment]
> I would propose taking it a step farther and having a set of words that remove it and everything else keep it added. So currently it would be `('inactive',)` means not on the IX, anything else means it is.

We shouldn't **remove** an entry based on the setting of `state`. If the IX wants to have it removed, it simply does not list the entry anymore.  Records which are in the equivalence class of `inactive` are simply ignored/skipped. Makes sense?
