### ISSUE TITLE
Update ASNAUTO tool to use API key for LAC-NIC

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/peeringdb#353]
for LAC-NIC to retrieve full information an API-Key is needed. Hence the tool has to be updated.

**Comment by arnoldnipper** [comment]
This is already live, isn't it?

**Comment by vegu** [comment]
@arnoldnipper no it was rolled to beta today - have the lacnic lookups on live been working or something?

**Comment by arnoldnipper** [comment]
@vegu ... yes, that was my impression
