### ISSUE TITLE
Add filter to prevent adding IPs of other IXes

### ISSUE THREAD

**Issue by Cybertinus** [peeringdb/peeringdb#355]
Wouldn't it be an idea to add a filter to the webinterface of PeeringDB which prevents you from adding an IP address from IX A when you are defining sessions for IX B?
In other words: I can never add an IP address to my NL-IX sessions which is in the 80.249.208.0/21 range (AMS-IX IPv4 peering vlan range).
This filter should be added both for IPv4 and IPv6 offcourse.

**Comment by arnoldnipper** [comment]
Good idea ... and this already is in the pipeline and should be implemented with the next release.  Issues #282 and #277 deal with this. Does that cover what you have in mind?

**Comment by arnoldnipper** [comment]
fixed
