### ISSUE TITLE
Sorting by clicking table headers should use local-compare

### ISSUE THREAD

**Issue by kieber** [peeringdb/peeringdb#356]
Goto https://www.peeringdb.com/ix/87, under "Local Facilities" click table header "Facility"; sorting is case-independent, lower case "euNetworks" is before upper case "Level(3)".  Perfect.

Goto https://www.peeringdb.com/net/11967, under "Private Peering Facilities" click table header "Facility"; sorting is CASE-DEPENDENT, lower case "euNetworks" is AFTER upper case "Level(3)". Bummer.

Just sorting by ASCII values?  Not observing locale?  Just guessing.

**Comment by arnoldnipper** [comment]
@peeringdb/pc indeed, sorting should be done in natural order (sort -V). No?

**Comment by arnoldnipper** [comment]
+1

**Comment by shane-kerr** [comment]
Alternately we could use locale-aware sorting like @kieber suggests.

It should be relatively easy in Python, as the standard library has the `[locale.strxfrm()](https://docs.python.org/3.5/library/locale.html#locale.strxfrm)` and `[locale.strcoll()](https://docs.python.org/3.5/library/locale.html#locale.strcoll)` functions to help with this:
```python
>>> import locale
>>> locale.setlocale(locale.LC_COLLATE, "en_US.UTF-8")
'en_US.UTF-8'
>>> sorted(["Alpha", "aardvark"], key=locale.strxfrm)
['aardvark', 'Alpha']
>>> locale.setlocale(locale.LC_COLLATE, "C")
'C'
>>> sorted(["Alpha", "aardvark"], key=locale.strxfrm)
['Alpha', 'aardvark']
```
If we're doing this sorting in the browser, then JavaScript also provides support that we can use with the `sort()` method:
https://www.w3schools.com/jsref/jsref_localecompare.asp

Using locale-based sorting will sometimes give different results for other languages. For example until 2010 _**ll**_ (two L's together) was considered as a single letter in Spanish and sorted differently (my guess is that this is still true in some places where Spanish is spoken).

I don't know whether presenting things in the order specified by the localization of the user will help - or if it will add confusion when debugging - but my guess is that users would appreciate it.

**Comment by mcmanuss8** [comment]
I think we do sorting in the browser, so the localecompare method is what I think we'd do. +1 to @shane-kerr's proposal

**Comment by koalafil** [comment]
Can we have the Release Notes pls?

**Comment by arnoldnipper** [comment]
**Release Note**

Bugfix. Sorting now honours locale-sorting
