### ISSUE TITLE
IXP membership entries keep disappearing for AS43369 (MINAP RRs)

### ISSUE THREAD

**Issue by netravnen** [peeringdb/peeringdb#357]
Useraccount "md _at_ seeweb _dot_ it" complains about the [MINAP RRs][0] in [ticket 20503][1] _disappearing_ from the MINAP Internet Exchange.

Looking in the backend at [ASN 43369 (MINAP RRs)][0]. I can deduce what $USER is experiencing. But I am unable to go any level deeper and deduce what (automated?) action caused this to be the case. ($USER writes they initially had "Allow IXP Update" enabled for [43369][0]. But have disabled it now. And yes. The [MINAP RRs][0] is included in the [IX-F feed][2])
![image](https://user-images.githubusercontent.com/1938389/43834737-88524dc0-9b0f-11e8-9447-a1000cda59d5.png)

I assume a server and/or application log file may be able to reveal more details than what is available in the Admin Dashboard?

Could $OPERATOR go a level deeper and maybe provide more details about the above issue?

[0]: https://peeringdb.com/asn/43369
[1]: https://peeringdb.deskpro.com/agent/#app.tickets,filter:24,t.o:20503,vis:5
[2]: https://www.minap.it/members.json

**Comment by arnoldnipper** [comment]
Just look at https://peeringdb.com/cp/peeringdb_server/ixlanixfmemberimportlog/ to dive deeper into the issue. When looking there I see that the addresses where deleted as they are already in use somewhere else
![change ixf import log peeringdb](https://user-images.githubusercontent.com/16888757/43854210-80a4cb1a-9b42-11e8-9e32-3637f0527a04.png)

**Comment by netravnen** [comment]
Is it possible to deduce from `where` the duplicate address conflicts
originates from?

/Netravnen

**Comment by arnoldnipper** [comment]
curl -sG https://peeringdb.com/api/netixlan --data-urlencode ipaddr4__in=185.1.114.252,185.1.114.253 | jq '.data[] | [ .ix_id, .name ]'

should do the trick. But that query currently returns nothing

**Comment by arnoldnipper** [comment]
I've rolled back tonight's changes

**Comment by arnoldnipper** [comment]
Yes, we are in contact with them.  For more info see first line of this issue ;-)

**Comment by grizz** [comment]
@arnoldnipper I don't see any communication with MINAP there, am I missing it?

**Comment by rfc1036** [comment]
"Them" would be me: feel free to ask here if needed.

**Comment by grizz** [comment]
@rfc1036 Oh, hi :) You've monitored your output and it's stable / consistent? Is that coming from IXP Manager or a custom script?

I'll be able to take a closer look from our side in a few hours.

**Comment by arnoldnipper** [comment]
@grizz ... https://peeringdb.deskpro.com/agent/#app.tickets,filter:24,t.o:20503,vis:5

**Comment by grizz** [comment]
@rfc1036 The route servers in your JSON dump are listed as AS64725 but on PDB they are AS43369 -- that wouldn't work, which is it supposed to be?

**Comment by rfc1036** [comment]
They were recently renumbered, looks like I had missed updating the IXP manager entry, thank you. Hopefully this should solve the issue.

**Comment by grizz** [comment]
Good deal, let us know if you still see any problems.

**Comment by arnoldnipper** [comment]
Thanks, Mr. Eagle Eye
