### ISSUE TITLE
Lock ASN once the record is created

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/peeringdb#358]
Currently the record owner is able to change the ASN (still called "Primary ASN") of a net record. That does not make sense at all.

**Comment by eloos** [comment]
@arnoldnipper so how would that work if someone has a need to change ASN, but maintains all peerings? (I did 12573, 8195 => 6696, then 6696 => 8195, so there is a use case)

**Comment by arnoldnipper** [comment]
@eloos  ... not really, as with changing the ASN a lot of more records have to be changed like netixlans, netfacs where the ASN is coded in. So far changing the ASN has not yet happened. But already cases that users changed their ASN (for whatever reason). If there is a need to change the ASN while keeping the relations that would call for a tool (resp. manual intervention of 20C).

**Comment by grizz** [comment]
+1 from me

This really needs to happen for #111 and is essentially decided in favor for in #168

**Comment by arnoldnipper** [comment]
Summarize: Currently, the record owner is able to change the ASN (still called "Primary ASN") of a net record. That does not make sense at all.

Proposal: make the field read-only once the record is created. *And* rename the field to "ASB"

**Comment by shane-kerr** [comment]
+1

**Comment by koalafil** [comment]
@arnoldnipper Release Notes pls

**Comment by arnoldnipper** [comment]
**Release Notes**
Once a network has been created, the field `asn` is made read-only. As the ASN is unique there is no reason to change it.  Making the field read-only is to prevent unwanted side effects.
