### ISSUE TITLE
IX-F JSON import - Ignore routeserver setting if not present

### ISSUE THREAD

**Issue by mikehellers** [peeringdb/peeringdb#359]
Following a peeringdb ticket (PDB #00013169) related to on of our (LINX) members it has become clear that the current IX_F json importer seems to assume that if no routeserver fileds are present in an IX's json schema, it means that the corresponding network is not present at the routeserver, and as such the setting will be  unticked if the network has enabled  "Allow IXP Update"

I do not think that this is the correct behaviour. If no routeserver information is present in the IX-F json file, these entries should stay untouched even is "Allow IXP update" is enabled. Only if the routeserver entry is set to either true or false in the IX-F json file, the entry should be changed accordingly.

We (LINX) do not currently populate our json file with route server data, and as such I have for now removed the json entries from our IXP data in peeringdb. We will in parallel work on including the data, but I am sure the same problem exists for other exchanges.

On a side note: I tried to find details about what exactly is being used by the JSON importer, but could not find any details on the documentation pages. Could somebody point me to details if available?

Thanks,
    mike

**Comment by arnoldnipper** [comment]
@mikehellers , please see #237 for importing rules

**Comment by grizz** [comment]
@peeringdb/pc This needs votes, I'm tending towards +1, but not sure I understand why an IX-F schema would have the field be absent.

**Comment by arnoldnipper** [comment]
+1 ... if an IX is not providing an info, value is ignored. However for the IX-F importer to be useful I would argue that the IX has to provide all of the information PDB is requiring. I.e. ASN, IPv4, IPv6, speed, RS peering

**Comment by mcmanuss8** [comment]
I feel like the RS server field should be explicitly set to true or false, not left up to interpretation. This makes validation easier

**Comment by eloos** [comment]
Aren't there 2 use cases?
- network already at IX, IXP Update allowed ==> do not overwrite what user has set
- network not yet at IX ==> absence means no route-server, if the user then afterwards flags as being present we are in case 1

If IX provides the field, allow ixp update takes the information from the IX as authoratative

**Comment by arnoldnipper** [comment]
The interesting question is what to do when the IX doesn't specify RS information at all

**Comment by mikehellers** [comment]
If it is not specified at all by the IX (which is what triggered this request) the existing information should not be changed. Currently, the assumption seems to be if it is not specified at all means that the RS is not being used. Which is not the correct assumption. and results in correct data being removed.

**Comment by grizz** [comment]
@mcmanuss8 I agree, but that's something the json schema spec would have to solve.

I just looked over the schema spec, it's not required, so IX not sending the information is in spec. I'm definitely a +1 this is a bug and should be fixed.

@eloos yes, exactly, so if it's set, it will override, if it's not set it will leave it alone. By default on a new network at an IX, it would be off

**Comment by arnoldnipper** [comment]
@grizz ... the spec also only requires the ASN. If PeeringDB falls back to this minimum then the importer becomes almost useless imho. The idea behind the importer was to get rid of stale data (which would still be able with the ASN only) and to correct IP addresses

**Comment by mikehellers** [comment]
@arnoldnipper I am not sure anymore what the point of this discussion is. If the importer assumes that if fields (which are not required) are not present in the json file, the data will be removed, the result will be the IXPs will disable the import function as it removes data entered by the networks.
Which is what we have done, as really it is the only option we have.

The whole issues had been made much worse by the fact that we, as a user, were not even aware that data was being removed. This is another fundamental issue with the importer.

**Comment by arnoldnipper** [comment]
> The whole issues had been made much worse by the fact that we, as a user, were not even aware that data was being removed. This is another fundamental issue with the importer.

I fully agree, @mikehellers ... that's the reason we are currently re-specing the importer. Question: is there any specific reason LINX is **not** including the RS information?

**Comment by mikehellers** [comment]
We (LINX) are in the process of adding the RS information to our json files. The reason why it wasn't there is simple: It wasn't seen as a requirement initially by us, especially by the use case we knew of the json file. In addition, the information of which LINX member is using each one of our route servers was not available easily form any system, except directly from the route server configurations. This is by now different, as route server configuration are by now generated automatically, instead of being manually maintained. 
As such, for us (LINX) the problem will solve itself, and we will then re-enable the importer.
But, even though we have changed this, I am sure many, especially smaller IXPs will have similar issues with easy access to the data in order to automatically generated up to date json files.

**Comment by arnoldnipper** [comment]
> But, even though we have changed this, I am sure many, especially smaller IXPs will have similar issues with easy access to the data in order to automatically generated up to date json files.

Not sure I buy this as especially smaller IXPs are using IXP Manager nowadays. Rather larger IXPs have their own homebrewed provisioning system which does not necessarily have an IX-F JSON export feature.

That said, I guess a rock solid PeeringDB importer including comprehensive documentation should do

**Comment by arnoldnipper** [comment]
Will be fixed by the new importer, @mikehellers. See #474 and please check

**Comment by arnoldnipper** [comment]
Fixed with version 2.22.0
