### ISSUE TITLE
Spawn new window when clicking on URLs

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/peeringdb#360]
Currently the app opens the URL in same window you are in. Spawning a new window might come in more handy esp. when you want to open the documention window. Of course Ctrl-Click also would do, but ...

**Comment by eloos** [comment]
I think both documentation and external links are good uses of a new window

**Comment by mcmanuss8** [comment]
So docs.peeringdb.com is on a different hostname than www.peeringdb.com, so a general rule of leaving www.peeringdb.com => new window/tab works for me

**Comment by grizz** [comment]
@peeringdb/pc not a lot of votes on this, I'm a -1. I'm happy to move it to Backlog if we're doing commented majority.

**Comment by grizz** [comment]
@arnoldnipper old school purist I guess? ;) Browsers all have a way to open a link in a new window, which lets the user decide, when it's forced, the user has no control. Simple use case that annoys me, I middle click on a PDB link to open it in a new tab, I now have 2 PDB tabs, and I want to use the second one to follow the link off of PDB in that tab but it forces me to create a new one.

It's pedantic at best, and I'm certainly not a "normal" user, so my -1 shouldn't matter much in what happens.

**Comment by arnoldnipper** [comment]
@grizz ... the spec was to open an new window iff it's leaves www.peeringdb.com (which includes anything but https://peeringdb.com/{fac,ix,net,sponsors}/*)

So, whenever you are working on the DB, your window will stay. But if you leave the DB to lookup additional information. a new window would be opened.
