### ISSUE TITLE
Username retrieval non-existant email bug

### ISSUE THREAD

**Issue by vegu** [peeringdb/peeringdb#365]
When entering an email address that does not exist, and email is still sent - the link will contain no usernames, and be useless - it should send no email at all.

**Comment by leovegoda** [comment]
If the e-mail address is entered via the web form, is it possible to have the form do some minimal dynamic checking that the e-mail address is likely to exist, such as checking if the domain part is already associated with another account and if not, falling back to checking for an MX record, and an A record if there's no MX record?

**Comment by arnoldnipper** [comment]
"When entering an email address that does not exist"  means that there is no account with that email address. I guess we don't want to go down the road and do checks.

**Comment by arnoldnipper** [comment]
Moved through to 3a as this was identified as a bug by a developer. @pc, please speak up, if you oppose.

**Comment by vegu** [comment]
**summary**

- requesting a username retrieval should not send an email if the entered email doesn't exist in peeringdb as a user's email.

**Comment by vegu** [comment]
Unable to reproduce this anymore, possibly got fixed at some point in the past 3 years.
