### ISSUE TITLE
Remove regional from scope option

### ISSUE THREAD

**Issue by grizz** [peeringdb/peeringdb#37]
Will leave anything currently with regional as "Not Disclosed"

**Comment by arnoldnipper** [comment]
Please leave it as it is. By moving "regional" to "Not Disclosed" we definitely lose information

**Comment by karumugham** [comment]
I agree with Arnold. "Regional" isn't a good option, but we do lose data removing it. Some peering automation tools might use the "Regional" tag combined with IX locations/etc to approximate a network's geographical scope.

I think we should either leave it alone, or remove "Regional" as an option for new networks. (In other words, "Regional" would only appear in the dropdown if you already have it selected.)

**Comment by karumugham** [comment]
(Moved this back to New Issues to try to stick to our proposed workflow...)

**Comment by grizz** [comment]
Icebox is for discussion :)

Losing information from a value we all agreed was useless is probably a good thing. If not dropping it, we could change it to the region the company was based in or something, but then we are filling in information that may or may not be correct, so I'd think it makes more sense to just have it goto null.

**Comment by arnoldnipper** [comment]
There are quite a few networks flagged as "Regional" (36% == 2,500). Based on presence at IXP and / or facilities where we exactly know where they are I would try to "localize" them. I've done this matching to peering regions already implicitly when compilingthe statistics.

**Comment by grizz** [comment]
@peeringdb/pc I can't tell what the proposal even is on this one. As I recall, I created the issue based on emails from someone. Moving to review for more feedback.

**Comment by mcmanuss8** [comment]
Kill this until there's a better proposal

**Comment by arnoldnipper** [comment]
We had a lenghty discussion on it. Consensus was that "Regional" does not have a proper meaning. Even more: in this context it is simply worthless. All other values make sense.

**Comment by grizz** [comment]
@mcmanuss8 I agree on killing until there's a better proposal

@arnoldnipper I agree that it's useless to have because it has no clear definition, but it "seems" to work in some situations. You commented earlier in this thread to leave it as is, are you willing to come up with a good proposal for what to do with it?

We could leave scope as is and define a new field to use for a more modern use case.

**Comment by arnoldnipper** [comment]
@grizz, so far no one could explain to me what "regional" means

**Comment by eloos** [comment]
@arnoldnipper https://en.wikipedia.org/wiki/United_Nations_geoscheme I believe is a good overview, however it would mean that we need to replace Regional as tag with the actual region, which I believe makes sense. That being said, people may want to show activity in more than one region. Possibly it is more interesting to provide a search end-point/web query that allows users to search by region and return all the networks that have an IX presence/facility in said region

**Comment by arnoldnipper** [comment]
Having "Geographic Scope" (aka info_scope) more fine grained could make sense (e.g Europe/Nothern or Europe/Global or Global/Global)

Still leaves the fact imho, that currently "Reginal" is pointless

**Comment by grizz** [comment]
Let's leave it as-is, work on new field(s) that have defined meanings, and see what we come up with?

With a new field or fields, we can come up with ideas, implement, see the adoption level, and then prune as we see fit on version 3.

**Comment by arnoldnipper** [comment]
+1

**Comment by mcmanuss8** [comment]
Strawman proposal: Change Geographic Scope to a multi-select instead of a single select. From there you can pick either a list of continents or countries you operate in. Port all networks with "Global" to the list of continents. 

Examples:
Network 1: Europe, Africa, Middle East

Network 2: United States

Network 3: United States, Canada, Europe, South America, South Africa

**Comment by grizz** [comment]
@mcmanuss8 I love it!

**Comment by arnoldnipper** [comment]
@mcmanuss8  ... +1 ... but would you really go down to country level here. Could make the drop down a bit unwieldy

**Comment by mcmanuss8** [comment]
I think so. There's a large volume of Networks who only operate in one country. Making them pick a continent is a bit vague. 
If I, as a content delivery network, want to find networks who operate in $country, it's really hard to find them right now using peeringdb. You can use facility and ix info, but where they peer is not necessarily where their end users are.

**Comment by arnoldnipper** [comment]
Sure, being able to specify down to country level would be great. But maybe then we should use another interface to specify the choices. Something similiar to adding an IX / Facility and then being able to immediately see your choice before committing.

**Comment by mcmanuss8** [comment]
I agree, we'll need a better/different UI to handle it in this case.

**Comment by arnoldnipper** [comment]
Summarize: the value "Regional" in field "Scope" does not make sense. It was suggested to widen the values for "Scope", but then that should be handled in a new issue. 

Conclusion: remove value "Regional"

@peeringdb/pc, butt in if you don't agree.

**Comment by grizz** [comment]
What are we changing the networks that have regional to?

Let's make the following a new issue, and leave this in until it's done?

> Strawman proposal: Change Geographic Scope to a multi-select instead of a single select. From there you can pick either a list of continents or countries you operate in. Port all networks with "Global" to the list of continents.
> 
> Examples:
> Network 1: Europe, Africa, Middle East
> 
> Network 2: United States
> 
> Network 3: United States, Canada, Europe, South America, South Africa

**Comment by arnoldnipper** [comment]
+1 for a new issue. I've opened #691

**Comment by grizz** [comment]
Closing in favor of #691
