### ISSUE TITLE
Make Website mandatory for suggesting a facility

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/peeringdb#370]
Currently only "Name", "Adress1", "City" and "Zip-Code" are mandatory fields. Website also should be, whereas "Zip-Code" is debatable as there are countries which don't have zip codes.
![20180901 peeringdb 01](https://user-images.githubusercontent.com/16888757/44946884-dfa47780-ae04-11e8-980f-313f262300e0.png)

**Comment by grizz** [comment]
@peeringdb/pc no votes, +1 from me

**Comment by arnoldnipper** [comment]
If someone suggests a facility they also should add an URL to the service. Otherwise, AC has to hie Sherlock Holmes and Watson to find out what is meant.

@shane-kerr, may I have a +1. Of course, all the others of @peeringdb/pc are also invited to vote :)

**Comment by shane-kerr** [comment]
+1

I also agree that Zip-Code (I guess "postal code" everywhere but the US) may be optional. Someone even made a list of countries without postal codes:

https://gist.github.com/bradydan/e172c3f99e211e6e47ad84f08f83dfe3

**Comment by mcmanuss8** [comment]
+1 to requiring a website. Also +1 making zip/postal code optional, but maybe separate it into another issue if that's cleaner for 20C.

**Comment by grizz** [comment]
Cleaner and cheaper to keep it in this ticket. :)

**Comment by netravnen** [comment]
Hmm. I see it is still being worked on...

![image](https://user-images.githubusercontent.com/1938389/72682874-37af4d00-3ad2-11ea-909f-0c57a97892fa.png)

Thou, I really think this SHOULD be implemented. We write in our replies to applicants. That the Website field is **required** to be set a value. But we do not enforce it upon application approval.

![image](https://user-images.githubusercontent.com/1938389/72682972-611ca880-3ad3-11ea-887e-2793062428d2.png)

Another, more simpler option, is to note in the _comments field_, what fields is recommended the user inputs upon creating a facility application.

**Comment by egfrank** [comment]
@peeringdb/ac  Hello all, I'm currently working on this ticket. It seems like currently Zipcode is required in the Add Facility form and the Suggest Facility form, but not required in the Admin portal. 

Should it continue to be allowed to be blank in the Admin portal?

The changes to zipcode are also in development but no questions there as of yet.

**Comment by arnoldnipper** [comment]
@egfrank make it mandatory in /cp as well. And please note that not all countries do have [postal codes](https://en.wikipedia.org/wiki/Postal_code)

**Comment by arnoldnipper** [comment]
**Release note**

When registering a facility a website now is mandatory

**Comment by DarwinCosta** [comment]
Noted and makes sense.

Darwin-.

**Comment by alexfguimaraes** [comment]
Ack!


Alexandre
