### ISSUE TITLE
Clean up users in verification queue

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/peeringdb#371]
Currently there are 4540 users in the verification queue [0]. The oldest one from March 15, 2016, 12:48 p.m. While all other records (org, fac, net, ix) are worked on by AC, these records go unnoticed and only clog up the queue.

Proposal 1: automagically remove user records older than x days.
Proposal 2: x = 180

[0] https://peeringdb.com/cp/peeringdb_server/verificationqueueitem/

**Comment by grizz** [comment]
@peeringdb/pc This needs votes

+1 from me, it seems like a no brainer (and has AC tag)

**Comment by vegu** [comment]
if its completely useless to show those entries to the AC lets just remove them from the result as well.

can still do the user cleanup as well, but no reason to show there at all if they are just in the way.

@arnoldnipper thoughts?

**Comment by grizz** [comment]
@vegu makes a good point, let's just delete unverified users as well as the verification queue after X days

I think 14 would be fine, definitely not more than 90 IMO

**Comment by arnoldnipper** [comment]
Let's me dafe and go for 90. Running it quarterly then should do

**Comment by arnoldnipper** [comment]
**Wrap up**

  * 20C to write a tool to delete `user` entries older than 90 days from the so-called `verification queue` 

  * 20C/Ops to run this tool daily/weekly

**Comment by arnoldnipper** [comment]
+1

**Comment by arnoldnipper** [comment]
**Release note**

Unfinished requests are removed from the verification queue periodically
