### ISSUE TITLE
Wish to help to translate PeeringDB in Traditional Chinese.

### ISSUE THREAD

**Issue by ChiefWilliamLu** [peeringdb/peeringdb#372]
Hi Arnold and Friends from PeerinDB, 
This is TPIX William Lu. I hope I can help to translate PeeringDB with Traditional Chinese version. Please let me know how to do that. Thank you!
Have a nice day!
William

**Comment by vegu** [comment]
Hi @ChiefWilliamLu!

Thanks for your interest in helping with peeringdb translations.

Pardon my ignorance, but as i am not at all familiar with chinese i will need your help in clarifying some things. 

Currently we have setup a locale copy for `zh_CN` for **simplified chinese** - I assume the differences between simplified and traditional are big enough to warrant separate translations, correct?

If so, when looking up the codes for traditional chinese i found the following locale codes - which would be the appropriate one for the locale you are wishing to provide?

Language | LC | LCID
-- | -- | -- 
Chinese - Hong Kong SAR | zh | zh-hk 
Chinese - Macau SAR | zh | zh-mo 
Chinese - Singapore | zh | zh-sg
Chinese - Taiwan | zh | zh-tw

Thanks!

**Comment by ChiefWilliamLu** [comment]
Hi Stefan,

Yes, traditional Chinese is very different from simplified Chinese and is used by HK, Macau, and most people in SG.


And the locale codes should be “ Chinese - Taiwan

zh

zh-tw

Thanks for reaching out, and please let me know how to support in translation.

 

Regards,
 
William Lu
Mobile: +886 958188856

**Comment by vegu** [comment]
I have added the base files for **zh_TW** locale at https://github.com/peeringdb/peeringdb/tree/master/locale/zh_TW/LC_MESSAGES

Documentation on how to write translations and submit to the peeringdb repository can be found at https://docs.peeringdb.com/translation/ - let me know if you need more clarification.
