### ISSUE TITLE
make URL required for new objects

### ISSUE THREAD

**Issue by grizz** [peeringdb/peeringdb#374]
Including networks, facilities, and IXes in order to make it easier for the AC to verify records before approving.

**Comment by grizz** [comment]
@peeringdb/pc this has no votes, and will be a really quick fix

**Comment by arnoldnipper** [comment]
Then please implement with the monthly

**Comment by eloos** [comment]
can you elaborate on what this means? url what where? If it improves efficiency I am all for it, but I don't get it

**Comment by arnoldnipper** [comment]
@eloos ... Including networks, facilities, and IXes in order to make it easier for the AC to verify records before approving.

**Comment by vegu** [comment]
Facility.website is already required at this point so this leaves ...

** Summary **

- `Network.website` required during network creation
- `InternetExchange.website` required during internet exchange creation
