### ISSUE TITLE
On changing email address rescan open affiliation requests

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/peeringdb#375]
PeeringDB uses RDAP and Whois information from the RIR to authenticate requests. In order to allow for a minimum of authentication information from RIR and requestor's email address must match. If we detect a mismatch we ask the requestor to alter the  data or to have the owner approve the request.

It would help if on changing the email addess open affiliation requests for this users would be rescanned.

**Comment by grizz** [comment]
@peeringdb/pc no votes, +1 from me

@peeringdb/20c let's spec this

**Comment by mcmanuss8** [comment]
+1

**Comment by vegu** [comment]
**summary**

- when a user changes their email address re-evaluate any open affiliation request that the user has that are tied to an asn.
- re-evalulation will occur in the form of closing and opening new instances of such affiliation requests - this will cause a fresh scan of rdap data and new notifications to be sent out as well.
