### ISSUE TITLE
IXF Import: Validate Ip addresses in the IXF data before searching for matches.

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/peeringdb#376]
For PDB 2001:7f8:33::A120:4345:1 is different from 2001:7f8:33::a120:4345:1. Unfortunately when typing in 2001:7f8:33::A120:4345:1, PDB converts this to 2001:7f8:33::a120:4345:1.

Issues: IXes specifying literals in IPv6 addresses in upper case in IX-F will remove entries even if they are correct.

**Comment by vegu** [comment]
Ip addresses are handled via the python `ipaddress` module throughout the site and are validated/compared that way. 

However this is an issue with the IXF importer where ip addresses coming out of the IXF data are not validated the same way before being compared against the ip addresses in peeringdb.

To fix i propose: apply the same validation to Ip addresses in the IXF data before searching for matches.

**Comment by vegu** [comment]
As for the lowercasing that PDB does - this happens during validation and is intended behaviour.

I understand that ipv6 addresses are not case sensitive, but is there a reason to not have all of them lowercase? (missing validation in the ixf importer aside)

**Comment by arnoldnipper** [comment]
@vegu , the only reason I see is to not change customer data. But I guess that would cost extra work to store the address in the format the customer provided it. So I'm totally happy with lower case and in a compressed format

**Comment by vegu** [comment]
@arnoldnipper acknowledged

I reworded the title of this ticket to be more in line with the issue at hand. Additionally we went ahead and fixed this as we were looking in to it. It has been rolled to beta and will go out with the next release.

**Comment by mcmanuss8** [comment]
I agree it's sanest if we lower case and auto-compress IPv6 input given to us

**Comment by arnoldnipper** [comment]
Note:  currently IXP Manager does not allow to change the IPv6 address to lowercase. So one problem catches another :-(
