### ISSUE TITLE
beta.peeringdb.com seemingly not reachable on IPv6

### ISSUE THREAD

**Issue by TimStallard** [peeringdb/peeringdb#377]
I was the person originally affected by issue #376 - many thanks for the quick fix!

I noticed that I don't seem to be able to reach the beta site to test the fix. From a quick look, it looks like the site works over v4 but not v6. I'm connecting from an IPv6-only network (with nat64+dns64, but no fallback to v4) so I'm not able to access the site at all. Happy to provide traceroutes etc if others can't reproduce the issue.

**Comment by ccaputo** [comment]
Not sure why beta lost or didn't get its IPv6 address on last boot.  Rebooted it and it got it fine this time.  Thanks.

**Comment by ccaputo** [comment]
After a yum-update and full instance restart, I am seeing DHCPv6 updates properly working.  I think we are good.
