### ISSUE TITLE
recaptcha doesn't work in China

### ISSUE THREAD

**Issue by grizz** [peeringdb/peeringdb#38]
Which blocks the signup process. Should either proxy for Chinese addresses, or find a different captcha solution

**Comment by karumugham** [comment]
Definitely a valid bug, but something like a proxy for Chinese users seems like it might be too much effort to maintain. A different Captcha solution seems like it might be better. Either way, move to Icebox and work with devs to decide best solution to move to Backlog?

**Comment by arnoldnipper** [comment]
@vegu, could you please come up with a proposal

**Comment by vegu** [comment]
There are self hosted solutions we could use such as [captcha](https://captcha.com), which seems to be the most popular. 

Could serve the self hosted version for countries where re-captcha is blocked, or alternatively just replace re-captcha entirely. Personally i am in favour of the first approach, simply because re-captcha, when it is working, looks to be more user-friendly.

**Comment by arnoldnipper** [comment]
** Proposal **

Server self-hosted version for countries where re-capthca is blocked

**Comment by eloos** [comment]
@vegu how will we identify that a re-captcha was blocked and that we need to use the self-host captcha?

**Comment by vegu** [comment]
if it's blocked, the elements wont be loaded onto the page, it's fairly straightforward to then simply load which ever substitute we decide.

**Comment by eloos** [comment]
For the resolution of this ticket I vote in favour of option A, use self-hosted solution when re-captcha doesn't work

**Comment by job** [comment]
A - but we need to actually evaluate whether this actually fixes the issue

**Comment by arnoldnipper** [comment]
I vote for **Proposal A**

**Comment by mcmanuss8** [comment]
I vote A
or C if it's significantly less dev effort: Another 3rd party captcha that works for China (if any exist) but only gets used for China.

**Comment by kay23** [comment]
I vote for for option **B** to reduce the amount of external resources that get fetched and reduce tracking of our users.

**Comment by grizz** [comment]
@kay23 Normally I'd agree with you, except recaptcha is so much better than any self hosted alternative I've seen -- recaptcha is completely transparent to the user now, and typing in the image characters affects usability. Do you know of a better alternative?

**Comment by karumugham** [comment]
I also would prefer option B for consistency. But grizz makes a good point, recaptcha has great usability...I can't find an existing library that's nearly as full-featured, esp with having a simple checkbox in most cases. If we can't find a reasonable captcha library, then I think option A is better.

**Comment by fhibler** [comment]
I would prefer Proposal A, as Re-Captcha is in general doing a good job. But especially for China aren't we running in any issues with HTTPS anyways?

**Comment by nopedial** [comment]
I would prefer option **B** too but if Recaptcha is so much better then it's probably better going with option **A**.

**Comment by thatchrisp** [comment]
Option A seems to make the most sense.

**Comment by arnoldnipper** [comment]
**Proposal A** 6 in favour

Server self-hosted version for countries where re-captcha is blocked

**Proposal B** 2 in favour

Replace re-captcha entirely by a self hosted solution


So majority is for **Proposal A**

**Comment by grizz** [comment]
Got it, thanks.

**Comment by vegu** [comment]
This is on beta.peeringdb.com now - i confirmed that it's working there, but it would be good if we could get someone from the affected locations to check if the fallback works for them as well. thanks

**Comment by job** [comment]
i will reach out to chinese friends
