### ISSUE TITLE
Network type: Add "Government"

### ISSUE THREAD

**Issue by Antonio-Prado** [peeringdb/peeringdb#381]
Hi,

just saw that the Network type list doesn't show any Government related item (and no, Non-profit doesn't fit).
Could be possible to add Government to the list?

Thank you
--
antonio

**Comment by mcmanuss8** [comment]
This seems easy, makes sense to me. Only minor issue is updating all the translations. 
@peeringdb/pc  agree we should add it?

**Comment by grizz** [comment]
+1 from me

**Comment by eloos** [comment]
+1

**Comment by arnoldnipper** [comment]
+1

**Comment by grizz** [comment]
@peeringdb/pc any more votes?

**Comment by thatchrisp** [comment]
+1, good addition

**Comment by as44980** [comment]
+1, although should this cover other public and municipal authorities?

**Comment by arnoldnipper** [comment]
+1

**Comment by job** [comment]
+1
