### ISSUE TITLE
Add Oauth as a PeeringDB login method

### ISSUE THREAD

**Issue by mahtin** [peeringdb/peeringdb#383]
Presently PeeringDB uses it's own username/password database. This issue requests additional authentication methods for setting up a PeeringDB user. For example: [Google Identity](https://developers.google.com/identity/) or [Oauth2](https://oauth.net/2/).

Google provides [Oauth2 access](https://developers.google.com/identity/protocols/OAuth2) to it's API. PeeringDB should also follow that lead.

It is fully understood that this would mean updates to the UI, backend trust mechanism, and maybe the API.

It's possible that these days this is the same as asking for OpenID support (they aren't exactly the same - see [here](https://stackoverflow.com/questions/1087031/whats-the-difference-between-openid-and-oauth)).

Note: This is the opposite of the existing [Oauth](https://docs.peeringdb.com/oauth/) support that PeeringDB supplies.

**Comment by eloos** [comment]
I am undecided on this, peeringDB as OAuth provider seems to link *work* related activities across tools all nicely together, I am not too fond of creating links with tools which are typically considered in the private space.

**Comment by vegu** [comment]
We actually had done some work on this pre 2.0 release - so the logic / functionality is already mostly there - however it was never finalized and turned on - one of the reasons i recall was that having your email be related to your org/asn/fac/ix etc. was important for verification purposes and oauth through google or facebook seemed counterproductive to that approach.

**Comment by leovegoda** [comment]
@arnoldnipper What was the outcome of the Decide milestone?

**Comment by arnoldnipper** [comment]
@leovegoda, milestone "1 Decide" means that no decision is taken so far :)  So, A: nothing so far

**Comment by leovegoda** [comment]
> @leovegoda, milestone "1 Decide" means that no decision is taken so far :) So, A: nothing so far

Thanks!

**Comment by arnoldnipper** [comment]
@pc, those  of you who are deeper in this matter could you please comment

**Comment by arnoldnipper** [comment]
As this does not get traction, I'm closing this issue
