### ISSUE TITLE
It should be impossible to save an active entity under an entity that is marked as deleted.

### ISSUE THREAD

**Issue by vegu** [peeringdb/peeringdb#389]
There are currently several ways to run into this when editing objects in the /cp admin interface. Mainly due to the static nature of the forms in that environment.

One way to reproduce

- open edit network form in one tab
- do organization merge that moves that network to another org in second tab
- save network form in first tab (which still has the now deleted org selected)

The solution is to have the server error whenever an object is saved with a status != it's parent entity. The /api endpoints already do this correctly as far as i recall - just need to apply the same logic when objects are saved through the admin control panel.

**Comment by arnoldnipper** [comment]
Pushing through to 3a as this is identified as a bug by a developer. @pc, please speak up, if you disagree.

**Comment by vegu** [comment]
**summary**

- when creating or updating an object **disallow** the following status mismatches with its parent
  - parent is `deleted`: contained object is `ok` | `pending`
  - parent is `pending`: contained object is `ok`
- check that his behaviour is consistent in requests to the /api as well as the django-admin interface
