### ISSUE TITLE
Create IX entries from IX-F exports if network not registered in PDB at all

### ISSUE THREAD

**Issue by durkovic** [peeringdb/peeringdb#391]
As per discusion in #308 I'm creating a separate ticket.

If a network is listed in IX-F export as member of the IX, but no entry exists in PDB for this network, the record is discarded. In our IX, such situation accounts for 95% of missing entries.

While I understand that peeringdb historically preferred network-provided data,
with automation and unified json format in place at several IXPs, it's a pity
to just trash this data and don't use it for the community.

@grizz advised in #308 that in such case it might be possible to create simple network entry from RDAP and import the IX-F feed for this network.

In order to respect network's decision not be listed as member of an IX, this ticket only proposes to act if no record exists in PDB.

**Comment by arnoldnipper** [comment]
We should first reach consensus on PC ...

personally a +1 ... what do other PC members think?

**Comment by mcmanuss8** [comment]
Would be nice to have, but only if we can do it in such a way that it's clear the network entry was autogenerated and make it really easy for a network to take down such records or take ownership of them.

**Comment by grizz** [comment]
@peeringdb/pc any more votes?

**Comment by grrrrreg** [comment]
Trying to understand @mcmanuss8 what would be the ways that members of an IX could opt out of their records being shown in the IX-F object for that IX ?
Conceptually I would assume that it requires to have an Opt-in or Opt-out checkbox in every IX-F member IX's member admin page, but how does that get conveyed and implemented on a global scale?

**Comment by durkovic** [comment]
I don't think PeeringDB is the correct place to implement such opt-out.

IX-F exports are downloaded from IXP websites on daily basis by multiple entities, so implementing
opt-out just in PeeringDB will not have the desired effect - ISP will still be listed as IXP member at several other places.

If ISP doesn't want to be listed as member of particular IXP, it should IMHO contact the IXP and ask them to remove ISP's data from their IX-F export.

**Comment by arnoldnipper** [comment]
> If ISP doesn't want to be listed as member of particular IXP, it should IMHO contact the IXP and ask them to remove ISP's data from their IX-F export.

Exactly ... and this is what actually also happens. And we really have to be careful to ultimately trust the IX-F export files that all members are listed. I defintely know of one network which is in PeeringDB and also list itself as being connected at a certain IXP but does not want to be shown as an IXP member by that IXP.

**Comment by durkovic** [comment]
>  I defintely know of one network which is in PeeringDB and also list itself as being connected at a certain IXP but does not want to be shown as an IXP member by that IXP.

Well, publishing inconsistent information about itself at different places doesn't look like best practice and might confuse peering partners.

Actually, data inconsistency is the main problem I'm trying to discuss here. It's not uncommon, that PeeringDB only shows ~60% of connected members not because others actively opted-out, but because they don't want to register to "yet another portal". 

Let's take an example from IP space: once an ISP establishes contractual relation with e.g. RIPE, gets IP addresses & ASN from them and creates route objects, that info is automatically visible in RADB without any need for ISP's manual intervention.

So why not implement the same principle with peering info - ISP is in contractual relation with IXP, IXP is the authority which assigns IP addresses in peering LAN and operates route servers, so IXP is the native origin of authoritative info.

**Comment by ccaputo** [comment]
From [PeeringDB Data Ownership Policy Document](https://docs.peeringdb.com/gov/misc/2020-04-06_PeeringDB_Data_Ownership_Policy_Document_v1.0.pdf):

```
5.2.1) netixlan
[...]
• In order for "netixlan" data elements to be created by a Network or through automation
enabled by a Network, an Internet Exchange must first create related "ix", "ixlan", and
"ixpfx" data elements. Due to this dependency and a desire to prevent operational
disruption, this Task Force recommends in section 7 that "ix", "ixlan", and "ixpfx" data
elements not be able to be deleted or modified in such a way that would impact
dependent "netixlan" data elements.

• The "netixlan" data element includes a "net_id", which points to an "net" data element,
which includes an "org_id" with associated privileges. In addition, Networks may take
advantage of automated mechanisms that PeeringDB offers, which utilize data publicly
exported by Internet Exchanges.
```

Thus unless a network has 'Allow IXP Update' explicitly enabled, the Task Force Policy Document specifies that missing netixlan entries in the IX-F JSON export would not be created.

**Comment by arnoldnipper** [comment]
> Thus unless a network has 'Allow IXP Update' explicitly enabled, the Task Force Policy Document specifies that missing netixlan entries in the IX-F JSON export would not be created.

As the network is not yet registered with PeeringDB ist can't have set 'Allow IXP Update'. Thus close ticket as implementation would violate the Data Ownership Policy
