### ISSUE TITLE
Add folded sort into PeeringDB displays

### ISSUE THREAD

**Issue by mahtin** [peeringdb/peeringdb#397]
The sort order for Exchanges/Networks/Facilities should be case-insensitive. Presently lower-case entities are displayed at the end of a list. See https://peeringdb.com/search?q=London for example. 

<img width="388" alt="image" src="https://user-images.githubusercontent.com/4521085/49583160-2c1fb780-f90c-11e8-8535-a5be40f14039.png">

**Comment by arnoldnipper** [comment]
+1

**Comment by ynbrthr** [comment]
+1

@peeringdb/pc , another +1 is needed

**Comment by grizz** [comment]
I'm willing to be I'm one of the very few who expect that behavior :)

+1 anyway

**Comment by vegu** [comment]
Is this a request for all alpha numeric sorting on peeringdb or just for the quick search results?

Moving to 3a until clarification.

**Comment by mahtin** [comment]
My request is for all situations. Returned values, displayed results, etc. As they say “consistency is the mainstay of a working civilization”.

**Comment by arnoldnipper** [comment]
> Is this a request for all alpha numeric sorting on peeringdb or just for the quick search results?

**All** alpha-numeric sorting should be case-insensitive.

**Comment by vegu** [comment]
With the switch to an indexed search backend where results are now sorted by search score this issue is no longer relevant - there is however a new isues at #1050 that proposes a change back to alphanumeric sorting that if implemented should consider this ticket.
