### ISSUE TITLE
Obfuscate email addresses

### ISSUE THREAD

**Issue by zorun** [peeringdb/peeringdb#4]
It seems that currently, publicly visible email addresses are completely unobfuscated, which is very nice for spammers collection scripts.

It would be nice to at least attempt to obfuscate them (I don't know the state of the art, maybe javascript?).  Without that, I know I will never publish the contact information for my ISP as public.

**Comment by grizz** [comment]
I don't see a need for it, since email addresses are only shown for registered users if Visibility is marked private, something I'm not thinking of?
