### ISSUE TITLE
Fix out of office ticket spam

### ISSUE THREAD

**Issue by grizz** [peeringdb/peeringdb#40]
> 1. User A requests affiliation with record XYZ
> 2. An e-mail is sent to all admins (or even members???) of parent
>    organisation of XYZ with from address support@peeringdb.com
> 3. If this e-mail hits an ooo a reply is sent to
>    support@peeringdb.com
> 
> A decent header in the outgoing e-mails to the admin could prevent
> backscatter.

**Comment by arnoldnipper** [comment]
Is already addressed in https://github.com/peeringdb/peeringdb/issues/12 imho

**Comment by grizz** [comment]
Yes, but we need to review rfc3834 and make sure out of office is handled correctly as well, I believe user generated auto responses are supposed to follow the reply: path.
