### ISSUE TITLE
Notify a record holder when there is an automated change to the profile

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/peeringdb#403]
Every now and then it happens that a netixlan is deleted for whatever reason. In most cases this goes unnoticed to the record holder.  Notify a record holder when there is an automated change to the profile

**Comment by mcmanuss8** [comment]
+1 great idea

**Comment by fhibler** [comment]
I think notifications are key, when something in the profile has been changed through an automation, the record holder (all r/w in org?) should be notified by email (with opt-out capability) with the diffs being visible.

If we can agree on this being valid for all type of objects linked to an org, then +1 from me.

**Comment by vegu** [comment]
@peeringdb/pc some questions before estimation can be made

- is this to be estimated just for netixlans or all type of objects linked to an org
- allow opt out ? if so per network/fac/ix or at the org level?
- specifications on notification rate / spam avoidance (if any)

**Comment by arnoldnipper** [comment]
So far automated changes may only happen to `netixlan`. Right? Regarding notification, it could make sense to allow opt-in/out, i.e. to have a per user/network flag if they want to get a notification.  A per user/network/ix is out of scope IMO. Is rate-limiting needed?

**Comment by vegu** [comment]
rate limiting and opt in / out seems in part to be a policy decision , from a developers perspective we can offload the emailing to be outside of the main process, so its not as much a question about performance bottlenecking (at least i dont think itll be a problem) as it is about what users expect and agree to and receive from peeringdb in form of communications :)

i think you're right, netixlans are the only thing touched by auto updates at this point - once the ix-f importer is running again

**Comment by grizz** [comment]
@peeringdb/pc Still waiting to hear if it's opt in or opt out, and a definitive answer to which level should get notified.

**Comment by arnoldnipper** [comment]
Proposal:

 * opt-in
 * old_netixlan and new_netixlan

**Comment by leovegoda** [comment]
> rate limiting and opt in / out seems in part to be a policy decision , from a developers perspective we can offload the emailing to be outside of the main process, so its not as much a question about performance bottlenecking (at least i dont think itll be a problem) as it is about what users expect and agree to and receive from peeringdb in form of communications :)

Are users able to get a scheduled notification summary e.g. hourly, daily, or weekly depending on their specific needs?

**Comment by vegu** [comment]
**summary**

- implement notifications to users for automatic updates to objects they are watching 
- as `netixlan` is the only object type that receives automatic updates, this defines the scope of this ticket, but the system will be implemented so we can easily apply it to other objects should the need arise in the future.
- this system should be opt-in on a user/network basis
- emails should be consolidated (e.g., one email about the ix-f importer updating a number of netixlans instead of emailing for each netixlan)
- netixlan notifications should contain:
    - action taken (created, removed or modified)
    - exchange name, id and link
    - network name, AS and link
    - ipaddr4/ipaddr6 of netixlan being affected
    - reason for action

**Comment by vegu** [comment]
> Are users able to get a scheduled notification summary e.g. hourly, daily, or weekly depending on their specific needs?

I currently specified a general summarization that happens in the scope of the process that causes the automated updates. So the daily ix-f importer run. 

If we do need stuff like weekly reports as part of the scope of this ticket please move it back to 3a and lets clarify.
