### ISSUE TITLE
Get 504 when specifying both ASN and Organization

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/peeringdb#404]
When specifying both ASN and Organization when trying to affiliate to an organisation, the server takes quite  a while for processing and then throws a 504.

Reported by a user and verified by me
![20190114 peeringdb 00](https://user-images.githubusercontent.com/16888757/51100056-8269fb00-17d4-11e9-80c6-c8154473588d.png)

**Comment by vegu** [comment]
Unable to reproduce on dev environment
Able to reproduce on prod environment from the django shell

It's the RDAP lookup for 267729 getting stuck somewhere. Will update once i know more.

**Comment by ynbrthr** [comment]
> Unable to reproduce on dev environment
> Able to reproduce on prod environment from the django shell
> 
> It's the RDAP lookup for 267729 getting stuck somewhere. Will update once i know more.

@vegu , any update?

**Comment by leovegoda** [comment]
Do we have a status update on this?

**Comment by arnoldnipper** [comment]
Will re-open if we run into this issue again
