### ISSUE TITLE
Main is included in facility name

### ISSUE THREAD

**Issue by htj** [peeringdb/peeringdb#41]
Our system had some trouble figuring out a peering name. We got the following section (from https://www.peeringdb.com/api/net?asn=8757&depth=2 but not really important).

```
    {
      "id": 29439,
      "ix_id": 18,
      "name": "LINX LON1: Main",
      "ixlan_id": 18,
      "notes": "",
      "speed": 100000,
      "asn": 8757,
      "ipaddr4": "195.66.225.49",
      "ipaddr6": "2001:7f8:4::2235:1",
      "is_rs_peer": true,
      "created": "2016-07-06T14:27:11Z",
      "updated": "2016-07-28T09:26:47Z",
      "status": "ok"
    }
```

Both the network engineer and I are surprised about the the inclusion about :Main in the name.
If you go to https://www.peeringdb.com/ix/18 the main part is not included, so it seems like this introduces a new name, which is not intuitive.

Pleaser consider putting the information about main facility in a seperate field.

**Comment by arnoldnipper** [comment]
@htj ... if you look at https://www.peeringdb.com/ix/18 and look at the box "Peers at this Exchange Point" you see that information about the peering Vlan "Main" is included. This is what is reflected in what you post as well. 

There is a second Vlan on the same IXP which is called "Multicast" and which will show up with

 "name": "LINX LON1: Multicast",

Does that explain?

**Comment by htj** [comment]
My issue is that the API has changed wrt. to the format of facility names.

Further, there is a discrepancy between the facility names in browser interface and the API. This will only confuse people.

From an API design point-of-view, you have made a compound data structure inside a string. Having a separate field/attribute for "Main" / "Multicast" is a better way.

**Comment by arnoldnipper** [comment]
You are right that the documentation could be better. It does not say what "name" contains. What changed was that LINX decided to make clear that there are to vlans on the IXP LON1. One which is named "Main" and the other is "Multicast". 

And don't confuse representation via the GUI and the JSON.

The data structure of name is serializer.

Best advise is to use id's only. These will never ever change.
