### ISSUE TITLE
Add a "last synced at $date" to beta.peeringdb.com

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/peeringdb#410]
beta.peeringdb.com is using the account information data from peeringdb.com. However syncing from beta.peeringdb.com  is usually only done when testing requires it.

I.e. when users recently signed up they probably will not be able to log in to beta.peeringdb.com because beta.peeringdb.com and peeringdb.com are out of sync.

Adding information to when beta.peeringdb.com was synced last time improves usabilty

**Comment by eloos** [comment]
I think it is a good idea, but it doesn't solve the issue of beta.peeringdb.com not having the correct account info.
Should we have a separate infrastructure for beta testing vs. dev testing with test data?

**Comment by grrrrreg** [comment]
Does that mean that beta.peeringdb.com and peeringdb.com use a separate database that only gets refreshed opportunistically?
* If so, would it make sense to refresh it automatically periodically? (Disclaimer: I have no idea what #records we are talking about and what the stress of replication could be)
* is there a reason for beta. to not be the prod DB? (maybe this is also a stupid question so bear with me...)

**Comment by arnoldnipper** [comment]
> Does that mean that beta.peeringdb.com and peeringdb.com use a separate database that only gets refreshed opportunistically?
> 

yes

> * If so, would it make sense to refresh it automatically periodically? (Disclaimer: I have no idea what #records we are talking about and what the stress of replication could be)

Afaik 20C is working on it. From discussions with @grizz and @vegu I remember that we have to be careful not to break anything as beta may contain new features which are not supported by the old DB.

> * is there a reason for beta. to not be the prod DB? (maybe this is also a stupid question so bear with me...)

beta is used to test out new features. Hence it would be a bad idea to use prod DB for this.

**Comment by arnoldnipper** [comment]
@pc, please +1 or -1

**Comment by ynbrthr** [comment]
+1

**Comment by shane-kerr** [comment]
+1
