### ISSUE TITLE
404 on certain facilities

### ISSUE THREAD

**Issue by hengchai** [peeringdb/peeringdb#413]
Please check the facilities "Savvis Docklands" (733) and "Savvis sc9" (576). They're 404-ing and causing peeringdb sync to fail.

https://www.peeringdb.com/net/2740

https://www.peeringdb.com/fac/576
https://www.peeringdb.com/fac/733

**Comment by arnoldnipper** [comment]
This most likely came from an improperly restored network. Please try again

**Comment by hengchai** [comment]
Working now, thanks!
