### ISSUE TITLE
Handling of documentation and private ASN 

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/peeringdb#419]
Currently RDAP lookup for documentation and private ASNs are noit  handled separately by the ASNAUTO tool which prepopulates net and org records.

* Documentation ASN
    * RFC 5398
    * 16-Bit numbers: 64496 - 64511
    * 32-Bit numbers: 65536 - 65551

* Private ASN
    * RFC 6996
    * 16-Bit numbers: 64512 - 65534
    * 32-Bit numbers: 4200000000 - 4294967294

* for the production server
    * generate an error message that a documentation / private ASN was entered

* for the tutorial server
    * create a `net` and `org` record with name "AS$ASN" where $ASN is the ASN in question
   * Affiliation request is granted for the requesting email address and `user`

**Comment by arnoldnipper** [comment]
Please also add "last ASN"

* RFC 7300
   * Last ASNs
   * 16-bit number: 65535 
   * 32-bit number: 4294967295 

for both production and tutorial server create an error message as these ASN should not be used

**Comment by grizz** [comment]
Good call, should add AS_TRANS too (23456)

**Comment by arnoldnipper** [comment]
Sure

**Comment by arnoldnipper** [comment]
Looks like the code is buggy. Request for ASN 98764 just created a record and opened a DeskPRO ticket
![20190905 PeeringDB 00](https://user-images.githubusercontent.com/16888757/64341395-89a27b00-cfe8-11e9-8ded-0deff77a28f7.png)

**Comment by arnoldnipper** [comment]
Having a closer look I see that this issue does not cover ASN 65552-131071 which are also reserved

**Comment by job** [comment]
I added 65552-131071 in https://github.com/peeringdb/peeringdb/commit/14f798859612dae21dcbee48424152e3196c1330
