### ISSUE TITLE
ASNAUTO tool not working properly anymore

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/peeringdb#426]
![20190211 peeringdb 01](https://user-images.githubusercontent.com/16888757/52578296-3e463680-2e24-11e9-87b7-a579edcc7ada.png)
Sender: support@owentis.com
Email also listed in RDAP record: support@owentis.com 

Action: no auto aprroval, although email addresses match

**Comment by vegu** [comment]
On the requested by user line it shows that the email exists in our system with an uppercase S i am guessing the check we are doing is case sensitive.

Bug either way, but the tool should still work correctly otherwise.
