### ISSUE TITLE
Null `rencode` from facility

### ISSUE THREAD

**Issue by grizz** [peeringdb/peeringdb#431]
It is a legacy unused field, it should be nulled, made so it can't be edited, and removed in PDB3.

**Comment by grizz** [comment]
@peeringdb/pc any objections?

**Comment by jzp-github** [comment]
Aw man... Not re-allocated for testing? 

If you were running the RIPEDB I bet you'd yank POETIC-FORM & POEM! :-P

**Comment by grizz** [comment]
@jzp-github I'm not opposed to that :)

**Comment by grizz** [comment]
@peeringdb/pc Votes please!

**Comment by arnoldnipper** [comment]
+1

**Comment by shane-kerr** [comment]
+1

**Comment by mcmanuss8** [comment]
+1

**Comment by koalafil** [comment]
@grizz Release Notes pls

**Comment by grizz** [comment]
**Release Notes**
Null out all values for legacy unused `rencode` field, and make it read only to prepare for removal in PDB v3 (#625).
