### ISSUE TITLE
Translation missing and might be wrong

### ISSUE THREAD

**Issue by ghankins** [peeringdb/peeringdb#441]
https://www.peeringdb.com/net/694

When you are in “Netzwerke” there ist still says “Öffentliche Peering-Exchanges” even so “Exchanges” already have been translated to “Austauschpunkte”

It also says “Private Peering Facilities” and not “Private Peering Liegenschaften”

IMHO I would have translated facility rather to “Einrichtung” than “Liegenschaft”.

**Comment by arnoldnipper** [comment]
Maybe it's best to point users to https://translate.peeringdb.com and fix it there by themselves

**Comment by ghankins** [comment]
Some of these might have been broken during the rebranding.

**Comment by arnoldnipper** [comment]
If something still is not translated, please mention this on http://lists.peeringdb.com/cgi-bin/mailman/listinfo/pdb-translate
