### ISSUE TITLE
sponsor level in search results

### ISSUE THREAD

**Issue by ccaputo** [peeringdb/peeringdb#449]
Right now the sponsor CSS badges only show up on result pages.  Since it was originally envisioned, and because a sponsor recently reignited the idea, the board and I as Secretary/Treasurer would like a quote to see how much it would cost to expand these badges to be present in search results (both quick search and advanced).

In addition, right now there is a bug in that the line with the sponsor badge on sponsor pages is an unexpected hyperlink to the https://www.peeringdb.com/sponsors page, when only the badge itself should be a link.  Clicking on the sponsor name should not result in a jump to another page.

**Comment by mcmanuss8** [comment]
Let's split these into two separate asks. #452 for the second one. Keeping this one for the sponsor level in search results
