### ISSUE TITLE
Adjust text size and color after rebranding

### ISSUE THREAD

**Issue by ghankins** [peeringdb/peeringdb#450]
https://twitter.com/damianzaremba/status/1102502749348995073

The black text on a light grey background is really hard to read in the new branding, especially with small text :(

![inked20190305 peeringdb 00_li](https://user-images.githubusercontent.com/8171907/53855580-32214500-3f9c-11e9-88e5-3ee3864762ac.jpg)

**Comment by mcmanuss8** [comment]
Does making the black more...black help? ex: is #000000 better than #00203e? See attached.

If not, lightening the grey might help more.

![Screen Shot 2019-03-08 at 4 43 01 PM](https://user-images.githubusercontent.com/5892502/54057648-7fcac700-41c1-11e9-8ded-90c9fdc53a3d.png)
![Screen Shot 2019-03-08 at 4 42 55 PM](https://user-images.githubusercontent.com/5892502/54057649-7fcac700-41c1-11e9-8d51-0f7f56f8c245.png)

**Comment by ghankins** [comment]
It was grey instead of blue, and I made it bigger.

**Comment by ghankins** [comment]
You can check dev0.peeringdb.com right now.

**Comment by arnoldnipper** [comment]
is this still an issue, @ghankins. If not, please close it

**Comment by ghankins** [comment]
This was fixed last year.
