### ISSUE TITLE
Make all records available via API regardless of status

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/peeringdb#451]
PeeringDB records may have "status"  ["deleted","ok", "pending"]. Currently only records with "status" "ok" are shown.

However when you want to do statistics you will miss those with "status" "deleted" (and "pending").

**Comment by grizz** [comment]
I'm not sure on allowing pending, deleted maybe?

@peeringdb/pc What do you think?

**Comment by mcmanuss8** [comment]
I think deleted would be good to show. I'm also iffy on showing pending, might be bad data there. I could be convinced with a good use case though

**Comment by arnoldnipper** [comment]
`pending` means this record is currently been worked on by AC. There is nothing iffy imho. The record will then change status to `ok` or been removed, i.e. **not** change to `deleted`.

So a record first always is `pending` even if not visible that long in this status or explicitly shown. Then it will either be approved which changes status to `ok` or denied which will remove the record.

Once approved status may change to `deleted` and from there again to `ok`.

So `pending` indeed may not be needed.

**Comment by mcmanuss8** [comment]
@arnoldnipper  I guess my point was someone could submit bad data, it goes to pending, AC reviews it, then drops it because it was bad. It might be saner if we just never showed people data the AC hasn't reviewed. I'm not familiar enough with the kind of data you end up dropping in the AC to say if that's a serious risk or not

**Comment by arnoldnipper** [comment]
> I guess my point was someone could submit bad data, it goes to pending, AC reviews it, then drops it because it was bad. It might be saner if we just never showed people data the AC hasn't reviewed. I'm not familiar enough with the kind of data you end up dropping in the AC to say if that's a serious risk or not

Could you be more specific what you mean by risk? From my AC pov it would be nice to also have the pending records as I then can easily scan my workload and eventually also get rid of outdated records

**Comment by grizz** [comment]
The more I think about it, I think `pending` should be completely internal, we have no control over the data and it has no benefit to users.

**Comment by arnoldnipper** [comment]
> The more I think about it, I think `pending` should be completely internal, we have no control over the data and it has no benefit to users.

+1

**Comment by grizz** [comment]
So let's add a flag for the query `status` and one does `status=deleted` it only shows those records? By default it would be "ok"

I'm on the hotseat this week @peeringdb/pc -- let's get some decisions going! :)

**Comment by arnoldnipper** [comment]
> So let's add a flag for the query `status` and one does `status=deleted` it only shows those records? By default it would be "ok"

+1

**Comment by arnoldnipper** [comment]
> So let's add a flag for the query `status` and one does `status=deleted` it only shows those records? By default it would be "ok"

Wrong issue???

**Comment by arnoldnipper** [comment]
Has been implemented
