### ISSUE TITLE
Org/Network name of a sponsor should not link to /sponsors, only the sponsor badge should

### ISSUE THREAD

**Issue by mcmanuss8** [peeringdb/peeringdb#452]
@ccaputo  writes in #449:

> In addition, right now there is a bug in that the line with the sponsor badge on sponsor pages is an unexpected hyperlink to the https://www.peeringdb.com/sponsors page, when only the badge itself should be a link. Clicking on the sponsor name should not result in a jump to another page.

**Comment by ccaputo** [comment]
Can this get some love please?  Also, why the "Board" tag?  Thanks!

**Comment by arnoldnipper** [comment]
Summarize:  the line with the sponsor badge on sponsor pages is an unexpected hyperlink to the https://www.peeringdb.com/sponsors page, when only the badge itself should be a link. Clicking on the sponsor name should not result in a jump to another page.

@peeringdb/pc , please make up your mind.

**Comment by grizz** [comment]
Looks like a clear bug to me, +1

**Comment by mcmanuss8** [comment]
Ditto +1

-Steve
(from iPhone - expect typos)

**Comment by shane-kerr** [comment]
+1 

I'm not sure it's actually a problem, but seems like a simple change and might avoid some confusion.

**Comment by arnoldnipper** [comment]
Supported by @shane-kerr, @mcmanuss8, @grizz and @arnoldnipper

**Comment by arnoldnipper** [comment]
**Release note**
This is a bug fix. From now on only when clicking on the sponsor badge will direct to the sponsor page
