### ISSUE TITLE
Route-server URL starting with ssh://

### ISSUE THREAD

**Issue by alarig** [peeringdb/peeringdb#462]
Hi,

We can’t use SSH for a routes server URL, only HTTP(S) and telnet are supported, with 'ssh rviews@lg.grifon.fr' the regex doesn’t validate.

**Comment by arnoldnipper** [comment]
Adding ssh as protocol definitely makes sense, @peeringdb/pc. What's your opinion? Currently telnet, http and https are supported.

**Comment by shane-kerr** [comment]
+1

Although the SSH URI is not standardized, it is used. If there are route servers only using SSH then it makes sense.

**Comment by job** [comment]
+1

The `SSH` URI is registered in IANA's registry though.

Here are two patch proposals that could be merged if the PC agrees on the functionality:

https://github.com/peeringdb/django-peeringdb/pull/34
https://github.com/peeringdb/peeringdb/pull/617

**Comment by mcmanuss8** [comment]
+1

**Comment by grizz** [comment]
+1 -- and it should be done in django-peeringdb imo (for others who build things, and it's the base)

However, neither PRs have passing tests.... :)

**Comment by grizz** [comment]
@job get the tests passing in your django-peeringdb PR please :)

**Comment by job** [comment]
the thing is passing tests. would you mind taking a look to whether you
agree with the implementation choices?
