### ISSUE TITLE
Add new network type for networks that provide network services

### ISSUE THREAD

**Issue by mcmanuss8** [peeringdb/peeringdb#463]
Covers networks that offer network-centric services. Some examples:

DNS, NTP, Whois, RDAP, DDOS protection

**Comment by arnoldnipper** [comment]
Any suggestion for a name, @mcmanuss8 ?

**Comment by mcmanuss8** [comment]
"Network Services" ?

**Comment by arnoldnipper** [comment]
Merge with #381?

**Comment by mcmanuss8** [comment]
No on merging (different network use cases), but they should definitely be done at the same time!

**Comment by mcmanuss8** [comment]
Summary:  Add a new network type of "Network Services" to the dropdown of Network Type. Do at the same time as #381 to simplify work for developers

@peeringdb/pc  votes please

**Comment by arnoldnipper** [comment]
+1

**Comment by ynbrthr** [comment]
+1

**Comment by ynbrthr** [comment]
Shouldn't we include a short description text for each field? To avoid or limit misclassifications. E.g. for #463, "Covers networks that offer network-centric services. Some examples: DNS, NTP, Whois, RDAP, DDOS protection" would provide some clarity in what is intended here with that type.

**Comment by grizz** [comment]
+1 -- agree we should add some help text for each type however

**Comment by arnoldnipper** [comment]
+1, @ynbrthr ... however, this should be a new issue. Would you mind to open one, @ynbrthr :)
