### ISSUE TITLE
Improve information text at "Manage" section for "Add IXP" and "Add Exchange"

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/peeringdb#47]
A lot of users don't get it that this section is only to add _own_ facilities, networks and IXPs. So, please make clear that this section is only there to add records you own.

For Exchanges please also add the information that the Exchange will only show up in the search list for adding IXP if the organisations has provides ixlan information as well

**Comment by vegu** [comment]
Can you provide the exact description you would like us to put there, thanks

**Comment by arnoldnipper** [comment]
same as #215
