### ISSUE TITLE
New IX-F JSON importer procedure

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/peeringdb#474]
In #351 there is a lot of discussions on how to properly import IX-F JSON files. There are two issues basically

* how to act on `state` or to disregard it at all

* what to do if fields differ, e.g. customer set  is_rs_peer to `true`, IX set it to `false`

Completely ignoring seems not to be wise as some IXes are using `"state": "inactive"` for whatever reason.  Ignoring this state could hence lead to creating a netixlan for this ASN.

Hence we are defining two equivalence classes based on the values currently seen.

* Act on class
  * `state` is in [ null, "active" "connected", "operational"]
  * on "Allow IX update" == "true"
     * create the netixlan if it didn't exist
     * modify the netixlan if it exist and differs
     * noop else
  * on "Allow IX update" == "false"
    * delete the netixlan iff there is a mismatch in the triple (asn, ipaddr4, ipaddr6)

* Ignore class
  * `state` is in ["inactive"]
  * on "Allow IX update" == "true" a netixlan is not created
  * noop on any existing netixlan

Now we still have to define what to do with ASN which are in the IX-F JSON import and not in PeeringDB and vice versa.

* if an ASN is in the IX-F JSON import and not in PeeringDB
  * noop

* if an ASN is not the in IX-F JSON import, but is in PeeringDB
  * delete the netixlan

**Comment by grizz** [comment]
@arnoldnipper want to change how member types are acted on now as well?

It currently allows `peering`, `ixp`, `routeserver`, and `probono`
￼

**Comment by arnoldnipper** [comment]
According to the latest version, it's now

member_type": {
              "description": "Participant type: peering, ixp, pro bono, routeserver or other",
              "type": "string",
              "enum": ["peering","ixp","other"]
}

From an importer pov I don't see that it would make sense to act differently on the member_type. Do you?

**Comment by grizz** [comment]
I don't think it makes sense to operate differently based on member type either.
