### ISSUE TITLE
10terabit isn’t realistic (presently) 

### ISSUE THREAD

**Issue by mahtin** [peeringdb/peeringdb#475]
PeeringDB presently accepts 10T as a value for public peering port speed. This (at least in 2019) seems unrealistic. This field should have range checking. 

https://www.peeringdb.com/net/19515

Unless the network mean 10base-T (which is a thing!).

**Comment by mcmanuss8** [comment]
Agreed, let's kill it (for another few years at least :))

**Comment by arnoldnipper** [comment]
> PeeringDB presently accepts 10T as a value for public peering port speed. This (at least in 2019) seems unrealistic. This field should have range checking.

@mahtin , that is not public peering port speed but traffic level. And 10+ Tbps perfectly makes sense Right? Close the issue?

**Comment by arnoldnipper** [comment]
@mahtin shouldn't we close this?

**Comment by stillwaxin** [comment]
This does appear to be an issue. User configured his port speed to 10T not his network agg traffic levels. Prolly should be range checking this or even have the IXP be able to specify what port speeds are actually available to choose from.

**Comment by arnoldnipper** [comment]
With 400GE ports being around and the ability to have 32 ports in a LAG, 10T would theoretically be possible.

However, I totally agree that sanity checking should be done somehow.  That's what we currently see

`curl -sG https://peeringdb.com/api/netixlan --data-urlencode fields=speed | jq -c '[.data[] | .speed] | unique'
[0,1,2,3,4,5,10,15,20,25,30,34,40,45,50,60,70,80,100,112,150,155,200,250,300,310,350,400,500,600,622,700,750,800,850,900,1000,1024,1084,1200,1250,1300,1500,2000,2048,2049,2200,2500,3000,3072,3096,3500,4000,4096,5000,5120,5200,5500,6000,6144,7000,7500,8000,8192,8500,9000,10000,10024,10240,10480,11000,15000,17000,20000,20480,25000,30000,30720,40000,50000,60000,70000,75000,80000,90000,100000,110000,120000,130000,140000,150000,180000,200000,240000,290000,300000,370000,400000,500000,600000,800000,1000000]`

Maybe there should a warning when setting the speed higher than 1T

**Comment by as44980** [comment]
Could it be worth allowing the IX operator to specify the maximum capacity they can support, potentially in terms of the interface speed and supported lag members, and then sanity checking any user submitted data against that?

**Comment by arnoldnipper** [comment]
Actually, I can't see the use case. So what are people use this field for?  Theoretically, we could add max_capacity to the ixlan record and then check each new netixlan against this value.

My vote: -1

**Comment by netravnen** [comment]
> Maybe there should a warning when setting the speed higher than 1T

If IXP has JSON export activated. Speed entered for user network could be checked against IXP listed valued for validity of data entry?

**Comment by arnoldnipper** [comment]
See #481 for a more general solution

**Comment by arnoldnipper** [comment]
Implemented in #481
