### ISSUE TITLE
Requirements for adding a netixlan record

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/peeringdb#480]
Now that all IXes have at least one ixlan and at least one IPv{4,6} ixpfx per each ixlan we should start to check additions to an ixlan.

 * Field "asn" *MUST" be set
 * If the ixlan has an ixpfx.protocl == "IPv4" an ipaddr4 
   * MUST be set or
   * SHOULD be set
 * If the ixlan has an ixpfx.protocl == "IPv6" an ipaddr6
   * MUST be set or
   * SHOULD be set
 * If ipaddr{4,6} is set, it MUST match the ixlan
 * Fields "speed" and "is_rs_peer" SHOULD be set

**Comment by netravnen** [comment]
I prefer

- Field "asn" *MUST" be set
- If the ixlan has an ixpfx.protocl == "IPv4" an ipaddr4
  - *MUST be set or*
  - SHOULD be set
- If the ixlan has an ixpfx.protocl == "IPv6" an ipaddr6
  - *MUST be set or*
  - SHOULD be set
- Fields "speed" and "is_rs_peer" SHOULD be set

**Comment by arnoldnipper** [comment]
@netravnen I'm unsure what your choice is. It would be clear if you simply omit where there is an alternative

**Comment by grizz** [comment]
+1 for SHOULD

**Comment by mcmanuss8** [comment]
Agreed, SHOULD for both IPv4 and IPv6

We should validate that any IPs specified are within the CIDR ranges defined though if that's not already done...

**Comment by arnoldnipper** [comment]
After our discussion, +1 for SHOULD. 
@mcmanuss8 checking is not yet done

**Comment by mcmanuss8** [comment]
@arnoldnipper  do we have another issue for checking? If not, let's make one

**Comment by arnoldnipper** [comment]
> @arnoldnipper do we have another issue for checking? If not, let's make one

Not sure what you mean, @mcmanuss8

**Comment by mcmanuss8** [comment]
> > @arnoldnipper do we have another issue for checking? If not, let's make one
> 
> Not sure what you mean, @mcmanuss8

Is there another github issue tracking the addition of validation logic (ensuring a given IP for an IX member falls within the CIDR(s) of an IX)?

**Comment by arnoldnipper** [comment]
> > > @arnoldnipper do we have another issue for checking? If not, let's make one
> > 
> > 
> > Not sure what you mean, @mcmanuss8
> 
> Is there another github issue tracking the addition of validation logic (ensuring a given IP for an IX member falls within the CIDR(s) of an IX)?

Not that I'm aware of. That was the reason to create this :)

**Comment by arnoldnipper** [comment]
Integrated #488

**Comment by eloos** [comment]
So conclusion of this issue is that we won't force people to fill this field, but if they fill it (#488) that we will validate that it is correct?

**Comment by arnoldnipper** [comment]
The conclusion is, that networks only have to provide an ASN. But be **aware** if the IX provides an IX-F JSON URL and the network has set `allow_ixp_update = "no"` entry will be removed if it differs in (ASN, ipaddr4, ipaddr6). So it is highly recommended to exactly set the entry according to what the IX specifies.

**Comment by arnoldnipper** [comment]
To summarise and bringing it forward. Support at least from @eloos @grizz @mcmanuss8 and @arnoldnipper 

Now that all IXes have at least one `ixlan` and at least one IPv{4,6} `ixpfx` per each `ixlan` we should start to check additions to an `ixlan`.

 * Field `asn` **MUST** be set
 * If the `ixlan` has an `ixpfx.protocol` == "IPv4" `ipaddr4` **SHOULD** be set
 * If the `ixlan` has an `ixpfx.protocol` == "IPv6" `ipaddr6` **SHOULD** be set
 * If ipaddr{4,6} is set, it **MUST** be within the correspondant `ixpfx` range
 * Fields `speed` and `is_rs_peer` **SHOULD** be set

@koalafil please include in next call

**Comment by grizz** [comment]
It's already implemented this way. :)

**Comment by arnoldnipper** [comment]
> It's already implemented this way. :)

**it isn't** 

![20200317 PeeringDB 00](https://user-images.githubusercontent.com/16888757/76827615-8dc51600-681f-11ea-9828-419671c82ef8.png)

**Comment by grizz** [comment]
@arnoldnipper I'm not following

> Now that all IXes have at least one `ixlan` and at least one IPv{4,6} `ixpfx` per each `ixlan` we should start to check additions to an `ixlan`.

It requires ipv4 or ipv6, which is 1 ixpfx, right?

**Comment by arnoldnipper** [comment]
Unfortunately, [consensus was](https://github.com/peeringdb/peeringdb/issues/480#issuecomment-546674439) that a `netixlan` object doesn't have to have an IP address set at all.  Right, @grizz?

**Comment by grizz** [comment]
I think I misread it or made a false assumption, it should have an added:

one of ipaddr{4,6} MUST be set.

I don't see a reason to ever have an ixlan that doesn't have one IP prefix, my main concern with saying SHOULD was that there could be IXes with just one of the two. Am I missing a use case?

Since that's the way it currently is, if we made it so you could have an `ixpfx` without an actual IP prefix, I feel like we'd be going backwards as far as data quality is concerned.

**Comment by arnoldnipper** [comment]
@grizz, @peeringdb/pc talked long about this issue. And I'm all with you that at least **one** of ipaddr{4,6} **MUST** be set. However, the consensus was different. I'n not a native AE/BE speaker. Perhaps, I misread and would be happy. And I +100 your reasoning.

But, what to do now?

**Comment by arnoldnipper** [comment]
@grizz and @vegu do you agree that we can close this issue here and it will be fixed in #697? Is that fine for @peeringdb/pc, too?

**Comment by grizz** [comment]
#697 does not allow for netixlan to not have *either* IP address, one of v4 or v6 still must be set.

I'm -1 on not requiring any IP address, and it went to MS3 before we clarified. I think we need another vote? @peeringdb/pc

**Comment by arnoldnipper** [comment]
> #697 does not allow for netixlan to not have _either_ IP address, one of v4 or v6 still must be set.

But it should, @grizz and @vegu. See the implementation discussions we had. This definitely referred to this ticket. I also can't help, but @peeringdb/pc decided, that just an ASN is fine.

**Comment by arnoldnipper** [comment]
@pc, there are good reasons to reconsider this (esp. @job). We decided that a `netixlan` only needs to have `asn` set. However, it seems that at least one IP would be really useful. Otherwise, it's really, really hard - if not impossible - to match IX-F JSON entries to `netixlan`. Please make up your mind!

**Comment by vegu** [comment]
From a developer's perspective it would be helpful to understand the use-case behind netixlans with nulled ipaddresses. 

Currently a netixlan is uniquely identify-able by it's ip4,ip6 tuple. In the case of both ipaddresses being nulled, do we also consider that a unique netixlan (in combination with it's asn)? e.g., would a network be limited to one netixlan with nulled ip-addresses per ixlan, or would they be allowed to create as many of those as they want / need ?

> > #697 does not allow for netixlan to not have _either_ IP address, one of v4 or v6 still must be set.
> 
> But it should, @grizz and @vegu. See the implementation discussions we had. This definitely referred to this ticket. I also can't help, but @peeringdb/pc decided, that just an ASN is fine.

I think this got lost in communication, i remember/understood that discussion as considering the implications not having ip-addresses would have on the importer down the line, not as an explicit call to implementation as part of the DOTF rollout.

**Comment by arnoldnipper** [comment]
> From a developer's perspective it would be helpful to understand the use-case behind netixlans with nulled ipaddresses.

To simply show that you are at the exchange. 

> Currently a netixlan is uniquely identify-able by it's ip4,ip6 tuple. In the case of both ipaddresses being nulled, do we also consider that a unique netixlan (in combination with it's asn)? e.g., would a network be limited to one netixlan with nulled ip-addresses per ixlan, or would they be allowed to create as many of those as they want / need ?

If we allow (asn, null, null) then it seems logical to me to allow as many of those as a network may have multiple connections.

> I think this got lost in communication, i remember/understood that discussion as considering the implications not having ip-addresses would have on the importer down the line, not as an explicit call to implementation as part of the DOTF rollout.

My understanding was that we are discussing how to implement the importer and went through all the corner cases. Looks like I should have been more explicit.

@pc, what is your opinion?

- [ ] `netixlan` **must** have either `ipaddr4` or `ipaddr6` set
- [ ]  an `asn` w/o any ipaddresses is just fine

**Comment by grizz** [comment]
I vote require an IP address.

(And sorry about editing your message, was seeing if I could actually check the checkbox, and yes, I could:) )

**Comment by mcmanuss8** [comment]
I would look at it this way:
Is it valuable for us to allow networks to mark that they are planning to join an IX before they know their IP assignments or not? If it is valuable, we cannot require this. If it is not valuable, then we should absolutely require this.

**Comment by arnoldnipper** [comment]
> Is it valuable for us to allow networks to mark that they are planning to join an IX before they know their IP assignments

Definitely, I would say. Especially as they now are able to tag this entry as not yet operational.

**Comment by leovegoda** [comment]
> I would look at it this way:
> Is it valuable for us to allow networks to mark that they are planning to join an IX before they know their IP assignments or not? If it is valuable, we cannot require this. If it is not valuable, then we should absolutely require this.

If it is valuable, could we have an "connection in process" kind of option that allows the organization to flag the fact that they are about to connect to the exchange?

**Comment by arnoldnipper** [comment]
> If it is valuable, could we have an "connection in process" kind of option that allows the organization to flag the fact that they are about to connect to the exchange?

That is the not setting operational flag for.

**Comment by arnoldnipper** [comment]
To be more explicit

```
{
  "id": 60509,
  "net_id": 24355,
  "ix_id": 3232,
  "name": "OpenSwitch-IX",
  "ixlan_id": 3232,
  "notes": "",
  "speed": 1000,
  "asn": 140974,
  "ipaddr4": null,
  "ipaddr6": "2602:feda:afe::20",
  "is_rs_peer": true,
  "operational": false, <----
   "created": "2020-08-24T18:34:06Z",
  "updated": "2020-08-24T18:34:06Z",
  "status": "ok"
}
```

![20201001 PeeringDB 00](https://user-images.githubusercontent.com/16888757/94847273-a9da7e80-0422-11eb-870b-882d03089aa8.png)

**Comment by ynbrthr** [comment]
> Is it valuable for us to allow networks to mark that they are planning to join an IX before they know their IP assignments
> 
> Definitely, I would say. Especially as they now are able to tag this entry as not yet operational.

[sorry @arnoldnipper , i managed to edit your own post rather than commenting on it. trying to fix that]

Right. And so, until you're operational, you may not have the IP allocated by the IXP yet. Once you're operational, you should have one

**Comment by arnoldnipper** [comment]
> Right. And so, until you're operational, you may not have the IP allocated by the IXP yet. Once you're operational, you should have one

That's not entirely true ... typically the procedure is like that

 * you decide to connect to a new IX ---> you could already publish your ASN at $NEWIX, setting operational to false
 * you get an IP address from $NEWIX ---> add ipaddr{4,6} to your record, leaving operational to false
 * you are ready to peer at $NEWIX ---> set field operational to true

**Comment by shane-kerr** [comment]
I support making an IP address a requirement. Having a user "pre-declare" that they will be an an IX doesn't actually save them any work since they'll have to update their record later when they get an IP address.

**Comment by arnoldnipper** [comment]
@shane-kerr, we all know that every network is updating their entries via the API. So it's not about saving any work.  I guess @mcmanuss8 was thinking of giving your peers an as early as possible heads-up. Does that make sense?

**Comment by shane-kerr** [comment]
> @shane-kerr, we all know that every network is updating their entries via the API. So it's not about saving any work. I guess @mcmanuss8 was thinking of giving your peers an as early as possible heads-up. Does that make sense?

I guess so. It doesn't seem likely to me that anyone actually does anything with this information, but I suppose it also doesn't hurt anything.

**Comment by mcmanuss8** [comment]
I think I (and maybe others) are making some assumptions about how ISPs use peeringdb to advertise they're coming soon. I have seen ISPs do this but I have no sense of how often that happens or how valuable it is to others. Maybe it's worth polling some community members to see what they think?

**Comment by arnoldnipper** [comment]
While I also agree that it is desirable to have an IP address, we are running in circles. Regardless of what we decide, it is a good decision which has its pros and cons.

**Comment by arnoldnipper** [comment]
I changed my mind from to **"make at least one IP a requirement"**

**Comment by arnoldnipper** [comment]
Meanwhile, at least three @peeringdb/pc gave a -1 to the last summary. Hence, there is this is new

**Summary**
 * Field `asn` **MUST** be set
 * `ipaddr4` **MUST** be set **or** `ipaddr6` **MUST** be set
 * If ipaddr{4,6} is set, it **MUST** be within the correspondant `ixpfx` range
 * Fields `speed` and `is_rs_peer` **SHOULD** be set

Please note that this already is the current behaviour. That means if no one opposes the issue is closed.

**Comment by grizz** [comment]
Agreed, that's currently how it is!
