### ISSUE TITLE
Add min_speed and max_speed to ixlan 

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/peeringdb#481]
Based on the discussion in #475 add to new fields to record `ixlan`

 * `min_speed`: minimum speed of connections to this `ixlan`
 * `max_speed`: maximum speed of connections to this `ixlan`

Adding these fields improves data quality

**Comment by mcmanuss8** [comment]
+1 is there a corresponding task to reject records that are > max or < min speeds?

**Comment by arnoldnipper** [comment]
> +1 is there a corresponding task to reject records that are > max or < min speeds?

Iff that will be voted on to implement

**Comment by as44980** [comment]
sounds like a good idea, could it be worth specifying that this is aggregate/logical capacity rather than individual interface speeds?

**Comment by arnoldnipper** [comment]
> sounds like a good idea, could it be worth specifying that this is aggregate/logical capacity rather than individual interface speeds

I don't think so as it is clear that this specifies the **logical connection** to the IX rather than the physical.

**Comment by as44980** [comment]
> I don't think so as it is clear that this specifies the **logical connection** to the IX rather than the physical.

Is that _clear_ based on the variable definitions of "minimum speed of connections to this ixlan" and "maximum speed of connections to this ixlan" ?

Or when a network updates their record and it simply asks for "Speed (mbit/sec)"?  ;)

**Comment by grizz** [comment]
@arnoldnipper you mean single config values for the whole DB, not adding fields per ixlan, right?

If so, +1 from me and we can close #475

**Comment by arnoldnipper** [comment]
@grizz, this request was from a user iirc. And it was meant to be per `ixlan`. Could make sense. Otoh may be difficult to implement

**Comment by grizz** [comment]
Oh, I see the `ixlan` reference now. Meh, easy to implement, but seems like it adds an admin overhead for each IXP and most values are going to be very similar. Compromise and do DB wide values?

And if most want it per `ixlan` I'd be good with that as well.

@peeringdb/pc thoughts?

**Comment by grizz** [comment]
@peeringdb/pc Is this thing on? :)

**Comment by arnoldnipper** [comment]
DB wide values perhaps would lead to `max_speed` only. Makes sense and then should be in the config startup file. Does that make sense?

**Comment by grizz** [comment]
Sure, makes sense to me - that's where the rest of the limits are as well.

https://github.com/peeringdb/peeringdb/issues/475#issuecomment-485329484

From that, it looks like maybe we should at least to 10M as min_limit? I find it hard to believe that's even still used tho.

**Comment by arnoldnipper** [comment]
Makes sense. However, we still have 

```
curl -sG https://peeringdb.com/api/netixlan --data-urlencode fields=speed | jq '[.data[] | select (.speed > 0) | .speed ] | unique | .[0:10]'
[
  1,
  2,
  3,
  4,
  5,
  10,
  20,
  25,
  30,
  34
]
```

**Comment by grizz** [comment]
How many of those are legit speeds and not typos? When the rest of the world is dealing with Gigs, are there still spots with <100M connections?

**Comment by arnoldnipper** [comment]
Let's move the world a bit forward. I would also be ok with `min_limit` = `100M`.

**Comment by shane-kerr** [comment]
Given that these are new values, maybe it makes sense to default `min_speed` to 0, or even better `None` (meaning that the `ixlan` either has not bothered to specify a `min_speed` or chooses not to specify one for some reason)?

Likewise maybe we should have the same logic for `max_speed`?

As for the DB-wide values, I guess I'm okay with `min_limit` of `100M` and `max_limit` of... `1T` (based on #475).

**Comment by arnoldnipper** [comment]
> Given that these are new values, maybe it makes sense to default `min_speed` to 0, or even better `None` (meaning that the `ixlan` either has not bothered to specify a `min_speed` or chooses not to specify one for some reason)?

@shane-kerr, didn't we already have consensus not to go for per `ixlan` values?

**Comment by shane-kerr** [comment]
> > Given that these are new values, maybe it makes sense to default `min_speed` to 0, or even better `None` (meaning that the `ixlan` either has not bothered to specify a `min_speed` or chooses not to specify one for some reason)?
> 
> @shane-kerr, didn't we already have consensus not to go for per `ixlan` values?

Ah, that was not at all clear to me. Maybe we should rename the ticket?

I'm +1 for DB-wide limits of at least 100 Mbit and at most 1 Tbit.

**Comment by ynbrthr** [comment]
as a recap, we have consensus for going with a db-wide range of acceptable ix port rates of:
* min: 100M
* max: 1T

as a sanity check

milestone bumped to 'consensus reached'

**Comment by arnoldnipper** [comment]
**Release Note**

To improve data quality exchange port speed rates are limited to: 100M <= port speed <= 1T

**Comment by arnoldnipper** [comment]
We probably should raise the threshold, as

```bash
curl -sG https://peeringdb.com/api/netixlan --data-urlencode fields=net_id,name,speed | jq -r '.data[] | select(.speed > 500000) | .net_id, .speed/1000, .name' | paste - - - | sort -k2,2nr
5098    1600    NL-ix: Main
5098    1600    NL-ix: Main
5098    1600    R_iX: Main
5098    1600    R_iX: Main
11448   1000    NAPAfrica IX Johannesburg: Peering
1560    1000    SIX Seattle: MTU 1500
22235   1000    KINIX
433     800     IX.br (PTT.br) São Paulo: ATM/MPLA
433     800     IX.br (PTT.br) São Paulo: ATM/MPLA
457     800     IX.br (PTT.br) São Paulo: ATM/MPLA
457     800     IX.br (PTT.br) São Paulo: ATM/MPLA
979     800     IX.br (PTT.br) Fortaleza: ATM/MPLA
979     800     IX.br (PTT.br) Fortaleza: ATM/MPLA
979     800     IX.br (PTT.br) São Paulo: ATM/MPLA
979     800     IX.br (PTT.br) São Paulo: ATM/MPLA
979     800     IX.br (PTT.br) São Paulo: ATM/MPLA
979     800     IX.br (PTT.br) São Paulo: ATM/MPLA
2       700     IX.br (PTT.br) São Paulo: ATM/MPLA
1418    600     LINX LON1: Main
1766    600     DE-CIX Frankfurt: DE-CIX Frankfurt Peering LAN
1766    600     DE-CIX Frankfurt: DE-CIX Frankfurt Peering LAN
2       600     IX.br (PTT.br) São Paulo: ATM/MPLA
319     600     DE-CIX Frankfurt: DE-CIX Frankfurt Peering LAN
319     600     DE-CIX Frankfurt: DE-CIX Frankfurt Peering LAN
3554    600     AMS-IX
3554    600     AMS-IX
```

Furthermore, if speed is >= 1000000, it is displayed as "1T" (see [KPN-Netco](https://peeringdb.com/net/5098)

**Proposal**: raise the maximum to 5000000 or even 10000000

**Comment by stillwaxin** [comment]
Does this need to be thought out a little bit more? Like have port speed be derived by something like a validated individual port speed with a reasonable multiplier for link aggregates? For example, we know for ethernet that 1g,10g,(maybe 25/40/50g),100g,400g are currently valid port speeds, and we know that its reasonable that networks will form link aggs of 1,2,4,8,16... ( and any number in between really) of these ports to form their total link agg speed. In the end a network would enter that they have 100g ports and have N=6 of them to indicate a 600g lag to the IXP. I realize that if this were interesting it'd be a separate issue.

**Comment by arnoldnipper** [comment]
> Does this need to be thought out a little bit more? Like have port speed be derived by something like a validated individual port speed with a reasonable multiplier for link aggregates? For example, we know for ethernet that 1g,10g,(maybe 25/40/50g),100g,400g are currently valid port speeds, and we know that its reasonable that networks will form link aggs of 1,2,4,8,16... ( and any number in between really) of these ports to form their total link agg speed. In the end a network would enter that they have 100g ports and have N=6 of them to indicate a 600g lag to the IXP. I realize that if this were interesting it'd be a separate issue.

I'm not sure what you want to propose? That we only allow discrete values for speed? Or what?

**Comment by stillwaxin** [comment]
What I'm thinking is that we could potentially switch to a model where we allow the network to enter a validated port speed for an individual port such as 1/10/100/400g and then a number of ports that form their lag from 1-32 and we calculate the final aggregated port speed based on those values. Note that this would not work for networks that have rate limits applied to their ports but perhaps that's not worth considering either.

**Comment by arnoldnipper** [comment]
> What I'm thinking is that we could potentially switch to a model where we allow the network

Which operational benefit does that have? None IMHO. It only makes the object way more complex. 100G capacity is 100G, regardless whether this is 1x100, 4x25 or 10x10.

**Comment by stillwaxin** [comment]
The benefit is that it restricts the network operator into providing pre-validated input into the port speed field.

**Comment by arnoldnipper** [comment]
> The benefit is that it restricts the network operator into providing pre-validated input into the port speed field.

@stillwaxin, please open a new issue if you want to change the number "Speed (mbit/sec)" input field to a number x select_from_dropdown_with_well-defined_bandwith field.

**Comment by arnoldnipper** [comment]
**Summary**
To improve data quality exchange port speed rates are limited to: 100M <= port speed <= **5T**

**Comment by arnoldnipper** [comment]
@peeringdb/pc and/or @peeringdb/oc does that need code change? Or are these value defined in a startup config file?

**Comment by ccaputo** [comment]
> @peeringdb/pc and/or @peeringdb/oc does that need code change? Or are these value defined in a startup config file?

Could be done in a startup file, but since there are several instances, a code change with testing is best: https://github.com/peeringdb/peeringdb/blob/ca2fa51430380001122910b1e43b9d9142cca08a/mainsite/settings/__init__.py#L285-L286

**Comment by arnoldnipper** [comment]
I'm pushing it through to 3a as implementation has been done. Now it's only to increase `DATA_QUALITY_MAX_SPEED` to 5000000. A user was asking to set 2.000000. Hence 5000000 makes sense to me.

**Comment by grizz** [comment]
This is a simple config change during any deployment.

**Comment by leovegoda** [comment]
Confirmed with @20c-ed that this issue is functionally complete. Future value changes can be accomplished with a configuration change at deployment time. No further development work required.
