### ISSUE TITLE
Text should wrap and not be cut off

### ISSUE THREAD

**Issue by jzp-github** [peeringdb/peeringdb#485]
Likely just a minor css twiddle, but I can't file a fix without jumping through dumb hoops at $BIGCOMPANY. 

Presenting the data should always be the first choice, over whatever style or formatting choices exist. Personally I think the current trend/obsession with "fixed-width" panels on web pages is a serious regression, but rather than fight the tide I'd suggest that you render text as wrapped within that chosen constraint. As it stands, long email addresses in "contacts" get cut off due to the current choices.  One can still pull the data out (clicking the right number of times to grab whole field in browser, or pull from the underlaying data), but the presentation is bad.  

Reproduced in Chrome, Safari, and Firefox [all $current] on Mac OSX.

Simple example: https://www.peeringdb.com/asn/9795
Attached image of a widest possible browser widow showing how the fixed panes fail to expand: 
<img width="1369" alt="pdb-needswrap-wide" src="https://user-images.githubusercontent.com/4713248/57142670-23cc8b00-6d8b-11e9-91ee-4deca5f77037.png">

**Comment by eloos** [comment]
Steve, what are your plans on this? Should we just add it to the backlog?

**Comment by mcmanuss8** [comment]
@eloos  it's an easy fix (in theory) - I put in a pull request to wrap the text
