### ISSUE TITLE
affiliate with ASN fails with 404 from RIPE

### ISSUE THREAD

**Issue by funkestefan** [peeringdb/peeringdb#494]
If I enter an ASN at https://www.peeringdb.com/profile I get:
RDAP Lookup Error: RDAP lookup to https://rdap.db.ripe.net/autnum/123456 returned 404

Tested with existing ASNs and non-existing ASNs belonging to RIPE and other regions.

**Comment by arnoldnipper** [comment]
What would be expected behaviour?

**Comment by arnoldnipper** [comment]
Maybe something like

`curl -sGL https://rdap.db.ripe.net/autnum/$ASN | jq 'if has("errorCode") then "ASN does not exist" else if (has("name")) then .name else "RDAP error" end end'`

might be more appropriate.  However, in this case ASN 123456 is not assigned at all.

**Comment by grizz** [comment]
@funkestefan This is just asking for better error messages, right?

**Comment by funkestefan** [comment]
Actually there are two things to fix:

1. Better error message. 
2. The RDAP lookup implementation should be changed.

The real problem was a lookup for AS26619, which returned a 404 error from RIPE RDAP. But RIPE is not responsible for AS26619, so RIPE wasn't the right source for this query. RFC7484[0] defines to use a bootstrap file to find a valid URI as a client entry point for RDAP lookups. The bootstrap file is a json object [1], as defined in RFC RFC8521 [2]. If someone follows the right path, AS26619 can be resolved. My suggestion:

- fetch a copy of the rdap-asn bootstrap file once a day/week and cache it
- if there is a newer bootstrap file at IANA, get the latest version and use it as the cached source for lookups
- build a map/table for rdap lookups for the correct rdap lookup source/server/path

 [0] https://tools.ietf.org/rfc/rfc7484.txt
 [1] https://www.iana.org/assignments/rdap-asn/rdap-asn.xhtml
 [2] https://tools.ietf.org/rfc/rfc8521.txt

**Comment by arnoldnipper** [comment]
Imho completely covered by #497. Agreed, @funkestefan ?

**Comment by funkestefan** [comment]
This enhances your [1] and the cosmetic fix is covered by your [3].

**Comment by grizz** [comment]
> The real problem was a lookup for AS26619, which returned a 404 error from RIPE RDAP. But RIPE is not responsible for AS26619, so RIPE wasn't the right source for this query. RFC7484[0] defines to use a bootstrap file to find a valid URI as a client entry point for RDAP lookups. The bootstrap file is a json object [1], as defined in RFC RFC8521 [2]. If someone follows the right path, AS26619 can be resolved. My suggestion:

RIPE used to provide a bootstrap server that redirects to the correct source, and it appears they no longer do. However we were at their whim for that, and just changed to rdap.org to which the same holds true for. So implementing without relying on a bootstrap server is probably the best way to ensure it works correctly going forward.

+1 to use bootstrap files and can review all the error messages at that point as well.

@peeringdb/pc Thoughts?

**Comment by arnoldnipper** [comment]
+1

**Comment by shane-kerr** [comment]
Just so I'm clear, the proposal is to get an authoritative list of assignments from... ICANN?, make our own bootstrap JSON file, and use that to figure out which RDAP server to query?

**Comment by grizz** [comment]
> Just so I'm clear, the proposal is to get an authoritative list of assignments from... ICANN?, 

Essentially, they're from IANA, the ASN bootstrap data is at https://data.iana.org/rdap/asn.json

>make our own bootstrap JSON file, and use that to figure out which RDAP server to query?

Yes, then use that to query the correct RIR. We're still somewhat at their whim because of RIR subdelegations, but it's as close as we can get.

**Comment by arnoldnipper** [comment]
> We're still somewhat at their whim because of RIR subdelegations, but it's as close as we can get.

What is really pita is that APNIC has a couple of subdelegations where the correspondent NIC does not run an RDAP server. I'm working with APNIC's George Michaelson to get this sorted,

**Comment by mcmanuss8** [comment]
+1 use iana's bootstrap

**Comment by funkestefan** [comment]
IANA might be the best source anyway +1

**Comment by shane-kerr** [comment]
+1

Using IANA bootstrap
