### ISSUE TITLE
Links to maps.google.com broken in some translations

### ISSUE THREAD

**Issue by durkovic** [peeringdb/peeringdb#496]
If a language uses decimal comma and not decimal point, links in facility page to maps.google.com are broken - they look like https://maps.google.com/?q=48,151421,17,112847

**Comment by arnoldnipper** [comment]
Confirmed ... happens e.g. when you are using "Deutsch" as your language. Should be fixed immediately imho

**Comment by edecaen** [comment]
Confirmed..
Same problem with "French" locale: "," instead of "." in url.
Geocode in French : https://www.google.com/maps?q=45,168755,5,68854
Geocode in English:  https://www.google.com/maps?q=45.168755,5.68854

**Comment by mcmanuss8** [comment]
peeringdb_server/templates/site/view.html is using the language massaged value for both display and the link to maps.google.com. Should continue to show the lat/long in the appropriate locale, but use a non-locale'd version for the url.
