### ISSUE TITLE
new translations not showing up on beta

### ISSUE THREAD

**Issue by grizz** [peeringdb/peeringdb#498]
Seems I'm missing a step in the language deploy, someone needs to look into it and make sure there are correct docs @peeringdb/oc

**Comment by FredNeuberger** [comment]
Hi,
Found this german typo here:

Trafficverhältnis Vorweiegend eingehend

Might this be fixes in the translation stuff that you are relating too?


Cheers

**Comment by arnoldnipper** [comment]
@FredNeuberger , do you also see this typo on https://beta.peeringdb.com? I can't find that string on https://translate.peeringdb.com

**Comment by FredNeuberger** [comment]
@arnoldnipper Yup, I do see it on beta.pdb.com

![pdb_german_vorweigend](https://user-images.githubusercontent.com/33221829/58169726-c0e75900-7c91-11e9-8304-5c333cf17243.PNG)

Not sure how to use that translation thingy properly, but I can't find the typo version either.

**Comment by arnoldnipper** [comment]
> Not sure how to use that translation thingy properly, but I can't find the typo version either.

@peeringdb/oc , has the latest translation being deployed to beta?

**Comment by mwtr** [comment]
I'd like to know when new translated Japanese words on the Weblate page will be put to beta PeeringDB page. If you have any updates, please let me know.

**Comment by ccaputo** [comment]
@mwtr I believe I now have up to your April 18th translations running on beta.  Please check and confirm you are seeing what is expected.  Thank you.

**Comment by FredNeuberger** [comment]
The german part seems to be good now
![pdb_german_vorweigend_corrected](https://user-images.githubusercontent.com/33221829/58729604-294cdd80-83ea-11e9-9364-0cc1fd866928.PNG)

**Comment by mwtr** [comment]
@ccaputo Thank you for information. I have confirmed that new translated Japanese words are put to beta.peeringdb.com.

**Comment by ccaputo** [comment]
Recent updates have now been rolled out to the production site.  Greek and Spanish are now enabled.

**Comment by ccaputo** [comment]
https://docs.peeringdb.com/translation/ : "Translations are updated hourly on the beta website https://beta.peeringdb.com/ and daily at 0000 UTC on the production website https://www.peeringdb.com/."
