### ISSUE TITLE
VerificationQueueItem - make unique in db schema

### ISSUE THREAD

**Issue by vegu** [peeringdb/peeringdb#502]
Recently rant into an issue where 2 `verificationqueueitem` instances were created for the same object and causing issues elsewhere (geosync process bugged out in this case).

They should be unique by `content_type`, `object_id` in the db schema.

**Comment by arnoldnipper** [comment]
+1

**Comment by mcmanuss8** [comment]
+1

**Comment by shane-kerr** [comment]
+1
