### ISSUE TITLE
Remove Partners link and page

### ISSUE THREAD

**Issue by ghankins** [peeringdb/peeringdb#503]
We are no longer partnering with Inflect and need to remove the Partners link from the footer and the Partners page that we added in #194.

**Comment by grizz** [comment]
@ghankins  You want to remove the whole partners page, or just Inflect?

**Comment by grizz** [comment]
@ghankins you can add and remove partners from the admin control panel real time btw

**Comment by job** [comment]
The whole page, since we have no partners at the moment.

**Comment by ghankins** [comment]
Yes, remove the whole page.

**Comment by grizz** [comment]
Will do

**Comment by grizz** [comment]
Fixed in 2.13.1.2 and deployed to beta.
