### ISSUE TITLE
Add "Management" search field to Advanced Search of Exchanges

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/peeringdb#506]
More and more IX Operators run more than one IX. Hence searching for Management the same way as for Facilities would make sense.

**Comment by arnoldnipper** [comment]
2418/3869 (i.e. 62.4%) facilities are managed by organisations running more than one facility. And you can search for the managing organisation.

444/820 (i.e. 54.1%) exchanges are managed by organisations running more than one exchange. However, you can't search for them.

Proposal: add field "Management" to https://peeringdb.com/advanced_search?reftag=ix

@pc, two more + needed

**Comment by shane-kerr** [comment]
+1

Seems reasonable.

**Comment by ynbrthr** [comment]
+1

**Comment by grizz** [comment]
@arnoldnipper I'm not sure what would be in the Management field? Organization?

**Comment by arnoldnipper** [comment]
> @arnoldnipper I'm not sure what would be in the Management field? Organization?

Not sure, I understand your question, @grizz? What's the difference in Management for Facilities and for IXes? Both point to Organisations. No?

**Comment by grizz** [comment]
I was asking what the field actually points to, yes. I just looked at the search form (without looking at the code), it looks like a text search to org name. In which case, yes, let's add it to both net and ix, rename it to Organization, and probably make it autocomplete?

**Comment by arnoldnipper** [comment]
**Summary**

 * rename "Management" to "Organization" in https://www.peeringdb.com/advanced_search#fac
 * add a search field "Organization" to https://www.peeringdb.com/advanced_search#{ix,net}
 * make searching autocomplete

@grizz, will autocompletion still allow for partial search as it is possible today?

**Comment by grizz** [comment]
@arnoldnipper yes, good call on clarifying that.
