### ISSUE TITLE
Bypass ACK question when at superuser level

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/peeringdb#507]
Admin Committee (AC) members use both the /cp as well as the regular GUI for their work. They pretty much know what they do.

Removing the ACK question would greatly cut down time spent for approving users

**Comment by eloos** [comment]
what is /cp?

**Comment by arnoldnipper** [comment]
https://peeringdb.com/cp/ is the top level of the Admin GUI

**Comment by vegu** [comment]
@arnoldnipper just for approving users or all confirmation prompts?

**Comment by arnoldnipper** [comment]
@vegu for all, please

**Comment by arnoldnipper** [comment]
@peeringdb/pc may I kindly ask for support

**Comment by mcmanuss8** [comment]
Don’t quite understand the ask since I haven’t done AC work. Is this a safety check kind of thing that we’re disabling? Like a “are you sure you want to...?”?

-Steve
(from iPhone - expect typos)

**Comment by arnoldnipper** [comment]
This is double-checking whether you really want to do this operation or not. Especially for ACKing affiliations (or even DENYing) I don't see the real value for regular users.

Being able to approve affiliation with **one** click instead of **four* would really help. Otoh,
![InkedScreenshot 2019-11-23 17 25 16_LI](https://user-images.githubusercontent.com/16888757/69482107-97151780-0e17-11ea-866b-f6809b0f4e2d.jpg)
 I see that @vegu has marked this as "Major". Having feedback from @peeringdb/ac would help.

**Comment by shane-kerr** [comment]
+1

I do think that we may want to be more careful with operations which remove information (like deletes) then approving additions.

**Comment by mcmanuss8** [comment]
If AC is ok with this, I'm ok with this. +1

**Comment by grizz** [comment]
+1 -- consensus reached

**Comment by arnoldnipper** [comment]
@vegu and/or @grizz, are there any questions left? Please respond within 5 working days. If no answer is received I will move it to the next milestone.

**Comment by vegu** [comment]
> @vegu for all, please

@arnoldnipper -  i am working on this at the moment and looking through the comments, can you re-confirm for me that you actually want to remove the confirmation prompt for delete actions (such as delete ix from org) as well?

Even if superusers (pdb admin) know what they are doing, accidental clicks happen, and restoring entities and all their deleted children is still a fairly manual process (aside from ixlans)

**Comment by arnoldnipper** [comment]
@vegu, please leave the confirmation for **deleting** items., but remove it for **adding/approving** them
