### ISSUE TITLE
Wording IPv6 IXlan size

### ISSUE THREAD

**Issue by funkestefan** [peeringdb/peeringdb#517]
If I try to add an IXlan larger than /64 (e.g. /56) it says "Minimum allowed prefix length is 64".
Since /56 is larger than /64, the error message is misleading.

It's either "Maximum" or if /64 is the only reasonable size, it should be defaulted.

**Comment by netravnen** [comment]
> It's either "Maximum" or if /64 is the only reasonable size, it should be defaulted.

Who needs more than `Max. Hosts = 18446744073709551616   (2^64 - 1)` in a subnet anyway? 😆 

Sarcastic comment aside. I agree we should default the IPv6 prefix-size field to /64.
User can afterwards edit the field to prefix-size smaller than /64 is necessary.

**Comment by arnoldnipper** [comment]
See #269  ... /64 being maximum, but may be shorter. This already is implemented. What AC (@funkestefan) has to do is to clean up.

**Comment by arnoldnipper** [comment]
Should read **"Maximum"** instead of "Minimum". Probably the same for IPv4
