### ISSUE TITLE
Make spelling of traffic levels consistent

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/peeringdb#519]
Either remove or add blank between the numbers and [MGT]bps. I'm in favour of removing the blank as it makes searching via the API easier.![Screenshot 2019-07-01 06.01.27.png](https://images.zenhubusercontent.com/57929671e40e5714b16c6b73/3a4e6263-3bf2-45b4-8e06-515b673c8314)

**Comment by arnoldnipper** [comment]
While at it 

 * change "1 Tbps+" to "1-5Tbps"
 * add "5-10Tbps"
 * change "10 Tbps+" to "10-20Tbps"
 * add "20-50Tbps"
 * add "50-100Tbps"
 * add "100+Tbps"

**Comment by vegu** [comment]
Needs to be fixed in django-peeringdb (since values are changed and added) and then peeringdb needs to be updated to use latest django-peeringdb package, which ideally should wait after #492 is completed.

**Comment by arnoldnipper** [comment]
still some +1s needed, @peeringdb/pc

**Comment by shane-kerr** [comment]
+1

I like the space after the number, and I'm not really sure why it would cause an issue with searching via the API, but I'm fine either way as long as the values are consistent.

**Comment by arnoldnipper** [comment]
@shane-kerr it doesn't cause issues, but it is easier w/o space ;-) ... just try it :)

**Comment by grizz** [comment]
+1 to normalize, and I'd be for no space, but don't really care either way.

Maybe even drop the "bps" from all of them?

**Comment by mcmanuss8** [comment]
+1 no space, keep bps in there (makes sure we don't confuse Gbps with GBps)

**Comment by grizz** [comment]
@peeringdb/pc This will also change the values used by the API, should we pause this and give more notice to users?

**Comment by arnoldnipper** [comment]
Nothing urgent, hence +1

**Comment by ynbrthr** [comment]
+1

**Comment by arnoldnipper** [comment]
+1 ... yes, we should pause this issue and give more notice to users

**Comment by grizz** [comment]
+1 from me as well, so pausing.

Should we update this to add 2 integer fields? `traffic_min` and `traffic_max`? We could use those to create this field programmatically then. Might be overkill, but would make scripting a ton easier.

**Comment by arnoldnipper** [comment]
What is the meaning of `traffic_ min` and `traffic_max`?

**Comment by stillwaxin** [comment]
Reminder that #594 exists that is related to this field as well.

**Comment by grizz** [comment]
> Reminder that #594 exists that is related to this field as well.

Oh right, thanks!

**Comment by grizz** [comment]
> What is the meaning of `traffic_ min` and `traffic_max`?

Was thinking just an int for Gigs, although with #594 I'm not sure we need to bother.

**Comment by arnoldnipper** [comment]
**Release note**
This is a bug fix and a minor improvement.  Spelling is made consistent and traffic levels up to 100+Tbps are added.

**Comment by ynbrthr** [comment]
There is no consensus for #594, is there? I would vote '-1' on it.

While I see the programatic appeal of using mix / max values for the traffic levels, would that not discourage the networks filling that up manually to actually use that field? As opposed to the large-brush brackets we have today.

**Comment by koalafil** [comment]
This is planned to be added to beta.peeringdb.com in April 2020 however it will NOT be released in immediate next release (2.20). This is in order to allow more time for API users for awareness and testing. It will be added to a future May/June release.
