### ISSUE TITLE
Exchange City Search

### ISSUE THREAD

**Issue by esundberg** [peeringdb/peeringdb#52]
On this page https://www.peeringdb.com/advanced_search

Under the exchange tab the city search field is a excat patern match, make this sure so there is wildcards on the front and end of the search string. If you search New York it is decieving because only 7 exchanges are listed when there is really 12 of them that should be listed. 

Where City='New York'  -- Gets you 7 Results
update to
Where City like '%New York%' -- Would get you 12 Results

City Names where New York in the mix
New York
DC, Reston, Boston, New York
New York / New Jersey
New York/New Jersey

**Comment by vegu** [comment]
implementing #23 will take care of this
