### ISSUE TITLE
Verify ixpfx's don't overlap/merge existing overlaps

### ISSUE THREAD

**Issue by DamianZaremba** [peeringdb/peeringdb#521]
Currently it is possible to define an IXLan that overlaps another IXLan. This can be seen in the current production data;

`GET https://www.peeringdb.com/api/ixpfx?pretty&ix_id=593`
```
{
  "meta": {}, 
  "data": [
    {
      "id": 12, 
      "ixlan_id": 593, 
      "protocol": "IPv6", 
      "prefix": "2001:504:0:6::/64", 
      "created": "2010-07-29T00:00:00Z", 
      "updated": "2016-03-15T09:24:16Z", 
      "status": "ok"
    }, 
    {
      "id": 17, 
      "ixlan_id": 593, 
      "protocol": "IPv4", 
      "prefix": "198.32.125.0/24", 
      "created": "2010-07-29T00:00:00Z", 
      "updated": "2018-08-01T19:02:01Z", 
      "status": "ok"
    }
  ]
}
```

`GET https://www.peeringdb.com/api/ixpfx?pretty&ix_id=17`
```
{
  "meta": {}, 
  "data": [
    {
      "id": 37, 
      "ixlan_id": 17, 
      "protocol": "IPv4", 
      "prefix": "198.32.124.0/23", 
      "created": "2010-07-29T00:00:00Z", 
      "updated": "2016-03-14T21:38:00Z", 
      "status": "ok"
    }, 
    {
      "id": 38, 
      "ixlan_id": 17, 
      "protocol": "IPv6", 
      "prefix": "2001:478:124::/64", 
      "created": "2010-07-29T00:00:00Z", 
      "updated": "2016-03-30T08:51:04Z", 
      "status": "ok"
    }
  ]
}
```

(`198.32.125.0/24` being the upper half of `198.32.124.0/23`).

It's not ideal as a user having both https://www.peeringdb.com/ix/17 & https://www.peeringdb.com/ix/593, with peers split across both.

From a network standpoint anything in the '/23 ixlan' can talk to the '/24 ixlan' but not the other way around... which makes it hard to build tooling against the data, since the choice of which id to use for peering (it is not possible to define duplicate IPs in netixlan's) is not easily machine choosable (more specific is not always the best choice).

I can't think of a good reason why it would be desirable to have overlapping of duplicate prefix entries across IX lans, but I perhaps have not thought about it for a very long time.

From a quick poke there are currently no duplicates and the following overlaps

- 2001:43f8:bb1:150::/64 overlaps 2001:43f8:bb1::/48
- 198.32.125.0/24 overlaps 198.32.124.0/23
- 218.100.7.0/24 overlaps 218.100.6.0/23
- 196.216.149.0/24 overlaps 196.216.148.0/22
- 196.216.150.0/24 overlaps 196.216.148.0/22
- 196.216.151.0/24 overlaps 196.216.148.0/22
- 198.32.166.0/23 overlaps 198.32.167.0/24

**Comment by arnoldnipper** [comment]
> Currently it is possible to define an IXLan that overlaps another IXLan.

Did you test that? Afaik what you see is old data which still has to be cleaned up

**Comment by arnoldnipper** [comment]
> * 198.32.166.0/23 overlaps 198.32.167.0/24

This is a really interesting one as both ranges are used at completely different IXes

 * 198.32.167.0/24 at BDIX (https://peeringdb.com/ix/2516)

 * 198.32.166.0/23 at CyrusOne Sterling (https://peeringdb.com/ix/1117)

**Comment by DamianZaremba** [comment]
> > Currently it is possible to define an IXLan that overlaps another IXLan.
> 
> Did you test that? Afaik what you see is old data which still has to be cleaned up

Sorry, I did not test the addition explicitly. It could be that this is validated correctly, but as you say this is old data. My assertion should be more 'Currently there are IXLans that overlap other IXLans'.

**Comment by grizz** [comment]
@arnoldnipper what is the proposed solution here?

**Comment by arnoldnipper** [comment]
@grizz ixpfx have to be pairwise disjoint. For existing ixpfx AC will clean up

**Comment by Shawna** [comment]
@arnoldnipper sounds good, thanks for the explanation.
