### ISSUE TITLE
Show "Last Updated" fields on fac, ix, org records

### ISSUE THREAD

**Issue by mcmanuss8** [peeringdb/peeringdb#526]
We show it on /net/ but not on the others. Probably should. When we do make sure it's ISO 8601 compliant like on /net/ :)

**Comment by arnoldnipper** [comment]
+1 and +1 for ISO 8601

**Comment by grizz** [comment]
+1 +1

**Comment by koalafil** [comment]
Can we pls have the Release Notes? Thx.

**Comment by arnoldnipper** [comment]
**Release Notes**

A "Last Updated" field is visible now for on fac, ix, org objects as well

**Comment by mcmanuss8** [comment]
**Release Notes**

A "Last Updated" field is visible now for fac, ix and org objects as well

**Comment by mcmanuss8** [comment]
(Sorry, minor grammar change, Arnold)

**Comment by arnoldnipper** [comment]
> (Sorry, minor grammar change, Arnold)

Thanks a lot, @mcmanuss8
