### ISSUE TITLE
The number of prefixes regarding route server operated by IXP

### ISSUE THREAD

**Issue by mwtr** [peeringdb/peeringdb#527]
IXP operates route servers which has same AS number on their separated IX networks.
I hope that we can fill in the different number of prefixes for each route server, because there is a  different between them.
We JPIX has JPIX TOKYO and JPIX OSAKA.
https://peeringdb.com/ix/30
https://peeringdb.com/ix/564

**Comment by arnoldnipper** [comment]
What about using different ASN per IX which imho is BCP

**Comment by mwtr** [comment]
I understand it's an opinion. But I guess majority is using same AS number for their route servers as below (If I have a misunderstanding, please let me know)
Using same AS Number : AMS-IX(6777), Any2(19996), Equinix(24115), LINX(8714), Netnod(52005), JPIX(23815)
Using different AS Number : DE-CIX
I would like to tell our member correct number of prefixes by using PeeringDB for each route server of JPIX.

**Comment by arnoldnipper** [comment]
@mwtr, maybe a lot of IX operators are using the same ASN at different IXes. But please see https://tools.ietf.org/html/rfc1930#section-4 where the RFC says: "Without exception, an AS must have only one routing policy." This imho also includes the number of prefixes announced. ASN's are not a scarce resource anymore. Furthermore, I'm missing a proposal how to implement your idea.

**Comment by mwtr** [comment]
@arnoldnipper Thank you. What IXPs using the same ASN can do now is that we write it in the note.

**Comment by as44980** [comment]
> @mwtr, maybe a lot of IX operators are using the same ASN at different IXes. But please see https://tools.ietf.org/html/rfc1930#section-4 where the RFC says: "Without exception, an AS must have only one routing policy." 

AFAIK many IXP route-servers now offer per-peer RIB, which arguably means there is no single routing policy on a individual route-server instance never mind between different metros...

Does an IXP route-server, which typically removes its own ASN from the AS_PATH, even have its "own" routing policy when all it does is facilitate the exchange of routing announcements as instructed by it peers/members?  ;)

**Comment by job** [comment]
Regardless of the outcome of this ticket, a route server operator
absolutely owns its routing policy and is responsible for a sane policy.
This means they must filter invalid routes and not propagate leaks etc.
There is not a difference anymore between IXPs and ISPs in this regard.

**Comment by arnoldnipper** [comment]
> AFAIK many IXP route-servers now offer per-peer RIB, which arguably means there is no single routing policy on a individual route-server instance never mind between different metros...

I would rather argue the other way round. The per-peer table is to ensure to have a single routing policy.  The policy is expressed by the AS-SET IMHO.


> > @mwtr, maybe a lot of IX operators are using the same ASN at different IXes. But please see https://tools.ietf.org/html/rfc1930#section-4 where the RFC says: "Without exception, an AS must have only one routing policy."
> 
> AFAIK many IXP route-servers now offer per-peer RIB, which arguably means there is no single routing policy on a individual route-server instance never mind between different metros...
> 
> Does an IXP route-server, which typically removes its own ASN from the AS_PATH, even have its "own" routing policy when all it does is facilitate the exchange of routing announcements as instructed by it peers/members? ;)

Same holds for a transit provider. Doesn't it? But actually, that is not the question we are talking about. The question is whether different IXes should have different ASN. And this also is nothing PeeringDB is able to decide. However, I'm strongly **against** the proposal.

So -1 from me.

**Comment by arnoldnipper** [comment]
@mwtr to you still want us to drive this forward? If not, please close this issue

**Comment by mwtr** [comment]
Please close this ticket. Thank you.
