### ISSUE TITLE
Merge /ix/593 into /ix/17

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/peeringdb#529]
Customer writes:

The IX with id 17 is the accurate record. The IX with id 593 should be merged into 17, keeping 17 as the id going forward.

The correct IPv4 subnet for IX id 17 is 198.32.124.0/23.

**Comment by vegu** [comment]
@arnoldnipper 

We do have a crude ixp merge CLI tool, but all it does is move ixlans from one ix to another - it doesn't addresss local facilities and it doesnt merge ixlans themselves.

Is that still useful to run? It'd add the ixlan from 593 to 17 as a second ixlan, and soft-delete 593.

**Comment by arnoldnipper** [comment]
TIA, please run the script, but don't soft delete 593 as I want to look at the facilities.

**Comment by vegu** [comment]
@arnoldnipper done

**Comment by arnoldnipper** [comment]
done
