### ISSUE TITLE
Exchanges IP Block filtering not applied

### ISSUE THREAD

**Issue by ermuller** [peeringdb/peeringdb#53]
If you go to https://www.peeringdb.net/advanced_search, on the "Exchanges" tab, and enter "206.223.116.0/24" (or 206.223.116.251, 206.223.116.0, 2001:504:0:1::/64, etc...) in the "IP Block" field, the returned list gives all known exchanges rather than narrowing it down to Equinix-SJ - same as it if that field is left blank.  (there's also nothing returned for the same terms in the results of the main page simple search).
It looks like the IP block isn't being applied to the search at all.

**Comment by vegu** [comment]
fixed in 16038ac
