### ISSUE TITLE
Renumber IP Space broken

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/peeringdb#532]
The Renumber IP Space tool does not longer work. 
![AwesomeScreenshot-Renumber-IP-Space-Preview-PeeringDB-2019-07-18-22-07-62](https://user-images.githubusercontent.com/16888757/61489796-ccae7d80-a9ab-11e9-9127-7365262a4bd8.png)
![Uploading AwesomeScreenshot-PeeringDB-2019-07-18-22-07-57.png…]()
![Uploading AwesomeScreenshot-Renumber-IP-Space-Preview-PeeringDB-2019-07-18-22-07-67.png…]()

**Comment by vegu** [comment]
Issue caused by netixlans in a deleted ixlan attached to the ix, hotfixed version exists on prodmaster and can be run via cli, but is not available in the admin ui until we roll out a proper patch.
