### ISSUE TITLE
Support IX-F Member Export Schema v1.0

### ISSUE THREAD

**Issue by barryo** [peeringdb/peeringdb#533]
The [IX-F member export schema](https://github.com/euro-ix/json-schemas) has now stabilised and we have released [v1.0](https://github.com/euro-ix/json-schemas/pull/34) of it.

The changes from v0.7 are very minor and it may "just work" for you. The specific changes are [documented here](https://github.com/euro-ix/json-schemas/blob/master/ixp-member-list.txt). In summary:

1. added `software` to switches (a string, not required). This should be a no-op for PeeringDB.

2. refactor `service_type` (relates to IXP operated route collectors and route servers) to an array of objects called `services` and add the following data which IX-F wants to record for statistical purposes / market analysis / etc:
    * `os`: (string, not required)
    * `os_version`: (string, not required)
    * `daemon`: (string, not required)
    * `daemon_version`: (string, not required)

Again, if you were not using the `ixroutecollector` and `ixrouteserver` indicators from `services` then this is also a no-op and you already support V1.0 🍾

**Comment by arnoldnipper** [comment]
@barryo , so far PeeringDB is only using (ASN, IPv4 address, IPv6 address, speed, is_using_routeserver)

@vegu please confirm and close

**Comment by barryo** [comment]
Cool, should "just work" then.

**Comment by arnoldnipper** [comment]
@vegu or @grizz  would you mind to check?

**Comment by grizz** [comment]
Confirmed, we just use `vlan_list` -- we're proud supporters of 1.0! :)
