### ISSUE TITLE
Posting https://www.peeringdb.com onto social media doesn't select a good preview image

### ISSUE THREAD

**Issue by mahtin** [peeringdb/peeringdb#537]
Posting https://www.peeringdb.com onto social media normally selects the facebook logo image vs. the PeeringDB image. This is a lost opportunity. The PeeringDB image should be the only (or first) image provided. This can be repeated via other social media platforms or messaging platforms.

<img width="503" alt="image" src="https://user-images.githubusercontent.com/4521085/62061459-1123ef80-b1dc-11e9-86d6-a3745c8baf42.png">

**Comment by grizz** [comment]
+1

**Comment by arnoldnipper** [comment]
+1

**Comment by mcmanuss8** [comment]
+1 although that FB logo is pretty awesome ;)

**Comment by mcmanuss8** [comment]
Quick glance - Looks like opengraph controls this:
https://ogp.me/

Adding something like <meta property="og:image" content="https://peeringdb.com/s/2.14.0//pdb-logo-coloured.png" /> 

to <head> should do the trick (but I haven't tried)

**Comment by grizz** [comment]
@mcmanuss8 Yep, should be just that, although probably should use the square logo. Generally it takes some playing around with the opengraph properties to make it look good across different platforms. LinkedIn/Twitter should probably be checked out too.

**Comment by mahtin** [comment]
If we are going down this path; let's add some more issues that are somewhat related.

Apple icon (should you want to place PeeringDB on your iPhone/iPad screen). See [here](https://realfavicongenerator.net/blog/apple-touch-icon-the-good-the-bad-the-ugly/).
```
<link rel="apple-touch-icon-precomposed" sizes="57x57" href="/images/apple-57x57.png" />
<link rel="apple-touch-icon-precomposed" sizes="72x72" href="/images/apple-72x72.png" />
<link rel="apple-touch-icon-precomposed" sizes="114x114" href="/images/apple-114x114.png" />
<link rel="apple-touch-icon-precomposed" sizes="144x144" href="/images/apple-144x144.png" />
```
Twitter/Tweeters read [this](https://developer.twitter.com/en/docs/tweets/optimize-with-cards/guides/getting-started.html):
```
<meta name="twitter:card" content="summary_large_image" />
<meta name="twitter:title" content="PeeringDB" />
<meta name="twitter:description" content="PeeringDB is a freely available, user-maintained, database of networks, ..." />
<meta name="twitter:url" content="https://peeringdb.com/" />
<meta name="twitter:image" content="https://peeringdb.com/images/twitter-whatever.png" />
<meta name="twitter:label1" content="Written by" />
<meta name="twitter:data1" content="Dr Peering" />
<meta name="twitter:label2" content="Filed under" />
<meta name="twitter:data2" content="Please peer with me" />
<meta name="twitter:site" content="@PeeringDB" />
<meta name="twitter:creator" content="@PeeringDB" />
```
Open Graph (see above); but this is the one I care about:
```
<meta property="og:image" content="https://peeringdb.com/images/opengraph-whatever.png" />
```
...etc etc...

**Comment by grizz** [comment]
@peeringdb/pc et al, We need a list of any other icons you'd like added. And what the preview image should be, just a logo?

**Comment by ghankins** [comment]
It looks like we need a square preview image?  Then we should use this one.
![Icon Logo Coloured](https://user-images.githubusercontent.com/8171907/79599909-48ad3180-80b4-11ea-89ec-85c19be81107.png)

**Comment by ghankins** [comment]
If the preview image is rectangular then use our color logo that we're already using as Steve suggested above.

**Comment by koalafil** [comment]
Can we have the Release Notes pls?

**Comment by grizz** [comment]
**Release Notes**

Add opengraph image for page preview.

**Comment by koalafil** [comment]
@grizz should this move to Ready for Implementation?
