### ISSUE TITLE
Add attribute `operational` to `netixlan`

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/peeringdb#539]
Currently the semantic of a `netixlan` record is that it is operational at an `ix`. Especially in conjunction with the IX-F JSON import that may lead to unwanted side-effects as records get deleted when `net`want to give early notice to their peers that they soon will show up at an `ix`.

An additional attribute-value pair `operational` of type Boolean (default TRUE) could help.  

Implications: the IX-F JSON importer procedure (#474) has to be modified to also accept status fields which could be interpreted as provisioning.  Please note that of today, only these status are used by `ix` providing an IX-F JSON export (data taken from IXPDB)

 * active
 * connected
* inactive
* null
* operational

**Comment by mcmanuss8** [comment]
This seems like a good idea - I frequently see people who want to use peeringdb like a movie trailer ("coming soon to an IX near you...") but aren't there yet. 

For API users, adding this as another attribute makes a lot of sense.

Why only grab the operational attribute? Why not add a status attribute with all of the same values as IX-F?

How this would change what the UI displays for a given entry that is not operational might need some thought. A clock icon to indicate "waiting"? A wrench icon to indicate "being built"?

**Comment by arnoldnipper** [comment]
> Why only grab the operational attribute? Why not add a status attribute with all of the same values as IX-F?

Because these are not well-defined values. Best we could come up was something meaning "operational" (`active`, `connected` and `operational`) and "not operational" (`inactive`). Of course, IXP-M has more internal states. But do we really need more than a binary value?

> How this would change what the UI displays for a given entry that is not operational might need some thought. A clock icon to indicate "waiting"? A wrench icon to indicate "being built"?

There is not much room left for additional icons imho. Why not simply put them in _italics_?

**Comment by mcmanuss8** [comment]
> > Why only grab the operational attribute? Why not add a status attribute with all of the same values as IX-F?
> 
> Because these are not well-defined values. Best we could come up was something meaning "operational" (`active`, `connected` and `operational`) and "not operational" (`inactive`). Of course, IXP-M has more internal states. But do we really need more than a binary value?

Not for the operational use case, but it might be easier from a development perspective to align 1:1 with the external db we're trying to mirror with. Either way though, each time IX-F changes that list of statuses, we'd have to change something on our side, so maybe not any different...

> > How this would change what the UI displays for a given entry that is not operational might need some thought. A clock icon to indicate "waiting"? A wrench icon to indicate "being built"?
> 
> There is not much room left for additional icons imho. 

What if they were small? :) Something like http://www.famfamfam.com/lab/icons/silk/icons/wrench.png

> Why not simply put them in _italics_?

Too subtle, IMO. Icons are more visible and adding tooltips to them can help people figure out what they mean if they're not 100% obvious.

We can break this into 2 issues if you want - one to add the attribute on the backend/api (since I think it's most useful for automation-driven folks) and then talk about the UI in a separate issue so we don't rathole on that.

**Comment by arnoldnipper** [comment]
> > > Why only grab the operational attribute? Why not add a status attribute with all of the same values as IX-F?
> > 
> > 
> > Because these are not well-defined values. Best we could come up was something meaning "operational" (`active`, `connected` and `operational`) and "not operational" (`inactive`). Of course, IXP-M has more internal states. But do we really need more than a binary value?
> 
> Not for the operational use case, but it might be easier from a development perspective to align 1:1 with the external db we're trying to mirror with. Either way though, each time IX-F changes that list of statuses, we'd have to change something on our side, so maybe not any different...
> 

As said these values are not well-defined. And we are definitely not **mirroring** IXPDB, but cross-checking/importing some data as we do with the RIRs.

And we should have values that do make sense to our community. And it is also way easier for us to track changes in e.g. IX-F JSON imports and to react on them.

> > > How this would change what the UI displays for a given entry that is not operational might need some thought. A clock icon to indicate "waiting"? A wrench icon to indicate "being built"?
> > 
> > 
> > There is not much room left for additional icons imho.
> 
> What if they were small? :) Something like http://www.famfamfam.com/lab/icons/silk/icons/wrench.png
> 
> > Why not simply put them in _italics_?
> 
> Too subtle, IMO. Icons are more visible and adding tooltips to them can help people figure out what they mean if they're not 100% obvious.
> 

I'm not an UX expert and would leave that to them.

> We can break this into 2 issues if you want - one to add the attribute on the backend/api (since I think it's most useful for automation-driven folks) and then talk about the UI in a separate issue so we don't rathole on that.

Sounds reasonable

**Comment by arnoldnipper** [comment]
One more +1 needed to move forward, @peeringdb/pc However, implementation details would have to be ironed out, still

**Comment by grizz** [comment]
+1 and +1 for just making it a Boolean for the reasons @arnoldnipper listed.

Don't we need to iron out implementation before voting?

**Comment by arnoldnipper** [comment]
> Don't we need to iron out implementation before voting?

We should iron it out before moving to "4 Ready for Implementation". Maybe we need another issue to vote on implementation options. Makes sense?

**Comment by mcmanuss8** [comment]
I'd rather we get consensus on the implementation all in one issue for sanity's sake. :) 

I'd still like a dropdown of values instead of a boolean to make it more extensible (even if we only offer two values  for now). I'm not going to die on this hill though, if you all would strongly prefer a boolean, I can go with that. :)
Maybe we can discuss at next call briefly?

**Comment by arnoldnipper** [comment]
@mcmanuss8, I could agree if you bring up good reasoning for having more than two values for the field `operational`. Either it is or it is not. However, if you want to implement more fine-grained information we should redefine the name of the field as well.  

I'm also not inclined to discuss this at the next call as we have tons of topics to deal with.

**Comment by mcmanuss8** [comment]
+1 let's make it operational = true or false for simplicity

**Comment by arnoldnipper** [comment]
Summarize: add a boolean field `operational` to object `netixlan`.  Default TRUE.

Motivation: `net` want to give early notice to their peers that they soon will show up at an `ix`. Setting it to FALSE does also signal the IX-F JSON importer to take special caution.

**Comment by job** [comment]
sounds good, +1

> Summarize: add a boolean field `operational` to object `netixlan`. Default TRUE.
> 
> Motivation: `net` want to give early notice to their peers that they soon will show up at an `ix`. Setting it to FALSE does also signal the IX-F JSON importer to take special caution.

sounds good

**Comment by vegu** [comment]
@peeringdb/pc was there ever any conclusion reached on how this should be exposed in the UI ? 

The ASN field in the **Public Peering Exchange Points** list seems redundant now that we dropped local asn - maybe it could be a check box there similar to the `RS Peer` checkbox?

![Screenshot 2020-04-04 at 0 17 08](https://user-images.githubusercontent.com/143124/78406000-5a99c980-760a-11ea-8be0-576279f9756b.png)

**Comment by arnoldnipper** [comment]
> @peeringdb/pc was there ever any conclusion reached on how this should be exposed in the UI ?

There was not even a suggestion made, IIRC. Dropping the ASN would give room for more checkboxes. In light of #673, it could make sense to rearrange the fields. I.e. put "RS Peer" and "RS (still to come)" on the left-hand side and the operational checkbox more prominently on the righthand side.

Thoughts, @peeringdb/pc?

**Comment by grizz** [comment]
> There was not even a suggestion made, IIRC. Dropping the ASN would give room for more checkboxes. In light of #673, it could make sense to rearrange the fields. I.e. put "RS Peer" and "RS (still to come)" on the left-hand side and the operational checkbox more prominently on the righthand side.

That makes sense to me, so it'll just be a second check box to the right of RS Peer, right?

**Comment by mcmanuss8** [comment]
Since the vast majority of records will be operational, how about we show text or an icon indicating when operational == false, only? 

Strawmen suggestions to fit in the little space we have there:
"Not up"
"Non-Op"
an x like this: https://i7.pngguru.com/preview/175/854/505/computer-icons-button-check-mark-cross-red-cross.jpg

**Comment by grizz** [comment]
I like that idea, @arnoldnipper @peeringdb/pc what do you think?

This is going to beta on Friday so we would like the answer ASAP

Thanks

**Comment by arnoldnipper** [comment]
> Since the vast majority of records will be operational, how about we show text or an icon indicating when operational == false, only?

Excellent idea! +1000

**Comment by ynbrthr** [comment]
On Tue, Apr 7, 2020 at 12:24 PM Arnold Nipper <notifications@github.com>
wrote:

> Since the vast majority of records will be operational, how about we show
> text or an icon indicating when operational == false, only?
>
> Excellent idea! +1000
>

like it. +1

**Comment by mcmanuss8** [comment]
Great - what should the text or icon be? 

Some other text ideas:
"Future"

Some other icon choices:
http://www.famfamfam.com/lab/icons/silk/icons/wrench.png
http://www.famfamfam.com/lab/icons/silk/icons/cancel.png
http://www.famfamfam.com/lab/icons/silk/icons/cog_error.png
http://www.famfamfam.com/lab/icons/silk/icons/error.png

**Comment by ynbrthr** [comment]
On Tue, Apr 7, 2020 at 1:58 PM mcmanuss8 <notifications@github.com> wrote:

> Great - what should the text or icon be?
>
> Some other text ideas:
> "Future"
>
> Some other icon choices:
> http://www.famfamfam.com/lab/icons/silk/icons/wrench.png
> http://www.famfamfam.com/lab/icons/silk/icons/cancel.png
> http://www.famfamfam.com/lab/icons/silk/icons/cog_error.png
> http://www.famfamfam.com/lab/icons/silk/icons/error.png
>

how about ‘in prov’ or ‘prov’ for the text? i like the wrench or the cog
for the icon, but you’ll want someone else’s opinion for UI matters

- y

> <http://www.famfamfam.com/lab/icons/silk/icons/error.png>
>

**Comment by grizz** [comment]
-1 on the Wrench, it makes me think it's able to be configured. :)

I like cog_error or error.

**Comment by vegu** [comment]
@peeringdb/pc 

For now we went with the most similar glyphicon we had for the `error` icon suggested - You can view others icons readily available in our current implementation [here](https://getbootstrap.com/docs/3.3/components/#glyphicons-how-to-use)

### Network View
![Screenshot 2020-04-10 at 11 54 42](https://user-images.githubusercontent.com/143124/78978388-57c73900-7b22-11ea-84cf-0a01b4c1f936.png)

### Network Editor
![Screenshot 2020-04-10 at 11 54 48](https://user-images.githubusercontent.com/143124/78978390-585fcf80-7b22-11ea-9d5f-a3714f0c59f1.png)

### Exchange View
![Screenshot 2020-04-10 at 11 54 31](https://user-images.githubusercontent.com/143124/78978386-56960c00-7b22-11ea-871d-a709a139da89.png)

**Comment by arnoldnipper** [comment]
Like it very much ... +1

**Comment by arnoldnipper** [comment]
**Release note**
This is a new feature and allows networks to give early notice to their peers that they soon will show up at an IXP.  A check box is added when adding a new IXP connection.  By default, a connection is considered `operational` and the box is ticked. When the connection is still in the provisioning mode, please untick the box. When viewing the warning glyphicon is shown right to the network name. The API object `netixlan` is enhanced by the boolean field `operational` defaulting to `true`. 

This feature is in line with the [Data Ownership Policy](https://docs.peeringdb.com/gov/misc/2020-04-06_PeeringDB_Data_Ownership_Policy_Document_v1.0.pdf)

**Comment by mcmanuss8** [comment]
Looks great. Nice job!
