### ISSUE TITLE
www.peeringdb.com Certificate Expired

### ISSUE THREAD

**Issue by esundberg** [peeringdb/peeringdb#54]
The certificate is expired Valid from 8/11/2015 to 9/2/2016

**Comment by grizz** [comment]
Which certificate? The wild card was renewed and installed.

**Comment by esundberg** [comment]
The certificate is for
*.peeringdb.com
Issued by ESET SSL Filter CA
Valid from 8/11/2015 to 9/2/2016

I am just browsing to the website. I get the issue in both chrome and IE.

![image](https://cloud.githubusercontent.com/assets/14306155/18238993/b6d5728a-7307-11e6-9fb2-cc6dbaaa0945.png)

**Comment by grizz** [comment]
I can't reproduce it at all, guessing it's client side, what IP does it resolve to for you?

https://www.ssllabs.com/ssltest/analyze.html?d=www.peeringdb.com

**Comment by job** [comment]
#worksforme

**Comment by esundberg** [comment]
Sorry for the fire drill on the certificate being expired. For some reason the PC is not downloading new root certificates and certificates from the site.
