### ISSUE TITLE
When looking at a network record, show last updated ix<->net or fac<->net date

### ISSUE THREAD

**Issue by mcmanuss8** [peeringdb/peeringdb#541]
When looking at https://peeringdb.com/net/979 today it says Last Updated 2018-06-29T03:04:55Z. But we have added IXes and Facilities since that date.  This confused a user, thinking we had a stale peeringdb record.

Consider showing the last association record update date in addition to the date we updated the net record. Related: #526

**Comment by arnoldnipper** [comment]
Not sure I like to update the `net` record. Instead, there should also be a "last updated" for `netixlan` (aka "Public Peering Exchange Points") and `netfac` (aka "Private Peering Facilities"). Thus, we would have much more differentiated information.

Same should be done for ixes and facs ("Peers at this Exchange Point" and "Networks")

**Comment by mcmanuss8** [comment]
I agree we wouldn't want to update the actual last updated field on the net record, this is more about what we'd display in the UI. Maybe something like:

**Last Updated:** 2018-06-26T...
**Interconnection Info Updated:** 2019-08-08T...

**Comment by mcmanuss8** [comment]
@peeringdb/pc opinions please? Specifically I'm proposing we add an additional field here to more accurately reflect how up to date a network is keeping their records.

**Comment by arnoldnipper** [comment]
Still +1 ... but I'm a bad UX designer and leave it up to you where to put it. This also includes to put this information aside `ix` and `fac`.

**Comment by arnoldnipper** [comment]
@mcmanuss8 would you mind speccing this more out? For which records? IMHO almost all, but definitely for `ix`, `fac`, `netixlan`, and `netfac`.

**Comment by mcmanuss8** [comment]
Unfortunately we only have a Last Updated field visible in the ui on /net/ . I won't try to boil the ocean and add similar fields to the other objects in this issue (but I think we should!). Will fork off #675 to handle those.

So for now I propose:

1) Add two new fields (in this order): 
    a) Public Peering Info Updated:  
    b) Peering Facility Info Updated: 
    c) Contact Info Updated: 

2) Display these fields on the UI directly below the Last Updated field (above Notes)
3) Calculate a) based on the most recently updated netix/netixlan update for this net
4) Calculate b) based on the most recently updated netfac update for this net
5) Calculate c) based on the most recently updated poc_set record for this net

Since these fields are calculated based on existing values in the API, we shouldn't need to expose dedicated values for them.

**Comment by arnoldnipper** [comment]
+1 ... but I'm all for it to have dedicated fields as well. Remember that we also have net_count and the like which can even be easier derived from existing fields.

**Comment by mcmanuss8** [comment]
I'm ok with dedicated fields if it's easy to add them. @grizz any opinions?

**Comment by arnoldnipper** [comment]
> I'm ok with dedicated fields if it's easy to add them. @grizz any opinions?

Imo it should be as easy as counting objects. E.g.

```curl -sG https://peeringdb.com/api/netixlan --data-urlencode net_id=541 --data-urlencode fields=updated | jq '[.data[] | .updated] | max' "2020-02-05T13:53:11Z"```

**Comment by grizz** [comment]
To summarize, we'll add fields to the net object, and update the datetime when any records are updated.

**Comment by ccaputo** [comment]
When a netixlan update (net at an ix) happens, should that push the network up the list on the landing page?  I think it should, since that would be useful for alerting the world to a network's new presence, but what do others think?

**Comment by arnoldnipper** [comment]
> When a netixlan update (net at an ix) happens, should that push the network up the list on the landing page? I think it should, since that would be useful for alerting the world to a network's new presence, but what do others think?

I wouldn't do so. For two reasons

 * to be fair you would have to take into account updates for `netfac` as well
 * if you look at the top 5 even at a weekend, the oldest is only some hours old. So it becomes more and more useless

**Comment by ccaputo** [comment]
> > When a netixlan update (net at an ix) happens, should that push the network up the list on the landing page? I think it should, since that would be useful for alerting the world to a network's new presence, but what do others think?
> 
> I wouldn't do so. For two reasons
> 
> * to be fair you would have to take into account updates for `netfac` as well

Agreed.

> * if you look at the top 5 even at a weekend, the oldest is only some hours old. So it becomes more and more useless

Good point.  I guess the question begs how useful those landing page updates are, and is the goal to raise awareness about policy or contact other non-netixlan & non-netfac changes.

**Comment by arnoldnipper** [comment]
> Good point. I guess the question begs how useful those landing page updates are, and is the goal to raise awareness about policy or contact other non-netixlan & non-netfac changes.

Looking at `net`,  `netixlan` and `netfac` updates the last seven days I get

```
date    #updates
2020-10-05      104
2020-10-06      157
2020-10-07      92
2020-10-08      182
2020-10-09      152
2020-10-10      51
2020-10-11      18
```

I.e. on busy days the top 5 would rotate through in ~40 minutes. If only looking at `net` updates I see

```
date    #updates
2020-10-05      49
2020-10-06      40
2020-10-07      41
2020-10-08      67
2020-10-09      47
2020-10-10      19
2020-10-11      12
```

Which means that the top 5 rotates through in 1h50.

Imho it's nice to have these figures to show that PeeringDB is being used.
