### ISSUE TITLE
User had issue adding facility, got error message when trying to click add facility button

### ISSUE THREAD

**Issue by netravnen** [peeringdb/peeringdb#542]
```
I get the autocompletion suggestion and can select e-shelter. But after clicking on „Gebäude hinzufügren“ I get the following error:

> Etwas ist schief gelaufen.
>
> Der Server hat Ihre Daten zurückgewiesen
> Die Felder network, facility, local_asn müssen eine eindeutige Menge bilden.
```

![image](https://user-images.githubusercontent.com/1938389/62791761-1d5a5780-bace-11e9-97c3-825cf1ff9ca1.png)

User searches and selects `e-shelter Frankfurt (FRA1)` from the search drop-down menu.
Kliks the add facility button below.
Gets the error message shown at the top.

Was [my-self] unable to re-produce.

Ticket: https://peeringdb.deskpro.com/agent/#app.tickets,inbox:archive_resolved,t.o:31955,vis:7

**Comment by arnoldnipper** [comment]
Which ASN?

**Comment by netravnen** [comment]
> Which ASN?

61381

**Comment by vegu** [comment]
@netravnen did this get resolved ? The error message indicates that the net -> fac connection already existed. I think a better non-developer friendly error message is definitely needed.

**Comment by arnoldnipper** [comment]
Same issue as #580
