### ISSUE TITLE
Firefox: line break in table at : in IPv6 addresses (cosmetic)

### ISSUE THREAD

**Issue by funkestefan** [peeringdb/peeringdb#543]
Firefox adds weird line breaks in long IPv6 addresses which leads to copy&paste errors for users. I can not see that behavior in Chrome. (#31986)

Wrong (Firefox):
![pdb-linewrap](https://user-images.githubusercontent.com/20709293/62830455-cfe60380-bc0f-11e9-9100-b070e17d0e80.png)

Better (Chromium):
![pdb-no-linewrap](https://user-images.githubusercontent.com/20709293/62830467-f60ba380-bc0f-11e9-99c3-53bad4c6f6b4.png)

Example taken from nl-ix (https://www.peeringdb.com/ix/64)

**Comment by arnoldnipper** [comment]
I see the same with Chrome. My proposal

 * remove `ixlan` info as it will go away soon

 * shorten box for "netname"

 * enlarge box for IPv4/6 information
![AwesomeScreenshot-www-peeringdb-ix-64-2019-08-11_8_24](https://user-images.githubusercontent.com/16888757/62837992-8bda1980-bc76-11e9-995f-808a3f5c596e.png)

**Comment by mcmanuss8** [comment]
I think a simple CSS change can fix this. Changing sites.css ip6 class from word-break: break-all; to word-break: normal; seems to fix the issue (see screenshot).

![Screen Shot 2019-08-20 at 5 55 44 PM](https://user-images.githubusercontent.com/5892502/63387591-d4c75780-c373-11e9-8be6-a2a51e425c90.png)

I'll put in a pull request for this now

**Comment by mcmanuss8** [comment]
So the IX LAN name after the IX Name is causing the Exchange column to be really wide in the case of https://peeringdb.com/net/457

A solution could be to remove the ASN below the IX name and put the IX LAN name there, which would shorten the width of the Exchange name significantly.

Alternatively, we could fiddle with the css more and see how to make the exchange column wrap cleanly.

**Comment by job** [comment]
have we ever considered the option of contracting a UI expert to help with
questions like these?

I think we all agree that the current linebreak is not optimal, but words
overlapping each other isnt either, and there is limit real estate on our
tablets/laptops/phones. I'm sure we arent the first ones with this type of
issue with tabular data.

**Comment by mcmanuss8** [comment]
I had the exact same thought as I was working on it, but my UI engineer had already left for the day. I’ll see if he’s willing to volunteer some time on this

**Comment by arnoldnipper** [comment]
We have these issue with the `ix` view and the `net` view. Luckily ix names tend to be quite short compared to net names.

`curl -sG https://peeringdb.com/api/ix --data-urlencode fields=name | jq '[.data[].name | length] | unique | max'
42`

compared to

`curl -sG https://peeringdb.com/api/net --data-urlencode fields=name | jq '[.data[].name | length] | unique | max'
109`

So making the space for Exchange name a bit smaller, dropping `ixlan` name  (as we are going to single `ixlan` anyway in near future) could do the trick for the `net`view.

I guess that could also work for the `ix` view. Net names are significantly longer, but I guess that's because net names consist of several words generally. And we breaking net names in more than one line is fine.

And strong +1 having an UI/UX expert looking at our GUI at all. E.g. 90% of all requestors don't understand what the "Add Facility" and "And Exchange" tab at the `org` view is for.

**Comment by grizz** [comment]
+1 

@peeringdb/pc what say you?

**Comment by shane-kerr** [comment]
I'm not sure exactly what the PC is being asked to vote on.

The IPv6 breaks have been fixed.

There have been at least 3 other proposals on the closed ticket:

- Move ASN below the IX name
- Get a UI/UX expert to do... something
- Reducing width of Exchange, dropping ixlan name

Maybe we should cut another ticket for UI/UX tweaks and maybe a separate one for what we want a UI/UX expert to provide?

**Comment by arnoldnipper** [comment]
> Maybe we should cut another ticket for UI/UX tweaks and maybe a separate one for what we want a UI/UX expert to provide?

I'm happy to get this issue stolen, @shane-kerr. Then do as you like :) TIA for your support

**Comment by grizz** [comment]
> I'm not sure exactly what the PC is being asked to vote on.
> 
> The IPv6 breaks have been fixed.

Oh, I missed that, thanks.

> There have been at least 3 other proposals on the closed ticket:
> 
> * Move ASN below the IX name
> * Get a UI/UX expert to do... something
> * Reducing width of Exchange, dropping ixlan name
> 
> Maybe we should cut another ticket for UI/UX tweaks and maybe a separate one for what we want a UI/UX expert to provide?

I like that idea, to start with, we could have a UX expert do a once over on all of PDB and give us advice, then create a ticket for the tweaks?

**Comment by arnoldnipper** [comment]
IPv6 issue is fixed ... UX issues are addressed in a separate ticket
