### ISSUE TITLE
containerize server

### ISSUE THREAD

**Issue by grizz** [peeringdb/peeringdb#548]
Will make deploys a lot easier, and pave the way for automatic test instances to be done how @job would like them.

**Comment by mcmanuss8** [comment]
+1 containerize please. I would really like us to be able to set up a test environment for developers with a single click/cli run, too, and I suspect that would make this easier

**Comment by grizz** [comment]
**Release Summary**

Internal software deployment system has been changed to use containers which reduces time spent by the ops team for deployments, allows for better scaling, and reduces the cost of entry for new developers to write and test their code.
