### ISSUE TITLE
Suggestion - Provide an option(checkbox) so that volunteers can add records & messaging

### ISSUE THREAD

**Issue by swapneelp** [peeringdb/peeringdb#549]
At this point of time, there is no such option so the system implies that the network operator himself is adding the entry. So if a volunteer adds on behalf of a network operator, It further confuses them as the message indicates it's somewhat of a takeover !

For example, as a volunteer, when I made an entry for a ASN which doesn't belong to me, following was the subject of the email sent to me as well as the AS owner. 

`User pswapneel wishes to request ownership of ORGNAME`

This is both confusing for network operators as it clearly doesn't indicate the objective. 

Perhaps, the changed wording could be, 

`User pswapneel  volunteered to add details of ORGNAME in PeeringDB. Please verify`

**Comment by arnoldnipper** [comment]
But how to distinguish requests coming from owners and requests coming from 3rd parties. If you are going to help operators please talk to them in advance!

**Comment by grizz** [comment]
> If you are going to help operators please talk to them in advance!

Agreed, please work directly with operators so they own and have access to their PDB records.

**Comment by arnoldnipper** [comment]
So, this is a -1, @grizz? We would need another -1 to turn this request down, @peeringdb/pc

**Comment by anuragbhatia** [comment]
Would also like to see the change in the language. We can all ask networks to be on peeringdb who aren't and that's somewhat unrelated to this specific issue. 

Using a better language which doesn't say that volunteer has "claimed ownership" but instead "$user has volunteer to add your organisation on peeringdb".

**Comment by swapneelp** [comment]
@arnoldnipper @grizz I am going to try to make my case again and hope that there isn't a -1 :-) 

Here is the real-case scenario, the network operators that I know are based out of Tier-II and Tier-III cities in India. To be honest, even with the education, they don't necessarily care about having information in peeringdb unless business stops ! 

The only request I would make again is perhaps to look at changing the messaging that gets sent out to the operator. This way, more volunteers can add records in the database. Hope this strikes as a useful case. If not, no worries 👍

**Comment by arnoldnipper** [comment]
@swapneelp again: get in touch with the network operator **before**you affiliate with the ASN and **get** their permission to do so. I'm in discussion with IXes to create a sort of proxy. Maybe you will be able to use that proxy for helping networks. Until then there is nothing we can do for you.

**Comment by arnoldnipper** [comment]
> Would also like to see the change in the language. We can all ask networks to be on peeringdb who aren't and that's somewhat unrelated to this specific issue.

@anuragbhatia, that's what we are already doing via the @peeringdb/outcom when we are at events and on social media. What else do you have in mind?

**Comment by grizz** [comment]
> So, this is a -1, @grizz? We would need another -1 to turn this request down, @peeringdb/pc

Apologies -- this request goes against the core tenet of PDB that the networks control their records in the DB and violates the Data Ownership Policy, so I didn't think we needed quorum to deny.

In the future, I'll follow process regardless. :)

-1 from me

**Comment by grizz** [comment]
@swapneelp I'm sorry if I came across as rude, getting other networks to register and use PDB is a noble cause for sure, you'll just have to go about it differently and teach them how to do it. :)

**Comment by swapneelp** [comment]
@arnoldnipper No problem !

@grizz Just to clarify, the intention (speaking as a volunteer) isn't to control the records of the operator, but merely to initiate the process so that the network operator can be then be guided to add the records themselves or the volunteer adds them which is verified/approved by the network operator. 

You can go ahead and close this one. Thanks!

**Comment by grizz** [comment]
@swapneelp Sure, as I said, it's a good cause and I didn't think you wanted to "control" anything. The problem is, there are networks that purposefully don't want their information listed in PDB, and we respect that by making sure only the ASN owners are allowed to enter information.

You can certainly encourage networks to add their data, or have them claim an ASN and delegate permissions to you to update information, that's completely up them.

Cheers
