### ISSUE TITLE
After merging organisations users default back to "member"

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/peeringdb#55]

**Comment by grizz** [comment]
That's by design, admins in the "parent" org keep admin, anything merged in goes to member. Is there a reason to change it?

**Comment by arnoldnipper** [comment]
On 07.09.2016 11:37, Matt Griswold wrote:

> That's by design, admins in the "parent" org keep admin, anything merged
> in goes to member. Is there a reason to change it?
> 

This concept of "parent" org is only in your head. For the cases I so
far encountered it was not valid.

E.g.: the current org is "BCIX". I create "BCIX Management GmbH" which
is the proper name of the org. This org only has a name. I then merge
BCIX into the newly created org.


Arnold

**Comment by grizz** [comment]
In the cases I've used it, the person requesting the merge wanted to remain admin and be free to update permissions. Either way, org merge is such a corner case, is it really worth spending time on it?
