### ISSUE TITLE
Suggestion - Page for Why have details in Peeringdb? in email sent to network operator

### ISSUE THREAD

**Issue by swapneelp** [peeringdb/peeringdb#550]
When a volunteer adds a record on behalf of a network operator, in the email which is sent out to the network operator, perhaps have a link to a page `Why have details in Peeringdb?` as network operators whom I have communicated with in Tier-II and Tier-III cities aren't aware of peeringdb and it's value.

**Comment by eloos** [comment]
Don't we have something from outreach on this? @ghankins

**Comment by ghankins** [comment]
We have these pages:
https://www.peeringdb.com/about
https://docs.peeringdb.com/faq/

We need to update the FAQ to be more helpful, but you could use the URL starting now as it won't change.

**Comment by grizz** [comment]
+1

@ghankins could the OC take ownership of this and write something up?

**Comment by arnoldnipper** [comment]
+1 and happy to shepherd this as I'm also a member of OC (why isn't there an OC team in Github?)

**Comment by ghankins** [comment]
Do we need something more than https://www.peeringdb.com/about?

If we add more content, we should add it to the about page as well so the content is consistent.

**Comment by arnoldnipper** [comment]
@ghankins and @peeringdb/outcom, I would keep the [about page](https://www.peeringdb.com/about) clear and concise. From there we would link to a separate page with more information. Could that make sense?

**Comment by ghankins** [comment]
I think Arnold's suggestion makes sense then.  The about page also has stuff about the PeeringDB culture which isn't relevant to why you should be in PeeringDB.

**Comment by grizz** [comment]
Oh, I figured you could just add it to the FAQ and thus wouldn't need PC approval, sounds like you have it under control. :)

**Comment by ghankins** [comment]
Yeah we could add it to the FAQ, and then just send a link to that section in the email.

**Comment by mcmanuss8** [comment]
This seems like something you guys can self-service, @ghankins. If not, reopen?

**Comment by arnoldnipper** [comment]
> This seems like something you guys can self-service, @ghankins. If not, reopen?

Sure, @peeringdb/outcom can. But as this is an external request I propose to keep it open until finalized. Does that make sense somehow?

**Comment by arnoldnipper** [comment]
As @leovegoda is working on this now I close this issue
