### ISSUE TITLE
PeeringDB AUP Update: Ban political discussion

### ISSUE THREAD

**Issue by tpaseka** [peeringdb/peeringdb#551]
Some PeeringDB records are being created to sow political discord. This isn't what the platform is about and should not be tolerated.

![image](https://user-images.githubusercontent.com/2107473/63370682-9744d900-c337-11e9-9a07-8455412349e7.png)

In this case, PeeringDB clearly uses ISO-3166-2 Alpha and does not take a position on what is or isn't a country. Simply what is used as defined by this ISO standard.

**Comment by job** [comment]
I’d like to propose this discussion is held on the pdb-gov@ mailing list.

If any software actionable items come from that discussion we can use
GitHub to track progress.

The AUP contents aren’t decided through GitHub.

**Comment by lshiychina** [comment]
The official name of the standard is Codes for the representation of names of countries and their subdivisions.
so the name should be "country / region" not only "country" to prevent political arguments.

**Comment by job** [comment]
In any regard, discussion will take place on PDB-gov@ mailing list
