### ISSUE TITLE
Add text to https://peeringdb.com/suggest/fac

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/peeringdb#554]
Should read

Suggest Facility to be added to the database. Your suggestion will be reviewed by the PeeringDB Administration Committee. It will then either be finalized and entered into the database, or declined. No further action is required on your part.

In order to be approved, we would expect that the suggested Facility offers colocation, data center and/or meet-me-room services to the public.

**Only use this if you don't own the Facility. If you own it, please use "Add Facility" under your organization record.**

**Comment by eloos** [comment]
+1

**Comment by grizz** [comment]
+1

**Comment by mcmanuss8** [comment]
+1

**Comment by shane-kerr** [comment]
+1 (better late than never)
