### ISSUE TITLE
Notes field translate button disappears

### ISSUE THREAD

**Issue by vegu** [peeringdb/peeringdb#555]
Likely a bug introduced when we switched to javascript only markdown rendering in #221 - the button is there for a moment then disappears

**Comment by grizz** [comment]
+1 -- @peeringdb/pc vote please

**Comment by shane-kerr** [comment]
+1

**Comment by arnoldnipper** [comment]
+1

**Comment by arnoldnipper** [comment]
**Release note**
This is a bug fix. The "Translate" button is there for a moment and then disappeared.
