### ISSUE TITLE
Show all languages on beta, even if translation is not ready for prod

### ISSUE THREAD

**Issue by mcmanuss8** [peeringdb/peeringdb#557]
Summarizing email thread into github.

As a translator, it is difficult to see what the text looks like in the site (versus just the strings in the translation site). 
We don't want to show all languages in prod until they're ready.
Ops doesn't want to spin up another hostname just for translators to view the results of translation.

A compromise seems to be to show all languages on beta.peeringdb.com with a little warning above the language selector indicating that not all languages are ready for production. Ideally we would also say which ones those are.

**Comment by arnoldnipper** [comment]
+1

**Comment by grizz** [comment]
+1

**Comment by grizz** [comment]
+1

**Comment by ericandrei** [comment]
Showing translations on beta would mean that users can login. I cannot login to the beta website.

**Comment by arnoldnipper** [comment]
> I cannot login to the beta website.

@ericandrei would you mind to open a ticket with support@peeringdb.com.  Both accounts are in beta

**Comment by grizz** [comment]
+1 and I'd be in favor of doing any hourly sync from translate.peeringdb.com

**Comment by arnoldnipper** [comment]
+1 for hourly sync from translate.peeringdb.com

**Comment by arnoldnipper** [comment]
**Release note**
As soon as a new [translation](https://translate.peeringdb.com/languages/) is starting it is available on the [beta](https://beta.peeringdb.com/) to help the translators and to encourage the community for input.
