### ISSUE TITLE
fix `pdb_stats` command for past dates

### ISSUE THREAD

**Issue by vegu** [peeringdb/peeringdb#558]
Running `manage pdb_stats` to generate stat summary misses some objects.

The cause of this is an issue were some object's history snapshots miss the status change from `pending` to `ok`, since the command goes through the history to get the object's state at a specific date those objects are not counted.

This should be fixed by finding out why those status changes are missing from historic data and fixing that issue.

Edit: Fixing the command to work correctly when no date parameter is supplied (generate for current date) is now tracked separately in #560

**Comment by ccaputo** [comment]
This script is run daily at 2359 UTC without a date parameter.  Its current results are not matching the web site.  For example:

pdb_stats.py:

2019-09-03
fac: 3008
net: 16189
org: 16231
users: 22529
ix: 662

versus web site on that date:

Global System Statistics
696 Exchanges
16447 Networks
3342 Facilities
29083 Connections to Exchanges
26835 Connections to Facilities

That discrepancy is important to fix.

Regenerating for past dates is not urgent, but it would be good to get that fixed too so queries by date can work.

**Comment by vegu** [comment]
@ccaputo  in that case i suggest we split this into two tickets, since fixing the command to work correctly when no date parameter is submitted should be quick, while fixing the archived data issue is likely going to be more complicated.

**Comment by ccaputo** [comment]
Fine with me.  Please do so.

**Comment by vegu** [comment]
@ccaputo fixing pdb_stats with current/no date parameter is now tracked in #560

**Comment by arnoldnipper** [comment]
+1

**Comment by mcmanuss8** [comment]
+1

**Comment by grizz** [comment]
+1

**Comment by ccaputo** [comment]
Past dates don't seem to be accurate.  Daily at 2359 we perform:

  /tmp/pdb_stats.lock /srv/www.peeringdb.com/bin/manage pdb_stats >> /efs/logs/pdb_stats

Last 3 days from /efs/logs/pdb_stats:

2019-12-27
fac: 3509
ix: 725
net: 17527
org: 17187
users: 24082

2019-12-28
fac: 3509
ix: 725
net: 17529
org: 17188
users: 24086

2019-12-29
fac: 3509
ix: 724
net: 17532
org: 17191
users: 24088

But "/srv/www.peeringdb.com/bin/manage pdb_stats --date 20191227" results in:

2019-12-27
fac: 3132
ix: 689
net: 17277
org: 17240
users: 24084

Mismatches for other dates too.

**Comment by grizz** [comment]
We'll check it out tomorrow.

**Comment by vegu** [comment]
@ccaputo looks like we hadn't run the retroactive status fix for archived data yet.
 
Done that now, and numbers are now more inline - however there appears to be still some small discrepancy for ix (+6) and fac (+2) objects that i haven't managed to track down yet.

```
2019-12-28
-------------
fac: 3511
ix: 731
net: 17529
org: 17242
users: 24087

2019-12-27
-------------
fac: 3511
ix: 731
net: 17526
org: 17240
users: 24084
```

**Comment by vegu** [comment]
@ccaputo had a small oversight in the retroactive adjustments - fixed it and numbers should now be accurate.

The remaining discrepancies are very likely due to the current date cronjob being run at a specific time versus the past date report being generated for 23:59:59 (end of day)

Please review on your end as well, and let us know if you disagree with the above.

```
2019-12-27
-------------
fac: 3509
ix: 725
net: 17525
org: 17186
users: 24084

2019-12-28
-------------
fac: 3509
ix: 725
net: 17528
org: 17188
users: 24087

2019-12-29
-------------
fac: 3509
ix: 725
net: 17531
org: 17191
users: 24088
```

Also did a test for current using both methods

without `--date`

```
2020-01-02
-------------
fac: 3508
ix: 725
net: 17549
org: 17208
users: 24106
```

with `--date=20200102`

```
2020-01-02
-------------
fac: 3508
ix: 725
net: 17549
org: 17208
users: 24106

**Comment by ccaputo** [comment]
The daily stats run at 2359 UTC so I am not sure I agree.  We need accurate numbers for 12/31 for the following years for the infographic being produced.  Can you help us with accurate numbers for 12/31/2019, 12/31/2018, 12/31/2017, 12/31/2016 using the fixed script?

Thanks!

**Comment by vegu** [comment]
@ccaputo the fixes i did earlier today were fixes to the archived data, not the `pdb_stats` script itself, so the `pdb_stats` script on prod0 should produce accurate numbers now.

regarding the few discrepancies remaining, we can look into it more, there might as well be some other bug going on, however if you look at the final test i did it's producing identical number generating for current date with and without the --date option

**Comment by ccaputo** [comment]
Right now the one difference I see is that when the script was run at 2359 UTC on 12/31/2019 as "/srv/www.peeringdb.com/bin/manage pdb_stats" it indicated 24101 users.

But if run as "/srv//www.peeringdb.com/bin/manage pdb_stats --date=20191231" it indicates 24105 users.

Which result should be trusted as being most accurate?

Also, when I run it for 20181231 and previous new years eves, I get results different than previously documented in our published infographic.  Are the results in the current script run with date more accurate than our previously published numbers?  I just want to make sure before we change the numbers to better reflect reality.

**Comment by arnoldnipper** [comment]
Are both timestamps really identical? Maybe 20191231 is 20191231T00:00:00Z

**Comment by vegu** [comment]
@ccaputo and @peeringdb/20c had further communication via email, here is what was found:

The issue with the unstable user count when generating for past dates comes from the fact that we count verified users only and have no way to see a user's status of verification for a given past date.

Right now the command will return all users created before/at the specified date that were verified at the time when the command was run, causing this slight deviation in numbers over time.

As a practical example, if i a user signed up on 31st Dec, but only got verified on Jan 4, running the pdb_stats command for dec31 on jan5 will now show that user in the count, when it did not earlier.

**Notes**

- Verification here means email is verified and user is part of at least one organization
- User counts generated for current date should always be accurate
- In order to fix we would need to add logging for user verification state changes

**Comment by ccaputo** [comment]
From my perspective, I don't see a need to do the work to have a perfect user count by date, so I added the following to internal notes: NOTE 2020-01-04: the 'user' count varies depending on when the script is run, since it is based on approval and org affiliation, thus it is important to consistently use the count from [pdb_stats.json] which is emailed to sponsorship@peeringdb.com on the first of the new year.

Closing this... :-)
