### ISSUE TITLE
fix locale config gen to loop over anything passed

### ISSUE THREAD

**Issue by grizz** [peeringdb/peeringdb#565]
Currently it uses `if` for each locale, and then sets the displayed version. It should read the `locale` list and generate anything given.

**Comment by grizz** [comment]
Should also allow for enabling all languages.

**Comment by ccaputo** [comment]
> Should also allow for enabling all languages.

Enable _all_ languages, or just those in the https://github.com/peeringdb/translations repo?  I'm thinking the later.

**Comment by arnoldnipper** [comment]
Enabling all languages which are in translation.

**Comment by grizz** [comment]
This will be invalidated and that functionality added with #557
