### ISSUE TITLE
Click to copy certain fields

### ISSUE THREAD

**Issue by mcmanuss8** [peeringdb/peeringdb#567]
Add some JS to copy a field. Add it to some fields that are commonly copied from the UI:

- IP addresses & CIDRs
- ASNs
- Email addresses
- Phone #s

**Comment by eloos** [comment]
@mcmanuss8 isn't this cluttering the interface? Are there issues with selecting and copying by mouse??

**Comment by mcmanuss8** [comment]
It wouldn't be a separate button, it would just popup with a tooltip on hover. So you move your mouse over the IP and it would say "Click to copy to clipboard". Clicking it would add it to your clipboard.

**Comment by grizz** [comment]
@peeringdb/pc Votes? I'm not for this, but not strongly enough to -1

**Comment by job** [comment]
I am not sure either what is solved (or proposed for that matter), on my machine when I double click a ASN or an IP address the element is selected and I can press cmd-c / ctrl-c whatever the local keyboard shortcut is for copying to the clipboard. 

(openbsd / x11 / chromium here)

**Comment by mcmanuss8** [comment]
Maybe this will help? 

Here I'm trying to copy an IPv6, and then an IPv4 address out of the UI in Chrome on a mac. If it's v4, not too bad, double clicking works, then I can hit command-C and copy it. If it's v6, I have to drag across the length of the string, then hit command-C

In this issue the idea is you'd move your mouse over the address (or other fields we think are worth copying like phone numbers?) and a "click here to copy" tooltip shows up. You click that and save a few seconds per copy. If you do lots of copying and pasting from peeringdb, because you're not API-savvy, this could save you lots of time. 

![out3](https://user-images.githubusercontent.com/5892502/74380238-357d9d00-4db7-11ea-8b00-d104e5531371.gif)

**Comment by leovegoda** [comment]
The Product Committee has decided to close this issue. There was no agreement on the concept and the issue has not been discussed for six months or longer.
