### ISSUE TITLE
How do we secure personal data going forward?

### ISSUE THREAD

**Issue by asbjornst** [peeringdb/peeringdb#568]
Starting a new issue, as this is not about fixing #566, but how to avoid the next one.

Background: feature #451 inadvertently enabled the privacy leak in #566?

To quote @arnoldnipper from the support ticket `2019UA8KJ` leading up to #566:
> Revealing `deleted`records only has been introduced with the last role out. And I guess no one has thought about any GDPR issues associated with this. Are there any? The answer is not that simple but definitely needs discussion.

Just like all RFC's have a "Security Considerations" section, and newer ones have a "Privacy Considerations" subsection ([RFC6973](https://tools.ietf.org/html/rfc6973)), unless it's blatantly obvious not needed (like the whole document is focused on privacy).

If someone have to consider the implications, and in most cases just write "There are none".
The PC could then question it, if they disagree or have concerns with the assertion.

Do we believe that #566 would have been caught if someone would have had to write a statement about the privacy implications of #451? Or do we believe that distant memories of #566 is enough to avoid the next one?

**Comment by asbjornst** [comment]
@job, it's fine if the submitter is presenting a solution. In case that the submitter doesn't have enough knowledge about PeeringDB, to evaluate it and writes "I don't know", then it still helps by raising a red flag, that needs to be figured out in the comments.

If the submitter is presenting a problem, with an open solution, it might not work as well. Unless the solution is presented in a new issue.

It might also be useful to use a label to mark issues with unresolved privacy/GDPR questions.

**Comment by job** [comment]
Your analysis is good. Even if the problem submitted says “I don’t know”,
the PC will see that the problem submitter didn’t know and thus remember
that the PC should be aware and know.

I kind of expect that over time we will more and more be mindful of GDPR;
because it doesn’t only impact work in peeringdb, but many of us have to
deal with it in context of our professional life.

If we change anything (and I am not sure we should), I think it should be
in a soft way.

**Comment by arnoldnipper** [comment]
@asbjornst and @job, what about we add a check to milestone 3a for "Privacy Considerations"? @peeringdb/pc, what do you think?

**Comment by arnoldnipper** [comment]
@asbjornst you now have to use a [template](https://github.com/peeringdb/peeringdb/issues/new?assignees=&labels=&template=bug_report.md&title=) to open an issue. And both templates query for
- Are there security concerns?
- Are there privacy concerns?

Hence, I'm closing this issue now
