### ISSUE TITLE
Inclusion of the field "Country"

### ISSUE THREAD

**Issue by jaapbr** [peeringdb/peeringdb#57]
Change Proposal: 
To include the "Country" field in the "Public Peering Exchange Points" for a given "Network" record.

Goal:
It would help to evaluate presence of the selected "Network" supporting decisions of network expansion.

Advantage:
Increases facility in the use of the database for strategic peering evaluation.

**Comment by arnoldnipper** [comment]
@jaapbr what `country` field should be added to "Public Peering Exchange Points"? The country where the IX is? For evaluation, you most likely would use the API. 

For displaying on the GUI it would perhaps overload the display

**Comment by arnoldnipper** [comment]
@jaapbr still waiting for an answer. If it's the network's country where should we take this information from? Or would each network have to declare this themself? And what if the country operates in several countries?

**Comment by arnoldnipper** [comment]
No feedback from @jaapbr for a couple of weeks. Hence closing
