### ISSUE TITLE
IX-F import doesn't perform changes

### ISSUE THREAD

**Issue by rasssta** [peeringdb/peeringdb#573]
Not sure if this is already reported as there are plenty of IX-F related issues.

Anyhow, I've noted that a certain change for https://www.peeringdb.com/ix/2677 is not taking place as it should. I added "Allow IXP Update" for that specific IXP a couple of days ago but the changes that are stated when I click "Preview" haven't been executed yet.

![image](https://user-images.githubusercontent.com/4455235/65256632-20e6f280-db00-11e9-8de9-caa0a451b90f.png)

**Comment by arnoldnipper** [comment]
The IX-F JSON import is disabled since 2019-08-30, i.e. the last import ran at 2019-08-30 00:00:00 UTC. See https://docs.peeringdb.com/ix-f-json-import-rules/
