### ISSUE TITLE
No dropdown values for certain fields when using different locale than English

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/peeringdb#576]
e.g. for Portuguese and German, there are no dropdown values available for "Geographic Scope". For Portuguese even more fields are affected

**Comment by koalafil** [comment]
Same with French.

**Comment by vegu** [comment]
Looking at this now - same issue causes #572, working on a patch

Not entirely sure of cause yet

**Comment by vegu** [comment]
Patch pushed to branch pr_fix_576_572, will need a merge and then a rollout.

Cause of the issue was side effect from an update to current django-peeringdb(1.0.0) in 2.16.0

cc: @arnoldnipper @koalafil

**Comment by arnoldnipper** [comment]
Please reopen. An Italian user just reported that there is no dropdown for field "Ratio Requirement" in Italian.

![20190923 PeeringDB 02](https://user-images.githubusercontent.com/16888757/65437077-71718f00-de23-11e9-8ec6-f09bd2c39a03.jpg)

**Comment by vegu** [comment]
Can confirm that there still appears to be an issue here, looking into it.
