### ISSUE TITLE
geosync command log message encoding fix

### ISSUE THREAD

**Issue by vegu** [peeringdb/peeringdb#578]
Ran into an issue where it kept crashing with an encoding error caused by the name of the facility it was processing

**Comment by mcmanuss8** [comment]
+1 Let's fix

**Comment by arnoldnipper** [comment]
+1

**Comment by eloos** [comment]
this is now fixed right?

**Comment by ccaputo** [comment]
Not to my knowledge.

**Comment by koalafil** [comment]
To my knowledge it is fixed: On 9 October, 20C reported that it was fixed (as a hotfix) during 5-6 Oct weekend and that they would close the issue.  @grizz @vegu @Shawna can you pls comment?

**Comment by vegu** [comment]
fix was merged and rolled out as a hotfix

**Comment by eloos** [comment]
thanks for confirming that it was fixed
