### ISSUE TITLE
Have an RSS-feed (like) functionality to be notified about new objects created in PeeringDB

### ISSUE THREAD

**Issue by koalafil** [peeringdb/peeringdb#581]
This is a request from Walt Wollny and based on his feedback. 

The idea is to have an RSS feed or some other similar functionality which periodically will send updates to subscribers showing new objects created in the PeeringDB since the last update. It could be weekly I presume.
[Of course POCs should be shown in the feed in accordance to their visibility settings...]

Thoughts?

**Comment by netravnen** [comment]
_Input:_ The current JSON API can be used as data-source for this functionality.
* Fetch the `N` most recent entries based upon creation time (descending order, newest to oldest), and
* Format data output in RSS compliant output.

**Comment by koalafil** [comment]
@ccaputo @job do you have input as well, from OPS committee perspective ?

**Comment by grizz** [comment]
Honestly, I don't see much of a use case for this, like @netravnen said, it's accomplishable via the API.

I also don't see a reason not to do it... :) @peeringdb/pc votes?

**Comment by shane-kerr** [comment]
I guess that I'm in favor of updating the API to allow an RSS (or similar) service to be provided is reasonable. We can actually decide whether to build an RSS service as a separate issue, I think. 

While running an RSS feed is not a big or complicated service, it does mean updating documentation, updating our monitoring, and making sure that whoever handles operations is willing to handle the additional work.

**Comment by ccaputo** [comment]
Every new feature increases paid & volunteer work load in a multitude of ways.  Thus I must ask, is there demand for this beyond that expressed by one person?

**Comment by grizz** [comment]
> I guess that I'm in favor of updating the API to allow an RSS (or similar) service to be provided is reasonable. We can actually decide whether to build an RSS service as a separate issue, I think.

This is already easily accomplishable, every list call takes `since` to limit to the objects updated since that timestamp.

**Comment by mcmanuss8** [comment]
Feels like we should couple with #915

+1 to this iff we do #915

**Comment by ynbrthr** [comment]
+1

**Comment by leovegoda** [comment]
The Product Committee has decided to close this issue. There was no agreement on the concept and the issue has not been discussed for six months or longer.
