### ISSUE TITLE
invalid URL can be set in website fields

### ISSUE THREAD

**Issue by ccaputo** [peeringdb/peeringdb#583]
Both net and org pages allow an invalid URL to be set as a website address. For example, this can be configured: "http://https://TEST@www.example.xyz/"

Then when "peeringdb sync" is run on a client running django >=2.2.2, this will happen:

django.core.exceptions.ValidationError: {'website': ['Enter a valid URL.']}

This will be potentially fixed when https://github.com/peeringdb/peeringdb/issues/492 is completed, but a separate issue to check for or potentially handle separately.

**Comment by grizz** [comment]
@ccaputo Maybe we should check for reachability? Do you have a better idea?

**Comment by ccaputo** [comment]
> @ccaputo Maybe we should check for reachability? Do you have a better idea?

I just checked with the current production site and "http://https://TEST@www.example.xyz/" can no longer be set, so I think this issue could be closed.

As for testing for reachability, I don't know.  That's really a different issue and may not be a good idea since someone may want to configure a URL in advance of it existing, or the resource may be down at the moment of configuration.

**Comment by grizz** [comment]
Nice, fully agree and I'm not sure it would be a priority now. Thanks!
