### ISSUE TITLE
Add export tool to https://peeringdb.com/cp/peeringdb_server/$type

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/peeringdb#586]
For any of the items in https://peeringdb.com/cp/peeringdb_server/$type add a button to export the data to a CSV file. E.g. to be able to have CSV list of https://peeringdb.com/cp/peeringdb_server/user/?is_staff__exact=1

**Comment by arnoldnipper** [comment]
@peeringdb/ac please make up your mind

**Comment by arnoldnipper** [comment]
@peeringdb/pc as this is AC only, please check and ideally support by adding +1

**Comment by netravnen** [comment]
> For any of the items in https://peeringdb.com/cp/peeringdb_server/$type add a button to export the data to a CSV file. E.g. to be able to have CSV list of https://peeringdb.com/cp/peeringdb_server/user/?is_staff__exact=1

I am in on this 😍 👍

_**Hint:**_ It would be lovely for the export function to be available to consume from command-line tools. E.g.
* `curl -s -n -G -L -X GET -u <User>:<Pass> https://peeringdb.com/cp/peeringdb_server/user/?is_staff__exact=1&format=[json|csv]` **OR**
* `curl -s -n -G -L -X GET -u <User>:<Pass> -H "Accept: application/json" https://peeringdb.com/cp/peeringdb_server/user/?is_staff__exact=1`
* `curl -s -n -G -L -X GET -u <User>:<Pass> -H "Accept: text/csv" https://peeringdb.com/cp/peeringdb_server/user/?is_staff__exact=1`

**Comment by mcmanuss8** [comment]
+1 seems legit
As a general rule it'd be nice to export any widget on peeringdb but let's do it here and then think about how to make it more general later

**Comment by grizz** [comment]
+1

**Comment by shane-kerr** [comment]
I really like @netravnen's suggestion. As I understand it, the buttons proposed in this ticket could actually just be links to the generic export URL. Indeed we could easily have a radio-button next to the button which specifies JSON (for devops folks) or CSV (for marketing people). :wink:

**Comment by vegu** [comment]
@peeringdb/pc please summarize what's to be estimated, as there is multiple suggestions in the comments that add to the original ticket specs

**Comment by arnoldnipper** [comment]
To summarise:

 * For any of the items in https://peeringdb.com/cp/peeringdb_server/$type add a button to export the data to a CSV file. E.g. to be able to have CSV file of https://peeringdb.com/cp/peeringdb_server/user/?is_staff__exact=1

 * Option 1: same as above but in JSON format

 * Option 2: make this information available via a retrievable URL as well. E.g. `curl -snG https://peeringdb.com/cp/peeringdb_server/user/?is_staff__exact=1&format=json`
