### ISSUE TITLE
Add pagination to https://peeringdb.com/cp/peeringdb_server

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/peeringdb#587]
Currently, all output is set to 50 entries. It would be nice to make this configurable or to turn it off completely

**Comment by arnoldnipper** [comment]
@peeringdb/ac please make up your mind

**Comment by arnoldnipper** [comment]
@peeringdb/pc as this is AC only, please check and ideally support by adding +1

**Comment by netravnen** [comment]
> It would be nice to make this configurable or to turn it off completely

👍 Agreed.

Make it possible to pre-select the size of the list returned from a pre-defined list of sizes. Default to e.g. 50 items of no size is selected. _(E.g. 10, 25, 50, 100, 250, 500, 1000)_

**Comment by mcmanuss8** [comment]
+1 
DataTable has a good implementation of this IMO https://datatables.net/examples/basic_init/alt_pagination.html

**Comment by arnoldnipper** [comment]
one more +1 please @peeringdb/pc ... same for #586

**Comment by grizz** [comment]
+1 -- this still needs an actual spec of what to do. Is it just adding `Show X Entries` to the UI?

**Comment by arnoldnipper** [comment]
Summarize:

 * implement pagination according to https://datatables.net/examples/basic_init/alt_pagination.html

 * values: 10, 25, 50, 100, 250, all

Do you need more, @grizz?

**Comment by grizz** [comment]
@arnoldnipper nope, that's perfect, thanks

**Comment by grizz** [comment]
@arnoldnipper actually, `all` will still scroll inside the separate window as it does now, right? The above link doesn't have `all` and I don't think it should fill the whole page.

Also, should we give users a knob to turn for their own default?

**Comment by arnoldnipper** [comment]
Then take an arbitrarily large number for all (eg. 100,000). A per-user default is not needed. Set default to 25, please.

**Comment by grizz** [comment]
> Then take an arbitrarily large number for all (eg. 100,000).

`all` can be implemented just fine, I was talking about the behavior when, for example, 100,000 are displayed.

> A per-user default is not needed. Set default to 25, please.

I would want one, pagination drives me crazy, but I'll digress if others don't.

**Comment by vegu** [comment]
@peeringdb/ac @peeringdb/pc  there already is pagination in the current /cp [0], so this ticket is just about providing a drop down for result limits? Am i understanding this correctly?

0: https://www.peeringdb.com/cp/peeringdb_server/network/

**Comment by arnoldnipper** [comment]
That's correct, @vegu. Currently, there is a fixed page size. This should be made configurable.
