### ISSUE TITLE
RFD & MRAI Policy

### ISSUE THREAD

**Issue by randyqx** [peeringdb/peeringdb#588]
It would be convenient to know an AS's Route FLap Damping and Min Route Advert Interval.

**Comment by arnoldnipper** [comment]
Thanks for the suggestion, @randyqx To get a better understanding of this feature request:

 * does every ASN set  Route Flap Damping (RFD) and Min Route Advert (MRA) Interval in their BGP?

 * if not, how many ASN do that?

 * How would knowledge of these values help to make the internet better?

**Comment by grizz** [comment]
Not against adding these, but the can also go in the notes section if needed.

Closing for lack of response, @randyqx please reopen at any point and we'll discuss.
