### ISSUE TITLE
Search/filter for "Networks" present/not present in a given "Exchange Point" or "Facility"

### ISSUE THREAD

**Issue by jaapbr** [peeringdb/peeringdb#59]
Change Proposal:
To create a search/filter for "Networks" present in a given "Exchange Point or Facility" and NOT present in another given "Exchange Point or Facility".

Goal:
Intends to find "who" is:
- in a **target site** (your company is evaluating), and
- _simultaneously_, not in the sites your company already have presence.

Advantage:
Increases facility in the use of the database for strategic peering evaluation.

**Comment by vegu** [comment]
Implemented in 62a1a16f
