### ISSUE TITLE
Drop "Local" from "Local Exchanges"

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/peeringdb#591]
On the left-hand side, you always find information about the record itself, while on the right-hand site there is information about records associated with the given record. Hence "Local Exchanges" should be on the right-hand side the same way as "Networks" are. And perhaps it's a good idea to rename to "Exchanges" at the same time to make it consistent.

![20191027 PeeringDB 01](https://user-images.githubusercontent.com/16888757/67632541-03e2d380-f8a5-11e9-83ef-e64fed3ee5e5.png)

**Comment by arnoldnipper** [comment]
@peeringdb/pc, thoughts?

**Comment by grizz** [comment]
I like it how it is, if you look at something like https://www.peeringdb.com/fac/1 -- there's a lot more networks than there are IXes so I think it flows better.

**Comment by arnoldnipper** [comment]
I fully agree that from a UX pov it makes more sense how it is, but still would like to have the "Local " dropped **or** added to "Networks" as well 💃

**Comment by grizz** [comment]
@arnoldnipper ugh, I didn't notice the Local part, I fully agree. If you make the ticket to drop Local from Exchanges, I'll do the 5 second fix after one more +1. :) Although I guess changing that in the locale might take a bit more time.

**Comment by arnoldnipper** [comment]
Renamed the subject, @grizz ... anyone give a +1, please @peeringdb/pc

**Comment by shane-kerr** [comment]
+1
