### ISSUE TITLE
Reconsider 'staff' privilege level

### ISSUE THREAD

**Issue by job** [peeringdb/peeringdb#592]
It appears that the 'staff' privilege level is not used for anything, but that sometimes users obtain this level either through missclicks or a software defect.

If we aren't using this functionality, maybe we should remove the code paths related to 'staff' to simplify the code base.

**Comment by grizz** [comment]
I'm not sure removing `staff` level is the correct way to go, I believe we are using it?

Why not just audit the users with that access level, just like `superuser`?

**Comment by arnoldnipper** [comment]
`staff` definitely makes sense. Missing documentation led to misconfiguration which can be fixed easily. @funkestefan and I compiled a list of users who should have `staff` status.

**Comment by job** [comment]
ok! thanks
