### ISSUE TITLE
Sponsorship: multiple org records under a single sponsorship

### ISSUE THREAD

**Issue by ccaputo** [peeringdb/peeringdb#593]
The Board has approved of a "Major" task under the 20c support contract to implement the following:

- The sponsorship control panel will be changed to allow more than one /org/ record to be tied to a single sponsorship.

- Sponsor badges will appear on the records of all associated organizations for a sponsorship.

As I understand the processes, Filiz will coordinate with the Product Committee as to the scheduling of when this "Major" task will occur, in relation to any other "Major" tasks.

**Comment by mcmanuss8** [comment]
+1 let's do this

**Comment by arnoldnipper** [comment]
+1

**Comment by arnoldnipper** [comment]
> * The sponsorship control panel will be changed to allow more than one /org/ record to be tied to a single sponsorship.

@ccaputo  where may one find more background info and motivation for this?

**Comment by ccaputo** [comment]
Hi @arnoldnipper.  One sponsor has been acquired by another.  To avoid the parent organization and subsidiary having to combine their administrative domains in PeeringDB, I proposed to the board that we allow PeeringDB /org/ organizations with common (ie. 50%+) ownership to be under a single sponsorship.  Informally, the board approved, with one abstention.  The immediate effect will be an increase sponsorship revenue and I believe this may be useful for other organizations that may find it convenient to not combine their /org/ records.  Please let me know of any concerns.

**Comment by arnoldnipper** [comment]
Two comments
 * When first reading this issue I thought it was about **pooling** of sponsorships, i.e. multiple, independent `org` share a sponsorship. Your explanation clarifies

 * We have a similar issue when it comes to voting. Maybe introducing a (hidden) field `belongs_to` could solve both

**Comment by ccaputo** [comment]
> Two comments
> 
> * When first reading this issue I thought it was about **pooling** of sponsorships, i.e. multiple, independent `org` share a sponsorship. Your explanation clarifies

Sorry for the confusion and I am glad I can clarify this.  I confirm that is not what this is about.

> * We have a similar issue when it comes to voting. Maybe introducing a (hidden) field `belongs_to` could solve both

That is an interesting insight but not what is the effort here.  In the sponsorship control panel I need to ability to add and remove /org/ records from a sponsorship without organizations worrying about the impact to their future voting ability.  Unless obvious in the public record, the affiliation aspect of voting registration involves an actual affirmation by the voters to relationships that may not actually be public.

**Comment by ccaputo** [comment]
Re-opening due to testing on beta...

In a sponsorship, if the second organization doesn't have a logo configured, while first does, the status "Logo Missing" is indicated.  That should not be the case.

Then if the second organization has a logo uploaded, to prevent the "Logo Missing" message, TWO logos will now show up on the sponsors page.  That should not be possible with a single sponsorship.

A work around is to ignore the "Logo Missing" message and only configure one of the organizations with a logo, but I believe the fix is to make it so the single logo and optional URL are tied to the sponsorship, not the organization.  Ie., one sponsorship has one logo on the sponsors page, but the possibility of being associated with more than one organization.

Please advise of questions and thanks!

**Comment by ccaputo** [comment]
Per discussion with @vegu , at this point only the "Logo Missing" issue needs to be fixed, and no change to the object schema is needed.  This leaves open the possibility, should it be available as a benefit at some point, for multiple logos to be presented under a single sponsorship.
