### ISSUE TITLE
Consider "Traffic Levels"

### ISSUE THREAD

**Issue by stillwaxin** [peeringdb/peeringdb#594]
Consider whether the Traffic Levels value for a Network (api/net:"info_traffic") is useful or not. I believe that networks that really care about traffic levels would use a flow tool to really figure out what the traffic levels they actually have for a particular network. I would propose to remove this field entirely.

**Comment by shane-kerr** [comment]
Agree that we should update documentation to be more clear about the lack of actual meaning.

Possibly we should start a list of things that we want to deprecate, and when it gets long enough decide that it is time for a new major version. Or such a list may already exist?

**Comment by arnoldnipper** [comment]
-1 ... i.e. leave this field in

**Comment by grizz** [comment]
-1 -- Leave it in, but let's add help text saying this is an arbitrary number provided by the networks.
