### ISSUE TITLE
bug caused by the org affiliationship request without an asn

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/peeringdb#598]
@vegu writes:  bug caused by the org affiliationship request without an asn - which is a valid thing to have, but its hard failing because it's trying to do asn validation on an empty asn during the save. Looks like this got introduced at some point when we added bogon asn validation.

The cause for this should get a bug ticket in the main repo.

This particular instance can be fixed by typing any number into the asn field and deleting the affiliation request (since its already approved anyways).

**Comment by arnoldnipper** [comment]
@peeringdb/pc , please +1. Developper @vegu categorized this as a bug.

**Comment by shane-kerr** [comment]
+1

Seems like a relatively straightforward bug.

**Comment by grizz** [comment]
+1

**Comment by mcmanuss8** [comment]
+1

**Comment by arnoldnipper** [comment]
**Release note**
This is a bug fix and is only relevant for the @peeringdb/ac
