### ISSUE TITLE
Fix tutorial data reset

### ISSUE THREAD

**Issue by vegu** [peeringdb/peeringdb#599]
Issue was introduced in 2.16.0 with the upgrade to `django-peeringdb 1.0`

Sync part of the reset relied on the old `django-peeringdb` sync functionality. Should now instead use `peeringdb-py` 1.0.0 to handle the sync.

Since we also have test.peeringdb.com now should add a test with full reset and sync from test.peeringdb.com so this doesn't get missed in the future.

**Comment by arnoldnipper** [comment]
@peeringdb/pc please vote ... +1 from my side

**Comment by grizz** [comment]
+1

**Comment by shane-kerr** [comment]
+1

**Comment by arnoldnipper** [comment]
@koalafil , please proceed as @shane-kerr @grizz and @arnoldnipper support this issue

**Comment by arnoldnipper** [comment]
It's still not working :( 
![20200127 Reset Environment  Preview    PeeringDB](https://user-images.githubusercontent.com/16888757/73170304-54650980-40fe-11ea-9c6f-97c15b7194b8.png)

**Comment by arnoldnipper** [comment]
@peeringdb/oc or @vegu is there something else I have to take care of? I simply selected "Reset Environment", then pressed "Preview Command" and got the error message "cannot import name sync".

**Comment by grizz** [comment]
@arnoldnipper I believe this is taken care of with the tutorial 2.18 deploy?

**Comment by grizz** [comment]
Closing since no news is good news. :) @arnoldnipper please reopen if it didn't work as intended.
