### ISSUE TITLE
API Endpoint for ASN

### ISSUE THREAD

**Issue by schiederme** [peeringdb/peeringdb#608]
Make ASN searchable via API e.g.
GET /api/asn/{ASN}

Should return a list of ORG, IX, NET and FAC endpoints with the right data e.g.
https://www.peeringdb.com/api/net/{ID}

This could be useful for Peering Management in custom interfaces.

**Comment by mcmanuss8** [comment]
To clarify, you want https://www.peeringdb.com/api/asn/4436 to return the exact same data as https://www.peeringdb.com/api/net/1 (since network 1 in peeringdb is GTT/4436)? 

If so, I think that's a reasonable ask, especially since https://www.peeringdb.com/asn/4436 does the same thing.

**Comment by arnoldnipper** [comment]
We should keep the API clean imho. Endpoints should relate to objects. ASN is not an object. And  https://www.peeringdb.com/asn/4436 only is there for backwards compability which we don't have at the API. A call  https://www.peeringdb.com/api/net?asn=4436 does exactly what you want.

**Comment by shane-kerr** [comment]
I tend to agree with @arnoldnipper that if we have https://www.peeringdb.com/api/net?asn=4436 we don't need https://www.peeringdb.com/asn/4436 in the API.

**Comment by schiederme** [comment]
> I tend to agree with @arnoldnipper that if we have https://www.peeringdb.com/api/net?asn=4436 we don't need https://www.peeringdb.com/asn/4436 in the API.

Yeah. I didn't´t know that this exist. This was the point of my question. Thank you for that!

**Comment by mcmanuss8** [comment]
I think it'd be worthwhile to improve the documentation, though. Looking at https://www.peeringdb.com/apidocs/#!/net/net_read - and https://www.peeringdb.com/apidocs/#!/net/net_list  I don't see any mention of the ?asn=X argument.

**Comment by arnoldnipper** [comment]
@mcmanuss8, it is mentioned in https://docs.peeringdb.com/api_specs/#operations last bullet point "[field_name] int|string queries for fields with matching value"

But you are absolutely right that documentation needs a lot of improvement.
