### ISSUE TITLE
staleness visualization

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/peeringdb#61]
http://ubersmith.peeringdb.com/admin/supportmgr/ticket_view.php?ticket=2094

The promotion of 'recently updated' networks has been on
the landing page for a long time. There is an opportunity to
provide simple visual cues for staleness of individual entries.
Since installs take a while, "staleness" might only need to
be measured on a long scale, perhaps triggering only on the
last update in 3mo/6mo/12mo/24mo/never.

I'd suggest simply having a few alternate css templates to
indicate age/staleness, taking the blue in the network
record on a gradation to red? or changing the background
grey in the network record in gradients toward yellow?

I suppose something automated and highly dynamic would
be possible, but since I'm not volunteering to code it I didn't
suggest it.

Actually, after thinking about it, gradiate the background to
black, matching text colour. Then when someone is totally
stale (or the company has gonebelly-up), the problem is self-
correcting as they will see (or their peers/potential peers will
see and nag) an annoyance in the display.
## 

Joe Provo
Packet Slinger
ITA Software by Google
317-JZP-0-JZP

**Comment by mcmanuss8** [comment]
It would be interesting to crowd source this if possible - use session data from route servers and peers at each IX to see if *anyone* is peering with this entry. Possible states:

Buildout: Added/edited within ~1-2months and no up sessions 
New: Added/edited within ~3-6 months and has up sessions
Live: Has up Sessions but not New
Stale: Not added/edited within ~3-6 months and has no up sessions in the last month
Unknown: No session data available at this IX

The rub of course is getting the data from more than 1-2 peers. But if we could get it, that'd be great.

**Comment by eloos** [comment]
I struggle with the defintion of 'staleness' especially given that we have implemented IF-X sync allowing exchanges to effectively remove entries of members whom are no longer present. The UI also does not allow for an IX entry to be added without IP address, avoiding people setting up 'to come' status. Staleness should not be confused with stability, it is not because a record exists for x months without changes, that the nework is not actively peering on a particular IX.
Furthermore, principally, we say that the data-owner is the network setting up their presence in PeeringDB, "enriching" how their data looks towards others without consent seems like a violation of that principle. To flag known bad data, we should further pursue a decision on #170

**Comment by job** [comment]
I'm not sure we should implement visual clues on a color scale. In PeeringDB staleness doesn't mean 'incorrectness', or actually doesn't mean a whole lot. Some networks are content with what they have and have no need to update anything. Some networks update their records every day - it doesn't really matter.

**Comment by arnoldnipper** [comment]
+1 on what @eloos and @job say

**Comment by grizz** [comment]
I really like the idea of this, but lean towards something like @mcmanuss8 said

**Comment by mcmanuss8** [comment]
I think staleness is only useful if we do something like my proposal from Jan 10th alongside it. Otherwise it's useless per @job 's comment. It's not that we want to look at age of a particular record, we want to know if it's still valid or not.

**Comment by aarohaa** [comment]
In favor.

**Comment by kay23** [comment]
I think staleness is not very helpful. However adding a flag if you are planning to turn up a facility or IXP could be really helpful. Buildout and Live in that case would help a lot to differentiate between the states already.

**Comment by job** [comment]
I can’t really see a case for “coming soon”. Either you are present, or you
aren’t. There is nothing automatable about the “soon” state. Also, what
does “soon” even mean?

https://tools.ietf.org/html/draft-farrel-soon-05

**Comment by arnoldnipper** [comment]
Imho we discussed this issue in depth and came to the 'wontfix' conclusion. And I do not see any new pov to reopen the issue

**Comment by thatchrisp** [comment]
Also +1 to @eloos and @job.
