### ISSUE TITLE
Update "Last Updated" when public or private peering facilities are modified

### ISSUE THREAD

**Issue by thatchrisp** [peeringdb/peeringdb#613]
Currently, when you update your public or private facilities, your timestamp is not updated.  It may erroneously give potential peers the idea that your record has been abandoned.  Any/all updates to the net entry should update the timestamp imho.

**Comment by arnoldnipper** [comment]
@thatchrisp, seems to be a duplicate of #129. Do you agree?

**Comment by mcmanuss8** [comment]
Feels more like a dupe of #541 to me

**Comment by mcmanuss8** [comment]
Merging to #541
