### ISSUE TITLE
Add a count next to public and private facilities

### ISSUE THREAD

**Issue by thatchrisp** [peeringdb/peeringdb#614]
It would be nice to have a count() next to the public and private facilities.  Saves having to count dozens of entries by hand.

**Comment by arnoldnipper** [comment]
There are not *public* facilities. There are only *Public Peering Exchange Points". For those, you have the numbers of participants if you click on any of the facilities where the IX services are available.

And you don't need to count by hand. Just use the API and see for `net_count`. Both for /api/fac and /api/ix. E.g. https://peeringdb.com/api/ix/1149?fields=net_count&pretty

However, having this information directly at /fac and /ix would be nice as well. Is this what you have in mind? If so, I would propose to rephrase the subject.

**Comment by mcmanuss8** [comment]
@thatchrisp I think @arnoldnipper has nailed it for the API way to get this. Are you asking for a frontend version? If so, would something like the mockup in https://github.com/peeringdb/peeringdb/issues/18#issuecomment-373224067 work (a summary at the top of each /fac or /ix or /net record with counts or sums of interesting values)?

**Comment by arnoldnipper** [comment]
@thatchrisp would #18 implement what you are looking for?

**Comment by arnoldnipper** [comment]
Imho related to #834, #835 and #836. Do you agree, @thatchrisp?

**Comment by arnoldnipper** [comment]
Covered by #834, #835 and #836
