### ISSUE TITLE
Insert links into ID fields in DESKPRO AUTOASN tickets

### ISSUE THREAD

**Issue by netravnen** [peeringdb/peeringdb#615]
_Re-open correct place https://github.com/peeringdb/admincom/issues/245)_

## 1. AUTOASN tickets markup

Can I request we add Links to peeringdb.com to ID fields in e.g. AUTOASN ticket created in Deskpro?

![](https://user-images.githubusercontent.com/1938389/71623148-d3882000-2bda-11ea-8d57-28ada856c1a0.png)

## 2. Facility SUGGEST tickets

We could add a direct link to the front-end editor for the pending object?

Reasoning: I often find it easier and quicker to use the front-end editor to change fields for an object. Rather than use the backend editor under /cp/

![image](https://user-images.githubusercontent.com/1938389/71714693-2f3aef00-2e0f-11ea-8ed7-b7ee32b5b86c.png)

## 3. [`${_IS_PROD_OR_DEV_INSTANCE}`] User `${USERNAME}` wishes to request ownership of `${ORGANIZATION_NAME}`

User to Organization ownership tickets flagged for manual review.

![image](https://user-images.githubusercontent.com/1938389/71715176-cd7b8480-2e10-11ea-90ce-805d447a65bd.png)

---

@vegu @grizz ?
Commentary input requested

**Comment by netravnen** [comment]
> Can I request we add Links to peeringdb.com to ID fields in e.g. AUTOASN ticket created in Deskpro?

This suggestion has potential to be implemented in other tickets as well. Containing aut-nums and PeeringDB ID fields.

**Comment by arnoldnipper** [comment]
> This suggestion has the potential to be implemented in other tickets as well. Containing aut-nums and PeeringDB ID fields.

@netravnen, would you mind to provide markups for those cases as well? TIA

**Comment by arnoldnipper** [comment]
@peeringdb/pc, @peeringdb/ac uses both the AC GUI as well as the regular GUI. Hence linking directly to the regular GUI object would be a big benefit

**Comment by netravnen** [comment]
> would you mind to provide markups for those cases as well?

1 added. https://github.com/peeringdb/peeringdb/issues/615#issue-544709051

**Comment by mcmanuss8** [comment]
To clarify, the ask here is anywhere we generate a link in a deskpro ticket to link to both the peeringdb.com public UI and the AC private UI? If so that makes sense to some degree...although I would expect the AC UI to be a superset of the public UI. 

Is there a reason we wouldn't want to focus on making the AC UI feature parity with the public UI instead of adding 2 links? If there's good reasons from AC, I support adding both links.

**Comment by arnoldnipper** [comment]
@mcmanuss8, the AC GUI is **completely** different from the public GUI. In theory, Admins could completely do their work via the AC API, but in practice, both are used as the public GUI is more comfortable. At least for me.

**Comment by mcmanuss8** [comment]
> @mcmanuss8, the AC GUI is **completely** different from the public GUI. In theory, Admins could completely do their work via the AC API, but in practice, both are used as the public GUI is more comfortable. At least for me.

I see - would it make any sense to cut separate issues to make the AC UI more comfortable?

**Comment by arnoldnipper** [comment]
> I see - would it make any sense to cut separate issues to make the AC UI more comfortable?

Let's implement first what @netravnen proposed. The AC GUI is well thought-thru as well. But for some tasks (e.g. approving an affiliation request), the public GUI is way faster and more comfortable.

**Comment by mcmanuss8** [comment]
> > I see - would it make any sense to cut separate issues to make the AC UI more comfortable?
> 
> Let's implement first what @netravnen proposed. The AC GUI is well thought-thru as well. But for some tasks (e.g. approving an affiliation request), the public GUI is way faster and more comfortable.

Sounds like a plan. +1

**Comment by grizz** [comment]
> Reasoning: I often find it easier and quicker to use the front-end editor to change fields for an object. Rather than use the backend editor under /cp/

Completely agree, on the very rare times that I need to do something.

+1

**Comment by grizz** [comment]
btw @netravnen This was a wonderfully clear and well laid out issue, thank you :)

**Comment by arnoldnipper** [comment]
**Release note**
This only affects tickets generated for @peeringdb/ac. A link to the object in the UI is added.
