### ISSUE TITLE
Warning for missing information

### ISSUE THREAD

**Issue by koalafil** [peeringdb/peeringdb#616]
This is a request on behalf of Vladimir Drushchits (raised during Moscow Peering Forum 2019): "We are an ISP so we consider ourselves a Network and not an IXP in PeeringDB. Our Org object constantly pushes warnings to fill in the routeserver information. As an ISP, network, we do not run a routeserver. Could the warnings stop for networks pls? "

**Comment by arnoldnipper** [comment]
Currently a warning 'Some of the data on this page is incomplete, please update the fields marked with "!! to improve data quality.' is shown if a field of record `net` is not set. 

Proposal: do not show this warning for fields

 * Route Server URL
 * Looking Glass URL

**Comment by mcmanuss8** [comment]
+1

**Comment by arnoldnipper** [comment]
Small addition after last call.  Currently a warning 'Some of the data on this page is incomplete, please update the fields marked with "!! to improve data quality.' is shown if a field of record net is not set.

Proposal: do not show this warning for fields

 * Route Server URL
 * Looking Glass URL
 * if IPv4 Prefixes or IPv6 Prefixes is set

**Comment by arnoldnipper** [comment]
@Shawna, @vegu and @grizz: any question on how to implement this?

**Comment by arnoldnipper** [comment]
Small addition after last call. Currently a warning 'Some of the data on this page is incomplete, please update the fields marked with "!! to improve data quality.' is shown if a field of record net is not set.

Proposal: do not show this warning for fields

 * Also Known As
 * Route Server URL
 * Looking Glass URL
 * if IPv4 Prefixes or IPv6 Prefixes is set

**Comment by vegu** [comment]
@arnoldnipper 

>if IPv4 Prefixes or IPv6 Prefixes is set

I understand this as: don't show a warning for the fields `IPv4 Prefixes` and `IPv6 Prefixes` if either of them is set, but show warning for both if neither of them is set - is that correct?

**Comment by arnoldnipper** [comment]
@vegu, that is correct.
