### ISSUE TITLE
Support alternative direction of writing, e.g. Arabic

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/peeringdb#618]
Now that Arabic is translated for 100% it should be put into production. Also **right alignment** of text is needed for Arabic as it is written from right to left.

@peeringdb/oc, please install Arabic. @peeringdb/pc, please support this issue

**Comment by mcmanuss8** [comment]
Forgive my ignorance - wouldn't the Arabic strings be entered right to left in the translation tool? 

+1 though, whatever we can do to get better language support always has my vote

**Comment by arnoldnipper** [comment]
> Forgive my ignorance - wouldn't the Arabic strings be entered right to left in the translation tool?

This is **not** for translation.peeringdb.com, but for https://peeringdb.com, and https://{beta,tutorial}.peeringdb.com. This currently still looks like the attached.

<img width="1077" alt="HOME Page" src="https://user-images.githubusercontent.com/16888757/71851737-79ee8c80-30d7-11ea-8147-5802847f5db0.png">

**Comment by shane-kerr** [comment]
+1

**Comment by arnoldnipper** [comment]
@Shawna, @vegu and @grizz, any questions on how to implement?

**Comment by vegu** [comment]
@arnoldnipper @peeringdb/pc 

i understand that this needs right adjustment and right to left direction of text everywhere, but it sounds like this would need actual layout adjustment as well.

few quick examples i can think of are

- column order in tables (advanced search result for example)
- entity view layout (https://www.peeringdb.com/net/20)
    - flip label, value columns
    - flip the entire layout so network fields are on the right side and public peering exchange points are on the left?

thoughts?

**Comment by arnoldnipper** [comment]
> i understand that this needs right adjustment and right to left direction of text everywhere, but it sounds like this would need actual layout adjustment as well.

I have asked Sara Alamin Mohamed Hassan from PCH to chime in. Sara did the translation.

**Comment by arnoldnipper** [comment]
Sara says: Yes, for Arabic it will be better to flip the entire layout, to make the
Arabic words in the correct order.

I have attached a sample for how the page should be. but also notice
that Arabic titles/text
[arabic interface for peeringDB.pdf](https://github.com/peeringdb/peeringdb/files/4127164/arabic.interface.for.peeringDB.pdf)
 need also to be aligned from rtl.

**Comment by vegu** [comment]
@arnoldnipper can you show the following screenshot to Sara and let me know if she thinks this looks good generally speaking (small glitches aside) - thanks

![pdbrtl](https://user-images.githubusercontent.com/143124/73471252-b8ebc700-4391-11ea-825d-ec445a92c337.PNG)

**Comment by arnoldnipper** [comment]
@vegu, Sara says: The screenshot is perfect. The Arabic words and alignment are correct.

**Comment by job** [comment]
Looks great indeed, +1

**Comment by koalafil** [comment]
Can we have the Release Notes pls?

**Comment by arnoldnipper** [comment]
**Release Note**

For right-to-left written languages, the entire layout of the PeeringDB website has to be flipped around.
