### ISSUE TITLE
At https://status.peeringdb.com/ No method to return to main page .

### ISSUE THREAD

**Issue by jwl02-arin** [peeringdb/peeringdb#619]
Hello Support , Just a nit on the webpage at
https://status.peeringdb.com/

There seems to be no method to return to main page from this page .

Asked by Mr. Arnold Nipper to insert Issue to tracker .
Hth ,  JimL
ps: still wondering why github requires I create an account just to enter a issue into the tracker ?

**Comment by arnoldnipper** [comment]
@peeringdb/oc, are you able to put a return link to https://peeringdb.com on https://status.peeringdbcom?

**Comment by ccaputo** [comment]
UptimeRobot (the status page service) does not appear to support this ability, but I have now emailed them asking that they do so.

**Comment by ccaputo** [comment]
Unfortunately, the response from Uptime Robot is as follows:

---
Totally understand the need and, as of now, we decided not to add this feature (or add any other links) to the status pages to prevent the risk of:
 *  all the status pages run under the same IP and also the stats.uptimerobot.com/[customKey] addresses
 *  and, any malicious links can cause the IP and the main URL to be blocked or marked as unsafe by search engines.
For this reason, we currently plan to keep the status pages link-free and may definitely come up with a solution once we see that there are no such risks.
 
P.S> Sorry for not being able to create a custom solution as the codebase is totally generic for all status pages.
---

**Comment by mcmanuss8** [comment]
Bummer. At a minimum, we could make the link to status (and other things not on peeringdb.com) open in a new tab, which might help. Right now the link to status uses the same window. #360 covers that idea

**Comment by job** [comment]
This PR can be merged if we have enough +1

https://github.com/peeringdb/peeringdb/pull/622

**Comment by grizz** [comment]
+1 to #622 -- thanks @job!

**Comment by grizz** [comment]
@peeringdb/pc need one more +1 and I'll slip this into the current beta and get it out there since it's a small change

**Comment by shane-kerr** [comment]
I kind of hate things that open in a new tab/window. I realize that it's a hack to work around the problem with our status page, but to me the cure is worse than the disease.

**Comment by arnoldnipper** [comment]
So, this was a +1000, @shane-kerr :D
