### ISSUE TITLE
Latency information

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/peeringdb#62]
In my daily peering planning i often consider the latency impact 
introduced after adding peers over remote exchanges. In order to get 
good measurements I usually ask my peering partners for a central server 
or something else that could make a reliable point of reference.

My suggestion is that you add a field for this information in the 
network-view of PeeringDB. Preferably one that accepts comma separated 
input (ipv4/ipv6/fqdn).

I'd be happy to promote this during the upcoming EPF8 if you decide to 
implement! ;)

Thank you for a great service!

/Rickard (skyflex on IRC)
## 

Rickard Östman, Nätchef, Bahnhof AB
rickard.ostman@bahnhof.net  AS8473
+46 8 55577132,      +46 761 110139

**Comment by arnoldnipper** [comment]
_http://ubersmith.peeringdb.com/admin/supportmgr/ticket_view.php?ticket=2768_

**Comment by mcmanuss8** [comment]
needs discussion - So you give me an IP on your network, what then? Unless your network is only in one city/metro this is not very helpful. I would need to know representative points of your network. For my use cases - give me a pingpoint for each major grouping of end users. 
Similar to the issue in #58 it seems like the schema need is more like a list of places this network offers connectivity (which could obviously be quite cumbersome to maintain):

country, state/province, city/metro, lat, long, v4pingpoint(s), v6pingpoint(s)

**Comment by eloos** [comment]
this seems like a heavy set of additional reference data to be included in PeeringDB. Once fields are added, they can no longer be removed until the next major version.
I also tend to see this outside the realm of the mission of PeeringDB. With OAuth and the database being publically available, I would suggest that someone comes up with this as a 3rd party app.
I propose to close this issue and not pursue it.

**Comment by job** [comment]
I think this (at this point in time) doesn't belong in PeeringDB

**Comment by arnoldnipper** [comment]
Doesn't belong to PeeringDB

**Comment by thatchrisp** [comment]
Too much room for error and really out of scope.
