### ISSUE TITLE
Add organisations and registered users to "Global System Statistics" in footer

### ISSUE THREAD

**Issue by ghankins** [peeringdb/peeringdb#620]
We report the number of registered users in our annual infographic, but it's missing from the footer.

Global System Statistics
728 Exchanges
17595 Networks
3500 Facilities
30937 Connections to Exchanges
28174 Connections to Facilities
NNNNN Registered Users  <-------------- add here

**Comment by arnoldnipper** [comment]
@ghankins, should we also add the number of `org`?

Global System Statistics
17254 Organisations <-------------- add here
728 Exchanges
17595 Networks
3500 Facilities
30937 Connections to Exchanges
28174 Connections to Facilities
NNNNN Registered Users <-------------- add here

**Comment by ghankins** [comment]
Good point, we are missing org as well.

**Comment by grizz** [comment]
+1 from me

**Comment by arnoldnipper** [comment]
@peeringdb/pc, please support

**Comment by ynbrthr** [comment]
+1

**Comment by vegu** [comment]
@pc @ghankins Registered, but only verified users, correct?

It's a minor either way, but verified user isnt a fast performance check as it needs to check email confirmation status (one table) and user organization status (another table). So will probably cache the count somewhere and refresh that several times per day.

**Comment by arnoldnipper** [comment]
Yes, verified users only, @vegu. And updating data every 24/12/6h seems to be fine.
