### ISSUE TITLE
Update API docs

### ISSUE THREAD

**Issue by grizz** [peeringdb/peeringdb#626]
Django Rest Framework is dropping support for the outdated coreapi used to generate our current API docs [0] in their next release, so we'll need to move off it soon.

Two popular options are Swagger UI and ReDoc, I prefer Swagger UI, but either look better than our current ones.

Might as well also take the time to add info to the docs themselves, as well as make it easier for the community to contribute docs.

[0] https://www.django-rest-framework.org/community/3.10-announcement/#continuing-to-use-coreapi
[1] https://swagger.io/tools/swagger-ui/
[2] https://github.com/Redocly/redoc

**Comment by grizz** [comment]
Need to make sure all extra query endpoints end up in here as well (for example, whereis on ixpfx).

**Comment by grizz** [comment]
@peeringdb/pc Could we get some +1 love here? :)

**Comment by arnoldnipper** [comment]
+1

**Comment by mcmanuss8** [comment]
Heavy +1

**Comment by shane-kerr** [comment]
+1

We clearly need to switch to something maintained. Since I'm not really an application developer I have no strong feelings about _what_ we change to.

**Comment by job** [comment]
Plus one

**Comment by arnoldnipper** [comment]
@Shawna, is there anything needed to implement this issue?

**Comment by Shawna** [comment]
Hello,

Nope! We're all set.

Thanks!

**Comment by grizz** [comment]
**Release Summary**

Internal mechanisms for generating the API docs have been updated to current standards. This also allows for easier user contributions to the docs themselves.
