### ISSUE TITLE
pre-2.0 historical SQL - should link to it be removed or should it be put back up?

### ISSUE THREAD

**Issue by ccaputo** [peeringdb/peeringdb#632]
I noticed at https://docs.peeringdb.com/ :

 - "The PeeringDB 1.0 MySQL interface is gone. The last available MySQL dump is archived at https://www.peeringdb.com/v1/final_export.sql"
  
but that pre-2.0 historical SQL file is no longer up.  Should it be put back up or should https://docs.peeringdb.com/ be adjusted in some way?

The CAIDA reference:  
 
 - "MySQL dumps from July, 29 2010 to March 14, 2016 are archived by CAIDA at http://data.caida.org/datasets/peeringdb-v1/."

is still fine/works.

**Comment by job** [comment]
A link to the caida project is probably sufficient by now. The final 1.0
dump was only meant as documentation for the transition to the API and not
relevant anymore.

**Comment by ccaputo** [comment]
Ok cool...  I removed the reference from the docs.
