### ISSUE TITLE
Korean translation

### ISSUE THREAD

**Issue by gordon-shumway-net** [peeringdb/peeringdb#633]
Hey together,
it would be cool to help with the Korean translation on translate.peeringdb.com
Can someone generate the necessary files for it and add it to the repository?
(As noted on https://docs.peeringdb.com/translation/)

Thank you!
Gordon :)

**Comment by arnoldnipper** [comment]
@peeringdb/oc, please add Korean (ko, ko_KR) to https://translate.peeringdb.com/languages/

**Comment by ccaputo** [comment]
Korean is now available for translation at:

  https://translate.peeringdb.com/

When it reaches the point where it makes sense to be visible on the beta site, please re-open this issue.  Thank you.

**Comment by arnoldnipper** [comment]
@ccaputo afair the decision was to have all languages available at beta immediately

**Comment by ccaputo** [comment]
> @ccaputo afair the decision was to have all languages available at beta immediately

#557 isn't implemented yet, but I have made the changes to the code base (beta.yaml, 10-locale.conf) and performed a hot patch on beta.  @grizz FYI re this being properly deployed in next deploy to beta.

**Comment by gordon-shumway-net** [comment]
Hey together,

how is it going in regard to #557 ?
Would be cool to have Korean on the Beta site soon.
We are at 60% at the moment and would like to check how it looks like. :)

**Comment by ccaputo** [comment]
Sorry about that.  It was on beta, but got removed in the last deploy.  Korean is back on beta now.  (I have no knowledge of #557's status.)

**Comment by arnoldnipper** [comment]
@ccaputo could you please make sure that new languages stay on beta. TIA

**Comment by grizz** [comment]
Ugh, I even double checked languages last beta deploy and clearly screwed up, sorry.

I believe #557 is waiting on PC approval -- that is the correct way to fix this. :)

**Comment by arnoldnipper** [comment]
> I believe #557 is waiting on PC approval -- that is the correct way to fix this. :)

Sure ... sorry
