### ISSUE TITLE
Remove support for python2

### ISSUE THREAD

**Issue by job** [peeringdb/peeringdb#634]
Python 2 is dead https://github.com/python/devguide/pull/344

we should remove any workarounds to support py2.7, and remove CI tests related to py2

**Comment by shane-kerr** [comment]
+1

Removing and simplifying code is a noble goal.

**Comment by mcmanuss8** [comment]
+1

**Comment by grizz** [comment]
This is already done for the server, unless I'm missing something?

For the client, it makes sense to me to leave it until it's a hassle, since there are still people using py2 in production (unfortunately).

**Comment by job** [comment]
@grizz we don't need to bear the cost of supporting people who run unsupported platforms. If you don't have py3 available on your operating system, something is VERY wrong and it'll be *your* problem, not ours.

**Comment by grizz** [comment]
Unless we're doing something with it, it's a cost to remove it :)

You're talking about the peeringdb python client and django-peeringdb, right?

**Comment by job** [comment]
Yeah, all of the software PDB maintains.

I’m aware there is some cost to removing it, but keeping it isn’t free
either. At some point the CI pipelines will stop supporting py2 as well, we
will need to move before our hand is forced. Now seems a good time :-)

**Comment by grizz** [comment]
Sure, and your django-peeringdb PR is a good reason to nuke it there. :)

**Comment by grizz** [comment]
** Release Summary **

Python 2.7 and 3.4 support is removed bring removed from PeeringDB packages.
