### ISSUE TITLE
Don't create a new net object, when there only is an ASN block

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/peeringdb#636]
Ex.: ASN [131482](https://peeringdb.com/cp/peeringdb_server/network/22161). This ASN is within an ASN block which is further assigned from APNIC to CNNIC. And CNNIC has not yet assigned this ASN to anyone. Hence querying via whois for an aut-num object does not return a result, but

whois -T aut-num as131482 | egrep -v '^($|%($| ))'
%ERROR:101: no entries found

The current prefill procedure however simply takes information from the RDAP query and is not able to detect whether this is an ASN block or a single ASN.

This is an @peeringdb/ac issue only IMO and does not have any impact on production. @peeringdb/pc, please vote.

**Comment by grizz** [comment]
I would tentatively vote +1 on this, but are we sure the information even exists in RDAP? This seems like one of those instances that it might not.

**Comment by arnoldnipper** [comment]
I did a check (>95% confidentiality, i.e. picked 400 ASN randomly from PeeringDB). Either the ASN was not assigned anymore **or** the handle equalled '"$ASN|AS$ASN"'. Could you please double-check.

**Comment by grizz** [comment]
From the original ASN:

```sh
curl https://rdap.apnic.net/autnum/131482 | jq .handle
"AS131481 - AS131580"
```

So we can probably assume that if it comes back as a range, it's not assigned yet. Do you know an ASN that CNNIC was delegated and has assigned?

**Comment by arnoldnipper** [comment]
E.g.
```sh
curl -sGL https://rdap.org/autnum/139589 | jq .handle
"AS139589"
``` 
Attached a file with all ASN assigned from APNIC to CNNIC. 
[20200129_CN_ASN.txt](https://github.com/peeringdb/peeringdb/files/4126433/20200129_CN_ASN.txt)

**Comment by arnoldnipper** [comment]
> So we can probably assume that if it comes back as a range, it's not assigned yet

Either a range **or** `null` (which seems to be what LACNIC returns when the ASN is not assigned).

**Comment by grizz** [comment]
It's all starting to come back to me, thanks for the walkthrough :)

Strong +1 from me.

**Comment by mcmanuss8** [comment]
+1 - seems reasonable. To be clear - do you want it to ignore ranges entirely or prefill for the entire range?

**Comment by arnoldnipper** [comment]
> +1 - seems reasonable. To be clear - do you want it to ignore ranges entirely or prefill for the entire range?

If you hit a range that means you hit what in whois speak is an as-block. If there is no autnum then there is no assignment. To answer your question: ignore

**Comment by arnoldnipper** [comment]
@Shawna, are implementation details needed?

**Comment by Shawna** [comment]
Hello,

No details needed, thanks so much!

**Comment by arnoldnipper** [comment]
**Release note**
This is a bug fix and is only relevant for the @peeringdb/ac.

**Comment by arnoldnipper** [comment]
```
curl -sGL https://rdap.org/autnum/139691 | jq '.handle, .startAutnum, .endAutnum'
"AS139578 - AS140601"
139578
140601
```
However https://peeringdb.com/net/21026

**Comment by arnoldnipper** [comment]
@vegu and @grizz. please check!

**Comment by arnoldnipper** [comment]
Please forget ... user modified `net` and `org` to strange values after returning `net` to APNIC
