### ISSUE TITLE
Ignore field validation during tutorial sync from prod

### ISSUE THREAD

**Issue by vegu** [peeringdb/peeringdb#637]
Right now when doing a sync from production to tutorial the sync will interrupt if it encounters any validation issues with the data. 

In the most recent example we ran into this issue with phone numbers that sill need manual correction from the #50 change. Some numbers could not automatically be corrected and syncing them to the tutorial server will raise a validation error.

We rolled out 2.18 to the tutorial server today and have hot-fixed this issue there for the time being, but going forward it might make the most sense to simply not do any data validation when doing these tutorial resets, since while ideally production data should be valid its not always going to be (like in this case)

**Comment by arnoldnipper** [comment]
+1

**Comment by mcmanuss8** [comment]
Would it be easier to just clean up the bad data, or null it out?

**Comment by vegu** [comment]
Changes on a case to case basis i'd say - in this case there are many network contact phone numbers that could not be automatically validated / formatted during the migrations when #50 was rolled out and probably will take some time until those are out of the system.

Null out during the sync you mean ? Could - bit more effort implementation wise but not much. Basically it comes down to whether it's ok for the tutorial instance to have the same bad data prod has or not, if not, then nulling out seems more reasonable :)

**Comment by arnoldnipper** [comment]
@vegu, but data validation happens not only when syncing to the tutorial server. Right? So why is it a big issue now? Because you installed beta on tutorial?

**Comment by vegu** [comment]
Phone number validation has been rolled out to both production and tutorial at this point. (2.18)

When we add new forms of data validation - such as phone number validation - there are cases where we are not able to automatically correct / remove all the invalid data at the same time the new validation is rolled out and that bad data will remain to exist until it is manually fixed. 

Tutorial sync works by pulling data from the production peeringdb api. 

There are still invalid numbers that exist in the production database, which tutorial will attempt to save (and validate) during the sync, causing a validation failure and aborting the remaining sync process.

My proposal is for tutorial to simply accept production api data as "good" without re-validating it itself, as it is supposed to be a copy of production data anyways.

cc: @arnoldnipper

**Comment by arnoldnipper** [comment]
> Would it be easier to just clean up the bad data, or null it out?

@mcmanuss8, this should happen in the production DB. Hence I fully support what @vegu proposes. For the tutorial server simply accept production api data as "good" without re-validating, as it is supposed to be a copy of production data anyway.

**Comment by arnoldnipper** [comment]
@vegu, afaik this is implemented. If so, please close this issue

**Comment by arnoldnipper** [comment]
@20c, could you please check whether field validation is being disabled during sync from prod to tutorial?

**Comment by vegu** [comment]
@arnoldnipper it's not implemented yet, so leaving the issue open

**Comment by arnoldnipper** [comment]
@pc, super low, otoh also low hanging. Let's get work done

**Comment by shane-kerr** [comment]
+1

**Comment by grizz** [comment]
+1

**Comment by vegu** [comment]
This has been fixed as part of #724.
