### ISSUE TITLE
When undeleting AS18138 aka /net/22211 system throws an 500

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/peeringdb#639]
Asking RIPE whois with -a flag gives 

```sh
%ERROR:101: no entries found
````

RDAP does not have AS information as APNIC has delegated this  block to JPNIC and JPNIC is not running an RDAP service. 

However, JPNIC has whois information.

```sh
whois -h whois.nic.ad.jp as18138
[ JPNIC database provides information regarding IP address and ASN. Its use   ]
[ is restricted to network administration purposes. For further information,  ]
[ use 'whois -h whois.nic.ad.jp help'. To only display English output,        ]
[ add '/e' at the end of command, e.g. 'whois -h whois.nic.ad.jp xxx/e'.      ]

Autonomous System Information:
a. [AS Number]                  18138
b. [AS Name]                    SAKURA-G
g. [Organization]               SAKURA Internet Inc.
m. [Administrative Contact]     KT749JP
n. [Technical Contact]          JP00072233
o. [IMPORT]
p. [EXPORT]
[Assigned Date]                 2018/09/20
[Last Update]                   2018/09/20 14:52:53(JST)
```

**Comment by shane-kerr** [comment]
I see there is a problem, but it's not clear to me what the exact fix proposed is. @arnoldnipper maybe you can explain it?

**Comment by arnoldnipper** [comment]
@shane-kerr, @grizz and @vegu: the backend is bailing out somewhere. Please have a look and fix

**Comment by vegu** [comment]
@arnoldnipper it's a bug triggered from `info_prefixes4` and `info_prefixes6` being null/blank, set them both to `0` (or any other integer value) to work around for now.

From a quick glance at the traceback this looks like a side effect from the python3 upgrade that was missed.

**Comment by vegu** [comment]
customer facing ui does not seem to be affected by this as it properly fails the integer validation on a blank input with a user friendly error message

**Comment by arnoldnipper** [comment]
@vegu, can you please restore /org and /net. The user is desperately waiting for it. TIA

**Comment by vegu** [comment]
@arnoldnipper done
