### ISSUE TITLE
Overlap of two or more ASN, both for IXP and Facilities

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/peeringdb#64]
http://ubersmith.peeringdb.com/admin/supportmgr/ticket_view.php?ticket=9315

I would like the ability to enter two ASNs and find all peering points that they
have in common.

For example, if I want t see where Akamai might be able to peer with HE, I would
like to be able to enter 20940 and 6939 and produce a list of the peering
locations present in both of their lists.

Would it be possible to get such a capability? If there's a security or other
concern, I'd even be willing to accept the idea that one of the ASNs in question
must be one of my own ASNs.

**Comment by mcmanuss8** [comment]
https://github.com/peeringdb/peeringdb/issues/16
