### ISSUE TITLE
Bad source translation

### ISSUE THREAD

**Issue by gordon-shumway-net** [peeringdb/peeringdb#645]
Hey together,

I couldn't find a way, how to suggest an source translation change.
How is the process for that?
Example:
Behind the link (https://translate.peeringdb.com/translate/peeringdb/server/ko/?checksum=75d73f4badd970e6), I found a "bad source". 
"rout" instead of "route" in "route server".

The string can be found here in the code:
**peeringdb_server/migrations/0027_never_via_route_servers.py** (https://github.com/peeringdb/peeringdb/blob/ba6f9b643253bed03b6884bae0c2ed15c326749f/peeringdb_server/migrations/0027_never_via_route_servers.py)

How to change that? :)

**Comment by grizz** [comment]
@gordon-shumway-net Thanks! It will be corrected on the next deploy.

**Comment by gordon-shumway-net** [comment]
Hey @grizz sounds great! :)

So it there is no process at the moment to change the original source language?
Is there a process planned/possible to do that through the weblate as well?

**Comment by grizz** [comment]
The source is actually in the code, so it needs a deploy to fix. This is the first time we've had (or someone has caught at least) a typo that got through QA on it, so it doesn't happen often.

**Comment by gordon-shumway-net** [comment]
Okay, fine! 💯 

One by the way question.
Do you have an idea where this string appears on the PeeringDB WebUI, is there a trick to figure that out?
It seems that it is a help text, but where, couldn't find it yet. :(

**Comment by arnoldnipper** [comment]
+1

**Comment by grizz** [comment]
@gordon-shumway-net 
> Do you have an idea where this string appears on the PeeringDB WebUI, is there a trick to figure that out?
> It seems that it is a help text, but where, couldn't find it yet. :(

Help strings are only used in the admin console and generated documentation.

**Comment by gordon-shumway-net** [comment]
@grizz 
> > Do you have an idea where this string appears on the PeeringDB WebUI, is there a trick to figure that out?
> > It seems that it is a help text, but where, couldn't find it yet. :(
> 
> Help strings are only used in the admin console and generated documentation.
Yeah okay, but where in the admin console?
For both an IX and a network I'm affiliated with it is not possible for me to see the help text. :(

**Comment by grizz** [comment]
@gordon-shumway-net the PeeringDB admin console, not visible to users
