### ISSUE TITLE
Possible for `ok` ixpfx to exist in `pending` ixlan

### ISSUE THREAD

**Issue by vegu** [peeringdb/peeringdb#649]
This should never be the case, and caused an issue with the peeringdb client sync function.

Needs further debugging, but from a quick glance it looks like it may have something to do with a situation where the prefix that is added to the pending ixlan is already soft-deleted and gets undeleted in the process.

**Comment by arnoldnipper** [comment]
+1 and @peeringdb/pc please add a +1 as obviously it is a bug

**Comment by grizz** [comment]
+1

**Comment by mcmanuss8** [comment]
+1 , let's fix this bug

**Comment by ccaputo** [comment]
SIX "peeringdb sync" got hit by this today.  I hope it can get fixed soon.

**Comment by koalafil** [comment]
@arnoldnipper Release Notes pls.

**Comment by arnoldnipper** [comment]
**Release Notes**
This issue fixes an internal bug
