### ISSUE TITLE
Add pointer from API docs to tutorial

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/peeringdb#650]
Most users surfing the [API docs](https://peeringdb.com/apidocs) are not aware that there are tutorials covering the use of the API. Hence a header/footer pointing to https://docs.peeringdb.com/#tutorials-and-workshops would make sense.

@peeringdb/pc, easy issue to decide on. Please make up your mind

**Comment by shane-kerr** [comment]
+1

Seems very helpful.

**Comment by grizz** [comment]
+1

**Comment by mcmanuss8** [comment]
+1 but we should bundle this with #626 (or at least not do it until #626 is done)

**Comment by arnoldnipper** [comment]
> +1 but we should bundle this with #626 (or at least not do it until #626 is done)

Imho #626 is done. @grizz please correct me if I'm wrong.

**Comment by grizz** [comment]
> > +1 but we should bundle this with #626 (or at least not do it until #626 is done)
> 
> Imho #626 is done. @grizz please correct me if I'm wrong.

@arnoldnipper it will be after next release

**Comment by koalafil** [comment]
Can we have the Release Notes pls?

**Comment by arnoldnipper** [comment]
**Release Note**

A URL is added from the API documentation website to the PeeringDB tutorials
