### ISSUE TITLE
Re-add feature to add org from ix/fac/net level in admin UI

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/peeringdb#651]
Looks like #597 removed this feature. See snapshot attached

![20200224 PeeringDB 00](https://user-images.githubusercontent.com/16888757/75180069-bb94ce80-573b-11ea-8b0c-c110f30374bb.png)

**Comment by arnoldnipper** [comment]
@peeringdb/pc #597 removed a feature which AC needs to have back asap

**Comment by mcmanuss8** [comment]
+1 let's do this asap.

**Comment by vegu** [comment]
@arnoldnipper If i click the looking glass icon next to the text box it opens the org list with the add org button - whats the different behaviour?

**Comment by arnoldnipper** [comment]
> @arnoldnipper If i click the looking glass icon next to the text box it opens the org list in a popup including an add org button - whats the different behaviour?

Thanks for clarifying @vegu. I was still looking for the "+" which has been there before. So, better description would have been needed. Re-opening #597 still is valid, though imho
