### ISSUE TITLE
missing delete button for user

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/peeringdb#653]
Add a section to the user's [profile](https://peeringdb.com/profile) to allow for deletion of their account

Split off from #121 which handles deletion of `org`

@peeringdb/pc please vote

**Comment by arnoldnipper** [comment]
+1

**Comment by shane-kerr** [comment]
+1

**Comment by mcmanuss8** [comment]
+1

**Comment by arnoldnipper** [comment]
@pc, what do you think? Currently, a user has to mail @ac to have their account deleted. A button would be cool. Just put it somewhere in the already overloaded https://peeringdb.com/profile :)

**Comment by mcmanuss8** [comment]
I guess but seems super low priority. How often do you get user deletion requests by the person themselves and not someone else?

**Comment by arnoldnipper** [comment]
> I guess but seems super low priority. How often do you get user deletion requests by the person themselves and not someone else?

Full ACK, @mcmanuss8 that this should have low priority. But when redesigning the profile section we shouldn't forget. So far I've seen <5 requests.

**Comment by leovegoda** [comment]
We should probably document how people can close their account and have their data deleted, especially if (for the time being) that is to send an e-mail to support@ and request it

**Comment by arnoldnipper** [comment]
> We should probably document how people can close their account and have their data deleted, especially if (for the time being) that is to send an e-mail to support@ and request it

This could and should go into the new profile section

**Comment by grizz** [comment]
I count three +1s

Here's a fourth, +1

**Comment by arnoldnipper** [comment]
I only now count three (@grizz, @mcmanuss8 and @arnoldnipper) ... but anyway

**Comment by grizz** [comment]
and @shane-kerr (github has been hiding similar comments, which is quite annoying) -- but, yes, irrelevant, we'll go forward!
