### ISSUE TITLE
Changing org while adding net results in 500

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/peeringdb#654]
Scenario:

 * user sends a request for adding a `net` under his `org`
 * According to RIR information the `org` is not the owner
 * AC adds new `org` via looking glass and "+"
 * New `org` shows up in `net` object under approval
 * Clicking on "Save" results in "Server Error (500)"

Workaround is to set the new `org_id` via API

@peeringdb/ac can you confirm?

**Comment by netravnen** [comment]
> @peeringdb/ac can you confirm?

Confirmed. _(Tested in Chrome, Chrome Incognito, Internet Explore, and Chrome Mobile (Android))_

**Comment by arnoldnipper** [comment]
Looks it has to do with unset prefix fields

**Comment by mcmanuss8** [comment]
That's a bummer. Let's fix this bug. +1

**Comment by grizz** [comment]
+1

**Comment by koalafil** [comment]
Can we have the Release Notes pls?

**Comment by arnoldnipper** [comment]
**Release Note**

Bugfix for the Admin Committee UI.
