### ISSUE TITLE
Reverse status == deleted for /net/22506

### ISSUE THREAD

**Issue by netravnen** [peeringdb/peeringdb#655]
Currently, #654 prevents edits to objects through the admin ui. The API interface has a check of sorts, preventing pdb admins to update status field `deleted` -> `ok`.
E.g. `$ curl  -H "Accept: application/json" -X PUT --data "$JSON_BLOB" https://$PDB_U:$PDB_P@www.peeringdb.com/api/net/$NET_ID`. Return code from the server is `{"meta": {"error": "Not found."}}`

Requested DB action:
1. Change field `status` to `ok` from `deleted`
2. Change `org_id` to `25360` from `16273`
3. Close this issue

**Comment by arnoldnipper** [comment]
done
