### ISSUE TITLE
Sort user IDs in https://peeringdb.com/cp/peeringdb_server/userpermission/xxxxx numerically

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/peeringdb#656]
Currently, the IDs are sorted alphabetically which does not make sense at all. Generally speaking, fields should be sorted by their nature.

@peeringdb/pc please +1

![Change User Permission   PeeringDB](https://user-images.githubusercontent.com/16888757/75760829-3495b680-5d38-11ea-8833-7a24d4a250db.png)

**Comment by shane-kerr** [comment]
+1

**Comment by grizz** [comment]
+1
