### ISSUE TITLE
How to add E.164 compatible extensions?

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/peeringdb#657]
This is not really an issue, but a question to our vendor, @Shawna, @vegu and @grizz 

Input: +CCnnnnnnnxmmm -> +CCnnnnnnnmmm
Input: +CCnnnnnnn;ext=mmm -> +CCnnnnnnnmmm

Q: how to add E.164 compatible extensions? And extension definitely is something different than just keep on dialing.

**Comment by grizz** [comment]
From what I can tell, E.164 defines a max of 15 digits, so I'm not sure extensions are going to be valid no matter what.

I'd probably want to start with asking if this is currently a problem? Do companies even use extensions anymore?

**Comment by mcmanuss8** [comment]
I know some companies do but I don't know that it's a big enough problem to warrant more investigation. Can we close until someone complains? :)

**Comment by arnoldnipper** [comment]
> Can we close until someone complains? :)

A user complained. That's the reason I opened the issue ;-)

**Comment by mcmanuss8** [comment]
> > Can we close until someone complains? :)
> 
> A user complained. That's the reason I opened the issue ;-)

ah :) I saw the "This is not really an issue" in your initial comment and thought it was just curiosity

**Comment by arnoldnipper** [comment]
> ah :) I saw the "This is not really an issue" in your initial comment and thought it was just curiosity

Maybe we should add a label "question" ;-)

**Comment by grizz** [comment]
I think closing this and saying there's no standardized way to handle extensions would be sufficient.
