### ISSUE TITLE
Improve MTU field

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/peeringdb#658]
The current release forces you to set a non-negative value. However, 37% of all `ixlan` records have set MTU to `null`. If you now edit the LAN field you most likely will have to edit the MTU.

Proposal:

 * change fields with value `null` to 1500
 * check for a reasonable minimum. 576?
 * check for a reasonable maximum. 65535?

**Comment by netravnen** [comment]
> check for a reasonable maximum. 65535?

I would recommend this value be
1. the largest commonly used IP MTU (e.g. 9000), or
2. The largest known hardware MTU currently supported by any routing/switching hardware (e.g. 9216, [src](https://en.wikipedia.org/wiki/Jumbo_frame))

**Comment by arnoldnipper** [comment]
> I am in favour of this value being

What if the `ix` is not using Ethernet?

**Comment by shane-kerr** [comment]
If we have to pick a value, I'd suggest 0. That is actually not allowed in IP packets but will match our constraints. Picking an allowed value means getting it wrong sometimes.

**Comment by job** [comment]
> > check for a reasonable maximum. 65535?
> 
> I am in favour of this value being
> 
> 1. the largest commonly used IP MTU (e.g. 9000), or
> 2. The largest known hardware MTU currently supported by most routing/switching hardware (e.g. 9216, [read more](https://en.wikipedia.org/wiki/Jumbo_frame))

@netravnen Arnold opened this issue about the value being `0` being problematic. The internet wide MTU is 1500 or a bit less, the most commonly used IP MTU absolutely is not 9000 in either ISP or IXP interconnection platforms. 

The value selection mechanism maybe should be a drop-down menu of commonly used MTU sizes at IXPs, with the default being 1500 because that is how the gear that most IXPs install by default will operate.

**Comment by job** [comment]
> > I am in favour of this value being
> 
> What if the `ix` is not using Ethernet?

The current PeeringDB data model is 100% focused on Ethernet with some historic remains of ATM. Any changes to the UI/characteristics of the MTU field in the current context, will be assumed by everyone to be Ethernet related. 

I don't think you are wrong that peeringdb should investigate supporting non-ethernet platforms if they exist, but for now this specific MTU value probably should be strictly interpreted as if it is an Ethernet thing.

**Comment by ynbrthr** [comment]
> > > check for a reasonable maximum. 65535?
> > 
> > 
> > I am in favour of this value being
> > 
> > 1. the largest commonly used IP MTU (e.g. 9000), or
> > 2. The largest known hardware MTU currently supported by most routing/switching hardware (e.g. 9216, [read more](https://en.wikipedia.org/wiki/Jumbo_frame))
> 
> @netravnen Arnold opened this issue about the value being `0` being problematic. The internet wide MTU is 1500 or a bit less, the most commonly used IP MTU absolutely is not 9000 in either ISP or IXP interconnection platforms.
> 
> The value selection mechanism maybe should be a drop-down menu of commonly used MTU sizes at IXPs, with the default being 1500 because that is how the gear that most IXPs install by default will operate.

both defaulting to 1500 and having a dropdown seems reasonable

**Comment by grizz** [comment]
@ynbrthr I don't see any voting or consensus here?

**Comment by ynbrthr** [comment]
Ha! @arnoldnipper suggested to use a default value of 1500 (and replace the nulls by that value), and check for min / max; @job was also in favor of defaulting to 1500, and go for a dropdown of used mtu sizes, and I seconded that. That looks like consensus to: use 1500 as default, and check the acceptable values, either with a dropdown or by specifying min/max. I'm happy to walk that back to 2 if you feel I've stretched it here.

**Comment by arnoldnipper** [comment]
**Summary**
 * use a default of 1500
 * replace 0/`null` by 1500
 * ad dropdown with common MTU sizes (1500, 9000) (what else)

Currently, we find sizes as

```
jq '.mtu' 1593292188-ixlan.json | sed 's/null/0/' | sort -n | uniq -c
    302 0
      1 1280
      1 1400
      1 1410
      2 1480
    407 1500
      1 1514
      1 1522
      2 1600
      1 2500
      1 2800
      4 4470
     52 9000
     14 9216
      1 9612
      1 10000
      2 10200
```

So, should we only offer 1500 and 9000?

**Comment by stillwaxin** [comment]
Before this is settled I'd like to point out that there should be some
definitions made before setting some values. For example what MTU is
specified? The IP MTU or the Ethernet MTU? Depending on the answer the
value would be different. If the answer is IP does that mean IPv4 and
IPv6? Take a look at the AMS-IX Config Guide and notice this phrase:
"The AMS-IX platform is designed to carry Ethernet frames with a
payload of up to 1500 bytes. MTU settings must be configured
accordingly."
This implies that the Ethernet MTU is higher than 1500 but is left unstated.

Perhaps the phrase Payload MTU is a good one to use as it implies that
for either IPv4 or IPv6 the MTU is what is stated but the IXP/Ethernet
MTU is arbitrary but supports up to the specified Maximum.

On Sat, Jun 27, 2020 at 5:19 PM Arnold Nipper <notifications@github.com> wrote:
>
> Summary
>
> use a default of 1500
> replace 0/null by 1500
> ad dropdown with common MTU sizes (1500, 9000) (what else)
>
> Currently, we find sizes as
>
> jq '.mtu' 1593292188-ixlan.json | sed 's/null/0/' | sort -n | uniq -c
>     302 0
>       1 1280
>       1 1400
>       1 1410
>       2 1480
>     407 1500
>       1 1514
>       1 1522
>       2 1600
>       1 2500
>       1 2800
>       4 4470
>      52 9000
>      14 9216
>       1 9612
>       1 10000
>       2 10200
>
> So, should we only offer 1500 and 9000?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.



-- 
[stillwaxin@gmail.com ~]$ cat .signature
cat: .signature: No such file or directory
[stillwaxin@gmail.com ~]$

**Comment by grizz** [comment]
All of this https://github.com/peeringdb/peeringdb/issues/658#issuecomment-650630449 plus changing the label to Payload MTU.

Any more discussion and I'll recommend PDB drops the MTU field entirely :)

**Comment by as44980** [comment]
In general I support the idea of Improving the MTU field, and echo concerns that 0 is not a useful value for any IX which claims to be live :)

> Before this is settled I'd like to point out that there should be some definitions made before setting some values. For example what MTU is specified? The IP MTU or the Ethernet MTU? Depending on the answer the value would be different. If the answer is IP does that mean IPv4 and IPv6? Take a look at the AMS-IX Config Guide and notice this phrase: "The AMS-IX platform is designed to carry Ethernet frames with a payload of up to 1500 bytes. MTU settings must be configured accordingly." This implies that the Ethernet MTU is higher than 1500 but is left unstated. Perhaps the phrase Payload MTU is a good one to use as it implies that for either IPv4 or IPv6 the MTU is what is stated but the IXP/Ethernet MTU is arbitrary but supports up to the specified Maximum.

Some very valid points here, and perhaps some overlap with #487 ? :)
