### ISSUE TITLE
Improve readability when users have special permissions

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/peeringdb#659]
Simply see snapshot attached. Impossible to read w/o getting eye cancer. Please invert the colour.

![20200306 PeeringDB 01](https://user-images.githubusercontent.com/16888757/76072871-02cf5a80-5f99-11ea-8ba9-34159bb88cdd.png)

@peeringdb/pc this should be any easy one to +1. If you do not agree, you have to read out every single line 🦅

**Comment by mcmanuss8** [comment]
+1 yeah that's not cool

**Comment by shane-kerr** [comment]
+1

**Comment by grizz** [comment]
+1

**Comment by tvberlin** [comment]
+1, please fix, thank you.
