### ISSUE TITLE
number of connected networks in the Exchanges search results

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/peeringdb#66]
http://ubersmith.peeringdb.com/admin/supportmgr/ticket_view.php?ticket=11850

very much miss the ability to see the number of connected
networks in the Exchanges search results.

```
            Previously I'd be able to gauge the size of a set of IXP's using
```

PeeringDB...and now I have to click on each search result individually and count
while scrolling.

```
            Please consider this feature request.
```

Thanks,

-Jacob Zack
Sr. DNS Administator - CIRA (.CA TLD)

**Comment by grizz** [comment]
@peeringdb/pc pasting from email here so there isn't a middle step:

With my PC hat on, I vote for 1

```
In regards to #66 we would like some input on how you would like it implemented. 

1. Add as a `net_count` field to the ix serilizer at the `/api/ix` endpoint - this endpoint is used by advanced search and thus will make the information available there as well. 
2. Join it into the advanced search after the result is retrieved via separate queries, leaving the api schemas untouched.

To us 1. would make sense, but adding fields that don't exist in the schema to the api has been a point of discussion before, so please advise on how you would like use to proceed.

The final - user facing - result in the advanced search would be identical, although their might be a slight delay before the net count is joined in if we go with the second solution.
```

**Comment by arnoldnipper** [comment]
+1 for 1, i.e " Add as a `net_count` field to the ix serilizer at the `/api/ix` endpoint - this endpoint is used by advanced search and thus will make the information available there as well. "

Adding new fields to the API is imho uncritical, dropping would be. I might be wrong

**Comment by eloos** [comment]
Option 1, also allows searching for IXs with minimal amount of members

**Comment by mcmanuss8** [comment]
+1 adding another column to the api is reasonable, as long as it's not a meaningful performance hit

**Comment by fhibler** [comment]
Option 1, especially with the API in mind (as mentioned by @mcmanuss8)

**Comment by grrrrreg** [comment]
Yes, Option 1 is also my preferred choice - API first.

**Comment by job** [comment]
I think the original ticket is about the WebUI, not the API.

Adding counters in the API seems weird, you can easily count elements yourself, if needed. If you have programmatic interest in an IXP you’ll request the full thing anyway. 

I also feel conflicted about exposing the information in the WebUI, because it may give unfair advantage to larger IXPs, hindering the opportunity for smaller competitor IXPs. We know that UI design drives bias, we need to be careful. 

I’d like to abstain from this vote.

**Comment by netravnen** [comment]
> I think the original ticket is about the WebUI, not the API.

I agree with job on this one. _(even thou I am not part of the PC)_ & I agree I think it misses the point of the original requester to add the capability in the API. Because as written by Arnold. It is laid out as a UI feature request. Not an API capability.

**Comment by arnoldnipper** [comment]
> Adding counters in the API seems weird, you can easily count elements yourself, if needed. If you have programmatic interest in an IXP you’ll request the full thing anyway.

curl -sG https://peeringdb.com/api/fac/1 --data-urlencode fields=net_count | jq
{
  "meta": {},
  "data": [
    {
      "net_count": 344
    }
  ]
}

**Comment by arnoldnipper** [comment]
> I also feel conflicted about exposing the information in the WebUI, because it may give unfair advantage to larger IXPs, hindering the opportunity for smaller competitor IXPs.

Why would that be unfair? We would show for every IXP the exact number. Nothing else.

**Comment by arnoldnipper** [comment]
> i suspect people may click *only* on the top 1 or top 2 IXP

I could buy your argument if we would serve the result in `sort -rn` only.  Currently, we sort by alphabetically by name (which also may already drive biasing)
