### ISSUE TITLE
Upgrade tutorial.peeringdb.com to latest release and keep it in sync with production

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/peeringdb#662]
tutorial.peeringdb.com should always be on the same release as peeringdb.com to give tutorial attendees the same experience and feature set.

@peeringdb/oc I guess this is only your domain. Or is there code change involved which would need +1 from @peeringdb/pc

**Comment by arnoldnipper** [comment]
@peeringdb/oc could you please take care. @peeringdb/outcom would need latest release on tutorial soon

**Comment by arnoldnipper** [comment]
@peeringdb/oc were you able to look into this?

**Comment by arnoldnipper** [comment]
@peeringdb/oc although it's not really pressing, I would like to see this addressed. Would you mind to give at least a reasonable RfS?

**Comment by arnoldnipper** [comment]
@pc, imho this doesn't touch production. But nevertheless, as it is here. Please +1

**Comment by shane-kerr** [comment]
+1

**Comment by grizz** [comment]
@peeringdb/oc will take care of this next production release.

**Comment by arnoldnipper** [comment]
> @peeringdb/oc will take care of this next production release.

Perfect ... and how do you ensure to keep tutorial in sync?

**Comment by grizz** [comment]
We'll add it to the production release tasks.

**Comment by arnoldnipper** [comment]
**Summary**

Keeping tutorial.peeringdb.com in sync with www.peeringdb.com is added to the production release tasks

**Comment by arnoldnipper** [comment]
> We'll add it to the production release tasks.

When? I've to do a tutorial at upcoming Apricot in a couple of days and would like the attendees to work with an up to date system. Tutorial currently is at 2.18.0

**Comment by grizz** [comment]
Updated, and set up the deploy to handle it. Took quite a bit longer than we anticipated since we had to convert it to the container system.
