### ISSUE TITLE
change default encoding of API calls to 'utf-8'

### ISSUE THREAD

**Issue by emileaben** [peeringdb/peeringdb#663]
As I've struggled many hours now with the interaction between the
python2 (don't ask, but for this i couldn't switch to python3 ...)
requests library and peeringDB API, I'd like to make the following
suggestion for change.

If I query:
https://www.peeringdb.com/api/ix

The response headers say:
content-type: application/json; charset=iso-8859-1

I think it makes more sense to have the charset be 'utf-8' for the json
output.

The current charset (iso-8859-1) causes python programmers extra steps trying to convert this to unicode. For instance, in the much used python requests library you need
to know and understand this. The standard approach is this:

   r_ixlan = requests.get("https://www.peeringdb.com/api/ixlan")
   j_ixlan = r_ixlan.json()

to get the json output (but all kinds of hell happens when you try
manipulating for instance the ixp 'name' field that contains non-ascii
code).

What one needs to do to get this right:
```
   r_ix = requests.get("https://www.peeringdb.com/api/ix")
   # do this differently because ascii/utf-8 etc.
   r_ix.encoding = 'utf-8'
   r_ix_txt = r_ix.text
   j_ix = json.loads( r_ix_txt )
   # ^^---- these 3 lines are hours of effort 
```

In my case I have the solution now, but I think it will save hours of
pain on people trying to program against peeringDB if you make this change.
Happy to make a twitter poll or somesuch to see if i'm the only one who
had to deal with this.

hope this helps make peeringDB even better!

thanks for providing this service, it's awesome

best regards,
Emile Aben
RIPE NCC

**Comment by arnoldnipper** [comment]
@peeringdb/pc makes sense to me, hence +1. But would like to hear the programmer's pov ... @grizz and @vegu

**Comment by shane-kerr** [comment]
+1

I'm fully in favor of moving everything to UTF-8.

**Comment by grizz** [comment]
+1

**Comment by koalafil** [comment]
Can we have a Release Note pls?

**Comment by arnoldnipper** [comment]
**Release Note**
The output of API calls will change from `content-type: application/json; charset=iso-8859-1` to `content-type: application/json; charset=utf-8`
