### ISSUE TITLE
Selection should only present undeleted objects

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/peeringdb#664]
If e.g. in the network context and selecting an organisation also deleted organisation are available for selection. There is no use case for this.

![Screenshot 2020-03-16 00 43 56](https://user-images.githubusercontent.com/16888757/76713331-2c6a4d80-6720-11ea-80e5-fbc955c181ec.png)

**Comment by arnoldnipper** [comment]
@peeringdb/pc please +1

**Comment by arnoldnipper** [comment]
I forgot to mention ... three of these names belong to deleted organisations

**Comment by shane-kerr** [comment]
+1

**Comment by mcmanuss8** [comment]
+1 makes sense

**Comment by grizz** [comment]
+1

**Comment by koalafil** [comment]
Can we have the Release Notes pls?

**Comment by arnoldnipper** [comment]
**Release Note**

Admin Committee only related. Only non-deleted should be presented for selection
