### ISSUE TITLE
Drop ixlan name from displaying at "Peers at this Exchange Point"

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/peeringdb#665]
Since release 2.19.0 there is only one ixlan per ix. Displaying the ixlan name buys nothing. Removing it frees up place for the network name.

![20200316 PeeringDB 00](https://user-images.githubusercontent.com/16888757/76718366-dce34c00-6736-11ea-9d98-14b7605a602b.png)

@peeringdb/pc simple yes/no +1/-1 imho

**Comment by shane-kerr** [comment]
+1

**Comment by mcmanuss8** [comment]
+1 but ideally we would do this at the same time as #543

**Comment by arnoldnipper** [comment]
> +1 but ideally we would do this at the same time as #543

Sure, but IPv6 addresses can become horribly long ... the longest are **39**
