### ISSUE TITLE
When changing owner of an ix admin GUI borks because of "Ixlan for exchange already exists"

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/peeringdb#666]
Clearly a bug IMHO. Work around is to change the owner_id via the API

![20200316 PeeringDB 01](https://user-images.githubusercontent.com/16888757/76806009-90ece180-67e0-11ea-9375-db56cce97f90.png)

@peeringdb/pc , please +1

**Comment by shane-kerr** [comment]
+1

**Comment by mcmanuss8** [comment]
+1

**Comment by grizz** [comment]
+1

**Comment by grizz** [comment]
+1

**Comment by koalafil** [comment]
Can we have the Release Notes pls?

**Comment by arnoldnipper** [comment]
**Release Note**

Bugfix for the Admin Committee UI
