### ISSUE TITLE
Fix use autocomplete fields in the admincom controlpanel to speed up loading times

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/peeringdb#667]
related to #597  this feature should be implemented everywhere where we currently have a dropdown menu. E.g.

 * https://peeringdb.com/cp/peeringdb_server/user/xxxx/change/ -> Add another User to Organization Affiliation Request

**Comment by arnoldnipper** [comment]
@peeringdb/pc please +1 as this is a bug fix for #597 probably

**Comment by shane-kerr** [comment]
+1

**Comment by grizz** [comment]
@arnoldnipper could you list all the places it's missing? We only see that one.

+1

**Comment by mcmanuss8** [comment]
+!

**Comment by arnoldnipper** [comment]
> @arnoldnipper could you list all the places it's missing? We only see that one.

my hope was that you know better. I will crawl through all the menus :)

**Comment by grizz** [comment]
We'll see if we can grep, but we're the ones who missed that in the first place. :)

**Comment by arnoldnipper** [comment]
To fix afais

 * https://peeringdb.com/cp/peeringdb_server/user/xxxx/change/ -> Add another User to Organization Affiliation Request
 * https://peeringdb.com/cp/peeringdb_server/ixlanprefix/xxxx/change/
 * https://peeringdb.com/cp/peeringdb_server/networkixlan/xxxx/change/ -> ixlan
 * https://peeringdb.com/cp/peeringdb_server/partnership/add/
 * https://peeringdb.com/cp/peeringdb_server/userorgaffiliationrequest/34524/change/ -> Org & User
 * https://peeringdb.com/cp/peeringdb_server/verificationqueueitem/33914/change/ -> User

**Comment by koalafil** [comment]
Amendment to https://github.com/peeringdb/peeringdb/issues/597
