### ISSUE TITLE
Add help text to "Add {Facility, Network, Exchange} tab

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/peeringdb#669]
Please add 

 **Only use this if you own the {Facility, Network, Exchange}**

in bold as the first line to the correspondent help text on the right side. Still, a lot of users try to add their connection to a facility/exchange via these tabs instead of going to their network and then adding the facility/exchange.

**Comment by arnoldnipper** [comment]
@peeringdb/pc please +1 to help @peeringdb/ac **TIA**

**Comment by shane-kerr** [comment]
+1

**Comment by grizz** [comment]
+1

**Comment by koalafil** [comment]
Can we have the Release Notes pls?

**Comment by arnoldnipper** [comment]
**Release Note**

Added a better help text to make crystal clear that adding a Facility, Network, or Exchange means that you are owning this object.
