### ISSUE TITLE
Add Looking Glass field to the IX object

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/peeringdb#672]
Currently, only the `net` object has a looking glass field. However, almost all `ix` provide a looking glass as well. Having it as a field in the `ix` object seems more appropriate than in the `net` object of the route servers.

@peeringdb/pc, please vote

**Comment by ynbrthr** [comment]
looks like a good idea to me

**Comment by mcmanuss8** [comment]
+1

**Comment by shane-kerr** [comment]
+1

**Comment by job** [comment]
I am not entirely sure about this proposal.

The *route servers* are a `net` object in the context of PeeringDB, and the referenced ASN is the ASN that hosts the looking glass.

An `ix` object to me is merely a layer-2 fabric, it cannot contain a looking glass because the looking glass only exists on the route servers, the layer-2 fabric does not have a BGP looking glass.

Adding a BGP-4 Looking Glass URL to IX objects (representing layer-2 fabrics) to me seems a misrepresentation of what actually happens on the engineering side of the house.

We discussed before how to create a reliable representation link from the list of peers to figure out who the "official" route servers are, I don't think we came to full consensus there.

@arnoldnipper can you elaborate what your vision is on what that URL in that object would represent?

**Comment by arnoldnipper** [comment]
> @arnoldnipper can you elaborate what your vision is on what that URL in that object would represent?

@job and @peeringdb/pc, while you are true that an `ix` is a layer-2 fabric per se the data model in PeeringDB also always associates an IPv4/v6 LAN with it. It is even not possible to add an `ix` w/o this layer-3 information. Hence it makes perfect sense.

**Comment by job** [comment]
That makes no sense to me, I’m sorry :-(

The peering IP addresses are assigned to interfaces on *routers* that run BGP. The IX *owns* the IPs, but doesn’t do any of the routing. That happens on the routers. Only routers can be BGP Looking Glasses, because they run a BGP process to inspect. The IX does not run EBGP.

An organization can own an ix object and a net object. The net object represents a construct that runs BGP. A route server runs BGP, so it can have a looking glass url. Route servers are net objects.

An IX object does not run EBGP. The peering lan IPs are not configured on the switchports. There can’t be an “ix” looking glass, we don’t have that technology in the internet.

Summary: ix objects cannot have a BGP looking glass because what an ix object represents in the whole technology stack does not run BGP.

**Comment by mcmanuss8** [comment]
I agree IXes are not networks and don't route.
But, from a user perspective, if I wanted to see what's going on with a given exchange, I would expect to go to peeringdb.com/ix/N to see things like:
1) A website where I can see information, maybe traffic stats
2) A link to a looking glass (if one is available) to see looking glass info

I wouldn't expect to go find the route servers' IX.

I think if we want to enforce this, we'd need a very clean/obvious way for the user to see "If you want to see routing information about this IX - this is the route server network object you can use".

From a data model perspective, I agree with your points @job. From a usability perspective, I agree with @arnoldnipper  that the proposal makes sense to most users. Is there a way we can make the data model clean while making the usability intuitive for users?

**Comment by arnoldnipper** [comment]
@mcmanuss8 and @job as much as I also like a clean data model, over time we have added a lot of sugar because it is more user friendly. 

From a BGP pov the LG probably will also show up in the RS ASN. But the URL to the LG should also be visible at the `ix` objects for the reasons @mcmanuss8 pointed out.

**Comment by job** [comment]
> I agree IXes are not networks and don't route.

Excellent, we are in agreement.

> But, from a user perspective, if I wanted to see what's going on with a given exchange, I would expect to go to peeringdb.com/ix/N to see things like:

but hold on, that seems a bit misleading to those poor users: that LG will absolutely not tell them what is going on at the IXP. The IXP doesn't route.

IXPs are not transit providers and this should be clear from the datamodel and how we operate the internet.

> I wouldn't expect to go find the route servers' IX.

why not?

> I think if we want to enforce this, we'd need a very clean/obvious way for the user to see "If you want to see routing information about this IX - this is the route server network object you can use".
> 
> From a data model perspective, I agree with your points @job. From a usability perspective, I agree with @arnoldnipper that the proposal makes sense to most users. Is there a way we can make the data model clean while making the usability intuitive for users?

I think the current code is clean and easy to use in this regard, and adding this feature will:

a) confuse users about what IXPs are
b) confuse IXP operators 
c) artificially prop-up IXPs to a position that most people will be unable to see the difference between IXPs and ISPs via peeringdb.

What problem are we solving?

**Comment by mcmanuss8** [comment]
> What problem are we solving?

We're trying to make it easier for users to discover where the looking glass for the route server of a given IX lives. As above, I don't think the flow as it stands now is intuitive, so we should take some action. I think see at least these two solutions:


1) Adding a dedicated field on the IX for that IX's route server url, and showing it on the /ix/ page
2) On the /ix/ page, pull the looking glass url of the IX's Route Server network object (if present) and showing it on the /ix/ page
3) Making the route server network object more prominent in some way s.t. the user has an easier time finding it. 

For 3, it looks like some IXes have done this by either putting the link in notes field, or naming the route servers cleanly (https://www.peeringdb.com/ix/31) is one - but even then I might see another IX's route server. I think some better linkage between the two objects is needed if we want to guide users through the data model cleanly

**Comment by mcmanuss8** [comment]
(Moving back to Decide until we can get consensus)

**Comment by koalafil** [comment]
Removed it from May Support Contract too.

**Comment by arnoldnipper** [comment]
> (Moving back to Decide until we can get consensus)

There was consensus. Question is how to implement it. Hence put it back to 3a, not 1. Or am I wrong?

**Comment by grizz** [comment]
I would recommend we leave the schema as is and just make a new section for any network of type route server, list the peers, and looking glass and any other field on the network object we think should be displayed on the IX.

Seems like a quick easy fix for usability.

**Comment by mcmanuss8** [comment]
> There was consensus. Question is how to implement it. Hence put it back to 3a, not 1. Or am I wrong?

There was, and then we got a -1 before it was implemented, which means we fall back to needing consensus again (so decide milestone). 

Ideally we should try harder to get full consensus before we fallback to the 75% voting threshold method of pushing things through. Let's try to work this out more. :)

**Comment by arnoldnipper** [comment]
My reading is a bit different. There was **full** consensus. It reached milestone 4 on 2020-04-17 and only got a -1 6 days ago, i.e. roughly **six** weeks after everything was ironed out.

**Comment by arnoldnipper** [comment]
@grizz, do I get it right that you want to move the peers from the `ix` to the `net` section of the RS ASN?

**Comment by arnoldnipper** [comment]
And still, in these six weeks the world kept spinning ... luckily

**Comment by grizz** [comment]
> @grizz, do I get it right that you want to move the peers from the `ix` to the `net` section of the RS ASN?

I was saying we have all the fields we want here on the network object, so if the network is type RS, we could inline list them in the ix display. We could even take it a step further and add a set on the ix for "Official Route Servers" or something like that.

**Comment by as44980** [comment]
A little late to this party, but I fully support maintaining a clear separation between the ix object representing a layer2 fabric and net objects representing any networks which provide layer3 services across this fabric.

That said, an easy and automation friendly means to display any looking glass provided by the ix operator does seem useful..

So on the basis that any such looking glass functionality would be run on a layer3 device with an asn, and that the net objects already have a "Looking Glass URL" record, it would make sense to do something like what is being discussed in #734 ..

But with respect to which asn (and thus net object) is the correct one to reflect a Looking Glass for an IXP, should we give any consideration that some IX's operate both Route Servers and Route Collectors.. with the later potentially being more representative of the participants of the IX fabric, rather than just those who participate in multi-lateral peering via the former?

**Comment by fischerdouglas** [comment]
IMHO, looking glass Attribute is already on the NET Object.

So, If IX objects could have a "net_id" field that would point(obviously) to the equivalent NET, it would be enough to know what is the Looking glass of that IX.

In terms of API query, is just a recursion.
In terms of Web interface, is just an hyperlink.

**Comment by fischerdouglas** [comment]
IMHO, looking glass filed is already on the NET Object.

**Comment by arnoldnipper** [comment]
> IMHO, looking glass filed is already on the NET Object.

Proposal is to have this field to save users a lookup. It should be read-only and be derived from the RS ASN object.

**Comment by as44980** [comment]
> Proposal is to have this field to save users a lookup. It should be read-only and be derived from the RS ASN object.

Partiuclarly given that the members on an IXP who peer with the _route-servers_ are likely to be only a subset of those who peer with the _route-collectors_, is it safe to assume that IXP's will use a common url to provide Looking Glass functionality displaying data derived from both route-collectors and route-servers?

**Comment by arnoldnipper** [comment]
New attempt and honouring that the `ix` is not a network and does not speak BGP. However, as @mcmanuss8 pointed out, it is about the user. Taking into account what @grizz proposed this is the new 

**Proposal**

 - add a read-only field `looking_glass`
 - pull this information from respective `net` objects, classified as official RS or RC
 - **TBD**: if we want to distinguish between RS and RC, fields could be named `rs_looking_glass` and `rc_looking_glass`. This would also make it crystal clear where the information is coming from

@peeringdb/pc, please discuss!

**Comment by as44980** [comment]
-1 from me until there is clear distinction between route-collectors and route-servers based on the fact only one of these could even remotely be expected to represent "the IX object"

**Comment by job** [comment]
-1

IX objects can reference RS/RC (net) objects, but an IX itself is a layer-2 construct... which does not run a BGP process, thus there cannot be a looking glass.

I think the linkage should be IX -> Net -> LG

Switches don't have BGP, fact of life.

**Comment by job** [comment]
Addition: I'm not opposed to https://github.com/peeringdb/peeringdb/issues/734 but this (#672) feels like an inappropriate shortcut in the data model

**Comment by martinhannigan** [comment]
Good observation.

**Comment by arnoldnipper** [comment]
> I think the linkage should be IX -> Net -> LG

That's exactly the proposal :)

**Comment by job** [comment]
> > I think the linkage should be IX -> Net -> LG
> 
> That's exactly the proposal :)

oh, that is not my impression

in your proposal the word 'looking_glass' is associated towards some LG URL in a Net object, while I argue that the #734 linkage already is sufficient

an IX object can point to a Net object, and from there there are links to LGs (which represent BGP processes running inside the Routers in the Net object's AS). There is no point in linking an IX object directly via a 'read-only' shortcut to a URL in a Net object. I imagine it causes user confusion as IX devices simply don't have BGP processes which can be inspected via "Looking Glasses".

-1 stands

**Comment by arnoldnipper** [comment]
@job, now we are talking about how to implement it. There is a huge benefit in making life easier for our users. That's what we do since a long time also breaking the data model.

And the only one who might be confused maybe you. I'll bet that 90+% of our users do associate a LG with an IX.

**Comment by mcmanuss8** [comment]
Consensus here seems to be to do #734 instead of this. All agreed? If so, will close this

**Comment by leovegoda** [comment]
The Product Committee has decided to close this issue. There was no agreement on the concept and the issue has not been discussed for six months or longer.
