### ISSUE TITLE
Add is_rs field to netixlan object

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/peeringdb#673]
Currently, there is no way to reliably identify the route servers for a given `ix`.  Adding the field `is_rs` would solve this problem. because then a `netixlan` object containing a field `"is_rs": true`  clearly identifies a route server for the given `ix`.

@peeringdb/pc, what do you think about this proposal?

**Comment by arnoldnipper** [comment]
I guess to make this foolproof we also would have to add a field `rs_asn` somewhere to the `ix` record. Otherwise too many might be tempted to set `"is_rs": true`, even though they are not a route server

**Comment by mcmanuss8** [comment]
Could we safety check this s.t. the net has to belong to the same org as the ix?

**Comment by arnoldnipper** [comment]
I could imagine that the route server is run by a different organisation than the ix. Hence, what extra level of safety check would be added? The ix already has to specify the route server asn.

**Comment by arnoldnipper** [comment]
@peeringdb/pc what do you think about it? Adding a field `rs_asn` to object `ix` and field `is_rs` to object `netixlan` would allow for automatic detection of route servers for an IX. Thoughts?

**Comment by grizz** [comment]
Isn't this already solved by adding the ASN as a network and setting type `Route Server`?

I don't see what advantages this has to the method we're already using.

**Comment by job** [comment]
yeah, you can already fully automated find the route servers of the IXP operator themselves. You can follow the connection from IXP to org, discover if the org has net objects, discover if those are route servers or not and if they are connected to the peering lan. all the data is there already today

and of course it is operator local choice whether to set up peering with 'official' route servers or un-official ones.

**Comment by arnoldnipper** [comment]
> Isn't this already solved by adding the ASN as a network and setting type `Route Server`?

No, the link between the IX and the ASN is missing

**Comment by job** [comment]
On Sat, Apr 18, 2020, at 14:46, Arnold Nipper wrote:
> > Isn't this already solved by adding the ASN as a network and setting type `Route Server`?
> 
> No, the link between the IX and the ASN is missing

Are you sure? IXP operators list their Route Server ASN as a participant of the IX.

**Comment by arnoldnipper** [comment]
> yeah, you can already fully automated find the route servers of the IXP operator themselves.

Your assumption is that the `org` running the `ix` and the `org` running the route servers are the same. In most cases that's true, but I can also imagine that a company offers route server services to other IXes as this requires more knowledge

**Comment by job** [comment]
On Sat, Apr 18, 2020 at 07:48:57AM -0700, Arnold Nipper wrote:
> > yeah, you can already fully automated find the route servers of the IXP operator themselves.
> 
> Your assumption is that the `org` running the `ix` and the `org`
> running the route servers are the same. In most cases that's true, but
> I can also imagine that a company offers route server services to
> other IXes as this requires more knowledge

Indeed, if there are 'official' third-party route servers, they are
likely to be operated as a white-label under the org of the IXP.

I think data for operators is already available, I've successfully
automated a network using the `Route Server` network type and the
existing relationship model.

So I'm not yet convinced this is worth spending a minor on.

**Comment by arnoldnipper** [comment]
> Indeed, if there are 'official' third-party route servers, they are likely to be operated as a white-label under the org of the IXP.

Maybe and maybe not. My proposal covers this as well as also those cases where you have other servers in the RS LAN.

**Comment by arnoldnipper** [comment]
@peeringdb/pc, I withdraw as I have another idea which covers this as well. Stay tuned :)

**Comment by grizz** [comment]
> > yeah, you can already fully automated find the route servers of the IXP operator themselves.
> 
> Your assumption is that the `org` running the `ix` and the `org` running the route servers are the same. In most cases that's true, but I can also imagine that a company offers route server services to other IXes as this requires more knowledge.
> 
> Furthermore, an IX might have more servers in the Route Server LAN like collectors, buoys and the like. Tell me how to find the RS then.

FWIW, it works for any org / network, if it's listed as a participant and is type RS, it accomplishes that.
