### ISSUE TITLE
Expose Last Updated fields on ix, fac and org

### ISSUE THREAD

**Issue by mcmanuss8** [peeringdb/peeringdb#675]
Relates to #541

**Comment by mcmanuss8** [comment]
Similar to #541 

ix:
1) Add the following fields, in this order, above Notes, below Protocols Supported:
    a) Last Updated:
    b) Last Peer Update:
    c) Last Facility Update:

2) Expose a) as the updated value of /ix/ - already there in the api
3) Add a new field to the API for b) - keeps track of the last time a peer was added or removed to this IX
4) Add a new field to the API for  c) - keeps track of the last time a facility was added or removed to this IX

fac:
1) Add the following fields, in this order, above Notes, below Protocols Supported:
    a) Last Updated:
    b) Last Network Update:
    c) Last Exchange Update:

2) Expose a) as the updated value of /fac/ - already there in the api
3) Add a new field to the API for b) - keeps track of the last time a network was added or removed to this fac
4) Add a new field to the API for  c) - keeps track of the last time an IX was added or removed with this fac

org:
1) Add the following fields, in this order, above Notes, below Protocols Supported:
    a) Last Updated:
    b) Last Network Update:
    c) Last Exchange Update:
    d) Last Facility Update:

2) Expose a) as the updated value of /fac/ - already there in the api
3) Add a new field to the API for b) - keeps track of the last time any network associated with this org was updated
4) Add a new field to the API for  c) - keeps track of the last time any ix associated with this org was updated
5) Add a new field to the API for d) - keeps track of the last time any facility associated with this org was updated

**Comment by arnoldnipper** [comment]
+1

**Comment by arnoldnipper** [comment]
Hanging around for 9 months now, @peeringdb/pc. Please vote!

**Comment by leovegoda** [comment]
The Product Committee has decided to close this issue. There was no agreement on the concept and the issue has not been discussed for six months or longer.
