### ISSUE TITLE
Data Ownership TF recommendation - 2:  ixfac and netfac dependency on "fac" conflict resolution

### ISSUE THREAD

**Issue by koalafil** [peeringdb/peeringdb#677]
This is **second** of the two issues I am creating corresponding to the two main recommendations from Data Ownership Task Force as noted in the [PeeringDB Data Ownership Policy Document.](https://docs.peeringdb.com/gov/misc/2020-04-06_PeeringDB_Data_Ownership_Policy_Document_v1.0.pdf)

TF requests that PeeringDB is modified in order to prevent operational disruption relating to handling of  "ixfac" and "netfac" data elements.

Relevant sections of the policy document are:

5.1.2) fac
...
The deletion or alteration of a "fac" data element may cause associated "ixfac" and "netfac" data elements to be deleted. Since this may cause an operational impact, this Task Force recommends that PeeringDB be modified to prevent disruptive changes to a "fac" data element while it has one or more dependent data elements. Facilities may work with the Admin Committee to remove dependent data elements in a safe manner.
...

7.2) "ixfac" and "netfac" dependency on "fac" 
In order to prevent operational disruption, this Task Force recommends that PeeringDB be modified to prevent deletion or updates of "fac" data elements from having a disruptive effect on dependent "ixfac" and "netfac" data elements, when data exists that would be disrupted. When needed, the removal of dependent data elements should be coordinated by the Admin Committee.

**Comment by koalafil** [comment]
Coupled with https://github.com/peeringdb/peeringdb/issues/676

**Comment by mcmanuss8** [comment]
Will be implemented in #697
