### ISSUE TITLE
Permissions not saved

### ISSUE THREAD

**Issue by tvberlin** [peeringdb/peeringdb#678]
Hi all,

when saving permissions for our users, some of the "per network" checkboxes are unchecked after reloading the page. No error is displayed. Affects users in https://peeringdb.com/org/8155.

Please let me know if you need more details.

Thanks,
Theo

**Comment by arnoldnipper** [comment]
So you did both, adding and then eventually **saving** at the end?

**Comment by tvberlin** [comment]
1. Edit permissions
2. Save
3. Re-open page or refresh it
= Randomly permissions are "lost".

**Comment by arnoldnipper** [comment]
I'm not able to reproduce this behaviour. Could you please provide a series of screen shots and your OS/browser version as well what you exactly did.

When I click a box and then "Add" and the "Save" everything is fine.

**Comment by grizz** [comment]
I'm also unable to reproduce, I'm guessing it was a network or client side issue. @tvberlin if you're still seeing this behavior, could you please re-open this with a screenshot, or preferably the output from your javascript console after hitting save?

Thanks!
