### ISSUE TITLE
Add read-only Superuser

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/peeringdb#679]
PC members should be able to have **full** read access to both User UI and Admin UI

**Comment by ynbrthr** [comment]
sounds like a swell idea. +1

**Comment by grizz** [comment]
+1

Implementationwise, giving read only access to the User UI might be a bit of a nightmare.

How about read only to Admin UI, and a mock org that they're actually admins of?

**Comment by arnoldnipper** [comment]
> How about read only to Admin UI, and a mock org that they're actually admins of?

+1 and we already have ["example.org"](https://peeringdb.com/org/25554) they could be admin of.

**Comment by vegu** [comment]
tested some and readonly for admin ui already mostly works given the proper permissions are set, however i did encounter at least one 500 error when viewing internet exchange listing with such a setup, should write tests for each view and make sure they load properly when viewed with a read only

also with the mock org thing, does not sound like there needs to be any developer action taken in that regard if i understand correctly.

estimating in the context of the above

**Comment by koalafil** [comment]
Can we have the Release Notes pls?

**Comment by ynbrthr** [comment]
**Release notes**

Provide PC members with a read-only access to the Admin UI.
