### ISSUE TITLE
Add net_count_ixf field to ix object

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/peeringdb#683]
Currently, there already is information and read-only field `net_count` which gives the total number of `netixlan` objects associated with an `ix`. For those `ix` providing an IX-F JSON import we also could compile the number of connections derived from that import. 

This information helps

 * the Outreach Committee to identify IX to work with
 * participants to rate the "completeness" of an ix
 * us to compile statistics

Proposal:

 * add field `net_count_ixf`to the `ix` object
 * if the `ix` provides an IX-F JSON import, the value is the number of connections derived from that import
 * if the `ix` does not provide an IX-F JSON import, the value is `null`

@peeringdb/pc and @ccaputo, thoughts?

**Comment by ccaputo** [comment]
Looks good to me.  Maybe both counts could be displayed on the /ix/ page, although there really is another aspect to the counts, which is how many are correct vs. how many differ.

**Comment by ynbrthr** [comment]
yes. +1

**Comment by grizz** [comment]
I'm for the concept, but we should probably wait and see how the Data Ownership TF guidelines get implemented before starting on this.

+1 at any rate.

**Comment by mcmanuss8** [comment]
Suggestion while we're in here: How about an attribute to show the last time the IX-F import was imported for this IX? Would let us know if this is something they run multiple times a day, daily, weekly, or rarely, or if they've stopped running it.

Otherwise, + 1

**Comment by arnoldnipper** [comment]
> Suggestion while we're in here: How about an attribute to show the last time the IX-F import was imported for this IX? Would let us know if this is something they run multiple times a day, daily, weekly, or rarely, or if they've stopped running it.

Nice idea. However, the IX-F JSON's timestamp is when you accessed it, not when it was changed the last time. Having #344 in mind we might go from pull to push. So, a timestamp when the last successful import happened, would make sense.

**Comment by grizz** [comment]
Putting this in 3a while we figure out the rest of the DTF specs.

**Comment by grizz** [comment]
**Summary**
Add `ixf_net_count` and `ixf_last_import` (timestamp) to the ix obect.

**Comment by koalafil** [comment]
Can we pls have the Release Notes? Thx.

**Comment by koalafil** [comment]
@arnoldnipper Release Notes pls

**Comment by arnoldnipper** [comment]
**Release Notes**
A field is added to the API object `ix`, called `net_count_ixf`, which indicates the number of `net` objects the exchange has in their IX-F JSON if they provide one. Otherwise, the value is `null`.
