### ISSUE TITLE
Automate creation of Release Notes

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/peeringdb#688]
As of 2.20.0, we have introduced Release Notes. The shepherd writes a Release Note as a final comment of the issue starting the first line with "**Release Notes**".

This ticket is about auto-extracting the Release Notes and adding them to the Release Note page.

@peeringdb/pc, please support

**Comment by grizz** [comment]
+1

Oops, I made the template **Release Summary** --  I like Notes better

**Comment by mcmanuss8** [comment]
+1 - we might need a new milestone to track what's committed to be developed in the next release but isn't closed yet. But I support either way.

**Comment by grizz** [comment]
**Summary**

Script that goes over GitHub Milestones and extracts data to build the markdown for the Release Notes page (https://github.com/peeringdb/docs/blob/master/docs/release_notes/index.md)

It should look for comments starting with `**Release Notes**` to add to the Summary column (which should probably be renamed to notes?)
