### ISSUE TITLE
To add "not specified" value for  IPv4/IPv6 Prefixes filelds and to update upper limits

### ISSUE THREAD

**Issue by magrmagr** [peeringdb/peeringdb#693]
Background:
Some known content operator disabled IPv6 BGP sessions with MSK-IX Route Servers and sent us email from his robot "please fix max prefix in PeeringDB".
After investigation, we noticed that probably some scripts and processes at that content operator side read from Peering DB values for IPv4/IPv6 Prefixes.

Our policy:
https://www.peeringdb.com/net/10215

Years ago we specified 0 and expect that this means "not specified" or
"infinity". Bacause we don't want to update this field (as IXP operator). 

Failed solution:
We decided to specify 1 000 000 and failed because
limitations of PeeringDB.
Current limits 500000 for IPv4, 50000 for IPv6.

Another story:
At the same time, Hurricane Electics sent us notification that recommended prefix limit for IPv6 sessions for peering with HE is 85000. In terms of this logic and numbers, we should specify minimum 100000 for IPv6 MSK-IX Route Servers and unable to do this.

Our suggestions:
- to add  "not specified" value for  IPv4/IPv6 Prefixes filelds
- alternatively, to extend limits for IPv4/IPv6 Prefixes for IXP/Route Servers.

**Comment by arnoldnipper** [comment]
This is the same as #671, @magrmagr as dropping the limit is not an option. Do you want us to close it?

**Comment by arnoldnipper** [comment]
limits have been updated
