### ISSUE TITLE
Auto focus cursor on search field on main website

### ISSUE THREAD

**Issue by job** [peeringdb/peeringdb#695]
Since there are no other forms on the https://www.peeringdb.com/ website, i think it would be useful of the user's cursor is automatically brought to the main search box at the top. This way folks can immediately start typing whatever they are looking for.

This approach might be useful in some other views on the peeringdb data as well

**Comment by arnoldnipper** [comment]
+1

**Comment by shane-kerr** [comment]
+1

**Comment by mcmanuss8** [comment]
+1 but only on / - not on any of the subpages

**Comment by arnoldnipper** [comment]
**Summary**

Auto focus cursor on search field on

 * /
 * /advanced_search
 * /advanced_search#ix
 * /advanced_search#net
 * /advanced_search#fac
 * /advanced_search#org
