### ISSUE TITLE
Lock some objects from being deleted by the owner

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/peeringdb#696]
As long as referenced by other objects the deletion of `ix`, `ixlan`, `ixpfx` and `fac` as well as `org`  has an operational impact. Hence we should special care of this.

Proposal:

 * this relates to objects `ix`, `ixlan`, `ixpfx`, `fac` and `org` only
 * if an owner tries to delete one of these objects which is still referenced
   * an error message pops up (e.g. "This object is still referenced. You aren't able to do so. Please contact PeeringDB Support")
   * Send a notification to PeeringDB Support by using the DeskPRO API

This relates to #676 and #677

@peeringdb/pc, please join and make up your mind

**Comment by grizz** [comment]
I assume you mean use the API to make a support ticket, right?

+1 from me

**Comment by arnoldnipper** [comment]
> I assume you mean use the API to make a support ticket, right?
> 

Right ... changed to: Send a notification to PeeringDB Support by using the DeskPRO API

**Comment by grizz** [comment]
@peeringdb/pc Need votes please

**Comment by mcmanuss8** [comment]
Instead of asking them to contact support, should we encourage self-service by listing out which objects are referenced and helping them contact the appropriate owners for cleanup? Thinking of reducing the load on AC here. 
If this is infrequent enough, maybe it's not worth doing though.

**Comment by arnoldnipper** [comment]
> If this is infrequent enough, maybe it's not worth doing though.

Cases I'm aware of
 * `ix` owners deleting `ixlan` by accident because they wanted to cleanup, i.e. lack of information what happens when they delete the object
 * `fac` owners deleting abandoned facilities
 * did not happen so often

**Comment by arnoldnipper** [comment]
@peeringdb/pc, what is your opinion? I still need supporters. And @mcmanuss8, was that a +1?

**Comment by shane-kerr** [comment]
I also support @mcmanuss8's idea of showing the user which references are locking the object from deletion. Before I put a +1 here I want to see what other people think. :smile:

**Comment by arnoldnipper** [comment]
> I also support @mcmanuss8's idea of showing the user which references are locking the object from deletion. Before I put a +1 here I want to see what other people think.

Well, I guess I do not really understand what @mcmanuss8 has in mind. If I e.g. own a facility I clearly see what other objects are depending on my object. I only have to visit  /fac/fac_id.

What is not so obvious is how deletion of an `ixlan` impacts the `netixlan`.  

The main idea really is to prevent that someone unintentionally deletes an object. That has happened several times with `ixlan` where the `ix`  wanted to "clean up".

**Comment by grizz** [comment]
Showing the objects that reference it in the error message makes sense to me, we have to query to see if they exist anyway.

While it happens infrequently, 20C has had to manually fix data a couple times that people were overzealous in their "clean up" which ultimately takes more time than adding the check for child references to deny the delete.

**Comment by mcmanuss8** [comment]
I'm +1 of the idea in general, I just wanted to discuss some tweaks to the output we give the users s.t. we maybe reduce load on AC. 
So to be explicit: +1 to the idea we should blocking deletions of objects that are referenced elsewhere.
But I think we should be a bit more informative than just "this is referenced elsewhere, ask AC for help" when this happens.

**Comment by shane-kerr** [comment]
If there's a simple URL the user can query to find these links, then it should be simple to include that URL in the error message right? "Deletion is not possible because there are references to this. You can find see these references at https://foo.bar/ixlanid"

**Comment by arnoldnipper** [comment]
Interestingly, while a `fac` or `ix` resp. `ixlan` owner is not able to remove a single referencing object (`netfac` and `ixfac`, resp. `netixlan`) they are able to remove **all** by removing the referenced object.

And just to protect the users from themselves there should be a good help text what happens when you delete an object. There are even more orgs which also delete their networks to "clean up" and then are wondering why they can't add it.

@mcmanuss8, please feel free to provide a help text.

@shane-kerr: they only have to click on the object they try to delete in case of `fac` and `net`. Luckily `ixlan` is not there anymore explicitly. Deletion of this caused most harm so far. Deleting the `ixlan` only prevent users from adding new connections.

**Comment by arnoldnipper** [comment]
@mcmanuss8 and @shane-kerr, any ideas how to move on here? We still need +1's to move on this issue, @peeringdb/pc. Please get involved

**Comment by shane-kerr** [comment]
+1

As long as it is easy for the user trying to delete to know what references are preventing the deletion, this is a great idea. Otherwise, it is still a good idea but sure to frustrate some people.

I think that we should encourage people to solve their own problems and not push them to contact PeeringDB support, when possible. Not that we should _discourage_ people from contacting support, of course!

**Comment by grizz** [comment]
I think maybe just a list of referenced objects in the message? Not sure there's a need for having a whole endpoint for that.

**Comment by arnoldnipper** [comment]
@shane-kerr and @mcmanuss8, do I get you right to move that to 3 and then to discuss _how_ to implement?

@job, @ynbrthr and @Yo-Robinson what do you think?

**Comment by ynbrthr** [comment]
+1, and what @grizz says: provide a list of referenced objects in the error message

**Comment by mcmanuss8** [comment]
Yes, we can work out if it's easy to do what Shane and I suggested w.r.t. showing them where something is referenced. If it's hard, we can split that into another issue.

**Comment by as44980** [comment]
>     * `fac` owners deleting abandoned facilities

In this use case #464 may be relevant, especially as there are  facilities with "No longer operational" in both their title and notes section which have a number of ix records which remain associated, despite the facilities in question having ceased to be operated as datacentres several years ago :)

**Comment by koalafil** [comment]
Can we pls have the Release Notes (as it gets moved to Ready for Implementation)? Thx.

**Comment by vegu** [comment]
No sure why this wasnt in ready for implementation yet, but we are actively working on it now, so moving it there 

Also still needs release notes @peeringdb/pc

**Comment by vegu** [comment]
@peeringdb/ac can you confirm for me that the intention for this is still to open/update a deskrpo ticket anytime a user is prevented from deleting a protected entity as described above?

**Comment by arnoldnipper** [comment]
Confirmed, @vegu  ...  please open/update a deskpro ticket anytime a user is prevented from deleting a protected entity

**Comment by koalafil** [comment]
@arnoldnipper Release Notes pls

**Comment by arnoldnipper** [comment]
**Release Notes**
To protect operational data objects `fac`, `ix`, `ixlan` and `org` are prevented from being deleted as long as there are other objects related to it. First, these objects must be deleted before the object itself can be deleted. The attempt to delete such a protected object gives an error message and also opens a ticket with the PeeringDB support.
