### ISSUE TITLE
Creating, changing, and deleting a netixlan object

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/peeringdb#697]
The `netixlan` is an important, if not the most important object in PeeringDB. It is governed by `net` and `ix` (and probably `fac` soon as well). Hence special care has to be taken when creating, changing, and deleting this object. While `netixlan` always are created by `net`, the authoritative source for being connected to an `ix` and the `ipaddr4` and `ipaddr6` is with the owner of the `ix`.  Procedures for conflict resolution must be provided. Furthermore, online tools to ease the resolution of a conflict w/o having to involve PeeringDB support.

Proposal:

 * implement the procedure laid out in the attached pseudo-code as an enhancement for the disabled IX-F JSON importer
[pdb_pseudocode_539_585_627.txt](https://github.com/peeringdb/peeringdb/files/4497812/pdb_pseudocode_539_585_627.txt)

 * to encourage data harmony to add several buttons, e.g.
   * if there are `ix` the `net` is not yet connected to but shown in the IX-F JSON import, add buttons "Add", "Dismiss" as well as "Reset hints". "Add" would be like "Edit" with prefilled fields
   * if there are conflicting records, add button "Resolve Conflict" which is like "Edit" with data already corrected in a way the user sees what is corrected
   * Buttons "Auto-Add" and "Auto-Resolve". Make sure the user sees what's done

This ticket implements #676, #677 and #678. It also relates/supersedes #539, #585 and #627 

@peeringdb/pc, please +1 asap and I really would appreciate if the whole team would get involved as this is an important issue and basically implements all of the recommendations from the DTF

**Comment by ccaputo** [comment]
To be clear, the pseudocode is just for reference.  I fully expect the developers to implement the recommendations of the Policy Document using the appropriate paradigms of the Django/Python environment.

**Comment by arnoldnipper** [comment]
@ccaputo, the problem is that the recommendations in the Policy Document are not really very well specced out.

Q: do we need to have a clear spec?

**Comment by ccaputo** [comment]
I discussed the pseudocode with the 20C folks in the past and have confidence they understand the intention of it.

**Comment by arnoldnipper** [comment]
#480 shows that less complex issues are obviously not that clear. So again my question whether we have to have a spec which is something less descriptive and more formal as the Policy Document, but more descriptive and less formal as the pseudo-code.

**Comment by ccaputo** [comment]
> #480 shows that less complex issues are obviously not that clear. So again my question whether we have to have a spec which is something less descriptive and more formal as the Policy Document, but more descriptive and less formal as the pseudo-code.

Sorry - I am unable to help further.  I am swamped.

**Comment by grizz** [comment]
We need to have a clear spec to implement, we're happy to work one up for review, it shouldn't take much with all the work you two have done.

@arnoldnipper are you done making tickets for the data ownership policy?

**Comment by arnoldnipper** [comment]
> we're happy to work one up for review, it shouldn't take much with all the work you two have done.

Thanks a lot, @grizz 

> @arnoldnipper are you done making tickets for the data ownership policy?

yes, I'm done

**Comment by arnoldnipper** [comment]
> We need to have a clear spec to implement, we're happy to work one up for review, it shouldn't take much with all the work you two have done.

Where do we stand here, @grizz?

**Comment by arnoldnipper** [comment]
@grizz and @peeringdb/20c ... it has been 15 days now. What did your "it shouldn't take much" mean in days?

**Comment by grizz** [comment]
Means it's taken a lot more than we anticipated, but we'll have the spec to the PC this week. Sorry for that delay.

**Comment by arnoldnipper** [comment]
@vegu would you mind to attach the spec to this issue so that the rest of the @peeringdb/pc can +1

**Comment by vegu** [comment]
Create database tables to store IX-F import data for conflict management.

Entries on both ends (ix-f members, pdb netixlans) are identified by (asn, ip4, ip6)

Give admincom admins and network admins the tools to accept changes proposed by the ix-f import that could not automatically be imported as laid out in the import protocol below

Admincom admin tools for conflict resolution will be added to the /cp interface

Network admin tools for conflict resolution will be added to the public network view 


### Import Protocol



---



#### Reference


##### Acceptable Data Changes



1. Data is different and the network has given consent for automatic updates

using the ix-f import protocol.		


##### Conflicting Data Changes



1. Data is different and the network has **NOT** given consent for automatic updates

using the ix-f import protocol.



2. Data is different and **cannot** be applied automatically. (edge cases)



---




*   If netixlan[as,ip4,ip6] exists and has same values as remote-ixf[as,ip4,ip6]
    *   If local-ixf[as,ip4,ip6] exists  
        *   Remove local-ixf[as,ip4,ip6] (as it has been resolved) 
        *   Update ticket notifying that issue was resolved
*   If netixlan[as,ip4,ip6] exists and has different values as remote-ixf[as,ip4,ip6] in the fields (speed, is_rs, operational)
    *   If pdb network has **allow ixp updates enabled**
        *   Update netixlan
    *   If pdb network has **allow ixp updates disabled**
        *   If local-ixf[as,ip4,ip6] exists and is identical to remote-ixf[as,ip4.ip6]
            *   Do nothing
        *   If local-ixf[as,ip4,ip6] **does not** exist or is different from remote-ixf[as,ip4,ip6]
            *   Create/Update local-ixf[as,ip4,ip6]
            *   Create/Update a ticket for admin com 
            *   Email the network
            *   Email the ix
*   If netixlan[as,ip4,ip6] does not exist
    *   If pdb network has **allow ixp updates enabled**
        *   No conflicts
            *   Add netixlan[as,ip4,ip6]
        *   Conflict
            *   If local-ixf[as,ip4,ip6] exists and is identical to remote-ixf[as,ip4,ip6]
                *   Do nothing
            *   If local-ixf[as,ip4,ip6] **does not** exist or is different from remote-ixf[as,ip4,ip6]
                *   Create/Update local-ixf[as,ip4,ip6]
                *   Create/Update a ticket for admin com 
                *   Email the network
                *   Email the ix
    *   If pdb network has **allow ixp updates disabled**
        *   If pdb network has entry for ix
            *   If local-ixf[as,ip4,ip6] exists and is identical to remote-ixf[as,ip4,ip6]
                *   Do nothing
            *   If local-ixf[as,ip4,ip6] **does not** exist or is different from remote-ixf[as,ip4,ip6]
                *   Create/Update local-ixf[as,ip4,ip6]
                *   Create/Update a ticket for admin com 
                *   Email the network
                *   Email the ix
        *   If pdb network **does not** have entry for ix
            *   If local-ixf[as,ip4,ip6] exists and is identical to remote-ixf[as,ip4,ip6]
                *   Do nothing
            *   If local-ixf[as,ip4,ip6] **does not** exist or is different from remote-ixf[as,ip4,ip6]
                *   Create/Update local-ixf[as,ip4,ip6]
                *   Email the network
*   If netixlan[as,ip4 or ip6] exists (either ip4 or ip6 matches)
    *   Treat same way as does not exist 
*   If remote-ixf[as,ip4,ip6] **does not** exist
    *   If pdb network has **allow ixp updates enabled**
        *   Delete netixlan[as,ip4,ip6]
    *   If pdb network has **allow ixp updates disabled**
        *   If local-ixf[as,ip4,ip6] exists and has flag for deletion
            *   Do nothing
        *   If local-ixf[as,ip4,ip6] exists and has no flag for deletion
            *   Add deletion flag to local-ixf[as,ip4,ip6]
            *   Create/Update a ticket for admin com 
            *   Email the network
            *   Email the ix
        *   If local-ixf[as,ip4,ip6] does not exist
            *   Create/Update local-ixf[as,ip4,ip6] with deletion flag
            *   Create/Update a ticket for admin com 
            *   Email the network
    *   Email the ix
*   If remote-ixf[as,ip4,ip6] contains invalid data **but **can be parsed
    *   If local-ixf[as,ip4,ip6] exists and is identical to remote-ixf[as,ip4.ip6]
        *   Do nothing
    *   If local-ixf[as,ip4,ip6] **does not** exist or is different from remote-ixf[as,ip4,ip6]
        *   Create/Update local-ixf[as,ip4,ip6] and flag as invalid
        *   Email the ix
        *   Create/Update a ticket for admin com 
*   If remote-ixf source cannot be parsed
    *   Create ticket for admin com
    *   Email the ix
    *   Create lock to avoid spamming notifications about the same error


### User Interface Requirements (AdminCom Facing)

AdminCom will have access to the local-ixf records inside /cp - these will hold the ix-f data for conflicts.

Each row will be editable allowing administrators to override values in the fields speed, operational and is_rs_peer.

Each row will have an “Apply” button that will apply the record to the corresponding netixlan. 

Each row will have an ix-f data field that is a json-dump of the remote ix-f data corresponding for the record, this is read-only.

Records in this table will not be manually deletable. They will be deleted when the conflict has been resolved.


### User Interface Requirements (Customer Facing)

Below are the requirements from Github ticket #697



*   if there are `ix` the `net` is not yet connected to but shown in the IX-F JSON import, add buttons "Add", "Dismiss" as well as "Reset hints". "Add" would be like "Edit" with prefilled fields
*   if there are conflicting records, add button "Resolve Conflict" which is like "Edit" with data already corrected in a way the user sees what is corrected
*   Buttons "Auto-Add" and "Auto-Resolve". Make sure the user sees what's done


#### Notes for implementation

**Add / Dismiss**

Show a list (only network admins can see) for each ix the net is not yet connected to where ix-f records exist that indicate a connection. If there is more than one ix have the lists start out in a collapsed version, where clicking the list can expand it, this to avoid cluttering the UI in cases where several instances are found.

One list per exchange. 

Each row would be similar to the actual netixlan listing rows, but have an Add and Dismiss button.

Clicking the “Add” button will create the netixlan and remove the local-ixf record, effectively marking it as resolved.

Clicking the “Dismiss” button will flag the local-ixf record as dismissed and hide it.

Each list comes with a “Reset Hints” button

Clicking the “Reset Hints” button will un-dismiss all dismissed records.

Each list comes with an “Auto Add” button

Clicking the “Auto Add” button will automatically add all records in that list.

**Resolve Conflict**

This is for existing netixlan records that were flagged to conflict with remote-ixf data. A conflict resolution may result in an update to the record or a deletion of the record.

These are presented in a separate list (only network admins can see) . Rows in this listing will show the record key (asn,ip4,ip6) plus any fields that differ, showing the users what changes would be made. In case of a proposed deletion that should be very visibly communicated to the user

There will be a resolve conflict button next to each record that when clicked will apply the suggested update or deletion. 

There will also be an auto-resolve button that resolves all the conflicts at once.


### Preventing disrupting changes

These are purely what made sense to me as to what counts as a disruption, please add / edit as you see fit.



*   Ixpfx.prefix cannot be changed if the parent ixlan has netixlan’s in it with that fall into that address space.
*   Ixpfx cannot be deleted  if the parent ixlan has netixlan’s in it with that fall into that address space.
*   Ixlan cannot be deleted if it has netixlans
*   Ix cannot be deleted if it has netixlans
*   Org cannot be deleted
    *   if it has netixlans (either through ix or through net)
    *   If it has ix
    *   If it has fac
    *   If it has net
*   Fac cannot be deleted
    *   If it has ixfac
    *   If it has netfac

**Comment by vegu** [comment]
@arnoldnipper done

**Comment by mcmanuss8** [comment]
+1

**Comment by grizz** [comment]
+1

**Comment by arnoldnipper** [comment]
@peeringdb/pc I really would like to have an explicit opinion from everyone. We have a quorum and are able to move forward, but this is really a very important issue. So I want to have it go smoothly :)

**Comment by arnoldnipper** [comment]
@Yo-Robinson, @ynbrthr, @job and @shane-kerr, please also vote. I don't want to have this stopped right before we want to release it.

**Comment by Yo-Robinson** [comment]
+1 from me

**Comment by ynbrthr** [comment]
+1

**Comment by koalafil** [comment]
Can we pls have the Release Notes? Thx.

**Comment by koalafil** [comment]
@arnoldnipper Release Notes pls

**Comment by vegu** [comment]
@peeringdb/pc looks like we forgot to specify what it means to "contact a network" and "contact an exchange"

I found some guidance in the related (albeit) older ticket of #585 where @arnoldnipper states the following points of contact

> tech_email || policy_email
> Policy || Technical || NOC || Maintenance

We understood this as the following, please advise if this is incorrect:

## Contact points for exchange

1. `tech_email` - if not set fall back to
2. `policy_email`

## Contact points for network

1. `Policy` - if none fall back to
2. `Technical` - if none fall back to
3. `NOC` - if none fall back to
4. `Maintainance`

**Comment by arnoldnipper** [comment]
> We understood this as the following, please advise if this is incorrect:

This is absolutely correct

**Comment by arnoldnipper** [comment]
**Release Notes**
We completely re-implemented the way a connection to an exchange is handled. This new procedure allows both for a safe heads up a network can give to their peers as well as a safe way for exchanges to get rid of stale entries. Moreover, it allows networks to easily acknowledge new entries at exchanges which use the IX-F importer feature. See also the webinar for detailed information on this new procedure.
