### ISSUE TITLE
Long requests gives "502 Bad Gateway"

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/peeringdb#7]
When I do

curl -s -k -X GET https://www.peeringdb.com/api/net\?id__in=3881,7881,6723,6724,6725,3884,6726,3570,6494,6453,7887,3220,6186,3222,6106,3265,3225,781,702,4880,785,8882,86,4842,433,475,709,120,1964,121,163,1925,4889,1651,479,4260,124,126,1,1613,1614,2,1656,4,4224,5,1385,1304,8,2961,5532,2927,5222,5263,2382,2698,2616,5539,2699,2344,5229,2033,2078,2037,3921,3693,3615,6266,3618,3386,3308,821,590,823,4960,4961,4964,596,283,599,203,1772,286,4697,4341,8383,1777,8303,208,4070,1422,1423,1192,4034,1111,4308,1467,1193,4035,1112,1427,4036,1469,4079,1197,1157,1159,5964,9650,5927,2462,5071,2464,5388,2152,5309,5077,6652,6611,7771,3736,6386,3465,3152,3195,3155,3198,981,983,670,986,947,906,633,360,635,678,4734,4735,1812,1855,327,4190,1815,1501,8153,4196,1506,1233,1234,4199,1236,1279,9777,2895,9464,2501,2858,2819,5195,2273,5199,2235,2277,2236,6732,6460,3856,6464,6424,3502,3276,7236,7238,91,4890,4850,13,14,4894,170,8581,17,99,4814,8541,8815,4500,487,1660,1977,4231,8506,1624,1625,8549,4549,1354,1355,1357,1317,1319,5893,9812,2971,2625,9233,5233,2310,2313,2084,2006,6852,3932,3974,3938,3623,7350,6589,3312,3668,3080,3629,3397,3042,7002,7318,7319,7048,873,521,837,291,250,8977,4977,4937,8663,4622,254,4352,258,217,8041,1748,1476,8359,1477,1163,1479,1124,1125,9622,9938,2702,9311,5626,2704,2430,2431,1081,5042,2435,2477,5004,1086,1045,1004,1046,1006,9089,1007,6970,6939,6350,6312,3432,3707,6043,3436,3167,950,914,997,601,684,4740,4782,648,8745,4745,4704,4430,1864,10147,10106,1280,1555,1240,4122,1282,1201,1598,1517,1599,1204,9471,5432,2591,2592,5433,2595,2596,2281,2241,9124,2283,2558,2202,2519,6782,3554,3241,7285,3559,3208,721,763,21,450,725,23,1981,1900,27,457,29,1903,184,1904,499,458,1946,186,104,1949,1675,1635,149,1677,1363,1367,9590,2943,2986,2630,5595,2905,2988,2906,5282,2989,5283,5516,9284,2366,2325,5208,2327,2095,2096,2098,6860,3900,6591,3671,6596,6243,3320,3324,7327,3327,3055,3014,3016,3058,3017,572,8901,261,576,577,4631,262,4987,263,222,1792,1751,1752,539,1753,1480,268,269,1483,4092,1799,1443,1170,1486,8013,4018,8019,1138,9940,5320,5321,2755,5010,2404,2173,5014,2132,1014,2174,1098,6362,7715,3715,3716,7758,7487,3131,965,694,380,4710,341,301,617,8795,1872,4714,1833,346,347,4402,1836,308,309,8406,1565,4449,4176,1569,1258,5483,2521,9171,5171,2250,9448,2214,2218,3878,6132,7292,3567,7259,731,72,733,31,75,779,4874,423,8560,78,150,110,1955,1914,1956,1682,1915,1641,196,1683,155,115,4211,1918,1644,198,116,1371,4294,8295,1372,118,4257,2995,2600,2957,5210,2648,5217,2062,5259,2024,2028,3992,7954,3332,3647,6215,3060,3608,7063,3024,890,891,893,854,541,8993,4911,585,270,505,4641,4916,273,1721,508,10003,1764,236,278,1724,1766,1451,279,1726,1452,1412,1728,4338,1498,1459,1418,1186,1189,1108,5992,5994,9640,5641,5918,2491,9607,2494,2727,1062,2728,2180,2181,5022,2496,9379,2456,2100,9065,5025,1066,5068,6993,6995,6680,3725,3411,6061,3497,3142,3101,3418,972,3149,621,662,979,311,4722,316,1803,1804,358,4727,319,8497,8182,1848,4498,4418,1221,4103,1538,1264,1223,4105,1265,1268,1227,2800,2885,5493,2803,2534,5499,2577,2536,5188

I get "502 Bad Gateway"

**Comment by vegu** [comment]
This is caused by the header buffer size limitation on the server. We ended up increasing the limit, and made sure that if the limit is hit a 414 "Request URL too long error" is returned instead of 502. 

We upped the limit from 4k to 16k - hopefully sufficient for most cases, upping it further should only be done after discussion.

Note that there has to be an upper limit for security reasons, and i think a case can be made that if you need to pass 1000s of ids to the query, it'd be reasonable to do it against a local copy of the db instead, or split up the query.

This fix will roll out with 2.0.12
