### ISSUE TITLE
add python whois server

### ISSUE THREAD

**Issue by grizz** [peeringdb/peeringdb#701]
Currently it's running from inetd in docker which means the whois process needs to start every connection and it doesn't support support IPv6.

Should be redone to support IPv6 at the least.

**Comment by arnoldnipper** [comment]
+1

**Comment by shane-kerr** [comment]
+1

Makes sense. Probably as simple as using the [socketserver](https://docs.python.org/3/library/socketserver.html) module from the standard library with the `ThreadingMixIn`.

**Comment by grizz** [comment]
Closing based on the upcoming retirement of the whois service: https://docs.peeringdb.com/blog/whois_to_close/
