### ISSUE TITLE
Requests from peeringdb-py error 500

### ISSUE THREAD

**Issue by vegu** [peeringdb/peeringdb#702]
Happens on requests coming from the peeringdb python client to the api.

Does not happen when normally accessing the api through the browser or curl.

Issues is with the `CLIENT_COMPAT` setting

**Comment by arnoldnipper** [comment]
+1

**Comment by mcmanuss8** [comment]
+1 let's fix this ASAP

**Comment by grizz** [comment]
Pushing through to emergency release per @job and @mcmanuss8
