### ISSUE TITLE
Sanitize IRR as-set/route-set field

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/peeringdb#704]
Now that IRR checking is in place we should sanitize IRR as-set/route-set fields, i.e. 

1.  remove obvious wrong fields automatically (everything HTTP(s))
2. fix not properly formatted fields (delimiter)

While may be done automatically, 2. requires manual work. 

Proposal:

 * @20c or @peeringdb/oc to compile a list of net objects containing non-compliant `irr_as_set`fields
 * @20C or @peeringdb/pc to do 1. as stated above
 * @peeringdb/ac to fix fields according to 2. ( I volunteer)

@peeringdb/pc, please +1

**Comment by funkestefan** [comment]
Yes for remove obvious wrong fields automatically (as in links to websites)
No for fix not properly formatted fields, unless:
- community knows about the upcoming changes we intend to make in their IRR fields
- community is aware of how to parse pdbs IRR fields with a location identifier

**Comment by arnoldnipper** [comment]
> No for fix not properly formatted fields, unless:
> 
> * community knows about the upcoming changes we intend to make in their IRR fields
> * community is aware of how to parse pdbs IRR fields with a location identifier

This was in the release notes for 2.20.0

**Comment by grizz** [comment]
Shouldn't this wait for a decision on #605 so AC can help separate fields while they doing it?

I'm +1 for this either way.

**Comment by job** [comment]
I think this can proceed irrelevant of #605, because we can't on behalf of users decide which entry is IPv4 and which is IPv6. That goes against POLA.

+1 to fix what arnold described in the OP

**Comment by arnoldnipper** [comment]
> I think this can proceed irrelevant of #605, because we can't on behalf of users decide which entry is IPv4 and which is IPv6. That goes against POLA.

AC, of course, would fix not properly formatted IRR AS-SET/RS_SET in accordance with the users.

**Comment by grizz** [comment]
**Summary**
Product a tool that lists invalid as-sets

**Comment by arnoldnipper** [comment]
I guess that would only include **syntactically** wrong as-sets. Or will that also check whether the as-set really exists?

**Comment by job** [comment]
> I guess that would only include **syntactically** wrong as-sets. Or will that also check whether the as-set really exists?

I hope your guess is right. Since the validation in peeringdb is only done on syntax (and not actual network lookup), this list should also not be created with network lookup.

**Comment by arnoldnipper** [comment]
Q: should we also do semantic checking? According to one of our paradigms to remove/correct wrong information we probably should do.

**Comment by job** [comment]
Yes, I think we should /only/ do semantic checking.

But in some cases it will not be clear to the admin what the intention of the peeringdb user was, in such cases we have to reach out to the Network Operator and ask them what they intend to publish. 

If the user doesn't know or doesn't answer, the sanest default is probably to put the ASN number in the IRR field so there is /some/ information which is valid, and confirms with our understanding of IRR anyway.

admin process probably be something along the lines of:

1) look at the invalid entry, make a guess what was intended (stuff like remove a semi-colon)
2) check with PeeringDB user what they want
3) if no answer, or don't know, suggested value is the ASN of the network object, in format "AS$as_number" (where $as_number is the integer value from the net object, and the string is prefixed with the capital letters "AS")

Step 3 will always result in a valid object name.

**Comment by arnoldnipper** [comment]
> Step 3 will always result in a valid object name.

But not necessarily in an existing as-set ...

**Comment by job** [comment]
> > Step 3 will always result in a valid object name.
> 
> But not necessarily in an existing as-set ...

Right, but if the object is syntactically invalid, and the owner of the peeringdb record doesn't know what _would_ be the correct AS-SET, the default is to reference the AS number. 

```
hanna:~ job$ bgpq4 AS15562 | tail -2
ip prefix-list NN permit 209.24.1.0/24
ip prefix-list NN permit 209.24.5.0/24
```

using the AS as the 'fallback' is safer than putting in nothing, or making a guess, because at least the net object's owners "own" prefixes are part of filters.

I guess the alternative is to leave the field empty?

**Comment by netravnen** [comment]
> using the AS as the 'fallback' is safer than putting in nothing, or making a guess, because at least the net object's owners "own" prefixes are part of filters.
> I guess the alternative is to leave the field empty? My point is that we should be careful to have admins guessing what the intentions were. :)

👍

Fallback to `AS<aut-num>` if if the as-set field is left empty.

I think this will be the most idiot-proof solution in the long-term. (and also the simplest)

**Comment by arnoldnipper** [comment]
> I guess the alternative is to leave the field empty?

That would definitely be my preference

**Comment by grizz** [comment]
I meant only semantic checking, yes.

Leaving it empty is the correct choice -- no information is better than misinformation. If anyone using the data wants to turn NULL into AS$aut-num, they're welcome to do that on their side.

**Comment by arnoldnipper** [comment]
@peeringdb/20c, would you please compile a list (net_id, irr_as_set) of still broken entries? @peeringdb/ac did already fix a couple of entries. However, only those containing non-compliant characters.

**Comment by grizz** [comment]
@arnoldnipper - This issue is to create a tool that would list those failing validation, we could cobble together a query by hand to check this now, or maybe a better idea is a new issue that would take object type and field name, and list anything failing validation, since I think we'll keep wanting to run these types of reports.

Thoughts?

**Comment by arnoldnipper** [comment]
> better idea is a new issue that would take object type and field name, and list anything failing validation, since I think we'll keep wanting to run these types of reports.

I very much like this idea as there e.g. also still phone numbers to sanitize as well. What fields other than `irr_as_set` and `*phone` come to mind?

**Comment by grizz** [comment]
Those two right now, and we keep adding validation so I'm sure there will be more in the future. We've had at least prefixes and netixlan IPs before.

**Comment by arnoldnipper** [comment]
@grizz, I've got it right to close this issue and to open a new one?

**Comment by grizz** [comment]
Yes, that sounds good, thanks!

**Comment by arnoldnipper** [comment]
Records have been sanitized. #722 is implementing a tool for finding left-overs
