### ISSUE TITLE
API: limiting to "latitude=null" is not working

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/peeringdb#711]
```
curl -sG https://peeringdb.com/api/fac --data-urlencode latitude=null --data-urlencode fields=id | jq '[.data[] | .id] | length'
0
```
**but**
```
curl -sG https://peeringdb.com/api/fac --data-urlencode --data-urlencode fields=id,latitude | jq '[.data[] | select (.latitude==null) | .id] | length'
483
```
I..e when I shift the selection to jq I get the wanted result. Looks like a clear bug to me. @peeringdb/pc what do you think?

**Comment by arnoldnipper** [comment]
@peeringdb/20c, are you able to confirm?

**Comment by vegu** [comment]
`=null` is currently not supported as a query parameter. It will interpret it as "null" (string).

Possible solutions:

make the api understand =null is to be treated as a null comparison or implement a query filter similar to how the django api already does it with a `_isnull` suffix

So yes, confirmed that this is currently not working.

**Comment by arnoldnipper** [comment]
Not really a bug, but a missing feature
