### ISSUE TITLE
User is unable to update their net record

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/peeringdb#712]
User netbarretos (and me as well) is unable to update their record. I'm able to reproduce this error. However, no further information is given what is going wrong.

@peeringdb/pc, please +1 to get this resolved asap. @peeringdb/ac have you seen this as well recently? And are you able to reproduce this?

![20200505 DeskPRO image003](https://user-images.githubusercontent.com/16888757/81096668-0df62680-8f07-11ea-9fd1-eb445d16852f.jpg)

**Comment by ynbrthr** [comment]
+1

**Comment by DarwinCosta** [comment]
Hi Arnold,

Yes, I saw this coming along and tried to reproduce this but received the same error as you (without many details about it).

Looking forward further feedback from @peeringdb/pc <https://github.com/orgs/peeringdb/teams/pc>

Cheers,
Darwin-.

**Comment by DarwinCosta** [comment]
Hi Arnold,

Yes, I saw this coming along and tried to reproduce this but received the same error as you (without many details about it).

Looking forward further feedback from @peeringdb/pc <https://github.com/orgs/peeringdb/teams/pc>

Cheers,
Darwin-.

**Comment by arnoldnipper** [comment]
@peeringdb/20c, are you also able to reproduce this? And probably have a fix?

**Comment by Shawna** [comment]
We will look into this and get back to you.

Thanks!

**Comment by vegu** [comment]
@arnoldnipper @DarwinCosta I was able to update the record after fixing the irr as set value to "AS-BARRETOS RS-BARRETOS" - looks like a bug with the new irr as set validation we rolled out with the previous release.

**Comment by shane-kerr** [comment]
+1

For such serious operational bugs I wonder if we really want to require PC voting?

**Comment by vegu** [comment]
This seems to be triggered by the `/` character, other irr as set related validation errors are handled nicely and with a user friendly message, as far as i can tell.

**Comment by vegu** [comment]
https://peeringdb.com/api/net?irr_as_set__contains=/&fields=asn,id,irr_as_set&pretty

There are currently 240ish networks that have a `/` in their irr_as_set that would run into this when trying to update their network. I guess it used to be that networks put urls into that field.
 
The actual fix to the validator will need a code release - i wonder if it's sensible to do a data correction in the meantime.

**Comment by arnoldnipper** [comment]
```
curl -sG https://peeringdb.com/api/net\?irr_as_set__contains=//\&fields=,id | jq '.data | length'
53
```
of them are URLs which could safely be set to "".  I'm happy to go through the remaining 59. And I'm pretty sure @peeringdb/ac will give full support. I.e. we should be able to have a hotfix by Friday latest then.

Does that sound like a plan?

**Comment by funkestefan** [comment]
Talking about data ownership: @peeringdb/pc  or Stewards should probably take a look into it before we change net/orgs data to ""

**Comment by ccaputo** [comment]
Could each affected network be emailed to ask for permission to help them, along with the change that will be made for them in case they prefer to do it themselves?  Include a notice that until this is fixed, they will not be able to edit the rest of their Network page, or as appropriate.

**Comment by arnoldnipper** [comment]
One of the paradigms of PeeringDB is to fix **wrong** data. having an URL as `irr-as-set` clearly is wrong. All the other `irr-as-set` containing a "/" will be fixed together with the owners. This is inline with Data Ownership Document IMO. Does that make sense?

**Comment by job** [comment]
Makes sense to me, Arnold.

**Comment by funkestefan** [comment]
ACK

**Comment by vegu** [comment]
Spent some more time looking into this and there are other characters (that i have tested) that trigger this bug: `!"*([])?.=+`  - looks like it was introduced with the hotfix to re-enable sourceless irr validation (#706)

**Comment by mcmanuss8** [comment]
> For such serious operational bugs I wonder if we really want to require PC voting?

Bugs and regressions don't really require voting. We also have a process for expedited hot fix releases which I expect we should use here once we work out the best way to fix.

**Comment by arnoldnipper** [comment]
@vegu resp. @peeringdb/20c how do we move on here?

**Comment by arnoldnipper** [comment]
Moved directly to "3 Consensus Finalized" as this clearly is a bug

**Comment by koalafil** [comment]
Can we have the Release Notes pls?

**Comment by arnoldnipper** [comment]
**Release Note**

Bug fix. Missing pointer to where the non-compliant value is
