### ISSUE TITLE
Make the api understand =null

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/peeringdb#713]
Related to #711 

@vegu writes: `=null` is currently not supported as a query value. I haven't checked the code, but my assumption is that it interprets it as "null" (string).

The proposal is to make the API `=null` query.

@peeringdb/pc, please vote +1

**Comment by mcmanuss8** [comment]
That's fine until someone makes a network/org called "null" :) 
What's best practice for APIs doing this? An empty string?

**Comment by arnoldnipper** [comment]
> That's fine until someone makes a network/org called "null" :)

Is that really an issue? A name is not nillable. Hence it is clear to search for the string "null" and not for `null`

**Comment by mcmanuss8** [comment]
I was thinking more of a search for something like "Null Networks, Inc." or "The null internet exchange" might break if you passed search=null and expected it to be search='%null%'

**Comment by arnoldnipper** [comment]
You never pass search=null, but always "field_name"__(in|contains|starts_with)= if "field_name" is a string. Otoh "field_name"="" and "field_name"=null would of course be the same.

**Comment by grizz** [comment]
Which fields and what use case for what you're asking?

Generally, db fields are not null, but instead empty unless you want a tristate column. In case, you would use `field_name`__isnull.

**Comment by arnoldnipper** [comment]
> Which fields and what use case for what you're asking?

Generally, all fields where it makes sense. The use case was to find facilities where longitude is empty/null E.g. 

```
curl -sG https://peeringdb.com/api/fac/8395 --data-urlencode depth=0 --data-urlencode fields=id,name,latitude,longitude | jq '.data[]'
{
  "id": 8395,
  "name": "РТКомм-Юг (RTKomm-Yug)",
  "latitude": null,
  "longitude": null
}
```

**Comment by arnoldnipper** [comment]
Generally, db fields are not null, but instead, empty unless you want a tristate column. In case, you would use field_name__isnull.

**Comment by arnoldnipper** [comment]
> Generally, db fields are not null, but instead empty unless you want a tristate column. In case, you would use `field_name`__isnull.

There are tons (~ 11,000) of fields with value `null`. So, why do you say: Generally, db fields are not null, @grizz. Especially for querying it would be nice to single them out, instead of doing it via a jq-select.

**Comment by grizz** [comment]
@arnoldnipper because we usually make null invalid, if you have a report of fields that are null please send it to the list for discussion. It's probably a matter of fixing validation or cleaning up data.

**Comment by arnoldnipper** [comment]
@grizz 

```
    813   "arp_sponge": null,
    530   "ipaddr4": null,
   7072   "ipaddr6": null,
    437   "ixf_ixp_member_list_url": null,
    816   "ixf_last_import": null,
    500   "latitude": null,
    500   "longitude": null,
    260   "mtu": null,
      1   "rs_asn": null,
```

**Comment by arnoldnipper** [comment]
**Proposal**

@peeringdb/oc and/or @20c to change all field values from `null` to "".

@peeringdb/pc please vote.

**Comment by arnoldnipper** [comment]
> @arnoldnipper because we usually make null invalid, if you have a report of fields that are null please send it to the list for discussion. It's probably a matter of fixing validation or cleaning up data.

Coming back to this. With #800, specifically [defaulting to `null`](https://github.com/peeringdb/peeringdb/issues/800#issuecomment-847253152), your proposal won't work, @grizz Hence, if undefined the value is
- "" for string fields
- `null`else

Does that make sense, @peeringdb/pc?

**Comment by leovegoda** [comment]
The Product Committee has decided to close this issue. There was no agreement on the concept and the issue has not been discussed for six months or longer.
