### ISSUE TITLE
Support for Django 3

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/peeringdb#715]
In an [issue](https://github.com/peeringdb/peeringdb-py/issues/35#issuecomment-626039585)  in peeringdb-py user @mngan is asking for $subject

**Comment by shane-kerr** [comment]
+1

We have to do this eventually anyway, since version 2 is only supported another 2 years:

https://static.djangoproject.com/img/release-roadmap.688d8d65db0b.png

**Comment by grizz** [comment]
We should stick with the LTS versions in my opinion, we're on 2.2 now, so should wait until 3.2 unless there's a feature we need.

**Comment by shane-kerr** [comment]
I guess that's fair since it seems like an LTS is coming out every 2 years.

**Comment by arnoldnipper** [comment]
@grizz, prepare for [3.2 LTS](https://www.djangoproject.com/download/)

**Comment by grizz** [comment]
+1

Yep, we're waiting for 3.2.1 at least :)

**Comment by egfrank** [comment]
**Summary**
- Once Django 3.2.1 is released, upgrade to that version
- Update all other dependencies to new majors where possible as well
- Remove NSP and associated tables
