### ISSUE TITLE
[i18n] Add a new locale

### ISSUE THREAD

**Issue by Quenty-tolosan** [peeringdb/peeringdb#716]
Hello, I would like to translate into Occitan, iso code «oc».
Would it be possible to add it to the weblate so I can contribute?
Best regards

Quentí

**Comment by arnoldnipper** [comment]
@peeringdb/oc would you please add locale "oc" to the languages of our [translation](https://translate.peeringdb.com/) tool

**Comment by ccaputo** [comment]
Occitan is now available for translation at:

https://translate.peeringdb.com/

When it reaches the point where it makes sense to be visible on the beta site, please re-open this issue. Thank you.

**Comment by Quenty-tolosan** [comment]
Thanks @ccaputo !
But when I want to logon weblate with my newly PeeringDB account it loops and fails =/

**Comment by ccaputo** [comment]
> Thanks @ccaputo !
> But when I want to logon weblate with my newly PeeringDB account it loops and fails =/

Hmm.  Can you post a screenshot or screenshots?  I tested a translate.peeringdb.com logoff and then re-login with PeeringDB web site re-authorization and it worked with Chrome but not with Safari.  Trying to diagnose Safari now.

**Comment by ccaputo** [comment]
> Here: https://framapic.org/usN7QbEY8Reu/oXzgf3t1mtm7.png
> It says something might be wrong with the token
> 
> Edit: doesn't work with Chronium either =/

Does that redirect endlessly?

**Comment by Mejans** [comment]
I think it's endless.
I've just log off and tried to log in via weblate and it says now:
«

La vérification CSRF a échoué. La requête a été interrompue.

Pour des raisons de sécurité, ce site exige la présence d’un cookie CSRF lors de l’envoi de formulaires. Ce cookie permet de s’assurer que votre navigateur n’a pas été piraté.

Si vous avez désactivé l’enregistrement des cookies dans votre navigateur, veuillez le réactiver au moins pour ce site ou pour les requêtes de même origine (« same-origin »).
»

**Comment by ccaputo** [comment]
If you log out of PeeringDB and then log back in, does that improve anything?

**Comment by Mejans** [comment]
Nop =/

**Comment by ccaputo** [comment]
Please try again now.  Thanks!

**Comment by Mejans** [comment]
Nothing new :( I've disabled Firefox enhanced protection.

**Comment by ccaputo** [comment]
Does refreshing while holding down shift as you click Reload help at all?  (trying without cached data)

Hold down the Shift key and left-click the Reload button.
Press "Ctrl + F5" or press "Ctrl + Shift + R" (Windows,Linux)
Press "Command + Shift + R" (Mac)

**Comment by Mejans** [comment]
It doesn't help =/
On PeeringDB it says I have a limited account because I have no organisations, would it be the cause?

**Comment by ccaputo** [comment]
Could be.  Is your PeeringDB account verified?  Can you tell me what it is so I can check?  (Or email it to ccaputo@peeringdb.com - just the username/login-name)

**Comment by Mejans** [comment]
Quentí

**Comment by ccaputo** [comment]
> Quentí

Ok - I think that is the problem.  Your PeeringDB status is currently pending.   @arnoldnipper ?

**Comment by arnoldnipper** [comment]
> Ok - I think that is the problem. Your PeeringDB status is currently pending. @arnoldnipper ?

This user did not request affiliation to any organisation so far ...

**Comment by Mejans** [comment]
yes because I'm a lambda wiling to translate :)

**Comment by Mejans** [comment]
cc @arnoldnipper @ccaputo why is this issue closed? I have just tried and it still won't work =/

**Comment by arnoldnipper** [comment]
@Mejans, the loacale has been added. Please open a new issue for your problem. Thank you

**Comment by ccaputo** [comment]
> cc @arnoldnipper @ccaputo why is this issue closed? I have just tried and it still won't work =/

Hi.  https://github.com/peeringdb/peeringdb/issues/720 was created to fix the looping issue, but as far as you not being able to edit a language until your PeeringDB is no longer pending, that is by design as I understand it.  Are you able to take steps necessary for your PeeringDB account to become non-pending?
