### ISSUE TITLE
Enable sort and reverse sort of IP column in IX display

### ISSUE THREAD

**Issue by ccaputo** [peeringdb/peeringdb#72]
When viewing a IX record, it would be great if the IPv4/IPv6 column could be clicked on to cause a forward or reverse natural sort, like the other columns.  Natural sort being important because IP address sorting is not a simple matter.

If column remains consolidated, IPv4 address should be the primary sort key, with a secondary key being IPv6 address.

**Comment by arnoldnipper** [comment]
As both IPv4 and IPv6 addresses are unique there is no secondary key ... perhaps I don't get it, though

**Comment by ccaputo** [comment]
The secondary sort key is needed for when the primary key is empty/null/blank.  So if there are multiple entries with no IPv4 address, the IPv6 addresses should present as naturally sorted.

**Comment by grizz** [comment]
@peeringdb/pc This has been 2 years as well, let's decide.

+1 from me

**Comment by mcmanuss8** [comment]
+1 good to do

**Comment by koalafil** [comment]
@arnoldnipper can we pls recheck the milestone status? I see 2 PC members supported so far. We seem to need a 3rd one for this to reach consensus. Maybe it just needs to be highlighted if you are a supporter too.

**Comment by arnoldnipper** [comment]
+1

**Comment by shane-kerr** [comment]
+1

**Comment by koalafil** [comment]
Can we pls have the Release Notes? Thx.

**Comment by arnoldnipper** [comment]
**Release Notes**

Sort and reverse sort of IP column in IX display are added. Sort of the IP addresses in the expected natural order. The IPv4 address is the primary sort key. The IPv6 address is the secondary key.
