### ISSUE TITLE
Make spinning up a development peeringdb instance fully automated

### ISSUE THREAD

**Issue by mcmanuss8** [peeringdb/peeringdb#724]
Goal: With a single command, I should be able to spin up a peeringdb development instance s.t. I can make and test code changes locally. 
Why: Will significantly lower the bar for developers who want to contribute to peeringdb. Currently the bar is high enough that very few people are doing it.

Should coordinate with ops committee to ensure that we don't develop something that deviates/branches from existing ops code to spin up containers/servers

**Comment by mcmanuss8** [comment]
@peeringdb/pc please vote
@peeringdb/oc  - thoughts welcome here

**Comment by arnoldnipper** [comment]
+1

**Comment by ynbrthr** [comment]
+1

**Comment by grizz** [comment]
**Summary**
Will convert to docker-compose and spin up a local DB, sync from PeeringDB (with optional API Key from #266), and refactor the tests to run against MySQL inside the container. Then update CI to use that method on check in as well.
