### ISSUE TITLE
Private copy of PeeringDB tutorial server for video

### ISSUE THREAD

**Issue by ghankins** [peeringdb/peeringdb#726]
We need a copy of the latest PeeringDB version running in tutorial mode for the PeeringDB video:
 - a copy of tutorial (this already allows for RFC1918 and documentation ASN)
- removing any "tutorial" and use the production logo
- being accessible as video.peeringdb.com
- Arnold and Greg should be admins
- we estimate we'd need the server for a maximum of two months

**Comment by koalafil** [comment]
For process log purposes: This is for Outreach Committee. Greg confirmed via e-mail that this does not need to go through the full Product Committee process on OC ml.

**Comment by ghankins** [comment]
We found an alternative that will integrate better with the video, so we don't need a server for screen shots anymore.
