### ISSUE TITLE
RS Peer Checkbox also visible on IX Site

### ISSUE THREAD

**Issue by gordon-shumway-net** [peeringdb/peeringdb#727]
Hey together,
wouldn't it make sense to have the RS Peer Checkbox, which is visible on the Network site at the moment, also visible on the IX site?

Example, take a network you are interested in and you see at which Public Peering Exchange Points, it peers and if they peer with the Route Server or not.
If you then click on one of the IXs, it's not possible to see, which Networks peer with the Route Servers of the Exchange. So the opposite way.

What do you think about that?:)

**Comment by ynbrthr** [comment]
+1

**Comment by netravnen** [comment]
From a user perspective, and user-friendliness point of view, the
suggestion is definitely worth considering. Primarily worth it for users
primarily using PeeringDB via the Website. (Less so, if the primary
accessing PeeringhDB is via the API.)

**Comment by arnoldnipper** [comment]
> Less so, if the primary accessing PeeringhDB is via the API

Via the API you have **full** information about everything as you query the `netixlan` object. Q: if including `is_rs_peer` should we also include `operational`?

Both are useful information, however, space is limited. @peeringdb/pc, any thoughts?

**Comment by ynbrthr** [comment]
if we have to pick one, i would stick to is_rs_peer, as, so far as I can see, only a tiny minority of interconnects have an operational status of false.

**Comment by arnoldnipper** [comment]
> if we have to pick one, i would stick to is_rs_peer, as, so far as I can see, only a tiny minority of interconnects have an operational status of false.

Even with one additional, there is the question of where to place it. If that is solved then there might be space for the 2nd as well

**Comment by mcmanuss8** [comment]
> if we have to pick one, i would stick to is_rs_peer, as, so far as I can see, only a tiny minority of interconnects have an operational status of false.

But we also only recently added that. It's also the case that if we don't show it in the UI, it's less likely people are going to use it!

In general, I think we should be consistent and showing both on both pages, in the same ways.

**Comment by ynbrthr** [comment]
Actually, it seems to be present in both views already:

<img width="565" alt="image" src="https://user-images.githubusercontent.com/58094221/85630291-601f1280-b641-11ea-9ce3-54c323af2844.png">

<img width="570" alt="image" src="https://user-images.githubusercontent.com/58094221/85630337-7200b580-b641-11ea-8f9a-4cdc3640438c.png">

To recap, we have: on the ix view, per member: the operational status if set to false, port capacity, the addresses, and the peering policy; on the net view, per ix: the operational status if set to false, port capacity, the addresses, and the RS checkbox.

**Comment by grizz** [comment]
If we can display it with a single icon so it fits in correctly, I'm all for it -- +1

**Comment by arnoldnipper** [comment]
> If we can display it with a single icon so it fits in correctly, I'm all for it -- +1

We badly need a UX designer

**Comment by vegu** [comment]
> If we can display it with a single icon so it fits in correctly, I'm all for it -- +1
> We badly need a UX designer ... +1

Yeah someone needs to come up with an icon for it, as a placeholder can also see if you can find something fitting below (these are all available to us)

https://getbootstrap.com/docs/3.3/components/

**Comment by vegu** [comment]
Moving to 3a until we have selected an icon (even if its just a placeholder one)

**Comment by ynbrthr** [comment]
Err, sorry, why do we need an icon? It's about having the RS checkbox available on the ix view as it is on the new view. What am I missing?

**Comment by vegu** [comment]
As i read it the intention is to have an icon similar to the `operational` status that wont require space in the table header. If we are fine reserving space for "RS Peer" in the headers, or displaying the checkbox with an "RS Peer" label appended to it then lets pick a place where to put it and it can be moved to 4 also.

Does that make sense?

**Comment by arnoldnipper** [comment]
All we need is an icon. What about this one? 

![is_rs_peer](https://user-images.githubusercontent.com/16888757/87230291-4276da80-c3af-11ea-935b-7e3a9e744074.png)

**Comment by grizz** [comment]
@arnoldnipper I love it! :) I wonder if it would be better to just have an "rs" icon though, so people wouldn't need a legend?

@ynbrthr if we don't have a specific icon, it would need a column with header for it, which would clutter up the UI.

**Comment by arnoldnipper** [comment]
> @arnoldnipper I love it! :) I wonder if it would be better to just have an "rs" icon though, so people wouldn't need a legend?

Sounds good as well but users might think this is the RS?

**Comment by grizz** [comment]
Oh, good point. That's why I'm not in UX design!

**Comment by vegu** [comment]
**summary**

- add `is_rs_peer` indicator using icon specified in https://github.com/peeringdb/peeringdb/issues/727#issuecomment-657102289 to `Peers at this Exchange Point` listing on the ix view

**Comment by lukastribus** [comment]
This is terrible, it makes it seem like RS peering is "good" and not peering with the RS is "bad".

PeeringDB should neutrally document facts, not engage in marketing of IX features or peering politics.

**Comment by lukastribus** [comment]
The checkbox on the network page that is ticket/unticked uses the same colors then the rest of peeringdb. It is also clear that is a Yes or No thing. Instead the new icon is extremely colorful, and it is also absent for networks that don't peer with the RS.

This is bad UI and transmits good/bad messages as opposed to document a boolean, which is what we ought to do.

**Comment by lukastribus** [comment]
Had a call with @arnoldnipper, we talked about different proposals and we agreed on the following:

- adjust the colors of the icon so that it matches with the existing UI
- move the icon to the policy column, as the RS peer is indeed a policy decision of the AS so it makes sense to have it there

Using a checkbox would require renaming the column ("RS/Policy" or something) and that would mean it no longer matches the data model/API, which is also to be avoided.

So the 2 changes proposed above is a good compromise we both agreed on.


Any feedback would be much appreciated.


Thanks

**Comment by arnoldnipper** [comment]
> So the 2 changes proposed above is a good compromise we both agreed on.

+1

**Comment by grizz** [comment]
It's too late, this is being deployed shortly.

@lukastribus @arnoldnipper please make another issue and we can address that. Thank you.
