### ISSUE TITLE
When attempting to add an IX to an ASN's profile, the IX will not be an available option if the IX has not added the IP information for that exchange.

### ISSUE THREAD

**Issue by The-chris-P** [peeringdb/peeringdb#73]
When attempting to add an exchange to the "Public Peering Exchange Points" of our profile, the exchange would not show up in the "Exchange" search box since the exchange did not fill in the IP addressing information on their profile for that exchange. I can give specifics if needed. Grizz looked into this and asked me to open this issue.

**Comment by arnoldnipper** [comment]
Afaik this is a feature, not a bug. We want to do sanity checks. And as long as the IP info is not there, we can't do.

**Comment by grizz** [comment]
There's still a lot of IXs that don't have correct prefix information, we either need to enter the info or change this. Former is probably better, although a bit more work.

Should probably have a monthly report that runs as well.

**Comment by arnoldnipper** [comment]
I would consider it a feature not a bug. If the ixpfx is missing how do you check that the address entered is valid?

**Comment by grizz** [comment]
@arnoldnipper I agree that's how it should be, but in that case we need to go through the IX's without prefix info and enter it, task for the AC?

**Comment by eloos** [comment]
I agree that this is a feature and not a bug, @arnoldnipper can you confirm that the AC will look into this?
@grizz can we then make the deliverable of this issue such a report? (both on-demand via interface and email, or how does it generally work on the admin-com side?

**Comment by grizz** [comment]
To be clear, if it stops networks from entering legit information, it's a bug

**Comment by arnoldnipper** [comment]
How do we check that the networks enter legit information if we don't have the IP range? We already have enough bullsh*t in PeeringDB. And of course AC will lokk after it.

**Comment by grizz** [comment]
Per #8 AC will add prefix info for all IXPs, and we'll validate against that, which will fix this.
