### ISSUE TITLE
English shows up twice on beta as a language choice in the profile dropdown

### ISSUE THREAD

**Issue by grizz** [peeringdb/peeringdb#733]
From #714

**Comment by arnoldnipper** [comment]
+1, @peeringdb/pc

**Comment by gordon-shumway-net** [comment]
Could this maybe have something to do with the situation, that United States English is available for translation on translate.peeringdb.com?
So you could choose between British and US English?

What I think is also confusing and maybe even more, is that Spanish appears two times on Beta but just once on Production.

**Comment by grizz** [comment]
We don't have British English at all, or two Spanish. I thought this was going to be a quick PR fix, but I can't see what's wrong with it after a little poking.

+1 from me
@peeringdb/pc can we one more +1?

**Comment by shane-kerr** [comment]
+1

**Comment by gordon-shumway-net** [comment]
> We don't have British English at all, or two Spanish. I thought this was going to be a quick PR fix, but I can't see what's wrong with it after a little poking.

Okay, it's not British, but somehow there is an English US in addition to the source language available for translation.
https://translate.peeringdb.com/languages/

**Comment by grizz** [comment]
This is now fixed, possibly from #1227
