### ISSUE TITLE
Restrict email domains for organizations 

### ISSUE THREAD

**Issue by mcmanuss8** [peeringdb/peeringdb#737]
(Relates to #736) 

If #736 is done, some organizations will want to ensure that only corporate email addresses are used for peeringdb accounts. This way, the behaviors described in #736 will (eventually) prevent former staff from having access to modify peeringdb records, as they will no longer have access to their old email address, even if they do still have access to their peeringdb account.

To support this we should:

a) Add an optional checkbox called "Only allow users with emails in these domains:"
b) If the checkbox is checked, display a 1:M association where admins can add domains in the format:

@isp.net
@us.isp.net
etc

(All values must start with @)

c) If the checkbox is checked, whenever a user is associated with an organization, check that their email address matches the whitelist associated with the organization. If it's not, don't allow the association, and provide some helptext to let the user know why.

**Comment by ynbrthr** [comment]
I like that, but how do we go about for folks having roles with multiple orgs?

**Comment by mcmanuss8** [comment]
I think if the org wants that strict control, the user will have to make multiple peeringdb accounts.
Not ideal, but for orgs who wants that, I don't see a better solution that isn't...awkward

**Comment by arnoldnipper** [comment]
> I think if the org wants that strict control, the user will have to make multiple peeringdb accounts.
> Not ideal, but for orgs who wants that, I don't see a better solution that isn't...awkward

what about also allowing full email addresses, e.g. 

arnold@nipper.de
@de-cix.net

**Comment by arnoldnipper** [comment]
> what about also allowing full email addresses, e.g.
> 
> [arnold@nipper.de](mailto:arnold@nipper.de)
> @de-cix.net

or even more complex rules like

+ arnold@nipper.de
- @not_allowed.test.com
- certain_user@test.com
+ @test.com

**Comment by arnoldnipper** [comment]
+1

**Comment by mcmanuss8** [comment]
> > what about also allowing full email addresses, e.g.
> > [arnold@nipper.de](mailto:arnold@nipper.de)
> > @de-cix.net

Feels like that would just be the same as deciding if an individual user could be associated to the org or not. Not sure individual email addresses add value there.

> or even more complex rules like
> 
> ```
> + arnold@nipper.de
> - @not_allowed.test.com
> - certain_user@test.com
> + @test.com
> ```

minuses for a domain could make sense but only if we were going to allow wildcards. So like:

+ @*.isp.net
- @abc.isp.net

While the wildcard is implicit before the @, it's not implicit after the @ in my original proposal. I'm ok supporting a more complicated syntax, but I don't know if it'll add a lot of value. IMO we should try the simple version (list of individual domains) and revisit if, after getting some usage, we have users who are clamoring for a more complicated implementation

**Comment by shane-kerr** [comment]
+1

This is for the general suggestion. I have no strong feelings over allowing individual addresses, negative matches, or any specific approach.

**Comment by as44980** [comment]
> some organizations will want to ensure that only corporate email addresses are used for peeringdb accounts.

This would be very useful and appreciated by some orgs, dare I risk going one step too far by suggestion a further option to automatically approve account association requests for emails which match whatever means of specifying domains etc is agreed? 

> I think if the org wants that strict control, the user will have to make multiple peeringdb accounts.
> Not ideal, but for orgs who wants that, I don't see a better solution that isn't...awkward

This seems like a reasonable balance, with it being opt-in then its for the org admins to decide..


> Feels like that would just be the same as deciding if an individual user could be associated to the org or not. Not sure individual email addresses add value there.

I guess the challenge is that if there was a need for an exception to the general policy of requiring corporate emails for a specific individual then a domain only based solution would work for individuals with their own domain such as arnold@nipper.de, but not for arnold.nipper@popular-webmail.example.com..

>  IMO we should try the simple version (list of individual domains) and revisit if, after getting some usage, we have users who are clamoring for a more complicated implementation

+1, my gut feeling would be the orgs most likely to utilize such a feature would be less likely to have exceptions than orgs where multi-hat-wearers are the norm.

>  If the checkbox is checked, whenever a user is associated with an organization, check that their email address matches the whitelist associated with the organization. If it's not, don't allow the association, and provide some helptext to let the user know why.

Is this something which is envisaged to apply exclusively for new account association requests or should we consider existing associations?

For example should submitting an updated org object with this option enabled (having previously not been enabled), is there any value or need to highlight if any existing users do not comply with this newly enforced policy? 


Finally should we consider requiring a minimum of at least one entry is the domain/address regexp list in order to enable the feature, or would it be considered a feature that could be used should the org admin decide they do not wish to permit any new association requests? :)

**Comment by arnoldnipper** [comment]
> Is this something which is envisaged to apply exclusively for new account association requests or should we consider existing associations?

We shouldn't consider applying this to existing affiliations as all but the first have been approved **explicitly**. If you don't want them anymore, you are still able to remove them. But if you want to keep them such a feature would dis-affiliate those accounts.

**Comment by grizz** [comment]
This needs some implementation details @peeringdb/pc

**Comment by mcmanuss8** [comment]
@grizz - what questions do we have outstanding on the implementation discussion?

**Comment by grizz** [comment]
@mcmanuss8 Which of the many implementation ideas is it? There's everything from a simple list of domains to let's make a new  a new specification language. :)

I'm -1 one for all of them, a company can do that quite easily on their own before approving access without us adding logic for it. In fact, after #736 I think it would be easier for an admin to look at the list of users and reach out to tell them something like "hey, you're approved with a personal email, please register under your company email and I'll remove the old one when I approve the new one"

I was waiting for the dust to settle to see what the final proposal was before voting, and it's now consensus reached.

**Comment by grizz** [comment]
To expand, if there's a simple list of domains that would make admins' jobs easier, I can see doing that, but what about all the current ones that don't match? Need some sort of UI to highlight it? Send warnings? Any sort of automatic removal could result in an operational issue, etc.

**Comment by arnoldnipper** [comment]
@grizz, this is exactly one of the issues I would move to 1a. I.e. let's keep in mind, but it has low, low, low prio.

**Comment by mcmanuss8** [comment]
@grizz Let's stick with the simple list of domains. As I stated in a previous comment:
> IMO we should try the simple version (list of individual domains) and revisit if, after getting some usage, we have users who are clamoring for a more complicated implementation

As for an organization's ability to add people - yes, in theory each org admin  can do this, but as I've seen from a similar implementation at $day_job, they often don't pay close enough attention (often they just look at the name, see someone they know and hit accept). This led to disgruntled employees having access to resources far longer than they should have, which is why we added a similar feature. 

In terms of rollout, if you added such a domain list on an existing account, we'd warn you that there were users who didn't match the list of domains, but leave them fo the org admin to decide what to do with them (remove them from the org or leave them for now).

**Comment by grizz** [comment]
@peeringdb/pc Needs to have some discussion on how this fits together with #736 #738

**Comment by leovegoda** [comment]
@peeringdb/pc should we go with just a list of domains for the initial implementation? If so, should we implement #736 at the same time?

**Comment by vegu** [comment]
**Summary**

1. Add organization based switch for “Only allow users with emails in these domains” to organization user affiliation management UX
	1. If checked allow organizations to manage a list of domains to filter email addresses against in the format of “@zyx.com”
	1. If checked, block users from sending affiliation requests if their email does not match any of the domains specified in the filters.
1. In the case where restriction is enabled while there are already users affiliated whose email do not match the filters, the organization management tool for affiliations needs to highlight these users in the user listing, probably through special color highlight for the email address and a help text on mouse over.
1. If a user has multiple email addresses (#738) it is sufficient for one of their email addresses to match the restricted domain filters.
