### ISSUE TITLE
Allow multiple email addresses per user

### ISSUE THREAD

**Issue by job** [peeringdb/peeringdb#738]
Related to https://github.com/peeringdb/peeringdb/issues/737

If we allow a single user to specify multiple addresses (and select one primary address for communication) we can easily deal with the combination of users that help multiple orgs and orgs that want to restrict which users can associate.

This idea came from Gaurab Raj Upadhaya

**Comment by ynbrthr** [comment]
+1

**Comment by arnoldnipper** [comment]
this is 100% contradicting #267

**Comment by mcmanuss8** [comment]
I read #267 as "Ensure an email address is associated no more than one user", not "Ensure that each user can only have one email address"

I think this can coexist with #267. To summarize the proposed rules then:

* A user can have one or more email addresses
* A user should have exactly one email address selected as "primary" for communication or other purposes
* An email address can only be associated with exactly one user

**Comment by arnoldnipper** [comment]
+1

**Comment by arnoldnipper** [comment]
> Related to #737
> 
> If we allow a single user to specify multiple addresses (and select one primary address for communication) we can easily deal with the combination of users that help multiple orgs and orgs that want to restrict which users can associate.
> 
> This idea came from Gaurab Raj Upadhaya

Are there other use cases, @job? If we allow fine-grained filters, additional email addresses wouldn't be needed

**Comment by as44980** [comment]
> If we allow a single user to specify multiple addresses (and select one primary address for communication) we can easily deal with the combination of users that help multiple orgs and orgs that want to restrict which users can associate.

Firstly having a designated backup/fallback email for account recovery could be worth considering, and perhaps be non-contentious if used solely for this purpose and not searchable in any way etc..

However while I expect the use case where multiple orgs may wish to associate a single user with their account, and thus be able to grant permissions against objects under that org, is fairly common..

Is there a significant demand for a single user to have multiple emails which could all potentially be used to associate this user with an org?

And if so would it be a permanent association with the user object, or would this relationship be revoked if the user removes the email which was used to create an association with an org?  

;)

**Comment by arnoldnipper** [comment]
With fine-grained access-lists in #737, I don't see any need for this issue anymore.

**Comment by arnoldnipper** [comment]
**Summary**

* A user can have one or more email addresses
* A user should have exactly one email address selected as "primary" for communication or other purposes
* An email address can only be associated with exactly one user

**Comment by vegu** [comment]
**Summary**

1. A user can have one or more email addresses
1. A user should have exactly one email address selected as "primary" for communication or other purposes
	1. A user always needs to have a primary email address except when the user is no longer active (closed account)
1. An email address can only be associated with exactly one user
	1. Should have a unique constraint in the database schema
	1. Clean up of existing problems:
		1. There are currently 22 duplicate email addresses in the database - Needs to be handled through #267 first
		1. Closing a user account currently blanks their primary email, in order to work with any unique constraint that needs to be nulled instead.
1. While an email address is marked as primary it cannot be removed and the user will be asked to change primary status to one of their other email addresses when attempting to remove it.
1. If a user closes their account all of their emails should be removed.
