### ISSUE TITLE
RDAP Lookup Error when querying for an Entity - GRUK-RIPE vs gruk-RIPE

### ISSUE THREAD

**Issue by netravnen** [peeringdb/peeringdb#739]
Summary:
- Entity handle is returned in full uppercase when querying the Autnum object via RDAP regardless of if the handle is a mix of upper- and lowercase characters.
- RDAP query is case sensitive when querying for an Entity object (if **not** using `-t entity-search-by-handle $Handle`).
- This case sensitivity is only applicable for RDAP queries and does not apply to RIPE web-ui and WHOIS queries.

---

Suggestion:
- Introduce an RDAP Entity query fallback if 1st query fails. E.g.
  1. `$ rdap -s $Server $HANDLE` 404 Not found
  2. `$ rdap -s $Server -t entity-search-by-handle $HANDLE` 200 OK
- Or always use `-t entity-search-by-handle` when querying for Entity objects.

---

https://peeringdb.deskpro.com/agent/#app.tickets,inbox:all,t.o:43605,vis:5

Error caused by case [ upper | lower ] sensitivity.

```
$ ./go/bin/rdap -s rdap.db.ripe.net AS15599`  
<snip>
Autnum:
  Handle: AS15599
  Name: AVANTEL-NEFTEUGANSK-ASN
  Type: DIRECT ALLOCATION
  Conformance: rdap_level_0
  Port43: whois.ripe.net
  Notice:
    Title: Filtered
    Description: This output has been filtered.
  Notice:
    Title: Source
    Description: Objects returned came from source
    Description: RIPE
  Notice:
    Title: Terms and Conditions
    Description: This is the RIPE Database query service. The objects are in RDAP format.
    Link: http://www.ripe.net/db/support/db-terms-conditions.pdf
  Link: https://rdap.db.ripe.net/autnum/15599
  Link: http://www.ripe.net/data-tools/support/documentation/terms
  Event:
    Action: last changed
    Date: 2020-06-04T17:18:47Z
  Entity:
    Handle: GRUK-RIPE
    Role: technical
    Role: administrative
</snip>
```

- `$ ./go/bin/rdap -s rdap.db.ripe.net GRUK-RIPE`
  `# Error: RDAP server returned 404, object does not exist.`
  404 Not Found
- `$ ./go/bin/rdap -s rdap.db.ripe.net -t entity-search GRUK-RIPE`
  `# Error: RDAP server returned 404, object does not exist.`
  404 Not Found
- `$ ./go/bin/rdap -s rdap.db.ripe.net -t entity-search-by-handle GRUK-RIPE`
  200 OK
- `$ ./go/bin/rdap -s rdap.db.ripe.net gruk-RIPE`
  200 OK

The discrepancy is not seen when using the web-ui of the database. Due to no case sensitivity being applied to the search query.

- [apps.db.ripe.net/db-web-ui/lookup?source=ripe&key=**GRUK-RIPE**&type=person](https://apps.db.ripe.net/db-web-ui/lookup?source=ripe&key=GRUK-RIPE&type=person)
  200 OK
- [apps.db.ripe.net/db-web-ui/lookup?source=ripe&key=**gruk-RIPE**&type=person](https://apps.db.ripe.net/db-web-ui/lookup?source=ripe&key=gruk-RIPE&type=person)
  200 OK

Neither when using regular whois

- `$ whois -h whois.ripe.net GRUK-RIPE | grep -v '^$' | grep -v '^%'`
  200 OK
- `$ whois -h whois.ripe.net gruk-RIPE | grep -v '^$' | grep -v '^%'`
  200 OK

**Comment by arnoldnipper** [comment]
**Summary**

By default, RDAP query is case sensitive when querying for an Entity object. Suggestion is to make the query case insensitive by adding `-t entity-search-by-handle`.

@peeringdb/pc please +1 as this only affects @peeringdb/ac and their interface and does not have any implications on production.

**Comment by ynbrthr** [comment]
+1

**Comment by shane-kerr** [comment]
+1

**Comment by grizz** [comment]
Should be done along with #494

**Comment by netravnen** [comment]
_*update: *_RIPE NCC has notified us they changed something on their side, so the query below now return the expected data output, code *200 OK*

`$ ~/go/bin/rdap --server=https://rdap.db.ripe.net GRUK-RIPE`
200 OK

AdminCom, ProductCom, and 20c support have been notified via E-mail, quitting the RIPE NCC notification message.

**Comment by grizz** [comment]
This was fixed by RIPE.
