### ISSUE TITLE
Remove user constrains for AC

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/peeringdb#741]
In an effort to delegate as much as possible to the appropriate teams I propose to remove cosntrains put on users for AC. This e.g. includes setting smaller masks (see screenshot attached).

@peeringdb/ac what other items can you think of?

@peeringdb/pc please make up your mind.
![Add_ix_lan_prefix_PeeringDB](https://user-images.githubusercontent.com/16888757/84159911-e3e7d500-aa6d-11ea-8ba3-e52d26593343.png)

**Comment by funkestefan** [comment]
Nothing from the top of my head, but will keep it in mind.

**Comment by funkestefan** [comment]
I wanted to change the org of a network and got this. (Ipaddr6 was empty) I had to fill in a valid address before I could change the org and remove it later.

![Screenshot from 2020-06-15 19-55-55](https://user-images.githubusercontent.com/20709293/84690345-a6d68380-af42-11ea-8df9-f0de75909620.png)

**Comment by arnoldnipper** [comment]
@funkestefan, this is #644  ... to get rid of this error, you have to delete the objects again by clicking on the little cross left to the entry.

**Comment by funkestefan** [comment]
The cross would delete the entries. I didn't want to delete the network ix lan entries.
#644 is the same bug, waiting for release.

**Comment by mcmanuss8** [comment]
To clarify - is the ask here to not do IP validation for AC members? To allow them proceed with certain operations despite validation errors?

**Comment by arnoldnipper** [comment]
@mcmanuss8, the ask is **not** to disable IP validation for AC members, but to allow certain operations (like specifying a shorter mask for an ixpfx) w/o having to go to the vendor (aka @20c). IOW: AC should be enabled to do as much as possible. And judging whether an IX needs a different mask clearly is something AC has to decide and not the vendor.

**Comment by grizz** [comment]
What is the use case for setting a shorter mask in this case?

**Comment by arnoldnipper** [comment]
> What is the use case for setting a shorter mask in this case?

IIX Israel **is** using this prefix :) They are an L3 IX

**Comment by arnoldnipper** [comment]
> edit: I'm all for letting the AC do everything they can, but there might be a better solution here.

@peeringdb/pc and esp. @grizz, please discuss

**Comment by grizz** [comment]
I guess I'm fine with removing the limits for the AC, although I'm having a hard time getting behind this use case. :)

**Comment by arnoldnipper** [comment]
@pc, please review and ideally +1 as this is @ac related only

**Comment by shane-kerr** [comment]
+1

If the AC feels it's useful, I guess we should give them the tool!

**Comment by vegu** [comment]
@arnoldnipper would this apply to all of the following checks then:

```
# maximum value to allow in network.info_prefixes4
set_option("DATA_QUALITY_MAX_PREFIX_V4_LIMIT", 1000000)

# maximum value to allow in network.info_prefixes6
set_option("DATA_QUALITY_MAX_PREFIX_V6_LIMIT", 100000)

# minimum value to allow for prefix length on a v4 prefix
set_option("DATA_QUALITY_MIN_PREFIXLEN_V4", 18)

# maximum value to allow for prefix length on a v4 prefix
set_option("DATA_QUALITY_MAX_PREFIXLEN_V4", 28)

# minimum value to allow for prefix length on a v6 prefix
set_option("DATA_QUALITY_MIN_PREFIXLEN_V6", 64)

# maximum value to allow for prefix length on a v6 prefix
set_option("DATA_QUALITY_MAX_PREFIXLEN_V6", 116)

# maximum value to allow for irr set hierarchy depth
set_option("DATA_QUALITY_MAX_IRR_DEPTH", 3)

# minimum value to allow for speed on an netixlan (currently 100Mbit)
set_option("DATA_QUALITY_MIN_SPEED", 100)

# maximum value to allow for speed on an netixlan (currently 1Tbit)
set_option("DATA_QUALITY_MAX_SPEED", 1000000)
```

If not please cherry-pick the ones you want

**Comment by arnoldnipper** [comment]
@vegu, yes, please.  AC will use this new power with care.
