### ISSUE TITLE
ARIN has split into ARIN + ARIN-NONAUTH

### ISSUE THREAD

**Issue by grizz** [peeringdb/peeringdb#743]

**Comment by arnoldnipper** [comment]
What is this for, @grizz?

**Comment by grizz** [comment]
To track and include in release notes @job's PR for the new ARIN IRR source.

**Comment by arnoldnipper** [comment]
> To track and include in release notes @job's PR for the new ARIN IRR source.

ARIN-NONAUTH is not yet recognised as an IRR source.

**Comment by grizz** [comment]
Good catch, it's the first source with a `-` and a regex bug -- opened #921
