### ISSUE TITLE
Add “Route Collector” network type

### ISSUE THREAD

**Issue by job** [peeringdb/peeringdb#745]
Similar to how the “Route Server” network type exists, we can introduce a “Route Collector” network type to ease network automation.

(Placeholder ticket following from the ‘route server data model’ call with Arnold, Matt, Job, McManus, and Yan)

**Comment by mcmanuss8** [comment]
+1 Let's do this. There are at least 4 "Route Server" network objects that say "collector' in their names. This would reduce some ambiguity in their roles

**Comment by arnoldnipper** [comment]
+1

**Comment by ynbrthr** [comment]
> Similar to how the “Route Server” network type exists, we can introduce a “Route Collector” network type to ease network automation.
> 
> (Placeholder ticket following from the ‘route server data model’ call with Arnold, Matt, Job, McManus)

not that it matters much, but i was there too :)

**Comment by arnoldnipper** [comment]
It matters :)

**Comment by grizz** [comment]
+1

> not that it matters much, but i was there too :)

I was chuckling to myself about that on the call, he was talking to you while typing that and didn't list you. :)

**Comment by grizz** [comment]
I don't think "requires notice" is needed, it's just adding another choice so it couldn't break any existing code.

**Comment by as44980** [comment]
Out of interest, is anyone aware of any net objects which self-identify as route collectors which also undertake Private Peering?

If not, should setting the info_type to Route Collector and possibly even Route Server remove any "Private Peering Facilities" associated with this net object to reduce confusion? :)

**Comment by arnoldnipper** [comment]
> If not, should setting the info_type to Route Collector and possibly even Route Server remove any "Private Peering Facilities" associated with this net object to reduce confusion? :)

Imho "Private Peering Facilities" is really misleading. For me, this simply means that this is a facility where a `net` is available for interconnection. For what reason ever. And both, RC and RS are available for interconnection somewhere.

**Comment by as44980** [comment]
> Imho "Private Peering Facilities" is really misleading. For me, this simply means that this is a facility where a `net` is available for interconnection. For what reason ever. And both, RC and RS are available for interconnection somewhere.

I certainly agree its ambiguous, my interpretation is that when present on a net record this indicates physical locations where the network is able to accommodate private peering via dedicated physical (aka private) interconnections, rather than say just a list of facilities where the network is available for interconnection via a layer2 fabric such as an IXP.

If the consensus is that at least for net objects this data represents _a facility where a net is available for interconnection_, but not necessarily able to accommodate what is commonly understood by Private Peering, then perhaps renaming this from "Private Peering Facilities" to "Interconnection Facilities" would remove this ambiguity?

And if not, would it make sense to clarify that network should only list facilities where they are able to accept dedicated, physical interconnection without requiring the potential peer to also be present on some IXP? :)

**Comment by ynbrthr** [comment]
> > If not, should setting the info_type to Route Collector and possibly even Route Server remove any "Private Peering Facilities" associated with this net object to reduce confusion? :)
> 
> Imho "Private Peering Facilities" is really misleading. For me, this simply means that this is a facility where a `net` is available for interconnection. For what reason ever. And both, RC and RS are available for interconnection somewhere.

Yes, but, at least for RSes, they're available in the context of an IX only. They are in a facility alright, but you can't interconnect with an RS if you're not part of the IX. That's probably true for IX-provided RCs as well.

**Comment by ynbrthr** [comment]
> > Imho "Private Peering Facilities" is really misleading. For me, this simply means that this is a facility where a `net` is available for interconnection. For what reason ever. And both, RC and RS are available for interconnection somewhere.
> 
> I certainly agree its ambiguous, my interpretation is that when present on a net record this indicates physical locations where the network is able to accommodate private peering via dedicated physical (aka private) interconnections, rather than say just a list of facilities where the network is available for interconnection via a layer2 fabric such as an IXP.
> 
> If the consensus is that at least for net objects this data represents _a facility where a net is available for interconnection_, but not necessarily able to accommodate what is commonly understood by Private Peering, then perhaps renaming this from "Private Peering Facilities" to "Interconnection Facilities" would remove this ambiguity?

I would agree. I know of a number of networks listing (private peering) facilities where one can buy transit from them, but not necessarily peer. Conversely, some networks looking for transit in some markets use peeringDB to see who's present where. Bottom line, Interconnection facilites would be less misleading than the current private peering facilities wording.

**Comment by arnoldnipper** [comment]
> If the consensus is that at least for net objects this data represents _a facility where a net is available for interconnection_, but not necessarily able to accommodate what is commonly understood by Private Peering, then perhaps renaming this from "Private Peering Facilities" to "Interconnection Facilities" would remove this ambiguity?

Does it make sense to get into a debate on what _interconnection_ really means? It could be a direct physical connection, a lambda, a vpni, across an ix or via whatever and for whatever reason. Hence I fully support your suggestion of renaming to  **"Interconnection Facilities"**

**Comment by job** [comment]
What about **Physical Interconnection Facilities** ?

**Comment by ynbrthr** [comment]
> What about **Physical Interconnection Facilities** ?

a facility, at least as far as pdb is concerned, is a physical location, your suggestion sounds redundant, does it not?

**Comment by job** [comment]
On Fri, Jun 19, 2020 at 04:22:57PM -0700, Yan Berthier wrote:
> > What about **Physical Interconnection Facilities** ?
> 
> a facility, at least as far as pdb is concerned, is a physical
> location, your suggestion sounds redundant, does it not?

But imagine newcomers, who are not yet familiar with peeringdb. New
users probably need more guidance on what what is.

The existing peeringdb users will indeed understand that if we rename
'private peering facilities' to 'facilities' it means the same.

What if in the future there will be some kind of 'virtual
interconnection facility' that peeringdb has a role in documenting for
operators to use.

I think there will be value in being specific, at the small cost that
someone at times thinks it is redundant. but that will briefly pass :)

**Comment by grizz** [comment]
I agree completely that the "Private peering" part should be replaced, and at the risk of being too pedantic, I like `Interconnection Facilities` better than `Physical Interconnection Facilities` -- a facility is a physical location in English, not just in PeeringDB. And if there's any doubt, seeing a list of data centers with physical addresses under the header should explain to anyone. :)

**Comment by job** [comment]
Just using the word "Facility" would also work for me. Good points Matt

**Comment by grizz** [comment]
**Summary**
Add “Route Collector” network type.
