### ISSUE TITLE
Clean up info_type if name contains "Route Servers" or "Route Collector"

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/peeringdb#747]
[ has to wait for #745 being implemented ]

Generally, the field `info_type` is self-declared by the networks. However, if the name suggest a certain function (here RS or RC) `name` and `info_type` should match.

```
curl -sG https://peeringdb.com/api/net --data-urlencode name__contains="Route Server" --data-urlencode fields=info_type | jq -r '.data[].info_type' | sort | uniq -c
      2
      9 Non-Profit
     22 Not Disclosed
      7 NSP
    226 Route Server

curl -sG https://peeringdb.com/api/net --data-urlencode name__contains="Route Collector" --data-urlencode fields=info_type | jq -r '.data[].info_type' | sort | uniq -c
      1 Non-Profit
      3 Not Disclosed
      4 Route Server
```
Having `info_type` set properly is needed to automagically set the BGP session parameters properly as well.

@peeringdb/pc please vote. And @peeringdb/ac please keep an eye on it.

**Comment by ynbrthr** [comment]
+1

**Comment by grizz** [comment]
+1

**Comment by alexfguimaraes** [comment]
+1

**Comment by mcmanuss8** [comment]
What action should we do though? Fix it? Create a task for AC to ping the owner org?

**Comment by arnoldnipper** [comment]
> What action should we do though? Fix it? Create a task for AC to ping the owner org?

Yes, this is something we want @peeringdb/ac to do. They have their own queue, but this is only used for on- and de-boarding.

**Comment by DarwinCosta** [comment]
> On 17 Jun 2020, at 21:31, Arnold Nipper <notifications@github.com> wrote:
> 
> ﻿
> What action should we do though? Fix it? Create a task for AC to ping the owner org?
> 
I’m ok with both suggestions, but I would suggest to: Create a task for AC to ping org owners.

**Comment by arnoldnipper** [comment]
- [ ] @peeringdb/ac to ping the owner org

**Comment by Yo-Robinson** [comment]
+1
