### ISSUE TITLE
PeeringDB website has a poor choice of line-breaks for IPv6 addresses.

### ISSUE THREAD

**Issue by mahtin** [peeringdb/peeringdb#748]
I believe (in order to improve readability and reduce confusion) IPv6 addresses should have a `no wrap` style option added such that their numeric values aren't broken across lines.

I fully understand that we could discuss UI and web layout ad-infinitum; however, I hope we call agree that IPv6 addresses (and IPv4 for that matter) should not be broken up when displayed online.

<img width="579" alt="image" src="https://user-images.githubusercontent.com/4521085/84929763-253b3e80-b085-11ea-91b7-225f2aa086ed.png">

- image grabbed from https://www.peeringdb.com/asn/60772 page displayed on a MacBook via Chrome browser.

**Comment by arnoldnipper** [comment]
makes perfect sense and should be dealt with while working on #665 and #543 and #397 (not directly related, but ...) ... hence a **big** +1

**Comment by ynbrthr** [comment]
+1

**Comment by job** [comment]
+1

**Comment by arnoldnipper** [comment]
**Summary**

To improve readability IP{4,6} addresses should have `no wrap` style option added such that their numeric values aren't broken across lines. Issues #543 and #665 also deal with this matter

**Comment by shane-kerr** [comment]
+1

FWIW, it looks fine here with Firefox on an a Ubuntu laptop. @arnoldnipper's suggestion makes complete sense.

![image](https://user-images.githubusercontent.com/1943584/85030478-c9081580-b17d-11ea-85d9-488a4f054f9f.png)
