### ISSUE TITLE
Mismatch between LAN and IP addresses for Netnod (and perhaps other IXP as well)

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/peeringdb#75]
when migrating from PDB 1.0 to PDB 2.0 all IP addresses were assigned to only one LAN. See https://ubersmith.peeringdb.com/admin/supportmgr/ticket_view.php?ticket=15481

![20161014 peeringdb 00](https://cloud.githubusercontent.com/assets/16888757/19397811/b3f3806e-9249-11e6-9e0d-fe0812a20f60.png)

**Comment by grizz** [comment]
This should be fixed by removing the whole IX LAN concept

**Comment by arnoldnipper** [comment]
Don't get ... do you want to make them a separate IXP each? Imho you then lose precious information. My understanding is that IX Lans from the same IXP are on the same physical hardware (just different vlans like main, regular 1500-byte peering LAN, jumbo LAN, muliticast), whereas two IXP ae on different hardware

**Comment by grizz** [comment]
> Imho you then lose precious information.
We wouldn't lose any information from what I can tell, what are you thinking of?

> My understanding is that IX Lans from the same IXP are on the same physical hardware
Not necessarily, LINX for example. Either way, there are very few cases where it happens and it drastically decreases both API intuitiveness and UI display simplicity, which is what this bug is about.

There's a mailing list thread on this somewhere.

**Comment by arnoldnipper** [comment]
You are losing the information that a LAN is on the same physical infrastructure. Let's have an example. Currently DE-CIX Frankfurt (https://peeringdb.com/ix/31) has two IX lans on the same physical infrastructure. If you remove the concept of IX lans these two would pop up as two single IXP. So the information that it is the same physical infrastructire is lost.

LINX really is two IXP (LINX LON1 and LINX LON2). However LINX LON1 has two IX lans on it ;-)

**Comment by grizz** [comment]
As far as I know, it's never been formally defined like that, but it makes sense. With that logic, it would still be better to just define a relationship stating that separately and still get rid of the nested IX LAN schema.

**Comment by grizz** [comment]
@peeringdb/pc This hasn't been touched in 2 years, referenced in #21 -- let's decide

**Comment by mcmanuss8** [comment]
Is this a noop if we kill ix lans in #21?

**Comment by grizz** [comment]
Almost, we still might want to define a way for IXes to disclose that a LAN is on the same hardware

**Comment by arnoldnipper** [comment]
> Almost, we still might want to define a way for IXes to disclose that a LAN is on the same hardware

Isn't the notes field sufficient to do so?

**Comment by mcmanuss8** [comment]
I'd say if there's no programmatic use case for needing to know if it's on the same hardware, we should just rely on notes. If there's a valid use case (like "I won't automatically turn up new peers here if it's not on the same HW"), then we should get a dedicated field for it.

**Comment by grizz** [comment]
I agree notes is good for now, we can wait for a legit use case for adding a field for that.

**Comment by mcmanuss8** [comment]
Let's close for now then in favor of #21. Can re-open or make a new ticket when there's a legit use case
