### ISSUE TITLE
IRR as-set/rs-set validation broken

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/peeringdb#750]
[ related to #151 ]

Instead of giving a proper error message as the as-set is not compliant ("." instead of "::") the systems borks with a 500. Would it be possible to bug fix this with the next release already? What do you think, @peeringdb/pc ?

![20200623 PeeringDB 00](https://user-images.githubusercontent.com/16888757/85460946-13d1c500-b5a4-11ea-92eb-2f6bbdbde65f.png)

**Comment by job** [comment]
Yes, a nicer error would be useful!

**Comment by grizz** [comment]
How is this consensus finalized?

+1 from me, so consensus is now reached. :)

**Comment by arnoldnipper** [comment]
> How is this consensus finalized?

Obvious **bug**?

**Comment by grizz** [comment]
Oh, wasn't aware that short circuited, sorry.

**Comment by vegu** [comment]
I believe this is the same as #712 - fix is currently rolled out to beta

**Comment by grizz** [comment]
**Release Notes**
Improve error messages for invalid IRR objects.
