### ISSUE TITLE
sign-in / translate.peeringdb.com / invalid_request

### ISSUE THREAD

**Issue by gordon-shumway-net** [peeringdb/peeringdb#756]
Hey together,

I just recognized today that I'm not able anymore to login at Weblate on translate.peeringdb.com.
If I click on "Sign In" in Weblate it's forwarding to peeringdb.com as usual, if I login on peeringdb.com then, there an error is coming.
**Error: invalid_request
Invalid client_id parameter value.**

It's also not working in another Browser or if I'm already logged in at peeringdb.com.
Nothing changes.

Could that have something to do with the recent merges?
Or do I something wrong?

Gordon :)

**Comment by arnoldnipper** [comment]
> Could that have something to do with the recent merges?

What merges?

**Comment by arnoldnipper** [comment]
> Error: invalid_request
> Invalid client_id parameter value.

same here

**Comment by arnoldnipper** [comment]
@peeringdb/oc could you please have a look

**Comment by ccaputo** [comment]
@grizz, any idea what changed on the production site to break OAuth with the translations site?

**Comment by grizz** [comment]
@ccaputo No idea, looking into it now.

**Comment by grizz** [comment]
Fixed.

**Comment by gordon-shumway-net** [comment]
> > Could that have something to do with the recent merges?
> 
> What merges?

Hey Arnold :)

Maybe just something in the last pull requests which merged: https://github.com/peeringdb/peeringdb/pulls?q=is%3Apr+is%3Aclosed
Especially that, seems that there happened much: #751

**Comment by gordon-shumway-net** [comment]
> Fixed.

Great Grizz!
Thank you, it's working again! :)
