### ISSUE TITLE
Lightweight user notification mechanism

### ISSUE THREAD

**Issue by ynbrthr** [peeringdb/peeringdb#758]
As suggested by @arnoldnipper in #719, let's start with a lightweight implementation to notify logged-in users of impeding changes, while a more full-fledged solution is worked out:

E.g.: "What about simply having a bigger "News" button in the footer under the social media items which leads to https://docs.peeringdb.com/news. That would be simple to implement"

**Comment by arnoldnipper** [comment]
+1

**Comment by shane-kerr** [comment]
+1

**Comment by mcmanuss8** [comment]
+1

**Comment by vegu** [comment]
**Summary**

- add "News" button to the "Social Media" section in footer that points to https://docs.peeringdb.com/news
