### ISSUE TITLE
Describe the 'never-via-routeservers' flag

### ISSUE THREAD

**Issue by ynbrthr** [peeringdb/peeringdb#759]
During the implementation of #394, having a tooltip to describe what that flag is about was discussed, but never implemented: 

"On the frontend we should add a tooltip to the field which describes it (leveraging code in #228):
"Indicates if this network will announce its routes via route servers or not""

A FAQ entry could be added as well.

**Comment by arnoldnipper** [comment]
> A FAQ entry could be added as well.

See https://docs.peeringdb.com/faq/#technical

And +1

**Comment by shane-kerr** [comment]
+1

**Comment by arnoldnipper** [comment]
**Release note**

A tooltip to the 'never-via-routeservers' flag is added
