### ISSUE TITLE
[beta] IX-F Suggestions: Leaving the editor and returning to it via back button issues

### ISSUE THREAD

**Issue by vegu** [peeringdb/peeringdb#765]
>  https://beta.peeringdb.com/net/20 -> Review Suggestions -> ChIX ->
> Their PeeringDB entry -> back button and all net{ixlan,fac} are gone

Refresh fixes.

Issue appears to be that both exchange list and facility list filters receive values after going back.

**Comment by ccaputo** [comment]
Fix confirmed.
