### ISSUE TITLE
[beta] IX-F importer: all sent email should be kept in an internal table

### ISSUE THREAD

**Issue by ccaputo** [peeringdb/peeringdb#767]
For both beta and production, we should maintain a copy of all emails sent by the IX-F importer - headers and body - in an internal table.  This will help with diagnostics (following up on bounces, for example) and also to just make sure we are aware of the emails PeeringDB is sending out in an automated fashion, rather than being blind.

On beta, since emails aren't actually going out, this will enable the perception of what would have normally gone out, if in production.

**Comment by ynbrthr** [comment]
+1

**Comment by arnoldnipper** [comment]
+1

**Comment by ccaputo** [comment]
@peeringdb/pc to be clear, approval for this is ASAP needed in order to be able to actually properly test & verify the IX-F importer.  I consider this a blocker preventing the IX-F importer code from going to production.

**Comment by arnoldnipper** [comment]
@peeringdb/pc I have moved this to consensus reached already. Please butt in if you think this issues doesn't make sense!

**Comment by mcmanuss8** [comment]
+1

-Steve

**Comment by grizz** [comment]
Operational bug, finalizing.

**Comment by ccaputo** [comment]
Confirmed.
