### ISSUE TITLE
[beta] IX-F importer: "DeskPRO Tickets" table needs to be searchable

### ISSUE THREAD

**Issue by ccaputo** [peeringdb/peeringdb#768]
The "DeskPRO Tickets" table needs to be searchable.

**Comment by vegu** [comment]
@ccaputo subject search or both message and subject search?

**Comment by ccaputo** [comment]
> @ccaputo subject search or both message and subject search?

Regexp searchable for both please.  Same for https://github.com/peeringdb/peeringdb/issues/767.  Thanks.

**Comment by vegu** [comment]
In that case, looking at production there are 22000 ticket objects archived there. For sake of performance, should we introduce a max-age so we dont hoard them indefinitely? :)

 @peeringdb/ac is there any reason to keep deskpro tickets archived in /cp once they have been sent to deskpro?

**Comment by ccaputo** [comment]
> In that case, looking at production there are 22000 ticket objects archived there. For sake of performance, should we introduce a max-age so we dont hoard them indefinitely? :)

If the bodies make it too large, I'd be happy with just the subjects.  Main thing is as part of testing the ix-f importer, I want to be able to filter by ASN.

**Comment by mcmanuss8** [comment]
+1 on making it searchable. Ambivalent on regex or simple search

-Steve

**Comment by ynbrthr** [comment]
+1

**Comment by funkestefan** [comment]
I didn't even know we had all the deskpro tickets in /cp. Whats the purpose of all the redundant data?

**Comment by ccaputo** [comment]
> I didn't even know we had all the deskpro tickets in /cp. Whats the purpose of all the redundant data?

The IX-F importer beta testing does not create actual DeskPRO tickets.  Rather it puts them into a table in the /cp/ so that we can see the tickets that would have been created.  This is needed for testing/verifying/understanding how the new importer is working.

Not sure if this table would exist in production.  @vegu?

**Comment by funkestefan** [comment]
https://peeringdb.com/cp/peeringdb_server/deskproticket/?p=0 looks like we have it in production?!

**Comment by ccaputo** [comment]
> https://peeringdb.com/cp/peeringdb_server/deskproticket/?p=0 looks like we have it in production?!

Fair enough.  :-)  I imagine this is useful for debugging.

**Comment by arnoldnipper** [comment]
> @peeringdb/ac is there any reason to keep deskpro tickets archived in /cp once they have been sent to deskpro?

No ... afair we only introduced this queue because ticket got lost.

**Comment by vegu** [comment]
The table exists because tickets are not sent to DeskPRO immediately from the main web-server process. They are gathered and sent by separate job that runs regularly (every minute or so?)

This is helpful for several reasons:

1. It disconnects and deskpro api issues from the user request that spawns the ticket
2. The deskpro api might fail, and if it does we still have the ticket to resend it once that problem is fixed

It does also help with debugging.

So the table has purpose, and for debugging reasons it'd be nice to keep published tickets around for a couple days or so.

That said if we do a subject-only search i don't think we need to deal with this in the scope of this ticket. Worst case can always delete the old DeskPRO tickets in production by hand as well.

**Comment by ccaputo** [comment]
I think subject-only is fine.

**Comment by ccaputo** [comment]
@peeringdb/pc to be clear, approval for this is ASAP needed in order to be able to actually properly test & verify the IX-F importer.  I consider this a blocker preventing the IX-F importer code from going to production.  The current table is unwieldy from a test perspective, yet is need to track and verify things.

**Comment by arnoldnipper** [comment]
@peeringdb/pc I have moved this to consensus reached already. Please butt in if you think this issues doesn't make sense!

**Comment by grizz** [comment]
Operational bug, finalizing.

**Comment by ccaputo** [comment]
Fix confirmed.  @vegu, it might be worth amending the help text to include a link to: https://docs.python.org/3/library/re.html

It took me a while to figure out how to escape a left bracket with Python's re library :-) .  An example for the curious: `^[\[].*$`

**Comment by ccaputo** [comment]
> Fix confirmed. @vegu, it might be worth amending the help text to include a link to: https://docs.python.org/3/library/re.html
> 
> It took me a while to figure out how to escape a left bracket with Python's re library :-) . An example for the curious: `^[\[].*$`

Reclose if not worth adding the URL to help admins.

**Comment by ccaputo** [comment]
Fix confirmed.
