### ISSUE TITLE
[beta] IX-F importer: Clicking "Preview" (IXP Update Tools) on /net/ page resulted in 170 ticket resolutions

### ISSUE THREAD

**Issue by ccaputo** [peeringdb/peeringdb#769]
Some 170 tickets indicating resolution were just created with a timestamp of "July 16, 2020, 4:44 p.m.".  I believe this happened due to me clicking "Preview" on a /net/ page.

**Comment by vegu** [comment]
Hm, not able to reproduce this

**Comment by ccaputo** [comment]
> Hm, not able to reproduce this

At least on the beta system, since the resolutions were performed, I don't expect you will be able to unless all the IX-F tables are reset, or beta is reset, or a new IX-F import is made with another IXP.

Or is it possible you were doing work on https://github.com/peeringdb/peeringdb/issues/764 and I just conflated it with my test click of "Preview"?

**Comment by vegu** [comment]
No, i think this is a legitimate bug, just not sure how or why it happened yet.

**Comment by vegu** [comment]
was able to reproduce and can confirm that something about preview process is broken and seemingly resolves some conflicts.

**Comment by vegu** [comment]
looks like it actually just deleted the suggestions and didnt apply anything

**Comment by ccaputo** [comment]
This appears fixed in my testing.
