### ISSUE TITLE
[beta] IX-F suggestions: consolidate delete+add

### ISSUE THREAD

**Issue by vegu** [peeringdb/peeringdb#770]
The IX-F importer uses a unique set of (asn, ip4, ip6) as a way to identify entries on both sides.

In instances where (asn, ip4, ip6) exists on the IX-F side but on the peeringdb side there is only (asn, ip4, null) the importer will suggest the following actions

- delete (asn, ipv4, null)
- create (asn, ipv4, ipv6)

Right now this creates a notification for each action and is presented to the user as two separate suggestions they can apply.

while this atomic approach is sensible during automated application ix-f data, it makes more sense to consolidate such an action into an update like operation that is presented to the user as one action.

Likewise consolidating notifications where a netixlan is to be created and a related netixlan is to be deleted into one notification also makes sense.

**Proposed solution**

Set the delete operation(s) as a requirement of the add operation with a cascading delete. So if the add suggestion is removed so are the requirements.

In the case where such a combination exists the action will be classified as `update` rather than `add`. And the `delete` suggestions wont be rendered to the user since they are attached to another suggestion. 

Also there will be a clean up mechanism tied to a cron job that makes sure no orphaned requirements exist.

**Comment by vegu** [comment]
@ccaputo please add any additional thoughts you have on this issue

**Comment by ccaputo** [comment]
Maybe this solution is a parent "hint" with two children "actions", with the "actions" being indivisible, and only the parent "hint" being presented in the UI/tickets/emails.

**Comment by vegu** [comment]
I agree, updated the ticket with specifications

**Comment by mcmanuss8** [comment]
+1

-Steve

**Comment by ynbrthr** [comment]
+1

**Comment by arnoldnipper** [comment]
+1

**Comment by ccaputo** [comment]
@peeringdb/pc to be clear, approval for this is ASAP needed. I consider this a blocker preventing the IX-F importer code from going to production.

**Comment by arnoldnipper** [comment]
@peeringdb/pc I have moved this to consensus reached already. Please butt in, if you don't like it.

**Comment by grizz** [comment]
Operational bug, finalizing

**Comment by ccaputo** [comment]
Fix confirmed.  Most excellent!

**Comment by ccaputo** [comment]
@vegu, I notice that in the "IX-F Import Preview" the separate "suggest-delete" and "suggest-modify" remain visible, for example from https://beta.peeringdb.com/ix/984 :

![Screen Shot 2020-08-17 at 2 27 06 PM](https://user-images.githubusercontent.com/1417833/90446184-cea6ac80-e095-11ea-8293-9cc28c667541.png)

![Screen Shot 2020-08-17 at 2 27 18 PM](https://user-images.githubusercontent.com/1417833/90446194-d36b6080-e095-11ea-9932-6a6eae3cdbd8.png)

Is that something that is also able to be consolidated to avoid confusion by users that review the Preview?

**Comment by vegu** [comment]
@ccaputo looks like it's already halfway there by saying it wants to modify it (instead of add), we just need to make sure it hides the suggest-delete - i have opened #824 to track this
