### ISSUE TITLE
[beta] IX-F importer: don't bother about missing IPv{4,6} address when network is not doing IPv{4,6}

### ISSUE THREAD

**Issue by ccaputo** [peeringdb/peeringdb#771]
If a network's IPv6 flag for "Protocols Supported" is unchecked, we should not create tickets/hints/emails about a missing IPv6 address.

Conflicted addresses should still be worked toward resolution, but "null != ix_provided_ipv6" should be left alone if the network hasn't indicated support for IPv6.

**Comment by ynbrthr** [comment]
+1

**Comment by arnoldnipper** [comment]
+1

**Comment by ccaputo** [comment]
@peeringdb/pc to be clear, approval for this is ASAP needed.  I consider this a blocker preventing the IX-F importer code from going to production.  Forcing IPv6 addresses on networks not running IPv6 has the potential to turn into an IX-F importer reputation fiasco.

**Comment by arnoldnipper** [comment]
@peeringdb/pc I've moved this to "Consensus reached" for obvious reason. If one of you strongly objects it's still time and please do so.

@vegu: the same rule should apply for IPv4 as well of course

**Comment by ccaputo** [comment]
> @vegu: the same rule should apply for IPv4 as well of course

Good point!

**Comment by grizz** [comment]
Going to finalize this, seems like an operational bug, and it's only 12 hours before deadline.

**Comment by vegu** [comment]
@ccaputo the original ticket text talks specifically about not doing hints/email/tickets, but this would also change automated networks not getting the ipv6 set by the importer if they are not flagged as supporting ipv6, is that correct?

**Comment by arnoldnipper** [comment]
@vegu and @ccaputo, this clearly looks like a race condition. However, by giving permission to an IX to set `netixlan` values that also indirectly would need to set `info_unicast` and `info_ipv6`.  Would that make sense?

**Comment by mcmanuss8** [comment]
+1

**Comment by vegu** [comment]
> @vegu and @ccaputo, this clearly looks like a race condition. However, by giving permission to an IX to set netixlan values that also indirectly would need to set info_unicast and info_ipv6. Would that make sense?

that'd be easiest if thats a viable solution that people are happy with

if not, the other solution i had in mind was to fall back to partial matching to whatever ip they support and the unsupported ip gets ignored entirely, but also throws a bit of a wrench into the current implementation.

**Comment by ccaputo** [comment]
> @vegu and @ccaputo, this clearly looks like a race condition. However, by giving permission to an IX to set netixlan values that also indirectly would need to set info_unicast and info_ipv6. Would that make sense?

The tooltip for "Allow IXP Update" only says: "If enabled, an ixp may manage this network's entry in their peering list".

I don't see an interpretation of that as meaning that a network's list of "Protocols Supported" can be controlled by that.

Maintaining trust of the networks, so that more and more are comfortable selecting "Allow IXP Update", means we should not adjust their list of protocols supported and rather should perform updates/hints/emails/tickets that conform to their list of supported protocols.  Increasing the list of unintended consequences of selecting "Allow IXP Update" will, IMHO, result in less users of it than otherwise.

@arnoldnipper & @mcmanuss8 & @job & @peeringdb/pc ?

**Comment by arnoldnipper** [comment]
what about: Update and also create a ticket as there are contradicting information?

**Comment by ccaputo** [comment]
> what about: Update and also create a ticket as there are contradicting information?

I don't see how that will help.  IXPs will generally assign both an IPv4 and IPv6 address to all participants, and thus generally include both of those in their IX-F JSON export, regardless of whether the networks are actually not employing one of the protocols.  Thus there will almost always be contradicting information when a network has "Allow IXP Update" enabled and one of the major "Protocols Supported" unselected.

**Comment by arnoldnipper** [comment]
> IXPs will generally assign both an IPv4 and IPv6 address to all participants

Where is that written? Any well operating IX is only publishing real data. Unfortunately `operational` can't be set per protocol. Which would make sense anyway.

**Comment by arnoldnipper** [comment]
Which leads me to the question of how useful `info_unicast`, `info_multicast`, and `info_ipv6` nowadays still is.

**Comment by ccaputo** [comment]
> > IXPs will generally assign both an IPv4 and IPv6 address to all participants
> 
> Where is that written? Any well operating IX is only publishing real data. Unfortunately `operational` can't be set per protocol. Which would make sense anyway.

I doubt it is written anywhere.  :-)  My sense is that most IXPs simply assign both upon connection and don't monitor whether both are used operationally as part of informing their IX-F JSON export.

But networks know their own networks, and if one intentionally unchecks support of a protocol in PeeringDB, I don't see how that should be overridden.

**Comment by ccaputo** [comment]
If one IXP has a flawed IX-F JSON export, that should not be able to override a network's global protocol setting.

**Comment by arnoldnipper** [comment]
> My sense is that most IXPs simply assign both upon connection and don't monitor whether both are used operationally as part of informing their IX-F JSON export.

This is pure speculation. And IXPs very well know which protocols their customers use. At least the very well run do ;-)

**Comment by arnoldnipper** [comment]
> If one IXP has a flawed IX-F JSON export, that should not be able to override a network's global protocol setting.

As already mentioned. I don't see any useful operational information in these settings (anymore).

**Comment by ccaputo** [comment]
> > My sense is that most IXPs simply assign both upon connection and don't monitor whether both are used operationally as part of informing their IX-F JSON export.
>
> This is pure speculation. And IXPs very well know which protocols their customers use. At least the very well run do ;-)

Informed speculation.  :-)

An IXP could derive, for example, IPv6 protocol use based on conversation with the network, data from PeeringDB's 
```info_ipv6``` setting, operational observation, etc.

Either way, the setting of a global flag based on local observation or contact by a single IXP, is not appropriate.

> > If one IXP has a flawed IX-F JSON export, that should not be able to override a network's global protocol setting.
> 
> As already mentioned. I don't see any useful operational information in these settings (anymore).

Fair enough, but as long as they exist, they should be honored.  Removal of them is an independent issue for discussion elsewhere.

**Comment by arnoldnipper** [comment]
> Fair enough, but as long as they exist, they should be honored. Removal of them is an independent issue for discussion elsewhere.

Sure ... and hence, the best we can do is

 * to set all values according to the IX-F import but for ipv6
 *  to open an issue as there is a conflict so that `net` or `ix` update their setting

**Comment by ccaputo** [comment]
> > Fair enough, but as long as they exist, they should be honored. Removal of them is an independent issue for discussion elsewhere.
> 
> Sure ... and hence, the best we can do is
> 
> * to set all values according to the IX-F import but for the not supported protocol

Sorry - can you clarify explicitly what you mean here?

> * to open an issue as there is a conflict so that `net` or `ix` update their setting

I'm good with that.

**Comment by arnoldnipper** [comment]
> Sorry - can you clarify explicitly what you mean here?
> 

Aren't we discussing the case that the network did not set at least one protocol, but the ix is providing an IP address for exactly this protocol? So, what to do?

 * if `ip_unicast` is set to "false", don't set `ipaddr4`
 * if `ip_ipv6` is set to "false", don't set `ipaddr4`
 * set anything else

**Comment by ccaputo** [comment]
> Aren't we discussing the case that the network did not set at least one protocol, but the ix is providing an IP address for exactly this protocol? So, what to do?
> 
> * if `ip_unicast` is set to "false", don't set `ipaddr4`
> * if `ip_ipv6` is set to "false", don't set `ipaddr4`
> * set anything else

Correcting the above IPv6 line to say "don't set `ipaddr6`" makes this good.   Agreed.  Thus:

* if `ip_unicast` is set to "false", don't set `ipaddr4`
* if `ip_ipv6` is set to "false", don't set `ipaddr6`
* otherwise handle appropriately based on "Allow IXP Update" settings and the DOTF-derived specs
* open an issue when there is a conflict between protocols supported and IX-F JSON, so that `net` or `ix` update their setting

**Comment by vegu** [comment]
@ccaputo @arnoldnipper thanks for the summary / clarification

**Comment by arnoldnipper** [comment]
**Summary**

The IX-F JSON importer also has to look at the supported protocols section in the `net` object. Specifically

* if `ip_unicast` is set to "false", don't set `ipaddr4`
* if `ip_ipv6` is set to "false", don't set `ipaddr6`
* otherwise handle appropriately based on "Allow IXP Update" settings and the DOTF-derived specs
* open an issue when there is a conflict between protocols supported and IX-F JSON, so that `net` or `ix` update their setting

**Comment by arnoldnipper** [comment]
@ccaputo, did you notice that both `ip_unicast` and `ip_ipv6` are set to "false" by default? In fact, 22.06% actually have set both fields to "false" while 2.69% of them still have set `allow_ixp_update` to "true".

**Comment by ccaputo** [comment]
> @ccaputo, did you notice that both `ip_unicast` and `ip_ipv6` are set to "false" by default? In fact, 22.06% actually have set both fields to "false" while 2.69% of them still have set `allow_ixp_update` to "true". And these networks have 1,117 connections to exchanges.

No, I didn't know that.  Can you perform that check and include only networks who have been updated in the last 2 years?

**Comment by arnoldnipper** [comment]
> No, I didn't know that. Can you perform that check and include only networks who have been updated in the last 2 years?

  * created <= 1y ago: 1249/3444, i.e. 36.26%
  * updated <= 1y ago: 1548/9888, i.e. 15.65%

  * created <= 2y ago: 2208*100/6464, i.e. 34.15%
  * updated <= 2y ago: 2523/13225, i.e. 19.07%

**Comment by grizz** [comment]
Wow, I think we need to change the defaults? :) Maybe make it empty so they're forced to enter something?

**Comment by arnoldnipper** [comment]
> Wow, I think we need to change the defaults? :) Maybe make it empty so they're forced to enter something?

Forcing and API? ... esp. when you declare the field as boolean :)

**Comment by arnoldnipper** [comment]
@ccaputo, are you fine with this?

**Summary**

The IX-F JSON importer also has to look at the supported protocols section in the `net` object. Specifically

* iff `ip_unicast` is set to "false", don't set `ipaddr4` (i.e. `ipaddr6` is set to "true")
* iff `ip_ipv6` is set to "false", don't set `ipaddr6` (i.e. `ipaddr4` is set to "true")
* otherwise handle appropriately based on "Allow IXP Update" settings and the DOTF-derived specs
* open an issue when there is a conflict between protocols supported and IX-F JSON, so that `net` or `ix` update their setting

**Comment by ccaputo** [comment]
> * iff `ip_unicast` is set to "false", don't set `ipaddr4` (i.e. `ipaddr6` is set to "true")
> * iff `ip_ipv6` is set to "false", don't set `ipaddr6` (i.e. `ipaddr4` is set to "true")

I wonder if what you intend here is:

* if (`ip_unicast` == false && `ip_ipv6` == true) then don't set/hint for `ipaddr4`
* if (`ip_unicast` == true && `ip_ipv6` == false) then don't set/hint for `ipaddr6`
* if (`ip_unicast` == false && `ip_ipv6` == false) then set/hint for both `ipaddr4` and `ipaddr6`
* if (`ip_unicast` == true && `ip_ipv6` == true) then set/hint for both `ipaddr4` and `ipaddr6`

with the idea being that if either of the `ip_unicast` or `ip_ipv6` flags is set, then use them, otherwise assume the network is utilizing both protocols?

**Comment by arnoldnipper** [comment]
> I wonder if what you intend here is:

if the network did not set a protocol assume that it did not see this flag.

**Comment by ccaputo** [comment]
> > I wonder if what you intend here is:
> 
> if the network did not set a protocol assume that it did not see this flag.

Fine with me.

**Comment by ccaputo** [comment]
Keeping in mind this screenshot of notifications for ChIX after a reset:

<img width="960" alt="Screen Shot 2020-07-29 at 4 34 08 PM" src="https://user-images.githubusercontent.com/1417833/88864176-73317f00-d1b9-11ea-9eda-9981c03146bf.png">

if the AS63311 data is corrected to match ChIX and another reset-all is performed, there will be absolutely no email generated to neteng@unitedix.net regarding the Digital Network Access Communications protocol setting IPv6 mismatch with the ChIX IX-F export.  My expectation is that the IX should still get an email, even if there is only one item and that one item is a protocol difference.  This is reproducible back and forth.

**Comment by arnoldnipper** [comment]
> if the AS63311 data is corrected to match ChIX and another reset-all is performed, there will be absolutely no email generated to [neteng@unitedix.net](mailto:neteng@unitedix.net) regarding the Digital Network Access Communications protocol setting IPv6 mismatch with the ChIX IX-F export.

What did our specification say? Afair we didn't say anything about which notifications to send to the ix.

**Comment by ccaputo** [comment]
> > if the AS63311 data is corrected to match ChIX and another reset-all is performed, there will be absolutely no email generated to [neteng@unitedix.net](mailto:neteng@unitedix.net) regarding the Digital Network Access Communications protocol setting IPv6 mismatch with the ChIX IX-F export.
> 
> What did our specification say? Afair we didn't say anything about which notifications to send to the ix.

I suppose the specification didn't mention this, but this is clearly an inconsistency bug.  Potentially an edge case as @vegu asked we should look out for.

**Comment by arnoldnipper** [comment]
> * open an issue when there is a conflict between protocols supported and IX-F JSON, so that `net` or `ix` update their setting

The specification was very clear imho

**Comment by ccaputo** [comment]
> > * open an issue when there is a conflict between protocols supported and IX-F JSON, so that `net` or `ix` update their setting
> 
> The specification was very clear imho

Maybe I wasn't clear.  An issue is being opened when there are two conflicts, but not when there is one, in the case where one is a protocol conflict.  It doesn't make sense to email the IX where there are two, but not when there is only one.  The IX should be emailed in both cases.

**Comment by arnoldnipper** [comment]
Maybe I don't understand. The specification says to open an issue when there is a conflict between protocols supported and IX-F JSON. Regardless of whether there are other conflicts.

**Comment by ccaputo** [comment]
> Maybe I don't understand. The specification says to open an issue when there is a conflict between protocols supported and IX-F JSON. Regardless of whether there are other conflicts.

Yes.  I am saying an issue is being raised appropriately when there are 2 or more conflicts for an IX-F import, but not when a protocol mismatch is the sole conflict for an IX-F import.

**Comment by arnoldnipper** [comment]
> Yes. I am saying an issue is being raised appropriately when there are 2 or more conflicts for an IX-F import, but not when a protocol mismatch is the sole conflict for an IX-F import.

And I was saying that the specification is clear about this. Namely to open an issue.

**Comment by ccaputo** [comment]
> > Yes. I am saying an issue is being raised appropriately when there are 2 or more conflicts for an IX-F import, but not when a protocol mismatch is the sole conflict for an IX-F import.
> 
> And I was saying that the specification is clear about this. Namely to open an issue.

Ok - we are in agreement.  What I am trying to point out is that this is not happening consistently.

**Comment by ccaputo** [comment]
https://github.com/peeringdb/peeringdb/issues/811 may be related.
