### ISSUE TITLE
[beta] IX-F importer: only under beta: provide ability to reset "DeskPRO Tickets" table and all hints/dismisses/emails/etc.

### ISSUE THREAD

**Issue by ccaputo** [peeringdb/peeringdb#773]
Am I right in thinking it would be useful to have the ability to reset all aspects of the IX-F importer hinting/resolution process, but only on the beta site?

Possible as a flag or set of flags to ```pdb-container pdb_ixf_ixp_member_import```?

Maybe a global ```--reset``` flag?  And/or specific flags as make sense, such as ```--reset-dismisses``` and ```--reset-tickets``` and ```--reset-emails```?

Obviously, changes to netixlan that have already been accepted, would not be reset.

I think this would be useful for verifying bug fixes and new features of the IX-F importer.

Additionally, the resets themselves should be logged in the "DeskPRO Tickets" table, after any clearing, so that other tester admins can perceive the reset.

**Comment by vegu** [comment]
From a developer standpoint that makes sense to me.

When you say reset deskpro tickets, do you mean clear out the entire table or just remove tickets related to the ix-f importer. I am assuming the latter and IX-F tickets are identified by matching for the "[IX-F]" prefix in the subject. Let me know if not.

`--reset`: reset hints / dismisses / ix-f tickets / ix-f email table (#767)

Then individual flags for each

1. `--reset-hints`
2. `--reset-dismisses`
3. `--reset-tickets`
4. `--reset-email`

Prohibit use of these parameters if the environment is production.

**Comment by ccaputo** [comment]
> When you say reset deskpro tickets, do you mean clear out the entire table or just remove tickets related to the ix-f importer. I am assuming the latter and IX-F tickets are identified by matching for the "[IX-F]" prefix in the subject. Let me know if not.

I confirm I mean just the ix-f importer related items.  Thanks.

Is there anything else that should be resettable that I am missing?

> `--reset`: reset hints / dismisses / ix-f tickets / ix-f email table (#767)
> 
> Then individual flags for each
> 
> 1. `--reset-hints`
> 2. `--reset-dismisses`
> 3. `--reset-tickets`
> 4. `--reset-email`
> 
> Prohibit use of these parameters if the environment is production.
> 
> At the end make a DeskProTicket describing the reset

Excellent!

We may also want to make it so @arnoldnipper and other admin testers can run these from the Admin CP?  Or possibly only from the Admin CP rather than the CLI.  If possible, I think that would be preferred over the CLI.  Or maybe along with the CLI?

**Comment by vegu** [comment]
> We may also want to make it so @arnoldnipper and other admin testers can run these from the Admin CP? Or possibly only from the Admin CP rather than the CLI. If possible, I think that would be preferred over the CLI. Or maybe along with the CLI?

We have functionality in place to give admin com a UI for any peeringdb CLI. So i think it makes sense to develop the command then provide a ui for it as well. Question is should that still be tied to the import process (eg also allow the importer to be triggered from the ui?) or as a separate command.

**Comment by ccaputo** [comment]
> > We may also want to make it so @arnoldnipper and other admin testers can run these from the Admin CP? Or possibly only from the Admin CP rather than the CLI. If possible, I think that would be preferred over the CLI. Or maybe along with the CLI?
> 
> We have functionality in place to give admin com a UI for any peeringdb CLI. So i think it makes sense to develop the command then provide a ui for it as well. Question is should that still be tied to the import process (eg also allow the importer to be triggered from the ui?) or as a separate command.

I think being able to atomically trigger the importer from the admin UI would be useful.  Right now @peeringdb/ac does not have that ability to my knowledge.

**Comment by arnoldnipper** [comment]
> I think being able to atomically trigger the importer from the admin UI would be useful. Right now @peeringdb/ac does not have that ability to my knowledge.

That's true ... AC is not able to run the importer manually.

**Comment by ccaputo** [comment]
> > I think being able to atomically trigger the importer from the admin UI would be useful. Right now @peeringdb/ac does not have that ability to my knowledge.
> 
> That's true ... AC is not able to run the importer manually.

Would you/AC like the ability to trigger the importer on both the production and beta sites, with the ```--reset``` options being limited to the beta site?

**Comment by arnoldnipper** [comment]
> Would you/AC like the ability to trigger the importer on both the production and beta sites, with the `--reset` options being limited to the beta site?

Imho it would make sense to run the importer for a specific IX. And iirc we were talking about running the importer hourly instead of daily. Weren't we?

**Comment by ccaputo** [comment]
> > Would you/AC like the ability to trigger the importer on both the production and beta sites, with the `--reset` options being limited to the beta site?
> 
> Imho it would make sense to run the importer for a specific IX.

Arnold, is your thought to have the @peeringdb/ac be able to trigger the importer to run for a specific IX?

@vegu: Any thoughts on this?  

> And iirc we were talking about running the importer hourly instead of daily. Weren't we?

We've talked about that in the past.  But with this new one I think we are back to square one in terms of re-evaluating that.  Ie., start slow and ramp up with experience.

**Comment by vegu** [comment]
I dont see any inherent problem with allowing the ac to trigger the importer for single exchanges.

**Comment by funkestefan** [comment]
Would it be a problem to allow an IXP to trigger the importer for it's own data? This could be added to ixpmanager to push local data changes to pdb via API requests.

**Comment by ccaputo** [comment]
@peeringdb/pc to be clear, approval for this is ASAP needed in order to be able to actually properly test & verify the IX-F importer.  I consider this a blocker preventing the IX-F importer code from going to production.  At a minimum the CLI reset ability is needed for now.  The additional /cp/ features can be broken out into a separate feature request ticket if @vegu indicates they would more substantial development time.

**Comment by arnoldnipper** [comment]
@peeringdb/pc I have moved this to consensus reached already. Please butt in if you think this issue doesn't make sense!

**Comment by vegu** [comment]
@ccaputo i dont anticipate allowing the ac to run the importer against an exchange to add any significant amount of time, but will re-assess after the --reset functionality has been implemented.

Letting exchanges run the importer for themselves should be a separate ticket imo.

**Comment by grizz** [comment]
Operational bug, finalizing.

@funkestefan Added #779 -- great idea!

**Comment by ccaputo** [comment]
Use of this reset functionality is confusing and not sure as intended.  At present if one selects, for example, "ChIX" and click "Reset hints", it will reset hints for all IXes and then perform an import for just ChIX.

If I select ChIX, and click some reset options, I expect then reset operations to pertain only to ChIX.

If I don't select any ix, which is currently not allowed, that is when I would expect the operations to be global.

If we want this functionality to _EITHER_ work as a per-ix importer _OR_ a resetter, we should make it so the IX choice is exclusive of the reset choices and vice versa.  As mentioned, at present one has to select an IX to then "Preview Command".  There is no option for not selecting an IX.

Since the resets are just for the beta at this point (maybe forever), I'm happy with exclusivity being forced.  You are either resetting things (beta-only) or forcing a particular IX to perform an import (beta or production).

**Comment by arnoldnipper** [comment]
I also came across this behaviour. But once you understand you know how to combine them. 

Q: how many ixes are able to use this GUI to test the new functionalities?

**Comment by ccaputo** [comment]
> I also came across this behaviour. But once you understand you know how to combine them.
> 
> Q: how many ixes are able to use this GUI to test the new functionalities?

Only PeeringDB admins, so very few.  I am okay with this being just a documentation update on the page if you don't care for the exclusivity aspect to be enforced in code.

**Comment by arnoldnipper** [comment]
> Only PeeringDB admins, so very few.

To test the new importer/functionalities IXes currently only have limited tools. Maybe I've misplaced it, but the importer endpoint /import/ixlan/$ixlan_id/preview does not longer work for me.

**Comment by ccaputo** [comment]
I think the simplest change would be to make it so in the /cp/ interface it is possible to perform the command without specifying a specific IX.  This would allow admins to kick off a full import, outside of the cron schedule, on both prod and beta.  (resets remain limited to beta)

**Comment by arnoldnipper** [comment]
Let's leave it as it is for the moment. When we are done with beta, change it to perform a full import. A per IX import may then be done via #779

**Comment by ccaputo** [comment]
I think things are good as is.  Closing this.

**Comment by ccaputo** [comment]
I have confirmed that the `--reset` flags do not work in production, as intended.
