### ISSUE TITLE
Add YouTube icon and update Twitter icon in footer

### ISSUE THREAD

**Issue by ghankins** [peeringdb/peeringdb#774]
Order should be:
Facebook
GitHub
LinkedIn
Twitter (replace with attached and name icon social-twitter.png)
YouTube (add attached and name icon social-youtube.png, link to https://www.youtube.com/channel/UCOrYWUg-dbL9UTFV_Lry6Wg)

![social-youtube](https://user-images.githubusercontent.com/8171907/87862533-3d6dda00-c91f-11ea-99c7-7bf807a164f9.png)
![social-twitter](https://user-images.githubusercontent.com/8171907/87862534-3e067080-c91f-11ea-9c1b-c4e3179924e9.png)

**Comment by ghankins** [comment]
Release Notes: A new YouTube icon and link is added, and the Twitter icon is updated in the footer.

**Comment by arnoldnipper** [comment]
+1

**Comment by arnoldnipper** [comment]
@ghankins this does not need code changes, right?

**Comment by ghankins** [comment]
> @ghankins this does not need code changes, right?

@arnoldnipper that is correct.

**Comment by arnoldnipper** [comment]
@peeringdb/pc, please ack as this is for @peeringdb/outcom and only needs a config line in the webserver config but no code change

@peeringdb/oc would it be possible to make the changes with the next release?

**Comment by mcmanuss8** [comment]
+1

-Steve

**Comment by ynbrthr** [comment]
+1

**Comment by ccaputo** [comment]
My understanding is this is not a webserver config change, but rather these are footer template changes with PNG image additions/changes.  Those kinds are changes are higher risk now that the instances are in docker containers.  Hot patching would involve careful docker container manipulation and restarts.

With all of the ix-f importer work to be done, I expect there will be a new beta deploy (or few).  Can you label this as such so that @grizz knows to make sure this goes into the next one?

**Comment by ccaputo** [comment]
@ghankins do you have an updated YouTube URL yet?  SInce subscribers is above 100 now, I imagine you'll want to update this issue to use the actual final URL.

**Comment by ghankins** [comment]
To create a custom URL for your channel, your account needs to:
    Have 100 or more subscribers.
    Be at least 30 days old.
    Have an uploaded photo as a channel icon.
    Have uploaded channel art.

We created the channel on Jul 13, 2020 so I expect we'd be eligible for a custom URL around Aug 13.

**Comment by ccaputo** [comment]
> To create a custom URL for your channel, your account needs to:
> Have 100 or more subscribers.
> Be at least 30 days old.
> Have an uploaded photo as a channel icon.
> Have uploaded channel art.
> 
> We created the channel on Jul 13, 2020 so I expect we'd be eligible for a custom URL around Aug 13.

Got it.  I trust for now this issue should proceed is as, with the current URL?

**Comment by mcmanuss8** [comment]
> > To create a custom URL for your channel, your account needs to:
> > Have 100 or more subscribers.
> > Be at least 30 days old.
> > Have an uploaded photo as a channel icon.
> > Have uploaded channel art.
> > We created the channel on Jul 13, 2020 so I expect we'd be eligible for a custom URL around Aug 13.
> 
> Got it. I trust for now this issue should proceed is as, with the current URL?

May as well. I submitted a PR for it and it's a trivial change we can do in a future release once we have a custom URL

**Comment by ghankins** [comment]
> 
> 
> > > To create a custom URL for your channel, your account needs to:
> > > Have 100 or more subscribers.
> > > Be at least 30 days old.
> > > Have an uploaded photo as a channel icon.
> > > Have uploaded channel art.
> > > We created the channel on Jul 13, 2020 so I expect we'd be eligible for a custom URL around Aug 13.
> > 
> > 
> > Got it. I trust for now this issue should proceed is as, with the current URL?
> 
> May as well. I submitted a PR for it and it's a trivial change we can do in a future release once we have a custom URL

I think so too, let's proceed and I'll open another issue when we have the custom URL.
