### ISSUE TITLE
Misleading tooltip of prefix limit fields

### ISSUE THREAD

**Issue by moesoha** [peeringdb/peeringdb#775]
The two prefix limit fields, "IPv4 Prefixes" and "IPv6 prefixes", and its tooltips are misleading some users. I've seen many users wrote 24 for IPv4 and 48/64 for IPv6, as they think the fields are for maximum CIDR length.

The current tooltip is "Recommended IPv4/IPv6 maximum-prefix limit to be configured on peering sessions for this ASN". We can use "Recommended maximum number of IPv4/IPv6 routes/prefixes to be ..." or some better choice.

**Comment by arnoldnipper** [comment]
While I see that some users are not understanding `maximum-prefix limit` this is the terminus technicus. Whenever you configure the maximum-prefix it will be shown like that.  

Hence -1

**Comment by ynbrthr** [comment]
while the fields' name could be misconstrued, the tooltip doesn't leave room for (mis)interpretation. I would think that the networks having entered a prefix length here did so before the tooltip got implemented, I don't see how someone could get confused with it.

-1 for me

**Comment by job** [comment]
I agree with Arnold and Yann

**Comment by arnoldnipper** [comment]
**Summary**

kill the issue as the tooltip is exactly saying what is meant

**Comment by moesoha** [comment]
Many networks created recently have this issue, like https://www.peeringdb.com/net/23986 https://www.peeringdb.com/net/23987 .

When I corrected other two networks by telling them how to understand the tooltip, one of the operators says they do think the field is prefix length limit to fill.

Anyway, this may not be a problem for most users, but surely it misleads some users.

**Comment by arnoldnipper** [comment]
We are closing the issue as the tooltip is exactly saying what is meant

**Comment by HertzHz** [comment]
No, it's really a bad idea, I'm one of operators who write 24 and 48 here.
Recommended IPv6 maximum-prefix limit.  maximum-prefix can be understood as prefix max length.
```
>>> import requests
>>> _data = requests.get("https://www.peeringdb.com/api/net?info_prefixes6=48").json()
>>> len(_data['data'])
39
```

Up to now, there's still 39 networks are using 48 for max prefixes

![Snipaste_2020-08-13_18-05-58](https://user-images.githubusercontent.com/63715679/90122583-15439080-dd90-11ea-8a01-92aeb6ac987c.png)

This is a channel which is started on June, 2020, only 2 months there are 26 updates are using 48 as max prefixes
These all can show how widespread is this misunderstanding, if you change `Recommended IPv6 maximum-prefix limit` to `Recommended IPv6 maximum routes limit` I think the problem will get solved.

**Comment by grizz** [comment]
I agree with @moesoha and think @HertzHz makes a valid point. It's literally a 1 minute change to add `(number of routes)` to the tooltip, why wouldn't we just do it? There's certainly no downside to it that I can see and I've spent more time typing this than it would have taken to change it. :)

+1 from me, starting a full formal vote @peeringdb/pc

**Comment by HertzHz** [comment]
+1

**Comment by job** [comment]
+1

**Comment by Alan-yhq** [comment]
+1

**Comment by moesoha** [comment]
Thank you grizz! I'm advising to use a tip like "Recommended maximum number of IPv4 routes/prefixes to be configured on peering sessions for this ASN".

+1 for me.

**Comment by arnoldnipper** [comment]
> Thank you grizz! I'm advising to use a tip like "Recommended maximum number of IPv4 routes/prefixes to be configured on peering sessions for this ASN"

Sounds perfect to me.

+1 for changing the tooltip
