### ISSUE TITLE
Location data normalization

### ISSUE THREAD

**Issue by ynbrthr** [peeringdb/peeringdb#777]
* Evaluation of a geolocation normalization API (Openstreetmap, others)
* Address normalization via a javascript widget whenever a record is added / created
* Needs to handle updates via the API
* Standardize address fields across all objects using geoloc data: facs, orgs, and add suite/floor address field (RFC6350; RFC5774)
* Search will be done by lat/long rather than name
* Local city names will be handled in the translation layer

Existing related issues:

#98: name equivalent class for searching
#255: Address field for datacenters could do with a floor or suite number
#479: you can’t find an ixp in montana (April 2019)

**Comment by arnoldnipper** [comment]
+1

**Comment by shane-kerr** [comment]
+1

**Comment by mcmanuss8** [comment]
+1

**Comment by vegu** [comment]
**Questions**

When changing the address field of org or facility, should the user be asked to confirm the normalized address ? 

**Notes**

We're still working out localization - whether or not we can make it work through the current translation 
setup via gettext or not.

Search enhancements are to be part of the search improvement milestone and should be specced or there

**Summary**
- add `suite` field to org and fac models / views / api serializers
- add `floor` field to org and fac models / views / api serializers
- add org to the geogoding enabled objects
- enhance the current geocoding function to also normalize address fields (english)
  - city
  - country
  - address1
  - address2
  - zipcode
  - suite
  - floor 
- normalize all existing facility and organization addresses
- validate and normalize address field changes (or new objects) with the api request.
  - an address that could be geocoded will be returned in the api response / UX feedback with the normalized values
  - an address that cannot be geocoded correctly will result in a validation error
- (pending clarification) enhance the address form to also normalize / validate the entered data
  and ask the user for confirmation

**Comment by arnoldnipper** [comment]
> When changing the address field of org or facility, should the user be asked to confirm the normalized address ?

A user should be asked to confirm the normalized address iff it differs from what they entered. Both in case they initially add the address as well when they later change it.

**Comment by ynbrthr** [comment]
> > When changing the address field of org or facility

or ixp. even if it's tackled at a later stage, we need to capture that all objects being tied to a location will be addressed

**Comment by ynbrthr** [comment]
> > When changing the address field of org or facility, should the user be asked to confirm the normalized address ?
> 
> A user should be asked to confirm the normalized address iff it differs from what they entered. Both in case they initially add the address as well when they later change it.

not sure about that. looking at vienna, at, we have 3 versions:

Vienna (Wien), Vienna, Wien

the first entry is incorrect, and the last one will be used for users using a german locale. We don't need user input for that. Likewise, looking at the facs at 43.644672,-79.384128, we get as street addresses:

151 Front St W.
151 Front St
151 Front St. W.
151 Front Street West

We will normalize to 1 of those (actually, i believe it should be "151 Front St W" which is not even here), we don't need people's input for that.

**Comment by arnoldnipper** [comment]
There was a discussion going on the PC list which clearly indicates that there is no consensus

**Comment by leovegoda** [comment]
The Product Committee has decided to close this issue. There was no agreement on the concept and the issue has not been discussed for six months or longer.
