### ISSUE TITLE
Do not show objects in status "pending" on the UI

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/peeringdb#784]
Currently, `ix` and `fac` in `status` "pending" are publicly shown. This may be confusing, esp. if they do not get approved. Proposal is to not show only objects with `status` "ok".

**Comment by arnoldnipper** [comment]
@peeringdb/pc, please vote

**Comment by shane-kerr** [comment]
+1 to only show objects with status "ok".

**Comment by job** [comment]
+1

Small nit: maybe it can be made so that users with peeringdb wide admin privileges will see the "pending" objects?

**Comment by netravnen** [comment]
>
> Small nit: maybe it can be made so that users with peeringdb wide admin
> privileges will see the "pending" objects?
>
I'm for this idea (to a degree), as it makes sense for org-admins to be
able to edit pending review applications (not org-users). One caveat I'd
like to add is, in my opinion, the "Pending review" shall, in this example,
be more prominently displayed on the page. Apart from just a small label
beside the editing button. (e.g. use of bold text or put an Informational ℹ
sign next to it).

If you mean any e.g. AC-member or similar accounts with the Super-Admin
privilege. That is of course also an option to go with.

**Comment by job** [comment]
Yeah I meant that such pending entries should be easily visible to AC members, not to regular peeringdb users.

**Comment by arnoldnipper** [comment]
> I'm for this idea (to a degree), as it makes sense for org-admins to be able to edit pending review applications (not org-users).

Why does it make sense to edit _pending_ issues? Either you approve or disapprove. Once approved you are able to edit via the UI.

> Yeah I meant that such pending entries should be easily visible to AC members, not to regular peeringdb users.

These are not easily visible via the UI but only via the Admin UI

**Comment by job** [comment]
sounds good

**Comment by mcmanuss8** [comment]
I liked the idea of showing them to AC members but if AC doesn't find value in it, then +1 to the proposal of only showing objects with "ok" status

**Comment by arnoldnipper** [comment]
> I liked the idea of showing them to AC members but if AC doesn't find value in it, then +1 to the proposal of only showing objects with "ok" status

AC has a way better look via the AC GUI. And as mentioned there is no benefit of being able to edit a pending object. If you want to approve it, do it and then edit. If you don't want to approve it, then there is no need to edit it ;-)

**Comment by netravnen** [comment]
On Tue, 28 Jul 2020 at 19:47, Arnold Nipper <notifications@github.com> wrote:
> I liked the idea of showing them to AC members but if AC doesn't find value in it, then +1 to the proposal of only showing objects with "ok" status

I find the value in being able to view pending objects from the user
front-end. Especially in cases where an organization may submit
multiple entries for approval within a very short period of time (e.g.
>2 entries for approval submitted within a time span of ~15 minutes).
Albeit rare, this does happen.

**Comment by arnoldnipper** [comment]
> In my personal opinion, navigating between multiple entries in the database under the same organization is infinitely more accessible from the user frontend. Compared to the Admin UI where the focus of UI navigation leans heavier on per-object-of-$type basis.

Does https://peeringdb.com/cp/peeringdb_server/verificationqueueitem/ not work for you?

**Comment by vegu** [comment]
**Summary**

- Entities that do **not** have status `ok` should not be available to be viewed through the customer facing UI, and should return a 404 Not Found response.
- It is still a good idea to indicate to organization admins that they have entities that are pending review, so keep the entry that is displayed in their Facility/Network/Exchange list after they sent of the creation request, but remove the link to the entity itself.

**Comment by as44980** [comment]
Perhaps because the lack of progress in #23 it appears that users continue to suggest facilities which already exist, which are now associated with https://www.peeringdb.com/org/20525, and these are showing up on the front page..

Given these duplicate facilities are superflous I cant see any need to display them outside of whatever this AC admin interface that has taken up most of the discussion on this thread is about, so it would be nice if users could trust that data which appears on the front page is not bogus :)
