### ISSUE TITLE
strip "-" when doing searches

### ISSUE THREAD

**Issue by mcmanuss8** [peeringdb/peeringdb#787]
A common problem I have is searching for de-cix or ams-ix by typing "decix" and "amsix" respectively.

A quick fix for this would be to try stripping out the - when searching for a string (in addition to the existing search results). In SQL you could do something like:

select distinct ix, name from ix where name like '%searchstring%' or  replace(name, "-", "") like '%searchstring%'

**Comment by ynbrthr** [comment]
+1

**Comment by arnoldnipper** [comment]
+1

**Comment by job** [comment]
+1

**Comment by shane-kerr** [comment]
+1

**Comment by vegu** [comment]
Reading this, my assumption is that this behaviour should be consistent between the quick search / advanced search / api filter search - is that correct?

If also to be implemented for advanced search / api filters which fields, if any, other than entity names should this behaviour apply to?

Moving to 3a while waiting on clarification for that, thanks.

**Comment by mcmanuss8** [comment]
I feel it only applies to entity names. I'm ok with this change being on both the api and the frontend to make it consistent.

**Comment by as44980** [comment]
While I can certainly see this would be useful for the examples listed..

It appears that at least the quick search and advance search for IX's both consider the "Long Name" field where any IX's who were concerned about users who are unaware of their preferred hyphenation could place their unhypinated equivalents.. 

As it would appear "DE-CIX" has opted to do in their [Chennai IX's record](https://www.peeringdb.com/ix/2588) :smile:  

Also should we consider potential confusion where stripping "-" from a search string would result in namespace conflicts?

eg when searching for [B-IX](https://www.peeringdb.com/search?q=B-IX), is it desirable that the result should include [BiX](https://www.peeringdb.com/ix/55) and [BIX.BIG](https://www.peeringdb.com/ix/331) ?

**Comment by arnoldnipper** [comment]
> As it would appear "DE-CIX" has opted to do in their [Chennai IX's record](https://www.peeringdb.com/ix/2588) 😄

This was me to see if it is working. It doesn't ;-)

**Comment by arnoldnipper** [comment]
> Also should we consider potential confusion where stripping "-" from a search string would result in namespace conflicts?

I guess that can be solved by ranking the results

**Comment by as44980** [comment]
> > As it would appear "DE-CIX" has opted to do in their [Chennai IX's record](https://www.peeringdb.com/ix/2588) smile
> 
> This was me to see if it is working. It doesn't ;-)

Hmm, it would appear to work as its included in the search results for [DECIX](https://www.peeringdb.com/search?q=decix)..

Or is this not what you expected? :smile:

**Comment by arnoldnipper** [comment]
> > > As it would appear "DE-CIX" has opted to do in their [Chennai IX's record](https://www.peeringdb.com/ix/2588) smile
> > 
> > 
> > This was me to see if it is working. It doesn't ;-)
> 
> Hmm, it would appear to work as its included in the search results for [DECIX](https://www.peeringdb.com/search?q=decix)..
> 
> Or is this not what you expected? 😄

I always forget that changes to the DB are not visible immediately. I.e. I added "DECIX" and did not wait long enough so that the result showed up in the query.

**Comment by as44980** [comment]
> I always forget that changes to the DB are not visible immediately. I.e. I added "DECIX" and did not wait long enough so that the result showed up in the query.

Clearly your Internet connection is too fast, these problem never existed back when reloading a webpage left ample time to make a hot drink :coffee:

**Comment by grizz** [comment]
This will be fixed with #23
