### ISSUE TITLE
[beta] IX-F importer: tooltip remains visible after clicking "Auto-resolve", also misspelling

### ISSUE THREAD

**Issue by ccaputo** [peeringdb/peeringdb#788]
The "Autoamtically update and remove all suggested entries" tooltip remains visible after clicking "Auto-resolve".  Also, `Autoamtically` should be correctly spelled `Automatically`.

<img width="609" alt="Screen Shot 2020-07-29 at 2 48 16 PM" src="https://user-images.githubusercontent.com/1417833/88857143-956fd080-d1aa-11ea-8802-69a5e7e1b057.png">

**Comment by shane-kerr** [comment]
+1 

For fixing both bugs.

**Comment by ccaputo** [comment]
Fix confirmed.
