### ISSUE TITLE
System emails should be HTML+plaintext instead of just plaintext

### ISSUE THREAD

**Issue by job** [peeringdb/peeringdb#79]
Currently PeeringDB is emailing 'plaintext' emails with hyperlinks to Deskpro - however Deskpro (unlike ubersmith) is not converting these plaintext hyperlinks to actual hyperlinks, so admins need to copy+paste the links into their browsers instead of just clicking.

Would it be possible to change the system emails to HTML formatted emails? Just making the emails HTML isn't enough, the mimetype needs to be HTML as well.

**Comment by grizz** [comment]
Has anyone tested if it will pick up links from an email with both text and HTML mimetypes on the emails?

```
                       _
ASCII ribbon campaign ( )
 against HTML e-mail   X
                      / \
```

**Comment by job** [comment]
Yes, I sent an email from gmail's webinterface. That produced the expected
outcome.

**Comment by grizz** [comment]
Good deal, thanks. We'll make it send both then.

**Comment by vegu** [comment]
fixed in baeac8d (2.0.12)

**Comment by vegu** [comment]
reopened and moved to "Done" status until rolled to production

**Comment by job** [comment]
when will 2.0.12 be deployed?

**Comment by grizz** [comment]
Waiting on AC approval, see list threads.
