### ISSUE TITLE
[beta] IX-F importer: Lack of fields  in IX-F JSON should imply "undefined" rather than "false" and result in no action

### ISSUE THREAD

**Issue by ccaputo** [peeringdb/peeringdb#792]
If an IX does not set "routeserver" in their IX-F JSON data, the IX-F importer is currently treating this as meaning `false`, thus resulting in hints/issues/tickets for any network that has "is_rs_peer" set to `true`.  This is very broken.  A lack of this data should mean `undefined` and not result in any action.  The IX-F JSON spec in no way makes this field required.

https://github.com/peeringdb/peeringdb/issues/359 is related, but creating this as a separate bug because I see it as a showstopper for the IX-F importer re-enabling.

**Comment by mcmanuss8** [comment]
+1 - seems like an important bug for us to fix before we roll this out.

**Comment by arnoldnipper** [comment]
Same holds for all other fields (i.e. ipaddr4, ipaddr6 and speed). Only asn is required.

**Comment by vegu** [comment]
> Same holds for all other fields (i.e. ipaddr4, ipaddr6 and speed). Only asn is required.

Ipaddresses already meet that criteria, i will test that speed works accordingly as well, and if not can probably fix it in scope of  this ticket

**Comment by vegu** [comment]
Looks like speed needs to be fixed for this as well. I am good to just attach that to this ticket if everyone else is.

**Comment by arnoldnipper** [comment]
> Looks like speed needs to be fixed for this as well. I am good to just attach that to this ticket if everyone else is.

I've changed the subject to catch all other fields as well
