### ISSUE TITLE
[beta] IX-F importer: handling of buggy IX-F JSON data

### ISSUE THREAD

**Issue by ccaputo** [peeringdb/peeringdb#794]
In cases where an IX supplies buggy IX-F JSON data that can't be reasonably processed, for example the same IP address appearing multiple times in the export, the importer shall:

* create a ticket for the AC
* send an email to the IX informing them of the issue

@vegu & @arnoldnipper, do you think the import flag for the IX should also be set to `false`, or best to leave it `true` so it simply gets retried over and over, while not resulting in successive tickets/emails?

**Comment by vegu** [comment]
we already have a locked notify to the ix for cases like this , the duplicate ip issue just doesn't trigger it at the moment, adding that condition to it should be fairly straightforward.

it will notify the ix once, then not again until another error happens after a successful import.

**Comment by arnoldnipper** [comment]
To remove duplicates simply run it through

``` 
jq '.member_list | unique'
```

**Comment by ccaputo** [comment]
Please don't close this.  It is not simply addressed by removing duplicates.  There will be cases where IX-F exports are faulty in other ways.

**Comment by arnoldnipper** [comment]
> There will be cases where IX-F exports are faulty in other ways.

In what ways buggy.

**Comment by ccaputo** [comment]
> > There will be cases where IX-F exports are faulty in other ways.
> 
> In what ways buggy? Duplicates are not buggy. If the IX-F JSON is compliant, the importer has to process it. Fullstop. Normalizing (e.g. removing duplicates which created the problems) should, of course, be done, before actually working on the import.

I don't know.  But the IX-F JSON could be compliant one day and then non-compliant the next.  In that case it makes sense to:

* create a ticket for the AC
* send an email to the IX informing them of the issue

Or at least just inform the IX if you don't want the AC to be notified about it.

**Comment by arnoldnipper** [comment]
> Or at least just inform the IX if you don't want the AC to be notified about it.

We should expect that the exchange provides a compliant import. So, sending them an email incl. a hint on how to validate their JSON should be sufficient.  As I understood @vegu this already is done. So, let's close the issue. Ok?

**Comment by ccaputo** [comment]
> > Or at least just inform the IX if you don't want the AC to be notified about it.
> 
> We should expect that the exchange provides a compliant import. So, sending them an email incl. a hint on how to validate their JSON should be sufficient. As I understood @vegu this already is done. So, let's close the issue. Ok?

I created the issue because my understanding from @vegu's email is that it is not yet being done (emailing IX, creating DeskPRO ticket).  If @vegu says otherwise, we can close it or he can close it.

Please clearly state if you don't want an AC ticket when this happens.

**Comment by arnoldnipper** [comment]
There is no need to create a DeskPRO ticket

**Comment by ccaputo** [comment]
_Summary_:

In cases where an IX supplies buggy IX-F JSON data that can't be reasonably processed, the importer shall:

* send an email to the IX informing them of the issue

**Comment by vegu** [comment]
> _Summary_:
> 
> In cases where an IX supplies buggy IX-F JSON data that can't be reasonably processed, the importer shall:
> 
> * send an email to the IX informing them of the issue

This already happens, so closing

**Comment by ccaputo** [comment]
Confirmed.
