### ISSUE TITLE
peeringdb-py feels abandoned

### ISSUE THREAD

**Issue by mahtin** [peeringdb/peeringdb#796]
As a follow-up to #786 and in looking at https://github.com/peeringdb/peeringdb-py/issues and more importantly http://peeringdb.github.io/peeringdb-py/ I feel that `peeringdb-py` feels abandoned. I stand by my statement in #786 that the code will not perform a sync; however, I will go one stage further and point out that the documentation is both sparse (it's always been sparse - so this isn't new)  and that the code is far from complete.

Effort should be placed on making this code a solid offering.

**Comment by job** [comment]
In the other ticket there was a question outstanding, hard to move forward if you don't reply

**Comment by grizz** [comment]
I agree, we have a handful of things we're going to get on once the DOTF issues are complete.

There are also sync fixes that will be released this month with everything else.

**Comment by arnoldnipper** [comment]
@mahtin I close this ticket as there is nothing to do
