### ISSUE TITLE
Additional self-selection fields for IX objects

### ISSUE THREAD

**Issue by mcmanuss8** [peeringdb/peeringdb#799]
If we end up with a lot of ideas, we can split the conversation into multiple issues to keep it sane. Let's try one ticket for now though.

Format here is the field and below a list of options for that field. All options are placeholders and are up for debate :)

Service Level: 
- Best Effort (no SLA)
- Normal Business Hours
- 24/7 Support

OpenIX Certification:
- Not Certified
- Working Towards Certification
- Certified
(For this value, would be excellent if we could hook into an openix api)

Commercial Terms:
- No Commercial Terms
- Bundled with other services
- Non-recurring fees only
- Recurring fees

**Comment by arnoldnipper** [comment]
+1

**Comment by shane-kerr** [comment]
+1

Seems like a reasonable start.

**Comment by job** [comment]
Might be good to rename "Commercial Terms:" to "Terms:"

**Comment by job** [comment]
Similar to what I commented in the MANRS issue, I think that if an IX is not OpenIX certified, the phrase OpenIX should not show in the Web UI for a given IX.

I imagine over time various "badges" and "self-selection" datafeeds can pop up, perhaps from competing standards / certification organisations. 

Since humans have a strong tendency to 'check all the boxes', I feel we should only show boxes that actually have been check, rather than blindly encourage people to join specific certification processes for no other than than checking the box on peeringdb.

**Comment by arnoldnipper** [comment]
> Similar to what I commented in the MANRS issue, I think that if an IX is not OpenIX certified, the phrase OpenIX should not show in the Web UI for a given IX.

How would an IX then get OpenIX certified? The current idea is that the IX might tick the box but it will only be shown if we can verify at OpenIX.

Or did I misunderstand you?

**Comment by job** [comment]
> > Similar to what I commented in the MANRS issue, I think that if an IX is not OpenIX certified, the phrase OpenIX should not show in the Web UI for a given IX.
> 
> How would an IX then get OpenIX certified? The current idea is that the IX might tick the box but it will only be shown if we can verify at OpenIX.
> 
> Or did I misunderstand you?

That seems like duplicate work, I can see a few approaches:

1) periodically peeringdb fetches the latest data from $badge_provider, and offers those badges up to display on the ix record, the user selects which badges they want to display

2) periodically peeringdb fetches the latest data from $badge_provider and it is displayed automatically

3) the user indicates they have a badge, and then peeringdb fetches confirmation from the $badge_provider

I think option 2 is my current preference, as it is least work for all involved. Option 1 also seems user friendly

**Comment by arnoldnipper** [comment]
Option 2 clearly goes against our paradigm that data is user-provided. Hence I would go for option 3.

**Comment by johannesmoos** [comment]
I think it would be handy to have the ```info_traffic``` and ```info_ratio``` fields of the ```net``` object also to be present in the ```ix``` object. Options can be carried over. Background: IX Route servers are modelled as networks and specifying the IX traffic [ratio] there is technically not 100 % correct. IXPs can configure these values in the ```ix``` object. Does this make sense?

**Comment by arnoldnipper** [comment]
Thanks for suggesting. `info_traffic` does make perfect sense to me, @johannesmoos. But shouldn't `info_ratio`not also be "Balanced"?

**Comment by johannesmoos** [comment]
Yes, this should almost always be the case. I think I overthought this one (interconnecting IXs, …). So let’s keep it simple and forget about the ```info_ratio``` part.

**Comment by martzuk** [comment]
> Option 2 clearly goes against our paradigm that data is user-provided. Hence I would go for option 3.

IMHO a combination of 1 and 3, as with JSON import a user can select that they're happy for the IX to populate data on their record for them, which strictly goes against the paradigm of data being user provided.

**Comment by grizz** [comment]
@peeringdb/pc so, skipping OIX since I think that's handled in #801 

What do we want for field names here?

`service_level`
`terms`

And the field types should be string, with a choice drop down?

Since this will be adding a field to the API, should we get a full vote on it?

**Comment by vegu** [comment]
**summary**

- add `service_level` field to InternetExchange object and api serializer, represented as a `choice` dropdown with the following `string` values:
  - Best Effort (no SLA)
  - Normal Business Hours
  - 24/7 Support
  - Not Disclosed `default`
- add `terms` field to InternetExchange object and api serializer, represented as a `choice` dropdown of the following `string` values:
  - No Commercial Terms
  - Bundled with other services
  - Non-recurring fees only
  - Recurring fees
  - Not Disclosed `default`

**Comment by egfrank** [comment]
Hi @peeringdb/pc . We're currently developing this issue and had a question. Presently, Advanced Search allows filtering by certain choice fields such as Media Type. Should `service_level` and `terms` be added to Advanced Search? If yes, should that be completed as part of this issue, or should it be split off into a separate issue?

![Screen Shot 2021-04-15 at 4 53 47 PM](https://user-images.githubusercontent.com/17442049/114943638-e80e1d00-9e0b-11eb-8345-ca6c21484d4d.png)

**Comment by mcmanuss8** [comment]
@egfrank good question. #802 handles adding support for these to advanced search. If you have cycles to include it in the next release, please do so.

**Comment by arnoldnipper** [comment]
There is no way for IX operators to input these additional pieces of information
