### ISSUE TITLE
Check network's IXP IP address against IXP's IP range

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/peeringdb#8]
Make sure that $networks_IP is within the IXP's IP range (both IPv4 and IPv6)

**Comment by karumugham** [comment]
Agree this makes sense, seems like a straightforward enhancement and will improve the integrity of data. I suggest we move this to the Icebox.

**Comment by eloos** [comment]
@grizz, @arnoldnipper how far are we with this? I think for exchanges that have an IX-F feed this is fixed, how about others? If an IXP controls their record I believe they can set the correct IP range and new records are checked against that?

**Comment by arnoldnipper** [comment]
There are still 108 IXP which don't have any ixpfx registered.

**Comment by eloos** [comment]
@arnoldnipper ok, so what does that mean for the 108 IXP which are not on the ixpfx feed? Is there no coherence checking at all?

**Comment by arnoldnipper** [comment]
@eloos , there is no such thing as an ixpfx feed. There are actually two issues

 * IXes having no ixlan entry are not selectable for adding

 * Add coherence checking if there is an ixpfx record

**Comment by grizz** [comment]
@arnoldnipper exactly -- does the AC want to take on the task of getting correct prefix info into everything? Otherwise I think we should fix the not addable first.

**Comment by arnoldnipper** [comment]
@grizz / @eloos , yes AC will take care

**Comment by grizz** [comment]
Sounds good, let's do this and I'll close #73

**Comment by grizz** [comment]
Oh, one more thing to review, we'll only enforce this on edit / add new to start with, and do another ticket for existing data validation, make sense?

**Comment by eloos** [comment]
@grizz yes that makes sense, I assume @arnoldnipper already knows which ones need to be cleaned up

**Comment by arnoldnipper** [comment]
Now all IXes have at least one ixpfx to check against. Would be great to have this feature now to keep the DB clean. Old entries still have to be cleaned up though

**Comment by arnoldnipper** [comment]
Could we please move on here. This would greatly improve data quality.
