### ISSUE TITLE
Renumber IP space for an entire IX LAN tool

### ISSUE THREAD

**Issue by job** [peeringdb/peeringdb#80]
Sometimes an internet exchange renumbers its peering lan prefix into a bigger prefix. Common practise is to renumber all PDB entries in one go.

Best practise for an IXP is to renumber the range leaving the least significant bits as they were. In other words, the recent INEX renumbering was essentially this operation: `s/193.242.111.x/185.6.36.x/`

It would be nice if there is a tool to help with such a renumbering, manually changing all entries through the `/cp` interface is meh.

**Comment by vegu** [comment]
a command line tool for this exists already, however if we want to expose it to support staff we'll need to implement a UI for it as the cli is only available to server admins.

**Comment by grizz** [comment]
I think it's fine as is since it doesn't happen often, @job?

**Comment by job** [comment]
if i and arnold have access to the CLI tool its good enough.

how do i use it?

**Comment by grizz** [comment]
Need to add docs for this

**Comment by grizz** [comment]
@job FYI, we can do this manually in the interim if you need it done

**Comment by vegu** [comment]
fixed in d6037f44 - we ended up giving it a UI in the control panel, i will send instructions to admincom when we roll it to beta.
