### ISSUE TITLE
Extend Advanced Search for IXes and Facilities

### ISSUE THREAD

**Issue by mcmanuss8** [peeringdb/peeringdb#802]
Specifically add three related and complementary features. If there's disagreement on these, we can split into multiple issues. I view them all as for the same use cases, so bundling them together. Several of these are blocked by #799 and #800 

Brief use cases:
a) As a network, I want to find IXes and Facilities to join that I'm not already at, that meet my network's requirements and where I can meet Networks of mutual interest. 

Suggested features:

1) For logged in users, add a "My Organization is <dropdown> at". The dropdown should have options for:
- doesn't matter (default)
- present
- not present

Default value is to not care about this. If present, look to see if the user's organization's networks or IXes or Facilities are in that IX or Facility and filter results appropriately. Similarly for not present, but in reverse.

2) Add a "With X much capacity" for IXes, "With X much space" and "With X much power" for Facilities. 
In all of these cases you would have a numeric field and then a corresponding field next to it with a dropdown for units:
- Default to Gbps for IX
- Square meters for space
-  kW for facilities

3) Add a "With {all|any|none} of these networks are present" for IXes and Facilities. 
- Give a dropdown for the type of query the user wants to do with options: All, Any, or None. All requires all networks they select to be in a given IX or Facility. Any will match an object if any one (or more) of the networks they select is present. None will only match IXes and Facilities where none of the selected networks are present
- Give a multi-select typeahead search for networks and allow the user to type out networks (like "ABC Net", "XYC Inc"). Consider appending the ASN to the name in the the displayed value to both make it easier to confirm the results for the user and make the typeahead simpler (so I can type 32934 and get Facebook, for example)

**Comment by arnoldnipper** [comment]
+1

**Comment by as44980** [comment]
Personally I would support 1) & 3) and use them if implemented.

However I foresee dragons lurking behind 2), especially the danger that PeeringDB is treated as some sort of colo market place...  unless of course that is what the users want? ;)

**Comment by arnoldnipper** [comment]
@peeringdb/pc, please make up your mind

**Comment by leovegoda** [comment]
I'd like some input from the @peeringdb/pc on this. Rather than get into feature specifics, I'd like to check if people would be happy with building more into search based on number or type of networks present at a facility or IX?

**Comment by job** [comment]
+1

**Comment by kaycliff** [comment]
+1 

I think this is a great idea. However, my only concern is smaller exchange points that are still growing getting excluded due to these searches.

**Comment by egfrank** [comment]
**Summary**
- Add "My organization is at" filter which will give users the choice to filter (both by inclusion and by exclusion) if the user's organization's networks or IXes or Facilities are in that IX or Facility
- Add a "With X much capacity" for IXes, "With X much space" and "With X much power" for Facilities
- Add a "With {all|any|none} of these networks are present" for IXes and Facilities, with a dropdown for {all|any|none} and a autocomplete search bar for network

**Comment by arnoldnipper** [comment]
@egfrank and @peeringdb/pc inlight of our discussion I would like to add
**Summary**
- Add "My organization is at" filter which will give users the choice to filter (both by inclusion and by exclusion) if the user's organization's networks or IXes or Facilities are in that IX or Facility
- Add a "With X much capacity" for IXes, "With X much space" and "With X much power" for Facilities
- Add a "With {all|any|none} of these networks are present" for IXes and Facilities, with a dropdown for {all|any|none} and a autocomplete search bar for network
- When searching for a city for an IX also take into account `ixfac.city`

**Comment by egfrank** [comment]
One question, for the first search ( My Organization is at...) we have some users who belong to multiple organizations. For that search, would we like to provide an option to chose one of their organizations? Or would it include all ix / facilities within to any of their organizations?

**Comment by grizz** [comment]
Drop down for their orgs is fine.

**Comment by arnoldnipper** [comment]
> Drop down for their orgs is fine.

plus one for **all**

**Comment by kaycliff** [comment]
+ 1
Also a search within the drop down would be helpful.
