### ISSUE TITLE
Searching for a user in /cp/peeringdb_server/userorgaffiliationrequest results in 500

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/peeringdb#803]
https://peeringdb.com/cp/peeringdb_server/userorgaffiliationrequest/?q=lmanu gives me a "Server Error (500)"

**Comment by vegu** [comment]
```
FieldError at /cp/peeringdb_server/userorgaffiliationrequest/
Related Field got invalid lookup: icontains
```

Search filters setup incorrectly

**Comment by arnoldnipper** [comment]
> Search filters setup incorrectly

@vegu what does that mean? User error? Or bug?

**Comment by shane-kerr** [comment]
In general it should not be possible for a user to create a situation that results in a 500 error. Of course misconfiguration on the administrator side can cause this. So I guess this is a bug and should be handled as such.

**Comment by vegu** [comment]
@arnoldnipper bug - i just worded my explanation poorly, which meant that the search filters are wired up incorrectly in the code
