### ISSUE TITLE
[beta] IX-F importer: manual add followed by IX-F prompted add can result in "The server rejected your data"

### ISSUE THREAD

**Issue by ccaputo** [peeringdb/peeringdb#807]
If I start with this:

<img width="589" alt="Screen Shot 2020-08-11 at 9 30 36 AM" src="https://user-images.githubusercontent.com/1417833/89923404-65b2c680-dbb5-11ea-90d4-3d16465226d5.png">

and then I manually add just a portion of the suggestion with my own typing:

<img width="584" alt="Screen Shot 2020-08-11 at 9 32 18 AM" src="https://user-images.githubusercontent.com/1417833/89923570-a4488100-dbb5-11ea-9954-904a546198f5.png">

such that I now have:

<img width="573" alt="Screen Shot 2020-08-11 at 9 32 47 AM" src="https://user-images.githubusercontent.com/1417833/89923597-ae6a7f80-dbb5-11ea-87c7-ed165a02560b.png">

clicking Auto-add or Add at this point results in:

<img width="588" alt="Screen Shot 2020-08-11 at 9 33 49 AM" src="https://user-images.githubusercontent.com/1417833/89923679-ca6e2100-dbb5-11ea-867b-e803169c353c.png">

While this may be an unlikely sequence of steps, it may be worth fixing.

**Comment by vegu** [comment]
I agree that this is awkward, not sure what a good fix for this would be or how commonly it would happen.

One way i can see is checking after manually adding if one of the ips added matches the ip in a hint and then dismissing that hint?

**Comment by ccaputo** [comment]
> One way i can see is checking after manually adding if one of the ips added matches the ip in a hint and then dismissing that hint?

Keep in mind I only manually added the v4 addr in the test above.  It might have behaved differently if I had manually added both v4 & v6 addrs, like the hint.

Also, I wonder if this is related to https://github.com/peeringdb/peeringdb/issues/808 .  Ie., if the actual add didn't happen until Save was clicked, then the code would have a chance to re-assess whether the hint remains valid.  In fact, using the hint after manually adding but prior to the Save, could simply update what would be saved should the Save get clicked.

**Comment by arnoldnipper** [comment]
@ccaputo is this issue still relevant?

**Comment by ccaputo** [comment]
> @ccaputo is this issue still relevant?

Yes.

**Comment by egfrank** [comment]
**Summary**
- When manually adding a netixlan hide any ix-f suggestions posed by the UI if they are an exact match to the entry added

**Comment by ccaputo** [comment]
> **Summary**
> 
> * When manually adding a netixlan hide any ix-f suggestions posed by the UI if they are an exact match to the entry added

I don't think that is an accurate summary.  In the example, I added something different than the hint.  My sense is that #808 would make sense to address ahead of this issue.

**Comment by vegu** [comment]
@ccaputo looks like your response here was missed, apologies. I do agree that having #808 solved for this would likely be helpful.

As this ticket was selected for implementation this month in order to move things along, i want to try to propose a more accurate summary, please let me know if this seems workable for you:

**summary**

- when manually adding a netixlan, blank the matching ipaddresses in all ix-f suggestions  
- if a suggestion ends up with no ipaddresses, hide the suggestion entirely
 
thanks
