### ISSUE TITLE
[beta] IX-F importer: notice about dismissed hints remains after no longer relevant

### ISSUE THREAD

**Issue by ccaputo** [peeringdb/peeringdb#809]
If I have a hint:

<img width="589" alt="Screen Shot 2020-08-11 at 10 21 54 AM" src="https://user-images.githubusercontent.com/1417833/89928530-d0b3cb80-dbbc-11ea-93d5-fec293dd1759.png">

and then I dismiss it:

<img width="574" alt="Screen Shot 2020-08-11 at 10 22 48 AM" src="https://user-images.githubusercontent.com/1417833/89928544-d4dfe900-dbbc-11ea-96e4-3464f47fcf85.png">

The notice about the dismissed hint remains even if I resolve the issue manually:

<img width="567" alt="Screen Shot 2020-08-11 at 10 27 23 AM" src="https://user-images.githubusercontent.com/1417833/89928859-47e95f80-dbbd-11ea-8dd4-b33e195613d4.png">

A re-run of the IX-F Importer clears the old hint, so it may be this is a bug that is not worth fixing, since the daily run of the importer will take care of it.

Assigning to @vegu to determine if this is an easy fix.

**Comment by vegu** [comment]
The importer is the process that eventually confirms and deletes the resolved hint, so that part is by design. However we should be ignoring dismissed hints that have a noop action at the time of page load, which should be pretty quick to fix.

**Comment by grizz** [comment]
Fast track to 4 (clear bug).

**Comment by ccaputo** [comment]
Mostly fixed with 2.21.0.6.  (A refresh of the page is needed after the Save, in order for the notice about "Reset Suggestions" to disappear.)

**Comment by ccaputo** [comment]
> Mostly fixed with 2.21.0.6. (A refresh of the page is needed after the Save, in order for the notice about "Reset Suggestions" to disappear.)

Another time I tested this, I didn't need to do a refresh.
