### ISSUE TITLE
duplicate tickets opened for user approval

### ISSUE THREAD

**Issue by grizz** [peeringdb/peeringdb#81]

**Comment by grizz** [comment]
Looks like a failure on deskpro to combine tickets with the same subject (resulting from separate user requests).

@arnoldnipper has a ticket open with Deskpro

**Comment by job** [comment]
this can move to https://github.com/peeringdb/admincom/issues

**Comment by grizz** [comment]
Issue moved to [peeringdb/admincom #4](https://github.com/peeringdb/admincom/issues/4) via [**ZenHub**](https://www.zenhub.com/)
