### ISSUE TITLE
Get rid of the 'Protocols supported' fields / UI for IXes

### ISSUE THREAD

**Issue by ynbrthr** [peeringdb/peeringdb#810]
Axe the 'Protocols supported' field: proto_unicast, proto_multicast, proto_ipv6.

Some IXPs have a discrepancy between those fields and the address families available on the platform (ixpfx).

Alternatively, we can keep proto_unicast and proto_ipv6 and populate them from ixpfx's protocols

**Comment by arnoldnipper** [comment]
+1 ... and axe them as they contain redundant information. These fields come from v1 which did not have the `ixpfx` object

**Comment by shane-kerr** [comment]
+1

I'm fine with removing them.

**Comment by mcmanuss8** [comment]
+1

**Comment by as44980** [comment]
> Alternatively, we can keep proto_unicast and proto_ipv6 and populate them from ixpfx's protocols

I would support this approach as not only does it avoid removing a feature that at least some users may find useful, it also improves the data quality by making it much more likely to be accurate than the current self-declared values...

And perhaps if, similar to the extra advanced search functionality proposed in #802 , a user could filter the results of an IX search based on supprting IPv4 and/or IPv6?

**Comment by vegu** [comment]
**Summary**
- remove `proto_unicast`, `proto_multicast`, `proto_ipv6 `fields from `ix` UI
- fields remain in the v2 api but  `proto_ipv6` and `proto_unicast` will be populated from the existance of protocols in the exchange's ixpfx records. `proto_multicast `will be set to `true`
- fields to be dropped from the v3 api

**Comment by arnoldnipper** [comment]
1 Question, 1 Remark

 Q: Why do we set `proto_multicast` to `true`? Currently, we have  666 false and 148 true

 R: fields `proto_{ipv6,unicast,mulitcast}` are read only

**Comment by egfrank** [comment]
Checking in on this, @peeringdb/pc , as I'm going to be implementing this soon.

How should we set `proto_multicast` ?

**Comment by arnoldnipper** [comment]
Leave `proto_multicast` as is, @vegu and @egfrank
