### ISSUE TITLE
[beta] IX-F importer: [showstopper]: Add fails outright when no protocol is selected

### ISSUE THREAD

**Issue by ccaputo** [peeringdb/peeringdb#811]
Scenario when no protocols are enabled by a network...

When IX-F JSON data lists a network and it is missing from PeeringDB, the IX-F Importer creates:

<img width="793" alt="Screen Shot 2020-08-11 at 10 43 21 AM" src="https://user-images.githubusercontent.com/1417833/89930513-b8917b80-dbbf-11ea-8537-483a74404e95.png">

But when a user views the hint, the IP addresses are missing when no Protocols are enabled:

<img width="1173" alt="Screen Shot 2020-08-11 at 10 43 37 AM" src="https://user-images.githubusercontent.com/1417833/89930521-bd562f80-dbbf-11ea-98e5-680f0feab803.png">

And the Add or Auto-add fails with "The server rejected your data":

<img width="585" alt="Screen Shot 2020-08-11 at 10 44 02 AM" src="https://user-images.githubusercontent.com/1417833/89930536-c0e9b680-dbbf-11ea-907a-986713dd076c.png">

This is a showstopper, in my opinion.  If no protocol is selected, I think we decided that implies both are assumed enabled.  (I do note that when one or both protocols are enabled, the adds work fine.)

**Comment by arnoldnipper** [comment]
> I think we decided that implies both are assumed enabled

Confirmed. If no protocol is selected we assume that the network supports `proto_{unicast,ipv6}`

**Comment by vegu** [comment]
Bug confirmed - seems to be on the UI side - it is actually registering it as supporting both, which is why the suggestion shows up in the first place, but the UI is bugging out when filling them in.

**Comment by grizz** [comment]
Fast track to 4 because clear bug.

**Comment by ccaputo** [comment]
Fix confirmed in 2.21.0.6.
