### ISSUE TITLE
Suppress RDAP call for contact data/handles for NIC.br // AUTOTOOL

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/peeringdb#814]
Brazil has put in place a data protection law called LGPD (see e.g. https://gdpr.eu/gdpr-vs-lgpd/). Due do this law NIC.br does not return any data for handles.

Please modify AUTOTOOL to suppress calls for NIC handles from rdap.registro,br

@peeringdb/pc this affects @peeringdb/ac only

**Comment by alexfguimaraes** [comment]
Perhaps this law protection, also doesn’t return any RDAP query and it can affect tests results after the PeeringDB update.

**Comment by peterhelmenstine** [comment]
Well that's unfortunate, for authenticating... so RIPE doesn't do this with GDPR. Wish they would get on the same page...

**Comment by grizz** [comment]
@arnoldnipper have you escalated this through nic.br for possible work arounds?

**Comment by arnoldnipper** [comment]
Julimar from @peeringdb/ac (also NIC.br) talked to registro.br and their answer was:

```
For reasons of a personal data protection law, it was necessary to remove these consultation options and that the RDAP will be adjusted to not provide the link for this type of query.
```

What would be a workaround in your eyes, @grizz ?

**Comment by peterhelmenstine** [comment]
So that argument says there's no reason to have a contact for someone participating to be on the internet, which isn't that against what ICANN instructs? Keeping current contact info current?

**Comment by netravnen** [comment]
"Funny" thing is a standard query for a LACNIC administered ASN still returns the aut-num and entity information (using ~/go/bin/rdap). Querying the entity directly outputs the 'no data' mentioned earlier...

**Comment by alexfguimaraes** [comment]
Registro.br answer for Brazilian designation thats runs under Brazilian
Laws.... LACNIC return the generic identification of the ASN, when you
start dig information, you will land at Registro.br, where "sensitive" data
is hidden.

the "most funny" thing is, in the Rio de Janeiro and Sao Paulo streets, you
can buy all personal data(financial, address, id)... from all brazilian
people...

These law have been applied due political reasons. Not to protect the
people.

att
Alexandre

**Comment by arnoldnipper** [comment]
@vegu / @grizz do we have a quick workaround for this?

**Comment by alexfguimaraes** [comment]
Doesn't work either, i just did some tests and LacNic[1] return less info
than Registro/Whois[2] itself.

[1] https://rdap-web.lacnic.net/autnum/52925
[2] https://registro.br/tecnologia/ferramentas/whois/?search=52925



att
Alexandre

**Comment by arnoldnipper** [comment]
@vegu or @egfrank is there a need to look up the handle? Doesn't the call for the asn also return handle information?

**Comment by grizz** [comment]
I think @peterhelmenstine might be correct that it's against ICANN rules, but I don't know. Regardless of anything else, they're the only ones doing it and it's breaking things, so it would seem like the correct solution would be putting pressure on them, which I've had little luck with in the past.

LACNIC, for example, has an elegant solution of requiring an APIKEY so legitimate groups can get all the information.

I have no idea about a work around, is that information available anywhere else?

**Comment by arnoldnipper** [comment]
> I have no idea about a work around, is that information available anywhere else?

@20c, I get the information if I query the ASN via https://rdap.org/autnum/$ASN (.entities[0].entities[0].vcardArray[1][3][3], resp. .entities[1].vcardArray[1][3][3]). Hope that helps

**Comment by grizz** [comment]
Ahh, so it's just on the object entities instead of the handles, I see. We can get the emails from that then, yes.

**Comment by arnoldnipper** [comment]
@pc jfyi that I've moved this issue forward to 3a as this is only impacting @peeringdb/ac

**Comment by grizz** [comment]
This will just need some playing with to find the best way to query that data without breaking the other RIRs, moving to 4

**Comment by arnoldnipper** [comment]
This still is broken. See [DeskPRO ticket](https://peeringdb.deskpro.com/agent/#app.tickets,inbox:unassigned,t.o:50435,vis:6)

**Comment by grizz** [comment]
Hrm, thought I replied to this in email already, that's a new error, 403, we can add that to the allowed failures as well.

**Comment by arnoldnipper** [comment]
> we can add that to the allowed failures as well.

Do you?
