### ISSUE TITLE
[beta] IX-F importer: [showstopper]: Seeing 'Update' hint instead of 'Add' hint

### ISSUE THREAD

**Issue by ccaputo** [peeringdb/peeringdb#816]
At https://beta.peeringdb.com/net/20575 at Update hint is being presented rather than an Add hint for SkyIX HK:

<img width="1178" alt="Screen Shot 2020-08-15 at 10 54 50 AM" src="https://user-images.githubusercontent.com/1417833/90318514-d32c6300-dee5-11ea-9e03-dbcd81281332.png">

Since https://beta.peeringdb.com/ix/3180 doesn't show this network:

<img width="1168" alt="Screen Shot 2020-08-15 at 10 57 05 AM" src="https://user-images.githubusercontent.com/1417833/90318543-14247780-dee6-11ea-9b28-c56cb9c1226b.png">

the hint should be an Add, not an Update.

**Comment by vegu** [comment]
Having no immediate success reproducing this locally, but can confirm the issue exists on beta and appears to be an edge case related to the changes introduced in #770

**Comment by grizz** [comment]
Fast track (clear bug).

**Comment by ccaputo** [comment]
Fix confirmed in 2.21.0.6.
