### ISSUE TITLE
[beta] IX-F importer: list of hints should be case-independently sorted alphabetically

### ISSUE THREAD

**Issue by ccaputo** [peeringdb/peeringdb#817]
The list of hints should be case-independently sorted alphabetically.  At present an example looks like this:

<img width="582" alt="Screen Shot 2020-08-15 at 11 08 55 AM" src="https://user-images.githubusercontent.com/1417833/90318784-bc870b80-dee7-11ea-9376-35d55cdf790a.png">

**Comment by grizz** [comment]
Fast track, clear bug.

**Comment by ccaputo** [comment]
Fix confirmed (2.21.0.6).
