### ISSUE TITLE
Sorting search results by traffic level is not in numerical value order

### ISSUE THREAD

**Issue by jwbensley** [peeringdb/peeringdb#82]
When using the advanced search and sorting the results by Traffic Levels the results are in numerical character order not numerial value order.

500-1000Gbps comes first in my search results, then 50-100Gbps, then 300-500Gbps.
![search terms](https://cloud.githubusercontent.com/assets/1025875/20518166/0b7ff956-b096-11e6-8c4a-a8c2a0d44ac2.png)
![stiched search results](https://cloud.githubusercontent.com/assets/1025875/20518167/0b8a40fa-b096-11e6-8597-fb758e571215.png)

**Comment by vegu** [comment]
thanks for the report, labeled as bug

**Comment by vegu** [comment]
fixed in f0f572f

**Comment by jwbensley** [comment]
Thanks!
