### ISSUE TITLE
ability for Networks to advise on scope of prefixes they may send to route-servers

### ISSUE THREAD

**Issue by as44980** [peeringdb/peeringdb#822]
While most networks announce "all" of their prefixes to route-servers, and a small number (perhaps 10 or so? :wink:) networks who wish for "none" of their prefixes to be advertised to route-servers.. 

I noticed some examples of networks who may wish to announce a limited subset of their prefixes to route-servers, such as [as14340](https://www.peeringdb.com/net/1100) who advise that the "will only send prefixes for a given continent/region to route servers"

So wondered if there was any value in having a user defined field for "Prefixes announced to route-servers" with a small number of values such as:

`None`
`City`
`Country`
`Region` 
`All`

This would allow networks to search for peers who they may presently see 'some' prefixes via route-servers, but could potentially receive more prefixes with bilateral sessions...

Which in turn I suspect would help increase the volume of traffic which goes via peering, and thus facilitating better interconnection :smile:

**Comment by arnoldnipper** [comment]
This then would be an additional field in the `netixlan` record? If so, why then not have a per IX IRR as-set/route-set?

**Comment by job** [comment]
This has been discussed before, PeeringDB should probably not dip its toes too deep into attempting to define routing policy languages. This is work to be taken on in the IETF

**Comment by as44980** [comment]
> This has been discussed before, PeeringDB should probably not dip its toes too deep into attempting to define routing policy languages. This is work to be taken on in the IETF

Surely the horse has bolted on that one since #394 was implimented, are we now trying to close the barn doors? ;)

**Comment by as44980** [comment]
> This then would be an additional field in the `netixlan` record? If so, why then not have a per IX IRR as-set/route-set?

On the basis of having seen at least some networks with policies which appear specific to "route servers" in general, whether that is that only a limited scope of prefixes would be announced or that they prefixes should never be visible via route servers, so I was imagining this would most likely apply to the net record rather than on a per-IX basis.. 

Similar to the "Never via route servers" flag, but perhaps in terms of UI location it might make more sense to place this as an additional row in the "Peering Policy" section rather attempting to squeeze this into the "Protocols Supported" row?

**Comment by arnoldnipper** [comment]
> On the basis of having seen at least some networks with policies which appear specific to "route servers" in general, whether that is that only a limited scope of prefixes would be announced or that they prefixes should never be visible via route servers, so I was imagining this would most likely apply to the net record rather than on a per-IX basis..

Would then splitting the "IRR as-set/rs-set" into two fields make sense? One for bilateral peering and on for peering across exchanges? Is that your proposal?

**Comment by arnoldnipper** [comment]
@pc, please vote

**Comment by arnoldnipper** [comment]
-1 from me as well ... @pc, please work on this.

**Comment by as44980** [comment]
> Would then splitting the "IRR as-set/rs-set" into two fields make sense? One for bilateral peering and on for peering across exchanges?

From what I can see there are few, if any, networks who have a dedicated AS-SET to describe their announcements at some or all IX's they peer on...

However there are networks who intentionally announce _just_ a subset of their prefixes to IX route-servers, perhaps just those from a specific geography.

Based on this observation it appears this approach would require an AS-SET per IX, and from the lack of consensous in #607 this doesnt appear practical, even if it was a good idea...

So for clarity, this is not what I have proposed...

**Comment by as44980** [comment]
> Is that your proposal?

No, as per the original issue I propose

>having a user defined field for "Prefixes announced to route-servers" with a small number of values such as:
>
> None
> City
> Country
> Region
> All

> This would allow networks to search for peers who they may presently see 'some' prefixes via route-servers, but could potentially receive more prefixes with bilateral sessions...

I would propose that an additional row is added to the "Peering Poliocy Information" section which is titled "Prefixes announced to route-servers", "Scope of route-server announcements" or similar.

This would allow networks to programatically express policies which are currently described in the notes section such as "will only send prefixes for a given continent/region to route servers"...

And consequently other network who use PeeringDb to identify potential bilateral peering sessions could parse the fact this network announces only a subset of their prefixes to route-servers, and thus could prioritse establishing a bilateral session.

As a bonus this feature would allow any of the very small number of networks who feel their prefixes should "Never [be announced] via route servers" could set the value for this new "Prefixes announced to route-servers" field to "None"...

So hopefully as #394 was implemented to suit a minority of networks who consider themselves "transit free" then perhaps this additional functionality could be added to help improve PeeringDB for the vast majority of networks who dont fall into this club?

**Comment by ynbrthr** [comment]
-1

**Comment by wmarantz** [comment]
I support the routing advertisement scope proposal but have no idea how often it will be used.  Is usage data available for features such as never via route server based on API queries? 

There are still global SaaS or content networks that do not operate an anycast or IP geolocation based edge service. These networks may want to peer as widely as possible but may need to ensure the peering does not massively impact latency. Many APAC networks are on route servers in Europe and/or the USA, but won't connect to route servers in APAC, don't have wide IX coverage in APAC, or have other latency factors around the vast distances involved in APAC. The content network would not want to peer global prefixes on the route servers in Europe to have packets travel from APAC to a route server peer in Europe and then back to APAC. The peeringDB option to specify a regional only policy on route servers would be beneficial to these content networks and would hopefully encourage networks with a sane latency aligned topology to bilaterally peer with the content network to receive full routing scope.

Maybe this type of content network is a true corner case, but I'm hoping the proposal would help grow peering.

**Comment by grizz** [comment]
Closing from consensus.

**Comment by as44980** [comment]
I am unsure I understand this opaque process for reaching "consensus"...

There look to be plenty of other examples like this where PeeringDB users propose things that they feel would help enhance the platform and potentially enable more peering, taking the time to clarify their proposals and engage with the community..

Then some other folks come along to simply add "-1", with no indication they have necessarily even taken time to read or consider the proposal.

At which point the attempts to improve things are torpedoed, and likely to be referenced to shut down any future suggestions which might sound slightly related.

Perhaps we could have some accountability here like a clear process for feature requests, and an ability to demonstrated that these are treated fairly regardless of whom they are proposed by?

**Comment by as44980** [comment]
> Maybe this type of content network is a true corner case, but I'm hoping the proposal would help grow peering.

Thanks for taking the time to share your feedback, and as you mention the "never via route server" feature it seems that being a corner case is far from a barrier to being included as a feature request!

**Comment by arnoldnipper** [comment]
> Perhaps we could have some accountability here like a clear process for feature requests, and an ability to demonstrated that these are treated fairly regardless of whom they are proposed by?

As I am the shepherd of this issue. The [decision making process and workflow](https://docs.peeringdb.com/committee/product/#decision-making-process-and-workflow) is one of the oldest and best documented process within PeeringDB. Besides the public document there is an internal one to guarantee that all PC members know what to do and to have consistent quality when members go out and new come in.

Please see our [Dispute Resolution](https://docs.peeringdb.com/committee/product/#peeringdb-product-committee-charter) if you are unhappy about what we do.
