### ISSUE TITLE
IX-F Preview - shows the consolidated delete operation when it shouldn't

### ISSUE THREAD

**Issue by vegu** [peeringdb/peeringdb#824]
Originally mentioned in #770 

![Screenshot 2020-08-24 at 17 45 20](https://user-images.githubusercontent.com/143124/91058822-9c66f300-e631-11ea-988a-e557265c33c6.png)

The delete operation is already included in the consolidated modify and should be hidden from the user.

**Comment by ccaputo** [comment]
@mcmanuss8 & @grizz: I don't consider this a showstopper, but I do think it should be prioritized for the next beta release.

**Comment by arnoldnipper** [comment]
@vegu / @grizz ... I guess this will be fixed with the next release. Right? And as this issue was tagged as a bug by a developer I've moved it to 3a

**Comment by ccaputo** [comment]
Fix confirmed in beta 2.22.1.3 by manually running Importer on ix/984 and then running Import Preview.  Preview now shows a simple "Modify", which matches the hint on the network page in this example.
