### ISSUE TITLE
[beta] IX-F importer: Make Importer return non-zero when there is an error that Ops should see

### ISSUE THREAD

**Issue by ccaputo** [peeringdb/peeringdb#825]
As far as I can tell, at present, the IX-F JSON Importer has an exit status of zero even when a particular import fails.  Since Ops normally runs the importer wrapped with chronic, errors indicated to stdout or stderr can be missed due to this.  Thus a change is needed to make the exit status be non-zero if any import fails or has an error, or for that matter if there are any notices that Ops should become aware of.

As an example, the errors noted at https://github.com/peeringdb/peeringdb/issues/795#issuecomment-677725600 might have been missed had I not manually run the importer.

The robustness of the Importer should not be changed by this.  Ie., it should continue to run as it does now, when a single import fails.

@grizz & @job I have marked this as Ready for Implementation.  Please override if I am wrong to do so.

**Comment by ccaputo** [comment]
@mcmanuss8 & @grizz: I don't consider this a showstopper, but I do think it should be prioritized for the next beta release.

**Comment by vegu** [comment]
** Specifications **

We need to tackle two main issues here 

1. When importer command is done return a non-zero exit code if we had any unhandled error (e.g the email import issue we fixed in #831) at the end of the import run
2. Output those errors at the end of the run

I think we can accomplish both by collecting those errors and simply re-raising them at the end of the run serving both purposes of outputting the error information as well as causing the importer command to exit with non-zero return code.

**Comment by arnoldnipper** [comment]
Where is the error report going to? May I suggest to include @peeringdb/ac and flag the report appropriately?

**Comment by ccaputo** [comment]
> Where is the error report going to? May I suggest to include @peeringdb/ac and flag the report appropriately?

My intention when I created this issue is that the error report go to stderr or stdout and get handled by Ops.  This is not about IX-F JSON errors so much as about the operational functioning of the Importer itself, such as the mailer failing to work due to an issue with the cloud provider.  Ops will forward issues to @peeringdb/ac when it makes sense to, but Ops needs to find out immediately when the Importer is having an operational problem.

**Comment by ccaputo** [comment]
> > Where is the error report going to? May I suggest to include @peeringdb/ac and flag the report appropriately?
> 
> My intention when I created this issue is that the error report go to stderr or stdout and get handled by Ops. This is not about IX-F JSON errors so much as about the operational functioning of the Importer itself, such as the mailer failing to work due to an issue with the cloud provider. Ops will forward issues to @peeringdb/ac when it makes sense to, but Ops needs to find out immediately when the Importer is having an operational problem.

I have inquired about having DeskPro tickets be created for @peeringdb/ac issues such as bad IX-F JSON data or bad URLs, while Ops gets informed about the more operational stuff.  Stay tuned...

**Comment by ccaputo** [comment]
@arnoldnipper, can you speak to your thoughts about this ticket with respect to your comment https://github.com/peeringdb/peeringdb/issues/794#issuecomment-667363742 ?  The code to create a DeskPro ticket for an IX-F JSON error is currently commented out at https://github.com/peeringdb/peeringdb/blob/master/peeringdb_server/ixf.py#L1643 due to #794.  Thanks.

**Comment by arnoldnipper** [comment]
If the IX gets informed then there is no need to open a DeskPRO ticket
