### ISSUE TITLE
Make GUI and API feature equivalent

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/peeringdb#827]
In short

 * What can be done via GUI, should be doable via API and vice versa
 * What is visible via GUI, should be visible via API and vice versa

example: it is possible to [suggest an exchange via API](https://www.peeringdb.com/apidocs/#operation/create%20ix), but the GUI pendant is missing. So, either add this feature to the GUI or disable creation via API

@pc, what do you think?

**Comment by shane-kerr** [comment]
+1

I'm happy with either:

1. The API being able to do everything, and the GUI being a subset of those features, or
2. The API and the GUI being feature equivalent (as proposed in this issue).

I suppose there may be users who are not comfortable with `curl` so would prefer to never have to use the API. Until we actually have a situation where it's _hard_ to implement something in one but not the other, feature-equivalency seems reasonable.

**Comment by ynbrthr** [comment]
agreed, +1

**Comment by grizz** [comment]
I agree with Shane, for implementation, we'll need a list of things to change.

**Comment by leovegoda** [comment]
> I agree with Shane.
> 
> For implementation, we'll need a list of things to change.

Can that list be derived from documentation?

**Comment by arnoldnipper** [comment]
> > I agree with Shane.
> > For implementation, we'll need a list of things to change.
> 
> Can that list be derived from documentation?

You are kidding, @leovegoda :)

**Comment by leovegoda** [comment]
If there's an agreement in principle but the documentation does not describe the current situation, do we have data from support tickets to help us identify what should be prioritized?

**Comment by grizz** [comment]
Arnold makes a good point and highlighted the "Suggest an IX" *feature* available via the API. I think that should be removed as we previously decided against allowing to suggest an IX. Besides that, I'm not sure of what else there is to tackle. So

**Summary**
Remove suggest an IX from the API

**Comment by arnoldnipper** [comment]
**Summary**
 - Remove suggest an IX from the API
 - add "Public Peering Info Updated"
 - add "Peering Facility Info Updated"
 - add "Contact Info Updated"
 
 The update information has been rolled out with release 2.25.0 but is missing the API fields. Hence, back to 3a. Or do we need to push it back to 1, @peeringdb/pc?

**Comment by egfrank** [comment]
Hello @peeringdb/pc !

For this I wanted to ask if we should remove "suggest a Network" from the API as well. @vegu said that as far as he knew, only facilities should get the suggest feature.

**Comment by vegu** [comment]
@arnoldnipper looking athttps://www.peeringdb.com/api/net/?limit=1&pretty - the fields `netixlan_updated`, `netfac_updated`, `poc_updated` are there.

However due to an issue with cron-jobs api cache regeneration had not been running the 1 or 2 days after the rollout, hence cached responses would have been missing the fields.

**Comment by arnoldnipper** [comment]
> For this I wanted to ask if we should remove "suggest a Network" from the API as well. @vegu said that as far as he knew, only facilities should get the suggest feature.

@egfrank and @vegu: I'm also able to _suggest a network_ by affiliating to it. Iow: I don't have to be the legal owner to create a network. Maybe that's the reason why the `net` object still needs the `suggest` field.

**Comment by arnoldnipper** [comment]
> However due to an issue with cron-jobs the api cache regeneration had not been running for 1 or 2 days after the rollout, hence cached responses would have been missing the fields at that time.

Thanks for clarifying. I also noticed that above-mentioned fields are there, now.

**Comment by egfrank** [comment]
Hi @arnoldnipper, you moved this to 3a because of the `netixlan_updated` `netfac_updated` `poc_updated`  issue right? Can we now move it back to 4, in light of that being resolved?

Additionally the summary is now just:
- Remove suggest an IX from the API

**Comment by arnoldnipper** [comment]
> Hi @arnoldnipper, you moved this to 3a because of the `netixlan_updated` `netfac_updated` `poc_updated` issue right? Can we now move it back to 4, in light of that being resolved?

Exactly

**Comment by arnoldnipper** [comment]
**Release Notes**
PeeringDB has a GUI and an API. This issue is a reminder to keep both feature equivalent.
