### ISSUE TITLE
IX-F importer: Handle ipv4/ipv6 on same vlan but separate connections

### ISSUE THREAD

**Issue by vegu** [peeringdb/peeringdb#828]
Split out from #815 

Below is a summarization of the comments from #815 related to this issue

**@ccaputo writes:**

BKNIX currently has the following for Akamai:

```
            "connection_list": [
                {
                    "ixp_id": 1,
                    "state": "active",
                    "if_list": [
                        {
                            "switch_id": 2,
                            "if_speed": 10000
                        }
                    ],
                    "vlan_list": [
                        {
                            "vlan_id": 1,
                            "ipv4": {
                                "address": "203.159.68.40",
                                "as_macro": "AS-AKAMAI",
                                "routeserver": true,
                                "mac_addresses": [
                                    "ec:13:db:f0:37:f1"
                                ]
                            }
                        }
                    ]
                },
                {
                    "ixp_id": 1,
                    "state": "active",
                    "if_list": [
                        {
                            "switch_id": 2,
                            "if_speed": 10000
                        }
                    ],
                    "vlan_list": [
                        {
                            "vlan_id": 1,
                            "ipv6": {
                                "address": "2001:deb:0:68:0:a502:940:1",
                                "as_macro": "AS-AKAMAI",
                                "routeserver": true,
                                "mac_addresses": [
                                    "ec:13:db:f0:37:0c"
                                ]
                            }
                        }
                    ]
                }
            ]
```

Starting with:

![Screen Shot 2020-08-18 at 5 44 44 PM](https://user-images.githubusercontent.com/1417833/90579380-b2307000-e17a-11ea-90b5-1096e8ca1172.png)

Clicking Add results in "The server rejected your data":

![Screen Shot 2020-08-18 at 5 45 05 PM](https://user-images.githubusercontent.com/1417833/90579412-c7a59a00-e17a-11ea-91e6-28ce838082e1.png)

Clicking Accept and Save and then reviewing remaining BKNIX hints results in:

![Screen Shot 2020-08-18 at 5 48 50 PM](https://user-images.githubusercontent.com/1417833/90579516-1a7f5180-e17b-11ea-90db-cc9014ac526f.png)

Clicking Add and Save now works and results in two connections:

![Screen Shot 2020-08-18 at 5 49 57 PM](https://user-images.githubusercontent.com/1417833/90579561-48649600-e17b-11ea-836e-2b0edf5bb60c.png)

Since that matches the IX-F JSON data which shows two connections, the end result appears correct.  But we got here by persisting through a "The server rejected your data" message.  That is suboptimal.

Re-opening this in case it makes sense to combine the two operations in to a single operation that achieves the same result while forgoing the error.  (will remove "showstopper" from the issue name)

-----------
**@egfrank writes:**

Looking at the issue above, Vegu posted Finally, this is all on a per connection basis. So vlan ids shared across multiple connections in separate vlan_list lists are not aware of each other and wont result in any such combinations. and as far as I understand this example falls into that bucket.

What I'm seeing is that, at first, the user is not able to accept the first hint, because adding the connection with ipaddr4 = 203.159.68.40 would overlap with the existing connection with both ipaddr4=203.159.68.40 and ipaddr6=2001:deb:0:68:0:a502:940:1. Then, once they've taken the suggestion to update that existing connection to only set the ipaddr6, they are allowed to accept the "add" hint.

Because they are currently two separate hints, I'm taking that to mean that theoretically a user may choose to dismiss the "update" hint. In which case, that error message would remain meaningful. Likewise, I'm assuming that a user might want to dismiss the "add" hint and only update the existing connection.

If you don't think that a user would ever chose to only accept one of those hints, then it would make sense to consolidate them. I'm not 100% sure what this change would entail but I'd predict that, instead of the vlan_id sanitation referenced in this issue, it would involve the same requirement_of logic implemented in issue #770

----------
**@ccaputo writes:**

Even if a network has two circuits to an IX, one for IPv4 and one for IPv6, as far as PeeringDB goes, the network may prefer a single entry since there may be no desire to describe the actual topology. Thus a network that doesn't want to split the existing record into two records, would simply want to click Dismiss. But they would likely only expect to click a single Dismiss, not two.

Logically the above is a single hint, but it is presented as two hints. That is the bug. :-)

Like #770 it makes sense to combine related Add/Update into a single Update which makes clear what will happen. The network can then decide if this is something they want to do (split the record) or Dismiss it. Maybe a way to present this to the user would be to show the before and after appearance in some manner.

**Comment by egfrank** [comment]
**Summary**
- Compare vlan_ids across different connection entries in the ix-f data, to find if ip4 and ip6 address updates with the same vlan_id can be consolidated into a single suggestion

**Comment by egfrank** [comment]
Hi @ccaputo I want to make sure I understand what we're trying to do with this issue:
My understanding is that in your example:

```            "connection_list": [
                {
                    "ixp_id": 1,
                    "state": "active",
                    "if_list": [
                        {
                            "switch_id": 2,
                            "if_speed": 10000
                        }
                    ],
                    "vlan_list": [
                        {
                            "vlan_id": 1,
                            "ipv4": {
                                "address": "203.159.68.40",
                                "as_macro": "AS-AKAMAI",
                                "routeserver": true,
                                "mac_addresses": [
                                    "ec:13:db:f0:37:f1"
                                ]
                            }
                        }
                    ]
                },
                {
                    "ixp_id": 1,
                    "state": "active",
                    "if_list": [
                        {
                            "switch_id": 2,
                            "if_speed": 10000
                        }
                    ],
                    "vlan_list": [
                        {
                            "vlan_id": 1,
                            "ipv6": {
                                "address": "2001:deb:0:68:0:a502:940:1",
                                "as_macro": "AS-AKAMAI",
                                "routeserver": true,
                                "mac_addresses": [
                                    "ec:13:db:f0:37:0c"
                                ]
                            }
                        }
                    ]
                }
            ]
```

We could eventually just merge this down to 

```
"connection_list": [
    {
        "ixp_id": 1,
        "state": "active",
        "if_list": [
            {
                "switch_id": 2,
                "if_speed": 10000
            }
        ],
        "vlan_list": [
            {
                "vlan_id": 1,
                "ipv4": {
                    "address": "203.159.68.40",
                    "as_macro": "AS-AKAMAI",
                    "routeserver": true,
                    "mac_addresses": [
                        "ec:13:db:f0:37:f1"
                    ]
                },
                "ipv6": {
                    "address": "2001:deb:0:68:0:a502:940:1",
                    "as_macro": "AS-AKAMAI",
                    "routeserver": true,
                    "mac_addresses": [
                        "ec:13:db:f0:37:0c"
                    ]
                }
        ]
]

And we can do that because `connection state` and `if_list` values are identical? Is this what you had in mind?

What would we do in this case if the `state` or `if_list` values were different?
cc: @vegu

**Comment by ccaputo** [comment]
> And we can do that because `connection state` and `if_list` values are identical? Is this what you had in mind?

I _think_ so, but I'd really like @arnoldnipper to share his thoughts to make sure this path is good.

> What would we do in this case if the `state` or `if_list` values were different?

@arnoldnipper?

**Comment by arnoldnipper** [comment]
> > And we can do that because `connection state` and `if_list` values are identical? Is this what you had in mind?
> 
> I _think_ so, but I'd really like @arnoldnipper to share his thoughts to make sure this path is good.

This is safe to do.

> > What would we do in this case if the `state` or `if_list` values were different?

> @arnoldnipper?

If `if_list` values differ it's still safe to combine as from a peer pov it doesn't matter if IPv4 and IPv6 are on different interfaces. However, if `state` values are different there is no way to map this to anything meaningful in PeeringDB. 

Imho it makes sense to refine our `operational` field to `ipaddr4_operational` and `ipaddr6_operational`.  Does that make sense? @Job and others, what do you think?

**Comment by arnoldnipper** [comment]
**Release Notes**
This issue deals with how the IX-F importer handles information from the IX-F JSON import. PeeringDB handles both the IPv4 as well as the IPv6 address in the same object (`netixlan`). And from a peering partner pov this is ok as it doesn't matter whether these addresses are on the same interface or even same router. However, IX-F JSON differentiates. 

For the time being, the importer combines IPv4 and IPv6 if both are set to an operational status in the IX-F JSON.
