### ISSUE TITLE
API: Parameter fields for ixlan does not work anymore

### ISSUE THREAD

**Issue by empi89** [peeringdb/peeringdb#829]
In our automation we used to call https://peeringdb.com/api/ixlan/1812?fields=ixpfx_set. This api call returns http error code 500 now. Is this way to call the API considered deprecated?

**Comment by vegu** [comment]
@empi89 Not deprecated, looks like a bug rolled out with the 2.22 release that happened a couple hours ago stemming from the implementation of #249 

If you are able to authenticate during your api requests that seems to be a valid work around for now. 

We are still investigating the issue.

**Comment by vegu** [comment]
@empi89 a fix for this was rolled out in 2.22.1, and looks good from here - can you confirm it is also fixed on your end please.

**Comment by empi89** [comment]
Works again - Many thanks for fixing this in such an awesome speed!
