### ISSUE TITLE
Sync data inconsistent with PeeringDB data

### ISSUE THREAD

**Issue by martzuk** [peeringdb/peeringdb#83]
On https://www.peeringdb.com/ix/1249 I see the LAN IPv4 to be 206.53.202.0/24 and IPv6 to be 2001:504:61::/64 however in the database synced with the sync tool I see IPv4 as: 185.1.69.0/24 and IPv6 as 2001:7f8:18:210::/64

I deleted all the tables and re-ran the sync, but I see the same happen again.

mysql> select * from peeringdb_ixlan_prefix where ixlan_id=1249;
+-----+--------+---------------------+---------------------+---------+-------+----------+----------------------+----------+
| id  | status | created             | updated             | version | notes | protocol | prefix               | ixlan_id |
+-----+--------+---------------------+---------------------+---------+-------+----------+----------------------+----------+
| 730 | ok     | 2016-11-22 10:47:20 | 2016-11-22 10:47:20 |       0 |       | IPv4     | 185.1.69.0/24        |     1249 |
| 731 | ok     | 2016-11-22 10:47:20 | 2016-11-22 10:47:20 |       0 |       | IPv6     | 2001:7f8:18:210::/64 |     1249 |
+-----+--------+---------------------+---------------------+---------+-------+----------+----------------------+----------+
2 rows in set (0.00 sec)

**Comment by vegu** [comment]
the ixlan for ix 1249 has the id 1241, the ids of ix and ixlan are not always identical (actually the only identical ones are from the initial import from v1 to v2)

sqlite> select * from peeringdb_ixlan where ix_id=1249;
1241|ok|2016-03-22 15:40:48|2016-04-14 09:41:17|0|DE-CIX Dallas Peering LAN||1500||0|0||1249
sqlite> select * from peeringdb_ixlan_prefix where ixlan_id=1241;
724|ok|2016-03-22 15:41:02|2016-03-22 15:41:02|0||IPv4|206.53.202.0/24|1241
725|ok|2016-03-22 15:42:03|2016-04-14 20:32:36|0||IPv6|2001:504:61::/64|1241
