### ISSUE TITLE
IX-F Importer: Add failed email resending

### ISSUE THREAD

**Issue by egfrank** [peeringdb/peeringdb#833]
As mentioned in https://github.com/peeringdb/peeringdb/issues/831, we're splitting this out into a new issue. 

Currently, if a commit succeeds but the email fails, there is currently no mechanism to re-send that email on a second run. The logic to send an email is entirely dependent on notifications from the import process, and if the importer is re-run on the same data, no new notifications are produced.

To fix this bug, we need to implement email resending in the importer, which will require some speccing out and time on beta.

One thing we need to define is whether resending emails should check if the message being resent is actually still valid or not.

**Comment by ccaputo** [comment]
Reposting, since I don't think this is about "failed email resending" so much as about not-committing when email fails to send:

> > 1. I've confirmed that, like you stated, if a commit succeeds but the email fails, there is currently no mechanism to re-send that email on a second run. The logic to send an email is entirely dependent on notifications from the import process, and if the importer is re-run on the same data, no new notifications are produced. To fix this bug, we need to implement email resending in the importer, which will require some speccing out and time on beta.
> 
> I wonder it if makes sense to simply not commit to `ixfmemberdata` or other involved non-email tables when an email fails? That way, next time importer runs, it is a clean slate and the issue will be rediscovered. Ie.:
> 
> * create email in table for network (as appropriate) with sent == null
> * create email in table for ix (as appropriate) with sent == null
> * attempt to send network email and set `sent` if successful
> * attempt to send ix email and set `sent` if successful
> * if emails successful, commit changes to `ixfmemberdata` and any other involved tables

Furthermore, a failure that can't be logged anywhere else, such as preferably a DeskPRO ticket, should be logged to stdout.  Combined with https://github.com/peeringdb/peeringdb/issues/825 so that `chronic` doesn't hide the problem, this will enable Ops to be able to take action or at least be aware of the issue.

**Comment by ccaputo** [comment]
> Reposting, since I don't think this is about "failed email resending" so much as about not-committing when email fails to send:

To be clear, I am good with what your team comes up with as being best here.

Had I run a full import, when the email issue cropped up, we'd be in a situation where a bunch of commits would have happened, with no emails, and we would need to recover from it some how.  An email retrying scheme might be fine in that scenario, especially if after some number of retries, the AC is alerted via a DeskPRO ticket.  Basically I don't want us to be blind.

**Comment by vegu** [comment]
**Summary**

- implement re-send mechanic for emails that could not be sent (indicated by a
`sent` value of null)
- when re-sending an email add a note to the email stating "This email could
not be delivered initially and may contain stale information"
- add a field to the admin-com import emails table to show this note as well
- update `sent` if send is successful

**Comment by ccaputo** [comment]
I have confirmed that production release 2.23.0 of the Importer is now able to re-send emails that failed to be sent in a prior run.
