### ISSUE TITLE
Add ix_count to object fac

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/peeringdb#834]
Like `net_count` add a field `ix_count` to object `fac`. The field is ready-only.

@pc, please make up your mind

**Comment by ynbrthr** [comment]
+1

**Comment by arnoldnipper** [comment]
A series of issues to add counters to object relations. Related to #835 and #836

@pc, please review

**Comment by mcmanuss8** [comment]
+1

**Comment by egfrank** [comment]
**Summary:**
- Add to the API a read-only field to fac that is ix_count (ie number of exchanges the linked to the facility)
