### ISSUE TITLE
Add {ix,fac}_count to object net

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/peeringdb#835]
Like net_count for facilities, add `{ix,fac}_count` fields to object `net`. This is an informational field and read-only.

@pc, please vote on this issue.

**Comment by ynbrthr** [comment]
+1

**Comment by arnoldnipper** [comment]
A series of issues to add counters to object relations. Related to #834 ad #836

@pc, please review

**Comment by mcmanuss8** [comment]
+1

**Comment by egfrank** [comment]
**Summary:**
- Add to the API a read-only field `ix_count` to net (ie the number of ix the network is linked to)
- Add to the API a read-only field `fac_count` to net (ie the number of facilities the network is linked to)
