### ISSUE TITLE
Add fac_count to object ix

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/peeringdb#836]
To complete the set of informational fields add `fac_count` to object `ix`. This is an informational, read-only field and its value denotes the number of facilities the exchange is in.

@pc, please make up your mind

**Comment by ynbrthr** [comment]
+1

**Comment by arnoldnipper** [comment]
A series of issues to add counters to object relations. Related to #834 ad #835

@pc, please review

**Comment by mcmanuss8** [comment]
+1

**Comment by egfrank** [comment]
** Summary: **
- Add a read-only field to `ix` that is `fac_count` (ie number of facilities the exchange is in)
