### ISSUE TITLE
Provide a friendlier explanation when entering / changing a phone number

### ISSUE THREAD

**Issue by ynbrthr** [peeringdb/peeringdb#837]
When one tries to enter a non e164-formatted phone number, the error message could be more helpful 

<img width="588" alt="image" src="https://user-images.githubusercontent.com/58094221/93142724-973b1800-f6b4-11ea-9fee-42519c26ad57.png">

We could also provide either a tooltip with an explanation on what the e164 looks like, or a pointer toward a FAQ entry or a resource.

**Comment by arnoldnipper** [comment]
+1

**Comment by shane-kerr** [comment]
+1

**Comment by arnoldnipper** [comment]
@ynbrthr, any suggestion for a **friendly** explanation?

**Comment by ynbrthr** [comment]
* provide a tooltip for the phone number fields: "An E.164-formatted phone number start with a +, followed by the country code, then the national phone number (dropping the leading 0 in most countries), without spaces or dashes between the groups of digits"
* replace the server error code by something more friendly

**Comment by vegu** [comment]
Looks like there is also the additional issue of the error message being cut off if it happens on the top most contact, contacts further down the line currently show this

<img width="407" alt="phone-error-message-pdb" src="https://user-images.githubusercontent.com/143124/94286326-8795bc00-ff5d-11ea-81a6-23464cbf27c3.PNG">

**Comment by ynbrthr** [comment]
> Looks like there is also the additional issue of the error message being cut off if it happens on the top most contact, contacts further down the line currently show this

Haaaa! That's why! I got that error message in some instances, but never managed to reproduce it when i wanted to take a screenshot. I didn't pay attention to which contact's phone number I was editing. So yeah, there is that too
