### ISSUE TITLE
Delete childless org objects

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/peeringdb#838]
There are currently ~600 _childless_ `org` objects, i.e. they don't have any child objects (`ix`, `fac` or `net`). While they do no harm, they shouldn't be there as we only want to have useful data.

My proposal is to delete them if they are childless for more than x days (x=30).

@pc, what do you think?

**Comment by shane-kerr** [comment]
+1

I agree. This seems like a logical auto-cleanup. It's also easy for someone to re-create an auto-deleted `org` object without any child objects, right?

**Comment by leovegoda** [comment]
If we do this, should it be a one-off, or should there be an automated process that deletes childless `org` objects after 30 days?

**Comment by shane-kerr** [comment]
> If we do this, should it be a one-off, or should there be an automated process that deletes childless `org` objects after 30 days?

I assumed that it would be an automated process.

**Comment by leovegoda** [comment]
> I assumed that it would be an automated process.

Good

**Comment by arnoldnipper** [comment]
> It's also easy for someone to re-create an auto-deleted `org` object without any child objects, right?

Actually, deleted objects can't be re-created. But you are able to set status from deleted to ok. And it should be an automated, regular process. The same as deleting orphaned users and returned ASNs.

**Comment by ynbrthr** [comment]
shouldn't we notify the admin users of said orgs of the impending deletion?

**Comment by arnoldnipper** [comment]
> shouldn't we notify the admin users of said orgs of the impending deletion?

Will we notify users who don't finish registration? Will we notify _orphaned_ users before we delete them?

**Comment by arnoldnipper** [comment]
@pc, one more +1 needed ... on one hand side childless orgs don't hurt on the other hand keeping the DB clean and up to date is good.

**Comment by arnoldnipper** [comment]
@peeringdb/pc, one more +1 needed

**Comment by arnoldnipper** [comment]
Could we please get the smallish issues done. We start to pile up issues again :(

@peeringdb/pc, one more +1 needed

**Comment by leovegoda** [comment]
Anyone else on the @peeringdb/pc support this proposal?

**Comment by mcmanuss8** [comment]
+1 but we should email them first and then delete 30d after the email imo

**Comment by arnoldnipper** [comment]
> but we should email them first

What is the benefit? Objects are not really deleted but only marked deleted.

**Comment by leovegoda** [comment]
Is there more @peeringdb/pc support for moving this on?

**Comment by kaycliff** [comment]
+1 on deletion and email notification prior. 

@arnoldnipper I think the intent is to make sure anyone who can take action is aware in case it fell off their radar. 
It could also help mitigate related emails from users who discover that the objects were deleted at a later date.

**Comment by vegu** [comment]
This is deployed to production, but is not yet a scheduled task - we will run manually then reach out to ops and ac to see if any tweaking is needed before it is added to cron.
