### ISSUE TITLE
Advanced Search (continued/multiple searches)

### ISSUE THREAD

**Issue by funkestefan** [peeringdb/peeringdb#839]
Problem: If I go to advanced search, the default search would be IX. If I search for a city I get results for IX's in that city. If I continue and search for facilities in the same city, the search does not jump to facility search. (see attached video)

[pdb-advanced-search.mkv.zip](https://github.com/peeringdb/peeringdb/files/5234569/pdb-advanced-search.mkv.zip)

**Comment by arnoldnipper** [comment]
@funkestefan, is that the same as #536? Would you mind to check? If so, it will be fixed with the next release

**Comment by funkestefan** [comment]
Yet, it's a duplicate, waiting for fix.
