### ISSUE TITLE
Add a maintenance page to {www,beta,tutorial}.peeringdb.com

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/peeringdb#844]
Upgrading to a new version may take a while. Hence, it would be nice to show something that explains why the website is down. Something like the attached

![maintenance-page](https://user-images.githubusercontent.com/16888757/94658366-fd55ab00-0302-11eb-8973-53d3d7c7493b.png)

**Comment by arnoldnipper** [comment]
@pc, what do you think? And @peeringdb/oc how hard is this?

**Comment by mcmanuss8** [comment]
My preference would be to only do this if we *can't* make seamless releases happen (bring up new container, make sure all is well, cutover users from old container to new).

**Comment by grizz** [comment]
It's usually no downtime, this would just be another thing to do that would take deploy time -- and we already announce the maintenance window, so I don't think it's necessary.

Has someone complained about something? (I don't remember when the last time we had downtime during a deploy was).

Hard -1 from me for doing it on beta. There is no SLA on beta, and after production is deployed to the same as beta, ops often uses beta as a testing ground for other things.
