### ISSUE TITLE
Need consolidated app logs

### ISSUE THREAD

**Issue by grizz** [peeringdb/peeringdb#845]
Probably should use graylog, but open to other options. After the move to containerization, getting at the logs as been a huge pain.

**Comment by ccaputo** [comment]
I note that entries are currently going to syslog, which is bad.  Further, we have gaps ala:

```
Oct 11 15:07:54 prod2 pdb_django: Check Object permissions GET, AnonymousUser, peeringdb.organization.635.facility.365
Oct 11 15:08:03 prod2 journal: Suppressed 629 messages from /system.slice/pdb_django.service
```

**Comment by arnoldnipper** [comment]
@peeringdb/pc, moved to 3a as this has no direct impact on the production website

**Comment by vegu** [comment]
**summary**

- structured logging to stdout and move the logging to files
