### ISSUE TITLE
IX-F importer: de-duplicate data

### ISSUE THREAD

**Issue by ccaputo** [peeringdb/peeringdb#847]
Per https://github.com/peeringdb/peeringdb/issues/795#issuecomment-701891012 @arnoldnipper says the IX-F JSON schema allows identical entries, thus de-duplication of identical entries is needed.

As an example, at present the /ix/2571 import results in an email to the IXP indicating:

```
Address 185.1.135.1 assigned to more than one distinct connection
```

but the JSON with duplicate records is apparently valid.

**Comment by vegu** [comment]
We are already deduping identical member entries at https://github.com/peeringdb/peeringdb/blob/master/peeringdb_server/ixf.py#L293

This requires that the member entries are completely identical though - in the case above the ip exists in 4 member entries that are all identical with the exception of the member `id` field (at a quick glance).

In the case where member entries differ but have duplicate ip information it is not sensible to determine which one is the correct one hence it was decided in an email exchange to generate the above error.

In the context of this issue - the deduping process could be made smarter to dedupe entries where peeringdb irrelevant fields differ (like member id) to deal with the above issue.

**Comment by arnoldnipper** [comment]
What is the "member id" you are referring to, @vegu? The IX-F JSON does not know a member id. IMO the importer should only take care or relevant fields (asnum, ipv{4,6}.address, ipv(4|6).routeserver, ifspeed, state), then de-duplicating and then import.

**Comment by vegu** [comment]
I haven't checked the IX-F JSON schema today, but the feed in question sets an "id" field on the member_list entries

**Comment by arnoldnipper** [comment]
> I haven't checked the IX-F JSON schema today, but the feed in question sets an "id" field on the member_list entries

This "IX-F JSON" seems to be horribly broken and is **not** compliant.  I'll contact the IX

**Comment by arnoldnipper** [comment]
> I haven't checked the IX-F JSON schema today, but the feed in question sets an "id" field on the member_list entries

There is no "id" field in the member_list section.

**Comment by arnoldnipper** [comment]
De-duplication is already done
