### ISSUE TITLE
sponsorship_notify RuntimeWarning (was: End of Sponsorship notification email is no longer working)

### ISSUE THREAD

**Issue by ccaputo** [peeringdb/peeringdb#851]
Some time between December 4th, 2019 and September 27th, 2020, the email notification mechanism to indicate the end of a sponsorship became broken.  No email was received for a sponsorship that ended on September 27th, 2020 or for one that ended on October 7th, 2020.

As Secretary/Treasurer, I rely on this functionality.  Please prioritize a fix.

**Comment by mcmanuss8** [comment]
Regression, fast track

**Comment by ccaputo** [comment]
This may be the problem:

```
$ /home/pdb/bin/pdb-container pdb_sponsorship_notify
/srv/www.peeringdb.com/venv/lib/python3.7/site-packages/django/db/models/fields/__init__.py:1427: RuntimeWarning: DateTimeField Sponsorship.end_date received a naive datetime (2020-10-08 20:22:10.966091) while time zone support is active.
  RuntimeWarning)
```

**Comment by ccaputo** [comment]
> This may be the problem:
> 
> ```
> $ /home/pdb/bin/pdb-container pdb_sponsorship_notify
> /srv/www.peeringdb.com/venv/lib/python3.7/site-packages/django/db/models/fields/__init__.py:1427: RuntimeWarning: DateTimeField Sponsorship.end_date received a naive datetime (2020-10-08 20:22:10.966091) while time zone support is active.
>   RuntimeWarning)
> ```

The exit code for the above is 0.  If it were to be changed to indicate an error when there is an error, chronic would have prevented this from being hidden.

**Comment by ccaputo** [comment]
@vegu has indicated the RuntimeWarning is not the issue.  That said, it would be good to also get that resolved so it does not raise a flag in the future.  UTC ftw.

**Comment by ccaputo** [comment]
In addition to RuntimeWarning fix, another issue has been discovered.  Please make it so notify_date is nullified when state changes to Active, so that when it ever returns to Over, another notification can happen.
