### ISSUE TITLE
User gets "IP already exists" when adding a previously deleted netixlan having the same addresses

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/peeringdb#852]
Situtation:
```bash


curl -sG https://peeringdb.com/api/netixlan --data-urlencode status=deleted --data-urlencode since=1 --data-urlencode ipaddr4=206.81.104.15 | jq '.data[]'
{
  "id": 45765, <----
  "net_id": 14779,
  "ix_id": 2274,
  "name": "EVIX: Peering LAN",
  "ixlan_id": 2274,
  "notes": "",
  "speed": 100,
  "asn": 136985,
  "ipaddr4": "206.81.104.15",
  "ipaddr6": "2602:fed2:fff:ffff::14",
  "is_rs_peer": true,
  "operational": true,
  "created": "2018-12-11T00:02:38Z",
  "updated": "2020-02-19T04:08:27Z",
  "status": "deleted"
}
```
Although this record is deleted, a user gets "IP already exists" when adding a new record with the same IP addresses. This clearly is a bug.

<img width="582" alt="20201008 PeeringDB 01" src="https://user-images.githubusercontent.com/16888757/95494972-0ac40280-099f-11eb-914e-e790bb336bbb.png">

A workaround is that a superuser adds the record, instead. Interestingly, the same `netixlan` is used instead of creating a new one.

```
bash
curl -sG https://peeringdb.com/api/netixlan  --data-urlencode ipaddr4=206.81.104.15 | jq '.data[]'
{
  "id": 45765, <----
  "net_id": 1224,
  "ix_id": 2274,
  "name": "EVIX: Peering LAN",
  "ixlan_id": 2274,
  "notes": "",
  "speed": 1000,
  "asn": 34549,
  "ipaddr4": "206.81.104.15",
  "ipaddr6": "2602:fed2:fff:ffff::14",
  "is_rs_peer": false,
  "operational": true,
  "created": "2018-12-11T00:02:38Z",
  "updated": "2020-10-08T17:40:11Z",
  "status": "ok"
}
```

@AC, heads-up ... @pc please +1

**Comment by arnoldnipper** [comment]
Looks like a similar issue as #580

**Comment by arnoldnipper** [comment]
@vegu and @matt we now have the 2nd case. Could this be related to the latest release?

**Comment by vegu** [comment]
@arnoldnipper If this was recently introduced it seems like 2.22 was the more likely time - nothing in the last release touched any of this behaviour in an obvious way.

That said, we haven't had a chance to reproduce this locally yet, will updated once we know more.

Also, two cases from two different users i assume?

**Comment by arnoldnipper** [comment]
> Also, two cases from two different users i assume?

When looking closer at the 2nd issue it turned out that this was something different. And I'm also not able to reproduce it. Hence I close it and will keep it in mind when it pops up again.

**Comment by arnoldnipper** [comment]
Bonus question, @vegu: I would have expected that a new `netixlan` would have been created, i.e. that (asn, ipaddr4, ipaddr6) is a key. Instead, the old `netixlan` record is reused. Why?

**Comment by vegu** [comment]
@arnoldnipper if a deleted object is blocking on a unique constraint (e.g. a key that can uniquely identify the object) it will instead attempt to restore the deleted object instead of nulling the old one and creating a new instance.

To expand on the example in this ticket

- it allows a network to delete the netixlan and adding it again will restore the old one first and update it
- this is also true when the netixlan was deleted, and now a different network is claiming the ip, it will restore it, updated it and move it to the new network

If i recall correctly, it was a design choice made early on to take play nice with / take advantage of the fact that nothing is ever hard-deleted and version snapshots are kept of every change to an object.

**Comment by arnoldnipper** [comment]
It happened again, @vegu 

```
curl -sG https://peeringdb.com/api/netixlan --data-urlencode ipaddr4=62.69.146.63 --data-urlencode since=1 | jq '.data[]'
{
  "id": 39222,
  "net_id": 13228,
  "ix_id": 676,
  "name": "ECIX-FRA",
  "ixlan_id": 676,
  "notes": "",
  "speed": 20000,
  "asn": 42652,
  "ipaddr4": "62.69.146.63",
  "ipaddr6": "2001:7f8:8:20:0:a69c:0:1",
  "is_rs_peer": true,
  "operational": true,
  "created": "2018-01-24T13:10:54Z",
  "updated": "2018-04-30T09:12:55Z",
  "status": "deleted"
}
```

![20201012 PeeringDB 00](https://user-images.githubusercontent.com/16888757/95795294-4e45a600-0cea-11eb-82fa-7925394f1afc.png)


```
curl -sG https://peeringdb.com/api/netixlan --data-urlencode ipaddr4=62.69.146.63 --data-urlencode since=1 | jq '.data[]'
{
  "id": 39222,
  "net_id": 433,
  "ix_id": 676,
  "name": "ECIX-FRA",
  "ixlan_id": 676,
  "notes": "",
  "speed": 0,
  "asn": 15169,
  "ipaddr4": "62.69.146.63",
  "ipaddr6": null,
  "is_rs_peer": false,
  "operational": true,
  "created": "2018-01-24T13:10:54Z",
  "updated": "2020-10-12T22:16:27Z",
  "status": "ok"
}
```

**Comment by vegu** [comment]
@arnoldnipper we've still had no luck reproducing this in dev. 

For debugging purposes it'd be helpful if you could send us the usernames of the users that have run into this. Thanks.

**Comment by arnoldnipper** [comment]
> For debugging purposes it'd be helpful if you could send us the usernames of the users that have run into this. Thanks.

Will do it via email

**Comment by vegu** [comment]
User accounts seem to be in order - i can't find anything that stands out that would cause this on that end.

We went ahead and re-created the second situation on our dev instance, and weren't able to reproduce the issue.  Tested with different locales as well to make sure its not a repeat of #580.

Next step might be poking beta and see if we can reproduce it there.

**Comment by arnoldnipper** [comment]
Thanks, @vegu ... let's keep it open (would love to have a "1a Postponed" milestone here) until it happens again

**Comment by arnoldnipper** [comment]
Closing and keeping in mind
