### ISSUE TITLE
IX-F Importer: Make hyperlinks clickable when creating DeskPRO tickets

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/peeringdb#856]
Make hyperlinks clickable when creating DeskPRO tickets.

**Comment by netravnen** [comment]
![Unavngivet 1602704461](https://user-images.githubusercontent.com/1938389/96037329-fb90f900-0e65-11eb-846f-5dc64647a8c3.png)

Current (per single URI to open):
1. Select hyperlink using mouse operation
2. Copy URI to copy-paste buffer
3. Open new (blank) tab
4. Paste URI
5. Enter to load page

Requested (clickable URI's):
1. Command/CTRL-click URI to open page new tab
2. Go to newly opened tab.

**Comment by arnoldnipper** [comment]
@pc, would love to see +1 immediately 🥇

**Comment by ccaputo** [comment]
Definite +1 from my perspective.  Per @peeringdb/ac, further IX-F Importer roll-out is blocked until this is implemented.  @peeringdb/pc please expedite as able.

**Comment by ynbrthr** [comment]
+1

**Comment by mcmanuss8** [comment]
+1

**Comment by peterhelmenstine** [comment]
Would like to see it open a new tab rather than leave the current page

**Comment by ccaputo** [comment]
> Would like to see it open a new tab rather than leave the current page

I would think that should be up to the particular admin's tastes, no?

**Comment by arnoldnipper** [comment]
> I would think that should be up to the particular admin's tastes, no?

Agree ... however, afaik that is not configurable on a per user basis. And this is something which falls under DeskPRO. But we had this discussion on PeeringDB owned websites as well. 

So, +1 for @peterhelmenstine ... I also hate <Strg>-Click :)

**Comment by ccaputo** [comment]
> > I would think that should be up to the particular admin's tastes, no?
> 
> Agree ... however, afaik that is not configurable on a per user basis. And this is something which falls under DeskPRO. But we had this discussion on PeeringDB owned websites as well.
> 
> So, +1 for @peterhelmenstine ... I also hate -Click :)

Sounds good.  Goal here is to make things as easy as possible for the @peeringdb/ac.  I think this is being fast-tracked, so please make clear below the spec for @peeringdb/20c.  Thanks!

**Comment by ccaputo** [comment]
> Definite +1 from my perspective. Per @peeringdb/ac, further IX-F Importer roll-out is blocked until this is implemented. @peeringdb/pc please expedite as able.

I misunderstood emails and want to clarify: This is not a blocker.

**Comment by arnoldnipper** [comment]
> I misunderstood emails and want to clarify: This is not a blocker.

That's true. However, it would make @peeringdb/ac life much easier.

**Comment by alexfguimaraes** [comment]
agree!

**Comment by DarwinCosta** [comment]
+1.

Best Regards,
Cumprimentos,
Darwin-.

**Comment by ccaputo** [comment]
I tested this on beta and believe it is looking good.  @peeringdb/ac for an example you can check out: https://peeringdb.deskpro.com/agent/go/ticket/50199

**Comment by arnoldnipper** [comment]
Looks good

**Comment by alexfguimaraes** [comment]
+1
