### ISSUE TITLE
IX-F Importer: intermittent issue with speed validation

### ISSUE THREAD

**Issue by vegu** [peeringdb/peeringdb#857]
When the importer encounters ix-f entries without speed or a speed of 0 it is not supposed to note any validation errors about speed limits.

This seems to be working in most cases, but we have encountered one conflict resolution notification that noted a speed validation error when speed wasn't provided.

References:

https://peeringdb.com/cp/peeringdb_server/deskproticket/25822/change/ - no speed, with validation error note
https://www.peeringdb.com/cp/peeringdb_server/deskproticket/25825/change/ - no speed, no validation error note

**Comment by arnoldnipper** [comment]
@pc, as this has been identified as a bug by a developer I have routed this issue through to 3a

**Comment by ccaputo** [comment]
Re-tested the same network on beta 2.23.0.2 and confirm a conflict was no longer raised.
