### ISSUE TITLE
IX-F Importer: Make pdb_deskpro_publish command ignore importer tickets

### ISSUE THREAD

**Issue by vegu** [peeringdb/peeringdb#858]
The importer does it's own publishing, and there is a tiny window between the importer saving a ticket and publishing it that the deskpro publish job we have running on cron picks it up as well, resulting in a dupe ticket error.

Solution: Either don't save the ticket until the importer has published it, or make the deskpro_publish job ignore ix-f tickets.

**Comment by arnoldnipper** [comment]
@pc, as this is flagged as a bug by a developer I've routed this issue through to 3a

**Comment by ccaputo** [comment]
Source code change looks good.  Hard to test due to race condition.
