### ISSUE TITLE
Private network contacts missing from expanded /api/net output when serving cached api response

### ISSUE THREAD

**Issue by vegu** [peeringdb/peeringdb#862]
Going to `/api/net?depth=2&fields=poc_set` will serve a cached api response for /api/net - network contacts with visibility set to private will be missing even if the user should have permissions to view them.

This error doesn't seem to occur when doing live queries (e.g, by network id)

**Comment by arnoldnipper** [comment]
Routed through to 3a as this is a bug identified by a developper

**Comment by grizz** [comment]
Invalid via #944
