### ISSUE TITLE
Improve error handling when a user tries to add an object which is already there

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/peeringdb#863]
In case a user tries to add an object which is already there (and not deleted) they get a "Something went wrong 500 error" which not very helpful.

In this case, give a "You are trying to add an object which is already there" and point to this object resp. parent object.

**Comment by arnoldnipper** [comment]
@pc, please make up you rmind

**Comment by shane-kerr** [comment]
+1

"something went wrong" is basically never the correct error message. :wink:

**Comment by mcmanuss8** [comment]
+1 - exactly what Shane said

**Comment by peterhelmenstine** [comment]
Yup. What Shane said

**Comment by alexfguimaraes** [comment]
+1

**Comment by vegu** [comment]
@arnoldnipper What object creation caused this error?

That type of error message is raised on unhandled errors, not when creation is blocked on a unique key constraint (or any other type of validation exception).

We have several instances where this works and is communicated to the user correctly. (e.g. trying to add a netixlan with an ip that already exist) - so i am thinking this might be specific to a certain object type?

**Comment by arnoldnipper** [comment]
> so i am thinking this might be specific to a certain object type?

iirc the user tried to add an ASN. When I do, I get both "Something went wrong. ..." as well as a "Network with this ASN already exists". I don't remember that the user had the latter error message on their screenshot.

So, the error is handled, but still the message pops up.
![20201023 PeeringDB 00](https://user-images.githubusercontent.com/16888757/97006903-d3c62300-1540-11eb-817a-d16b3a15c80f.png)

**Comment by vegu** [comment]
Is the specification here to remove the "Something went wrong" box entirely on validation errors (which includes errors like the object already exists) since the more specific error will popup on the erroring field anyhow?

Or are we looking for a relabeling of "Something went wrong" ?

**Comment by arnoldnipper** [comment]
Imho the "Something went wrong" box easily distracts from the other error message. Make that a bit bigger and change the font to bold could help. Does that make sense?

**Comment by alexfguimaraes** [comment]
Agree!!

**Comment by vegu** [comment]
**summary**

- increase visibility of field validation error notes by increasing size and font weight
