### ISSUE TITLE
GEO: Support Open Location Code (OLC) (also known as Plus Codes) to denote locations

### ISSUE THREAD

**Issue by netravnen** [peeringdb/peeringdb#864]
I think PeeringDB should consider the feasability to support Open Location Code.

The reasoning be it is an open standard for location codes, Being able to more granularly support denoting a specific location. Which can be useful in cases where our common understanding of [Address] is either (A) not possible, or (B) not very accurate.

[Address]: {Street Addr.} {Street No.}, {Zip}, {State}, {Country}

## What is Open Location Code?

> The Open Location Code (OLC) is a geocode system for identifying an area anywhere on the Earth.[1] It was developed at Google's Zürich engineering office,[2] and released late October 2014.[3] Location codes created by the OLC system are referred to as "plus codes".
> 
> Open Location Code is a way of encoding location into a form that is easier to use than showing coordinates in the usual form of latitude and longitude. Plus codes are designed to be used like street addresses, and may be especially useful in places where there is no formal system to identify buildings, such as street names, house numbers, and post codes.[4]
> 
> Plus codes are derived from latitude and longitude coordinates, so they already exist everywhere.[5] They are similar in length to a telephone number – 849VCWC8+R9, for example – but can often be shortened to only four or six digits when combined with a locality (CWC8+R9, Mountain View). Locations close to each other have similar codes. They can be encoded or decoded offline. The character set avoids similar looking characters, to reduce confusion and errors, and avoids vowels to make it unlikely that a code spells existing words. Plus codes are not case-sensitive, and can therefore be easily exchanged over the phone.[6]
> 
> Since August 2015, Google Maps supports plus codes in their search engine.[7] The algorithm is licensed under the Apache License 2.0.[8] and available on GitHub.[9]
> 
> Google states that plus codes are accepted as postal addresses in Cape Verde,[10] parts of Kolkata,[11] and the Navajo Nation.[12]

Source: Wikipedia

- https://plus.codes / https://maps.google.com/pluscodes/
- https://en.wikipedia.org/wiki/Open_Location_Code
- https://support.google.com/maps/answer/7047426?co=GENIE.Platform%3DAndroid&hl=en
- https://github.com/openstreetmap/openstreetmap-website/issues/1807

_Edit:_ A DeskPro ticket as an example where it makes sense. _"Google doesn't find "201,j, n, s road"_ (OLC: P99M+95 Dhaka, Bangladesh) ⟵ This could be resolved and/or alliviated using OLC as the location identifier. Due to not all addressing schematics in use today can be accurately fit into the common schematic used in "the industrial world".

- https://peeringdb.deskpro.com/agent/go/ticket/49708

**Comment by netravnen** [comment]
Videos on YouTube describing Plus Codes and what they can/are used for already today: https://www.youtube.com/c/pluscodes/videos

**Comment by arnoldnipper** [comment]
> _Edit:_ A DeskPro ticket as an example where it makes sense. _"Google doesn't find "201,j, n, s road"_ (OLC: P99M+95 Dhaka, Bangladesh) ⟵ This could be resolved and/or alliviated using OLC as the location identifier. Due to not all addressing schematics in use today can be accurately fit into the common schematic used in "the industrial world".

The user also could have provided lat/lon data.

**Comment by leovegoda** [comment]
Is this intended as a replacement for lat/long coordinates or an alternative representation? If the latter, what are the advantages provided to users other than an additional representation of the location?
