### ISSUE TITLE
Allow arbitray decimal places as input for longitude and latitude. Systems rounds to six

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/peeringdb#865]
Currently, only six places are allowed. However, Google maps always provides seven.

![20201031 PeeringDB 00](https://user-images.githubusercontent.com/16888757/97792158-d2e55f00-1bda-11eb-8888-0385168ad007.png)

**Comment by arnoldnipper** [comment]
+1  ... @ynbrthr, you are shepherding as it deals with locations. Ok?

**Comment by netravnen** [comment]
👍

**Comment by peterhelmenstine** [comment]
+1 more accurate the better

**Comment by shane-kerr** [comment]
+1

**Comment by mcmanuss8** [comment]
+1

**Comment by mcmanuss8** [comment]
I'd also support us allowing more digits than 7 to be input and just rounding to 7 if more are supplied (with an appropriate warning that we will round it)

**Comment by arnoldnipper** [comment]
> I'd also support us allowing more digits than 7 to be input and just rounding to 7 if more are supplied (with an appropriate warning that we will round it)

I came across these 6 digits when googling for the precision of GPS coordinates, but couldn't find any reason. I opened this issue because Google always returns **seven** digits. If there is a reasoning to only have six digits then I'm fine. But then the system should do the rounding.

Probably @20c knows why we are only supporting six digits. Btw.: seven digits is 1.11cm at the equator

**Comment by ynbrthr** [comment]
> > I'd also support us allowing more digits than 7 to be input and just rounding to 7 if more are supplied (with an appropriate warning that we will round it)
> 
> 
> 
> I came across these 6 digits when googling for the precision of GPS coordinates, but couldn't find any reason. I opened this issue because Google always returns **seven** digits. If there is a reasoning to only have six digits then I'm fine. But then the system should do the rounding.
> 
> 
> 
> Probably @20c knows why we are only supporting six digits. Btw.: seven digits is 1.11cm at the equator

looks like we've all been googling the same thing :)

+1 for supporting 7 digits, and rounding if more are provided

**Comment by grizz** [comment]
+1

> Probably @20c knows why we are only supporting six digits. Btw.: seven digits is 1.11cm at the equator

It looks like it was a default that was an oversight on our part, this should technically be a bug.

**Comment by arnoldnipper** [comment]
**Summary**

 * allow arbitrary precision when adding geolocation data
 * round to 6 digits 

See also the wiki [entry](https://en.wikipedia.org/wiki/Decimal_degrees)

**Comment by ynbrthr** [comment]
> **Summary**
> 
> 
> 
>  * allow arbitrary precision when adding geolocation data
> 
>  * round to 6 digits 
> 

it's round to 7 digits, is it not?

**Comment by arnoldnipper** [comment]
> it's round to 7 digits, is it not?

no, 6 digits. Why?

 * high-end GPS equipment provides an [accuracy of a few cm](https://www.gps.gov/systems/gps/performance/accuracy/)
 * according to the [wiki article](https://en.wikipedia.org/wiki/Decimal_degrees) 6 digits will do for a few cm
 * even when we want to locate equipment in a rack we never will need more than 6 digits
 * backwards compatibility
 * just ease c&p of data taken from Google maps (the main reason)

**Comment by egfrank** [comment]
** Summary **
- Allow arbitrary length of inputs to lat+long
- Round to 6 digits (including google maps output)
