### ISSUE TITLE
AS removal/transfer

### ISSUE THREAD

**Issue by keatonaglair** [peeringdb/peeringdb#866]
Allow Networks to be either removed or transferred between organizations?
Of course there should be some "Are you absolutely sure?!" checks, just a suggestion.

**Comment by keatonaglair** [comment]
Didn't realize you could remove ASN, but I'll leave this open for the transfer between organizations part of my original comment.

**Comment by arnoldnipper** [comment]
> Allow Networks to be either removed or transferred between organizations?

Just mail PeeringDB [Support](mailto:support@peeringdb.com)
