### ISSUE TITLE
Suggestion Form

### ISSUE THREAD

**Issue by leovegoda** [peeringdb/peeringdb#870]
We should create a form on peeringdb.com that allows anyone to report suggestions to PeeringDB, whether they are bug reports, enhancement suggestions, or something more administrative.

We should build a simple web form allowing users to provide suggestions. The form should be translated into all supported languages and encourage feedback in any language. The text box should support at least 1000 characters. It should also support uploading images so that people can send screenshots of problems.

People who are logged in to the website should have the following data recorded:

- Name
- E-mail address
- Organizational affiliation(s)
- Text of the suggestion
- Any attachments uploaded

We should gather the same data for those not logged in after they have passed a CAPTCHA test.

The proposals should be placed in a suggestions queue in DeskPRO.

When the Product Committee decides to act on a suggestion, an issue for it should be created in Github, so its development can be tracked transparently.

**Comment by arnoldnipper** [comment]
Translation will happen automatically ... or not. And we already have an issue where logged-in users can report [bad data](#170).

**Comment by leovegoda** [comment]
> we already have an issue where logged-in users can report [bad data](#170). We could merge both issues imho. #170 is at 3a, but open since 07/2017. Hence, could wait for another month or two to do both issues in one shot.

I think both #170 and this issue do good things but are focused on different issues. #170 focuses on data quality and so, to some extent, is about what other users are publishing. This issue is mostly focused on getting other kinds of feedback. The examples given in the original issue are mostly things controlled by PeeringDB rather than users.

**Comment by arnoldnipper** [comment]
You are talking about the content. I'm talking about the form itself. Both are about giving feedback.

**Comment by arnoldnipper** [comment]
@peeringdb/pc, please vote!

**Comment by leovegoda** [comment]
The Product Committee has decided to close this issue. There was no agreement on the concept and the issue has not been discussed for six months or longer.
