### ISSUE TITLE
Create a sponsorship object or add a field "sponsor" to org

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/peeringdb#877]
**Motivation**
Currently, PeeringDB has sponsors which don't own any `fac`, `ix` or `net` object. When doing automatic garbage collection (i.e. identifying childless `org` objects) we would also remove those sponsor `org` objects.

**Solution**
  * 1: add a `sponsorship` object. This can be as simple as only containing the sponsorship level
  * 2: add a `sponsor` field to the `org` object. The value is the sponsorship level

I'd prefer solution 1 as then all legit `org` objects also have a child.

@peeringdb/pc please make up your mind.
@ccaputo what do you think?

**Comment by ccaputo** [comment]
Internal sponsorship objects already exist and should automatically prevent deletion, as we have previously covered this.  @grizz, can you confirm?  (In the case of the childless org I created yesterday, garbage collection will be prevented once I have the sponsorship object created in the next day or so.  Currently waiting on one aspect.)

If you are talking about exposing sponsorships in the /api/ I don't see the point.  Is that needed for anything?

**Comment by ccaputo** [comment]
I've got confirmation from 20C that "if there is an active sponsorship tied to the organization the organization will be blocked from being deleted" and "Inactive sponsorships on the other hand currently do not block the deletion of the organization."

Recommend closure.

**Comment by arnoldnipper** [comment]
> If you are talking about exposing sponsorships in the /api/ I don't see the point. Is that needed for anything?

Yes, for automatic garbage collection.

**Comment by ccaputo** [comment]
> > If you are talking about exposing sponsorships in the /api/ I don't see the point. Is that needed for anything?
> 
> Yes, for automatic garbage collection.

Automatic garbage collection performed by a script that uses the REST /api/ ?  As I understand it, a DELETE would not be possible if attempted.

That said, if you and others think solution 1 makes sense, I don't object.

**Comment by arnoldnipper** [comment]
May I also point to #827 (Make GUI and API feature equivalent)

**Comment by ccaputo** [comment]
> May I also point to #827 (Make GUI and API feature equivalent)

Sponsorships are not the primary service purpose of PeeringDB, so I don't see how they make sense in an /api/ that should be relatively static in definition.  Sponsorships as PeeringDB's funding model may change over time for all we know.  Putting management of sponsorships into the /api/, when only one person - the Secretary/Treasurer - maintains them, makes no sense to me, and just increases technical debt.  Making it so there is an automated way to query the sponsor level of organizations does not seem to match PeeringDB's actual reason for being.  Having thought about this more, I don't see the point and recommend against this handcuff.
