### ISSUE TITLE
Add "Last login" to https://peeringdb.com/cp/peeringdb_server/user/

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/peeringdb#879]
If AC wants to contact an organisation with multiple admins, it would be handy to know who has logged in last. Currently, I have to go to each record to find out. An extra column would help.

![20201114 PeeringDB 00](https://user-images.githubusercontent.com/16888757/99150178-08864f80-2693-11eb-805d-e9f1afd7e642.png)

@peeringdb/ac, what do you think?

@pc, please +1

**Comment by DarwinCosta** [comment]
> On 14 Nov 2020, at 16:05, Arnold Nipper <notifications@github.com> wrote:
> 
> ﻿
> If AC wants to contact an organisation with multiple admins, it would be handy to know who has logged in last. Currently, I have to go to each record to find out. An extra column would help.
> 
> 
> 
> @peeringdb/ac, what do you think?
> 
I think this would be useful. +1.

**Comment by peterhelmenstine** [comment]
Yup. Handy feature

**Comment by shane-kerr** [comment]
+1

**Comment by ynbrthr** [comment]
+1

**Comment by alexfguimaraes** [comment]
+1

**Comment by egfrank** [comment]
**Summary**
- Add "last login" as a column in User list view in the admin portal (/cp/peeringdb_server/user/)

**Comment by alexfguimaraes** [comment]
+1
