### ISSUE TITLE
IXF-Importer: Showstopper: "Could not process IX-F Data" emails are re-sent with each Importer run

### ISSUE THREAD

**Issue by ccaputo** [peeringdb/peeringdb#880]
"Could not process IX-F Data" emails to IXes are sent each time the Importer discovers them.  This is a showstopper problem, because it means that any time the Importer is run, a number of IXes will get emailed about something they have already been recently emailed about.  As part of the Importer rollout, for example, after the cron 0000 UTC run, a manual run is also performed with new ixlan additions.

I recommend the Importer be ASAP/HOTFIX modified to make it so an IX gets this notification no more than once per week.  I think this frequency is enough to nudge an IX to either turn off their imports or fix their data.

As part of this fix, we need to know if there are any other emails of this nature that would be sent with each Importer run.  The Importer may some day be run once per hour and we need to make sure we don't send emails without restraints on duplication in short time periods.

**Comment by ccaputo** [comment]
Possible solution method: In django perform the equivalent of a SELECT on the ixfimportemail table, WHERE Subject & Recipients & IX match the proposed "Could not process IX-F Data" email.  If there is a match with a Created time _or_ Sent time within 7 days, simply skip sending an additional email.  Otherwise, send a new email, adding a new entry to ixfimportemail table accordingly.  (I focus on both Created and Sent here, and not just Sent, in case there is an email retry scenario also in play.)

**Comment by arnoldnipper** [comment]
Didn't we agree to remind them 3 times and then to disable the import?

**Comment by ccaputo** [comment]
Closing.  I found the code that limits notifications to once every 36 hours.  In my testing, the error cause had changed, and somehow that resulted in another email.  That is actually a good thing.

https://github.com/peeringdb/peeringdb/blob/a6d824da58f63cfe8edba42d056620fb1f45a714/peeringdb_server/ixf.py#L1684-L1695

**Comment by arnoldnipper** [comment]
That still results in an email every other day. A more sophisticated mechanism would be good. E.g. backing off. And disabling import after three reminders.

**Comment by ccaputo** [comment]
> That still results in an email every other day.

I've now set these emails to be at least 15 days apart.  If you prefer 7 days or some other number, let's discuss in email.

> A more sophisticated mechanism would be good. E.g. backing off. And disabling import after three reminders.

Additional state would need to be preserved in order to do that.  I recommend against this increase in complexity in the Importer.

**Comment by arnoldnipper** [comment]
> I've now set these emails to be at least 15 days apart. If you prefer 7 days or some other number, let's discuss in email.
> 

15 days is fine

**Comment by ccaputo** [comment]
#890
