### ISSUE TITLE
wrap correctly on mobile

### ISSUE THREAD

**Issue by job** [peeringdb/peeringdb#881]
![signal-2020-11-14-193458](https://user-images.githubusercontent.com/153816/99154690-0089d800-26b2-11eb-95a2-4568ffe3fd43.png)

In environments where the screen is small, we probably don't want to ever wrap/cutoff the ASN as that's a vital thing in our context :)

**Comment by arnoldnipper** [comment]
+1

**Comment by shane-kerr** [comment]
+1

**Comment by leovegoda** [comment]
Looking at what is assigned right now, I think the longest ASNs have six digits. Allowing for seven digits to be shown should give us plenty of time.

**Comment by egfrank** [comment]
**Summary**
- On mobile fac view, make ASN column wide enough to show 7 digits without wrapping
