### ISSUE TITLE
IXF-Importer: don't abort when there is nothing to import

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/peeringdb#882]
Currently, the importer is aborting with an error message when there is nothing to import. Especially when member_list is empty. The importer must not send an error message when there is nothing to import.

Somewhat related to #880.

**Comment by ccaputo** [comment]
I agree this should be fixed.  @arnoldnipper, can you give a sense of urgency?  Should we ask IXes to uncheck the import flag when they have nothing to import?  Emails will go them about once every two days, otherwise.

**Comment by ccaputo** [comment]
I do wonder, what is the point of configuring an IX-F JSON at PeeringDB, if there is nothing to import?  Maybe it is actually better to inform the IX when there is nothing to import, since that might make them aware of a problem with their IX-F JSON data?

**Comment by arnoldnipper** [comment]
> I do wonder, what is the point of configuring an IX-F JSON at PeeringDB, if there is nothing to import?

They already set up everything at PeeringDB while not yet ready to export any member information. 

> Maybe it is actually better to inform the IX when there is nothing to import

The IX gets informed. No?

**Comment by ccaputo** [comment]
> > I do wonder, what is the point of configuring an IX-F JSON at PeeringDB, if there is nothing to import?
> 
> They already set up everything at PeeringDB while not yet ready to export any member information.
> 
> > Maybe it is actually better to inform the IX when there is nothing to import
> 
> The IX gets informed. No?

Current status is the IX gets informed when there is nothing to import, but this very issue you have created here would change that, no?

**Comment by arnoldnipper** [comment]
The [Note](https://docs.peeringdb.com/ix-f-json-import-rules/) in the "For IXP" section says: The Importer expects that you also provide IP addresses. If your IX-F JSON has an empty member_list or only contains ASNs, there will be no useful information. You might want to disable the import.

So, there is no need to send an error message as we can assume that the IX provides no data on purpose. KISS!

Fellow @peeringdb/pc members: what do you think?

**Comment by ccaputo** [comment]
> The [Note](https://docs.peeringdb.com/ix-f-json-import-rules/) in the "For IXP" section says: The Importer expects that you also provide IP addresses. If your IX-F JSON has an empty member_list or only contains ASNs, there will be no useful information. You might want to disable the import.
> 
> So, there is no need to send an error message as we can assume that the IX provides no data on purpose. KISS!

Are you okay with the "IX-F Import Preview" still showing the error "`No entries in any of the vlan_list lists, aborting.`" ?  I'd like to keep that there so the IX has some visibility to what is happening with their export.

My recommendation Summary is:

- In the case of "`No entries in any of the vlan_list lists, aborting.`", make a change to the Importer to no longer send emails about this, but keep the code which shows the message in the "IX-F Import Preview".

Good?

**Comment by arnoldnipper** [comment]
> Are you okay with the "IX-F Import Preview" still showing the error "`No entries in any of the vlan_list lists, aborting.`" ? I'd like to keep that there so the IX has some visibility to what is happening with their export.

We should be consistent. It's not an error to have nothing to import. So the answer is "no".

**Comment by ccaputo** [comment]
> > Are you okay with the "IX-F Import Preview" still showing the error "`No entries in any of the vlan_list lists, aborting.`" ? I'd like to keep that there so the IX has some visibility to what is happening with their export.
> 
> We should be consistent. It's not an error to have nothing to import. So the answer is "no".

Ok - I guess I am beginning to understand your goal here.  Thus:

Summary:

- In the case of "`No entries in any of the vlan_list lists, aborting.`", make a change to the Importer to no longer send emails nor show an error message in the "IX-F Import Preview".

Good?

**Comment by arnoldnipper** [comment]
> Good?

Perfetto!

**Comment by ccaputo** [comment]
It looks like IX-F Import Preview is showing errors for IXes that have "`No entries in any of the vlan_list lists, aborting.`".  For example:

<img width="893" alt="Screen Shot 2020-11-20 at 3 32 21 PM" src="https://user-images.githubusercontent.com/1417833/99859689-a2dc0c80-2b45-11eb-85c4-7446ba6cc639.png">

Arnold, do you agree these errors should not be listed for the case of "`No entries in any of the vlan_list lists, aborting.`"?

**Comment by arnoldnipper** [comment]
> Arnold, do you agree these errors should not be listed for the case of "`No entries in any of the vlan_list lists, aborting.`"?

I guess this error message will go away once this issue is implemented.

**Comment by arnoldnipper** [comment]
**Summary**

- In the case of "`No entries in any of the vlan_list lists, aborting.`", make a change to the Importer to no longer send emails nor show an error message in the "IX-F Import Preview".

**Comment by arnoldnipper** [comment]
**Release Notes**
If there is nothing to import from an IX-F JSON don't abort with an error message.
