### ISSUE TITLE
IXF-Importer: stdout/stderr need to be in order

### ISSUE THREAD

**Issue by ccaputo** [peeringdb/peeringdb#884]
I suspect the Importer is buffering stdout while stderr is unbuffered.  Can we make it so both stdout and stderr from the Importer do _not_ have buffering and/or flush after each print()?  That would help with catching when an error happens in the context of the other logging.

**Comment by arnoldnipper** [comment]
+1, @pc, pls support

**Comment by shane-kerr** [comment]
+1

What we really want is for stdout and stderr to share the same buffer if they are going to the same output (whether a tty or a file), but flushing as described is a reasonable approach since we don't expect output like this to impact performance much.

**Comment by mcmanuss8** [comment]
+1

**Comment by ccaputo** [comment]
Dug into this further.  Turns out to be a docker issue, not a django issue.  And I have a way to trigger docker not to perform buffering while testing.  ("-t")

Closing.
