### ISSUE TITLE
IX-F Importer: Unbound variable error on invalid member type

### ISSUE THREAD

**Issue by vegu** [peeringdb/peeringdb#885]
```
ERROR: local variable 'asn' referenced before assignment
Traceback (most recent call last):
  File "/srv/www.peeringdb.com/peeringdb_server/management/commands/pdb_ixf_ixp_member_import.py", line 232, in handle
    success = importer.update(ixlan, save=self.commit, asn=asn)
  File "/srv/www.peeringdb.com/peeringdb_server/ixf.py", line 391, in update
    self.parse(data)
  File "/srv/www.peeringdb.com/peeringdb_server/ixf.py", line 652, in parse
    self.parse_members(data.get("member_list", []))
  File "/srv/www.peeringdb.com/peeringdb_server/ixf.py", line 696, in parse_members
    asn, "ignore", _("Invalid member type: {}").format(member_type)
UnboundLocalError: local variable 'asn' referenced before assignment
```

Happens in the importer's handling of member type values when it encounters a member type it doesn't know what to do with and attempts to log this.

As the error itself is a bug in the log function we never saw what the member type value was or which ix-f feed contained it.

Whatever the trigger was in the ix-f data seems to have gone away now. For the scope of this ticket lets fix the issue above so the log works properly in this situation.

**Summary**

- fix bug in ixf importer logging when encountering unknown member types
- add test case with unknown member types

**Comment by arnoldnipper** [comment]
Routed through to 3a as a developer classifies this as a bug, @peeringdb/pc

**Comment by ccaputo** [comment]
Note to self: I confirmed this is reproducible on betamaster with "`/home/pdb/bin/pdb-container pdb_ixf_ixp_member_import --commit --reset`" so it would be good to test the fix there.

**Comment by ccaputo** [comment]
> Note to self: I confirmed this is reproducible on betamaster with "`/home/pdb/bin/pdb-container pdb_ixf_ixp_member_import --commit --reset`" so it would be good to test the fix there.

Note: This bug is intermittent.  A subsequent reset and full run failed to reproduce it.

**Comment by ccaputo** [comment]
As part of this, the member_type should be ignored going forward, so that the Importer accepts all member types.
