### ISSUE TITLE
IX-F Importer: Add information to command error output to indicate which exchange and ix-f feed caused each error

### ISSUE THREAD

**Issue by vegu** [peeringdb/peeringdb#886]
**Problem**

When running the importer command, errors are collected and displayed at the end of the run as per #825. 

However it is currently impossible to relate those errors to the exchanges that caused them.

**Proposal/Summary**

- Add exchange information  (name, id, ix-f url) to IX-F command error output messages

**Comment by arnoldnipper** [comment]
+1 ... and @peeringdb/pc please give +1 as well

**Comment by ynbrthr** [comment]
+1

**Comment by ccaputo** [comment]
+1

**Comment by mcmanuss8** [comment]
+1

**Comment by egfrank** [comment]
**Summary**
- Add exchange information (name, id, ix-f url) to IX-F command error output messages
