### ISSUE TITLE
Add a GEO RFC 8805 Self-Published IP Geolocation URL to net object

### ISSUE THREAD

**Issue by humdai** [peeringdb/peeringdb#887]
RFC 8805 has recently been published which provides a format whereby a network operator can publish a mapping of IP address prefixes to simplified geolocation information.  Section 8 of the RFC recognises that a suitable mechanism for sharing of these with geo-data companies, CDNs, media companies etc does not currently exist.  It strikes me that the most logical way of achieving this would be via an extra field in peeringdb..

**Comment by arnoldnipper** [comment]
> It strikes me that the most logical way of achieving this would be via an extra field in peeringdb..

Could you please explain in more detail, @humdai? PeeringDB does not have IP prefix object, but only a `net` object.

**Comment by humdai** [comment]
> > It strikes me that the most logical way of achieving this would be via an extra field in peeringdb..
> 
> Could you please explain in more detail, @humdai? PeeringDB does not have IP prefix object, but only a `net` object.

So using the Github ASN as an example, when I visit their page: 

https://www.peeringdb.com/net/5152 

A summary page is displayed, this include fields like Looking Glass URL, Route Server URL etc.  What I am suggesting is that a RFC8805 geo feed URL field could be added.  Then a network operator can link to their self published geo feed.  This feed can then be pulled by media companies, CDNs, geo-data companies etc.

**Comment by arnoldnipper** [comment]
+1

**Comment by arnoldnipper** [comment]
@ynbrthr, as you are shepherding all the geo issues I've assigned this issue to you

**Comment by mcmanuss8** [comment]
I'd argue this is tangential to the geo issues we're working on, but I'm happy to let Yan drive it if he's got cycles. :)

I'll point out this could relate to my comment in #58 (https://github.com/peeringdb/peeringdb/issues/58#issuecomment-271694394) if we had more metadata in the RFC specification. For example, if the specification included things like "this prefix contains just network gear" vs "this prefix contains eyeballs" you could imagine us parsing it and getting a list of geos where the network has eyeballs that a CDN might want to reach.

**Comment by arnoldnipper** [comment]
> if we had more metadata in the RFC specification.

Wouldn't that belong to the route/inetnum/inet6num object?

**Comment by massimocandela** [comment]
Hi all,

Please, see https://tools.ietf.org/html/draft-ietf-opsawg-finding-geofeeds-00 
Where geofeeds are linked to inet(6)nums. At the moment we have 1k+ entries and 2 geolocation providers implementing it (others are working on it).

Also, see this tool for discovering and downloading them automatically: https://github.com/massimocandela/geofeed-finder

Ciao,
Massimo

**Comment by arnoldnipper** [comment]
@massimocandela, my understanding now is that putting in a field at an ASN level would not make sense. Am I right?

**Comment by jkldgoefgkljefogeg** [comment]
draft-ymbk-opsawg-finding-geofeeds does not negate the need for geofeed publishing in peeringdb. imo ASN level geofeed is easier to use and more sensible for some use cases not involving IRR/whois db

**Comment by massimocandela** [comment]
Hi @arnoldnipper 

No, we tried but it was not working. 

We needed the inetnum for the following reasons:
1) The inetnum allows you to validate the "ownership" of the prefix. Users can set whatever prefix they want in the file. If you link the file from an inetnum you can ~safely ignore whatever in the geofeed file is not contained in the referring inetnum (the idea is that if you can link if from the inetnum, you can gelocate it). This makes the life easier/safer for who has to use this files.

2) Inetnums impose a hierarchy across the multiple geofeed files. This allows an operator to create in whatever moment a "more specific" geofeed file overwriting whatever the "parent" geofeed says. Which also gives us an important flexibility, e.g., providers can correct addresses for their customers (which is a common approach), if/when customers want to autonomously do it, they can just add a geofeed to their inetnum).

**Comment by arnoldnipper** [comment]
> No, we tried but it was not working.

I'm puzzled ... as you answer "No" to my question "Am I right?", but then lining out why inetnum is needed. Can you please clarify?

**Comment by massimocandela** [comment]
> draft-ymbk-opsawg-finding-geofeeds does not negate the need for geofeed publishing in peeringdb. imo ASN level geofeed is easier to use and more sensible for some use cases not involving IRR/whois db

At the moment the main issue we have is a lot of copies of geolocation data spread in a lot of companies, which gets stale and nobody knows how to correct it. The idea behind having geofeeds in a centralized place is to create a sort of authoritative source. Planning on having them in yet another repository is in my opinion harmful and contributes to the lack of authoritative source. It promotes duplication, which guided us to the nightmare we have today in the first place, where to correct a prefix we have to try randomly to contact X geolocation/content providers and wait they fix it (and it reminds me [this](https://imgs.xkcd.com/comics/standards.png) :P ).

Linking geofeeds to the asn is not a challenge. Having geolocation providers onboard and provide an easy way for them validating the file is the problem. Also, geo providers already access whois data, the bulk data is easily parsable and I believe APIs mirroring the geofeed list will appear soon.

My point is, we had the geolocation problem unresolved for years: let's try now with **one** proposed solution. If it doesn't work we can always reassess.

**Comment by massimocandela** [comment]
> > No, we tried but it was not working.
> 
> I'm puzzled ... as you answer "No" to my question "Am I right?", but then lining out why inetnum is needed. Can you please clarify?

My answer was "no" that it would not make sense. So "yes" you are right.  Somewhere I must have done `let true = false` :)

**Comment by massimocandela** [comment]
> As for geofeed hierarchy, allowing different entities to set geofeed covering the same prefix is problematic and introduces unnecessary complexity.

This is how the IP space works. Nothing you can do about it. The flexibility I refer to is just an unavoidable extra, which apparently is the most common approach how currently ip geolocation gets fixed (summarized with "I asked my provider").

**Comment by randyqx** [comment]
http://archive.psg.com/201120.opsawg-geofeeds.pdf   
though you might find the whole preso interesting.  in particular, read slide 12 and think about it for a bit.

**Comment by arnoldnipper** [comment]
> My answer was "no" that it would not make sense. So "yes" you are right. Somewhere I must have done `let true = false` :)

I switch from +1 to -1, now that I have more background. Thanks, @massimocandela

**Comment by ynbrthr** [comment]
> @ynbrthr, as you are shepherding all the geo issues I've assigned this issue to you

thanks @arnoldnipper!

**Comment by shane-kerr** [comment]
-1

I find @massimocandela's arguments compelling, and look forward to the confusing day when there are both `remarks:` and `geofeeds:` in the RIPE Database. ;-)

**Comment by humdai** [comment]
I was not aware or draft-ietf-opsawg-finding-geofeeds-00 when I made this suggestion.  As a solution to the problem of how to distribute these feeds it looks like it will work.  I am curious why you believe that this method will be more successful than geoloc?
