### ISSUE TITLE
Type issue when overriding settings through environment variables for numeric types

### ISSUE THREAD

**Issue by vegu** [peeringdb/peeringdb#888]
A lot of the django settings can be overwritten using identically named environment variables, however for settings expecting numeric values we are currently not coercing such overrides to the expected numeric type causing type error issues in the code.

This was observed when trying to override `IXF_PARSE_ERROR_NOTIFICATION_PERIOD` but i suspect its true for other settings as well.

**Summary**

- go through all the overridable settings and make sure that overrides are coerced to the correct expected type

**Comment by shane-kerr** [comment]
Just so I'm clear, you mean that the code is treating `IXF_PARSE_ERROR_NOTIFICATION_PERIOD` (and possibly others) as a string and then getting errors later on when using the value?

**Comment by vegu** [comment]
Correct

**Comment by arnoldnipper** [comment]
+1

**Comment by arnoldnipper** [comment]
Classified as bug and hence routed through to 3a, @peeringdb/ac
