### ISSUE TITLE
IXF Importer: Handle the case where IX-F JSON import errors are numerous

### ISSUE THREAD

**Issue by ccaputo** [peeringdb/peeringdb#891]
I have observed an IX import going back & forth between a failure to transfer and another issue.  (for example: "Address 0.0.0.0")

We have a check of IXF_PARSE_ERROR_NOTIFICATION_PERIOD (#890 is making this 15 days) in place to avoid frequent emails due to changing errors, but also we have the problem of the IX being in the dark about the totality of current issues.  At present, only the first issue noticed is communicated to the IX, and they don't learn of any subsequent issues, unless there is a successful import in between.

I believe it would make sense to build a uniqued sorted list of issues, with most recent timestamp for each included in the email to the IX, with a new email being sent to the IX regardless of IXF_PARSE_ERROR_NOTIFICATION_PERIOD in the case where the uniqued list (sans timestamps) since last success (or first run) has changed.

As an example, an IX might initially get:

```
There was an issue when we attempted to parse the IX-F data for Foo Internet Exchange Point

  TIMESTAMP: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
```

and then a later email (ignoring IXF_PARSE_ERROR_NOTIFICATION_PERIOD), based on the issues changing, would indicate there are multiple issues, sorted with most recent issue first:

```
There have been multiple issues when we attempted to parse the IX-F data for Foo Internet Exchange Point

  TIMESTAMP: "Address 0.0.0.0 assigned to more than one distinct connection"

  TIMESTAMP: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
```

(TIMESTAMPS should be UTC human readable.  Ie. ISO 8601 ala "2020-11-18T16:34:45Z".  Internally, in the JSON stored in the ixlan 'IX-F error' field, there can also be a counter to aide with sorting, if needed.)

On each run of the Importer, the timestamp for a particular error would be updated each time it happens.  That would be helpful to both the IX _and_ PeeringDB Admins.  But if the list sans timestamps is unchanging, IXF_PARSE_ERROR_NOTIFICATION_PERIOD is honored, resulting in infrequent emails for the same set of errors.

The errors would be cleared whenever there is a success, since upon first failure after a successful import, we want the IX to be informed about it.

@vegu estimates this to be a couple hours of dev time.  @peeringdb/ac / @arnoldnipper: Feedback on whether this would be helpful and should be developed, is needed.

**Comment by arnoldnipper** [comment]
@ccaputo, we already have an "IX-F Import Preview" feature built in. It is highly recommended that each IX is using this stool before enabling an IX-F JSON import.

**Comment by ccaputo** [comment]
> @ccaputo, we already have an "IX-F Import Preview" feature built in. It is highly recommended that each IX is using this stool before enabling an IX-F JSON import.

Good point.  But that won't show all of the problems being perceived, unless they re-Preview over and over, which they won't know to do.

What do you think of the proposal?

**Comment by arnoldnipper** [comment]
> What do you think of the proposal?

I'm not in favour of it

**Comment by ccaputo** [comment]
> > What do you think of the proposal?
> 
> I'm not in favour of it

Why not?

**Comment by arnoldnipper** [comment]
> Why not?

IXP should check their export first against a validator, before enabling the import.  Your tool would cover very, very rare corner case. If any.

Besides that, AC is there to help to provide an error-free IX-F JSON.
