### ISSUE TITLE
IX-F Importer: Bogus output of "Preview" tool

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/peeringdb#896]
The output shows an entry not related to the network. ASN 397806 has member_type set to "other", not ASN 6939.

@vegu, please confirm.

![2020-11-20](https://user-images.githubusercontent.com/16888757/99862831-908cbd80-2b9b-11eb-946e-f8b891edd030.png)

**Comment by vegu** [comment]
Looks like a bug in the preview tool, where invalid member type messages aren't filtered for the network viewing the preview.

**Comment by arnoldnipper** [comment]
@peeringdb/pc, routed through to 3a as a developer confirms that this is a bug
