### ISSUE TITLE
Allow network's IXP IP to be null

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/peeringdb#9]
This is to indicate that a connection to that IXP will happen and to give other participants a heads up

**Comment by karumugham** [comment]
I've run into this one myself with PDB 2.0; it was nice to be able to add a pending IX before getting an IP, which is no longer possible.

Maybe we should make this display as an explicit "Pending" state in the UI? I think that'll be less confusing than having an empty field.

**Comment by grizz** [comment]
Pending in the UI is a good idea, we'd still need a solution for how we treat it in the API as well.

**Comment by grizz** [comment]
Null in the API, can display as Pending in the UI

**Comment by job** [comment]
Current consensus is disallow NULL: http://lists.peeringdb.com/pipermail/pdb-tech/2016-December/thread.html
