### ISSUE TITLE
Add "long name" or "aka" field to 'fac' records

### ISSUE THREAD

**Issue by as44980** [peeringdb/peeringdb#902]
It appears there are users searching for facility records with two or more terms that are taken as a string, and thus do not match the particular naming convention that the facility owner has used to display their records, at least until #23 is implemented.

For example [fac record 34](https://www.peeringdb.com/fac/34) is commonly referred to as "Telehouse North" by those present in the facility, but as the fac record name is "Telehouse - London (Docklands North)" a search query for "Telehouse North" does not match.

So, taking inspiration from #787 where the "Long Name" field provided a location where alternate spellings or hypen-less variants of the IX name could be added to avoid changing the search function, I would like to propose a similar field for fac records.

This is also comparable to the "Also Known As" field in the net records which also appears to provide a means to reflect alternate names which the network may be known by, in this case typically used to include historical names and other entities which may have been merged into this network.

Hence not only would adding a similar filed to fac records help make it easier for users to locate facilities by their common names, this should also help to reflect the fact many facilities have had more than one owner over their lifetime :)

**Comment by arnoldnipper** [comment]
+1 for both fields. @peeringdb/pc, what do you think?

**Comment by job** [comment]
Sounds good

**Comment by grizz** [comment]
+1, and let's normalize that across the objects

**Comment by arnoldnipper** [comment]
**Summary**

- add fields `aka` and `name_long` to object `fac`, `ix`, `net`, and `org`
