### ISSUE TITLE
Drop `dot1q_support` field

### ISSUE THREAD

**Issue by as44980** [peeringdb/peeringdb#903]
I cnat find any explaination for how this flag should be used, and suggest it could benefit from calrification in the form of tool tip text as was implimented for the 'never-via-routeservers' flag #759..

For me it is unclear if this flag being ticked mean the 'ix' (and thus 'ixlan') COULD be delivered as dot1q tagged frames, or that it MUST be?

And, feel free to suggest a separate issue, but is there any value in providing IX's with a means to specify the dot1q tag which would be used to deliver these frames if 'dotq1' is either optional or mandatory?

**Comment by job** [comment]
Good find, I am not entirely sure what it is suppose to mean either

**Comment by arnoldnipper** [comment]
+1 for a tool tip.

**Comment by martinhannigan** [comment]
> I cnat find any explaination for how this flag should be used, and suggest it could benefit from calrification in the form of tool tip text as was implimented for the 'never-via-routeservers' flag #759..
> 
> For me it is unclear if this flag being ticked mean the 'ix' (and thus 'ixlan') COULD be delivered as dot1q tagged frames, or that it MUST be?
> 
> And, feel free to suggest a separate issue, but is there any value in providing IX's with a means to specify the dot1q tag which would be used to deliver these frames if 'dotq1' is either optional or mandatory?

If multiple people can't figure out what its used for and it serves little automation function perhaps a better route would be deletion of it? -1 tool tip.

**Comment by leovegoda** [comment]
> +1 for a tool tip.

What should the tool tip say? What is the field meant to mean?

**Comment by arnoldnipper** [comment]
**Summary**
Provide a tooltip for the "DOT1Q" flag (API `dot1q_support`).

The API suggests that this flag indicates whether tagged VLANs are supported. However, when looking at actual settings (675 false, 183 true) this can't be true. 100% of all switches support VLAN tagging.

A different interpretation would be whether the VLAN is tagged by default towards the customer. However, then `dot1q_support` is misleading.

+1 for dropping the field

**Comment by ynbrthr** [comment]
+1 for dropping it

**Comment by arnoldnipper** [comment]
**Summary**
As it is unclear what the meaning of the field "DOT1Q" (API `dot1q_support`) is,
- it will be dropped asap
- existing values will be set to "false" with next release

**Comment by egfrank** [comment]
Just to be clear, we cannot hard remove the field from the api until [v3 of the api](https://github.com/peeringdb/peeringdb/issues/625)

For now we can:
- make that field readonly on the API and set the field to False
- remove the field from the Internet Exchange ui
- update the field description to indicated that it is a deprecated field


Once we release v3 of the API we can:
- Drop the field from the API
- Drop the field from the database
