### ISSUE TITLE
2FA Backup Tokens language doesn't seem correct

### ISSUE THREAD

**Issue by ccaputo** [peeringdb/peeringdb#908]
The 2FA Backup Tokens language is:

```Backup tokens can be used when your primary and backup phone numbers aren't available. The backup tokens below can be used for login verification. If you've used up all your backup tokens, you can generate a new set of backup tokens. Only the backup tokens shown below will be valid.```

That language doesn't sense to me given the OTP method we are using - Time-based One-time Password (TOTP) - does not involve phone numbers.  Am I not understanding something?

**Comment by grizz** [comment]
Err, you're correct, and that's definitely a bug.

**Comment by ccaputo** [comment]
> That language doesn't sense to me [...]

Can we now take a moment to laugh at my bug report about language not making sense, itself containing language that is a mistake? LoL.
