### ISSUE TITLE
Add Carrier Record Type

### ISSUE THREAD

**Issue by mustangthz** [peeringdb/peeringdb#909]
Hello PDB Team,

I'd like to request that we add a new object type: Carrier.

It could be related to both the IX and FAC objects.  Lots of discussion needed in terms of how relations would work, etc.

But I'd really like to add the capabilities to document what carriers are at what facility and IXP.

**Comment by job** [comment]
Is this issue intended to provoke discussion on what the definition of a "Network" is?

**Comment by mustangthz** [comment]
> Is this issue intended to provoke discussion on what the definition of a "Network" is?

Actually no, it's meant to leverage PeeringDB as a carrier list for Facilities and a "reseller/transport" list for IXPs.

An effort to actually add value vs rejecting people.

**Comment by job** [comment]
Gotcha.

At EPF 2019 I suggested the PDB 'object type' data model should perhaps be reviewed to pave the way for more types of operations to be documented in PDB.

[Snijders_EPF2019_blurring_lines_ixp_isp.pdf](https://github.com/peeringdb/peeringdb/files/5732618/Snijders_EPF2019_blurring_lines_ixp_isp.pdf)

**Comment by arnoldnipper** [comment]
> Gotcha.

You simply tried to blur the line between `ixp` and `net` but did not contribute to an extension. A `carrier` object perfectly makes sense.  Especially, as this gives a lot of new relations.

**Comment by arnoldnipper** [comment]
@peeringdb/pc; please take a **closer** look

**Comment by job** [comment]
> > Gotcha.
> 
> You simply tried to blur the line between `ixp` and `net` but did not contribute to an extension. A `carrier` object perfectly makes sense. Especially, as this gives a lot of new relations.

Hmmmm, the slides suggest otherwise. I brought up "optical transport providers" as an example of something that doesn't fit the current model.

**Comment by arnoldnipper** [comment]
> > > Gotcha.
> > 
> > 
> > You simply tried to blur the line between `ixp` and `net` but did not contribute to an extension. A `carrier` object perfectly makes sense. Especially, as this gives a lot of new relations.
> 
> Hmmmm, the slides suggest otherwise. I brought up "optical transport providers" as an example of something that doesn't fit the current model.

They do not. The basic line of your presentation is: **Anyone should be able to self-declare “I am an Exchange” or, “I am an IP service provider**

And  this simply doesn't work. There has to be a **common** understanding what an **IXP** and what an **ISP** is.

**Comment by job** [comment]
I'd like to better understand what is meant with "Carrier", the word seems to mean different things to different people in the global community. It would be helpful to iterate which technologies are in use and how they are applied.

Many IP networks call themselves "carriers".

I think focus on technological interconnection models is another way to solve these categorization issues.

**Comment by arnoldnipper** [comment]
> Many IP networks call themselves "carriers".

Sure. And they most likely are.

* A carrier is an organisation who provides a transparent OSI layer 1/2 connections between point A and point Z

**Comment by mustangthz** [comment]
> I think focus on technological interconnection models is another way to solve these categorization issues.

My thought process was that "carriers" or facilities could announce carrier presence in a few ways:
1) Facility based DF
2) Leased DF
3) Wave/Lit L1ish
3) Ethernet 
3a-z flavors of ethernet handoff?

On the IXP Side
1) Reseller VLANs
2) L2 connectivity to FAC for IXP connection

Obviously lots to think through, but I think it would be a good space for PDB to get into.

**Comment by leovegoda** [comment]
If we were to go ahead with this enhancement, how should the new `carrier` object differ from existing objects? Also, is it possible to separate the design and development of the new object from any policy or process needed to support users who want to create `carrier` objects?

**Comment by job** [comment]
I think from a 'peeringdb API technology and concept perspective' a `carrier` object would be very much like a `facility` object. In terms of peeringdb development effort I'd probably gauge it to be in the ballpark of "a copy of the facility object type" called `carrier`. And similar wizard & search properties related to the facility type.

**Comment by arnoldnipper** [comment]
IMO the `carrier` object differs from the `fac` object. I would expect that the `carrier` object has information about what transport technologies are supported. E.g. Ethernet, DF, Waves, you name it. So it's more like the `ix` object. And besides the `carrier` object we would also have
- `netcarrier`: `net` is reachable via `carrier`
- `ixcarrier`: carrier provides transport to `ix`
- `carrierfac`: `carrier` is available in `fac`

Does that make sense?

**Comment by martinhannigan** [comment]
Not. Not at all. None of this is in english so any of us who haven't been
buried in PDB for the last five years can understand it.

**Comment by arnoldnipper** [comment]
> None of this is in english so any of us who haven't been buried in PDB for the last five years can understand it.

IMO new objects should be in line with what we already have.
- `netcarrier` corresponds to `netfac` and `netixlan`
- `ixcarrier`corresponds to `ixfac`
- `carrierfac` corresponds to `ixfac` and `netfac`

Neither of them is in English as well.

**Comment by martinhannigan** [comment]
The question I would have is what is the business purpose of the carrier
object? Is it to existence of a carrier network so it can then be bound to
a facility, presumably a fac record?

**Comment by mcmanuss8** [comment]
@ynbrthr  can you weigh in here? I know you were scoping this out.

> The question I would have is what is the business purpose of the carrier object? Is it to existence of a carrier network so it can then be bound to a facility, presumably a fac record?

@martinhannigan my understanding is it's to represent organizations that offer Layer 1/2 services vs a network which generally offers Layer 3 services. @arnoldnipper  is proposing a data model that we would let such an org say they offer such services to reach a given network, a given ix or a given facility. Much like a given network can do now.

There's lots of ways we could implement this, this is just one proposal that's fairly similar to the way peeringdb is currently structured (we have a netix object to say a network can reach an ix. A netfac object to say a network can reach a facility. An ixfac object to say an ix can reach a facility, etc).

**Comment by martinhannigan** [comment]
Thanks @mcmanuss8. Going back to the top of the thread @mustangthz seems to say he simply wants to be able to relate a carrier to a facility.  See https://www.peeringdb.com/fac/7878 and notes for what I would like to see us avoid doing by implementation of such an object. @mustangthz may have additional thoughts.

**Comment by arnoldnipper** [comment]
> I'd like to request that we add a new object type: Carrier.

@martinhannigan, that is what @mustangthz is proposing in this issue. And in my [earlier post](https://github.com/peeringdb/peeringdb/issues/909#issuecomment-781669317) I've ironed out how this could look like.

**Comment by arnoldnipper** [comment]
> See https://www.peeringdb.com/fac/7878 and notes for what I would like to see us avoid doing by implementation of such an object.

Why, @martinhannigan?

**Comment by martinhannigan** [comment]
@arnoldnipper you should direct those questions to Mr. @mustangthz since he made them. Thanks.

**Comment by mcmanuss8** [comment]
> Thanks @mcmanuss8. Going back to the top of the thread @mustangthz seems to say he simply wants to be able to relate a carrier to a facility. See https://www.peeringdb.com/fac/7878 and notes for what I would like to see us avoid doing by implementation of such an object. @mustangthz may have additional thoughts.

One reason I tagged @ynbrthr  is he had proposed something similarly previously, partially because there existed carriers who offered services to connect to IXes. I think we're all in agreement we want carrier <=> facility representation. Let's see if there exist use cases for carrier <=> ix and carrier <=> network or reasons to explicitly not want to model them here.

**Comment by arnoldnipper** [comment]
> @arnoldnipper you should direct those questions to Mr. @mustangthz since he made them. Thanks.

Looks like I misunderstood "... and notes for what I would like to see us avoid doing ..."

**Comment by arnoldnipper** [comment]
use cases for carrier <=> ix: IX resellers

**Comment by mustangthz** [comment]
The point of the request was to inventory what L1/L2 carriers are present at a Facility and what L1/L2 resellers are available for an iX.  I don't really see the point for Networks.

**Comment by ynbrthr** [comment]
> use cases for carrier <=> ix: IX resellers

yep, and that's what started that conversation

> The point of the request was to inventory what L1/L2 carriers are present at a Facility and what L1/L2 resellers are available for an iX. I don't really see the point for Networks.

to let networks signal that they reach an ix thru a given carrier?

**Comment by martinhannigan** [comment]
who cares about Ix’s? its about interconnection opportunity.

**Comment by mustangthz** [comment]
Yan,

I’m not sure that we want to inventory what IX participant rides on what carrier in PDB, that’s more of a contractual relationship.

I see Fac and IX.

-Chris

**Comment by ynbrthr** [comment]
> Yan, I’m not sure that we want to inventory what IX participant rides on what carrier in PDB, that’s more of a contractual relationship. I see Fac and IX.
> […](#)

yeah, agreed, that one is not a credible use case

**Comment by arnoldnipper** [comment]
> I see Fac and IX.

Would the last one need (carrier, fac, ix) then? I.e. while carrier and ix are both in fac1 and fac2, the carrier may only handoff connection to ix in fac1.

**Comment by leovegoda** [comment]
What is the status of this discussion? Do we want to create a `carrier` object and update a subset of other objects?

**Comment by arnoldnipper** [comment]
> What is the status of this discussion? Do we want to create a `carrier` object and update a subset of other objects?

IMO this discussion is still ongoing. Esp. if we create `carrier` how it should look like and which composed objects (`ixcarrier` and `carrierfac`) we also need.

**Comment by leovegoda** [comment]
It would be good to get input from the rest of @peeringdb/pc on this. If there's consensus, perhaps we could schedule this for 2.28.0?

**Comment by leovegoda** [comment]
When the @peeringdb/pc met at the start of April it discussed this issue and I agreed to draft some strawman text for discussion. The wording of this text needs to be refined and we need input on whether this is something we should be doing. If there is interest, we would like to hold one or more focus group sessions where we gather input to help us get a better understanding of user needs and the structures that would best meet them.

**Strawman text for discussion**
> Many facilities have high capacity links between them, allowing networks in one facility to connect to other parts of their own network or interconnect with another network in another facility. At the moment, this information is not visible in PeeringDB. 
> 
> Users researching interconnection decisions need to consult multiple data sources to find this information. Providing a structure to share this information could enable users to make better informed decisions when planning their interconnection strategies.
> 
> Should we create a data structure to allow organizations managing these inter-facility links to declare that they have a presence in an existing facility? If we did this, how detailed would the information need to be to be useful to potential users? How should it be structured?
> 
> We are not aware of security or privacy issues.

**Comment by leovegoda** [comment]
The PC ran two focus groups at the end of June. The discussion and next steps were summarized in [this blog post](https://docs.peeringdb.com/blog/carrier_object/). This issue will be updated when there is a decision on whether to create a new object type. If there is a decision to proceed there will be further engagement with PeeringDB users over the design and name.

**Comment by as44980** [comment]
Given this relates closely to the fac records, would it make sense to impliemt #1110 prior to adding this functionality?
