### ISSUE TITLE
ASN authentication workflow question/suggestion

### ISSUE THREAD

**Issue by FliesLikeABrick** [peeringdb/peeringdb#910]
Hello, I am opening this issue at the suggest of PDB support so that this may be reviewed/discussed:

We recently enrolled a new ASN into our Organization within PeeringDB.  As part of this, we received an e-mail from PDB staff indicating that in the case of an RDAP/Whois mismatch with the e-mail address on file for the account trying to add the new ASN, that PDB's process is to e-mail the requestor and request one of the following:
- An update to Whois so that the PDB requestor's e-mail address matches
- An e-mail that is sent from one of the addresses on file.

The latter seems like it could have a weakness, which I wanted to raise and ask about.  It is as follows:
- An unauthorized requestor  submits a new ASN to PeeringDB, perhaps as part of a larger ASN hijacking
- PeeringDB staff e-mail the requestor (attacker) with the requests as described above.  This e-mail includes the list of the e-mail addresses, which are of course public in other sources as well
- The attacker can trivially craft an outbound e-mail via SMTP back to PeeringDB staff with the From: header indicating an authorized party, and reference the original thread for (the appearance of) increased authenticity
- PeeringDB approve the request for the attacker to maintain the ASN in PeeringDB

Are there other mechanisms in PeeringDB's workflows that prevent this from occurring?  In my case I did need to use an alternate SMTP server to send the requested validation e-mail (as the inbound alias is not available for outbound messages via our Exchange server), and it caused me to think about the potential for abuse.

If not, it would seem a better workflow may be:
- E-mail the trusted e-mail addresses and ask them to authorize the requested changes (or update Whois), without CCing the potential attacker.  
- The recipient makes the changes, or sends a validation reply (which does not need to come from the requested address to serve its purpose, as PDB will know that the authorized approver received the first message as long as it is quoted or a token is referenced); or  indicates that the request was unauthorized
- PeeringDB staff take the appropriate action

Relying on receipt of an e-mail by a trusted party seems it may be a better authentication process than e-mailing a possible attacker and asking them to prove they can send a message appearing as a trusted source.  That is, being able to receive an e-mail and act on that is a better authentication mechanism than asking someone to synthesize an e-mail from a particular source e-mail address.

As a convenient side-effect, this also helps with organizations such as ours who list role accounts in Whois, and whose staff may not be able to generate outbound messages sourced from those addresses easily (such as us, as mentioned above, due to a recent e-mail system migration preventing us from sending messages from certain domains; but we can receive messages at the other domains)

**Comment by job** [comment]
Thanks for your feedback!

You are right that the workflow is not optimal. Some volunteers are working on a proposal to use cryptographic verification through the RPKI which (after implementation) will completely eliminate the need for email-based verification. This is a rather big project as it touches upon many aspects of PeeringDB, stay tuned!

**Comment by martinhannigan** [comment]
If there is a way to link RPKI with an object in general this seems like a
good idea. I'm very interested to see some high level details and expand
consensus. If it's cheap, fast and easy without a lot of burden on object
owners, the AC and users that would be even better.

**Comment by leovegoda** [comment]
The Product Committee has decided to close this issue. There was no agreement on the concept and the issue has not been discussed for six months or longer.
