### ISSUE TITLE
higher quality Logo

### ISSUE THREAD

**Issue by herbetom** [peeringdb/peeringdb#911]
The logo used on the website unfortunately looks blurry (even on my not super high resolution FullHD Monitor).

I wonder if it is available in a higher resolution, maybe it is possivle to embed it as SVG?

Main reason for the issue is that I would like to have peeringdb as thumbnail for [andOTP](https://github.com/andOTP/andOTP/). They seem to just use SVGs, but I couldn't find one. Therefore the issue ;)

I found the Logo at the following Places:

#### square Logo, color:
- https://github.com/peeringdb/peeringdb/blob/master/peeringdb_server/static/pdb-logo-square-coloured.png ([used](https://github.com/peeringdb/peeringdb/blob/af6974e3d3b08bf76a4082164190c49a78c4846b/peeringdb_server/templates/site/header.html#L30))
- https://github.com/peeringdb/peeringdb/blob/master/peeringdb_server/static/favicon.ico ([used](https://github.com/peeringdb/peeringdb/blob/af6974e3d3b08bf76a4082164190c49a78c4846b/peeringdb_server/templates/site/header.html#L33))
- https://github.com/peeringdb/docs/blob/master/peeringdb_theme/img/favicon.ico (used, same as other, just other Repo)

#### with Text, white:
- https://github.com/peeringdb/peeringdb/blob/master/peeringdb_server/static/pdb-logo-coloured-white.png

#### with Text, color:
- https://github.com/peeringdb/peeringdb/blob/master/peeringdb_server/static/pdb-logo-coloured.png ([used1](https://github.com/peeringdb/peeringdb/blob/af6974e3d3b08bf76a4082164190c49a78c4846b/peeringdb_server/templates/site/header.html#L17-L18), [used2](https://github.com/peeringdb/peeringdb/blob/af6974e3d3b08bf76a4082164190c49a78c4846b/peeringdb_server/templates/site/header.html#L82))
- https://github.com/peeringdb/docs/blob/master/peeringdb_theme/img/pdb-logo-coloured.png ([used](https://github.com/peeringdb/docs/blob/b2e3a06f049ec973ec0afb90f9de91091564cf0f/peeringdb_theme/main.html#L8), same as other, just other Repo)
- https://github.com/peeringdb/peeringdb/blob/master/peeringdb_server/static/pdb-logo-rect-coloured.png ([used](https://github.com/peeringdb/peeringdb/blob/af6974e3d3b08bf76a4082164190c49a78c4846b/peeringdb_server/templates/site/header.html#L17-L18), just blown up logo, not actually higher resolution)

cc @ghankins , @grizz (You seem to have contributed above mentionend Versions of the Logo)

**Comment by ghankins** [comment]
There are several issues here that we need to look into.

1. https://github.com/andOTP/andOTP/issues/715: I uploaded an SVG image for them to use.
2. We need to review all of the logos mentioned above and where they are used.  I expect some aren't used and should be removed.
3. We need to replace the PNGs that we determine should be kept with SVGs.

I will follow up with the PC on scheduling 2. and 3.

**Comment by herbetom** [comment]
I was a bit worried that the logo might not exist as a vector graphic because the PNGs are all in various stages of blurry. But, fortunately, that was unnecessary.

Whether I have listed all the logos, I do not know. Maybe there are others. I added to the Inital Comment the reference where those are used (at least those are the locations i found on a quick search).

I don't know if https://github.com/peeringdb/peeringdb/blob/master/peeringdb_server/static/pdb-logo-coloured-white.png is used. 

Probably just the [Main Logo on the Site](https://github.com/peeringdb/peeringdb/blob/af6974e3d3b08bf76a4082164190c49a78c4846b/peeringdb_server/templates/site/header.html#L82) can be replaced with an SVG. And even here, a fallback PNG maybe is necessary (I don't know the current state of SVG support in browsers).

But the least that could be done is to Render the PNGs in the correct resolution and not just Resize a smaller one :slightly_smiling_face:

**Comment by ghankins** [comment]
Thanks @herbetom , we'll take a look at all of the logos.

**Comment by arnoldnipper** [comment]
@ghankins where does @peeringdb/outcom stand here?

**Comment by ghankins** [comment]
> @ghankins where does @peeringdb/outcom stand here?

It would be great to make these changes at our next opportunity.

We need to review all of the logos mentioned above and where they are used. I expect some aren't used and should be removed.
We need to replace the PNGs that we determine should be kept with SVGs.

**Comment by arnoldnipper** [comment]
> It would be great to make these changes at our next opportunity.

@ghankins and @peeringdb/outcom do you need any help? Do we have to reach out to the sponsors? Or has that been done already? What's missing?

I can clearly identify what needs to be done. However, I don't see where we are.

**Comment by ghankins** [comment]
> @ghankins and @peeringdb/outcom do you need any help? Do we have to reach out to the sponsors? Or has that been done already? What's missing?
> 
> I can clearly identify what needs to be done. However, I don't see where we are.

"We" in this case means someone on the development team or someone who has a development instance and can check the HTML references to the logos mentioned in the first comment.  The logos are all PeeringDB logos, the issue has nothing to do with sponsor logos.

**Comment by ghankins** [comment]
This comment tracks the changes needed to each image.

square Logo, color:

    https://github.com/peeringdb/peeringdb/blob/master/peeringdb_server/static/pdb-logo-square-coloured.png
    https://github.com/peeringdb/peeringdb/blob/master/peeringdb_server/static/favicon.ico: no changes, it's in the format required for favicon.ico
    https://github.com/peeringdb/docs/blob/master/peeringdb_theme/img/favicon.ico: no changes, it's in the format required for favicon.ico

with Text, white:

    https://github.com/peeringdb/peeringdb/blob/master/peeringdb_server/static/pdb-logo-coloured-white.png

with Text, color:

    https://github.com/peeringdb/peeringdb/blob/master/peeringdb_server/static/pdb-logo-coloured.png
    https://github.com/peeringdb/docs/blob/master/peeringdb_theme/img/pdb-logo-coloured.png: changed with commit https://github.com/peeringdb/docs/commit/04b44af097e9efc1d294f0b587999e042abcc6f8
    https://github.com/peeringdb/peeringdb/blob/master/peeringdb_server/static/pdb-logo-rect-coloured.png

**Comment by martinhannigan** [comment]
Greg do we have a style guide for image and branding?

Tks

**Comment by herbetom** [comment]
Great to see progress here :+1: 

You might want to add a `-` to get the Checkboxes from GitHub: 

```
- [x] Check this
```

- [x] Check this

**Comment by ghankins** [comment]
> Greg do we have a style guide for image and branding? Tks

We don't have a style guide, it hasn't come up.  We're super easy and work on any logo questions or requests that we get individually.

**Comment by arnoldnipper** [comment]
@peeringdb/outcom, can you please finalize this?

**Comment by leovegoda** [comment]
Higher resolution logos are being produced and will be deployed in updated UX

**Comment by ghankins** [comment]
> Higher resolution logos are being produced and will be deployed in updated UX

We should already have SVG formats for all of the PeeringDB logos.  What ones are "being produced"?

**Comment by leovegoda** [comment]
> > Higher resolution logos are being produced and will be deployed in updated UX
> 
> We should already have SVG formats for all of the PeeringDB logos. What ones are "being produced"?

Looks like we can use the SVG ones. Thanks for pointing me at them!

**Comment by leovegoda** [comment]
Closing as we have the logos we need
