### ISSUE TITLE
Allow change of ixpfx mask for PDB Admins

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/peeringdb#912]
DOTF policy currently prevents from changing a Peering LAN prefix (aka ixpfx). While the deletion of an `ixlan` objects also involves the deletion of all `netixlan` objects with that `ixlan_id` this is not the case for `ixpfx`. 

To enlarge the LAN prefix mask, currently, these steps have to be performed

 * save `netixlan` objects
 * delete `netixlan` objects
 * delete `ixpfx` object
 * create a new `ixpfx`object
 * re-create the `netixlan` objects
 
If @peeringdb/ac could change the mask this would be a single and quick operation 

@peeringdb/pc and @peeringdb/ac, what do you think?

**Comment by peterhelmenstine** [comment]
Makes sense to me +1

**Comment by netravnen** [comment]
> To enlarge the LAN prefix mask, currently, these steps have to be performed

An alternative approach I've used before has been when handling an `ixpfx` ticket using the Admin (`/cp`) UI.

1. Check `netixlan` objects with new mask exists. (If e.g. a network has had added two `netixlan` objects for both new and old `ixpfx`, the renumber action in the admin UI will fail for these specific entries, as new `netixlan` entry already exist)
2. Change old `ixpfx` to new `ixpfx` (with the wrong mask, e.g. /24 to /24).
3. Change `ixpfx` mask from wrong to correct size (e.g. /24 to /23)

**Comment by arnoldnipper** [comment]
> An alternative approach I've used before has been when handling an `ixpfx` ticket using the Admin (`/cp`) UI.

That doesn't help when enlarging the mask.

**Comment by arnoldnipper** [comment]
@peeringdb/pc please give +1 as this is an @peeringdb/ac issue only

**Comment by mcmanuss8** [comment]
+1

**Comment by job** [comment]
+1

**Comment by grizz** [comment]
Finalized, but waiting on #924

**Comment by vegu** [comment]
#924 has been approved and estimated and is now ready to implement - i think it implements all the functionality requested here and #912 can thus be closed
