### ISSUE TITLE
API should do an IP6 address instead of a string match

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/peeringdb#913]
```bash
curl -sG https://peeringdb.com/api/netixlan --data-urlencode ipaddr6=2001:7f8:f2:e1:0:af21:3376:1 | jq '.data[].asn'
213376
```
but
```bash
curl -sG https://peeringdb.com/api/netixlan --data-urlencode ipaddr6=2001:7f8:f2:e1::af21:3376:1 | jq '.data[].asn'
```

@peeringdb/pc, please +1

**Comment by job** [comment]
totally!

+1

**Comment by arnoldnipper** [comment]
Interestingly, if you change 2001:7f8:f2:e1:0:af21:3376:1 to 2001:7f8:f2:e1::af21:3376:1, the system changes it back to 2001:7f8:f2:e1:0:af21:3376:1. Maybe we should also normalise how IPv6 addresses are stored. E.g. lower-case and compress consecutive "0"s to "::" from right to left.

**Comment by leovegoda** [comment]
RFC 5952 "defines a canonical textual representation format" for IPv6 addresses. While any valid format should be fine for input, and the format used for storing addresses doesn't matter, using this format for output would be helpful.

**Comment by job** [comment]
In addition to canonicalization for both input and output, the search queries input would need to conform to "Longest Prefix Match" (LPM) to avoid POLA

**Comment by ynbrthr** [comment]
+1

**Comment by egfrank** [comment]
Summary
- Normalize how IPv6 addresses are stored in the database
- Normalize existing IPv6 addresses in our database through a script
- Also normalize any ipv6 addresses in search filters upon lookup, so different formats of the same ipv6 address will return the same results


We could look at switching the db to postgres for native ip address types as well, which would enforce these constraints at the db level
