### ISSUE TITLE
Translation for the new 2FA Settings

### ISSUE THREAD

**Issue by gordon-shumway-net** [peeringdb/peeringdb#914]
Hey together,

the section under "https://beta.peeringdb.com/account/two_factor/" seems not fully available to be translated on Weblate.
Also if we click on "Show-Codes" when 2FA is configured, the text is not available to be translated.
The Button "Manage Two-Factor Authentication" under "https://beta.peeringdb.com/profile" is translated, but almost everything behind it not.

In the Organization (https://github.com/peeringdb) as an example I couldn't find any source code in regard to the string "Disable Two-Factor Authentication".
On the other hand, there are also some where the source code seems to be right, as an example the string "Backup Tokens":
https://github.com/peeringdb/peeringdb/blob/3c412a8c8cb5324ff81e8cc83ed96b3b07ba3f90/peeringdb_server/templates/two_factor/core/login.html
(Strg+F for Backup Tokens).

Can someone check that?
If more information is necessary just hit me. ;)

Gordon :)

**Comment by arnoldnipper** [comment]
@peeringdb/20c, resp @vegu and @grizz. IMO, this is a general issue/question. I.e. how do we make sure that all strings are quoted as to be translated?

Or did I misunderstand this issue completely? @peeringdb/pc what's your opinion?

**Comment by grizz** [comment]
That looks to be done: https://github.com/peeringdb/peeringdb/tree/master/peeringdb_server/templates/site/profile-2fa.html

So it just needs to be translated at https://translate.peeringdb.com/

**Comment by mcmanuss8** [comment]
Seems like we need some process to nudge our volunteer translators when we add/change strings

**Comment by leovegoda** [comment]
> Seems like we need some process to nudge our volunteer translators when we add/change strings

Is there an existing process with a bug or do we need a new feature?

**Comment by leovegoda** [comment]
The Product Committee has decided to close this issue. There was no agreement on the concept and the issue has not been discussed for six months or longer.
