### ISSUE TITLE
To force or not to force www, that is a question

### ISSUE THREAD

**Issue by netravnen** [peeringdb/peeringdb#916]
PeeringDB.com uses star-cert and domain record. I.e. `*.peeringdb.com`

Currently, both these front-page URI's can be accessed.
- https://peeringdb.com
- https://www.peeringdb.com

A downside of not forcing www or non-www URI is amongst others (in no particular order):
- Cookies currently not shared between domains. E.g.
  - Access https://peeringdb.com, login, then go to https://www.peeringdb.com, now you have not logged in. As cookies are not shared between URI's.
- SEO-ranking takes a downturn.
  - The above scenario is against BCP. Which is to either force www or non-www domain.
  - E.g. /ix/1 is indexed twice.

**Comment by netravnen** [comment]
Personally, I vote for forcing www prefix over non-www.

**Comment by leovegoda** [comment]
Do our web stats distinguish the proportion of people accessing https://peeringdb.com versus https://www.peeringdb.com? It would be helpful to know if there is a significant difference between the two. That might help us make a decision on what to do.

**Comment by arnoldnipper** [comment]
> Do our web stats distinguish the proportion of people accessing https://peeringdb.com versus https://www.peeringdb.com? It would be helpful to know if there is a significant difference between the two. That might help us make a decision on what to do.

The web stats only show the relative URL. So, evaluating the stats doesn't help.

**Comment by grizz** [comment]
I generally dislike the `www` prefix, but I agree it should be forced one way or another, so +1 to whatever consensus is.

**Comment by arnoldnipper** [comment]
> I generally dislike the `www` prefix, but I agree it should be forced one way or another, so +1 to whatever consensus is.

+1

**Comment by mcmanuss8** [comment]
+1 to www also because it'll make leveraging a CDN for full site delivery easier. IIRC, top level records can't be CNAMEs so we'll not be able to use DNS based CDNs unless we use something.peeringdb.com for CDN hosted objects. Obviously we could just do that w/ static content (static.peeringdb.com) but if we ever wanted full site delivery, this would be a blocker.

**Comment by job** [comment]
+1 to `www`

**Comment by netravnen** [comment]
> +1 to www also because it'll make leveraging a CDN for full site delivery easier.

A very sound operational argument. 💯

> top-level records can't be CNAMEs so we'll not be able to use DNS based CDNs

Personally, I'm for `www`. Amongst other reasons due to this (above) argument...

- Why (prematurely) limit the number of CDN's PeeringDB can potentially "scale-out" to (as a customer)...(?)
- Thinking back, I understand why top internet websites rarely use non-`www` address as the primary one. (Twitter using non-`www` sticks out a bit amongst large (to me) social media sites.)

**Comment by amartins** [comment]
+1 to `www`

**Comment by egfrank** [comment]
Summary
- Force the URI of peeringdb to use www, i.e. `https://www.peeringdb.com`
