### ISSUE TITLE
Re-entering a deleted netixlan fails with poor error message

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/peeringdb#925]
As with all DB objects `netixlan` objects are not deleted but only set status `deleted`. A network which gets the same `ipaddr4` (my best guess) will be re-assigned the deleted object and should be able to update it. However, this fails from time to time.

The object in question is
```json
{
  "id": 22741,
  "net_id": 6749,
  "ix_id": 64,
  "name": "NL-ix: Main",
  "ixlan_id": 64,
  "notes": "",
  "speed": 20000,
  "asn": 133229,
  "ipaddr4": "193.239.116.176",
  "ipaddr6": "2001:7f8:13::a513:3229:1",
  "is_rs_peer": false,
  "operational": true,
  "created": "2015-04-17T00:00:00Z",
  "updated": "2017-09-18T14:24:53Z",
  "status": "deleted"
}
```

The new network tried to update with (see also the DeskPRO [ticket](https://peeringdb.deskpro.com/agent/#app.tickets,inbox:archive_resolved,t.o:54112,vis:6))
![20210126 PeeringDB 00](https://user-images.githubusercontent.com/16888757/105853150-a8dae780-5fe5-11eb-990d-f8311b0d8fec.jpg)

When trying to update via the API I got
```json
{
  "asn": [
    "This entity was created for the ASN 133229 - please remove it from this network and recreate it under the correct network"
  ],
  "meta": {
    "error": "Bad Request"
  }
}
```

Workaround: directly change via the [AC GUI](https://peeringdb.com/cp/peeringdb_server/networkixlan/22741/change/)

@peeringdb/ac, did you run into this situation before? @peeringdb/pc, please +1 as clearly a bug

**Comment by ynbrthr** [comment]
+1

**Comment by arnoldnipper** [comment]
@peeringdb/ac, please make up your mind. As this is an AC-flagged issue, your votes counts also

**Comment by peterhelmenstine** [comment]
+1 Bad request could have a better explanation as to why.

**Comment by grizz** [comment]
+1

**Comment by DarwinCosta** [comment]
+1

**Comment by leovegoda** [comment]
Changed milestone and losing as @20c-ed have confirmed that this bug cannot be reproduced

**Comment by netravnen** [comment]
@leovegoda To be honest, I have recently encountered this multiple times over the last weeks. Not specifically NETIXLANs. Instead for IXs that

1. Listed their precense in a facility (BEST FAC),
2. Deleted  their precense in BEST FAC.
3. X amount of time later, they are now back in BEST FAC and tries to add an IXFAC.
4. They are rejected in (3) due to the object created during (1) still existing in the DB. But have had the status set to DELETED during (2). And the function triggered during (3) does not account for being able to "just" the change status DELETED -> OK.

The above scenario I have had also observed for NETFACs 1-2 times.

**Comment by netravnen** [comment]
The scenario a bit different. But similar enough to look like a pattern of the functions triggered when a user tries to re-add a prior deleted connection (IXFAC, NETFAC, NETIXLAN) could be more widespread than initially observed. But low enough in volume to go under the radar most of the time.

**Comment by netravnen** [comment]
Deskpro examples for IXFAC objects, 109405, 106843, 102694, 104953.

@leovegoda Previously raised a bug report specifically concerning the IXFAC case at https://github.com/peeringdb/peeringdb/issues/1626

**Comment by arnoldnipper** [comment]
Ceterum censeo that `netfac`, `ixfac`, and `netixlan` should be completely removed from the DB, once they are deleted. There is no use of keeping them, i.e only mark them deleted. They only cause hassle ... +1
