### ISSUE TITLE
Admin user is missing the "Edit" button

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/peeringdb#930]
User "sdvcvsp" is an Admin user. However, they are missing the "Edit" buttons on their objects. As this needs immediate attention I've routed the issue through to 3a, @peeringdb/ac 

@peeringdb/ac, have you seen the same behaviour?

**Comment by arnoldnipper** [comment]
@vegu writes: For some reason, the user was in both the org admin and the org users user group - when it should be one or the other, this latest release updated the permissioning backend and it's likely its exposing this bug in this form.

**Comment by vegu** [comment]
It looks like there are ~1500 users that would be affected by this issue.

It's something we, for now, could fix via script, but this should be looked at sooner than later. 

Spot checking the code its not immediately obvious to how those users end up in both groups.

@peeringdb/pc let me know if you want me to go ahead and adjust the bugged users via script.

**Comment by arnoldnipper** [comment]
> @peeringdb/pc let me know if you want me to go ahead and adjust the bugged users via script.

+2, one with me PC hat and one with my AC hat

**Comment by arnoldnipper** [comment]
> Spot checking the code its not immediately obvious to how those users end up in both groups.

You can easily do via the AC interface as well as via the Admin when the user has sent more than one request for affiliation.

**Comment by vegu** [comment]
Maybe that is it then - however 1500 seems like a high number in that case - does that happen a lot ?

The user management interface exposed to the users on their org admin page seems to not be the cause at least.

**Comment by vegu** [comment]
Actually you are right, the public facing user management form is affected by that as well once a user has multiple affiliation requests going to an org. That makes the high number more reasonable.

The user being able to affiliate to the same org more than once seems like a bug in itself.

**Comment by arnoldnipper** [comment]
> The user being able to request affiliation to the same org multiple times simultaneously seems like a bug in itself.

iirc there was/is an issue fixing it.

**Comment by arnoldnipper** [comment]
> > The user being able to request affiliation to the same org multiple times simultaneously seems like a bug in itself.
> 
> iirc there was/is an issue fixing it.

I mixed this up with #251

**Comment by vegu** [comment]
Since that issue will be tackled in #931, i propose for the scope of this ticket we also do the following:

**summary**
- fix bugged users on production via script
- approving an affiliation request of a user that is already a member of the org should do nothing
- denying an affiliation request of a user that is already a member of the org should do nothing

**Comment by arnoldnipper** [comment]
**Release Notes**
This issue fixes a bug where a user was in both the `org.admin` and the `org` user group while it should be one or the other

**Comment by arnoldnipper** [comment]
This issue still exists. I guess, merging organisations may also trigger this behaviour. Happened yesterday for both admins of [GoeTel](https://peeringdb.com/net/19040)

**Comment by arnoldnipper** [comment]
@mcmanuss8  and @leovegoda, should definitely be fixed asap

**Comment by leovegoda** [comment]
@arnoldnipper Is the issue still identical to what was originally reported or has it changed?

**Comment by arnoldnipper** [comment]
> @arnoldnipper Is the issue still identical to what was originally reported or has it changed?

Shorter questions could trigger shorter answers ;-)  ... the issue is still identical to what was originally reported. Though, it's unclear which actions place a user into both groups (member and admin). Merging organisations definitely is one of these actions.
