### ISSUE TITLE
AC is unable to delete users

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/peeringdb#932]
@peeringdb/ac is unable to delete users (Server Error (500). I guess directly related to work on the permission system and related to #930.

Would be cool to include this into the hotfix related to #930 

@peeringdb/pc, I've routed this through to 3a directly. If you oppose, butt in.

**Comment by vegu** [comment]
This was an issue caused by the migration process used during the recent release, and should now be fixed.

@arnoldnipper please confirm when you can, thanks

**Comment by arnoldnipper** [comment]
> @arnoldnipper please confirm when you can, thanks

confirmed, @vegu

**Comment by arnoldnipper** [comment]
@vegu, now I get a "502 Bad Gateway"
