### ISSUE TITLE
Adding a network results in 500

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/peeringdb#933]
I'm trying to add ASN 139541 (City Infosol Pvt Ltd). However, this give me
- a 500 if doing it via the AC gui
- a 500 with an additional "ASN cannot be changed" if doing via the user gui

![20210205 PeeringDB 00](https://user-images.githubusercontent.com/16888757/107031835-23102680-67b3-11eb-9cfe-537b67ebadf5.png)

**Comment by vegu** [comment]
Is there an existing network with that name?

**Comment by arnoldnipper** [comment]
> Is there an existing network with that name?

yes ... thanks for the hint :)
