### ISSUE TITLE
Geocode for org is broken

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/peeringdb#937]
URL: https://maps.google.com/?q=,

It should be

![20210206 PeeringDB 00](https://user-images.githubusercontent.com/16888757/107130342-9194d780-68cc-11eb-8004-10b89987876b.png)

@peeringdb/pc, please verify and give a +1

**Comment by martinhannigan** [comment]
Why wouldn’t PDB just notify the user? How do you know they want you to fix
it? What am I missing?

**Comment by martinhannigan** [comment]
I see more clearly.

What is the source of the gc?

**Comment by arnoldnipper** [comment]
@martinhannigan, the referencing works for facilities. So, I guess it's a tiny bug only.

**Comment by mcmanuss8** [comment]
+1

**Comment by leovegoda** [comment]
Does anyone else else on @peeringdb/pc support this change? If so so, we could schedule this for release 2.27.

**Comment by arnoldnipper** [comment]
As this is bug and minor I route it thru to 3a. @vegu / @leovegoda would be nice to add this to 2.27

**Comment by vegu** [comment]
@peeringdb/pc  looks like work on #940 already fixed this issue and it appears to be no longer broken on beta.

**Comment by vegu** [comment]
this went out with the 2.26 release today, closing
