### ISSUE TITLE
Return geo-normalized fields as "suggested address" 

### ISSUE THREAD

**Issue by egfrank** [peeringdb/peeringdb#940]
Previously, on POST/PUT to a geo-enabled object, we would overwrite the provided address fields with normalized address fields, i.e. address fields returned from Google Maps API.

Instead, we will return the normalized address fields as a dictionary within the API response called "suggested_address", instead of overriding the fields on the object itself.

The UX will read `suggested_address` and prompt to the user to apply the suggestion.

**Comment by mcmanuss8** [comment]
+1 
@peeringdb/pc please vote

**Comment by grizz** [comment]
+1

**Comment by arnoldnipper** [comment]
> Instead, we will return the normalized address fields as a dictionary within the API response called "suggested_address", instead of overriding the fields on the object itself.

Could you give an example output, please

**Comment by arnoldnipper** [comment]
+1 ... still waiting for an example, @egfrank

**Comment by arnoldnipper** [comment]
**Release Notes**
In an effort to normalise addresses, the system may overwrite the user input. In case of a mismatch, the user now is prompted with a "suggested address" and either confirms or rejects. In case of rejection, the address is taken as provided by the user. Please keep an eye on what you provided and what is suggested. The suggestion may flip street name and house name as well as cut off postal codes.
