### ISSUE TITLE
Organization Merging Tool only offers the first 10 matches

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/peeringdb#941]
The Organization Merging Tool only offers the first 10 matches to pick from in the drop-down. On the other hand, there is no way to anchor the search (e.g. ^PATTERN or PATTERN$ or ^PATTERN$)

Proposal:

 * offer all matches
 * provide at least ^and $ anchors
 
  * please do this for all search fields with drop-down search results. These are all limited to 10
 
 As this is an @peeringdb/ac only issue, @peeringdb/pc please give a +1. And AC team, please comment

**Comment by grizz** [comment]
+1

**Comment by peterhelmenstine** [comment]
+1

**Comment by peterhelmenstine** [comment]
+1 Yup.

**Comment by DarwinCosta** [comment]
+1.

**Comment by alexfguimaraes** [comment]
+1

**Comment by kaycliff** [comment]
+1

**Comment by egfrank** [comment]
** Summary **
For all Admin autocomplete drop downs
- Provide a scrollbar to see all provided options
- Admins will be able to add "^" or "$" to their search terms and search will interpret those regex symbols accordingly
