### ISSUE TITLE
Evaluate non-google map/geo sources 

### ISSUE THREAD

**Issue by mcmanuss8** [peeringdb/peeringdb#946]
While doing #777 we were unhappy with the results provided by gmaps. Evaluate:
* Openstreetmaps 
* Melissa

See what the pros and cons are for each

**Comment by mcmanuss8** [comment]
@peeringdb/pc please approve

**Comment by grizz** [comment]
+1

**Comment by arnoldnipper** [comment]
+1

**Comment by job** [comment]
+1
