### ISSUE TITLE
Auto-Approve if a network is added by an Admin

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/peeringdb#951]
Currently, ASN requests are auto-approved when the RDAP call returns matching email addresses. However, when an Admin with a differing email address is requesting the addition of an additional ASN, the request has to be ACKed by AC again. This is duplicate work as the Admin with the differing email address already was authorized before either by AC or an existing Admin.

@peeringdb/pc and @peeringdb/ac does it make sense to auto-approve those requests?

**Comment by martinhannigan** [comment]
Why would there not be a single admin role that would ack and update RDAP
when changed to avoid this? Would it be better to have a role account have
final approval on whatever the others, regardless of email, do?

I realize I may be retreading. Please educate.

**Comment by arnoldnipper** [comment]
> I realize I may be retreading. Please educate.

Currently, all additions of new objects (net, fac and ix) have to be approved by AC. The exception is when we find from RDAP that the requestor's email is also listed as a contact's email at the RIR. Then the request is auto-approved.

This issue deals with the situation when an existing PeeringDB org Admin requests the addition of a new ASN and their email address does not match an email address which the RIR has on file.

Iow: the criteria for auto-approval should be: matching email *or* admin permissions to add networks

**Comment by funkestefan** [comment]
Just to make sure I fully understand your request: You want to allow an organization's authorized admin to add ANY network, even if there is no matching RDAP entry?

**Comment by arnoldnipper** [comment]
> Just to make sure I fully understand your request: You want to allow an organization's authorized admin to add ANY network, even if there is no matching RDAP entry?

Stefan, of course the org must match.

**Comment by funkestefan** [comment]
If there is a way to match the organization and new AS records, I am okay with it.

What do you think about the following idea: We generate a temporarily valid code that a network admin must add to its registry AS records, e.g., a remarks field. We could parse it and allow self-service to admins.

**Comment by arnoldnipper** [comment]
> What do you think about the following idea: We generate a temporarily valid code that a network admin must add to its registry AS records, e.g., a remarks field. We could parse it and allow self-service to admins.

Excellent! That's what AC sometimes does when users are unable to send email from addresses found at the RIR because they belong to roles/lists. However, this should be a new issue as the whole procedure need more work.

**Comment by martinhannigan** [comment]
No. I'm wondering how you can instead make it a network to network function
instead of an AC function.

**Comment by arnoldnipper** [comment]
> No. I'm wondering how you can instead make it a network to network function instead of an AC function.

@martinhannigan, it's only an AC function as it fails to get authorized by the network

**Comment by grizz** [comment]
I really don't understand this, the verification part is that $ORG is authoritative for $ASN, having an org admin be able to self verify any ASN means there's no more verification. Did you mean PDB Admin?

> What do you think about the following idea: We generate a temporarily valid code that a network admin must add to its registry AS records, e.g., a remarks field. We could parse it and allow self-service to admins.

If they can modify the AS records, why can't they temporarily add their email address?

**Comment by leovegoda** [comment]
The Product Committee has decided to close this issue. There was no agreement on the concept and the issue has not been discussed for six months or longer.
