### ISSUE TITLE
Add field "Traffic Levels" (API "info_traffic") to object ix

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/peeringdb#952]
Currently, only networks carry the field "Traffic Levels" (API `info_traffic`). Hence, IX operators most often are misusing the route server "Traffic Levels" field to indicate how much traffic is crossing the fabric. For networks of type route server or route collector, fields "Traffic Levels" and "Traffic Ratios" are meaningless.

@peeringdb/pc what do you think?

**Comment by ynbrthr** [comment]
+1

**Comment by martinhannigan** [comment]
Its meaningless for IXP fabrics as well. I think enabling IXP sword
fighting over whos bigger using PDB schema is a bad idea.

$0.02.


-1

**Comment by ynbrthr** [comment]
it's of limited usefulness, but it's not useless. Maybe at some point, most IXPs will export their traffic stats using some API (see some discussions there: https://lists.ix-f.net/pipermail/tech-discuss/2020-November/000191.html). In the meantime, looks like a god idea to provide IXPs with a traffic level field rather than have them have to use their route server's traffic level field for that.

**Comment by martinhannigan** [comment]
On Tue, Mar 16, 2021 at 7:52 PM Yan Berthier ***@***.***>
wrote:

> it's of limited usefulness, but it's not useless.
>

Who would use it? What would it be used for? Would the input be a standard
measurement or at the discretion of the IXP?

Thanks for the IX-F thread. That is an umbrella org for IXPs. It makes
sense for IXPs to sword fight in their association. :) To me, it devalues
PDB by creating consumer confusion.


Warm regards,

-M<

**Comment by job** [comment]
-1

seems to be part of an ongoing effort to equalize IX objects and Net objects. Any IX operator wishing to actually run an IP transit network can easily request an ASN from the RIR and start an IP transit business with real BGP routers! :-)

**Comment by ynbrthr** [comment]
> -1
> 
> 
> 
> seems to be part of an ongoing effort to equalize IX objects and Net objects. 

say what now?

> Any IX operator wishing to actually run an IP transit network can easily request an ASN from the RIR and start an IP transit business with real BGP routers! :-)

Are you saying you need a BGP-speaking router to have traffic graphs? As you very well know, plenty of IXPs do publish such graphs, that feature is just to make it easy for those who want to convey that information in PeeringDB. As opposed to have to use the RS' info_traffic field.

**Comment by mustangthz** [comment]
I'm not sure what value this holds. Likely be ripe for false or stale data -1

**Comment by arnoldnipper** [comment]
@peeringdb/pc, please make up your mind. Traffic at an IXP still is a metric. Hence, it should be at the right place. I.e. at the `ix` object and not at one of the RS `net` objects.

**Comment by ynbrthr** [comment]
my mind is made up. networks have a traffic field; IXPs don't; some IXPs have to resort to provide that data in their route server's network object as a workaround because of that. so let's bring that field to the ix object.

another +1 (can I vote twice? :))

**Comment by mcmanuss8** [comment]
I'm not fully supportive. Joining an IX means you peer with individual networks. In the case of some IXes that mandate peering with the route server, you peer with everyone by default. 
The traffic volume your network can expect is then dependent on your network's traffic flow to those networks you peer with, and vice versa. 

It feels like an IX's traffic volume is thus misleading if one is using it as a metric to decide if you want to join an IX or not.

Going back to the original point of the issue - if IXes feel the need to volunteer this info in an overloaded way, it would be good to determine why they feel the need to supply this information (what problem is it trying to solve for our users) and then build the issue off that.

**Comment by ynbrthr** [comment]
while all your points are very good ones (i.e., the overall traffic exchanged over an IX is probably not a good metric for you as a network to decide to join or not, most IXPs publish traffic graphs on their website. We let networks publish that traffic data, why shouldn't we let IXPs do the same?

**Comment by mustangthz** [comment]
Agree with Yan.

**Comment by martinhannigan** [comment]
If I am reading this correctly you are talking about networks who disclose
ranges of traffic and ratio requirements? BTW, you made the IKYABWAI
argument: I want it because they have it, but I don't really need it. Both
of the network measurements are vestiges of days long gone. Many are not
disclosed and others are meaningless "100TBS+". I'd argue there is also a
data accuracy issue to consider.

Traffic "level" is also easily misinterpreted. Not all IXPs use the same
measurement standard. Some are more granular. Over the years, some (like
DE-CIX for example) have been roasted for more granular metrics. However,
that granularity does provide for better performance. But when compared to
95th, it isn't for apples to apples. The majority have settled on 95th. Is
it not painfully true that the correct way to analyze the value of an IXP
is by looking at the ASN's and determining how much traffic you have
between you and N? These changes are not targeted at experienced users.
This change in particular is for marketing.

-1

I would support this if it were refocused to  :%s/Traffic Levels/ASN
Count/g instead.

**Comment by grizz** [comment]
We have discussed removing the `info_traffic` field from Networks in v3, why would we want to add it here? :)

I would prefer to -1 this and remove it from Networks!

**Comment by mcmanuss8** [comment]
@grizz  do we have an issue for that? If so, I'd propose we get consensus on removing (or not) this field from networks. If we do, then it makes sense to follow suit here. I agree we should be consistent as a matter of principal, but let's decide what we want to do on the network side then revisit IXes.

Fair?

**Comment by ynbrthr** [comment]
> If I am reading this correctly you are talking about networks who disclose ranges of traffic and ratio requirements? BTW, you made the IKYABWAI argument

Hair-splitting, but this is the MIPDWRTPPFIO) argument (most IXPs publish that data on their website, and some use the RS traffic field in PDB as we don't provide that field in the ix object).

wrt ixp traffic graphs: even not normalized (even tho most use a 5-min sampling), looking at the graphs of two ixps in a given market can tell you which one is growing and which one is losing steam. the asn count doesn't provide that historical perspective.

as for the traffic range for networks: with all its shortcomings, I've used that in the past to compare networks (ISPs) in a new market, along with other metrics. Sure, its network-provided and probably inflated for most, but gives an overall sense.

**Comment by ynbrthr** [comment]
> We have discussed removing the `info_traffic` field from Networks in v3, why would we want to add it here? :)
> 
> I would prefer to -1 this and remove it from Networks!

as said above, i've used info_traffic. i disagree it's irredeemably useless. i don't feel that strongly about it tho. if everybody else wants to remove it, i won't object (too much)

**Comment by martinhannigan** [comment]
I have nothing to add, but I'm curious. Why would an IXP hijack an
unintended field to display traffic?

Here's an example of why this isn't so great:

https://www.peeringdb.com/net/17804

And

http://yycix.net/

Certainly looks like the latter is much better - and authoritative. This is
akin to the CLLI and API discussions we're having about other fields. $0.02
and YMMV

Warm regards,

-M<

**Comment by leovegoda** [comment]
The Product Committee has decided to close this issue. There was no agreement on the concept and the issue has not been discussed for six months or longer.
