### ISSUE TITLE
Minify/merge dependencies whenever possible

### ISSUE THREAD

**Issue by mcmanuss8** [peeringdb/peeringdb#955]
As with #954 - we should minify dependencies when possible, and merge multiple files if possible.

**Comment by leovegoda** [comment]
@peeringdb/pc - is there support for doing this? We want to do some work to improve web experience in the second half of the year and this could be a good start.

**Comment by peterhelmenstine** [comment]
+1 efficiency is nice.

**Comment by arnoldnipper** [comment]
+1

**Comment by grizz** [comment]
@mcmanuss8 / @leovegoda this is already all piped through Google's closure compiler and mostly merged when possible

I would either close as done, or we can merge more as part of #1367

**Comment by mcmanuss8** [comment]
Oh turns out developer tools on chrome unminify a bit when you click on the sources. Fun. When I was clicking around previously and based on the mixed naming convention (some as min.js some as just .js) I ASSumed we didn't have much minification. Turns out you now have to click and open in a new tab to see the raw source now. 


Anyway, I think there is still some work to do here, although it's not as bad as I thought when I wrote this issue. For script resources on network tab in chrome I see: 

- recaptcha__en.js  => minified
- api.js => minified
- jquery.js => minified
- js.cookie.js => not minified
- bootstrap.bundle.min.js => minified
- showdown.min.js => minified
- purify.min.js => minified
- base64url-arraybuffer.js => not minified (but it's pretty small)
- django-security-keys.js => not minified
- twentyc.core.js => minified
- twentyc.edit.js => minified
- twentyc.filter-field.js => minified
- twentyc.sortable.js => minified
- jquery.autocomplete-light.min.js => minified
- jsi18n/ => not minified
- peeringdb.js => minified
- js => minified
- installHook.js => not minified


and on the css side:

- bootstrap.css => not minified 
- jquery.autocomplete-light.css => not minified 
- twentyc.edit.css => not minified 
- site.css => not minified

**Comment by leovegoda** [comment]
> @mcmanuss8 / @leovegoda this is already all piped through Google's closure compiler and mostly merged when possible
> 
> I would either close as done, or we can merge more as part of #1367

My view is that as minification is now a part of the process, we should close this as done.

**Comment by grizz** [comment]
There are more than I thought there that are not minified. :)

I don't think it would be all that quick catch the rest though, so I'm fine with closing it now and we'll revisit when it's time to do #1367.
