### ISSUE TITLE
api documentation generate broken

### ISSUE THREAD

**Issue by vegu** [peeringdb/peeringdb#956]
Automatic openapi schema generation used to keep the documentation at https://www.peeringdb.com/apidocs/ updated is currently not functional. 

This is likely a regression introduced by dependency / library upgrades.

**Comment by grizz** [comment]
Clear bug, pushing to 4

**Comment by vegu** [comment]
This is deployed to production, but is not yet a scheduled task - we will run manually then reach out to ops and ac to see if any tweaking is needed before it is added to cron.
