### ISSUE TITLE
Admin now have to add longitude/latitude when adding an organisation via the Admin interface

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/peeringdb#957]
When adding an organisation @peeringdb/ac now have to add longitude/latitude data. This clearly is a bug. I have hence directly routed it through to 3a. If you oppose, butt in @peeringdb/pc

**Comment by peterhelmenstine** [comment]
Agreed

**Comment by funkestefan** [comment]
Agreed, please remove this manual workflow/restriction ASAP.

**Comment by DarwinCosta** [comment]
Agree.

**Comment by Juimar** [comment]
Agree.

**Comment by vegu** [comment]
Looks like an unintended side effect from implementation of #865

**Comment by mcmanuss8** [comment]
Is this something we can hotfix @vegu  @grizz ?

**Comment by vegu** [comment]
Looking at the change that caused this, the fix is simple enough that it could go straight to prod - however it would still need a scheduled versioned rollout.

**Comment by arnoldnipper** [comment]
When could that happen earliest, @vegu and @grizz?
