### ISSUE TITLE
Add OAuth Bearer to auth0

### ISSUE THREAD

**Issue by andydavidson** [peeringdb/peeringdb#958]
Feature request: Add the PeeringDB OAuth bearer as a social connection on the 'Auth0' service.

**Comment by leovegoda** [comment]
Are you referring to this [Auth0](https://auth0.com/#!)?

**Comment by grizz** [comment]
@andydavidson see above :)

**Comment by leovegoda** [comment]
The Product Committee has decided to close this issue. There was no agreement on the concept and the issue has not been discussed for six months or longer.
