### ISSUE TITLE
ASNAUTO tool broken?

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/peeringdb#959]
The ASNAUTO tool takes a shortcut in approving network requests when the requesting email address matches any email address found in the RIR record.

However, lately, I see that an ASNAUTO email and immediately after an email that asks for manual approval. So far, I couldn't figure out when this happens.

Example:
  - [ASNAUTO](https://peeringdb.deskpro.com/agent/#app.tickets,inbox:all,t.o:56869,vis:6)
  - [Manual](https://peeringdb.deskpro.com/agent/#app.tickets,inbox:all,t:56869,t.o:56870,vis:6)
  
@peeringdb/ac did you also see such behaviour?
@peeringdb/pc I'm tempted to route this thru to 3a as this clearly looks like a bug to me

**Comment by funkestefan** [comment]
Wasn't aware of this issue until your ticket.

**Comment by peterhelmenstine** [comment]
Same, first I've seen of this issue.

**Comment by DarwinCosta** [comment]
Same here.

**Comment by vegu** [comment]
**summary**

- fix issue with ASNAuto tool sending out incorrect manual approval requests
