### ISSUE TITLE
IX-F importer: intermittent bug during consolidation of notifications

### ISSUE THREAD

**Issue by vegu** [peeringdb/peeringdb#965]
**Describe the bug**

Happens during the notification consolidation process of the importer, after importer logic is done and before notifications are sent out to parties.

```
Traceback (most recent call last):
  File "/srv/www.peeringdb.com/./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/srv/www.peeringdb.com/venv/lib/python3.9/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/srv/www.peeringdb.com/venv/lib/python3.9/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/srv/www.peeringdb.com/venv/lib/python3.9/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/srv/www.peeringdb.com/venv/lib/python3.9/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/srv/www.peeringdb.com/peeringdb_server/management/commands/pdb_ixf_ixp_member_import.py", line 269, in handle
    importer.notify_proposals(error_handler=self.store_runtime_error)
  File "/srv/www.peeringdb.com/peeringdb_server/ixf.py", line 1671, in notify_proposals
    consolidated = self.consolidate_proposals()
  File "/srv/www.peeringdb.com/peeringdb_server/ixf.py", line 1634, in consolidate_proposals
    proposals[action].append(message)
KeyError: 'noop'
```

**To Reproduce**

Happened once, the next importer run finished successfully.
While we were unable to identify the feed that caused this issue, we should still be able to fix the error above.

Best guess: During the importer logic the importer instantiated a proposal and by the time it started preparing the notifications to send it out the issue had been fixed hence turning it into a `noop` (no action required) proposal which the consolidation logic was unable to process.

**Expected behavior**

`noop` proposals should always be discarded during consolidation of notification messages, since they are not actionable.

**Who is affected by the problem?**

Exchanges and networks relying on the ix-f importer to update / suggest changes to their data.

**What is the impact?**

Intermittent ix-f import failure that went a way on the next attempt.

**Are there security concerns?**

No

**Are there privacy concerns?**

No

**What are the proposed actions?**

Code fix: `noop` proposals aren't actionable and should be excluded from the consolidation. 

**What is the proposed priority?**

unknown

**Comment by ccaputo** [comment]
> Happened once, the next importer run finished successfully.

It happened once on production _and_ once on beta, for Importer runs that both started at 0000 UTC on the same day, so it seems unlikely this was a user fix which resulted in a noop, since it seems unlikely they would have fixed entries on both prod and beta.  More possibly the JSON data changed on a subsequent pull that showed no errors, on both prod and beta, or some other change happened, or there is some unknown bug.

Not sure of priority, but I can say from an Ops perspective, it would be good to investigate further and try to fix, since the Ops time to review and re-run the Importer when this happens, is a fair amount of time.

**Comment by grizz** [comment]
Bug, and takes up ops time, pushing to 4.

FYI @peeringdb/pc

**Comment by ccaputo** [comment]
Saw this again today.  @mcmanuss8 can we make sure this is queued for fixing?  Thanks!
