### ISSUE TITLE
IX-F Importer: fix command output buffering

### ISSUE THREAD

**Issue by vegu** [peeringdb/peeringdb#967]
**Describe the bug**

output going to `stderr` can potentially end up out of order with the rest of the command output going to `stdout` making it confusing for ops / devs to debug potential issues.

This was already addressed once before in #884, however the solution that was found then appears to not be workable when running the command via cron, so maybe its time for a code based solution.

**To Reproduce**

potentially any exception raised during import can cause this issue

**Expected behavior**

all output should be displayed in order of execution

**Who is affected by the problem?**

ops / devs trying to debug ix-f import issues

**What is the impact?**

increased time spent on debugging / determining causes for ix-f import issues

**Are there security concerns?**

no

**Are there privacy concerns?**

no

**What are the proposed actions?**

Either disable buffering of output or have stdout / stderr share the same buffer

**What is the proposed priority?**

unknown

**Comment by ccaputo** [comment]
@mcmanuss8 please expedite this if able.  Thanks!

**Comment by mcmanuss8** [comment]
+1

**Comment by arnoldnipper** [comment]
+1

**Comment by arnoldnipper** [comment]
And routed thru to 3a

**Comment by vegu** [comment]
**summary**

- Disable buffering of output or have stdout / stderr share the same buffer for the ix-f importer command
