### ISSUE TITLE
Allow geolocation input as Deg Min Sec

### ISSUE THREAD

**Issue by leovegoda** [peeringdb/peeringdb#968]
This issue is based on a conversation with Peter Helmenstine.

**Is your feature request related to a problem? Please describe.**
When a facility operator has their geolocation information in degrees, minutes, and seconds instead of decimal degrees they need to manually convert to decimal degree to enter the location. The UI should accept both formats and perform the conversion for the user.

**Who is affected by the problem?**
Users entering new facilities.

**What is the impact?**
If they have accurate data in one format and have to manually convert it to another they are likely to make data entry or copy/paste errors, slowing down the registration process.

**Are there security concerns?**
No

**Are there privacy concerns?**
No

**Describe the solution you'd like**
The UI should accept an input like this: 37°43'28.1"N 122°23'51.6"W and convert it to decimal degrees for the user.

**Describe alternatives you've considered**
Another option would be to have separate inputs for each type of input but that could end up confusing users.

**Could this feature request need support from the Admin Committee?**
Consider if an administrator might need to provide assistance at any point.

**What is the proposed priority?**
We should discuss this with the @peeringdb/ac but it needs to be done as a part of our Geo Search improvements

**Provide a rationale for any/all of the above**
If a user already has accurate data in one format, asking them to manually convert it to another format could introduce errors and this is likely to delay or frustrate the user. As long as the conversion can be done accurately and deterministically in software it should be available, so that we make our users lives simpler.

**Comment by peterhelmenstine** [comment]
+1 Thank you for submitting my request

**Comment by arnoldnipper** [comment]
-1 as we don't want users to specify geolocation data directly to the DB. Why? If geolocation can't be derived from the address given, the request must pop up at @peeringdb/ac and they have to manually find out or key in the data.

**Comment by peterhelmenstine** [comment]
If an address isn't available you need to input something in order to complete an unrelated edit. If you have the lat/lon this would simply to allow for editing in both formats. Currently you can't proceed without it. Either get rid of the requirement to add lat/lon or make it friendly to enter the data.

**Comment by martinhannigan** [comment]
This issue reminds me a lot of the CLLI code issue. While lat-long is
precise, it creates extra work. It requires research. It could conflict
with corporate or other standards since you can use them in varying degrees
(see that pun?) and I'm not certain what purpose using it as a requirement
has?

In my entire career, I've never asked for or given lat long for a service
order.

Not certain if I should be in favor or not. I'll do whatever Peter says
since he asked for it. Unless of course there is a really important use for
it.

**Comment by peterhelmenstine** [comment]
I don't necessarily care about the requirement of having lat/lon (except when an address is not available). I just want it to be user friendly to enter the data if it's there.

**Comment by martinhannigan** [comment]
Good point and eye opening. How often does that happen and what doesn't
have an address? Guess it would be useful to know the purpose of the lat
long requirement?

**Comment by peterhelmenstine** [comment]
Edge datacenters in the middle of nowhere, new construction, cable landing stations (cls).

If we require an address to find it I guess lat/lon is an alternative...

But again this ticket was originally for a UI issue

**Comment by martinhannigan** [comment]
Ok cool. Thanks. Not sure why I think this was also called out as required,
but doesn't seem to help utility wise. I agree with you regarding the input
format.

$0.02

**Comment by arnoldnipper** [comment]
> If an address isn't available you need to input something in order to complete an unrelated edit.

If the system can't map the address to a known address, the user still is able to have it accepted as is. It then should be up to @peeringdb/ac to work with the user to map the address to geolocation data. Giving a hint by the user is ok. However, it never should be taken as granted

**Comment by peterhelmenstine** [comment]
From the user's interface that's correct it can be submitted (with some cosmetic issues) but not from the admin site admin portal. It requires the lat/long in order to complete any edit. Not sure if we should create a separate GH issue for that or use this one too.

**Comment by arnoldnipper** [comment]
Let's stick with decimal

**Comment by arnoldnipper** [comment]
> Let's stick with decimal and use a [converter](https://www.rapidtables.com/convert/number/degrees-minutes-seconds-to-degrees.html)

Are you happy with that @peterhelmenstine? Reasons
- there are plenty of converters
- implementing just enlarges the code
- it's needed infrequently
- copying data from the converter to the AC interface is not hard

**Comment by peterhelmenstine** [comment]
Two issues here:

In regards to decimal formatting would be nice but not important enough to argue against.

In regards to an official address for a facility that hasn't been provided by the local government then that's still an issue which should probably be a differerent GH issue.

$0.02

**Comment by leovegoda** [comment]
The Product Committee has decided to close this issue. There was no agreement on the concept and the issue has not been discussed for six months or longer.
