### ISSUE TITLE
Remove white space from strings

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/peeringdb#971]
**Describe the bug**
Strings never start and end with white space

**To Reproduce**
Steps to reproduce the behaviour:
```
curl -sG https://www.peeringdb.com/api/fac --data-urlencode fields=zipcode | jq '[.data[] | select (.zipcode | test(".* $")) | .zipcode] | length'
9
```
There are tons more for every field in any object containing strings.

**Expected behaviour**
Strings never start and end with white space

**Who is affected by the problem?**
everyone

**What is the impact?**
matching strings is difficult

**Are there security concerns?**
no

**Are there privacy concerns?**
no

**What are the proposed actions?**
remove white space from strings in existing fields. Additionally, build an input filter which prevents white space at ^ and $

**What is the proposed priority?**
may be done any time

**Provide a rationale for any/all of the above**

**Additional context**
clean DB

@peeringdb/pc please +1 as this is really low-hanging fruit

**Comment by kaycliff** [comment]
+ 1

**Comment by grizz** [comment]
+1

We should add this to the save as well so it doesn't keep happening.

**Comment by arnoldnipper** [comment]
**Summary**
- remove white space from the start and end of any existing string field
- add a procedure to remove white space  from the start and end of any string field during input
