### ISSUE TITLE
Add 'Remove Peer' to object ix

### ISSUE THREAD

**Issue by happyhater** [peeringdb/peeringdb#973]
For peerings that are not active or they are leaving-- we should have an option to remove them w/out mailing peeringdb, in such way we can kept updated our exchanges in case if they have "Allow IXP Update" disabled.

**Comment by leovegoda** [comment]
@happyhater can you expand on this? Is the request related to support for the IX-F Member Export JSON Schema?

**Comment by arnoldnipper** [comment]
@happyhater, even when "Allow IXP Update" an IX-F import will notify the network. The implementation of the [DOTF Recommendations](https://docs.peeringdb.com/taskforce/dataownership/) is not yet fully carried out. Removing stalled networks after having been notified is still pending to be implemented.

For IXP not having IX-F exports, a "Remove Peer" would come in handy. I fully agree.

**Comment by happyhater** [comment]
My apologies,
I am new on PDB and I don't know all internal or public functions but I am requested this because my ix are having that Ghostpeer and they won't want to respond on their emails so in my opinion,

For IXPs that are managing a database or doing export of their members in format ix-f (json):
- After a notification of 3 x times the Ghostpeer are deleted automatically. (in such way we can prevent an malfunction ix-f.)

For those who won't kept a database or using json schema:
- Placing an "x" button right on the ASNs of Ghostpeer.

In this way can be reduced:
- Many requests to PDB staff
- Ghost peerings in ix

**Comment by netravnen** [comment]
1. Another way to go about it _could_ be to allow a ${Realpeer} to register IX Peering LAN IPv4 address.
2. Then *if* ${Ghostpeer} has the v4 address that was recently re-assigned to ${Realpeer} in the PeeringDB profile. But this information does not match the IX-F Members Export information. _But_ ASN of ${Realpeer} does.
   - Allow ${Realpeer} to create the connection between their network the $IX.
3. In the background automatically remove ${Ghostpeer} IPv4 from $IX LAN...?

**Comment by arnoldnipper** [comment]
Excellent idea, @netravnen. However, I think that should be a separate GH issue

**Comment by arnoldnipper** [comment]
#286
