### ISSUE TITLE
Create a "Wizards" framework for web forms

### ISSUE THREAD

**Issue by leovegoda** [peeringdb/peeringdb#974]
**Is your feature request related to a problem? Please describe.**
Creating entries for new organizations, networks, exchanges, and facilities requires users to iteratively create and edit multiple objects. While we have created some basic documentation (https://docs.peeringdb.com/howtos/) the process could be simplified through an interactive sequence of questions that lead the user through the complete setup process. 

This request is to create a framework for the creation and curation of wizards.

**Who is affected by the problem?**
Any new or non-expert user of PeeringDB's web interface.

**What is the impact?**

**Are there security concerns?**
No

**Are there privacy concerns?**
No

**Describe the solution you'd like**

1. Create a framework for a series of questions that gather all information required from a user to perform each step
2. The framework should allow the UI to present users with examples (text or images) to guide users where necessary 
3. The framework should allow users to complete when all required information is provided or continue to provide other information that is not required for the creation of the object(s)
4. The framework should allow syntactic validation of input where that is required
5. The framework should allow users to use the wizard to update an existing object, presenting paths for replacing information and paths for filling gaps

**Describe alternatives you've considered**
More complex documentation

**Could this feature request need support from the Admin Committee?**
This framework should allow us to create user interfaces that reduce the burden on the AC by integrating examples and explanation and validating syntax. 

**What is the proposed priority?**
This framework should be completed ahead of a UX refresh so we are in a position to get best value from that work.

**Provide a rationale for any/all of the above**
This framework should allow us to simplify the user experience and improve the overall quality of user supplied information through a guided path that presents simple questions, explains the rationale for required information, and presents examples where that is required.

**Additional context**
This is not a request to design and implement the wizards themselves but the creation of a framework upon which we can build wizards as needed. When the framework has been developed we would ideally create wizards for the creation and update of orgs, networks, exchanges, and facilities.

**Comment by arnoldnipper** [comment]
useful, but only gets a +1 from me if there are no other issues left. The current signup process is straightforward. Even for novices.
