### ISSUE TITLE
"Incomplete data" complainer for Peering Policy even with General Policy "None" or "Open"

### ISSUE THREAD

**Issue by kieber** [peeringdb/peeringdb#975]
**Describe the bug**
While being logged in and looking at a network I'm an admin for I get a "Some of the data on this page is incomplete, please update the fields marked with ! to improve data quality." complain banner, even if "General Policy" is set to "Open" or "No".  "Open" says, I'm peering with everybody, "No" says I don't have a written peering policy.  In both cases trying to pressure for a "Peering Policy" URL by showing the complaint banner seems kinda useless.

**Expected behavior**
"Some of the data on this page is incomplete, please update the fields marked with ! to improve data quality." complain banner should only be shown for missing "Peering Policy" URLs if "General Policy" is set to anything but "Open" or "No".

**Who is affected by the problem?**
Every admin

**What is the impact?**
Minor

**Are there security concerns?**
No

**Are there privacy concerns?**
No

**What are the proposed actions?**

**What is the proposed priority?**
low

**Provide a rationale for any/all of the above**

**Additional context**

**Comment by mcmanuss8** [comment]
Agreed, seems like a flaw. +1 from me

**Comment by arnoldnipper** [comment]
+1, i.e. remove warning if the field "Peering Policy" is left empty. Even if != "No" or "Open".

**Comment by vegu** [comment]
**summary**
- do not show missing data warning for empty **Peering Policy** field if **General Policy** is set to "Open" or "No"

**Comment by kieber** [comment]
I'm sorry to disappoint you, but this issue is not solved.  The warning still shows.
![Capture](https://github.com/peeringdb/peeringdb/assets/17052108/98d3150c-8bf8-4e35-bbde-9710a234ff5c)

**Comment by grizz** [comment]
@kieber This has not been deployed yet. It will be deployed to beta within the next 24 hours and production on 2024-06-05T04:00Z
