### ISSUE TITLE
AUP should include a contact email address

### ISSUE THREAD

**Issue by grizz** [peeringdb/peeringdb#976]
**Is your feature request related to a problem? Please describe.**
>Any request to pass on information to any other person or organization will be evaluated on the statement of purpose outlined by the requestor.

The AUP requires approval for data use, but does not say where to send requests.

**Who is affected by the problem?**
n/a

**What is the impact?**
n/a

**Are there security concerns?**
none

**Are there privacy concerns?**
none

**Describe the solution you'd like**
Add a sentence explaining how to request approval and where the requests should be sent.

**Describe alternatives you've considered**
n/a

**Could this feature request need support from the Admin Committee?**
It removes AC involvement.

**What is the proposed priority?**
not urgent

**Provide a rationale for any/all of the above**

**Additional context**

**Comment by arnoldnipper** [comment]
As this is not a separate document and embedded it shows the [support](mailto:support@peeringdb.com) contact email address on the footer.

However, when there should be a dedicated, different email address to send questions/complaints to (like with the privacy document), this issue makes sense. Probably, a PDF, like for the privacy document, would make more sense.

**Comment by grizz** [comment]
It was not at all clear to me... nor was it to the person who just emailed me personally :) The address to contact for those requests is stewards@ -- but yes, it would make sense to make a new alias for that.

So, add `aup@peeringdb.com` and alias it to stewards and add text clarifying.

@peeringdb/pc Give me a couple +1s here? :)

**Comment by arnoldnipper** [comment]
I would make it a full-blown PDF with a nice footer as in the privacy document

**Comment by leovegoda** [comment]
The Product Committee has decided to close this issue. There was no agreement on the concept and the issue has not been discussed for six months or longer.
