### ISSUE TITLE
Search field should operate on facility location

### ISSUE THREAD

**Issue by kieber** [peeringdb/peeringdb#978]
**Describe the bug**
Currently facilities cannot be searched by location.

**To Reproduce**
1. Type "dronten" in search box
2. You receive one hit in Facilities: "Solcon Datacenter Dronten"
3. You are missing "Serverius DC1" https://www.peeringdb.com/fac/857, which is also located in Dronten, it just doesn't have "Dronten" in ist name.

**Expected behavior**
At least for facilities the search term should additionally be matched against the city/Location.  For the example above I'd expect at least two hits:
"Solcon Datacenter Dronten"
"Serverius DC1"

**Who is affected by the problem?**
Everybody searching for a DC/Facility by city, if the facility operator failed to repeat the city in the facility name.

**What is the impact?**
Limitations in DC searches.

**Are there security concerns?**
No

**Are there privacy concerns?**
No

**What are the proposed actions?**

**What is the proposed priority?**
simply urgent/not

**Provide a rationale for any/all of the above**

**Additional context**

**Comment by arnoldnipper** [comment]
-1, that's what the Advanced Search is for

**Comment by grizz** [comment]
I agree to both -- will be fixed with the [2.28](https://github.com/peeringdb/peeringdb/milestone/50?closed=1) release on 2021-0721T0400 with location radius (advanced) search from #23
