### ISSUE TITLE
Automatic retrying of failed DeskPRO ticket creation

### ISSUE THREAD

**Issue by vegu** [peeringdb/peeringdb#982]
**Describe the bug**

Sometimes the DeskPRO API fails (see #981) and once it is fixed we currently have to manually re-queue those tickets to be sent out again, this currently requires intervention from the developers / ops to do.

We do a have a command that used to help with this, but it is broken and cumbersome to use and needs some re-factoring to be able to run in an automated matter.

**Who is affected by the problem?**

- AC waiting for failed tickets to be re-queued
- users waiting for their support tickets to be re-queued

**What is the impact?**

Currently after a DeskPRO API failure, once the issue is fixed, we have to wait for the developers to be available to re-queue the failed tickets

**Are there security concerns?**

no

**Are there privacy concerns?**

no

**What are the proposed actions?**

Fix the ticket requeuing command and make it usable in an automated fashion

**What is the proposed priority?**

unknown

**Comment by ccaputo** [comment]
+1.  This would be a good thing to have working again and after fixing, I envision it running hourly via cron on prodmaster and also emitting to stdout if any tickets are retried - even if successfully requeued - so that Ops has an additional view into whether any problems are ongoing.

**Comment by arnoldnipper** [comment]
+1

**Comment by ccaputo** [comment]
> +1 ... @ccaputo what is the reason/benefit of running it via cron. I understand the proposal that the tool will re-queue all tickets.

The tool @vegu mentions is manually run.  Once made to work again, I propose it get run hourly to pick up any crumbs that have fallen, per se, due to a failure to post to Deskpro, while at the same time providing an email alert when it has done anything.  This would add to the alerts provided by #981.

**Comment by arnoldnipper** [comment]
Running it per cron does not help if the failure is systematical.

**Comment by funkestefan** [comment]
An hourly run doesn't need someone to notice a failure and run it manually. Automate all the things and raise an alert if something is broken.

**Comment by arnoldnipper** [comment]
Failure modes are dupes or systematical. In both cases, a queue rerun doesn't help.

**Comment by ccaputo** [comment]
> Failure modes are dupes or systematical. In both cases, a queue rerun doesn't help.

I don't understand what you mean.  An example of how a re-run will help is if Deskpro goes down, thus ticket postings fail, and then Deskpro comes back up, resulting in ability of queued tickets to be posted.  Or another example is the 400 failure seen the other day - we would hear about the recurring issue much more quickly than we did.

**Comment by arnoldnipper** [comment]
> we would hear about the recurring issue much more quickly than we did.

That's why a created #981 ;-)

**Comment by ccaputo** [comment]
> > we would hear about the recurring issue much more quickly than we did.
> 
> That's why a created #981 ;-)

#981 addresses the code that handles the initial attempt to post a ticket to DeskPRO.  This issue #982 addresses a broken tool that needs to be refactored to handle the steps necessary to enable a re-queue of tickets.

**Comment by leovegoda** [comment]
The Product Committee has decided to close this issue. There was no agreement on the concept and the issue has not been discussed for six months or longer.
