### ISSUE TITLE
Allow REALPEER to overwrite GHOSTPEER netixlan entry, if asn and IPv6/v4 addresses matches the IX-F Members Export information

### ISSUE THREAD

**Issue by netravnen** [peeringdb/peeringdb#983]
1.  Allow a ${Realpeer} to register IX Peering LAN IPv4/v6 address.
2. Then *if* a ${Ghostpeer} has the IPv4/v6 address that was recently re-assigned to ${Realpeer} in the PeeringDB profile. But this information does not match the IX-F Members Export information. _But_ ASN and IPv6/v4 address(es) of ${Realpeer} does.
   - Allow ${Realpeer} to create the connection between their network the $IX.
3. In the background automatically remove ${Ghostpeer} IPv4/v6 from $IX LAN.
   - Optionally, shot an E-mail to ${Realpeer} and ${Ghostpeer} admins notifying them of this change... 🤔 So as to not silently hide the change from the affected network admins.

_Originally posted by @netravnen in https://github.com/peeringdb/peeringdb/issues/973#issuecomment-846392956_

_Clarification:_ Ghostpeer in this context refers to a network (ASN) that has recently disconnected from an IX LAN. But has not yet updated their PeeringDB record with this information. Leaving a stale netixlan entry in the networks (i.e. Ghostpeers) profile. Thereby preventing Realpeer to register the reassigned IP address.

**Comment by arnoldnipper** [comment]
+1

**Comment by peterhelmenstine** [comment]
Like this idea +1

**Comment by DarwinCosta** [comment]
+1

**Comment by grizz** [comment]
@netravnen Ghostpeer is defined as a peer on an IX that has IX-F memberlist yet doesn't list them?

**Comment by arnoldnipper** [comment]
>  Ghostpeer is defined as a peer on an IX that has IX-F memberlist yet doesn't list them?

Exactly, @grizz: there is an ok  `netixlan` object which `net_id` == id of the net question and `ix_id` == id of the ix in question. However, ix does not list the asn/net in their IX-F JSON.

**Comment by grizz** [comment]
+1

**Comment by grizz** [comment]
@peeringdb/pc need one more +1 please

**Comment by ynbrthr** [comment]
+1

**Comment by arnoldnipper** [comment]
> @peeringdb/pc need one more +1 please

Debatable whether this is an AC only issue. In that case, it already had consensus. Now, it has consensus from @peeringdb/pc as well :)
