### ISSUE TITLE
Add link to release notes to the footer of www.peeringdb.com

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/peeringdb#986]
**Is your feature request related to a problem? Please describe.**
As release notes are so important, they should be available from the footer on www.peeringdb.com. Currently, I 've to open a new website (if I'm lucky to know which one) and then make two additional clicks

**Who is affected by the problem?**
All users

**What is the impact?**
Direct access to the release notes

**Are there security concerns?**
no

**Are there privacy concerns?**
no

**Describe the solution you'd like**
Link to the release notes directly in the footer of www.peeringdb.com.  The perfect place would be "re.lea.se ([Release Notes](https://docs.peeringdb.com/release_notes/#release-2271))"

**Describe alternatives you've considered**
no

**Could this feature request need support from the Admin Committee?**
no

**What is the proposed priority?**
normal

**Provide a rationale for any/all of the above**
low hanging fruit

**Additional context**
none

**Comment by arnoldnipper** [comment]
@peeringdb/pc, low-hanging fruit imho. May I have +1's :)

**Comment by grizz** [comment]
+1, and quite easy

**Comment by ynbrthr** [comment]
+1

**Comment by leovegoda** [comment]
Good idea!

**Comment by vegu** [comment]
fixed in 9ebc176
