### ISSUE TITLE
Investigate and fix performance issue on organization page with lots of users / entities

### ISSUE THREAD

**Issue by vegu** [peeringdb/peeringdb#987]
**Describe the bug**

Some organization pages load significantly slower than others. There seems to be a scaling issue especially if there are many users affiliated with the organization. Load times of up to 30 seconds have been reported in some cases.  

**To Reproduce**

1. Log in as org / site administrator
2. Go to https://www.peeringdb.com/org/2

**Expected behavior**

More reasonable load times when viewing an organization page that has many users / entities under it.

**Who is affected by the problem?**

Users with admin permissions to an org with many users under it are affected the most. 

**What is the impact?**

While the organization view loads somewhat slow even for non admin users (4-5 seconds). Users with admin permissions may look at significantly longer load times if there are many users under the org.

**Are there security concerns?**

No

**Are there privacy concerns?**

No

**What are the proposed actions?**

Investigate cause and see if there are any scalability improvements to be made and fix the issue.

**What is the proposed priority?**

unknown

**Comment by peterhelmenstine** [comment]
+1 Noticeable lag

**Comment by leovegoda** [comment]
The Product Committee has decided to close this issue. There was no agreement on the concept and the issue has not been discussed for six months or longer.
