### ISSUE TITLE
Add per-org and per-user "ignorelist"

### ISSUE THREAD

**Issue by job** [peeringdb/peeringdb#993]
**Is your feature request related to a problem? Please describe.**

Some users use the PeeringDB web interface every day to discover new Facilities, IXPs, and Networks to interconnect with. Different users have different requirements, some users only wish to see search results from traditional 'larger' operations, other users wish to focus on interconnection hobby projects. 

Currently it is not possible to mark an object as something that in the future should not be included in search results.

**Are there privacy concerns?**

The list of objects to be ignored for each individual user, or ignored by every user in an organization should be confidential. For example it would be embarrassing for me if the list of objects I want to ignore becomes public.  

**Describe the solution you'd like**

In the UI at each object and at each organization there should be a UI element "add to ignorelist", equivalent API calls should also exist. If the user presses that button, the object is added to their personal ignorelist. It should be possible to see an overview of 'ignored' in the users profile. It should be possible to unignore objects/orgs. 

**Describe alternatives you've considered**

An alternative approach has been outlined in #992 , but I believe the downside is that not everyone will use the checkbox as appropriate, where as with a per-user ignorelist the user is in full control regardless of checkboxes being set or not.

**Could this feature request need support from the Admin Committee?**

AC needs to be aware that this feature exists, and that some users in the future will ask "I cannot find so and so on PeeringDB", and be taught that in the past they themselves (or a coworker) added something to an ignore list.

**What is the proposed priority?**

medium

**Comment by leovegoda** [comment]
If we went ahead with this approach and the search returned _x_ results to show plus _y_ results to ignore, it might be helpful to add a comment at the bottom of the shown results with text like: 

"_y_ results hidden based on ignore list. Click here to show those results anyway." 

That would help users quickly identify where they had accidentally added an entry to their ignore list that they would prefer to remove. We could also add a link to a page where a user to manage their ignore list.

**Comment by mcmanuss8** [comment]
I don't think this will solve the complaints from the community. While ignoring an object when it comes up will solve the problem for that object, it becomes whack-a-mole.
What I'm hearing users want is a way to describe classifications of objects that are uninteresting to them and ignore them based on those classifications.

**Comment by job** [comment]
@mcmanuss8 the database is 'self-classification', all data is user submitted. This means that there always will be situations where the _viewer_ disagrees with (some) information submitted by someone else. We can help the _viewer_ ignore information they do not like to see, by making a button to make it so.

Many organizations who automate around PeeringDB have the concept of a local 'ignorelists' to increase productivity. For those unable to locally filter out search results they don't find interesting, a per-user / per-org filter list function inside PeeringDB might be helpful.

**Comment by leovegoda** [comment]
The Product Committee has decided to close this issue. There was no agreement on the concept and the issue has not been discussed for six months or longer.
