### ISSUE TITLE
500 Error during login for 2FA enabled accounts with unverified email address

### ISSUE THREAD

**Issue by vegu** [peeringdb/peeringdb#996]
**Describe the bug**

A 2FA enabled account may raise a 500 internal error during login if the email address of the account is not verified.

**To Reproduce**

1. Enable 2FA
2. Change email address (and do not verify it)
3. Logout
4. Login 

**Expected behavior**

The login should proceed normally. 

**Who is affected by the problem?**

Users that have 2FA enabled on their accounts and change their email address and forget to verify the new address.

**Are there security concerns?**

none with the bug itself, some considerations for the fix:

The email address is used as a backup method for them to restore access to their account in case they lose their 2FA device. 

Email being verified is probably irrelevant for the 2FA process from a security standpoint - either the user has access to the email address and can use it to restore access, or they don't.

Alternatively, we disable email restore if the email address isn't verified.

**Are there privacy concerns?**

no

**What is the proposed priority?**

unknown

**Comment by arnoldnipper** [comment]
Routed through to 3a as this clearly is a bug and happens every now and then. Should be fixed asap

**Comment by vegu** [comment]
**summary**

- fix 500 error on 2FA enabled user login, if the user has an unverified email address
