### ISSUE TITLE
Allow organizations to require affiliated users to enable 2FA

### ISSUE THREAD

**Issue by leovegoda** [peeringdb/peeringdb#997]
**Is your feature request related to a problem? Please describe.**
Organizations increasingly require 2FA to be enabled on all services where it is available. Empowering organizations to require affiliated users to enable 2FA would give them them a tool to implement an organizational security policy.

**Who is affected by the problem?**
Organizations represented in PeeringDB with an internal security policy requiring 2FA to be enabled but with one or more users relying on password alone.

**What is the impact?**
This feature should help these organizations implement part of an organizational security policy, where it exists, though a PeeringDB configuration option. In the longer term, this should help bolster the quality of data published in PeeringDB by better securing more user accounts.

**Are there security concerns?**
This ought to improve security.

**Are there privacy concerns?**
I do not believe there are.

**Describe the solution you'd like**

1. Show a 2FA ON icon/badge next to each user with 2FA enabled in the user listing table. Show a 2FA OFF  icon/badge next to each user without 2FA enabled in the user listing table. Consider adding colors in addition to words to help many people quickly pick out the users who have not enabled 2FA.
2. Create an option in the organization user permissions control that can require all affiliated users to have 2FA enabled
3. Default the switch to OFF (or 2FA Not Required)
4. Allow organizations to move the switch to ON (or 2FA Required) even if there are affiliated users who have not activated 2FA
5. When set to ON (or 2FA Required) do not allow the Admin User(s) to approve affiliation requests from user accounts that have not enabled 2FA and show a concise message saying something like "User X requests affiliation with Organization Y but has not enabled 2FA. Org Y does not allow users to affiliate unless they have enabled 2FA on their account. You will be able to approve an affiliation request from User X, and assign permissions to them, when they have enabled 2FA"
6. Add a prominent alert when a grandfathered user logs in if their organization requires 2FA and they have not enabled it
7. Send the Admin User(s) a list of affiliated users who have not enabled 2FA once a month 

**Describe alternatives you've considered**
An alternative implementation choice might be to allow an organization to move the switch to ON (or 2FA Required) at the cost of removing all create, update, and delete permissions from affiliated accounts that have not already enabled it. This is a more disruptive approach and could create additional work for admins if the option is enabled by accident. Organizations with stricter policies can manually drop all permissions from users that have not enabled 2FA if they wish, which is why I did not request this approach.

**Could this feature request need support from the Admin Committee?**
AC insight welcome

**What is the proposed priority?**
During 2021Q3 or early 2021Q4.

**Provide a rationale for any/all of the above**
We encourage the use of 2FA and it is good to provide the organizations tools to better implement their security policies. Over time, this should help us maintain or improve data quality.

**Additional context**
This is part of a themed set of issues intended to help organizations better control how they are represented in PeeringDB. In addition to implementing this feature in the server, we will need to actively document its benefits and implementation and communicate its existence to users.

**Comment by arnoldnipper** [comment]
Makes absolute sense to me. Hence, a strong +1. @peeringdb/pc, what do you think?

**Comment by grizz** [comment]
+1

**Comment by arnoldnipper** [comment]
@peeringdb/pc, could we please have another +1

**Comment by martinhannigan** [comment]
Not on the pc but +1. Good idea.

**Comment by martinhannigan** [comment]
Id also add a step further clarification to allow an orgs security policy
to map to pdb:

not allowed
allowed - default
required

Thanks

**Comment by job** [comment]
+1 - good idea, would love to use this feature

**Comment by grizz** [comment]
@martinhannigan What would be the point or benefit of making 2FA not allowed?

**Comment by martinhannigan** [comment]
My impression is that a feature such as this would be driven by company
security policy. The issue narrative says "empowering organizations".
Providing the full range of options would align with that and allow
organizations to select their preference. No one has actually said what the
2FA method would be (unless I misread?). It also implies an "off" function
which maps to "not allowed". If I'm the security admin and PDB is offering
a useful security tool I guess it would be most useful if I can decide if
we should use it or not. I'm always a fan of let the organization decide
and give them the option to decide not to use it at all.

**Comment by job** [comment]
@martinhannigan 2FA is an optional security feature, this means that companies can optionally require it, but those companies should not be positioned such that they can disenfranchise/discourage users from setting up 2FA. 

The choice is with the user to set 2FA up or not, the choice is with organisations whether they require it or not.

**Comment by martinhannigan** [comment]
Fair enough, but the issue did say organization. I'm not certain I agree
that PDB should set security policy for an org which is why I suggested the
off button. If the org owns the access then shouldn't they be the ultimate
authority?

YMMV,

-M<

**Comment by mcmanuss8** [comment]
Orgs will generally require a certain bar of security, but not mandate less than a certain bar. In other words, choose a strong password, but if your password is too strong you usually won't get pushback on it. Same thing here.

+1 on making this an option orgs can set to true. If not set, it can still be setup on a per user basis of course

**Comment by arnoldnipper** [comment]
> The choice is with the user to set 2FA up or not, the choice is with organisations whether they require it or not.

+100

**Comment by martinhannigan** [comment]
On Sun, Aug 22, 2021 at 3:41 PM mcmanuss8 ***@***.***> wrote:

> Orgs will generally require a certain bar of security, but not mandate
> less than a certain bar. In other words, choose a strong password, but if
> your password is too strong you usually won't get pushback on it. Same
> thing here.
>
> +1 on making this an option orgs can set to true. If not set, it can still
> be setup on a per user basis of course
>
>
>
I'm not against 2FA. I'm not in favor of PDB telling orgs how they should
map security policy. I could envision a scenario where an org does not want
their employees using a type of 2FA because either its not supported, there
is some -1 day disclosed, company phones and costs for SMS, etc. etc. Not
everyone is sane. Or insane. :-) Seems like allowing for "false" for admin
may be a compromise. Anyhow. +1 for 2FA.

**Comment by vegu** [comment]
**summary**

- add a `require_2FA` option to `organization` model and  API serializer (`bool`, default to `False`)
- if `require_2FA` is `True` for an organization do not allow administrators of that org to approve users affiliation requests for users with 2FA disabled.
- allow orgs to switch their 2FA requirement to `True` even if they have users in org that are not 2FA enabled
- Add a prominent alert when a grandfathered user logs in if their organization requires 2FA and they have not enabled it
- display 2FA enabled / disabled badges in the user listing for an organization (green 2FA badge for enabled, colorless NO 2FA badge for disabled)
- regular (monthly) notifications to org admins for organizations that require 2FA informing them of users that don't have 2FA enabled

@peeringdb/pc what happens if a user turns off 2FA when they are in an org that requires 2FA?

**Comment by leovegoda** [comment]
> @peeringdb/pc what happens if a user turns off 2FA when they are in an org that requires 2FA?

Good question. I think there's a range of options:

- Notify the admin users that a user has disabled 2FA but do not change anything
- Drop permissions from the user (and possibly notify the admin users)
- Disable the ability to turn off 2FA (this is probably not ideal)

My perspective is that this issue is intended to empower orgs and not limit or encumber them, so I'd suggest a simple notification.

**Comment by mcmanuss8** [comment]
> Notify the admin users that a user has disabled 2FA but do not change anything
> Drop permissions from the user (and possibly notify the admin users)

I think a combination of these two. An ideal flow would do something like:

"The following users affiliated with your organization do not have 2FA turned on:

<list of users>

Would you like to drop their affiliation or leave it in place? If you drop affiliations, they will not be able to re-affiliate until they have 2FA turned on. 

[ Drop Affiliations ] [ Leave them Affiliated ] [ Cancel 2FA Requirement] 
"

A safety check for the Drop button might be to make sure the admin making the change has 2FA turned on so they don't lock themselves out. 

Users can then decide if they want to drop and make people re-apply (drop) or handle turning it on out of band (leave)

**Comment by arnoldnipper** [comment]
+1 for what @mcmanuss8 proposes

**Comment by grizz** [comment]
+1 to @mcmanuss8's proposal as well. I'd like to clarify the wording of the choices to be

`[Drop $user affiliation] [Leave $user affiliated] [Disable 2FA Requirement]`

Each option should have a confirm dialog explaining in a bit more detail, respectively:

`This will completely remove $user from $organization`
`This will allow the user to keep all privileges within $organization, which conflicts with your 2FA Policy`
`This will turn off the 2FA requirement for $organization, users will not need to use 2FA to login`

**Comment by arnoldnipper** [comment]
A confirming dialogue is great!

> `This will allow the user to keep all privileges within $organization, which conflicts with your 2FA Policy`

IANANS ... however, for me it would be unclear what conflicts with the 2FA policy. Suggestions:

`This will allow the user to keep all privileges within $organization. This conflicts with your 2FA Policy`
`This will allow the user to keep all privileges within $organization, and conflicts with your 2FA Policy`
